//! **The module bridge**: a v1 plugin reading and writing rows from inside an
//! installed module (the milestone "the v1 `Table` API", phase 5).
//!
//! This is the milestone's definition of done, at the end it was hardest to
//! reach. `sc-expr` proves the lowering with a spy and `sc-api` proves that the
//! plans write a real database; what is proved here is the third thing, which
//! neither of those can: that a **module** — a package on its own Deno worker, in
//! its own isolate, with its own permission set — can ask this server for rows at
//! all, and gets them under the authority of the trigger that fired it.
//!
//! The mechanism has two halves and both are asserted here:
//!
//! - **the ask channel** (§3). `__scAsk` out of the worker, routed to the caller
//!   of the call it belongs to (which is where a `CodeHosts` is borrowed),
//!   `Control::Answer` back in. Two module calls in flight at once are two
//!   callers, and the test that runs them concurrently is what says so.
//! - **the schema snapshot** (§2). `Table.findOne("books")` answers
//!   *synchronously*, because the tables crossed with the call rather than being
//!   asked for — which is what eight years of v1 plugins assume on their first
//!   line.
//!
//! And the boundary: a module's `onLoad` has no caller, so its `Table` refuses by
//! name and the module still loads with its actions intact.
#![cfg(feature = "deno-host")]
#![allow(clippy::unwrap_used, clippy::expect_used)]
use crate::common;

use std::sync::Arc;

use common::{fixture, have_npm, surfaces, temp_root};
use sc_action::{ActionContext, ActionRegistry, Event, EventKind};
use sc_catalog::{Catalog, bootstrap_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_module::{
    Installer, Module, ModuleHost, ModuleSet, ModuleSource, bootstrap_modules, save_module,
};
use sc_test_harness::TestDb;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

/// A library with a **key** in it, because `getField("author").is_fkey` is one of
/// the four things the definition of done names.
const SCHEMA: &str = "\
    CREATE TABLE authors (id bigint generated by default as identity primary key, \
        name text); \
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text, pages bigint, author bigint references authors(id), \
        read boolean default false); \
    INSERT INTO authors (name) VALUES ('Herbert'), ('Austen'); \
    INSERT INTO books (title, pages, author, read) VALUES \
        ('Dune',      412, 1, false), \
        ('Emma',      474, 2, false), \
        ('Ilium',     576, 1, false), \
        ('Nostromo',  320, 1, false);";

/// The catalog over a fresh database, with the module store bootstrapped.
async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    bootstrap_table_meta(&cat).await?;
    bootstrap_modules(&cat).await?;
    Ok(cat)
}

/// Install the fixture, store its row, and load the set into a registry — the
/// whole path a server takes, so what is under test is the thing that ships.
async fn install(
    cat: &Catalog,
    tag: &str,
) -> (Installer, Arc<ModuleHost>, ActionRegistry, ModuleSet) {
    let root = temp_root(tag);
    let installer = Installer::new(&root);
    let package = installer
        .install(
            ModuleSource::Local,
            &fixture("table-module").display().to_string(),
        )
        .await
        .unwrap_or_else(|e| panic!("installing the table fixture: {e}"));
    let mut module = Module::new(
        &package.name,
        ModuleSource::Local,
        fixture("table-module").display().to_string(),
    );
    module.version = Some(package.version);
    save_module(cat, &module).await.unwrap();
    let host = Arc::new(ModuleHost::new(&root));
    let mut registry = ActionRegistry::new();
    let set = ModuleSet::load(cat, &host, &installer, &surfaces(), &mut registry)
        .await
        .unwrap();
    (installer, host, registry, set)
}

/// Run one of the module's actions the way the dispatcher does.
async fn run(
    registry: &ActionRegistry,
    cat: &Catalog,
    action: &str,
    config: Attrs,
) -> Result<Json> {
    let event = Event::new(EventKind::None);
    let handler = registry.require(action)?;
    let mut ctx = ActionContext::new(cat, &event, &config, "a trigger");
    handler.run(&mut ctx).await
}

/// **The definition of done.** Saltcorn 1's six lines, inside an installed v1
/// plugin, against a real database — and the plugin never learns it is not
/// running on Saltcorn 1.
#[tokio::test]
async fn a_v1_plugin_reads_and_writes_rows_from_inside_a_module() {
    skip_without!(have_npm(), "npm is not on the PATH");
    let db = TestDb::new().await.unwrap();
    let cat = setup(&db).await.unwrap();
    let (installer, host, registry, set) = install(&cat, "v1-table-done").await;

    let answer = run(&registry, &cat, "v1_read_write", Attrs::new())
        .await
        .expect("the module's own six lines");

    // Metadata, synchronously: none of this cost a host call, because the schema
    // crossed with the call (§2).
    assert_eq!(answer["name"], json!("books"));
    assert_eq!(answer["pk"], json!("id"));
    assert_eq!(answer["author_is_key"], json!(true), "{answer}");
    assert_eq!(answer["author_target"], json!("authors"));
    assert!(
        answer["fields"]
            .as_array()
            .unwrap()
            .iter()
            .any(|f| f == &json!("title")),
        "{answer}"
    );

    // The read: v1's `where` and `selopts`, lowered in the module's own isolate
    // and answered by this server.
    assert_eq!(answer["titles"], json!(["Dune", "Emma", "Ilium"]));

    // And the write landed, through the row layer — so a trigger would have seen
    // it, which is the whole reason to have the method rather than a statement.
    let read = db
        .client()
        .await
        .unwrap()
        .query("SELECT title FROM books WHERE read ORDER BY title", &[])
        .await
        .unwrap()
        .iter()
        .map(|row| row.get::<_, String>(0))
        .collect::<Vec<_>>();
    assert_eq!(read, vec!["Dune".to_owned()]);

    // The module is loaded and the only thing wrong with it is its own `onLoad`
    // (the next test).
    let loaded = set.get("@saltcorn-test/table").unwrap();
    assert!(loaded.is_loaded());

    // **Again**, which is the assertion that §2's caching works: the first call
    // carried the snapshot's JSON, and this one carries only the generation. A
    // worker that had not kept it would fail naming the generation it has not
    // got, rather than quietly answering an empty schema.
    let again = run(&registry, &cat, "v1_read_write", Attrs::new())
        .await
        .expect("the second firing, with the schema already on the worker");
    assert_eq!(again["titles"], json!(["Dune", "Emma", "Ilium"]));

    host.shutdown().await;
    let _ = std::fs::remove_dir_all(installer.root());
}

/// §5.5: a module's `onLoad` has no caller, so the `Table` it reaches for refuses
/// **naming why** — and the module still loads, with every action working.
///
/// A load is where a v1 plugin builds the state its actions close over, and it is
/// called while the module is being installed: there is no `CodeHosts` borrowed
/// on anybody's stack, so there is no authority to lend. A `Table.findOne` that
/// answered `undefined` there would have the plugin compute the wrong answer
/// inside its own initialisation.
#[tokio::test]
async fn a_modules_on_load_cannot_reach_the_database_and_says_so() {
    skip_without!(have_npm(), "npm is not on the PATH");
    let db = TestDb::new().await.unwrap();
    let cat = setup(&db).await.unwrap();
    let (installer, host, registry, set) = install(&cat, "v1-table-onload").await;

    let loaded = set.get("@saltcorn-test/table").unwrap();
    let issues = loaded.issues.join(" | ");
    assert!(issues.contains("onLoad"), "{issues}");
    assert!(issues.contains("Table.findOne"), "{issues}");
    assert!(
        issues.contains("authority of the call"),
        "the refusal has to say why, not merely that: {issues}"
    );

    // Reported, not fatal: the actions are all there and they work.
    assert!(registry.get("v1_read_write").is_some());
    let answer = run(&registry, &cat, "v1_load_failure", Attrs::new())
        .await
        .unwrap();
    // …and the two pure `Field` statics worked there, because there is no
    // authority in a string function.
    assert_eq!(
        answer["load_failure"],
        json!("onLoad reached the database (page count)")
    );

    // And so does the one that reads rows, from the same module whose load threw.
    let read = run(&registry, &cat, "v1_metadata", Attrs::new())
        .await
        .unwrap();
    assert_eq!(
        read["missing"],
        json!(true),
        "a table nobody has is undefined"
    );
    assert_eq!(read["label"], json!("page count"));
    assert!(
        read["tables"]
            .as_array()
            .unwrap()
            .iter()
            .any(|t| t == &json!("authors")),
        "{read}"
    );
    // `_fd_*` is this server's own storage and is not a plugin's business.
    assert!(
        !read["tables"]
            .as_array()
            .unwrap()
            .iter()
            .any(|t| t.as_str().is_some_and(|n| n.starts_with("_fd_"))),
        "{read}"
    );

    host.shutdown().await;
    let _ = std::fs::remove_dir_all(installer.root());
}

/// §5.6: **two module calls in flight at once**, each with asks of its own.
///
/// The ask channel is routed by the id of the call it belongs to, because that is
/// what says whose authority it runs under — so the interesting failure is two
/// calls, since one cannot tell a right answer from a lucky one. The slow action
/// sleeps before reading, so its ask is genuinely served while the other module
/// call is inside the isolate.
#[tokio::test]
async fn two_module_calls_asking_at_once_each_get_their_own_answer() {
    skip_without!(have_npm(), "npm is not on the PATH");
    let db = TestDb::new().await.unwrap();
    let cat = setup(&db).await.unwrap();
    let (installer, host, registry, _set) = install(&cat, "v1-table-concurrent").await;

    let mut slow = Attrs::new();
    slow.insert("delay_ms".into(), json!(200));
    let mut inserted = Attrs::new();
    inserted.insert("title".into(), json!("Solaris"));

    // Started together, on the one worker the module is pinned to.
    let (slow, quick, parallel) = tokio::join!(
        run(&registry, &cat, "v1_slow_read", slow),
        run(&registry, &cat, "v1_insert", inserted),
        run(&registry, &cat, "v1_parallel_reads", Attrs::new()),
    );
    let slow = slow.expect("the slow read");
    let quick = quick.expect("the insert");
    let parallel = parallel.expect("two reads at once");

    assert_eq!(slow["waited"], json!(true));
    assert!(
        slow["titles"]
            .as_array()
            .unwrap()
            .iter()
            .any(|t| t == &json!("Dune")),
        "{slow}"
    );
    // The insert answered its own primary key, not the other call's rows.
    assert!(quick["id"].as_i64().unwrap() >= 5, "{quick}");
    // And two asks from **one** call are served concurrently rather than in
    // turn, which is why the caller keeps a set of them in flight.
    assert_eq!(parallel["long"], json!(3));
    assert!(parallel["all"].as_i64().unwrap() >= 4, "{parallel}");

    let titles = db
        .client()
        .await
        .unwrap()
        .query("SELECT count(*) FROM books WHERE title = 'Solaris'", &[])
        .await
        .unwrap();
    assert_eq!(titles[0].get::<_, i64>(0), 1, "the module's insert landed");

    host.shutdown().await;
    let _ = std::fs::remove_dir_all(installer.root());
}

/// §5.2: a worker that dies with a read in flight fails the call **by name**, and
/// the module works again on the next one.
///
/// The dangerous version of this is silence: an ask whose answer never arrives
/// leaves a module awaiting a promise nothing will settle, and the caller finds
/// out two minutes later from its wall clock. So the ask's caller is the reply
/// channel's caller, and when the worker takes itself down both end together.
#[tokio::test]
async fn a_worker_that_dies_with_a_read_in_flight_fails_the_call_by_name() {
    skip_without!(have_npm(), "npm is not on the PATH");
    let db = TestDb::new().await.unwrap();
    let cat = setup(&db).await.unwrap();
    let (installer, host, registry, _set) = install(&cat, "v1-table-exit").await;

    let err = run(&registry, &cat, "v1_read_then_exit", Attrs::new())
        .await
        .expect_err("the worker took itself down");
    let message = err.to_string();
    assert!(
        message.contains("process.exit(4)"),
        "the call has to name what stopped it: {message}"
    );

    // And the module is back on a fresh worker with its load replayed, so the
    // next read works — a dead worker costs one call, not the module.
    let answer = run(&registry, &cat, "v1_metadata", Attrs::new())
        .await
        .expect("the module is back");
    assert_eq!(answer["missing"], json!(true));

    host.shutdown().await;
    let _ = std::fs::remove_dir_all(installer.root());
}

/// A method v1 has and this server refuses keeps refusing **through the real
/// class** — the refusal tier is `v1_api.js`'s one list, and a module reaches it
/// the same way a code body does.
///
/// And a module **function** cannot reach the database at all: it is hoisted into
/// formulas, so it is called with nobody's authority. Both are named refusals
/// rather than silences, which is the whole of §9.
#[tokio::test]
async fn what_a_module_may_not_do_is_refused_by_name() {
    skip_without!(have_npm(), "npm is not on the PATH");
    let db = TestDb::new().await.unwrap();
    let cat = setup(&db).await.unwrap();
    let (installer, host, registry, set) = install(&cat, "v1-table-refusals").await;

    let err = run(&registry, &cat, "v1_schema_edit", Attrs::new())
        .await
        .expect_err("schema editing is not on offer");
    let message = err.to_string();
    assert!(message.contains("add_unique_constraint"), "{message}");
    assert!(message.contains("introspects"), "{message}");
    // The module's fault to the admin, not Saltcorn's (§16's split).
    assert_eq!(err.kind(), sc_error::ErrorKind::Application);

    // A function is called from inside a formula, which has no authority to lend.
    let loaded = set.get("@saltcorn-test/table").unwrap();
    assert!(
        loaded
            .manifest
            .as_ref()
            .unwrap()
            .functions
            .iter()
            .any(|f| f.name == "v1_table_from_a_function")
    );
    let err = host
        .call(
            "@saltcorn-test/table",
            "v1_table_from_a_function",
            Vec::new(),
            sc_module::CallHosts::default(),
        )
        .await
        .expect_err("a function has no caller to borrow from");
    let message = err.to_string();
    assert!(message.contains("Table.findOne"), "{message}");
    assert!(message.contains("module function"), "{message}");

    host.shutdown().await;
    let _ = std::fs::remove_dir_all(installer.root());
}
