//! Library items round-tripping through `_fd_library` against a real Postgres
//! (TODO "The builder" Phase 1).
//!
//! What only a database can settle: that an item comes back as it was saved,
//! that a name is unique per application, that only a Saltcorn UI application
//! may write one, that deleting an application takes its library, that in-place
//! updates are all or none, and that references and the generation see the
//! library.

use std::sync::Arc;

use sc_app::{AppId, Application, FrameworkRef, save_application};
use sc_catalog::{Catalog, SharedTx, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;
use sc_viewpattern::{
    LibraryItem, LibraryItemId, LibraryReferences, LibraryUpdate, Page, View, ViewSets,
    apply_library_updates, apply_library_updates_in, bootstrap,
    delete_application_views_pages_and_library, delete_library_item, install_saltcorn_ui,
    list_library, load_library_item, save_library_item, save_view,
};
use serde_json::{Value as Json, json};

/// A catalog over a per-test database with a `books` table, the roles,
/// applications and file-store tables, and this crate's three tables.
async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE books (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    sc_auth::bootstrap(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    sc_catalog::bootstrap_file_stores(&catalog).await?;
    sc_catalog::save_file_store(&catalog, &sc_files::FileStoreDef::local("apps", "/srv/x")).await?;
    bootstrap(&catalog).await?;
    bootstrap(&catalog).await?;
    install_saltcorn_ui()?;
    Ok(catalog)
}

/// A Saltcorn UI application over `books`.
async fn application(catalog: &Catalog, name: &str, subdomain: &str) -> Result<AppId> {
    let app = Application::new(name, subdomain, FrameworkRef::new("saltcorn-ui"))
        .with_table(TableId("books".to_owned()));
    Ok(save_application(catalog, &app).await?.id)
}

/// An application whose framework is `code`, which has no library.
async fn code_application(catalog: &Catalog) -> Result<AppId> {
    let app = Application::new(
        "Code",
        "code",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh"),
    )
    .with_table(TableId("books".to_owned()));
    Ok(save_application(catalog, &app).await?.id)
}

fn header(app: AppId) -> LibraryItem {
    LibraryItem::new(app, "Book header")
        .icon("fas fa-heading")
        .layout(json!({ "type": "blank", "contents": "Header", "textStyle": "h1" }))
}

/// A `library` segment placing `item`, with one field slot, as v1's builder
/// writes it.
fn placing(item: &LibraryItem) -> Json {
    json!({
        "type": "library",
        "library_id": item.id.0.to_string(),
        "slots": [{ "type": "field", "field_name": "title", "fieldview": "as_text" }],
    })
}

fn show_books(app: AppId, layout: Json) -> View {
    View::new(app, "Show Books", "Show", "books").configuration(
        json!({ "layout": layout, "columns": [] })
            .as_object()
            .cloned()
            .unwrap(),
    )
}

#[tokio::test]
async fn a_library_item_round_trips_updates_and_deletes() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;

    let mut item = header(app).description("The title card");
    item.attributes.insert("note".to_owned(), json!(1));
    save_library_item(&catalog, &item).await?;
    assert_eq!(
        load_library_item(&catalog, app, item.id).await?,
        Some(item.clone())
    );

    // An update in place: same id, new name and icon.
    let mut renamed = item.clone();
    renamed.name = "Title card".to_owned();
    renamed.icon = String::new();
    save_library_item(&catalog, &renamed).await?;
    let footer = LibraryItem::new(app, "Footer");
    save_library_item(&catalog, &footer).await?;
    // Ordered by name.
    assert_eq!(
        list_library(&catalog, app).await?,
        vec![footer.clone(), renamed.clone()]
    );

    assert!(delete_library_item(&catalog, app, renamed.id).await?);
    assert!(!delete_library_item(&catalog, app, renamed.id).await?);
    assert_eq!(load_library_item(&catalog, app, renamed.id).await?, None);
    assert_eq!(list_library(&catalog, app).await?, vec![footer]);
    Ok(())
}

#[tokio::test]
async fn a_name_is_unique_per_application_and_an_item_stays_in_its_own() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let one = application(&catalog, "One", "one").await?;
    let two = application(&catalog, "Two", "two").await?;

    save_library_item(&catalog, &header(one)).await?;
    let msg = save_library_item(&catalog, &header(one))
        .await
        .unwrap_err()
        .to_string();
    assert!(
        msg.contains("`One` already has a library item named `Book header`"),
        "{msg}"
    );

    // Another application may hold the same name.
    let theirs = header(two);
    save_library_item(&catalog, &theirs).await?;

    // An item is not found through, nor moved into, another application.
    assert_eq!(load_library_item(&catalog, one, theirs.id).await?, None);
    let mut moved = theirs.clone();
    moved.application = one;
    moved.name = "Moved".to_owned();
    let msg = save_library_item(&catalog, &moved)
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("another application"), "{msg}");

    let msg = save_library_item(&catalog, &LibraryItem::new(one, " padded"))
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("whitespace"), "{msg}");

    assert_eq!(list_library(&catalog, one).await?.len(), 1);
    assert_eq!(list_library(&catalog, two).await?, vec![theirs]);
    Ok(())
}

#[tokio::test]
async fn only_a_saltcorn_ui_application_writes_a_library() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let code = code_application(&catalog).await?;
    let names_code = |msg: String| {
        assert!(
            msg.contains("framework `code`") && msg.contains("`saltcorn-ui`"),
            "{msg}"
        );
    };

    names_code(
        save_library_item(&catalog, &header(code))
            .await
            .unwrap_err()
            .to_string(),
    );
    names_code(
        delete_library_item(&catalog, code, LibraryItemId::new())
            .await
            .unwrap_err()
            .to_string(),
    );
    names_code(
        apply_library_updates(&catalog, code, &[])
            .await
            .unwrap_err()
            .to_string(),
    );
    // Asking is not wrong: it has an empty library.
    assert!(list_library(&catalog, code).await?.is_empty());
    Ok(())
}

#[tokio::test]
async fn deleting_an_application_deletes_its_library_and_no_other() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let one = application(&catalog, "One", "one").await?;
    let two = application(&catalog, "Two", "two").await?;
    save_library_item(&catalog, &header(one)).await?;
    save_view(&catalog, &show_books(one, json!({}))).await?;
    let kept = header(two);
    save_library_item(&catalog, &kept).await?;

    delete_application_views_pages_and_library(&catalog, one).await?;
    assert!(list_library(&catalog, one).await?.is_empty());
    assert!(sc_viewpattern::list_views(&catalog, one).await?.is_empty());
    assert_eq!(list_library(&catalog, two).await?, vec![kept]);
    Ok(())
}

#[tokio::test]
async fn library_updates_are_all_or_none() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;
    let other = application(&catalog, "Other", "other").await?;
    let item = header(app);
    save_library_item(&catalog, &item).await?;
    let foreign = header(other);
    save_library_item(&catalog, &foreign).await?;
    let edited = json!({ "type": "blank", "contents": "Edited" });

    // One good update and one naming another application's item: refused by
    // the id, and the good one is not applied.
    let msg = apply_library_updates(
        &catalog,
        app,
        &[
            LibraryUpdate {
                library_id: item.id,
                layout: edited.clone(),
            },
            LibraryUpdate {
                library_id: foreign.id,
                layout: edited.clone(),
            },
        ],
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(
        msg.contains(&foreign.id.0.to_string()) && msg.contains("`BooksDB`"),
        "{msg}"
    );
    assert_eq!(
        load_library_item(&catalog, app, item.id)
            .await?
            .unwrap()
            .layout,
        item.layout
    );

    // Inside a caller's transaction, a rollback discards the edit…
    let update = [LibraryUpdate {
        library_id: item.id,
        layout: edited.clone(),
    }];
    let tx = SharedTx::begin_primary(&catalog)?;
    apply_library_updates_in(&tx, &catalog, app, &update).await?;
    tx.rollback().await?;
    assert_eq!(
        load_library_item(&catalog, app, item.id)
            .await?
            .unwrap()
            .layout,
        item.layout
    );

    // …and on its own, it is applied.
    apply_library_updates(&catalog, app, &update).await?;
    assert_eq!(
        load_library_item(&catalog, app, item.id)
            .await?
            .unwrap()
            .layout,
        edited
    );
    Ok(())
}

#[tokio::test]
async fn references_run_both_ways_through_nested_items_and_writes_move_the_generation() -> Result<()>
{
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;
    let sets = ViewSets::new();
    let before = sets.get(&catalog, app).await?;

    // `Card` places `Book header` in a slot; `Loop` places itself.
    let book_header = header(app);
    let card = LibraryItem::new(app, "Card").layout(json!({
        "type": "container",
        "contents": { "type": "library", "library_id": "not-a-uuid", "slots": [placing(&book_header)] },
    }));
    let mut looped = LibraryItem::new(app, "Loop");
    looped.layout =
        json!({ "above": [{ "type": "library", "library_id": looped.id.0.to_string() }] });
    let unused = LibraryItem::new(app, "Unused");
    for item in [&book_header, &card, &looped, &unused] {
        sets.save_library_item(&catalog, item).await?;
    }
    let saved = sets.get(&catalog, app).await?;
    assert!(saved.generation > before.generation);
    assert_eq!(saved.library.len(), 4);

    // A view places `Card` directly (and so `Book header`); a page places
    // `Book header` directly, and an item this application does not have.
    sets.save_view(
        &catalog,
        &show_books(app, json!({ "above": [placing(&card)] })),
    )
    .await?;
    sets.save_page(
        &catalog,
        &Page::new(app, "Home").layout(json!({ "besides": [
            placing(&book_header),
            { "type": "library", "library_id": LibraryItemId::new().0.to_string() },
        ]})),
    )
    .await?;
    let set = sets.get(&catalog, app).await?;

    let names = |items: Vec<&LibraryItem>| items.iter().map(|i| i.name.clone()).collect::<Vec<_>>();
    assert_eq!(
        names(set.library_placed_by_view(set.view("Show Books").unwrap())),
        ["Book header", "Card"]
    );
    assert_eq!(
        names(set.library_placed_by_page(set.page("Home").unwrap())),
        ["Book header"]
    );
    // An item that contains itself terminates, and is in its own answer.
    assert_eq!(names(set.library_placed_by_item(&looped)), ["Loop"]);

    assert_eq!(
        set.library_references(book_header.id),
        LibraryReferences {
            views: vec!["Show Books".to_owned()],
            pages: vec!["Home".to_owned()],
            library: vec!["Card".to_owned()],
        }
    );
    assert_eq!(
        set.library_references(card.id),
        LibraryReferences {
            views: vec!["Show Books".to_owned()],
            ..LibraryReferences::default()
        }
    );
    // Placing itself is not a reference to itself.
    assert!(set.library_references(looped.id).is_empty());
    assert!(set.library_references(unused.id).is_empty());

    // An in-place update and a delete move the generation too, and the reloaded
    // set sees them.
    sets.apply_library_updates(
        &catalog,
        app,
        &[LibraryUpdate {
            library_id: card.id,
            layout: json!({}),
        }],
    )
    .await?;
    let updated = sets.get(&catalog, app).await?;
    assert!(updated.generation > set.generation);
    assert_eq!(
        names(updated.library_placed_by_view(updated.view("Show Books").unwrap())),
        ["Card"]
    );
    assert!(sets.delete_library_item(&catalog, app, unused.id).await?);
    let deleted = sets.get(&catalog, app).await?;
    assert!(deleted.generation > updated.generation);
    assert!(deleted.library_item(unused.id).is_none());
    Ok(())
}
