//! Views and pages round-tripping through `_fd_views` / `_fd_pages` against a
//! real Postgres (TODO "Saltcorn UI" Phase 1).
//!
//! What only a database can settle: that what is saved comes back identical,
//! that each save-time refusal names what is wrong, that a name is unique per
//! application rather than globally, and that a view set's generation moves on a
//! write and not on a read.

use std::sync::Arc;

use sc_app::{AppId, Application, FrameworkRef, save_application};
use sc_catalog::{Catalog, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;
use sc_viewpattern::{
    Page, View, ViewSets, bootstrap, delete_application_views_pages_and_library, delete_page,
    delete_view, list_pages, list_views, load_page, load_view, save_page, save_view,
};
use serde_json::json;

/// A catalog over a per-test database with a `books` and a `publishers` table,
/// the roles, applications and file-store tables, and this crate's two tables.
async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE books (\
               id bigint generated by default as identity primary key, \
               title text not null); \
             CREATE TABLE publishers (\
               id bigint generated by default as identity primary key, \
               name text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    sc_auth::bootstrap(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    sc_catalog::bootstrap_file_stores(&catalog).await?;
    sc_catalog::save_file_store(&catalog, &sc_files::FileStoreDef::local("apps", "/srv/x")).await?;
    bootstrap(&catalog).await?;
    // Twice: the bootstrap is idempotent, key included.
    bootstrap(&catalog).await?;
    Ok(catalog)
}

/// An application over `books` only. Its framework is `code` because Saltcorn
/// UI is not a registered framework until Phase 5; the view store does not look.
async fn application(catalog: &Catalog, name: &str, subdomain: &str) -> Result<AppId> {
    let app = Application::new(
        name,
        subdomain,
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh"),
    )
    .with_table(TableId("books".to_owned()));
    Ok(save_application(catalog, &app).await?.id)
}

fn list_books(app: AppId) -> View {
    let mut view = View::new(app, "List Books", "List", "books")
        .description("Every book")
        .min_role(1)
        .configuration(
            json!({ "columns": [{ "type": "Field", "field_name": "title" }] })
                .as_object()
                .cloned()
                .unwrap(),
        );
    view.slug = Some(json!({ "label": "", "steps": [] }));
    view.attributes
        .insert("page_title".to_owned(), json!("Books"));
    view
}

#[tokio::test]
async fn a_view_and_a_page_round_trip_and_delete() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;

    let view = list_books(app);
    save_view(&catalog, &view).await?;
    assert_eq!(
        load_view(&catalog, app, "List Books").await?,
        Some(view.clone())
    );

    // An update in place: same id, new configuration and name.
    let mut edited = view.clone();
    edited.name = "All Books".to_owned();
    edited
        .configuration
        .insert("create_view_label".to_owned(), json!("Add"));
    save_view(&catalog, &edited).await?;
    assert_eq!(list_views(&catalog, app).await?, vec![edited.clone()]);
    assert_eq!(load_view(&catalog, app, "List Books").await?, None);

    let mut page = Page::new(app, "BooksOverview")
        .title("Books")
        .min_role(1)
        .layout(json!({ "above": [{ "type": "view", "view": "Filter books" }] }));
    page.attributes
        .insert("root_page_for_roles".to_owned(), json!([1]));
    save_page(&catalog, &page).await?;
    assert_eq!(
        load_page(&catalog, app, "BooksOverview").await?,
        Some(page.clone())
    );
    assert_eq!(list_pages(&catalog, app).await?, vec![page]);

    assert!(delete_view(&catalog, app, "All Books").await?);
    assert!(!delete_view(&catalog, app, "All Books").await?);
    assert!(delete_page(&catalog, app, "BooksOverview").await?);
    assert!(list_views(&catalog, app).await?.is_empty());
    assert!(list_pages(&catalog, app).await?.is_empty());
    Ok(())
}

#[tokio::test]
async fn each_refusal_names_what_is_wrong() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;
    let refused = |r: Result<View>| r.unwrap_err().to_string();

    // A pattern that is not registered.
    let mut view = list_books(app);
    view.viewpattern = "Room".to_owned();
    let msg = refused(save_view(&catalog, &view).await);
    assert!(
        msg.contains("`Room`") && msg.contains("not registered"),
        "{msg}"
    );

    // A table outside the application's subset — it exists, but not for this app.
    let mut view = list_books(app);
    view.table_name = Some("publishers".to_owned());
    let msg = refused(save_view(&catalog, &view).await);
    assert!(
        msg.contains("`publishers`") && msg.contains("`BooksDB`'s table subset"),
        "{msg}"
    );

    // A role no role defines (only 1 and 100 are built in).
    let view = list_books(app).min_role(7);
    let msg = refused(save_view(&catalog, &view).await);
    assert!(msg.contains("role 7"), "{msg}");

    // A name that is not one URL path segment.
    let mut view = list_books(app);
    view.name = "books/all".to_owned();
    let msg = refused(save_view(&catalog, &view).await);
    assert!(msg.contains("`/`"), "{msg}");

    // A name the application already has, on a different view.
    save_view(&catalog, &list_books(app)).await?;
    let msg = refused(save_view(&catalog, &list_books(app)).await);
    assert!(
        msg.contains("already has a view named `List Books`"),
        "{msg}"
    );

    // A page's refusals are the same sentences.
    let page = Page::new(app, "BooksOverview");
    save_page(&catalog, &page).await?;
    let msg = save_page(&catalog, &Page::new(app, "BooksOverview"))
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("already has a page named"), "{msg}");

    // The database refuses nothing it was not asked to: one view and one page.
    assert_eq!(list_views(&catalog, app).await?.len(), 1);
    assert_eq!(list_pages(&catalog, app).await?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn two_applications_hold_same_named_views_over_the_same_table() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let one = application(&catalog, "One", "one").await?;
    let two = application(&catalog, "Two", "two").await?;

    let first = list_books(one);
    let mut second = list_books(two);
    second.configuration.insert("columns".to_owned(), json!([]));
    save_view(&catalog, &first).await?;
    save_view(&catalog, &second).await?;

    assert_eq!(load_view(&catalog, one, "List Books").await?, Some(first));
    assert_eq!(
        load_view(&catalog, two, "List Books").await?,
        Some(second.clone())
    );

    // A view's id cannot be re-saved into another application.
    let mut moved = second.clone();
    moved.application = one;
    moved.name = "Moved".to_owned();
    let msg = save_view(&catalog, &moved).await.unwrap_err().to_string();
    assert!(msg.contains("another application"), "{msg}");

    // Deleting one application's views leaves the other's.
    delete_application_views_pages_and_library(&catalog, one).await?;
    assert!(list_views(&catalog, one).await?.is_empty());
    assert_eq!(list_views(&catalog, two).await?, vec![second]);
    Ok(())
}

#[tokio::test]
async fn a_generation_moves_on_write_and_not_on_read() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog(&db).await?;
    let app = application(&catalog, "BooksDB", "books").await?;
    let other = application(&catalog, "Other", "other").await?;
    let sets = ViewSets::new();

    let empty = sets.get(&catalog, app).await?;
    assert!(empty.views.is_empty());
    let other_set = sets.get(&catalog, other).await?;

    // Reads hand back the cached set, generation unchanged — even when the
    // database changed behind the cache's back, which is why every write goes
    // through `ViewSets`.
    save_view(&catalog, &list_books(app)).await?;
    let again = sets.get(&catalog, app).await?;
    assert_eq!(again.generation, empty.generation);
    assert!(again.views.is_empty());

    // A write through the cache reloads and moves the generation…
    let mut edited = list_books(app);
    edited.name = "Books".to_owned();
    sets.save_view(&catalog, &edited).await?;
    let written = sets.get(&catalog, app).await?;
    assert!(written.generation > empty.generation);
    assert_eq!(written.views.len(), 2);
    assert!(written.view("Books").is_some());

    // …and a page write and a delete move it again.
    sets.save_page(&catalog, &Page::new(app, "Home")).await?;
    let paged = sets.get(&catalog, app).await?;
    assert!(paged.generation > written.generation);
    assert!(paged.page("Home").is_some());
    assert!(sets.delete_view(&catalog, app, "Books").await?);
    assert!(sets.generation(app)? > Some(paged.generation));

    // Another application's set did not move.
    assert_eq!(sets.generation(other)?, Some(other_set.generation));
    Ok(())
}
