//! A code body's writes, end to end (the milestone "Tables in code", phase 3).
//!
//! Reads could be proved against a plan and a statement; writes cannot. The
//! whole claim of §4 is that a write from a code body is **an event like any
//! other** — coerced against its columns, observed by the table's own triggers,
//! carrying the caller and the trigger chain that led there, and bounded by the
//! same cascade limit an action's write is. Every one of those is a property of
//! the row layer being the thing that runs, so the only honest test of it is a
//! real database with real triggers installed.
//!
//! So: the trigger dispatcher is the real one, the triggers are saved and loaded
//! the way the admin's are, and the actions behind them are test doubles that do
//! one thing each — record what they were given, or write again so a cascade has
//! something to run away with.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::{Arc, Mutex};

use sc_action::{
    Action, ActionContext, ActionRegistry, Event, EventKind, MAX_DEPTH, Trigger, TriggerDispatcher,
    bootstrap_triggers, save_trigger,
};
use sc_api::code_host::TableHost;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_expr::CodeHost;
use sc_test_harness::TestDb;
use sc_types::FormField;
use serde_json::{Value as Json, json};

/// Books with an author key, an audit table for a trigger to write into, and one
/// self-referential table for the cascade bound — the same shape the server's own
/// trigger tests use, for the same reasons.
const SCHEMA: &str = "\
    CREATE TABLE authors (id bigint generated by default as identity primary key, name text); \
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text not null, pages bigint, published date, price numeric, \
        author bigint references authors(id)); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        what text, title text, who text); \
    CREATE TABLE links (id bigint generated by default as identity primary key, depth bigint); \
    INSERT INTO authors (name) VALUES ('Woolf'), ('Herbert');";

/// The catalog over a fresh database with [`SCHEMA`] in it.
async fn setup(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Ok(Arc::new(
        Catalog::init(driver as Arc<dyn DatabaseDriver>).await?,
    ))
}

/// One plan, answered — what `__scDbCall(plan)` gets back.
async fn ask(host: &TableHost, plan: Json) -> Result<Json> {
    host.call(plan).await
}

/// Every row of a table, by the shortest route that is not the code host itself:
/// a test that asserted its own writes through its own reads could agree with
/// itself about a write that never happened.
async fn rows_of(db: &TestDb, sql: &str) -> Vec<Vec<Option<String>>> {
    db.client()
        .await
        .unwrap()
        .query(sql, &[])
        .await
        .unwrap()
        .iter()
        .map(|row| {
            (0..row.len())
                .map(|i| row.get::<_, Option<String>>(i))
                .collect()
        })
        .collect()
}

#[tokio::test]
async fn an_insert_returns_the_written_row_with_its_values_typed_by_their_columns() -> Result<()> {
    let db = TestDb::new().await?;
    let host = TableHost::new(setup(&db).await?);

    // `db.books.insert({ … })` — one row in, one row out (not an array of one),
    // with the database-generated key filled in.
    let written = ask(
        &host,
        json!({
            "op": "insert", "table": "books",
            "values": {
                "title": "Orlando", "pages": 333, "published": "1928-10-11",
                "price": "12.50", "author": 1,
            },
        }),
    )
    .await?;
    assert_eq!(written["id"], json!(1), "the key the database generated");
    assert_eq!(written["title"], json!("Orlando"));
    // The REST wire shape, as a read's rows are: a Date is ISO and a Decimal is
    // exact text rather than a float that has quietly stopped being exact.
    assert_eq!(written["published"], json!("1928-10-11"));
    assert_eq!(written["price"], json!("12.50"));

    // The values reached the columns **typed**: the date is a date in the
    // database, not text that looks like one — which is what lets a date filter
    // find it. (A string bound to a date column would not compare this way.)
    let found = ask(
        &host,
        json!({
            "op": "select", "table": "books",
            "where": { "published": { "lt": "1930-01-01" } },
            "select": ["title"],
        }),
    )
    .await?;
    assert_eq!(found, json!([{ "title": "Orlando" }]));
    assert_eq!(
        rows_of(&db, "SELECT pg_typeof(published)::text FROM books").await,
        vec![vec![Some("date".to_owned())]],
    );

    // An array in is an array out, one statement per row.
    let many = ask(
        &host,
        json!({
            "op": "insert", "table": "books",
            "values": [
                { "title": "The Waves", "author": 1 },
                { "title": "Dune", "author": 2 },
            ],
        }),
    )
    .await?;
    let many = many.as_array().expect("an array of written rows");
    assert_eq!(many.len(), 2);
    assert_eq!(many[0]["id"], json!(2));
    assert_eq!(many[1]["title"], json!("Dune"));
    Ok(())
}

#[tokio::test]
async fn a_bulk_update_and_delete_answer_what_they_touched() -> Result<()> {
    let db = TestDb::new().await?;
    let host = TableHost::new(setup(&db).await?);
    ask(
        &host,
        json!({
            "op": "insert", "table": "books",
            "values": [
                { "title": "Orlando", "pages": 333, "author": 1 },
                { "title": "The Waves", "pages": 297, "author": 1 },
                { "title": "Dune", "pages": 412, "author": 2 },
            ],
        }),
    )
    .await?;

    // `db.books.where({ author: 1 }).orderBy("id").update({ pages: 100 })` —
    // `{ updated, ids }`, the shape the `update_rows` action already answers.
    let updated = ask(
        &host,
        json!({
            "op": "update", "table": "books",
            "where": { "author": 1 },
            "order": [ { "field": "id" } ],
            "values": { "pages": 100 },
        }),
    )
    .await?;
    assert_eq!(updated, json!({ "updated": 2, "ids": [1, 2] }));
    assert_eq!(
        rows_of(&db, "SELECT pages::text FROM books ORDER BY id").await,
        vec![
            vec![Some("100".to_owned())],
            vec![Some("100".to_owned())],
            vec![Some("412".to_owned())],
        ],
    );

    // A `.limit()` bounds a bulk write as it bounds a read — "the oldest one".
    let limited = ask(
        &host,
        json!({
            "op": "update", "table": "books",
            "where": { "author": 1 }, "order": [ { "field": "id" } ], "limit": 1,
            "values": { "title": "Orlando (rev.)" },
        }),
    )
    .await?;
    assert_eq!(limited, json!({ "updated": 1, "ids": [1] }));

    let deleted = ask(
        &host,
        json!({
            "op": "delete", "table": "books",
            "where": { "pages": { "gt": 300 } },
        }),
    )
    .await?;
    assert_eq!(deleted, json!({ "deleted": 1, "ids": [3] }));
    assert_eq!(
        rows_of(&db, "SELECT title FROM books ORDER BY id").await,
        vec![
            vec![Some("Orlando (rev.)".to_owned())],
            vec![Some("The Waves".to_owned())],
        ],
    );
    Ok(())
}

#[tokio::test]
async fn a_write_with_no_filter_or_a_bad_value_touches_nothing() -> Result<()> {
    let db = TestDb::new().await?;
    let host = TableHost::new(setup(&db).await?);
    ask(
        &host,
        json!({
            "op": "insert", "table": "books",
            "values": [ { "title": "Orlando", "pages": 333 }, { "title": "Dune", "pages": 412 } ],
        }),
    )
    .await?;

    // §4: a whole table rewritten or emptied is not something an omitted call
    // should be able to cause. The prelude says so in front of the author; this
    // is the host saying it to a plan that arrived without one anyway.
    for op in ["update", "delete"] {
        let err = ask(
            &host,
            json!({ "op": op, "table": "books", "values": { "pages": 1 } }),
        )
        .await
        .expect_err("refused");
        assert!(err.to_string().contains("every row of `books`"), "{err}");
    }

    // A bulk insert whose *last* row is wrong writes none of them: there is no
    // transaction here (§6), so the check has to come before the first statement.
    let err = ask(
        &host,
        json!({
            "op": "insert", "table": "books",
            "values": [ { "title": "Mrs Dalloway" }, { "title": "Jacob's Room", "pages": "lots" } ],
        }),
    )
    .await
    .expect_err("refused");
    assert!(err.to_string().contains("`pages`"), "{err}");

    assert_eq!(
        rows_of(&db, "SELECT title FROM books ORDER BY id").await,
        vec![
            vec![Some("Orlando".to_owned())],
            vec![Some("Dune".to_owned())],
        ],
        "nothing was written by any of the refused plans",
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Writes are events
// ---------------------------------------------------------------------------

/// A trigger action that records what it was handed: the event's row, its
/// caller, and how deep in a cascade it already was.
struct Recorder(Arc<Mutex<Vec<Json>>>);

#[async_trait::async_trait]
impl Action for Recorder {
    fn name(&self) -> &str {
        "record"
    }
    fn description(&self) -> &str {
        "Record the event, for a test to read back"
    }
    fn config_spec(&self) -> Vec<FormField> {
        Vec::new()
    }
    async fn run(&self, ctx: &mut ActionContext<'_>) -> Result<Json> {
        let seen = json!({
            "kind": ctx.event.kind.as_str(),
            "row": ctx.event.row,
            "user": ctx.event.user,
            "chain": ctx.chain,
            "depth": ctx.event.depth(),
        });
        self.0.lock().unwrap().push(seen.clone());
        Ok(seen)
    }
}

/// A trigger action that writes the table it fired on, **through a code host**,
/// carrying the chain it was given — a code body that feeds itself.
struct Feed {
    catalog: Arc<Catalog>,
    chains: Arc<Mutex<Vec<Vec<String>>>>,
}

#[async_trait::async_trait]
impl Action for Feed {
    fn name(&self) -> &str {
        "feed"
    }
    fn description(&self) -> &str {
        "Insert another row into the table that fired, from a code host"
    }
    fn config_spec(&self) -> Vec<FormField> {
        Vec::new()
    }
    async fn run(&self, ctx: &mut ActionContext<'_>) -> Result<Json> {
        self.chains.lock().unwrap().push(ctx.chain.clone());
        let depth = ctx
            .event
            .row
            .as_ref()
            .and_then(|row| row["depth"].as_i64())
            .unwrap_or(0);
        // Exactly what phase 5 will build for `run_js_code`: the event's caller
        // and *this trigger's chain*, so the event this write raises knows how
        // deep it is.
        let host = TableHost::new(Arc::clone(&self.catalog))
            .caused_by(ctx.event.user.clone())
            .chained(ctx.chain.clone());
        host.call(json!({
            "op": "insert", "table": "links", "values": { "depth": depth + 1 },
        }))
        .await
    }
}

/// The catalog with a real dispatcher installed over `actions`, and one trigger
/// per `(name, kind, table)` saved and loaded the way the admin's are.
async fn with_triggers(
    catalog: &Arc<Catalog>,
    actions: Vec<Arc<dyn Action>>,
    triggers: Vec<Trigger>,
) -> Result<Arc<TriggerDispatcher>> {
    let mut registry = ActionRegistry::new();
    for action in actions {
        registry.register(action)?;
    }
    let dispatcher = Arc::new(TriggerDispatcher::new(Arc::new(registry)));
    bootstrap_triggers(catalog).await?;
    for trigger in &triggers {
        save_trigger(catalog, dispatcher.registry(), trigger).await?;
    }
    dispatcher.reload(catalog).await?;
    catalog.set_table_events(Arc::clone(&dispatcher) as Arc<dyn sc_catalog::TableEvents>)?;
    Ok(dispatcher)
}

#[tokio::test]
async fn an_insert_from_a_code_body_fires_the_tables_own_trigger() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let seen = Arc::new(Mutex::new(Vec::new()));
    with_triggers(
        &catalog,
        vec![Arc::new(Recorder(Arc::clone(&seen)))],
        vec![
            Trigger::new("watch_insert", EventKind::Insert, "record").on("books"),
            Trigger::new("watch_update", EventKind::Update, "record").on("books"),
            Trigger::new("watch_delete", EventKind::Delete, "record").on("books"),
        ],
    )
    .await?;

    // The host carries the event's caller, as phase 5 will build it from the
    // event that ran the trigger.
    let host = TableHost::new(Arc::clone(&catalog))
        .caused_by(Some(json!({ "id": 7, "email": "who@example.com" })));

    ask(
        &host,
        json!({ "op": "insert", "table": "books", "values": { "title": "Orlando" } }),
    )
    .await?;
    ask(
        &host,
        json!({
            "op": "update", "table": "books",
            "where": { "title": "Orlando" }, "values": { "pages": 333 },
        }),
    )
    .await?;
    ask(
        &host,
        json!({ "op": "delete", "table": "books", "where": { "title": "Orlando" } }),
    )
    .await?;

    let seen = seen.lock().unwrap().clone();
    let kinds: Vec<&str> = seen
        .iter()
        .map(|e| e["kind"].as_str().unwrap_or_default())
        .collect();
    assert_eq!(
        kinds,
        vec!["insert", "update", "delete"],
        "each write through the row layer is the event it always was: {seen:?}"
    );
    // The row the event carries is the row that was written, and the caller is
    // the one this run was given — which is why an audit trigger on a code body's
    // write can say who caused it.
    assert_eq!(seen[0]["row"]["title"], json!("Orlando"));
    assert_eq!(seen[1]["row"]["pages"], json!(333));
    assert_eq!(
        seen[2]["row"]["title"],
        json!("Orlando"),
        "the row as it was"
    );
    assert_eq!(seen[0]["user"]["email"], json!("who@example.com"));
    // Nothing led here but a request, so these events are at depth 0.
    assert_eq!(seen[0]["depth"], json!(0));
    Ok(())
}

#[tokio::test]
async fn a_code_body_writing_its_own_table_is_stopped_by_the_cascade_bound() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let chains = Arc::new(Mutex::new(Vec::new()));
    let dispatcher = with_triggers(
        &catalog,
        vec![Arc::new(Feed {
            catalog: Arc::clone(&catalog),
            chains: Arc::clone(&chains),
        })],
        vec![Trigger::new("feed", EventKind::Insert, "feed").on("links")],
    )
    .await?;

    // The first write is a code body's, at depth 0 — and every write it causes is
    // one too, so nothing but the bound stops this.
    let host = TableHost::new(Arc::clone(&catalog));
    ask(
        &host,
        json!({ "op": "insert", "table": "links", "values": { "depth": 0 } }),
    )
    .await?;

    let depths = rows_of(&db, "SELECT depth::text FROM links ORDER BY id").await;
    assert_eq!(
        depths.len(),
        MAX_DEPTH + 1,
        "the first row plus one per firing, and firings stop at the bound: {depths:?}"
    );

    // The chain grew by one trigger per level — which is the mechanism, not a
    // coincidence: a host's write carries it, so the event it raises is one
    // deeper than the one that caused it.
    let chains = chains.lock().unwrap().clone();
    assert_eq!(chains.len(), MAX_DEPTH);
    assert_eq!(chains.first().map(Vec::len), Some(1));
    let deepest = chains.last().cloned().expect("a deepest run");
    assert_eq!(deepest.len(), MAX_DEPTH);

    // And what stopped it names the whole chain. The production path *reports*
    // that refusal rather than returning it — the write it would have followed
    // has already committed — so it is asked for here the way the admin's log
    // will get it: one more dispatch of the event the last write raised.
    let event = Event::new(EventKind::Insert)
        .on("links")
        .row(json!({ "id": 6, "depth": 5 }))
        .chained(deepest);
    let runs = dispatcher.dispatch(&catalog, &event).await;
    assert_eq!(runs.len(), 1);
    let message = runs[0].outcome.as_ref().unwrap_err().to_string();
    assert!(message.contains("feed → feed → feed"), "{message}");
    assert!(message.contains("was not run"), "{message}");
    Ok(())
}
