//! `db.sql(…)`: a code body's own SQL, against a real database.
//!
//! What a plan becomes can be asserted without a database, and the unit tests do
//! that. Everything *this* surface adds cannot: the claim is that the body's text
//! reaches the database as it stands, that its arguments arrive as binds, that
//! the rows come back as the wire shape, and — the part with teeth — that a
//! delegated statement runs inside the caller-context transaction where an
//! RLS-protected table's own policies decide. Each of those is a property of a
//! statement actually running, so each is tested against one.
//!
//! The fluent half is tested through the **real code runtime**, because the two
//! spellings of delegation (`db.sql(text, args, { asUser: true })` and
//! `db.asUser().sql(text, args)`) live in the JavaScript prelude and are not
//! visible from Rust at all.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_api::code_host::{HostLimits, TableHost};
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, enable_rls, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_expr::{CodeCall, CodeHost, CodeRuntime};
use sc_test_harness::TestDb;
use serde_json::{Value as Json, json};

/// Two owners with two books each — enough for a policy to divide.
const SCHEMA: &str = "\
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text, pages bigint, owner text); \
    INSERT INTO books (title, pages, owner) VALUES \
        ('Dune',   412, 'ada@example.com'), \
        ('Emma',   474, 'bob@example.com'), \
        ('Ilium',  576, 'ada@example.com'), \
        ('Ubik',   224, 'bob@example.com');";

/// The catalog over a fresh database with [`SCHEMA`] in it.
async fn setup(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    bootstrap_table_meta(&cat).await?;
    Ok(cat)
}

/// Put an ownership formula on `books` and let the **database** enforce it.
async fn rls_books(cat: &Catalog, formula: &str) -> Result<()> {
    let mut books = TableMeta::new("books");
    books.set_ownership_formula(Some(formula));
    books.set_rls_enabled(true);
    save_table_meta(cat, &books).await?;
    enable_rls(cat, &cat.require("books")?).await?;
    Ok(())
}

/// A host whose event was caused by `email` at role 40.
fn as_reader<'a>(cat: &'a Catalog, email: &str) -> TableHost<'a> {
    TableHost::new(cat).caused_by(
        40,
        Some(json!({
            "id": uuid::Uuid::new_v4().to_string(),
            "role": 40,
            "email": email,
        })),
    )
}

/// The `title` of every row of an answer, in the order they came back.
fn titles(rows: &Json) -> Vec<String> {
    rows.as_array()
        .cloned()
        .unwrap_or_default()
        .iter()
        .map(|r| r["title"].as_str().unwrap_or_default().to_owned())
        .collect()
}

#[tokio::test]
async fn the_bodys_sql_runs_as_written_with_its_arguments_bound() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    let host = as_reader(&cat, "ada@example.com");

    // The reason this surface exists: a question the chain does not ask. The
    // window function is the point — no `.where()`, `.groupBy()` or formula
    // expresses it, and before this the body's only way to answer it was to read
    // every row and rank them in JavaScript.
    let ranked = host
        .call(json!({
            "op": "sql",
            "sql": "select title, rank() over (partition by owner order by pages desc) as r \
                    from books where pages > $1 order by owner, r",
            "params": [200],
        }))
        .await?;
    assert_eq!(titles(&ranked), vec!["Ilium", "Dune", "Emma", "Ubik"]);
    assert_eq!(ranked[0]["r"], json!(1), "the columns are the query's own");

    // The argument is a **bind**, so a value that spells SQL is a value. The
    // table is still there afterwards, which is the assertion.
    let none = host
        .call(json!({
            "op": "sql",
            "sql": "select title from books where title = $1",
            "params": ["'; drop table books; --"],
        }))
        .await?;
    assert_eq!(none, json!([]));
    let all = host
        .call(json!({ "op": "sql", "sql": "select count(*) as n from books" }))
        .await?;
    assert_eq!(all[0]["n"], json!(4));

    // A write is a write: it commits, and it answers whatever it returned. What
    // it does **not** do is raise a table event — raw SQL does not go through the
    // row layer, and the module documentation says so where a body's author can
    // read it.
    let written = host
        .call(json!({
            "op": "sql",
            "sql": "insert into books (title, pages, owner) values ($1, $2, $3) returning id, title",
            "params": ["Nostromo", 320, "ada@example.com"],
        }))
        .await?;
    assert_eq!(titles(&written), vec!["Nostromo"]);
    let after = host
        .call(json!({ "op": "sql", "sql": "select count(*) as n from books" }))
        .await?;
    assert_eq!(after[0]["n"], json!(5), "the insert committed");
    Ok(())
}

#[tokio::test]
async fn a_delegated_statement_runs_where_the_policies_can_see_it() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    rls_books(&cat, "owner === user.email").await?;
    let host = as_reader(&cat, "bob@example.com");

    let mine = host
        .call(json!({
            "op": "sql", "authority": "user",
            "sql": "select title from books order by id",
        }))
        .await?;
    assert_eq!(
        titles(&mine),
        vec!["Emma", "Ubik"],
        "the statement ran at this caller's role and user, and the policies decided"
    );

    // The default is the trigger's own authority, which is admin — and
    // `ROLE_ADMIN` clears every policy's role floor, exactly as it does for the
    // admin API's row editor. One host, one statement, one field of difference.
    let every = host
        .call(json!({ "op": "sql", "sql": "select title from books order by id" }))
        .await?;
    assert_eq!(titles(&every), vec!["Dune", "Emma", "Ilium", "Ubik"]);

    // A delegated write is the policies' decision too: bob may not insert ada's
    // row, and a `WITH CHECK` violation is the same **not found** every other
    // withheld row is.
    let refused = host
        .call(json!({
            "op": "sql", "authority": "user",
            "sql": "insert into books (title, owner) values ($1, $2)",
            "params": ["Solaris", "ada@example.com"],
        }))
        .await
        .expect_err("the policy refuses a row this caller would not own");
    assert!(
        matches!(refused.repr(), sc_error::Repr::NotFound(_)),
        "{refused}"
    );
    Ok(())
}

#[tokio::test]
async fn the_row_cap_holds_here_too() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    let host = TableHost::new(&cat).with_limits(HostLimits {
        max_rows: 3,
        max_calls: 200,
    });

    // These rows are materialised into the isolate exactly as a `.rows()`'s are,
    // so the bound that exists for that is the bound here — and it refuses rather
    // than truncating, because a body handed 3 of 4 rows would compute a wrong
    // answer out of a right-looking one.
    let refused = host
        .call(json!({ "op": "sql", "sql": "select * from books" }))
        .await
        .expect_err("four rows against a cap of three");
    assert!(refused.to_string().contains("db.sql()"), "{refused}");
    assert!(refused.to_string().contains("3 rows"), "{refused}");

    host.call(json!({
        "op": "sql", "sql": "select * from books limit $1", "params": [3],
    }))
    .await?;
    Ok(())
}

#[tokio::test]
async fn both_spellings_of_delegation_reach_the_same_statement() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    rls_books(&cat, "owner === user.email").await?;
    let host = as_reader(&cat, "ada@example.com");

    // The fluent surface, in the runtime it actually runs in. `db.sql` is a
    // method of the handle, so `db.asUser().sql(…)` inherits the handle's
    // authority and the options object overrides it — the two spellings the
    // milestone offers, asserted to mean the same thing.
    let runtime = CodeRuntime::new();
    let out = runtime
        .run(CodeCall {
            code: r#"
                const opt   = db.sql("select title from books order by id", [], { asUser: true });
                const fluent = db.asUser().sql("select title from books order by id");
                const admin  = db.sql("select count(*) as n from books");
                const forced = db.asUser().sql("select count(*) as n from books", [], { asUser: false });
                return {
                  opt: opt.map((b) => b.title),
                  fluent: fluent.map((b) => b.title),
                  admin: admin[0].n,
                  forced: forced[0].n,
                };
            "#
            .to_owned(),
            host: Some(&host),
            ..CodeCall::default()
        })
        .await?;
    assert_eq!(
        out,
        json!({
            "opt": ["Dune", "Ilium"],
            "fluent": ["Dune", "Ilium"],
            "admin": 4,
            "forced": 4,
        })
    );

    // What the prelude refuses before anything is sent: an option nobody
    // implements is a silent no-op otherwise, which is the worst way to learn it
    // was spelled wrong.
    let refused = runtime
        .run(CodeCall {
            code: r#"return db.sql("select 1", [], { as_user: true });"#.to_owned(),
            host: Some(&host),
            ..CodeCall::default()
        })
        .await
        .expect_err("`as_user` is not an option");
    assert!(refused.to_string().contains("as_user"), "{refused}");
    assert!(refused.to_string().contains("asUser"), "{refused}");

    // And a body that put its value where the SQL goes is told so by the prelude
    // rather than by the database.
    let refused = runtime
        .run(CodeCall {
            code: r#"return db.sql({ select: "everything" });"#.to_owned(),
            host: Some(&host),
            ..CodeCall::default()
        })
        .await
        .expect_err("sql() takes text");
    assert!(refused.to_string().contains("SQL text"), "{refused}");
    Ok(())
}
