//! `asUser()`: a code body's database access delegated to the event's caller
//! (the milestone "Tables in code", phase 4).
//!
//! Nothing here can be proved against a plan. The whole claim of §5 is that a
//! delegated operation goes through [`sc_api::ownership`]'s `*_as` functions —
//! §7.3's rule, the same functions the agent tools use — and every consequence
//! that matters is a consequence of *those* running: the formula narrows a read
//! in the `WHERE` where it can and row by row where it cannot, an update is
//! checked on the row as it is and on the row as it would become, a withheld row
//! is the same not-found an absent one gets, and an RLS table's policies decide
//! inside a caller-context transaction. So: a real database, real policies, and
//! for the reified path the real V8 engine.
//!
//! The last test is the one this milestone's decision 1 exists for. A delegated
//! read whose ownership formula the translator refuses has to run the **formula**
//! isolate from inside a host call that a **code** thread is blocked on. One
//! isolate serving both would deadlock there, waiting for itself; the test runs
//! the body through the real `CodeRuntime` so that a regression is a hang the
//! suite reports rather than a subtlety nobody re-derives.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_action::{
    Action, ActionContext, ActionRegistry, EventKind, Trigger, TriggerDispatcher,
    bootstrap_triggers, save_trigger,
};
use sc_api::code_host::TableHost;
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, enable_rls, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_expr::{CodeCall, CodeHost, CodeRuntime, DenoEvaluator, JsEvaluator};
use sc_test_harness::TestDb;
use sc_types::FormField;
use serde_json::{Value as Json, json};

/// Two owners with two books each, so an ownership formula has something to
/// divide, and an `audit` table nobody owns — what a delegated write is refused
/// on and an admin's is not.
const SCHEMA: &str = "\
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text, pages bigint, owner text); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, what text); \
    INSERT INTO books (title, pages, owner) VALUES \
        ('Dune',   412, 'ada@example.com'), \
        ('Emma',   474, 'bob@example.com'), \
        ('Ilium',  576, 'ada@example.com'), \
        ('Ubik',   224, 'bob@example.com');";

/// The catalog over a fresh database with [`SCHEMA`] in it and the overlay table
/// bootstrapped, ready for an ownership formula.
async fn setup(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    bootstrap_table_meta(&cat).await?;
    Ok(cat)
}

/// Put an ownership formula on `books`, optionally as row-level security so the
/// database's own policies are what decide.
async fn own_books(cat: &Catalog, formula: &str, rls: bool) -> Result<()> {
    let mut books = TableMeta::new("books");
    books.set_ownership_formula(Some(formula));
    if rls {
        books.set_rls_enabled(true);
    }
    save_table_meta(cat, &books).await?;
    if rls {
        enable_rls(cat, &cat.require("books")?).await?;
    }
    assert!(
        cat.require("books")?.ownership.is_some(),
        "the formula is live"
    );
    Ok(())
}

/// A host whose event was caused by `email` at role 40 — below `books`' admin-only
/// floors, so this caller's access is whatever the ownership formula grants and
/// nothing else. The caller object is the shape an event carries: the id as a
/// uuid string, the role, and the fields a formula reads.
fn as_reader<'a>(cat: &'a Catalog, email: &str) -> TableHost<'a> {
    TableHost::new(cat).caused_by(
        40,
        Some(json!({
            "id": uuid::Uuid::new_v4().to_string(),
            "role": 40,
            "email": email,
        })),
    )
}

/// That host with the real formula engine behind it, for a formula the translator
/// refuses.
fn with_engine(host: TableHost<'_>) -> TableHost<'_> {
    host.with_evaluator(Some(Arc::new(DenoEvaluator::new()) as Arc<dyn JsEvaluator>))
}

/// One plan, answered — what `__scDbCall(plan)` gets back.
async fn ask(host: &TableHost<'_>, plan: Json) -> Result<Json> {
    host.call(plan).await
}

/// The `title` of every row of an answer, in the order they came back.
fn titles(rows: &Json) -> Vec<String> {
    rows.as_array()
        .cloned()
        .unwrap_or_default()
        .iter()
        .map(|r| r["title"].as_str().unwrap_or_default().to_owned())
        .collect()
}

/// Every row of a table, by the shortest route that is not the code host itself.
async fn rows_of(db: &TestDb, sql: &str) -> Vec<Vec<Option<String>>> {
    db.client()
        .await
        .unwrap()
        .query(sql, &[])
        .await
        .unwrap()
        .iter()
        .map(|row| {
            (0..row.len())
                .map(|i| row.get::<_, Option<String>>(i))
                .collect()
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_delegated_read_sees_only_the_rows_the_formula_grants() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", false).await?;
    let host = as_reader(&cat, "ada@example.com");

    // The same plan, twice, differing in one field. `asUser()`…
    let plan = json!({
        "op": "select", "table": "books", "authority": "user",
        "select": ["id", "title"], "order": [ { "field": "id" } ],
    });
    assert_eq!(
        titles(&ask(&host, plan.clone()).await?),
        vec!["Dune", "Ilium"],
        "the ownership formula narrowed the read to this caller's rows"
    );

    // …and `asAdmin()`, which is the default and reads everything. This is the
    // difference the whole phase is about, on one host and one body.
    let mut admin = plan.clone();
    admin["authority"] = json!("admin");
    assert_eq!(
        titles(&ask(&host, admin).await?),
        vec!["Dune", "Emma", "Ilium", "Ubik"],
    );

    // A row the formula withholds is the same **nothing** an absent row is: a
    // delegated `.get(pk)` cannot become a way to probe which rows exist.
    let probed = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user", "pk": 2, "limit": 1 }),
    )
    .await?;
    assert_eq!(
        probed,
        json!([]),
        "`.get(2)` is bob's row, so it is nothing"
    );

    // An aggregate is the same rule expressed inside the statement: the
    // translated formula rides in the `WHERE`, so a delegated count counts the
    // caller's rows and not the table's.
    let counted = ask(
        &host,
        json!({
            "op": "aggregate", "table": "books", "authority": "user",
            "aggregate": [ { "alias": "value", "fn": "count" } ],
        }),
    )
    .await?;
    assert_eq!(counted, json!({ "value": 2 }));

    // Grouping does not change the rule, it partitions what is left of it: the
    // formula narrows the rows, and only then are the groups formed. Ada's two
    // books group into one owner; the table's four would group into two.
    let grouped = ask(
        &host,
        json!({
            "op": "aggregate", "table": "books", "authority": "user",
            "group": ["owner"],
            "aggregate": [ { "alias": "n", "fn": "count" } ],
            "order": [ { "field": "owner" } ],
        }),
    )
    .await?;
    assert_eq!(grouped, json!([{ "owner": "ada@example.com", "n": 2 }]));
    Ok(())
}

#[tokio::test]
async fn a_delegated_read_of_an_rls_table_sees_what_the_policies_allow() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    // The same formula, enforced by the database: the read runs in a
    // caller-context transaction and the policies decide. `sc-api` applies no
    // predicate of its own here, which is exactly why this needs its own test —
    // a delegated read that forgot the context would see everything.
    own_books(&cat, "owner === user.email", true).await?;
    let host = as_reader(&cat, "bob@example.com");

    let rows = ask(
        &host,
        json!({
            "op": "select", "table": "books", "authority": "user",
            "select": ["title"], "order": [ { "field": "id" } ],
        }),
    )
    .await?;
    assert_eq!(titles(&rows), vec!["Emma", "Ubik"]);

    // And the admin's own path still reads the whole table: `ROLE_ADMIN` clears
    // the policy's role floor, as the admin API's row editor does.
    let all = ask(
        &host,
        json!({
            "op": "select", "table": "books",
            "select": ["title"], "order": [ { "field": "id" } ],
        }),
    )
    .await?;
    assert_eq!(all.as_array().map(Vec::len), Some(4));
    Ok(())
}

#[tokio::test]
async fn a_scheduled_triggers_delegation_reads_as_the_public_role() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", false).await?;

    // A scheduled or startup event carries nobody, so there is no one to act as.
    // §5's answer is the honest one rather than an error: the read is public's,
    // and public owns no rows. (Which is why `asAdmin()` is the default — this is
    // what a body that delegated by habit would get.)
    let scheduled = with_engine(TableHost::new(&cat));
    let plan = json!({
        "op": "select", "table": "books", "authority": "user", "select": ["title"],
    });
    assert_eq!(
        titles(&ask(&scheduled, plan.clone()).await?),
        Vec::<String>::new(),
    );

    // The same trigger's undelegated read is the admin's, and reads the table.
    let mut admin = plan;
    admin["authority"] = json!("admin");
    assert_eq!(
        ask(&scheduled, admin).await?.as_array().map(Vec::len),
        Some(4)
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_delegated_insert_outside_the_formula_writes_nothing() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", false).await?;
    // A delegated **write** is checked against a single row — the one proposed —
    // and that check is the evaluator's whether or not the formula would also
    // translate, so the engine is not optional here the way it is for a read.
    // (Which is what phase 5 has to hand `run_js_code`.)
    let host = with_engine(as_reader(&cat, "ada@example.com"));

    // §7.3's write rule, checked against the proposed row: a row ada could not
    // then read is a row ada may not write.
    let refused = ask(
        &host,
        json!({
            "op": "insert", "table": "books", "authority": "user",
            "values": { "title": "Nostromo", "owner": "bob@example.com" },
        }),
    )
    .await
    .expect_err("outside what ada may write");
    assert!(
        refused.to_string().contains("outside what you may write"),
        "{refused}"
    );

    // A table with no ownership formula at all is the other half of the same
    // rule: below the write floor and with nothing to extend it, a delegated
    // write is refused — while the trigger's own authority writes the audit row
    // it exists to write, which is why admin is the default.
    let audit = ask(
        &host,
        json!({
            "op": "insert", "table": "audit", "authority": "user",
            "values": { "what": "ada tried" },
        }),
    )
    .await
    .expect_err("ada may not write `audit`");
    assert!(audit.to_string().contains("audit"), "{audit}");
    ask(
        &host,
        json!({ "op": "insert", "table": "audit", "values": { "what": "the trigger did" } }),
    )
    .await?;

    // A row of ada's own goes in.
    let written = ask(
        &host,
        json!({
            "op": "insert", "table": "books", "authority": "user",
            "values": { "title": "Nostromo", "owner": "ada@example.com" },
        }),
    )
    .await?;
    assert_eq!(written["title"], json!("Nostromo"));

    assert_eq!(
        rows_of(&db, "SELECT title FROM books ORDER BY id").await,
        vec![
            vec![Some("Dune".to_owned())],
            vec![Some("Emma".to_owned())],
            vec![Some("Ilium".to_owned())],
            vec![Some("Ubik".to_owned())],
            vec![Some("Nostromo".to_owned())],
        ],
        "the refused inserts wrote nothing"
    );
    assert_eq!(
        rows_of(&db, "SELECT what FROM audit").await,
        vec![vec![Some("the trigger did".to_owned())]],
    );
    Ok(())
}

#[tokio::test]
async fn a_delegated_write_cannot_reach_a_row_the_caller_cannot_see() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", false).await?;
    let host = with_engine(as_reader(&cat, "ada@example.com"));

    // An update is checked twice — on the row as it is, and on the row as it
    // would become — so it cannot move a row out of the caller's own ownership.
    let moved = ask(
        &host,
        json!({
            "op": "update", "table": "books", "authority": "user",
            "where": { "title": "Dune" }, "values": { "owner": "bob@example.com" },
        }),
    )
    .await
    .expect_err("that update would give the row away");
    assert!(
        moved.to_string().contains("out of what you may reach"),
        "{moved}"
    );

    // A bulk write resolves its rows through the **delegated** read, so a row the
    // caller cannot see is never a row they can update by predicate. Not an
    // error: bob's rows simply are not among the matched ones.
    let by_predicate = ask(
        &host,
        json!({
            "op": "update", "table": "books", "authority": "user",
            "where": { "pages": { "gt": 100 } }, "values": { "pages": 1 },
        }),
    )
    .await?;
    assert_eq!(
        by_predicate["updated"],
        json!(2),
        "ada's two rows, not the table's four"
    );
    let deleted = ask(
        &host,
        json!({
            "op": "delete", "table": "books", "authority": "user",
            "where": { "owner": "bob@example.com" },
        }),
    )
    .await?;
    assert_eq!(deleted, json!({ "deleted": 0, "ids": [] }));

    // …and ada's own update went through, one event per row.
    assert_eq!(
        rows_of(&db, "SELECT pages::text FROM books ORDER BY id").await,
        vec![
            vec![Some("1".to_owned())],
            vec![Some("474".to_owned())],
            vec![Some("1".to_owned())],
            vec![Some("224".to_owned())],
        ],
    );
    Ok(())
}

/// A trigger action that records the chain and depth of the event it was handed.
struct Recorder(Arc<std::sync::Mutex<Vec<Json>>>);

#[async_trait::async_trait]
impl Action for Recorder {
    fn name(&self) -> &str {
        "record"
    }
    fn description(&self) -> &str {
        "Record the event's chain, for a test to read back"
    }
    fn config_spec(&self) -> Vec<FormField> {
        Vec::new()
    }
    async fn run(&self, ctx: &mut ActionContext<'_>) -> Result<Json> {
        let seen = json!({ "chain": ctx.chain, "depth": ctx.event.depth() });
        self.0.lock().unwrap().push(seen.clone());
        Ok(seen)
    }
}

#[tokio::test]
async fn a_delegated_write_is_an_event_at_the_depth_its_chain_says() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", false).await?;

    let seen = Arc::new(std::sync::Mutex::new(Vec::new()));
    let mut registry = ActionRegistry::new();
    registry.register(Arc::new(Recorder(Arc::clone(&seen))) as Arc<dyn Action>)?;
    let dispatcher = Arc::new(TriggerDispatcher::new(Arc::new(registry)));
    bootstrap_triggers(&cat).await?;
    save_trigger(
        &cat,
        dispatcher.registry(),
        &Trigger::new("watch", EventKind::Insert, "record").on("books"),
    )
    .await?;
    dispatcher.reload(&cat).await?;
    cat.set_table_events(Arc::clone(&dispatcher) as Arc<dyn sc_catalog::TableEvents>)?;

    // A delegated write goes through `ownership::insert_row_as` rather than
    // straight to the row layer — and it has to carry the same chain the
    // undelegated one does, or `Event::firing`'s cascade bound would restart at
    // zero and a body that writes the table that fired it would never stop.
    let host = with_engine(as_reader(&cat, "ada@example.com")).chained(vec!["watch".to_owned()]);
    ask(
        &host,
        json!({
            "op": "insert", "table": "books", "authority": "user",
            "values": { "title": "Nostromo", "owner": "ada@example.com" },
        }),
    )
    .await?;

    let seen = seen.lock().unwrap().clone();
    assert_eq!(seen.len(), 1, "the table's own trigger observed the write");
    assert_eq!(
        seen[0]["chain"],
        json!(["watch", "watch"]),
        "the delegated write's event descends from the trigger that made it"
    );
    assert_eq!(seen[0]["depth"], json!(1), "one deeper, not back at zero");
    Ok(())
}

// ---------------------------------------------------------------------------
// The reified path — and the deadlock it must not be
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_delegated_aggregate_over_an_untranslatable_formula_says_where_to_put_the_work()
-> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    // `.includes(…)` is a function call, so this formula cannot become SQL: it has
    // to be decided row by row, in the evaluator.
    own_books(&cat, "owner.includes(user.email)", false).await?;
    let host = with_engine(as_reader(&cat, "ada@example.com"));

    // The read is fine — the formula runs per row.
    let rows = ask(
        &host,
        json!({
            "op": "select", "table": "books", "authority": "user",
            "select": ["title"], "order": [ { "field": "id" } ],
        }),
    )
    .await?;
    assert_eq!(titles(&rows), vec!["Dune", "Ilium"]);

    // The aggregate is not, and §5 says so as an instruction rather than an
    // apology: a count over rows it cannot filter would be a number nobody can
    // check, and the code body is where a per-row decision can be made.
    let refused = ask(
        &host,
        json!({
            "op": "aggregate", "table": "books", "authority": "user",
            "aggregate": [ { "alias": "value", "fn": "count" } ],
        }),
    )
    .await
    .expect_err("an aggregate cannot carry a per-row formula");
    let message = refused.to_string();
    assert!(
        message.contains("cannot be aggregated for you"),
        "{message}"
    );
    assert!(message.contains("`.rows()`"), "{message}");
    assert!(message.contains("code body"), "{message}");

    // A grouped aggregate is refused for the very same reason — the guard is
    // asked before the grouping, because the question is which *rows* it may
    // range over — and says the same thing about where the work goes instead.
    let refused = ask(
        &host,
        json!({
            "op": "aggregate", "table": "books", "authority": "user",
            "group": ["owner"],
            "aggregate": [ { "alias": "n", "fn": "count" } ],
        }),
    )
    .await
    .expect_err("a grouped aggregate cannot carry a per-row formula either");
    assert!(
        refused.to_string().contains("cannot be aggregated for you"),
        "{refused}"
    );
    Ok(())
}

#[tokio::test]
async fn a_delegated_read_that_needs_the_formula_engine_completes_from_a_code_body() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner.includes(user.email)", false).await?;
    let host = with_engine(as_reader(&cat, "bob@example.com"));

    // The regression test for decision 1. This body runs on a **code** isolate,
    // whose thread blocks on the host call; the host call runs a delegated read
    // whose ownership formula only the **formula** isolate can decide. Two
    // runtimes, so the blocked thread is never the one the formula needs. One
    // isolate serving both would hang here — which is why this is a test with a
    // timeout around it rather than a comment.
    let runtime = CodeRuntime::new();
    let out = tokio::time::timeout(
        std::time::Duration::from_secs(20),
        runtime.run(CodeCall {
            code: r#"
                const mine = db.asUser().books.select("title").orderBy("id").rows();
                const all  = db.books.count();
                return { mine: mine.map((b) => b.title), all: all };
            "#
            .to_owned(),
            host: Some(&host),
            ..CodeCall::default()
        }),
    )
    .await
    .expect("a delegated read from a code body must not deadlock")?;

    assert_eq!(
        out,
        json!({ "mine": ["Emma", "Ubik"], "all": 4 }),
        "the delegated read is bob's rows and the undelegated count is the table's"
    );
    Ok(())
}

#[tokio::test]
async fn a_delegated_stream_is_refused_when_the_formula_decides_row_by_row() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner.includes(user.email)", false).await?;
    let host = with_engine(as_reader(&cat, "bob@example.com"));

    // §5's asymmetry, in the place it bites a stream. This formula only the
    // evaluator can decide, so a delegated read of `books` is bounded *after* the
    // rows come back — which means a batch of it would fetch the whole table,
    // hand back what survived, and do it again for the next batch. Not streaming,
    // and quadratic while looking like it. So it is refused, and the refusal says
    // what to do instead.
    let refused = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user", "cursor": true }),
    )
    .await
    .expect_err("a formula the database cannot carry cannot bound a batch");
    assert!(
        refused.to_string().contains("cannot be streamed"),
        "{refused}"
    );
    assert!(refused.to_string().contains(".rows()"), "{refused}");

    // And the way out is real: the same read unstreamed answers bob's rows, by
    // the reified path, exactly as it did before.
    let rows = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user", "order": [{ "field": "id" }] }),
    )
    .await?;
    assert_eq!(titles(&rows), vec!["Emma", "Ubik"]);

    // The refusal is about **delegation**, not about the table: the trigger's own
    // authority streams it, because no formula narrows an admin's read.
    let batch = ask(
        &host,
        json!({ "op": "select", "table": "books", "cursor": true, "limit": 2 }),
    )
    .await?;
    assert_eq!(titles(&batch["rows"]), vec!["Dune", "Emma"]);
    assert_eq!(
        batch["cursor"],
        json!([2]),
        "the next batch resumes after Emma"
    );
    Ok(())
}

#[tokio::test]
async fn a_delegated_stream_of_an_rls_table_is_bounded_by_the_policies() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email", true).await?;
    let host = as_reader(&cat, "ada@example.com");

    // Row-level security is carried *inside* the statement by definition, so each
    // batch is bounded over the rows the policies leave — the case a stream can
    // serve, and the reason the guard asks how the rule travels rather than
    // whether there is one.
    let first = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user",
                "cursor": true, "limit": 1 }),
    )
    .await?;
    assert_eq!(titles(&first["rows"]), vec!["Dune"]);

    let next = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user",
                "cursor": true, "limit": 1, "after": first["cursor"].clone() }),
    )
    .await?;
    assert_eq!(
        titles(&next["rows"]),
        vec!["Ilium"],
        "bob's rows are not skipped over — they were never in the stream"
    );

    let last = ask(
        &host,
        json!({ "op": "select", "table": "books", "authority": "user",
                "cursor": true, "limit": 1, "after": next["cursor"].clone() }),
    )
    .await?;
    assert!(titles(&last["rows"]).is_empty());
    assert_eq!(last["cursor"], Json::Null, "and the stream says it is done");
    Ok(())
}
