//! Table constraints end-to-end, against real Postgres (TODO Phase 3).
//!
//! The four kinds an admin can add, each created through the shared schema
//! editor and then **enforced by the database**: a write that breaks the rule is
//! refused whichever route it came in by, and — for a constraint whose admin
//! wrote a message — refused in the admin's own words rather than with
//! Postgres's `duplicate key value violates unique constraint "sc_uq_…"`.
//!
//! The other half of what these prove is that nothing is *stored*: every
//! assertion about what a table's constraints are is made after a
//! `catalog.reload()`, so what is being read is the database's own answer.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_api::rows;
use sc_api::schema_edit::{ApplyOptions, Operation};
use sc_catalog::{Catalog, ConstraintKind, TableConstraint};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;
use serde_json::json;

async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE departments (id bigint primary key, name text);
             CREATE TABLE employees (id bigint generated by default as identity primary key,
                 name text, note text, salary bigint,
                 department bigint references departments(id)
                     deferrable initially immediate);
             INSERT INTO departments VALUES (1, 'Eng'), (2, 'Ops');",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

async fn apply(catalog: &Catalog, op: Operation) -> Result<()> {
    sc_api::schema_edit::apply(catalog, &[op], &ApplyOptions::default()).await?;
    Ok(())
}

/// Add a constraint to `employees` and return the name it ended up with.
async fn add(
    catalog: &Catalog,
    kind: ConstraintKind,
    given: &str,
    message: &str,
) -> Result<String> {
    let name = TableConstraint::derived_name("employees", &kind, given);
    let mut constraint = TableConstraint::new("", kind);
    if !message.is_empty() {
        constraint = constraint.message(message);
    }
    apply(
        catalog,
        Operation::AddConstraint {
            table: "employees".into(),
            given_name: given.into(),
            constraint,
        },
    )
    .await?;
    Ok(name)
}

#[tokio::test]
async fn a_jointly_unique_constraint_speaks_the_admins_words() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    let name = add(
        &catalog,
        ConstraintKind::Unique {
            fields: vec!["department".into(), "name".into()],
        },
        "",
        "there is already someone by that name in that department",
    )
    .await?;
    assert_eq!(name, "sc_uq_employees_department_name");

    // Read back from the database, not from anything we stored: the reload
    // above threw the cache away and introspected again.
    let employees = catalog.require("employees")?;
    let constraint = employees
        .constraints
        .iter()
        .find(|c| c.name == name)
        .expect("the constraint is in the table's list");
    assert_eq!(
        constraint.kind,
        ConstraintKind::Unique {
            fields: vec!["department".into(), "name".into()],
        }
    );
    assert_eq!(
        constraint.error_message.as_deref(),
        Some("there is already someone by that name in that department")
    );

    let row = json!({ "name": "Ada", "department": 1, "salary": 100 });
    rows::create_row(&catalog, &employees, &row).await?;
    // The same pair again: refused, and refused in the admin's words.
    let err = rows::create_row(&catalog, &employees, &row)
        .await
        .expect_err("the second row breaks the constraint");
    assert!(
        err.to_string()
            .contains("there is already someone by that name in that department"),
        "{err}"
    );
    // The same rule, the same message, on an *update* — one funnel, not two.
    rows::create_row(
        &catalog,
        &employees,
        &json!({ "name": "Grace", "department": 1 }),
    )
    .await?;
    let grace = rows::list_rows(&catalog, &employees)
        .await?
        .as_array()
        .and_then(|rows| {
            rows.iter()
                .find(|r| r.get("name").and_then(|n| n.as_str()) == Some("Grace"))
                .cloned()
        })
        .expect("Grace");
    let id = grace.get("id").expect("id").to_string();
    let err = rows::update_row(&catalog, &employees, &id, &json!({ "name": "Ada" }))
        .await
        .expect_err("renaming Grace to Ada breaks the same constraint");
    assert!(
        err.to_string()
            .contains("there is already someone by that name in that department"),
        "{err}"
    );

    // …and only that pair. One column alone may still repeat.
    rows::create_row(
        &catalog,
        &employees,
        &json!({ "name": "Ada", "department": 2 }),
    )
    .await?;

    // Dropped, and the rule goes with it.
    apply(
        &catalog,
        Operation::DropConstraint {
            table: "employees".into(),
            name: name.clone(),
        },
    )
    .await?;
    let employees = catalog.require("employees")?;
    assert!(employees.constraints.iter().all(|c| c.name != name));
    rows::create_row(&catalog, &employees, &row).await?;
    Ok(())
}

#[tokio::test]
async fn a_row_constraint_is_enforced_by_the_database_aggregation_and_all() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // A formula over the row's own field *and* an aggregation over the same
    // table through an incoming key — the case a `CHECK` constraint cannot
    // express at all, which is why every row constraint is a trigger.
    let name = add(
        &catalog,
        ConstraintKind::Formula {
            formula: "salary > 0 && departmentⱵname !== 'Ops'".into(),
        },
        "sensible",
        "salaries are positive, and Ops does not hire",
    )
    .await?;
    assert_eq!(name, "sc_ck_employees_sensible");

    let employees = catalog.require("employees")?;
    // The formula comes back from the trigger's comment — the one thing a
    // `plpgsql` body cannot be read back as.
    assert_eq!(
        employees
            .constraints
            .iter()
            .find(|c| c.name == name)
            .map(|c| c.kind.clone()),
        Some(ConstraintKind::Formula {
            formula: "salary > 0 && departmentⱵname !== 'Ops'".into(),
        })
    );

    rows::create_row(
        &catalog,
        &employees,
        &json!({ "name": "Ada", "salary": 100, "department": 1 }),
    )
    .await?;
    for bad in [
        json!({ "name": "Bad", "salary": 0, "department": 1 }),
        json!({ "name": "Bad", "salary": 100, "department": 2 }),
    ] {
        let err = rows::create_row(&catalog, &employees, &bad)
            .await
            .expect_err("the row breaks the constraint");
        assert!(
            err.to_string()
                .contains("salaries are positive, and Ops does not hire"),
            "{err}"
        );
    }

    // The rule holds against a write that never goes near Saltcorn, too — which
    // is the whole reason it is in the database.
    let raw = db
        .client()
        .await?
        .batch_execute("INSERT INTO employees (name, salary, department) VALUES ('X', -1, 1)")
        .await;
    assert!(raw.is_err(), "psql is not exempt from a row constraint");

    // Dropping takes the trigger *and its function*: a constraint of the same
    // name added afterwards must not run the old formula.
    apply(
        &catalog,
        Operation::DropConstraint {
            table: "employees".into(),
            name: name.clone(),
        },
    )
    .await?;
    rows::create_row(
        &catalog,
        &catalog.require("employees")?,
        &json!({ "name": "Now fine", "salary": 0, "department": 2 }),
    )
    .await?;
    Ok(())
}

#[tokio::test]
async fn a_row_constraint_can_be_deferred_to_the_end_of_a_transaction() -> Result<()> {
    // Why the trigger is `AFTER … DEFERRABLE INITIALLY IMMEDIATE` rather than a
    // `BEFORE` one (decision 4). Nothing about an ordinary write changes — the
    // check happens at the statement, as the tests above show — but a caller
    // holding a transaction may put it off to commit, which is what lets rows
    // that refer to each other arrive in whatever order a CSV happens to list
    // them. A `BEFORE` trigger cannot be deferred at all: only a constraint
    // trigger can, and a constraint trigger is `AFTER` by definition.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    add(
        &catalog,
        ConstraintKind::Formula {
            formula: "departmentⱵname !== 'Ops'".into(),
        },
        "not_ops",
        "Ops does not hire",
    )
    .await?;

    // Immediate by default: an ordinary write is checked at the statement, and
    // the message is the admin's.
    let err = rows::create_row(
        &catalog,
        &catalog.require("employees")?,
        &json!({ "name": "Ada", "department": 2 }),
    )
    .await
    .expect_err("department 2 is Ops");
    assert!(err.to_string().contains("Ops does not hire"), "{err}");

    // Deferred: the employee arrives before the department it points at — the
    // order a CSV happens to list them in — and commits cleanly, because the
    // join the formula reads is evaluated when both rows are in.
    let mut client = db.client().await?;
    let tx = client
        .transaction()
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    tx.batch_execute(
        "SET CONSTRAINTS ALL DEFERRED;
         INSERT INTO employees (name, department) VALUES ('Ada', 9);
         INSERT INTO departments VALUES (9, 'Research');",
    )
    .await
    .map_err(|e| sc_error::Error::database(e.to_string()))?;
    tx.commit()
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    // …and a deferred transaction that never satisfies the rule still fails, at
    // commit rather than at the statement. Deferring is "check later", never
    // "do not check".
    let mut client = db.client().await?;
    let tx = client
        .transaction()
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    tx.batch_execute(
        "SET CONSTRAINTS ALL DEFERRED;
         INSERT INTO employees (name, department) VALUES ('Bad', 99);
         INSERT INTO departments VALUES (99, 'Ops');",
    )
    .await
    .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let committed = tx.commit().await;
    assert!(
        committed.is_err(),
        "a deferred constraint is checked at commit, not waived"
    );
    Ok(())
}

#[tokio::test]
async fn indexes_and_full_text_indexes_are_created_and_read_back() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    let index = add(
        &catalog,
        ConstraintKind::Index {
            fields: vec!["salary".into()],
            expression: None,
            method: "btree".into(),
        },
        "",
        "",
    )
    .await?;
    let fts = add(
        &catalog,
        ConstraintKind::FullTextSearch {
            language: "english".into(),
        },
        "",
        "",
    )
    .await?;
    assert_eq!(index, "sc_ix_employees_salary");
    assert_eq!(fts, "sc_fts_employees");

    let employees = catalog.require("employees")?;
    let kind = |name: &str| {
        employees
            .constraints
            .iter()
            .find(|c| c.name == name)
            .map(|c| c.kind.clone())
    };
    assert_eq!(
        kind(&index),
        Some(ConstraintKind::Index {
            fields: vec!["salary".into()],
            expression: None,
            method: "btree".into(),
        })
    );
    // A full-text index is *not* reported as an ordinary expression index: the
    // language it was built with is in its comment, and the language is what
    // decides whether a search can use it at all.
    assert_eq!(
        kind(&fts),
        Some(ConstraintKind::FullTextSearch {
            language: "english".into(),
        })
    );

    // The index really is over every text field — the expression the search side
    // will have to match to use it.
    let definition: String = db
        .client()
        .await?
        .query_one(
            "SELECT indexdef FROM pg_indexes WHERE indexname = $1",
            &[&fts],
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?
        .get(0);
    assert!(definition.contains("to_tsvector"), "{definition}");
    for column in ["name", "note"] {
        assert!(definition.contains(column), "{definition}");
    }

    // A text column added afterwards belongs in the index, or the index quietly
    // stops covering the table it claims to cover.
    apply(
        &catalog,
        Operation::AddField {
            table: "employees".into(),
            field: sc_api::schema_edit::FieldSpec {
                name: "nickname".into(),
                type_name: "text".into(),
                ..Default::default()
            },
        },
    )
    .await?;
    let definition: String = db
        .client()
        .await?
        .query_one(
            "SELECT indexdef FROM pg_indexes WHERE indexname = $1",
            &[&fts],
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?
        .get(0);
    assert!(definition.contains("nickname"), "{definition}");
    Ok(())
}

#[tokio::test]
async fn what_a_constraint_refuses_it_refuses_by_name() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // A formula asking a question a trigger cannot answer.
    let err = add(
        &catalog,
        ConstraintKind::Formula {
            formula: "user.id === id".into(),
        },
        "mine",
        "",
    )
    .await
    .expect_err("`user` has no meaning in the database");
    assert!(err.to_string().contains("user"), "{err}");

    // A field that is not there.
    let err = add(
        &catalog,
        ConstraintKind::Unique {
            fields: vec!["nope".into()],
        },
        "",
        "",
    )
    .await
    .expect_err("no such field");
    assert!(err.to_string().contains("nope"), "{err}");

    // The same constraint twice: refused by the name it already has, rather
    // than creating a second constraint enforcing one rule.
    add(
        &catalog,
        ConstraintKind::Unique {
            fields: vec!["name".into()],
        },
        "",
        "",
    )
    .await?;
    let err = add(
        &catalog,
        ConstraintKind::Unique {
            fields: vec!["name".into()],
        },
        "",
        "",
    )
    .await
    .expect_err("already there");
    assert!(err.to_string().contains("sc_uq_employees_name"), "{err}");

    // And a field a constraint names cannot be dropped from under it: Postgres
    // would drop the constraint along with the column without a word.
    let err = apply(
        &catalog,
        Operation::DropField {
            table: "employees".into(),
            field: "name".into(),
        },
    )
    .await
    .expect_err("the constraint needs the field");
    assert!(err.to_string().contains("sc_uq_employees_name"), "{err}");

    // …including a field a *formula* reads, which Postgres would not catch at
    // all: the trigger would survive and fail at the next write.
    add(
        &catalog,
        ConstraintKind::Formula {
            formula: "salary > 0".into(),
        },
        "paid",
        "",
    )
    .await?;
    let err = apply(
        &catalog,
        Operation::DropField {
            table: "employees".into(),
            field: "salary".into(),
        },
    )
    .await
    .expect_err("the row constraint reads the field");
    assert!(err.to_string().contains("sc_ck_employees_paid"), "{err}");

    // A field no constraint names is still droppable — the refusal is about
    // this constraint, not about constraints existing.
    apply(
        &catalog,
        Operation::DropField {
            table: "employees".into(),
            field: "note".into(),
        },
    )
    .await?;
    Ok(())
}
