//! Writing rows over GraphQL, against a real Postgres (TODO "GraphQL API"
//! Phase 6).
//!
//! The claim under test is not "a mutation works". It is that a GraphQL write
//! and a REST write are **the same write** — same coercion, same rich-type
//! rules, same `File`-field checks, same §7.3 ownership decision, same table
//! events — because they are the same code with two front doors. So the first
//! test does both and compares the *rows and the events*, and every test after
//! it asks whether one of those rules survived the trip.
//!
//! A rule is never tested by asserting that a permitted write succeeded. It is
//! tested by asserting what the caller who may **not** do it gets — because a
//! rule that quietly stopped running still lets the first kind of test pass.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::{Arc, Mutex};

use async_trait::async_trait;
use sc_api::{ApiProvider, ApiRequest, GraphqlLimits, GraphqlProvider, Method, RestProvider};
use sc_auth::User;
use sc_catalog::{
    Catalog, TableEvents, TableMeta, TableWrite, WriteOp, bootstrap_field_meta,
    bootstrap_file_stores, bootstrap_table_meta, connect_all_file_stores, save_field_meta,
    save_table_meta,
};
use sc_catalog::{DataFieldKind, FieldMeta, FileStoreId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_expr::{FormulaCall, JsEvaluator};
use sc_files::FileStoreDef;
use sc_query::Value;
use sc_test_harness::TestDb;
use serde_json::{Value as Json, json};

/// Two tables and a relation, so a mutation's result can be asked for more than
/// its own columns.
const FIXTURE: &str = "
    CREATE TABLE projects (
        id bigint generated by default as identity primary key,
        name text not null);
    CREATE TABLE tasks (
        id bigint generated by default as identity primary key,
        title text not null,
        owner text,
        done boolean,
        priority bigint,
        project bigint references projects(id));
    INSERT INTO projects (id, name) VALUES (1, 'Apollo'), (2, 'Gemini');
    INSERT INTO tasks (id, title, owner, done, priority, project) VALUES
        (1, 'write it',  'ada@example.com', false, 3, 1),
        (2, 'ship it',   'bror@example.com', false, 1, 1),
        (3, 'forget it', 'ada@example.com',  true,  2, 2);
    SELECT setval(pg_get_serial_sequence('tasks', 'id'), 100);
    SELECT setval(pg_get_serial_sequence('projects', 'id'), 100);
";

/// Every table write that happened, as the trigger dispatcher would see it.
type Events = Arc<Mutex<Vec<Json>>>;

/// A listener that records writes instead of running triggers.
///
/// The point of it is the comparison in the first test: a GraphQL insert and a
/// REST insert must raise the *same* event, because §10.2's emit seam is inside
/// the row layer and neither provider is supposed to know about it.
struct Recorder(Events);

#[async_trait]
impl TableEvents for Recorder {
    fn observes(&self, _table: &str, _op: WriteOp) -> bool {
        true
    }

    async fn emit(&self, _catalog: &Catalog, write: TableWrite<'_>) -> Result<()> {
        self.0.lock().expect("the event log").push(json!({
            "table": write.table.name,
            "op": write.op.as_str(),
            "row": write.row,
            "old_row": write.old_row,
        }));
        Ok(())
    }
}

async fn setup(db: &TestDb) -> Result<(Arc<Catalog>, Events)> {
    db.client()
        .await?
        .batch_execute(FIXTURE)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    let events: Events = Arc::new(Mutex::new(Vec::new()));
    catalog.set_table_events(Arc::new(Recorder(Arc::clone(&events))))?;
    Ok((catalog, events))
}

/// The GraphQL provider over both tables, with the aggregate fields switched on
/// — one test reads a mutation's returned row through the same selection a query
/// would use, aggregate field included.
fn provider(cat: &Catalog) -> Result<GraphqlProvider> {
    GraphqlProvider::project_with(
        "/graphql",
        &[cat.require("tasks")?, cat.require("projects")?],
        GraphqlLimits::new().aggregates(true),
    )
}

fn admin() -> Result<User> {
    User::new(uuid::Uuid::new_v4(), sc_auth::ROLE_ADMIN)
}

/// A caller at the public role, identified by an email an ownership formula can
/// read.
fn caller(email: &str) -> Result<User> {
    let mut user = User::new(uuid::Uuid::new_v4(), 100)?;
    user.extra
        .insert("email".to_owned(), Value::Text(email.to_owned()));
    Ok(user)
}

/// An evaluator that answers `owner === user.email` without JavaScript.
///
/// §7.3's write check is a **reified** one — it runs the formula against a
/// concrete row, because "the row as it would become" does not exist in the
/// database yet to be filtered — so a write to a table with an ownership formula
/// needs an evaluator. This stands in for V8: the tests here are about *which
/// row* the check is run against, not about the engine that answers it, and
/// pulling an isolate into this crate's test build to assert a string comparison
/// would be paying for the wrong thing.
struct OwnerIsCaller;

#[async_trait]
impl JsEvaluator for OwnerIsCaller {
    async fn eval(&self, call: FormulaCall) -> Result<bool> {
        let owner = call.row.get("owner");
        let email = call.user.as_ref().and_then(|u| u.get("email"));
        Ok(matches!((owner, email), (Some(a), Some(b)) if a == b))
    }

    async fn eval_value(&self, _call: FormulaCall) -> Result<Json> {
        Err(sc_error::Error::invalid("not part of this test"))
    }

    async fn run_code(&self, _call: sc_expr::CodeCall<'_>) -> Result<Json> {
        Err(sc_error::Error::invalid("not part of this test"))
    }
}

/// POST one document and return the response body.
async fn run_as(
    api: &GraphqlProvider,
    cat: &Arc<Catalog>,
    user: Option<&User>,
    document: &str,
) -> Result<Json> {
    let resp = api
        .handle(
            ApiRequest::new(Method::Post, "/graphql").body(json!({ "query": document })),
            cat,
            user,
        )
        .await?;
    assert_eq!(resp.status, 200, "{}", resp.body);
    Ok(resp.body)
}

/// The same, as an administrator.
async fn run(api: &GraphqlProvider, cat: &Arc<Catalog>, document: &str) -> Result<Json> {
    run_as(api, cat, Some(&admin()?), document).await
}

/// The `data` of a response, asserting there were no errors.
fn data(body: &Json) -> &Json {
    assert!(body.get("errors").is_none(), "{body}");
    &body["data"]
}

/// The first error's `extensions`, asserting there was one.
fn extensions(body: &Json) -> &Json {
    let errors = body["errors"].as_array().expect("errors in the body");
    assert!(!errors.is_empty(), "{body}");
    &errors[0]["extensions"]
}

/// The events recorded so far, cleared.
fn drain(events: &Events) -> Vec<Json> {
    std::mem::take(&mut *events.lock().expect("the event log"))
}

#[tokio::test]
async fn a_graphql_insert_and_a_rest_insert_are_the_same_write() -> Result<()> {
    let db = TestDb::new().await?;
    let (cat, events) = setup(&db).await?;
    let api = provider(&cat)?;
    let rest = RestProvider::project("/api", &[cat.require("tasks")?]);
    let user = admin()?;

    let body = run(
        &api,
        &cat,
        r#"mutation {
            insert_tasks(object: { title: "over graphql", done: false, priority: 7, project: 1 }) {
                id title done priority
            }
        }"#,
    )
    .await?;
    let graphql = data(&body)["insert_tasks"].clone();
    let graphql_events = drain(&events);

    let created = rest
        .handle(
            ApiRequest::new(Method::Post, "/api/tasks").body(
                json!({ "title": "over graphql", "done": false, "priority": 7, "project": 1 }),
            ),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(created.status, 201, "{}", created.body);
    let rest_events = drain(&events);

    // The same row, but for the generated id — which is the only thing the two
    // inserts could honestly disagree about.
    for column in ["title", "done", "priority"] {
        assert_eq!(
            graphql[column], created.body[column],
            "`{column}` differs: {graphql} vs {}",
            created.body
        );
    }
    assert!(graphql["id"].is_number(), "{graphql}");

    // …and the same event, raised by the row layer for both, with the caller
    // and the id the only difference.
    assert_eq!(graphql_events.len(), 1, "{graphql_events:#?}");
    assert_eq!(rest_events.len(), 1, "{rest_events:#?}");
    for event in [&graphql_events[0], &rest_events[0]] {
        assert_eq!(event["table"], json!("tasks"));
        assert_eq!(event["op"], json!("insert"));
        assert_eq!(event["row"]["title"], json!("over graphql"));
        assert_eq!(event["old_row"], Json::Null);
    }
    Ok(())
}

#[tokio::test]
async fn an_update_and_a_delete_go_through_the_row_layer_and_raise_its_events() -> Result<()> {
    let db = TestDb::new().await?;
    let (cat, events) = setup(&db).await?;
    let api = provider(&cat)?;

    let body = run(
        &api,
        &cat,
        r#"mutation {
            update_tasks_by_pk(pk_columns: { id: 1 }, set: { title: "rewritten", done: true }) {
                id title done priority
            }
        }"#,
    )
    .await?;
    // The untouched column is preserved rather than clobbered to null.
    assert_eq!(
        data(&body)["update_tasks_by_pk"],
        json!({ "id": 1, "title": "rewritten", "done": true, "priority": 3 })
    );
    let recorded = drain(&events);
    assert_eq!(recorded.len(), 1, "{recorded:#?}");
    assert_eq!(recorded[0]["op"], json!("update"));
    // An update's event carries the pre-image, which only the row layer can
    // produce — proof the write went through it rather than around it.
    assert_eq!(recorded[0]["old_row"]["title"], json!("write it"));

    let body = run(
        &api,
        &cat,
        "mutation { delete_tasks_by_pk(id: 3) { id title } }",
    )
    .await?;
    assert_eq!(
        data(&body)["delete_tasks_by_pk"],
        json!({ "id": 3, "title": "forget it" })
    );
    let recorded = drain(&events);
    assert_eq!(recorded.len(), 1, "{recorded:#?}");
    assert_eq!(recorded[0]["op"], json!("delete"));

    // And the row is gone from the database, not just from the response.
    let body = run(&api, &cat, "{ tasks_by_pk(id: 3) { id } }").await?;
    assert!(data(&body)["tasks_by_pk"].is_null(), "{body}");
    Ok(())
}

#[tokio::test]
async fn a_mutation_answers_with_the_row_a_query_would_have_returned() -> Result<()> {
    // An insert and an update read their row back, so a selection reaching
    // through a key or into a child aggregate is answered rather than nulled.
    let db = TestDb::new().await?;
    let (cat, _) = setup(&db).await?;
    let api = provider(&cat)?;

    let body = run(
        &api,
        &cat,
        r#"mutation {
            insert_tasks(object: { title: "reaching", project: 2 }) {
                title
                project { name }
            }
        }"#,
    )
    .await?;
    assert_eq!(
        data(&body)["insert_tasks"],
        json!({ "title": "reaching", "project": { "name": "Gemini" } })
    );

    // …and a child aggregate over the written row, which is a correlated
    // subquery of the read-back — the same column a query would have projected.
    let body = run(
        &api,
        &cat,
        r#"mutation {
            insert_projects(object: { name: "Mercury" }) {
                name
                tasks_aggregate { count }
                tasks { title }
            }
        }"#,
    )
    .await?;
    assert_eq!(
        data(&body)["insert_projects"],
        json!({ "name": "Mercury", "tasks_aggregate": { "count": 0 }, "tasks": [] })
    );

    // A delete has no row left to read, so the same question is refused rather
    // than answered `null` — a null there would read as "no project".
    let body = run(
        &api,
        &cat,
        "mutation { delete_tasks_by_pk(id: 1) { title project { name } } }",
    )
    .await?;
    let errors = body["errors"].to_string();
    assert!(errors.contains("project"), "{body}");
    assert!(errors.contains("mutation returned"), "{body}");
    Ok(())
}

#[tokio::test]
async fn an_update_is_refused_on_the_proposed_row_not_only_the_existing_one() -> Result<()> {
    // §7.3's WITH CHECK, at runtime: a caller may reach the row they own, and
    // may not use that reach to hand it to somebody else.
    let db = TestDb::new().await?;
    let (cat, _) = setup(&db).await?;
    bootstrap_table_meta(&cat).await?;
    let mut tasks = TableMeta::new("tasks");
    tasks.set_ownership_formula(Some("owner === user.email"));
    save_table_meta(&cat, &tasks).await?;
    let api = provider(&cat)?.with_evaluator(Arc::new(OwnerIsCaller));
    let ada = caller("ada@example.com")?;

    // Ada owns task 1 and may rewrite its title.
    let body = run_as(
        &api,
        &cat,
        Some(&ada),
        r#"mutation {
            update_tasks_by_pk(pk_columns: { id: 1 }, set: { title: "mine" }) { id title }
        }"#,
    )
    .await?;
    assert_eq!(
        data(&body)["update_tasks_by_pk"],
        json!({ "id": 1, "title": "mine" })
    );

    // …and may not move it out of her own ownership, even though she may reach
    // it: the check is on the row as it *would become*.
    let body = run_as(
        &api,
        &cat,
        Some(&ada),
        r#"mutation {
            update_tasks_by_pk(pk_columns: { id: 1 }, set: { owner: "bror@example.com" }) { id }
        }"#,
    )
    .await?;
    assert_eq!(extensions(&body)["code"], json!("FORBIDDEN"), "{body}");
    assert_eq!(extensions(&body)["table"], json!("tasks"), "{body}");

    // …and the row did not move.
    let body = run_as(&api, &cat, Some(&ada), "{ tasks_by_pk(id: 1) { owner } }").await?;
    assert_eq!(
        data(&body)["tasks_by_pk"]["owner"],
        json!("ada@example.com")
    );

    // A row she does not own is the same not-found an absent row gets, so a
    // mutation cannot be used to probe which rows exist.
    let body = run_as(
        &api,
        &cat,
        Some(&ada),
        r#"mutation {
            update_tasks_by_pk(pk_columns: { id: 2 }, set: { title: "not hers" }) { id }
        }"#,
    )
    .await?;
    assert_eq!(extensions(&body)["code"], json!("NOT_FOUND"), "{body}");
    let body = run_as(
        &api,
        &cat,
        Some(&ada),
        "mutation { delete_tasks_by_pk(id: 2) { id } }",
    )
    .await?;
    assert_eq!(extensions(&body)["code"], json!("NOT_FOUND"), "{body}");
    Ok(())
}

#[tokio::test]
async fn a_table_nobody_below_the_floor_may_write_refuses_at_resolve_time() -> Result<()> {
    // Decision 4: one schema per application. The mutation is in the SDL for
    // every caller; whether *this* caller may run it is decided when they do.
    let db = TestDb::new().await?;
    let (cat, events) = setup(&db).await?;
    let api = provider(&cat)?;
    assert!(api.sdl().contains("insert_tasks"), "{}", api.sdl());

    let public = User::new(uuid::Uuid::new_v4(), 100)?;
    for document in [
        r#"mutation { insert_tasks(object: { title: "sneaking in" }) { id } }"#,
        r#"mutation { update_tasks_by_pk(pk_columns: { id: 1 }, set: { title: "x" }) { id } }"#,
        "mutation { delete_tasks_by_pk(id: 1) { id } }",
    ] {
        let body = run_as(&api, &cat, Some(&public), document).await?;
        assert_eq!(
            extensions(&body)["code"],
            json!("FORBIDDEN"),
            "{document}: {body}"
        );
        assert!(
            body["errors"].to_string().contains("tasks"),
            "{document}: {body}"
        );
    }
    // Nothing was written, so nothing was observed.
    assert!(drain(&events).is_empty());
    Ok(())
}

#[tokio::test]
async fn a_validation_failure_names_the_field_it_was_about() -> Result<()> {
    let db = TestDb::new().await?;
    let (cat, _) = setup(&db).await?;
    let api = provider(&cat)?;

    // The `priority` column is a bigint; "soon" is not one, and the refusal is
    // the row layer's own coercion error naming the column it was about.
    let body = run(
        &api,
        &cat,
        r#"mutation { insert_tasks(object: { title: "x", priority: "soon" }) { id } }"#,
    )
    .await?;
    assert_eq!(extensions(&body)["code"], json!("BAD_USER_INPUT"), "{body}");
    assert_eq!(extensions(&body)["field"], json!("priority"), "{body}");

    // A `NOT NULL` column left out is the database's refusal, and it is a fault
    // to report rather than something the caller can restate — but it is still
    // an error rather than a row of nulls.
    let body = run(
        &api,
        &cat,
        "mutation { insert_tasks(object: { done: true }) { id } }",
    )
    .await?;
    assert!(body.get("errors").is_some(), "{body}");
    Ok(())
}

#[tokio::test]
async fn a_file_field_cannot_be_written_outside_its_store() -> Result<()> {
    let db = TestDb::new().await?;
    let (cat, _) = setup(&db).await?;
    bootstrap_file_stores(&cat).await?;
    bootstrap_field_meta(&cat).await?;

    let dir = std::env::temp_dir().join(format!("sc-graphql-mutations-{}", std::process::id()));
    std::fs::remove_dir_all(&dir).ok();
    std::fs::create_dir_all(dir.join("covers")).unwrap();
    save_file_store(&cat, &dir).await?;

    // `owner` becomes a `File` field constrained to `covers/` and PNGs — the
    // same overlay a REST caller's uploads are held to.
    let meta = FieldMeta::new("tasks", "owner").kind(DataFieldKind::File {
        store: FileStoreId("uploads".to_owned()),
        folder: Some("covers".to_owned()),
        mime_allow: vec!["image/png".to_owned()],
    });
    save_field_meta(&cat, &meta).await?;
    let api = provider(&cat)?;

    // Inside the folder, an allowed type: written, and read back as a path and
    // the URL the REST provider serves the bytes at.
    let body = run(
        &api,
        &cat,
        r#"mutation {
            insert_tasks(object: { title: "with a cover", owner: "covers/a.png" }) {
                owner { path url }
            }
        }"#,
    )
    .await?;
    let file = &data(&body)["insert_tasks"]["owner"];
    assert_eq!(file["path"], json!("covers/a.png"));
    assert!(
        file["url"].as_str().unwrap().starts_with("/api/tasks/"),
        "{file}"
    );

    // Outside the folder, and the wrong type: both refused by the field's own
    // rules, naming the field, exactly as they are on the REST path.
    for path in ["elsewhere/a.png", "covers/a.gif"] {
        let document = format!(
            r#"mutation {{ insert_tasks(object: {{ title: "nope", owner: "{path}" }}) {{ id }} }}"#
        );
        let body = run(&api, &cat, &document).await?;
        assert_eq!(
            extensions(&body)["code"],
            json!("BAD_USER_INPUT"),
            "{path}: {body}"
        );
        assert_eq!(extensions(&body)["field"], json!("owner"), "{path}: {body}");
    }
    std::fs::remove_dir_all(&dir).ok();
    Ok(())
}

/// Connect a local file store called `uploads` rooted at `dir`.
async fn save_file_store(cat: &Catalog, dir: &std::path::Path) -> Result<()> {
    sc_catalog::save_file_store(
        cat,
        &FileStoreDef::local("uploads", dir.to_string_lossy().as_ref()),
    )
    .await?;
    connect_all_file_stores(cat).await?;
    Ok(())
}
