//! Phase 9 integration test: an application's API authenticates against
//! `sc-auth`, and authorization is honored (design §7.2/§13.4).
//!
//! The round trip a React app actually makes: it is anonymous, it `login`s with
//! a password, the session that login starts identifies it on later calls, and
//! what it may then read or write is decided by its **role** — not by the fact
//! that it authenticated.

use std::sync::Arc;

use sc_api::{ApiProvider, ApiRequest, Method, RestProvider, SessionAction};
use sc_auth::{ROLE_ADMIN, ROLE_PUBLIC, SessionStore, User, bootstrap, create_user};
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;
use serde_json::json;

/// A catalog with a bootstrapped `users` table and one `posts` table.
async fn catalog(db: &TestDb) -> Result<Arc<Catalog>> {
    // The local test template may carry `users` tables from a v1 database; the
    // catalog keys tables by name alone, so clear them to reach the clean state
    // the MVP assumes. A no-op against CI's empty template.
    db.client()
        .await?
        .batch_execute(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; \
             CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    bootstrap(&cat).await?;
    Ok(Arc::new(cat))
}

fn provider(cat: &Catalog) -> Result<RestProvider> {
    Ok(RestProvider::project("/api", &[cat.require("posts")?]))
}

#[tokio::test]
async fn react_app_logs_in_against_sc_auth_and_the_session_identifies_it() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let api = provider(&cat)?;
    create_user(&cat, "editor@example.com", "correct-horse", ROLE_ADMIN).await?;

    // The app starts anonymous: it cannot read, and `whoami` tells it so.
    let anon = api
        .handle(ApiRequest::get("/api/posts"), &cat, None)
        .await?;
    assert_eq!(anon.status, 401);
    assert_eq!(
        api.handle(ApiRequest::get("/api/whoami"), &cat, None)
            .await?
            .status,
        401
    );

    // A wrong password does not authenticate...
    let bad = api
        .handle(
            ApiRequest::new(Method::Post, "/api/login")
                .body(json!({"email": "editor@example.com", "password": "wrong"})),
            &cat,
            None,
        )
        .await?;
    assert_eq!(bad.status, 401);
    assert_eq!(
        bad.session,
        SessionAction::Keep,
        "no session on a bad login"
    );

    // ...and neither does an unknown user — with the same answer, so the API does
    // not reveal which emails are registered.
    let unknown = api
        .handle(
            ApiRequest::new(Method::Post, "/api/login")
                .body(json!({"email": "nobody@example.com", "password": "correct-horse"})),
            &cat,
            None,
        )
        .await?;
    assert_eq!(unknown.status, 401);
    assert_eq!(unknown.body, bad.body);

    // The real password authenticates against sc-auth and starts a session.
    let ok = api
        .handle(
            ApiRequest::new(Method::Post, "/api/login")
                .body(json!({"email": "editor@example.com", "password": "correct-horse"})),
            &cat,
            None,
        )
        .await?;
    assert_eq!(ok.status, 200);
    assert_eq!(ok.body["email"], json!("editor@example.com"));
    assert_eq!(ok.body["role"], json!(i64::from(ROLE_ADMIN)));
    // The password hash never travels back.
    assert!(ok.body.get("password").is_none());
    assert!(ok.body.get("password_hash").is_none());

    // The provider does not touch cookies: it reports the session change and the
    // transport carries it. This is the seam `sc-server` mints the token at.
    let SessionAction::Start(user) = ok.session else {
        panic!(
            "a successful login must start a session, got {:?}",
            ok.session
        );
    };

    // That is exactly what a session store does with it — mint a token, and hand
    // the user back when the app presents it on the next request.
    let sessions = SessionStore::default();
    let token = sessions.login(user)?;
    let recovered = sessions
        .user_for(&token)?
        .ok_or_else(|| sc_error::Error::auth("the token just minted must identify its user"))?;

    // Authenticated, the same request now succeeds.
    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&recovered))
        .await?;
    assert_eq!(list.status, 200);

    let me = api
        .handle(ApiRequest::get("/api/whoami"), &cat, Some(&recovered))
        .await?;
    assert_eq!(me.body["email"], json!("editor@example.com"));

    // Logging out asks the transport to drop the token...
    let out = api
        .handle(
            ApiRequest::new(Method::Post, "/api/logout"),
            &cat,
            Some(&recovered),
        )
        .await?;
    assert_eq!(out.session, SessionAction::End);

    // ...and once it does, the token no longer identifies anyone.
    assert!(sessions.logout(&token)?);
    assert!(sessions.user_for(&token)?.is_none());
    Ok(())
}

#[tokio::test]
async fn authenticating_is_not_authorization() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let api = provider(&cat)?;

    // A real, logged-in user — at the least-privileged role.
    create_user(&cat, "reader@example.com", "correct-horse", ROLE_PUBLIC).await?;
    let login = api
        .handle(
            ApiRequest::new(Method::Post, "/api/login")
                .body(json!({"email": "reader@example.com", "password": "correct-horse"})),
            &cat,
            None,
        )
        .await?;
    assert_eq!(login.status, 200);
    let SessionAction::Start(reader) = login.session else {
        panic!("login must start a session");
    };

    // Being logged in is enough for `whoami`...
    assert_eq!(
        api.handle(ApiRequest::get("/api/whoami"), &cat, Some(&reader))
            .await?
            .status,
        200
    );

    // ...but the table's own access rules still decide the data (§7). An
    // introspected table is admin-only, so this authenticated user is forbidden —
    // a session is not a grant.
    let read = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&reader))
        .await?;
    assert_eq!(read.status, 403);

    let write = api
        .handle(
            ApiRequest::new(Method::Post, "/api/posts").body(json!({"title": "x"})),
            &cat,
            Some(&reader),
        )
        .await?;
    assert_eq!(write.status, 403);

    // The forbidden write never landed: an admin sees no rows.
    let admin = User::new(uuid::Uuid::new_v4(), ROLE_ADMIN)?;
    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&admin))
        .await?;
    assert_eq!(list.body.as_array().map(Vec::len), Some(0));
    Ok(())
}

#[tokio::test]
async fn a_malformed_login_is_rejected_before_any_password_check() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let api = provider(&cat)?;

    // Missing password, blank email, and a non-object body are malformed
    // requests, not failed logins.
    for body in [
        json!({"email": "a@b.c"}),
        json!({"email": "   ", "password": "pw"}),
        json!("nope"),
    ] {
        let err = api
            .handle(
                ApiRequest::new(Method::Post, "/api/login").body(body.clone()),
                &cat,
                None,
            )
            .await
            .map(|r| r.status)
            .expect_err(&format!("{body} must be rejected as malformed"));
        assert!(matches!(err.repr(), sc_error::Repr::Invalid(_)), "{err}");
    }
    Ok(())
}
