//! Phase 9 integration test: the REST [`ApiProvider`] against a real Postgres
//! (design §13.4).
//!
//! The projection and its dispatch rules are unit-tested in `sc-api`'s `rest`
//! module; what needs a database is the part that matters most — that a request
//! to a projected endpoint actually reads and writes the app's rows, and that
//! authorization is enforced on the way in.

use std::sync::Arc;

use sc_api::{ApiProvider, ApiRequest, ApiResponse, Method, RestProvider};
use sc_auth::User;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;
use serde_json::{Value as Json, json};
use uuid::Uuid;

/// A catalog over a per-test database holding one `posts` table.
async fn catalog_with_posts(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null, \
               views bigint)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Ok(Arc::new(
        Catalog::init(driver as Arc<dyn DatabaseDriver>).await?,
    ))
}

/// A provider over the app's declared table subset — `posts` only.
fn provider(cat: &Catalog) -> Result<RestProvider> {
    let posts = cat.require("posts")?;
    Ok(RestProvider::project("/api", &[posts]))
}

fn admin() -> Result<User> {
    User::new(Uuid::new_v4(), sc_auth::ROLE_ADMIN)
}

/// The rows of a list response.
fn rows(resp: &ApiResponse) -> Result<&Vec<Json>> {
    resp.body
        .as_array()
        .ok_or_else(|| sc_error::Error::invalid("list response is not an array"))
}

#[tokio::test]
async fn rest_crud_round_trip_through_the_provider() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_posts(&db).await?;
    let api = provider(&cat)?;
    let user = admin()?;

    // Empty to start.
    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&user))
        .await?;
    assert_eq!(list.status, 200);
    assert!(rows(&list)?.is_empty());

    // POST /api/posts creates a row and answers 201 with the inserted row,
    // including the database-generated id.
    let created = api
        .handle(
            ApiRequest::new(Method::Post, "/api/posts")
                .body(json!({ "title": "hello", "views": 1 })),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(created.status, 201);
    assert_eq!(created.body["title"], json!("hello"));
    let id = created.body["id"].as_i64().expect("generated id");

    // GET /api/posts now sees it.
    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&user))
        .await?;
    assert_eq!(rows(&list)?.len(), 1);
    assert_eq!(rows(&list)?[0]["title"], json!("hello"));

    // PUT /api/posts/{id} updates it and returns the updated row.
    let updated = api
        .handle(
            ApiRequest::new(Method::Put, format!("/api/posts/{id}"))
                .body(json!({ "title": "goodbye" })),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(updated.status, 200);
    assert_eq!(updated.body["title"], json!("goodbye"));
    // The untouched column is preserved, not clobbered to null.
    assert_eq!(updated.body["views"], json!(1));

    // DELETE /api/posts/{id} removes it.
    let deleted = api
        .handle(
            ApiRequest::new(Method::Delete, format!("/api/posts/{id}")),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(deleted.status, 200);

    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&user))
        .await?;
    assert!(rows(&list)?.is_empty());
    Ok(())
}

#[tokio::test]
async fn an_unauthorized_request_is_rejected_and_changes_nothing() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_posts(&db).await?;
    let api = provider(&cat)?;
    let user = admin()?;

    // An introspected table defaults to admin-only access (§7), so a public-role
    // user clears neither read nor write.
    let public = User::new(Uuid::new_v4(), sc_auth::ROLE_PUBLIC)?;

    let read = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&public))
        .await?;
    assert_eq!(read.status, 403, "under-privileged read must be forbidden");

    let write = api
        .handle(
            ApiRequest::new(Method::Post, "/api/posts").body(json!({ "title": "sneaky" })),
            &cat,
            Some(&public),
        )
        .await?;
    assert_eq!(write.status, 403);

    // An anonymous caller is unauthenticated rather than forbidden.
    let anon = api
        .handle(ApiRequest::get("/api/posts"), &cat, None)
        .await?;
    assert_eq!(anon.status, 401);

    // The rejected write never reached the database: authorization runs before
    // anything else, so a forbidden request has no side effects.
    let list = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&user))
        .await?;
    assert!(rows(&list)?.is_empty(), "a forbidden write must not insert");
    Ok(())
}

#[tokio::test]
async fn undeclared_tables_and_unknown_routes_are_not_reachable() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_posts(&db).await?;
    // The app declares no tables at all, so its API exposes no data — even though
    // `posts` exists in the catalog and the caller is an admin (§13.2). It still
    // projects its own auth endpoints; those are how a caller authenticates and
    // reach no table.
    let api = RestProvider::project("/api", &[]);
    let user = admin()?;
    assert!(api.endpoints().find("listPosts").is_none());
    assert!(api.endpoints().find("login").is_some());

    let resp = api
        .handle(ApiRequest::get("/api/posts"), &cat, Some(&user))
        .await?;
    assert_eq!(resp.status, 404, "an undeclared table must not be routable");

    // A declared table still 404s on a path it does not define, and 405s on a
    // method it does not answer.
    let api = provider(&cat)?;
    let resp = api
        .handle(ApiRequest::get("/api/posts/1/comments"), &cat, Some(&user))
        .await?;
    assert_eq!(resp.status, 404);

    let resp = api
        .handle(
            ApiRequest::new(Method::Patch, "/api/posts"),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(resp.status, 405);
    Ok(())
}

#[tokio::test]
async fn a_missing_row_is_not_found_and_a_bad_column_is_rejected() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_posts(&db).await?;
    let api = provider(&cat)?;
    let user = admin()?;

    // Updating a row that is not there is an error, not a silent success.
    let err = api
        .handle(
            ApiRequest::new(Method::Put, "/api/posts/999").body(json!({ "title": "ghost" })),
            &cat,
            Some(&user),
        )
        .await
        .expect_err("updating a missing row must fail");
    assert!(matches!(err.repr(), sc_error::Repr::NotFound(_)), "{err}");

    // A column the table does not have is rejected rather than ignored.
    let err = api
        .handle(
            ApiRequest::new(Method::Post, "/api/posts").body(json!({ "title": "x", "nope": 1 })),
            &cat,
            Some(&user),
        )
        .await
        .expect_err("an unknown column must fail");
    assert!(err.to_string().contains("nope"), "{err}");
    Ok(())
}

#[tokio::test]
async fn custom_routes_are_typed_but_stubbed() -> Result<()> {
    use sc_api::{Endpoint, HandlerRef, PathSpec, TypeSchema};

    let db = TestDb::new().await?;
    let cat = catalog_with_posts(&db).await?;
    let user = admin()?;

    let api = provider(&cat)?.with_custom_route(
        Endpoint::new("search", Method::Post, PathSpec::root().lit("api/search"))
            .input(TypeSchema::json())
            .output(TypeSchema::json())
            .auth(sc_api::AuthRequirement::admin())
            .handler(HandlerRef::Custom("select * from posts".to_owned())),
    );

    // The route is part of the contract...
    assert!(api.endpoints().find("search").is_some());

    // ...but the MVP does not run it, and says so rather than pretending.
    let resp = api
        .handle(
            ApiRequest::new(Method::Post, "/api/search").body(json!({ "q": "hello" })),
            &cat,
            Some(&user),
        )
        .await?;
    assert_eq!(resp.status, 501);

    // Auth is still enforced ahead of the stub: an anonymous caller is rejected
    // for being anonymous, not told the route is unimplemented.
    let anon = api
        .handle(ApiRequest::new(Method::Post, "/api/search"), &cat, None)
        .await?;
    assert_eq!(anon.status, 401);
    Ok(())
}
