//! Phase 2.3 integration test: a row write validates each value against its
//! field's **rich type and attributes**, and a violation is a client error
//! naming the field, with the row not written (design §6.1, §2.3).
//!
//! Rich fields cannot yet be *created* through the admin API — that is §3, the
//! `_sc_fields` overlay — so this drives the write path one seam below HTTP:
//! [`rows::create_row`], the exact function an application's REST POST funnels
//! into ([`RestProvider`](sc_api::RestProvider) calls it). A `people` table is
//! created for real in Postgres, then a catalog view of it is given rich fields
//! by hand — a `name` that is a `String` with a `max_length` and a `regex`, an
//! `age` that is an `Integer` with a `min`/`max` — and rows are written through
//! it. §3's admin API test closes the same loop over literal HTTP once a rich
//! field can be configured.
//!
//! What is asserted: a value that violates a rich rule is an `Invalid` error
//! (which the router maps to a 400) whose message **names the field**, and the
//! offending row is not in the table afterwards; a value that satisfies every
//! rule is written.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_api::rows;
use sc_catalog::{Catalog, Table};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Repr, Result};
use sc_test_harness::TestDb;
use sc_types::{Attrs, RichTypeRef, TypeRef};
use serde_json::json;

/// A catalog over a per-test database holding one physical `people` table with a
/// plain `text` name and a `bigint` age — the storage the rich types sit on.
async fn catalog_with_people(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE people (\
               id bigint generated by default as identity primary key, \
               name text not null, \
               age bigint)",
        )
        .await
        .map_err(|e| Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// Build an attribute bag from `(key, json)` pairs.
fn attrs(pairs: &[(&str, serde_json::Value)]) -> Attrs {
    let mut bag = Attrs::new();
    for (key, value) in pairs {
        bag.insert((*key).to_owned(), value.clone());
    }
    bag
}

/// The catalog's `people` table re-typed as it would be with a `_sc_fields`
/// overlay: `name` a `String` (≤ 5 letters, alphabetic), `age` an `Integer`
/// (0–120). This is the view §3.2 will produce; here it is assembled directly.
fn people_with_rich_fields(mut table: Table) -> Table {
    for field in &mut table.fields {
        match field.base.name.as_str() {
            "name" => {
                field.base.type_ = TypeRef::rich(RichTypeRef::resolve("string").unwrap());
                field.base.attributes =
                    attrs(&[("max_length", json!(5)), ("regex", json!("^[A-Za-z]+$"))]);
            }
            "age" => {
                field.base.type_ = TypeRef::rich(RichTypeRef::resolve("integer").unwrap());
                field.base.attributes = attrs(&[("min", json!(0)), ("max", json!(120))]);
            }
            _ => {}
        }
    }
    table
}

/// The number of rows currently in `table`.
async fn row_count(catalog: &Catalog, table: &Table) -> Result<usize> {
    Ok(rows::list_rows(catalog, table)
        .await?
        .as_array()
        .map_or(0, Vec::len))
}

#[tokio::test]
async fn a_row_satisfying_every_rich_rule_is_written() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog_with_people(&db).await?;
    let table = people_with_rich_fields(catalog.require("people")?);

    let row = rows::create_row(&catalog, &table, &json!({ "name": "Ann", "age": 30 })).await?;
    assert_eq!(row["name"], json!("Ann"));
    assert_eq!(row["age"], json!(30));
    assert_eq!(row_count(&catalog, &table).await?, 1);
    Ok(())
}

#[tokio::test]
async fn each_rich_violation_is_a_named_400_and_writes_no_row() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog_with_people(&db).await?;
    let table = people_with_rich_fields(catalog.require("people")?);

    // (body, the field the error must name, a fragment of the violation).
    let cases: &[(serde_json::Value, &str, &str)] = &[
        // String `max_length`: six letters over a five-letter limit.
        (json!({ "name": "Aurora", "age": 20 }), "name", "5"),
        // String `regex`: a digit where the pattern allows only letters.
        (json!({ "name": "A1", "age": 20 }), "name", "pattern"),
        // Integer `max`: above the range.
        (json!({ "name": "Ann", "age": 999 }), "age", "120"),
        // Integer `min`: below the range.
        (json!({ "name": "Ann", "age": -1 }), "age", "0"),
    ];

    for (body, field, fragment) in cases {
        let err = rows::create_row(&catalog, &table, body)
            .await
            .expect_err("the rich rule should reject this row");

        // `Invalid` is what the router maps to a 400 (not a 422): the rejection
        // is the request's fault, and the message reaches an app's user.
        assert!(
            matches!(err.repr(), Repr::Invalid(_)),
            "expected an Invalid (400) error, got {err:?}",
        );
        let message = err.to_string();
        assert!(
            message.contains(field),
            "error should name the field `{field}`: {message}",
        );
        assert!(
            message.contains(fragment),
            "error should explain the violation ({fragment}): {message}",
        );
    }

    // Not one of the four offending rows reached the table.
    assert_eq!(row_count(&catalog, &table).await?, 0);
    Ok(())
}

#[tokio::test]
async fn a_wrong_family_value_is_rejected_by_field_before_any_write() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = catalog_with_people(&db).await?;
    let table = people_with_rich_fields(catalog.require("people")?);

    // A non-numeric age never coerces to the `int8` the `Integer` sits on, so it
    // fails at the coercion step — still an `Invalid` naming the field.
    let err = rows::create_row(&catalog, &table, &json!({ "name": "Ann", "age": "old" }))
        .await
        .expect_err("a non-numeric age is not a valid integer");
    assert!(matches!(err.repr(), Repr::Invalid(_)), "{err:?}");
    assert!(err.to_string().contains("age"), "{err}");

    assert_eq!(row_count(&catalog, &table).await?, 0);
    Ok(())
}
