//! Saltcorn 1's `Table` **writing a real database** (the milestone "the v1
//! `Table` API", phase 4).
//!
//! The lowering is proved in `sc-expr`: a spy behind the sender asserts the plan
//! each v1 write sends and the shape it answers in. What is proved here is the
//! half a spy cannot — that the plan then *writes*, through the very same
//! `TableHost` a `db` chain goes through, which means three things a v1 plugin
//! author is entitled to:
//!
//! - **a write is an event.** Every one of these goes through the row layer, so
//!   the trigger an admin wrote sees a v1 plugin's `insertRow` exactly as it sees
//!   a `db.books.insert(…)`. That is the whole reason to have this method rather
//!   than a SQL statement.
//! - **whose write it is, is v1's argument.** `insertRow(row, user)` lowers to
//!   the plan's `{ user: id }` authority, and the named user goes through
//!   `sc_api::ownership`'s `*_as` functions — §7.3's rule, checked on the row as
//!   it is *and* on the row as it would become.
//! - **a refusal reads as v1's refusal.** `updateRow` answers a string and
//!   `tryUpdateRow` an `{ error }`, because that is what a v1 plugin branches on.
//!
//! The api is built here the way phase 6 will build it: over the run's own
//! sender (`db.__scSend`), the run's own trigger sender (`trigger.__scRun`) and
//! the run's own schema snapshot.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::{Arc, Mutex};

use sc_action::{
    Action, ActionContext, ActionRegistry, EventKind, Trigger, TriggerDispatcher,
    bootstrap_triggers, save_trigger,
};
use sc_api::code_host::{TableHost, TriggerRunHost, schema_snapshot};
use sc_auth::{User, create_user};
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_expr::{CodeCall, CodeRuntime, DenoEvaluator, JsEvaluator};
use sc_test_harness::TestDb;
use sc_types::FormField;
use serde_json::{Value as Json, json};

/// A library owned by email, which is what an ownership formula divides it by.
const SCHEMA: &str = "\
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text, pages bigint, owner text, read boolean default false); \
    INSERT INTO books (title, pages, owner, read) VALUES \
        ('Dune',      412, 'ada@example.com', false), \
        ('Emma',      474, 'bob@example.com', false), \
        ('Ilium',     576, 'ada@example.com', false), \
        ('Nostromo',  320, 'ada@example.com', false);";

/// The catalog over a fresh database, with the users table bootstrapped: a
/// **named** authority is a row of it, and this milestone's whole point is that
/// v1's `user` argument names one.
async fn setup(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    bootstrap_table_meta(&cat).await?;
    sc_auth::bootstrap(&cat).await?;
    Ok(cat)
}

/// Put an ownership formula on `books`, so a delegated write has a rule to meet.
async fn own_books(cat: &Catalog, formula: &str) -> Result<()> {
    let mut books = TableMeta::new("books");
    books.set_ownership_formula(Some(formula));
    save_table_meta(cat, &books).await?;
    assert!(
        cat.require("books")?.ownership.is_some(),
        "the formula is live"
    );
    Ok(())
}

/// A reader at role 40 — below `books`' admin-only floors, so what this user may
/// write is whatever the ownership formula grants and nothing else.
async fn reader(cat: &Catalog, email: &str) -> Result<User> {
    sc_auth::save_role(cat, &sc_auth::Role::new(40, "Reader"))
        .await
        .ok();
    create_user(cat, email, "correct-horse-battery", 40).await
}

/// Run `body` with the v1 `Table` and `Field` over this catalog, as the admin.
async fn v1(cat: &Catalog, body: &str) -> Result<Json> {
    v1_with(cat, None, body).await
}

/// The same, with a trigger host behind `run_trigger` when one is given.
async fn v1_with(cat: &Catalog, triggers: Option<&TriggerRunHost<'_>>, body: &str) -> Result<Json> {
    // With the formula engine behind it, because §7.3's write rule decides on
    // the row — the proposed one for an insert, and both the old and the new for
    // an update — and deciding on a row is what the evaluator is for.
    let host = TableHost::new(cat)
        .with_evaluator(Some(Arc::new(DenoEvaluator::new()) as Arc<dyn JsEvaluator>));
    let snapshot = schema_snapshot(cat)?;
    let runtime = CodeRuntime::with_workers(1);
    runtime
        .run(CodeCall {
            code: format!(
                "const {{ Table, Field }} = __scMakeV1Api(db.__scSend, __scSchema({}), \
                 typeof trigger === \"undefined\" ? null : trigger.__scRun);\n{body}",
                snapshot.generation()
            ),
            host: Some(&host),
            triggers: triggers.map(|t| t as &dyn sc_expr::TriggerHost),
            schema: Some(&snapshot),
            ..CodeCall::default()
        })
        .await
}

/// Every row of a table, by the shortest route that is not the code host itself.
async fn rows_of(db: &TestDb, sql: &str) -> Vec<Vec<Option<String>>> {
    db.client()
        .await
        .unwrap()
        .query(sql, &[])
        .await
        .unwrap()
        .iter()
        .map(|row| {
            (0..row.len())
                .map(|i| row.get::<_, Option<String>>(i))
                .collect()
        })
        .collect()
}

#[tokio::test]
async fn the_definition_of_dones_six_lines_read_and_write() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email").await?;
    let ada = reader(&cat, "ada@example.com").await?;

    // The milestone's own definition of done, run against a real database: a
    // synchronous `findOne`, a read with v1's where and selopts, and a write
    // addressed by the key the read answered.
    let out = v1(
        &cat,
        &format!(
            r#"const books = Table.findOne({{ name: "books" }});
               const recent = await books.getRows({{ pages: {{ gt: 400 }} }},
                                                  {{ orderBy: "title", limit: 10 }});
               const err = await books.updateRow({{ read: true }}, recent[0].id,
                                                 "{id}");
               return {{ pk: books.pk_name, titles: recent.map((b) => b.title),
                         err: err === undefined ? "ok" : err }};"#,
            id = ada.id
        ),
    )
    .await?;
    assert_eq!(out["pk"], json!("id"), "no host call answered this");
    // Read as the admin, so Emma is in it; written as ada, whose own row it is.
    assert_eq!(out["titles"], json!(["Dune", "Emma", "Ilium"]));
    assert_eq!(out["err"], json!("ok"), "v1 answers nothing when it worked");
    assert_eq!(
        rows_of(&db, "SELECT title FROM books WHERE read ORDER BY title").await,
        vec![vec![Some("Dune".to_owned())]],
    );
    Ok(())
}

#[tokio::test]
async fn every_v1_write_reaches_the_table_in_v1s_own_shapes() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;

    let out = v1(
        &cat,
        r#"const books = Table.findOne("books");
           const id = await books.insertRow({ title: "Ubik", pages: 224 });
           const tried = await books.tryInsertRow({ title: "Solaris", pages: 204 });
           const updated = await books.updateRow({ pages: 225 }, id);
           const triedUp = await books.tryUpdateRow({ pages: 226 }, id);
           await books.toggleBool(id, "read");
           const toggled = (await books.getRow({ id: id })).read;
           await books.toggleBool(id, "read");
           const back = (await books.getRow({ id: id })).read;
           await books.deleteRows({ title: "Solaris" });
           return {
             id: id, tried: tried,
             updated: updated === undefined ? "ok" : updated,
             triedUp: triedUp, toggled: toggled, back: back,
             pages: (await books.getRow({ id: id })).pages,
             left: await books.countRows(),
           };"#,
    )
    .await?;

    // v1's `insertRow` answers the primary key of the row it wrote.
    assert_eq!(out["id"], json!(5));
    assert_eq!(out["tried"], json!({ "success": 6 }));
    assert_eq!(out["updated"], json!("ok"));
    assert_eq!(out["triedUp"], json!({ "success": true }));
    assert_eq!(out["pages"], json!(226));
    // `toggleBool` is a read and a write here rather than v1's `SET f = NOT f`,
    // and it lands on the same value either way.
    assert_eq!(out["toggled"], json!(true));
    assert_eq!(out["back"], json!(false));
    assert_eq!(
        out["left"],
        json!(5),
        "the delete took Solaris and nothing else"
    );
    Ok(())
}

/// A trigger action that records the event it was handed.
struct Recorder(Arc<Mutex<Vec<Json>>>);

#[async_trait::async_trait]
impl Action for Recorder {
    fn name(&self) -> &str {
        "record"
    }
    fn description(&self) -> &str {
        "Record the event, for a test to read back"
    }
    fn config_spec(&self) -> Vec<FormField> {
        Vec::new()
    }
    async fn run(&self, ctx: &mut ActionContext<'_>) -> Result<Json> {
        let seen = json!({
            "kind": format!("{:?}", ctx.event.kind),
            "row": ctx.event.row,
            "payload": ctx.event.payload,
        });
        self.0.lock().unwrap().push(seen.clone());
        Ok(seen)
    }
}

/// The dispatcher, with `watch` on `books` for `kind` and a `manual` trigger
/// nothing fires but a body.
async fn watching(
    cat: &Catalog,
    kind: EventKind,
    seen: &Arc<Mutex<Vec<Json>>>,
) -> Result<Arc<TriggerDispatcher>> {
    let mut registry = ActionRegistry::new();
    registry.register(Arc::new(Recorder(Arc::clone(seen))) as Arc<dyn Action>)?;
    let dispatcher = Arc::new(TriggerDispatcher::new(Arc::new(registry)));
    bootstrap_triggers(cat).await?;
    save_trigger(
        cat,
        &dispatcher.registry(),
        &Trigger::new("watch", kind, "record").on("books"),
    )
    .await?;
    save_trigger(
        cat,
        &dispatcher.registry(),
        &Trigger::new("manual", EventKind::None, "record"),
    )
    .await?;
    dispatcher.reload(cat).await?;
    cat.set_table_events(Arc::clone(&dispatcher) as Arc<dyn sc_catalog::TableEvents>)?;
    Ok(dispatcher)
}

#[tokio::test]
async fn a_v1_write_is_an_event_the_tables_trigger_sees() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    let seen = Arc::new(Mutex::new(Vec::new()));
    let _dispatcher = watching(&cat, EventKind::Insert, &seen).await?;

    // The reason `insertRow` is worth having at all: it is the row layer's
    // write, so it is coerced, validated and **observed**, and an admin's
    // trigger does not learn that the plugin that caused it was written for
    // Saltcorn 1.
    v1(
        &cat,
        r#"const books = Table.findOne("books");
           await books.insertRow({ title: "Ubik", pages: 224, owner: "ada@example.com" });
           return null;"#,
    )
    .await?;

    let seen = seen.lock().unwrap().clone();
    assert_eq!(seen.len(), 1, "one write, one event: {seen:?}");
    assert_eq!(seen[0]["kind"], json!("Insert"));
    assert_eq!(seen[0]["row"]["title"], json!("Ubik"));
    Ok(())
}

#[tokio::test]
async fn a_v1_delete_is_an_event_per_row_it_took() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    let seen = Arc::new(Mutex::new(Vec::new()));
    let _dispatcher = watching(&cat, EventKind::Delete, &seen).await?;

    v1(
        &cat,
        r#"const books = Table.findOne("books");
           await books.deleteRows({ owner: "ada@example.com" });
           return null;"#,
    )
    .await?;

    // Three rows matched, so three events — the rows are resolved first and
    // written one at a time, which is what makes each one its own event.
    let seen = seen.lock().unwrap().clone();
    assert_eq!(seen.len(), 3, "{seen:?}");
    assert_eq!(
        rows_of(&db, "SELECT title FROM books ORDER BY title").await,
        vec![vec![Some("Emma".to_owned())]],
    );
    Ok(())
}

#[tokio::test]
async fn a_v1_run_trigger_goes_through_the_one_dispatcher() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    let seen = Arc::new(Mutex::new(Vec::new()));
    let dispatcher = watching(&cat, EventKind::Insert, &seen).await?;
    let triggers = TriggerRunHost::new(&dispatcher, &cat);

    let out = v1_with(
        &cat,
        Some(&triggers),
        r#"const books = Table.findOne("books");
           const ran = await books.run_trigger("manual", { id: 1, title: "Dune" });
           const missing = await books.run_trigger("nope", {}).then(
             () => "did not throw", (e) => e.message);
           return { ran: ran, missing: missing };"#,
    )
    .await?;

    // The action's own answer comes back, and the payload it saw is the row v1
    // handed over.
    assert_eq!(out["ran"]["payload"], json!({ "id": 1, "title": "Dune" }));
    assert!(
        out["missing"].as_str().unwrap_or_default().contains("nope"),
        "a trigger that is not there is named: {out}"
    );
    let seen = seen.lock().unwrap().clone();
    assert_eq!(seen.len(), 1, "through the dispatcher, once: {seen:?}");
    Ok(())
}

#[tokio::test]
async fn a_delegated_write_is_checked_as_the_row_is_and_as_it_would_become() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email").await?;
    let ada = reader(&cat, "ada@example.com").await?;

    let out = v1(
        &cat,
        &format!(
            r#"const books = Table.findOne("books");
               const ada = "{id}";
               return {{
                 // Her own row, left hers: granted.
                 own: await books.updateRow({{ pages: 999 }}, 1, ada),
                 // Somebody else's row: refused on the row **as it is**.
                 other: await books.updateRow({{ pages: 999 }}, 2, ada),
                 // Her own row, given away: refused on the row **as it would
                 // become**, which is the half a read-side check would miss.
                 away: await books.updateRow({{ owner: "bob@example.com" }}, 3, ada),
                 // And the same three through v1's other spelling.
                 tried: await books.tryUpdateRow({{ pages: 1 }}, 2, ada),
                 mine: await books.getRows({{}}, {{ forUser: ada, orderBy: "id" }})
                         .then((rs) => rs.map((r) => r.title)),
               }};"#,
            id = ada.id
        ),
    )
    .await?;

    assert_eq!(out["own"], Json::Null, "v1 answers nothing when it worked");
    // v1's convention, preserved: a **string** is the error, which is what
    // `if (err)` in eight years of plugins is written against.
    for key in ["other", "away"] {
        let message = out[key].as_str().unwrap_or_default();
        assert!(!message.is_empty(), "{key} should have been refused: {out}");
    }
    assert!(
        out["tried"]["error"].is_string(),
        "tryUpdateRow answers v1's other shape: {out}"
    );
    // The read through the same named user sees the same three rows the write
    // rule granted, because it is the same rule and the same functions.
    assert_eq!(out["mine"], json!(["Dune", "Ilium", "Nostromo"]));
    assert_eq!(
        rows_of(&db, "SELECT pages::text, owner FROM books ORDER BY id").await,
        vec![
            vec![Some("999".to_owned()), Some("ada@example.com".to_owned())],
            vec![Some("474".to_owned()), Some("bob@example.com".to_owned())],
            vec![Some("576".to_owned()), Some("ada@example.com".to_owned())],
            vec![Some("320".to_owned()), Some("ada@example.com".to_owned())],
        ],
        "only the write that was granted landed",
    );
    Ok(())
}

#[tokio::test]
async fn a_write_the_named_user_may_not_make_is_refused_as_v1_refuses_it() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = setup(&db).await?;
    own_books(&cat, "owner === user.email").await?;
    let ada = reader(&cat, "ada@example.com").await?;

    let out = v1(
        &cat,
        &format!(
            r#"const books = Table.findOne("books");
               const ada = "{id}";
               const threw = (p) => p.then(() => "did not throw", (e) => e.message);
               return {{
                 // An insert whose row the formula would not grant her.
                 insert: await threw(books.insertRow(
                   {{ title: "Ubik", owner: "bob@example.com" }}, ada)),
                 tried: await books.tryInsertRow(
                   {{ title: "Ubik", owner: "bob@example.com" }}, ada),
                 // Hers, so it is written.
                 own: await books.insertRow({{ title: "Ubik", owner: "ada@example.com" }}, ada),
                 // A delete of somebody else's row takes nothing: a row the
                 // caller cannot see is not a row they can reach by predicate.
                 deleted: await books.deleteRows({{ owner: "bob@example.com" }}, ada),
                 // A user who is not there is an error naming them, never a
                 // silent fall back to the admin's authority.
                 nobody: await threw(books.getRows(
                   {{}}, {{ forUser: "0d4e1e1e-0000-4000-8000-00000000dead" }})),
                 // v1's `forPublic` is the public role and nobody, which no
                 // lookup can improve on: the formula owns every row by an
                 // email, and an anonymous visitor has none, so the honest
                 // answer is no rows rather than an error.
                 public: (await books.getRows({{}}, {{ forPublic: true }})).length,
                 as_admin: (await books.getRows({{}})).length,
                 emma: await books.countRows({{ title: "Emma" }}),
               }};"#,
            id = ada.id
        ),
    )
    .await?;

    assert!(
        out["insert"].as_str().unwrap_or_default().contains("books"),
        "the refusal names the table: {out}"
    );
    assert!(out["tried"]["error"].is_string(), "{out}");
    assert!(out["own"].is_number(), "her own row was written: {out}");
    assert_eq!(out["deleted"], Json::Null);
    assert!(
        out["nobody"]
            .as_str()
            .unwrap_or_default()
            .contains("no user with id"),
        "{out}"
    );
    assert_eq!(out["public"], json!(0), "an anonymous visitor owns nothing");
    assert_eq!(
        out["as_admin"],
        json!(5),
        "and the run itself still reads it all"
    );
    assert_eq!(out["emma"], json!(1), "bob's row is still there");
    Ok(())
}
