// **Vue as an application framework** — the bundled module that proves §13.3's
// framework seam reaches past the frameworks written in Rust.
//
// `react` is a Rust framework: a handful of functions in `sc-app` that the
// registry switches a name onto. This is the same seven answers written down
// (`frameworks`), and the point of it is what an admin sees — a third entry in
// the framework picker, with its own settings form, its own default CSP, and a
// project Saltcorn writes for them — none of which required a line of Rust.
//
// What it is *not*
// ----------------
// A second serving implementation. A built Vue app is a static bundle with an
// SPA fallback, which is exactly what a built React app is, so serving, mounting
// and reloading are Saltcorn's and identical for both. What differs is the
// project and its idiom.
//
// Nor is it a second client generator. `src/feldspar/client.ts`, its helper,
// `schema.sql`, `SKILL.md` and the GraphQL client are written by **Saltcorn**,
// from the application's own API, on the same schedule for every framework. This
// module writes the half that is Vue's: the composables, the pages, the shell.
//
// The conventions, for a project named `todo` in file store `apps`
// -----------------------------------------------------------------
// | path | what it is |
// |---|---|
// | `todo/` | the project (Vite + Vue 3 + vue-router) |
// | `todo/dist` | the bundle Saltcorn serves |
// | `todo/src/feldspar/` | generated: rewritten on every build, never edited |
// | `todo/src/pages/*.vue` | one page per exposed table — yours from here |

/** The header every regenerated file carries, so the boundary between "yours"
 * and "ours" is visible in the file rather than only in the documentation. */
const GENERATED = `// Code generated by Saltcorn. DO NOT EDIT.
// Rewritten on every build; edits here are lost.
`;

// ---------------------------------------------------------------------------
// The declaration
// ---------------------------------------------------------------------------

/** The framework's settings: the same two `react` asks for, and for the same
 * reasons — a store is runtime state, so the list is a server query rather than
 * anything this module could enumerate, and the project directory is optional
 * because a store holding one application has no sub-directory to name. */
const config_fields = [
  {
    name: "store",
    label: "File store",
    type: "String",
    required: true,
    server_query: "file_stores",
  },
  {
    name: "project",
    label: "Project directory (blank for the store root)",
    type: "String",
    default: "",
  },
];

/** Where the source is and how it builds, as `{{ }}` templates over the settings
 * above — the same interpolation an email subject and an ownership formula go
 * through. A blank `project` collapses the segment it would have filled, which
 * is how "blank means the store root" stays one rule Saltcorn applies rather
 * than a conditional every framework writes. */
const build = {
  store: "{{ store }}",
  source: "{{ project }}",
  output: "{{ project }}/dist",
  command: "npm run build",
  install: { command: "npm install", marker: "node_modules" },
  runtime: "{{ project }}/src/feldspar",
  client: "client.ts",
};

/** The strict baseline with exactly the widenings a Vite bundle needs, and **no
 * `'unsafe-inline'` or `'unsafe-eval'` anywhere**: Vue's SFC compiler emits real
 * module scripts and a stylesheet file, and the styling below is a plain CSS
 * file rather than runtime `<style>` injection — which is what would otherwise
 * force `style-src 'unsafe-inline'` into every app's policy. */
const csp = {
  "img-src": ["'self'", "data:"],
  "font-src": ["'self'", "data:"],
  "connect-src": ["'self'"],
  "object-src": ["'none'"],
  "base-uri": ["'self'"],
  "frame-ancestors": ["'none'"],
};

/** The builder agent's system prompt: its role and this platform. How to work is
 * the `coding` trait's own prompt, which Saltcorn adds. */
const builder_prompt = `You build the \`{{ app }}\` application, a Vue 3 + Vite project served at \
the \`{{ subdomain }}\` subdomain. Its source is in the \`{{ store }}\` file store under \
\`{{ root }}\`, and your file tools are scoped to exactly that directory.

Three conventions of this framework: \`src/feldspar/\` is generated from the application's own \
API — its typed client and composables are rewritten on every build, so read it to learn what \
data is available but never edit it; the application's data is reached through that client, \
never by talking to a database; and pages are single-file components under \`src/pages/\`, \
registered in \`src/router.ts\`.`;

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

/** A path under the project. `""` is the project root, so a leading separator
 * never reaches a file store. */
const at = (dir, name) => (dir ? `${dir}/${name}` : name);

/** The row/insert/update types one file actually *names*.
 *
 * What a file uses and what it re-exports are different lists — a read-only
 * table's composables never mention its insert type — and an import of a type
 * nothing names is a `noUnusedLocals` failure in generated code the admin never
 * wrote. */
function usedRowTypes(table) {
  const used = [`${table.pascal}Row`];
  if (table.ops.create) used.push(`${table.pascal}Insert`);
  if (table.ops.update && table.pk) used.push(`${table.pascal}Update`);
  return used;
}

/** The literal a blank create form starts one column at. */
const emptyLiteral = (field) => field.empty;

// ---------------------------------------------------------------------------
// The generated runtime — Vue's half of `src/feldspar/`
// ---------------------------------------------------------------------------

/** `composables.ts`: a read, a write, and an invalidation, typed per table.
 *
 * The same three primitives React's `hooks.ts` supplies, over the same
 * one-version-counter-per-table cache — every read subscribes to its table,
 * every write bumps it. Keys are table names, which the server already
 * guarantees to be unique, so there is no query-key scheme to invent or get
 * wrong.
 *
 * Each composable answers **refs**, not unwrapped values, so a page destructures
 * them into top-level bindings (`const { data, loading } = useTasks()`) and Vue
 * unwraps them in the template. That is the one shape that is correct both in
 * `<script setup>` and in `<template>` without a `.value` sprinkled through the
 * markup. */
function composablesTs(ctx) {
  const rowTypes = ctx.tables.flatMap(usedRowTypes);
  let out = GENERATED;
  out += `
import { ref, shallowRef, watchEffect, type Ref } from "vue";
import { createClient, type ApiClient } from "./client";
`;
  if (rowTypes.length) out += `import type { ${rowTypes.join(", ")} } from "./client";\n`;
  out += `
/** The app's typed API client. Endpoint paths already include the API mount. */
export const api: ApiClient = createClient();

/** The state of one read: data, plus what is happening to it. */
export type Query<T> = {
  data: Ref<T | undefined>;
  error: Ref<Error | undefined>;
  loading: Ref<boolean>;
  /** Re-run this query (and any other on the same table). */
  refresh: () => void;
};

/** The state of one write. */
export type Mutation<A> = {
  run: (arg: A) => Promise<void>;
  pending: Ref<boolean>;
  error: Ref<Error | undefined>;
};

// One version counter per table: every read watches its table's counter, every
// write bumps it.
const versions = new Map<string, Ref<number>>();

function versionOf(table: string): Ref<number> {
  const known = versions.get(table);
  if (known) return known;
  const fresh = ref(0);
  versions.set(table, fresh);
  return fresh;
}

/** Discard what is cached for \`table\`, re-running every query over it. */
export function invalidate(table: string): void {
  versionOf(table).value += 1;
}

/**
 * Read something from the API, cached under \`table\` and re-run whenever
 * anything writes to that table.
 *
 * Exported because the per-table composables below cannot cover a custom
 * endpoint, and an app that adds one should be able to join the same cache
 * rather than build a second one beside it.
 */
export function useQuery<T>(table: string, load: () => Promise<T>): Query<T> {
  const data = shallowRef<T | undefined>(undefined);
  const error = shallowRef<Error | undefined>(undefined);
  const loading = ref(true);
  const version = versionOf(table);

  // Stopped automatically when the component that called this unmounts, which is
  // what makes a composable safe to call in \`setup\` and nowhere else.
  watchEffect((onCleanup) => {
    let cancelled = false;
    onCleanup(() => {
      cancelled = true;
    });
    // Read the counter, so this effect re-runs when the table is invalidated.
    void version.value;
    loading.value = true;
    load().then(
      (value) => {
        if (cancelled) return;
        data.value = value;
        error.value = undefined;
        loading.value = false;
      },
      (e: unknown) => {
        if (cancelled) return;
        data.value = undefined;
        error.value = e instanceof Error ? e : new Error(String(e));
        loading.value = false;
      },
    );
  });

  return { data, error, loading, refresh: () => invalidate(table) };
}

/**
 * Write through \`fn\`, then invalidate \`table\` so every query over it re-runs.
 * Exported for the same reason as \`useQuery\`.
 */
export function useMutation<A>(table: string, fn: (arg: A) => Promise<unknown>): Mutation<A> {
  const pending = ref(false);
  const error = shallowRef<Error | undefined>(undefined);
  const run = async (arg: A): Promise<void> => {
    pending.value = true;
    error.value = undefined;
    try {
      await fn(arg);
      invalidate(table);
    } catch (e: unknown) {
      error.value = e instanceof Error ? e : new Error(String(e));
    } finally {
      pending.value = false;
    }
  };
  return { run, pending, error };
}
`;
  for (const table of ctx.tables) out += `\n${tableComposables(table)}`;
  return out;
}

/** One table's composables, over that table's own object on the client. */
function tableComposables(table) {
  const { name, pascal, client, pk, pk_ts_type: key } = table;
  // What is re-exported follows the React generator's rule, because it follows
  // the *client's*: the insert and update types are emitted together for a table
  // the app lets anything write to.
  const exported = [`type ${pascal}Row`];
  if (table.ops.create || table.ops.update) {
    exported.push(`type ${pascal}Insert`, `type ${pascal}Update`);
  }

  let out = `// --- ${name} ---

// The row types come from the generated client, which derives them from this
// table's own columns; re-exported so a page imports its types and its
// composables from one place.
export { ${exported.join(", ")} } from "./client";

/** Every row of \`${name}\`, re-fetched when anything writes to it. */
export function use${pascal}(): Query<${pascal}Row[]> {
  return useQuery("${name}", () => api.${client}.list());
}
`;
  if (table.ops.create) {
    out += `
/** Insert a row into \`${name}\`. */
export function useCreate${pascal}(): Mutation<${pascal}Insert> {
  return useMutation("${name}", (row) => api.${client}.create(row));
}
`;
  }
  // Row-addressed operations: the API projects these only for a table with a
  // single-column primary key, so the composables follow the endpoints rather
  // than re-deciding it.
  if (pk) {
    if (table.ops.update) {
      out += `
/** Change a row of \`${name}\`. */
export function useUpdate${pascal}(): Mutation<{ id: ${key}; row: ${pascal}Update }> {
  return useMutation("${name}", ({ id, row }) => api.${client}.update(id, row));
}
`;
    }
    if (table.ops.delete) {
      out += `
/** Delete a row of \`${name}\`. */
export function useDelete${pascal}(): Mutation<${key}> {
  return useMutation("${name}", (id) => api.${client}.delete(id));
}
`;
    }
  }
  return out;
}

/** The generated directory's own README: what it is, and what to do when the
 * API it describes is missing something. */
function runtimeReadme(ctx) {
  const list = ctx.tables.length
    ? ctx.tables.map((t) => `- \`use${t.pascal}()\` — every row of \`${t.name}\``).join("\n")
    : "- (this application exposes no tables yet)";
  return `# \`${ctx.runtime}\` — generated

Everything in this directory is written by Saltcorn and **rewritten on every
build**. Edits here are lost. It is generated from the \`${ctx.app.name}\`
application's own API, so adding a table or a column in the admin UI makes the
matching types and composables exist at the next build, with nobody regenerating
anything by hand.

| file | what it is |
|---|---|
| \`client.ts\` | the typed API client: one method per endpoint this application exposes |
| \`helper.ts\` | how a request is made and how a failure is reported — the same in every application |
| \`composables.ts\` | Vue composables over that client, one set per table |
| \`schema.sql\` | a description of this application's tables, for writing SQL against |
| \`SKILL.md\` | the half of the application that is *not* in this repository |

## The composables

${list}

Each answers **refs**. Destructure them into top-level bindings in
\`<script setup>\` and the template unwraps them for you — that is the one shape
that is correct both in script and in markup, with no \`.value\` in the template:

\`\`\`ts
const { data, error, loading } = ${ctx.tables.length ? `use${ctx.tables[0].pascal}` : "useSomething"}();
\`\`\`

A write is a \`Mutation\`: call \`run\`, and every query over that table re-runs.

## The API is missing something I need

Add a custom SQL query to the application and it becomes a typed method on
\`client.ts\` at the next build:

\`\`\`sh
feldspar api add-query --app ${ctx.app.subdomain} --name recentPosts \\
  --sql "SELECT * FROM posts ORDER BY published DESC LIMIT :n"
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// The project, written once
// ---------------------------------------------------------------------------

function packageJson(ctx) {
  return `{
  "name": "${ctx.name}",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "typecheck": "vue-tsc --noEmit",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.0",
    "vue-router": "^4.5.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^6.0.0",
    "typescript": "^5.9.0",
    "vite": "^7.0.0",
    "vue-tsc": "^3.0.0"
  }
}
`;
}

/** `vue-tsc --noEmit` runs *before* `vite build` on purpose: the client is
 * regenerated from the app's endpoints on every build, so a table removed in the
 * admin UI should fail the build with a type error naming the call site, not
 * produce a bundle that 404s at runtime. */
const VITE_CONFIG = `import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

export default defineConfig({
  plugins: [vue()],
});
`;

/** `.vue` files are listed explicitly: TypeScript's \`include\` of a directory
 * picks up the extensions *it* knows, and \`.vue\` is one only \`vue-tsc\` adds. */
const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "verbatimModuleSyntax": true,
    "skipLibCheck": true,
    "noEmit": true,
    "types": ["vite/client"]
  },
  "include": ["src/**/*.ts", "src/**/*.vue", "vite.config.ts"]
}
`;

function indexHtml(ctx) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ctx.name}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`;
}

/** `node_modules` and `dist` only. The generated runtime is **not** ignored: it
 * is part of the source an admin reads and type-checks against, and a git repo
 * that omits it cannot be built anywhere but here. The last lines are the
 * session files `feldspar auth token` writes — live credentials for this
 * application, and a project that committed one would be handing out a
 * logged-in browser. */
const GITIGNORE = `node_modules
dist
*.local
.feldspar-session
.feldspar-session.json
`;

function mainTs() {
  return `import { createApp } from "vue";

import App from "./App.vue";
import { router } from "./router";
import "./app.css";

createApp(App).use(router).mount("#app");
`;
}

/** The shell: a header naming the app, a nav built from the route list, the
 * signed-in user, and the routes themselves.
 *
 * Without auth there is no user to show and no gate to apply, so the header's
 * last cell is simply not written — keeping it against a user that is always
 * `null` would generate an app permanently displaying "not signed in" beside a
 * sign-out button that cannot do anything. */
function appVue(ctx) {
  const links = ctx.tables
    .map((t) => `      <RouterLink to="/${t.name}">${t.title}</RouterLink>`)
    .join("\n");
  const imports = ctx.auth
    ? `import { RouterLink, RouterView } from "vue-router";\nimport { signOut, user } from "./auth";`
    : `import { RouterLink, RouterView } from "vue-router";`;
  const userCell = ctx.auth
    ? `
    <span v-if="user" class="sc-user">{{ user.email }}</span>
    <button v-if="user" @click="signOut">Sign out</button>`
    : "";
  return `<script setup lang="ts">
${imports}
</script>

<template>
  <header class="sc-header">
    <strong>${ctx.name}</strong>
    <nav>
      <RouterLink to="/">Home</RouterLink>
${links}
    </nav>${userCell}
  </header>
  <main>
    <RouterView />
  </main>
</template>
`;
}

/** The routes, as data.
 *
 * **Authenticated unless the application cannot sign anyone in**: the gate is a
 * navigation guard that asks who the user is once and sends an anonymous visitor
 * to the login page. An app with no auth endpoints gets no guard and no login
 * page — that statement is about a scaffold's *routes*, and it cannot lock a
 * door that has no key. */
function routerTs(ctx) {
  const imports = ctx.tables
    .map((t) => `import ${t.pascal} from "./pages/${t.pascal}.vue";`)
    .join("\n");
  const routes = ctx.tables
    .map((t) => `  { path: "/${t.name}", component: ${t.pascal} },`)
    .join("\n");
  let out = `import { createRouter, createWebHistory } from "vue-router";

import Home from "./pages/Home.vue";
${imports}${imports ? "\n" : ""}`;
  if (ctx.auth) out += `import Login from "./Login.vue";\nimport { currentUser } from "./auth";\n`;
  out += `
export const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: "/", component: Home },
${routes}${routes ? "\n" : ""}`;
  if (ctx.auth) out += `    { path: "/login", component: Login, meta: { public: true } },\n`;
  out += `  ],
});
`;
  if (ctx.auth) {
    out += `
// Asked once and cached: \`currentUser\` calls the API the first time and answers
// from the ref afterwards, so a click between two pages does not become a second
// round trip.
router.beforeEach(async (to) => {
  if (to.meta.public) return true;
  return (await currentUser()) ? true : { path: "/login" };
});
`;
  }
  return out;
}

/** The auth layer: module-level state, because who is signed in is a property of
 * the session and not of any one component.
 *
 * Generated only when the application exposes `login` / `logout` / `whoami`
 * through its API — all three or none, since a partial set means the provider
 * changed underneath and half an auth layer against it does not compile. */
const AUTH_TS = `import { ref } from "vue";

import { api } from "./feldspar/composables";

export type User = { id: string; email: string; role: number };

/** The signed-in user: \`null\` when anonymous, \`undefined\` until asked. */
export const user = ref<User | null | undefined>(undefined);

/** The user, asking the server the first time and answering from the ref after.
 *
 * A 401 from \`whoami\` is the ordinary anonymous case, not an error to report. */
export async function currentUser(): Promise<User | null> {
  if (user.value === undefined) {
    user.value = await api.whoami().then(
      (u) => u,
      () => null,
    );
  }
  return user.value;
}

export async function signIn(email: string, password: string): Promise<void> {
  user.value = await api.login({ email, password });
}

export async function signOut(): Promise<void> {
  await api.logout();
  user.value = null;
}
`;

const LOGIN_VUE = `<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";

import { signIn } from "./auth";

const router = useRouter();
const email = ref("");
const password = ref("");
const error = ref<string | undefined>(undefined);
const busy = ref(false);

async function submit(): Promise<void> {
  busy.value = true;
  error.value = undefined;
  try {
    await signIn(email.value, password.value);
    await router.push("/");
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : String(e);
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <form class="card sc-login" @submit.prevent="submit">
    <h1>Sign in</h1>
    <label>
      Email
      <input v-model="email" type="email" autocomplete="username" />
    </label>
    <label>
      Password
      <input v-model="password" type="password" autocomplete="current-password" />
    </label>
    <p v-if="error" class="sc-error">{{ error }}</p>
    <button type="submit" :disabled="busy">{{ busy ? "Signing in…" : "Sign in" }}</button>
  </form>
</template>
`;

/** The landing page: what this application is, and where its data is. */
function homeVue(ctx) {
  const list = ctx.tables.length
    ? ctx.tables
        .map((t) => `      <li><RouterLink to="/${t.name}">${t.title}</RouterLink></li>`)
        .join("\n")
    : `      <li>This application exposes no tables yet. Add one in the admin UI, then
        rebuild — a page and typed composables appear for it.</li>`;
  return `<script setup lang="ts">
import { RouterLink } from "vue-router";
</script>

<template>
  <h1>${ctx.app.name}</h1>
  <p>A Vue application served by Saltcorn.</p>
  <ul>
${list}
  </ul>
</template>
`;
}

/** One table's page: the rows, a create form for the columns a write may set,
 * and a delete button — each written only when the application's API actually
 * offers it. */
function pageVue(table) {
  const { pascal, name, client, pk } = table;
  const canCreate = table.ops.create;
  const canDelete = table.ops.delete && !!pk;

  const composables = [`use${pascal}`];
  if (canCreate) composables.push(`useCreate${pascal}`);
  if (canDelete) composables.push(`useDelete${pascal}`);

  let script = "";
  if (canCreate) script += `import { ref } from "vue";\n\n`;
  script += `import { ${composables.join(", ")} } from "../feldspar/composables";\n\n`;
  script += `const { data, error, loading } = use${pascal}();\n`;
  if (canCreate) {
    const empty = table.form.inputs
      .map((f) => `  ${f.name}: ${emptyLiteral(f)}`)
      .join(",\n");
    const minted = table.form.minted
      .map((n) => `${n}: crypto.randomUUID()`)
      .join(", ");
    const argument = minted ? `{ ...form.value, ${minted} }` : `{ ...form.value }`;
    script += `const create = useCreate${pascal}();
const { pending: creating, error: createError } = create;

const empty = {
${empty}
};
const form = ref({ ...empty });

async function add(): Promise<void> {
  await create.run(${argument});
  form.value = { ...empty };
}
`;
  }
  if (canDelete) {
    script += `const remove = useDelete${pascal}();
const { error: deleteError } = remove;
`;
  }

  const headers = table.fields.map((f) => `        <th>${f.label}</th>`).join("\n");
  const cells = table.fields
    .map((f) => `        <td>{{ row.${f.name} ?? "" }}</td>`)
    .join("\n");

  let template = `  <h1>${table.title}</h1>\n`;
  if (canCreate) {
    const controls = table.form.inputs.map((f) => formControl(f)).join("\n");
    template += `  <form class="card" @submit.prevent="add">
${controls}
    <button type="submit" :disabled="creating">Add</button>
  </form>
  <p v-if="createError" class="sc-error">{{ createError.message }}</p>
`;
  }
  if (canDelete) {
    template += `  <p v-if="deleteError" class="sc-error">{{ deleteError.message }}</p>\n`;
  }
  template += `  <p v-if="loading">Loading…</p>
  <p v-else-if="error" class="sc-error">{{ error.message }}</p>
  <table v-else>
    <thead>
      <tr>
${headers}${canDelete ? "\n        <th></th>" : ""}
      </tr>
    </thead>
    <tbody>
      <tr v-for="row in data ?? []" :key="${pk ? `String(row.${pk})` : "JSON.stringify(row)"}">
${cells}${
    canDelete
      ? `\n        <td><button @click="remove.run(row.${pk})">Delete</button></td>`
      : ""
  }
      </tr>
    </tbody>
  </table>
`;

  return `<script setup lang="ts">
${script}</script>

<template>
${template}</template>
`;
}

/** A labelled input bound into the create form's state, typed by the column.
 *
 * Which of the three it is was decided by Saltcorn (`control`), not re-derived
 * here from a type spelling this module would have to keep in step. */
function formControl(field) {
  const bind =
    field.control === "checkbox"
      ? `v-model="form.${field.name}" type="checkbox"`
      : field.control === "number"
        ? `v-model.number="form.${field.name}" type="number"`
        : `v-model="form.${field.name}"`;
  return `    <label>
      ${field.label}
      <input ${bind} />
    </label>`;
}

/** The project root's guide for coding agents. Written **once**, by the
 * scaffold, and never rewritten: agents append to it, and clobbering it would
 * destroy their work. */
function agentsMd(ctx) {
  const tables = ctx.tables.length
    ? ctx.tables.map((t) => `- \`${t.name}\` → \`src/pages/${t.pascal}.vue\``).join("\n")
    : "- (none yet)";
  return `# ${ctx.app.name}

A Vue 3 + Vite application served by Saltcorn at ${ctx.app.url}.

## Layout

| path | what it is |
|---|---|
| \`src/main.ts\` | the entry point |
| \`src/App.vue\` | the shell: header, nav, \`<RouterView>\` |
| \`src/router.ts\` | the routes${ctx.auth ? ", and the guard that requires a signed-in user" : ""} |
| \`src/pages/\` | one single-file component per table — **yours to change** |
| \`src/app.css\` | plain CSS with custom properties, both colour schemes |
| \`${ctx.runtime}/\` | **generated** — see its own README |

${tables}

## Rules

1. **Never edit \`${ctx.runtime}/\`.** It is regenerated from the application's
   API on every build; your edits are lost. Read it to learn what data exists.
2. **Reach data through \`${ctx.client}\`**, or the composables beside it. There is
   no database connection in this project and there is not meant to be.
3. **Build before reporting a change done**: \`npm run build\` type-checks every
   file in the project against the generated client, which is where a drift
   between this project and the application's API shows up.
${
  ctx.auth
    ? `4. **Every route requires a signed-in user** except \`/login\`. Mark a route
   \`meta: { public: true }\` to open it.\n`
    : ""
}
## Adding data the API does not have

\`\`\`sh
feldspar api add-query --app ${ctx.app.subdomain} --name recentPosts \\
  --sql "SELECT * FROM posts ORDER BY published DESC LIMIT :n"
\`\`\`

The query becomes a typed method on \`${ctx.client}\` at the next build.
`;
}

const APP_CSS = `:root {
  --bg: #ffffff;
  --fg: #1a1c1e;
  --muted: #5c6470;
  --line: #dfe3e8;
  --accent: #41b883;
  --radius: 8px;
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16181c;
    --fg: #e8eaed;
    --muted: #9aa3af;
    --line: #2c3038;
    --accent: #6fd8a8;
  }
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 16px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
}

.sc-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem 1.25rem;
  border-bottom: 1px solid var(--line);
}

.sc-header nav {
  display: flex;
  gap: 0.75rem;
  flex: 1;
}

.sc-header a {
  color: var(--muted);
  text-decoration: none;
}

.sc-header a.router-link-active {
  color: var(--accent);
  font-weight: 600;
}

.sc-user {
  color: var(--muted);
  font-size: 0.875rem;
}

main {
  max-width: 60rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem;
}

.card {
  display: flex;
  flex-wrap: wrap;
  align-items: end;
  gap: 0.75rem;
  padding: 1rem;
  border: 1px solid var(--line);
  border-radius: var(--radius);
  margin-bottom: 1.5rem;
}

label {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  font-size: 0.875rem;
  color: var(--muted);
}

input {
  font: inherit;
  color: var(--fg);
  background: var(--bg);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 0.4rem 0.6rem;
}

button {
  font: inherit;
  cursor: pointer;
  color: #fff;
  background: var(--accent);
  border: 0;
  border-radius: var(--radius);
  padding: 0.45rem 0.9rem;
}

button:disabled {
  opacity: 0.6;
  cursor: default;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  text-align: left;
  padding: 0.5rem 0.6rem;
  border-bottom: 1px solid var(--line);
}

th {
  color: var(--muted);
  font-size: 0.8125rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.sc-error {
  color: #c0392b;
}

.sc-login {
  flex-direction: column;
  align-items: stretch;
  max-width: 22rem;
  margin: 3rem auto;
}
`;

// ---------------------------------------------------------------------------
// The two generators
// ---------------------------------------------------------------------------

/** The whole project, written once when the application is created.
 *
 * Paths are relative to the project directory. The generated client, its helper,
 * `schema.sql` and `SKILL.md` are **not** here: Saltcorn writes those into
 * `ctx.runtime` for every framework, from the application's own API. */
function scaffold(ctx) {
  const files = [
    { path: "package.json", contents: packageJson(ctx) },
    { path: "vite.config.ts", contents: VITE_CONFIG },
    { path: "tsconfig.json", contents: TSCONFIG },
    { path: "index.html", contents: indexHtml(ctx) },
    { path: ".gitignore", contents: GITIGNORE },
    { path: "AGENTS.md", contents: agentsMd(ctx) },
    { path: "src/main.ts", contents: mainTs() },
    { path: "src/App.vue", contents: appVue(ctx) },
    { path: "src/router.ts", contents: routerTs(ctx) },
    { path: "src/app.css", contents: APP_CSS },
    { path: "src/pages/Home.vue", contents: homeVue(ctx) },
  ];
  if (ctx.auth) {
    files.push({ path: "src/auth.ts", contents: AUTH_TS });
    files.push({ path: "src/Login.vue", contents: LOGIN_VUE });
  }
  for (const table of ctx.tables) {
    files.push({ path: `src/pages/${table.pascal}.vue`, contents: pageVue(table) });
  }
  return files.concat(runtime(ctx));
}

/** The framework's own generated code, rewritten on every build and whenever the
 * application's definition changes — so a table added in the admin UI has a
 * `useNewTable()` at the next build, with nobody regenerating anything by hand. */
function runtime(ctx) {
  return [
    { path: at(ctx.runtime, "composables.ts"), contents: composablesTs(ctx) },
    { path: at(ctx.runtime, "README.md"), contents: runtimeReadme(ctx) },
  ];
}

module.exports = {
  sc_plugin_api_version: 1,
  plugin_name: "vue",
  frameworks: {
    vue: {
      label: "Vue",
      description:
        "Saltcorn creates a Vue 3 + Vite project, generates a typed client and composables " +
        "for your tables, installs its dependencies and builds it. Pick a file store and a name.",
      config_fields,
      build,
      csp,
      builder_prompt,
      // What the builder agent's `check` runs before the application build.
      checks: ["typecheck"],
      scaffold,
      runtime,
    },
  },
};
