//! Shared integration-test harness (principle 4: integration-tested against a
//! real database).
//!
//! Every test gets its **own freshly created Postgres database**, so tests are
//! fully isolated — including schema/DDL and `information_schema` introspection,
//! which the catalog relies on — and may run in parallel. The database is
//! dropped when the [`TestDb`] handle is dropped.
//!
//! The base connection is read from the `DATABASE_URL` environment variable
//! (the same one CI sets); if unset it falls back to a conventional local
//! default. The named database in that URL is only used as the *maintenance*
//! connection from which per-test databases are created and dropped — the tests
//! themselves never touch it.
//!
//! ```no_run
//! # async fn ex() -> sc_error::Result<()> {
//! let db = sc_test_harness::TestDb::new().await?;
//! let client = db.client().await?;
//! client.batch_execute("create table t (id int)").await.unwrap();
//! // ... db is dropped (and the database deleted) at end of scope ...
//! # Ok(()) }
//! ```
//!
//! It also carries [`TestSmtp`], a local SMTP server that accepts one message,
//! for the same reason: a test of the mail transport that never puts bytes on a
//! socket is a test of a mock.

pub mod smtp;

pub use smtp::{SmtpMessage, TestSmtp};

use deadpool_postgres::{Manager, ManagerConfig, Object, Pool, RecyclingMethod};
use sc_error::{Error, Result};
use tokio_postgres::{Client, Config, NoTls};
use uuid::Uuid;

/// Fallback used when `DATABASE_URL` is not set. Matches the Postgres service
/// wired up in CI so a bare `cargo test` works there without extra config.
const DEFAULT_URL: &str = "postgres://saltcorn:saltcorn@localhost:5432/saltcorn_test";

/// The maintenance database used to create and drop per-test databases. Present
/// on every standard Postgres install.
const MAINTENANCE_DB: &str = "postgres";

/// A handle to a freshly created, isolated Postgres database for one test.
///
/// Dropping the handle deletes the database (best effort). Prefer letting it
/// drop at the end of the test; the underlying connections are closed first so
/// the `DROP DATABASE` succeeds.
pub struct TestDb {
    /// Name of the per-test database (a unique, identifier-safe string).
    name: String,
    /// Pool of connections to the per-test database, handed to the test.
    pool: Pool,
    /// Connection config pointing at the maintenance database, used to drop the
    /// per-test database on teardown.
    admin_config: Config,
}

impl TestDb {
    /// Create a new, empty Postgres database and return a handle with a pool
    /// connected to it.
    pub async fn new() -> Result<TestDb> {
        let base = base_config()?;

        // Unique, identifier-safe name: `simple` renders 32 hex chars, so with
        // the `sc_test_` prefix the whole thing is a valid unquoted identifier.
        let name = format!("sc_test_{}", Uuid::new_v4().simple());

        let admin_config = with_dbname(&base, MAINTENANCE_DB);
        let admin = connect(&admin_config).await?;
        // Identifiers cannot be parameterised; `name` is generated by us from a
        // UUID (no attacker input), so interpolation here is safe. Quoted
        // defensively all the same.
        //
        // `SC_TEST_TEMPLATE` optionally names the template database to clone
        // from. It defaults to the server default (`template1`); a dev box whose
        // `template1` has a glibc collation-version mismatch (which makes
        // `CREATE DATABASE` fail) can point this at a database it owns and has
        // run `ALTER DATABASE … REFRESH COLLATION VERSION` on. CI leaves it
        // unset, so its behaviour is unchanged.
        let create = match std::env::var("SC_TEST_TEMPLATE") {
            Ok(t) if !t.is_empty() => {
                format!("CREATE DATABASE \"{name}\" TEMPLATE \"{t}\"")
            }
            _ => format!("CREATE DATABASE \"{name}\""),
        };
        admin
            .batch_execute(&create)
            .await
            .map_err(|e| Error::database(format!("create database {name}: {e}")))?;

        let pool = build_pool(&with_dbname(&base, &name))?;

        Ok(TestDb {
            name,
            pool,
            admin_config,
        })
    }

    /// The name of the per-test database.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// The connection pool for the per-test database.
    pub fn pool(&self) -> &Pool {
        &self.pool
    }

    /// Check out a pooled connection to the per-test database.
    pub async fn client(&self) -> Result<Object> {
        self.pool
            .get()
            .await
            .map_err(|e| Error::database(format!("checkout connection: {e}")))
    }
}

impl Drop for TestDb {
    fn drop(&mut self) {
        // Close pooled connections so nothing blocks `DROP DATABASE`.
        self.pool.close();

        let name = self.name.clone();
        let admin_config = self.admin_config.clone();

        // Drop is synchronous and we may be inside a tokio runtime, so we cannot
        // block on the current runtime. Run the async teardown on a dedicated
        // thread with its own single-threaded runtime.
        let _ = std::thread::spawn(move || {
            let runtime = match tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
            {
                Ok(rt) => rt,
                Err(_) => return,
            };
            runtime.block_on(async move {
                if let Ok(admin) = connect(&admin_config).await {
                    // `WITH (FORCE)` (PG13+) terminates any lingering backends.
                    let _ = admin
                        .batch_execute(&format!("DROP DATABASE IF EXISTS \"{name}\" WITH (FORCE)"))
                        .await;
                }
            });
        })
        .join();
    }
}

/// Parse the base connection config from `DATABASE_URL` (or the default).
fn base_config() -> Result<Config> {
    let url = std::env::var("DATABASE_URL").unwrap_or_else(|_| DEFAULT_URL.to_string());
    url.parse::<Config>()
        .map_err(|e| Error::config(format!("invalid DATABASE_URL: {e}")))
}

/// Clone `config` with its target database name replaced.
fn with_dbname(config: &Config, dbname: &str) -> Config {
    let mut c = config.clone();
    c.dbname(dbname);
    c
}

/// Open a one-off connection and drive it on a background task.
async fn connect(config: &Config) -> Result<Client> {
    let (client, connection) = config
        .connect(NoTls)
        .await
        .map_err(|e| Error::database(format!("connect: {e}")))?;
    tokio::spawn(async move {
        // When the client is dropped the connection future resolves; ignore the
        // result since teardown races are expected.
        let _ = connection.await;
    });
    Ok(client)
}

/// Build a connection pool for an already-created database.
fn build_pool(config: &Config) -> Result<Pool> {
    let mgr_config = ManagerConfig {
        recycling_method: RecyclingMethod::Fast,
    };
    let manager = Manager::from_config(config.clone(), NoTls, mgr_config);
    Pool::builder(manager)
        .max_size(8)
        .build()
        .map_err(|e| Error::database(format!("build pool: {e}")))
}
