//! The REST [`ApiProvider`] (design §13.4).
//!
//! Projects an application's tables into a REST API in the shape the design's
//! quality bar (Hasura / PostgREST / Supabase) sets: a table `posts` becomes
//! `GET /api/posts`, `POST /api/posts`, `PUT /api/posts/{id}`, and
//! `DELETE /api/posts/{id}`. The table is a **literal** path segment, not a
//! `{table}` parameter — an app's API exposes the app's own tables, so they are
//! part of the contract and get typed client methods (`listPosts`, `createPosts`,
//! …) rather than a stringly-typed table argument. That projection is the same
//! [`EndpointSet`](crate::EndpointSet) machinery the admin API uses, so an app's
//! client is generated by the same [`generate_client`](crate::generate_client).
//!
//! **Authorization** comes from each table's own [`AccessRules`](sc_catalog::AccessRules)
//! (§7): reads require `min_role_read`, writes `min_role_write`. The provider
//! enforces the requirement before running anything, so a REST caller sees
//! exactly what a user of that role would — there is no path into the data that
//! skips the check.
//!
//! **Authentication**: the projection includes the app's own `login` / `logout` /
//! `whoami`, so a React app authenticates against `sc-auth` through its own API
//! rather than borrowing the admin's (§7.2). `login` is public — it is how a
//! caller stops being anonymous — and it verifies credentials against the same
//! `sc_auth::authenticate` the admin login uses, for any role rather than admins
//! only. `signup` is the other public one, and it exists only where the
//! application's REST settings turn it on ([`CFG_ALLOW_SIGNUP`]): anybody at all
//! making an account is a decision, not a default. The provider never touches
//! cookies: it returns a [`SessionAction`] and the transport mints and carries
//! the token.
//!
//! **Custom SQL queries** (§13.4) are the one thing here that is not a
//! projection of the row layer: an administrator's own statement, at their own
//! sub-path and method, with typed parameters bound into it and its result typed
//! by the database that described it. [`custom`] holds the model, the rules and
//! the authority note — read that module before changing anything about them.
//! Custom routes authored as **guest code** remain carried by the endpoint model
//! and rejected with `501 Not Implemented`: that half is still stubbed, and the
//! honest failure is better than pretending.
//!
//! **Reads take a query string** (§13.4): `GET {mount}/{table}` accepts
//! PostgREST's `?select=…&column=op.value&order=…&limit=…&offset=…`, parsed by
//! [`query`] into the row layer's own `RowQuery` and run through the *same*
//! [`ownership::read_row_values_as`] the GraphQL provider's list fields use. The
//! query string is a syntax over the read layer, not a second reader — which is
//! also why an embedded `author(name)` is a correlated subquery of the same
//! statement rather than a second fetch.
//!
//! **Triggers** are projected one endpoint each — `POST {mount}/actions/{name}`,
//! request body → the event's payload, the action's result → the response — but
//! only for the triggers the *application* names ([`project_with`](RestProvider::project_with)).
//! Server-side automation is not an API surface by default: a trigger becomes
//! callable from outside because an app said so, and one nobody named is a 404
//! rather than a 403. Authorization is the trigger's own `min_role`, defaulting
//! to **admin** when it has none — a trigger whose access nobody has thought
//! about must not be the one that turns out to be public.

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use sc_auth::{User, authenticate};
use sc_catalog::{CallerContext, Catalog, DataFieldKind, Table, load_file_store_by_name};
use sc_error::{Error, Result};
use sc_expr::{JsEvaluator, Operation};
use sc_files::{ROLE_PUBLIC, check_access, mime_for_path, validate_file_path};
use sc_query::Value;
use sc_types::{Attrs, BasicType, FormField};
use serde_json::{Value as Json, json};

pub mod custom;
mod query;

use custom::CustomQuery;

use crate::auth::{credentials, credentials_schema, user_summary_json, user_summary_schema};
use crate::endpoint::{
    AuthRequirement, Endpoint, EndpointSet, HandlerRef, Method, PathSpec, QueryParam,
};
use crate::ownership;
use crate::provider::{ApiProvider, ApiRequest, ApiResponse};
use crate::resource::{ResourceField, ResourceFile, ResourceModel};
use crate::rows;
use crate::schema::{TypeSchema, ValueType};

/// The provider's registered name.
pub const REST_PROVIDER: &str = "rest";

/// The most rows a list endpoint returns when the caller names no `limit`, and
/// the ceiling one they *do* name is clamped to.
///
/// The GraphQL provider's [`row_cap`](crate::GraphqlLimits) argument, applied to
/// the other syntax and for the same reason: an unbounded list is a request to
/// stream a table into a response, and a caller's number is a request rather
/// than a permission. An application configures its own through
/// [`rest_config_spec`]'s one setting; this is what it is served under until
/// somebody states otherwise.
pub const DEFAULT_ROW_CAP: u64 = 500;

/// The setting behind [`RestProvider::with_row_cap`].
pub const CFG_ROW_CAP: &str = "row_cap";

/// The setting that projects `POST {mount}/signup` ([`RestProvider::with_signup`]).
/// Off unless an admin turns it on: an application whose accounts are made by
/// an administrator must not grow a door anybody can walk through.
pub const CFG_ALLOW_SIGNUP: &str = "allow_signup";

/// The setting naming the role an account made through `signup` gets. The key
/// the Saltcorn UI framework's own sign-up setting has, for the same thing.
pub const CFG_NEW_USER_ROLE: &str = "new_user_role";

/// The role [`CFG_NEW_USER_ROLE`] defaults to — v1's `user` role.
pub const DEFAULT_NEW_USER_ROLE: u8 = 80;

/// What an admin enabling the REST provider may configure.
///
/// The same arrangement the GraphQL provider's five are
/// under ([`graphql_config_spec`](crate::graphql_config_spec)): the application
/// form renders whatever a provider declares, so this list is the only place
/// that decides what a REST API can be configured with.
pub fn rest_config_spec() -> Vec<FormField> {
    vec![
        FormField::new(CFG_ROW_CAP, BasicType::Int)
            .label("Row cap per list read")
            .default_value(DEFAULT_ROW_CAP as i64),
        FormField::new(CFG_ALLOW_SIGNUP, BasicType::Bool)
            .label("Allow sign-up (anybody may create an account)")
            .default_value(false),
        FormField::new(CFG_NEW_USER_ROLE, BasicType::Int)
            .label("Role of a signed-up account")
            .default_value(i64::from(DEFAULT_NEW_USER_ROLE)),
    ]
}

/// The role an account made through the application's `signup` endpoint gets,
/// or `None` when the stored configuration does not offer sign-up.
///
/// A role outside `2..=100` is `None` too rather than the default: the
/// configuration was checked on save ([`check_rest_config`]), so one that is
/// out of range now was never accepted, and failing closed is the answer that
/// cannot make an administrator.
pub fn rest_signup_role(config: &Attrs) -> Option<u8> {
    if !config
        .get(CFG_ALLOW_SIGNUP)
        .and_then(Json::as_bool)
        .unwrap_or(false)
    {
        return None;
    }
    match config.get(CFG_NEW_USER_ROLE).filter(|r| !r.is_null()) {
        None => Some(DEFAULT_NEW_USER_ROLE),
        Some(role) => role
            .as_u64()
            .and_then(|r| u8::try_from(r).ok())
            .filter(|r| signup_role_allowed(*r)),
    }
}

/// What [`rest_config_spec`]'s vocabulary cannot say about the settings: that
/// the role a sign-up gives is never the administrator's.
pub fn check_rest_config(config: &Attrs) -> Result<()> {
    if let Some(role) = config.get(CFG_NEW_USER_ROLE).filter(|r| !r.is_null())
        && !role
            .as_u64()
            .and_then(|r| u8::try_from(r).ok())
            .is_some_and(signup_role_allowed)
    {
        return Err(Error::invalid(format!(
            "`{CFG_NEW_USER_ROLE}` must be a role from 2 to 100; an account \
             anybody can make through sign-up cannot be an administrator"
        )));
    }
    Ok(())
}

/// Any role but the administrator's.
fn signup_role_allowed(role: u8) -> bool {
    (sc_auth::ROLE_ADMIN + 1..=sc_auth::ROLE_PUBLIC).contains(&role)
}

/// The row cap an application's stored provider configuration names, or
/// [`DEFAULT_ROW_CAP`].
///
/// A value that is absent or of the wrong shape is the default rather than an
/// error, exactly as [`GraphqlLimits::from_config`](crate::GraphqlLimits::from_config)
/// treats one: the configuration was validated against [`rest_config_spec`] on
/// save, where the admin was still looking at it.
pub fn rest_row_cap(config: &Attrs) -> u64 {
    config
        .get(CFG_ROW_CAP)
        .and_then(Json::as_u64)
        .unwrap_or(DEFAULT_ROW_CAP)
}

/// Which table operation an endpoint runs. Recorded per endpoint at projection
/// time so dispatch is a lookup rather than a re-parse of the path.
#[derive(Debug, Clone, PartialEq, Eq)]
enum RestOp {
    /// `GET /{table}` — every row.
    List,
    /// `POST /{table}` — insert a row.
    Create,
    /// `PUT /{table}/{id}` — update the row with that primary key.
    Update,
    /// `DELETE /{table}/{id}` — delete the row with that primary key.
    Delete,
    /// `GET /{table}/{id}/{field}` — serve the bytes behind the row's `File`
    /// field (§4).
    Download {
        /// The `File` field whose stored path is resolved and served.
        field: String,
    },
    /// `POST /{table}/{id}/{field}/{filename}` — store the raw request body in
    /// the field's store and folder and point the row's field at it (§4).
    Upload {
        /// The `File` field the upload lands in.
        field: String,
    },
}

/// A projected table endpoint: the operation and the table it runs against.
#[derive(Debug, Clone)]
struct TableRoute {
    op: RestOp,
    table: String,
}

/// The path segment an app's exposed triggers live under: `POST
/// {mount}/actions/{name}`.
///
/// A literal segment rather than the trigger name at the mount's root, so a
/// trigger can never collide with a table (`/api/posts` is the `posts` table
/// whatever anyone calls a trigger) and a reader of a URL can tell which of the
/// two they are looking at.
const ACTIONS_SEGMENT: &str = "actions";

/// The endpoint names of the app's own auth operations. They are fixed rather
/// than derived from a table, so a table cannot collide with them: `op_name`
/// always prefixes a table's operations with `list`/`create`/`update`/`delete`.
const LOGIN: &str = "login";
const LOGOUT: &str = "logout";
const WHOAMI: &str = "whoami";
const SIGNUP: &str = "signup";

/// The first path segments this provider's own routes claim, which a custom SQL
/// query's sub-path may therefore not start with (see
/// [`custom::validate_custom_queries`]).
///
/// A table's name is the other half of that rule, and it is not a constant — it
/// is whatever the application declares. `signup` is reserved whether or not
/// the application offers it, so turning sign-up on cannot shadow a query.
pub(crate) const RESERVED_SEGMENTS: [&str; 5] = [ACTIONS_SEGMENT, LOGIN, LOGOUT, WHOAMI, SIGNUP];

/// Every endpoint name the provider's own auth may project — the three every
/// app has plus `signup` — which a custom query may therefore not be named.
pub(crate) const RESERVED_AUTH_NAMES: [&str; 4] = [LOGIN, LOGOUT, WHOAMI, SIGNUP];

/// The app's own auth operations, as a client generator meets them.
///
/// Public because a *consumer* of the endpoint set has to be able to ask whether
/// an application can sign anyone in — the React scaffold's login screen calls
/// exactly these three, and only this provider projects them (the GraphQL
/// provider projects its two, by design §13.4). Asking the endpoint set is how
/// that question stays right when a provider changes what it projects.
pub const AUTH_ENDPOINTS: [&str; 3] = [LOGIN, LOGOUT, WHOAMI];

/// A REST projection of an application's endpoint set (design §13.4).
pub struct RestProvider {
    mount: String,
    endpoints: EndpointSet,
    /// Endpoint name → the table operation it runs. Custom routes are absent
    /// here; they resolve through their [`HandlerRef`] instead.
    routes: HashMap<String, TableRoute>,
    /// Endpoint name → the trigger it runs, for the app's exposed subset.
    trigger_routes: HashMap<String, String>,
    /// The role a `signup` gives a new account, when the application offers
    /// sign-up at all ([`with_signup`](RestProvider::with_signup)).
    signup_role: Option<u8>,
    /// Endpoint name → the admin-authored SQL query it runs
    /// ([`with_queries`](RestProvider::with_queries)). Keyed the same way the
    /// [`HandlerRef::Sql`] on the endpoint names it, so dispatch is a lookup.
    custom_routes: HashMap<String, CustomQuery>,
    /// The dispatcher an exposed trigger is run through. Injected by the server
    /// via [`with_dispatcher`](RestProvider::with_dispatcher); absent in the
    /// contexts that only need the endpoint *shapes* (client generation), where
    /// calling one is a configuration error rather than a silent no-op.
    dispatcher: Option<Arc<sc_action::TriggerDispatcher>>,
    /// The engine behind ownership formulas' reified path (§7.3). Injected by
    /// the server via [`with_evaluator`](RestProvider::with_evaluator); when
    /// absent, a formula that needs it **fails closed** with a configuration
    /// error rather than granting anything.
    evaluator: Option<Arc<dyn JsEvaluator>>,
    /// The ceiling a list read is bounded by ([`DEFAULT_ROW_CAP`]).
    row_cap: u64,
}

impl RestProvider {
    /// Project `tables` into a REST API mounted at `mount`.
    ///
    /// The tables are the application's declared subset, already resolved
    /// against the catalog by the caller — an app only ever exposes the tables it
    /// declares (§13.2), and this crate sits below `sc-app` so it takes the
    /// resolved tables rather than the `Application`.
    ///
    /// Each table contributes four endpoints, each carrying the auth requirement
    /// its own access rules dictate. A table with no single-column primary key
    /// gets only the collection endpoints (list/create): there is no way to
    /// address one of its rows, so `PUT`/`DELETE` would be undeliverable
    /// promises.
    pub fn project(mount: impl Into<String>, tables: &[Table]) -> RestProvider {
        RestProvider::project_with(mount, tables, &[])
    }

    /// [`project`](RestProvider::project) plus one endpoint per exposed trigger
    /// (§10.2).
    ///
    /// The triggers are the application's declared subset, already resolved
    /// against the live trigger set by the caller — the same arrangement the
    /// tables have, and for the same reason: this crate sits below `sc-app`, so
    /// it takes what an app resolved rather than the `Application`.
    pub fn project_with(
        mount: impl Into<String>,
        tables: &[Table],
        triggers: &[sc_action::Trigger],
    ) -> RestProvider {
        let mount = normalize_mount(&mount.into());
        let mut endpoints = EndpointSet::new();
        let mut routes = HashMap::new();
        let mut trigger_routes = HashMap::new();

        // The app's own auth (§7.2). Projected for every app: an app whose users
        // cannot log in can only ever serve public-role data, and a caller has to
        // have some way to stop being anonymous. Public-role browsing still works
        // without ever calling these.
        endpoints.register(
            Endpoint::new(LOGIN, Method::Post, path_at(&mount).lit("login"))
                .input(credentials_schema())
                .output(user_summary_schema())
                // The only public endpoint: it is what turns an anonymous caller
                // into an authenticated one.
                .auth(AuthRequirement::Public),
        );
        endpoints.register(
            Endpoint::new(LOGOUT, Method::Post, path_at(&mount).lit("logout"))
                .auth(AuthRequirement::LoggedIn),
        );
        endpoints.register(
            Endpoint::new(WHOAMI, Method::Get, path_at(&mount).lit("whoami"))
                .output(user_summary_schema())
                .auth(AuthRequirement::LoggedIn),
        );

        // The tables as a *generated consumer* sees them (§13.1): the row shapes
        // and which endpoint performs which operation on them. Collected here
        // and registered after the loop, since the endpoint set is borrowed by
        // the registering closure for the whole of it.
        let mut resources: Vec<ResourceModel> = Vec::new();
        let exposed: std::collections::HashSet<&str> =
            tables.iter().map(|t| t.name.as_str()).collect();

        for table in tables {
            let name = &table.name;
            let mut resource = resource_model(table, &exposed);
            // A table with an ownership formula relaxes its endpoints to
            // Public (§7.3): the formula decides `user === null` — an admin
            // may grant anonymous callers rows — so the gate moves from the
            // endpoint's auth into the handler, where the rule becomes
            // "meets the role floor OR the formula grants the row". A table
            // without a formula keeps the MinRole gate exactly as before.
            let (read, write) = if table.ownership.is_some() {
                (AuthRequirement::Public, AuthRequirement::Public)
            } else {
                (
                    AuthRequirement::MinRole(table.access.min_role_read),
                    AuthRequirement::MinRole(table.access.min_role_write),
                )
            };
            let collection = || path_at(&mount).lit(name);

            let mut add = |op: RestOp, ep: Endpoint| {
                routes.insert(
                    ep.name.clone(),
                    TableRoute {
                        op,
                        table: name.clone(),
                    },
                );
                endpoints.register(ep);
            };

            resource.ops.list = Some(op_name("list", name));
            resource.ops.create = Some(op_name("create", name));
            add(
                RestOp::List,
                Endpoint::new(op_name("list", name), Method::Get, collection())
                    // What a read may say about itself, typed into the client so
                    // nobody has to write a `fetch` beside it (§13.1). The
                    // filters are the honest exception: `?published=gte.2020` is
                    // a *string vocabulary* keyed by column, so it is typed as
                    // one rather than as a shape it does not have.
                    .query(list_query_params())
                    .output(TypeSchema::array(TypeSchema::json()))
                    .auth(read.clone())
                    .handler(HandlerRef::named(op_name("list", name))),
            );
            add(
                RestOp::Create,
                Endpoint::new(op_name("create", name), Method::Post, collection())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("create", name))),
            );

            // Row-addressing endpoints need exactly one primary-key column to
            // address by; `single_pk` is the same rule the row layer enforces.
            let Ok(pk) = rows::single_pk(table) else {
                resources.push(resource);
                continue;
            };
            resource.primary_key = Some(pk.clone());
            resource.ops.update = Some(op_name("update", name));
            resource.ops.delete = Some(op_name("delete", name));
            let id_ty = table
                .field(&pk)
                .and_then(|f| f.base.type_.as_basic())
                .map_or(ValueType::Text, ValueType::from_basic);
            let item = || path_at(&mount).lit(name).param("id", id_ty);

            add(
                RestOp::Update,
                Endpoint::new(op_name("update", name), Method::Put, item())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("update", name))),
            );
            add(
                RestOp::Delete,
                Endpoint::new(op_name("delete", name), Method::Delete, item())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("delete", name))),
            );

            // A `File` field's bytes (§4), addressed **by table, row id and
            // field name** — never by raw store path. The row is what the caller
            // is allowed to see, and letting an app name an arbitrary path would
            // make the field's folder restriction advisory. Reads carry the
            // table's read rule, uploads its write rule; the file's own
            // path-cumulative `min_role` is enforced on top at request time, so
            // the stricter of the two always decides.
            for data_field in &table.fields {
                if !matches!(data_field.kind, DataFieldKind::File { .. }) {
                    continue;
                }
                let field = &data_field.base.name;
                let scoped = format!("{name}_{field}");
                resource.ops.files.push(ResourceFile {
                    field: field.clone(),
                    download: op_name("download", &scoped),
                    upload: op_name("upload", &scoped),
                });
                let file_item = || path_at(&mount).lit(name).param("id", id_ty).lit(field);
                add(
                    RestOp::Download {
                        field: field.clone(),
                    },
                    Endpoint::new(op_name("download", &scoped), Method::Get, file_item())
                        .binary_output()
                        .auth(read.clone())
                        .handler(HandlerRef::named(op_name("download", &scoped))),
                );
                add(
                    RestOp::Upload {
                        field: field.clone(),
                    },
                    Endpoint::new(
                        op_name("upload", &scoped),
                        Method::Post,
                        // The filename is a path parameter, so it is one
                        // segment by construction — a nested or traversing
                        // destination cannot even be expressed in the URL.
                        file_item().param("filename", ValueType::Text),
                    )
                    .binary_input()
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("upload", &scoped))),
                );
            }
            resources.push(resource);
        }

        for resource in resources {
            endpoints.register_resource(resource);
        }

        // The app's exposed triggers, one `POST {mount}/actions/{name}` each.
        // The role floor is the trigger's own, and an unset one is **admin**:
        // `min_role` is optional on a trigger because most triggers are never
        // called from outside at all, so its absence means "nobody has decided",
        // which must not read as "everybody".
        for trigger in triggers {
            let name = op_name("run", &trigger.name);
            trigger_routes.insert(name.clone(), trigger.name.clone());
            endpoints.register(
                Endpoint::new(
                    name.clone(),
                    Method::Post,
                    path_at(&mount).lit(ACTIONS_SEGMENT).lit(&trigger.name),
                )
                // The posted body *is* the event's payload, whatever shape the
                // action's configuration reads out of it, so it is typed as
                // json rather than as a struct nobody could derive.
                .input(TypeSchema::json())
                .output(TypeSchema::json())
                .auth(AuthRequirement::MinRole(
                    trigger.min_role.unwrap_or(sc_auth::ROLE_ADMIN),
                ))
                .handler(HandlerRef::named(name)),
            );
        }

        RestProvider {
            mount,
            endpoints,
            routes,
            trigger_routes,
            signup_role: None,
            custom_routes: HashMap::new(),
            dispatcher: None,
            evaluator: None,
            row_cap: DEFAULT_ROW_CAP,
        }
    }

    /// Offer sign-up: project `POST {mount}/signup`, which makes an account with
    /// `role` and signs it in, as `login` signs in an existing one. `None` is
    /// the default and projects nothing — an application that does not offer
    /// sign-up has no such route, and its generated client no such method.
    ///
    /// The endpoint goes in beside the other auth endpoints, ahead of every
    /// table's: `resolve` takes the first match, so a table that happens to be
    /// called `signup` cannot shadow it, exactly as one called `login` cannot
    /// shadow that.
    ///
    /// Called before [`with_queries`](RestProvider::with_queries), whose name
    /// check then sees `signup` among the endpoints already projected.
    pub fn with_signup(mut self, role: Option<u8>) -> RestProvider {
        let Some(role) = role else {
            self.signup_role = None;
            return self;
        };
        if self.endpoints.find(SIGNUP).is_some() {
            self.signup_role = Some(role);
            return self;
        }
        let signup = Endpoint::new(SIGNUP, Method::Post, path_at(&self.mount).lit(SIGNUP))
            .input(credentials_schema())
            .output(user_summary_schema())
            // Public for the reason `login` is: it is how a caller who has no
            // account stops being anonymous.
            .auth(AuthRequirement::Public);
        let mut endpoints = EndpointSet::new();
        let mut placed = false;
        for ep in self.endpoints.iter() {
            endpoints.register(ep.clone());
            if ep.name == WHOAMI {
                endpoints.register(signup.clone());
                placed = true;
            }
        }
        if !placed {
            endpoints.register(signup);
        }
        for resource in self.endpoints.resources() {
            endpoints.register_resource(resource.clone());
        }
        self.endpoints = endpoints;
        self.signup_role = Some(role);
        self
    }

    /// Serve this API's list endpoints under a different row cap than
    /// [`DEFAULT_ROW_CAP`].
    pub fn with_row_cap(mut self, row_cap: u64) -> RestProvider {
        self.row_cap = row_cap;
        self
    }

    /// Project the application's **custom SQL queries** (§13.4), one endpoint
    /// each, on top of the table and trigger routes.
    ///
    /// A `Result` rather than a builder that cannot fail, because a name a table
    /// endpoint already holds would otherwise be a panic in a running server:
    /// [`EndpointSet::register`] refuses duplicates, and the collision is
    /// reachable — a table gains a column and is reprojected beside a query an
    /// admin named after it. Saving the application refuses that combination
    /// first ([`custom::validate_custom_queries`]); this is the same rule at the
    /// other end, turning what would be a crash into a mount error naming both.
    pub fn with_queries(mut self, queries: Vec<CustomQuery>) -> Result<RestProvider> {
        for query in queries {
            if self.endpoints.find(&query.name).is_some() {
                return Err(Error::config(format!(
                    "custom SQL query `{}` has the same name as an endpoint this \
                     API already projects; rename the query",
                    query.name
                )));
            }
            self.endpoints
                .register(custom::custom_endpoint(&self.mount, &query));
            self.custom_routes.insert(query.name.clone(), query);
        }
        Ok(self)
    }

    /// Run an admin-authored SQL query (§13.4).
    ///
    /// The endpoint's `MinRole` — the query's own floor, admin unless the admin
    /// said otherwise — was enforced before this ran. What happens here is the
    /// rest of [`custom`]'s authority note: the caller's arguments are coerced
    /// to their declared types and **bound**, the statement runs inside the
    /// caller-context transaction so an RLS-protected table's policies still
    /// decide what it can see, and a `GET` runs `READ ONLY` so a write behind
    /// one fails rather than happening.
    async fn run_custom(
        &self,
        query: &CustomQuery,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let statement = custom::custom_statement(cat, query, req)?;
        let caller = ownership::caller_context(user);
        let rows = if query.read_only() {
            sc_catalog::run_in_context_read_only(cat, &caller, &statement).await
        } else {
            sc_catalog::run_in_context(cat, &caller, &statement).await
        }?;
        Ok(ApiResponse::ok(custom::rows_to_json(&rows)))
    }

    /// Inject the JavaScript evaluator ownership formulas' reified path runs
    /// on. The server constructs one engine and shares it across every
    /// provider; a provider without one still enforces translatable formulas
    /// symbolically and fails closed on the rest.
    pub fn with_evaluator(mut self, evaluator: Arc<dyn JsEvaluator>) -> RestProvider {
        self.evaluator = Some(evaluator);
        self
    }

    /// Inject the trigger dispatcher an exposed trigger's endpoint runs through
    /// — the *same* dispatcher every other event fires on, so a trigger called
    /// over an app's API is the trigger the admin configured, with the same
    /// `only_if`, the same cascade bound and the same action.
    pub fn with_dispatcher(
        mut self,
        dispatcher: Arc<sc_action::TriggerDispatcher>,
    ) -> RestProvider {
        self.dispatcher = Some(dispatcher);
        self
    }

    /// Run one of the app's exposed triggers, with the request body as the
    /// event's payload and the caller travelling with it (§10.2).
    ///
    /// The caller is not merely recorded: it is what the trigger's action sees as
    /// `user`, and what a row the action writes reports as the cause of its own
    /// event. A failing action comes back as an **error** — somebody asked for
    /// this one, so somebody is waiting for the answer — which is the same
    /// contract the admin's "run this now" button has.
    async fn run_trigger(
        &self,
        trigger: &str,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let dispatcher = self.dispatcher.as_ref().ok_or_else(|| {
            Error::config(format!(
                "this application exposes trigger `{trigger}` but no trigger \
                 dispatcher is available in this context, so it cannot be run"
            ))
        })?;
        let caller = ownership::caller_context(user);
        let result = dispatcher
            .run_trigger(cat, trigger, req.body.clone(), Some(&caller))
            .await?;
        Ok(ApiResponse::ok(result))
    }

    /// Add a developer-authored custom route as a bare endpoint (§13.4).
    ///
    /// The endpoint is projected and typed like any other, but nothing here
    /// knows how to *run* it: a [`HandlerRef::GuestCode`] is `501 Not
    /// Implemented`, and a [`HandlerRef::Sql`] resolves against the queries
    /// [`with_queries`](RestProvider::with_queries) registered — which is the
    /// way to add a custom SQL query, since it carries the definition the
    /// handler needs.
    pub fn with_custom_route(mut self, endpoint: Endpoint) -> RestProvider {
        self.endpoints.register(endpoint);
        self
    }

    /// Find the endpoint matching `req`, with its captured path parameters.
    ///
    /// `Err` distinguishes the two ways a request can miss: a path no endpoint
    /// claims (`404`) versus a path that exists but not for this method (`405`).
    // `clippy::result_large_err` does not apply: the `Err` here is not an error
    // being propagated up a call stack, it *is* the response to send — the one
    // caller either dispatches the endpoint or returns this `ApiResponse`
    // unchanged. Boxing it would add an indirection at seven call sites to shrink
    // a value that is constructed once per missed request and immediately
    // returned. (`ApiResponse` already boxes the one field worth boxing, `raw`.)
    #[allow(clippy::result_large_err)]
    fn resolve(&self, req: &ApiRequest) -> std::result::Result<(&Endpoint, Params), ApiResponse> {
        let mut path_matched = false;
        for ep in self.endpoints.iter() {
            match ep.path.match_path(&req.path) {
                Some(params) if ep.method == req.method => return Ok((ep, params)),
                Some(_) => path_matched = true,
                None => {}
            }
        }
        Err(if path_matched {
            ApiResponse::error(
                405,
                format!("{} is not allowed on {}", req.method.as_str(), req.path),
            )
        } else {
            ApiResponse::error(404, format!("no endpoint for {}", req.path))
        })
    }

    /// Verify credentials against `sc-auth` and start a session.
    ///
    /// Uses the same `authenticate` the admin login does, but for **any** role —
    /// an app's users are not admins. A bad password and an unknown user are the
    /// same `401` with the same message: distinguishing them would tell an
    /// attacker which emails are registered.
    async fn login(&self, body: &Json, cat: &Catalog) -> Result<ApiResponse> {
        let (email, password) = credentials(body)?;
        match authenticate(cat, &email, &password).await? {
            Some(user) => {
                let summary = user_summary_json(&user);
                Ok(ApiResponse::start_session(user, summary))
            }
            None => Ok(ApiResponse::error(401, "invalid credentials")),
        }
    }

    /// Make an account and start a session for it — `POST {mount}/signup`,
    /// projected only where the application offers sign-up.
    ///
    /// The account gets the role the application's settings name, never the
    /// administrator's ([`check_rest_config`]), under the password rule every
    /// other way of making one has: not blank. An address that already has an
    /// account is a `409` — unlike a failed login, the answer cannot be kept
    /// vague, because the caller has to be told to sign in instead.
    async fn signup(&self, body: &Json, cat: &Catalog) -> Result<ApiResponse> {
        let Some(role) = self.signup_role else {
            // The route is only projected alongside a role, so this is the set
            // having been extended by something else.
            return Ok(ApiResponse::error(
                404,
                "this application does not offer sign-up",
            ));
        };
        let (email, password) = credentials(body)?;
        let email = email.trim().to_owned();
        if sc_auth::load_user_by_email(cat, &email).await?.is_some() {
            return Ok(ApiResponse::error(
                409,
                "there is already an account with this email address",
            ));
        }
        let user = sc_auth::create_user(cat, &email, &password, role).await?;
        let summary = user_summary_json(&user);
        let mut out = ApiResponse::start_session(user, summary);
        out.status = 201;
        Ok(out)
    }

    /// Run a resolved table operation, enforcing the §7.3 access rule:
    /// **meets the operation's role floor OR the ownership formula grants the
    /// row**. Callers at or above the floor take exactly the pre-formula
    /// paths; everyone else exists only where the formula says so — and a row
    /// the formula withholds answers with the *same* not-found a missing row
    /// gets, so nothing about the table's contents can be probed.
    async fn run(
        &self,
        route: &TableRoute,
        params: &Params,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let table = cat.require(&route.table)?;
        let body = &req.body;
        let id = || -> Result<&str> {
            params
                .get("id")
                .map(String::as_str)
                .ok_or_else(|| Error::invalid("missing path parameter `id`"))
        };
        // When the database enforces this table's ownership (§6), the runtime
        // checks below are switched off entirely: every row operation runs in a
        // caller-context transaction and the generated policies decide. "You no
        // longer have to check" (GOALS), and joinfields are not refetched — the
        // policies' correlated subselects do that in the database.
        if table.rls_enabled {
            return self.run_rls(route, &table, params, req, cat, user).await;
        }
        // The caller's role for the path-cumulative file rule. Anonymous is
        // public; the table-level gate (floor or formula) runs separately.
        let role = user.map_or(ROLE_PUBLIC, |u| u.role);
        let meets_read = ownership::meets(user, table.access.min_role_read);
        let meets_write = ownership::meets(user, table.access.min_role_write);
        // The formula, for callers below the floor. Its absence there means
        // the endpoint was Public only by a stale projection — deny exactly as
        // the MinRole gate would have.
        // `Err(())` is "deny as the MinRole gate would" — the response is built
        // at the call site to keep this closure's error small.
        let formula = |allowed: bool| -> std::result::Result<Option<&sc_expr::Formula>, ()> {
            if allowed {
                Ok(None)
            } else {
                match &table.ownership {
                    Some(f) => Ok(Some(f)),
                    None => Err(()),
                }
            }
        };
        let evaluator = self.evaluator.as_ref();
        // The caller, travelling with every write so the event it raises knows
        // who caused it (§10.2). On this path it sets no GUCs — the table is not
        // RLS-enforced, and `rows` routes by the table, not by the context's
        // presence — it is identity, not authority.
        let caller = ownership::caller_context(user);

        Ok(match &route.op {
            // The read's own rule is `read_row_values_as`'s — the floor, the
            // formula, or the database's policies — so the gate here decides only
            // whether the caller is refused *as the endpoint's auth would have
            // refused them* (a 401/403 rather than an error), and the read
            // applies §7.3 itself.
            RestOp::List => match formula(meets_read) {
                Err(()) => forbidden(user),
                Ok(_) => self.list(cat, &table, req, user).await?,
            },
            RestOp::Create => {
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // An insert is checked against the proposed row, `_insert`
                    // folded true (§7.3) — WITH CHECK semantics at runtime.
                    Ok(Some(f)) => {
                        let proposed = rows::coerce_row_values(&table, body)?;
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Insert,
                            user,
                            evaluator,
                            &proposed,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "this row is outside your ownership",
                            ));
                        }
                    }
                }
                ApiResponse::with_status(
                    201,
                    rows::create_row_ctx(cat, &table, body, Some(&caller)).await?,
                )
            }
            RestOp::Update => {
                let id = id()?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => ApiResponse::ok(
                        rows::update_row_ctx(cat, &table, id, body, Some(&caller)).await?,
                    ),
                    Ok(Some(f)) => {
                        // USING: granted on the existing row…
                        let existing = self
                            .owned_row(cat, &table, f, Operation::Update, user, id)
                            .await?;
                        // …and WITH CHECK: granted on the proposed row too, so
                        // an update cannot move the row out of the caller's
                        // ownership.
                        let changes = rows::coerce_row_values(&table, body)?;
                        let merged = ownership::merged_row(&table, &existing, &changes);
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Update,
                            user,
                            evaluator,
                            &merged,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "the update would move this row out of your ownership",
                            ));
                        }
                        // The translated predicate rides in the UPDATE's WHERE
                        // when it can, closing the check-to-write race.
                        let guard =
                            ownership::write_guard(cat, &table, f, Operation::Update, user)?;
                        ApiResponse::ok(
                            rows::update_row_guarded(cat, &table, id, body, guard, Some(&caller))
                                .await?,
                        )
                    }
                }
            }
            RestOp::Delete => {
                let id = id()?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {
                        rows::delete_row_ctx(cat, &table, id, Some(&caller)).await?;
                        deleted()
                    }
                    Ok(Some(f)) => {
                        self.owned_row(cat, &table, f, Operation::Delete, user, id)
                            .await?;
                        let guard =
                            ownership::write_guard(cat, &table, f, Operation::Delete, user)?;
                        rows::delete_row_guarded(cat, &table, id, guard, Some(&caller)).await?;
                        deleted()
                    }
                }
            }
            RestOp::Download { field } => {
                match formula(meets_read) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // A file read is a read of the row (§7.3); the file's own
                    // path-cumulative rule still runs inside `download`.
                    Ok(Some(f)) => {
                        self.owned_row(cat, &table, f, Operation::Read, user, id()?)
                            .await?;
                    }
                }
                download(cat, &table, field, id()?, role).await?
            }
            RestOp::Upload { field } => {
                let filename = params
                    .get("filename")
                    .map(String::as_str)
                    .ok_or_else(|| Error::invalid("missing path parameter `filename`"))?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // An upload updates the row's field: granted on the
                    // existing row, and on the row as it will be — the formula
                    // may read the very field being written.
                    Ok(Some(f)) => {
                        let id = id()?;
                        let existing = self
                            .owned_row(cat, &table, f, Operation::Update, user, id)
                            .await?;
                        let (_, folder, _) = file_field(&table, field)?;
                        let path = upload_path(folder, filename);
                        let mut changes = std::collections::BTreeMap::new();
                        changes.insert(field.clone(), Value::Text(path));
                        let merged = ownership::merged_row(&table, &existing, &changes);
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Update,
                            user,
                            evaluator,
                            &merged,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "the upload would move this row out of your ownership",
                            ));
                        }
                    }
                }
                upload_ctx(
                    cat,
                    &table,
                    field,
                    id()?,
                    filename,
                    req.raw.clone(),
                    role,
                    &caller,
                )
                .await?
            }
        })
    }

    /// `GET {mount}/{table}` — the read, with everything the caller's query
    /// string said about it.
    ///
    /// One function for every table, protected or not: the query string parses
    /// into the row layer's [`RowQuery`](crate::rows::RowQuery) and the read goes
    /// through [`ownership::read_row_values_as`], which is where "meets the floor
    /// OR the formula grants the row OR the policies do" lives — the same entry
    /// point the GraphQL root field and an agent's `query_table` use. A filter,
    /// an ordering and a bound ride *inside* that read, so they narrow the rows
    /// the caller may see rather than being applied to some wider set first.
    async fn list(
        &self,
        cat: &Catalog,
        table: &Table,
        req: &ApiRequest,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let role = ownership::caller_role(user);
        let plan = query::parse(cat, table, req, role, self.row_cap)?;
        let rows = ownership::read_row_values_as(
            cat,
            table,
            &plan.query,
            role,
            user,
            self.evaluator.as_ref(),
        )
        .await?;
        Ok(ApiResponse::ok(plan.render(table, &rows)))
    }

    /// The existing row `id`, granted to the caller by the formula for `op` —
    /// or the **same not-found a missing row gets**, which is what makes
    /// denial indistinguishable from absence.
    async fn owned_row(
        &self,
        cat: &Catalog,
        table: &Table,
        formula: &sc_expr::Formula,
        op: Operation,
        user: Option<&User>,
        id: &str,
    ) -> Result<std::collections::BTreeMap<String, Value>> {
        let not_found = || {
            let pk = rows::single_pk(table)?;
            Err(Error::not_found(format!("no row with {pk} = {id}")))
        };
        let Some(existing) = ownership::fetch_row_values(cat, table, formula, id).await? else {
            return not_found();
        };
        if !ownership::row_allowed(
            cat,
            table,
            formula,
            op,
            user,
            self.evaluator.as_ref(),
            &existing,
        )
        .await?
        {
            return not_found();
        }
        Ok(existing)
    }

    /// Run a row operation on an **RLS-enabled** table (§6): the database's
    /// policies do all the gating, so there is no formula translation, no
    /// evaluator, and no fetch-then-check here. Every statement runs through a
    /// caller-context transaction, and a policy that withholds a row surfaces
    /// as the same not-found an absent row gets (`run_in_context` maps `42501`).
    /// The file endpoints still layer the path-cumulative file rule on top.
    async fn run_rls(
        &self,
        route: &TableRoute,
        table: &Table,
        params: &Params,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let ctx = ownership::caller_context(user);
        let body = &req.body;
        let role = user.map_or(ROLE_PUBLIC, |u| u.role);
        let id = || -> Result<&str> {
            params
                .get("id")
                .map(String::as_str)
                .ok_or_else(|| Error::invalid("missing path parameter `id`"))
        };
        Ok(match &route.op {
            // The same read as the non-RLS path, and deliberately so: it routes
            // itself through a caller-context transaction because the *table*
            // says to, so the policies decide exactly as they do everywhere else.
            RestOp::List => self.list(cat, table, req, user).await?,
            RestOp::Create => ApiResponse::with_status(
                201,
                rows::create_row_ctx(cat, table, body, Some(&ctx)).await?,
            ),
            RestOp::Update => ApiResponse::ok(
                rows::update_row_guarded(cat, table, id()?, body, None, Some(&ctx)).await?,
            ),
            RestOp::Delete => {
                rows::delete_row_guarded(cat, table, id()?, None, Some(&ctx)).await?;
                deleted()
            }
            RestOp::Download { field } => {
                download_ctx(cat, table, field, id()?, role, &ctx).await?
            }
            RestOp::Upload { field } => {
                let filename = params
                    .get("filename")
                    .map(String::as_str)
                    .ok_or_else(|| Error::invalid("missing path parameter `filename`"))?;
                upload_ctx(
                    cat,
                    table,
                    field,
                    id()?,
                    filename,
                    req.raw.clone(),
                    role,
                    &ctx,
                )
                .await?
            }
        })
    }
}

/// The query-string parameters every list endpoint accepts (§13.4), in the order
/// they appear in the generated client's options object.
///
/// `filter` is the one that is not a scalar: a filter is a *column* name with a
/// `op.value` string under it, so the client takes a map of them and appends each
/// entry as its own query-string pair — `{ published: "gte.2020-01-01" }` becomes
/// `?published=gte.2020-01-01`. Typing it as a map is honest about being a string
/// vocabulary; typing it as anything narrower would be a promise the query string
/// cannot keep.
fn list_query_params() -> Vec<QueryParam> {
    vec![
        QueryParam::new("select", ValueType::Text),
        QueryParam::new("order", ValueType::Text),
        QueryParam::new("limit", ValueType::Int),
        QueryParam::new("offset", ValueType::Int),
        QueryParam::new("filter", ValueType::Text).map(),
    ]
}

/// What a `DELETE` answers with.
///
/// The row layer hands back the row as it was — the only copy of it anyone will
/// ever get — and this projection deliberately does not: a REST `DELETE`
/// acknowledges, and a caller who wanted the row could have read it. The
/// GraphQL projection makes the other choice, which is why the shape is decided
/// here rather than in the row layer.
fn deleted() -> ApiResponse {
    ApiResponse::ok(json!({ "deleted": true }))
}

/// The rejection a caller below the floor gets when no formula extends access:
/// exactly what the `MinRole` gate answers, per caller state.
fn forbidden(user: Option<&User>) -> ApiResponse {
    match user {
        None => ApiResponse::error(401, "authentication required"),
        Some(_) => ApiResponse::error(403, "insufficient privilege"),
    }
}

/// The store-relative path an upload of `filename` lands at — the same shape
/// `upload` itself builds, factored so the ownership pre-check sees the row
/// exactly as it will be written.
fn upload_path(folder: Option<&str>, filename: &str) -> String {
    match folder
        .map(|f| f.trim_matches('/'))
        .filter(|f| !f.is_empty())
    {
        Some(folder) => format!("{folder}/{filename}"),
        None => filename.to_owned(),
    }
}

/// Serve the bytes behind a row's `File` field (§4).
///
/// The table's `min_role_read` was enforced as the endpoint's auth before this
/// ran; here the file's own **path-cumulative** `min_role` (§14.1) is enforced
/// on top — the stricter of the two decides, never the looser, because both
/// checks must pass. The projection only routes file endpoints for `File`
/// fields, but the catalog may have changed under a mounted app, so the current
/// field is re-checked rather than trusted.
async fn download(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
) -> Result<ApiResponse> {
    download_inner(cat, table, field, id, role, None).await
}

/// [`download`] resolving the row's file path through an RLS caller context
/// (§6), so a file behind a row the policies withhold is a not-found.
async fn download_ctx(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
    context: &CallerContext,
) -> Result<ApiResponse> {
    download_inner(cat, table, field, id, role, Some(context)).await
}

async fn download_inner(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
    context: Option<&CallerContext>,
) -> Result<ApiResponse> {
    let (store_name, _, _) = file_field(table, field)?;
    let path = match rows::read_field_ctx(cat, table, field, id, context).await? {
        Value::Text(path) if !path.is_empty() => path,
        // The row exists but references nothing: for the caller that is "no
        // file here", the same not-found an empty shelf gets.
        _ => {
            return Err(Error::not_found(format!(
                "row {id} has no file in `{field}`"
            )));
        }
    };
    let store = cat.require_file_store(store_name)?;
    let floor = store_floor(cat, store_name).await?;
    check_access(store.as_ref(), floor, &path, role).await?;
    let bytes = store.read(&path).await?;
    // Content type by extension, exactly as the field's MIME allow-list is
    // enforced — the two must agree on what a path is.
    let content_type =
        mime_for_path(&path).unwrap_or_else(|| "application/octet-stream".to_owned());
    Ok(ApiResponse::file(bytes, content_type))
}

/// Store an upload's bytes behind a row's `File` field (§4).
///
/// The table's `min_role_write` was enforced as the endpoint's auth. The bytes
/// land in the **field's** store and folder — the caller names only a filename,
/// one path segment by route construction — and the field's MIME restrictions
/// are applied here, server-side: a client-side accept filter is a convenience,
/// not a control. The row is updated to reference the stored path, through the
/// same `update_row` any JSON write takes (so the field's rules are enforced
/// twice, harmlessly).
///
/// The caller travels with it: on an RLS table it is the authority the
/// pre-existence check and the field update both run under, so a caller cannot
/// upload into a row they may not write; on any table it is who the update event
/// reports as its cause.
#[allow(clippy::too_many_arguments)]
async fn upload_ctx(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    filename: &str,
    data: Option<bytes::Bytes>,
    role: u8,
    context: &CallerContext,
) -> Result<ApiResponse> {
    upload_inner(cat, table, field, id, filename, data, role, Some(context)).await
}

#[allow(clippy::too_many_arguments)]
async fn upload_inner(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    filename: &str,
    data: Option<bytes::Bytes>,
    role: u8,
    context: Option<&CallerContext>,
) -> Result<ApiResponse> {
    let (store_name, folder, mime_allow) = file_field(table, field)?;
    let Some(data) = data else {
        return Err(Error::invalid(
            "expected the request body to be the file's bytes, sent with its own \
             content type (not application/json)",
        ));
    };

    let path = upload_path(folder, filename);
    validate_file_path(&path, folder, mime_allow).map_err(|e| rows::field_error(field, e))?;

    let store = cat.require_file_store(store_name)?;
    let floor = store_floor(cat, store_name).await?;
    // Writing into a restricted place is as governed as reading from one.
    check_access(store.as_ref(), floor, &path, role).await?;

    // The row must exist (and be writable by the caller) before the bytes land:
    // failing afterwards would leave an orphaned file no row references.
    rows::read_field_ctx(cat, table, field, id, context).await?;
    store.write(&path, data).await?;
    let updated =
        rows::update_row_guarded(cat, table, id, &json!({ field: path }), None, context).await?;
    Ok(ApiResponse::with_status(201, updated))
}

/// The `File` kind parameters of `field` on `table`: its store name, folder and
/// MIME allow-list. A field that is not (or is no longer) a `File` is a
/// not-found — the endpoint's own existence is what claimed otherwise.
fn file_field<'t>(
    table: &'t Table,
    field: &str,
) -> Result<(&'t str, Option<&'t str>, &'t [String])> {
    let found = table
        .field(field)
        .ok_or_else(|| Error::not_found(format!("`{}` has no field `{field}`", table.name)))?;
    match &found.kind {
        DataFieldKind::File {
            store,
            folder,
            mime_allow,
        } => Ok((store.0.as_str(), folder.as_deref(), mime_allow.as_slice())),
        _ => Err(Error::not_found(format!(
            "`{}.{field}` is not a File field",
            table.name
        ))),
    }
}

/// The store-wide access floor from the store's stored definition, `None` for a
/// store with no definition row (an ephemeral `--file-store`) — the same answer
/// the admin file endpoints resolve.
async fn store_floor(cat: &Catalog, store: &str) -> Result<Option<u8>> {
    Ok(load_file_store_by_name(cat, store)
        .await?
        .and_then(|def| def.min_role))
}

/// Captured path parameters.
type Params = HashMap<String, String>;

#[async_trait]
impl ApiProvider for RestProvider {
    fn name(&self) -> &str {
        REST_PROVIDER
    }

    fn mount(&self) -> String {
        self.mount.clone()
    }

    fn endpoints(&self) -> &EndpointSet {
        &self.endpoints
    }

    async fn handle(
        &self,
        req: ApiRequest,
        cat: &Arc<Catalog>,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let (endpoint, params) = match self.resolve(&req) {
            Ok(found) => found,
            Err(rejection) => return Ok(rejection),
        };

        // Authorization first, always: every API surface goes through the §7
        // layer, and nothing below this line runs until it passes.
        if let Some(rejection) = enforce_auth(&endpoint.auth, user) {
            return Ok(rejection);
        }

        match &endpoint.handler {
            HandlerRef::Named(_) if endpoint.name == LOGIN => self.login(&req.body, cat).await,
            HandlerRef::Named(_) if endpoint.name == SIGNUP => self.signup(&req.body, cat).await,
            HandlerRef::Named(_) if endpoint.name == LOGOUT => {
                Ok(ApiResponse::end_session(json!({ "ok": true })))
            }
            HandlerRef::Named(_) if endpoint.name == WHOAMI => Ok(ApiResponse::ok(
                // `LoggedIn` is enforced above, so a caller is present here.
                user.map_or(Json::Null, user_summary_json),
            )),
            HandlerRef::Named(_) => match self.routes.get(&endpoint.name) {
                Some(route) => self.run(route, &params, &req, cat, user).await,
                None => match self.trigger_routes.get(&endpoint.name) {
                    Some(trigger) => self.run_trigger(trigger, &req, cat, user).await,
                    // A named handler with no projected route of either kind: the
                    // set was extended with a route this provider cannot run.
                    None => Ok(ApiResponse::error(
                        501,
                        format!("endpoint `{}` has no implementation", endpoint.name),
                    )),
                },
            },
            // Custom routes authored as guest code are carried by the model but
            // not executable yet (design §13.4).
            HandlerRef::GuestCode { language, .. } => Ok(ApiResponse::error(
                501,
                format!("custom {language} routes are not implemented yet"),
            )),
            HandlerRef::Sql(name) => match self.custom_routes.get(name) {
                Some(query) => self.run_custom(query, &req, cat, user).await,
                // A `Sql` endpoint registered by something other than
                // `with_queries` — the set was extended with a route this
                // provider has no query for.
                None => Ok(ApiResponse::error(
                    501,
                    format!("custom SQL query `{name}` has no definition here"),
                )),
            },
        }
    }
}

/// Check a caller against an [`AuthRequirement`], returning a rejection when it
/// does not pass. Mirrors the server's own dispatch check, in the provider's
/// JSON vocabulary.
fn enforce_auth(auth: &AuthRequirement, user: Option<&User>) -> Option<ApiResponse> {
    let unauthenticated = || ApiResponse::error(401, "authentication required");
    match auth {
        AuthRequirement::Public => None,
        AuthRequirement::LoggedIn => user.is_none().then(unauthenticated),
        AuthRequirement::MinRole(min) => match user {
            None => Some(unauthenticated()),
            Some(u) if u.meets_role(*min) => None,
            Some(_) => Some(ApiResponse::error(403, "insufficient privilege")),
        },
    }
}

/// A `PathSpec` rooted at the provider's mount.
fn path_at(mount: &str) -> PathSpec {
    PathSpec::root().lit(mount)
}

/// Normalise a mount to a single leading slash and no trailing slash.
fn normalize_mount(raw: &str) -> String {
    let trimmed = raw.trim_matches('/');
    if trimmed.is_empty() {
        "/".to_owned()
    } else {
        format!("/{trimmed}")
    }
}

/// One table as a generated consumer sees it (§13.1): the shape of its rows, so
/// a client can type them, and the keys among them that point at *another*
/// projected table, so an embedded `?select=author(name)` can be typed too.
///
/// `exposed` is the set of table names this API projects. A key into a table
/// outside it keeps its scalar type and gains no relation: the API has no way to
/// read that table, so an embed through the key is not something a caller can
/// ask for here.
fn resource_model(table: &Table, exposed: &std::collections::HashSet<&str>) -> ResourceModel {
    let mut model = ResourceModel::new(&table.name);
    for field in &table.fields {
        let ty = field
            .base
            .type_
            .as_basic()
            .map_or(ValueType::Text, ValueType::from_basic);
        let mut rf = ResourceField::new(&field.base.name, ty);
        rf.required = field.required;
        rf.has_default = field.generated.is_some();
        rf.primary_key = field.primary_key;
        // A calculated field is read on the way out and refused on the way in
        // (`rows::reject_calc_writes`), so it belongs in a row and in no write.
        rf.read_only = matches!(field.kind, DataFieldKind::Calc { .. });
        if let DataFieldKind::Key { target_table, .. } = &field.kind
            && exposed.contains(target_table.0.as_str())
        {
            rf.references = Some(target_table.0.clone());
        }
        model.fields.push(rf);
    }
    model
}

/// The endpoint (and generated client method) name for an operation on a table:
/// `list` + `blog_posts` → `listBlogPosts`. Table names are unique, so these are
/// unique too; the result is a valid TypeScript identifier as long as the table
/// name is alphanumeric-ish, which the catalog's own naming already requires.
///
/// Public because generated code has to call these methods by name: `sc-app`'s
/// React scaffold writes hooks that invoke `listTasks`/`createTasks`/…, and
/// recomputing the convention there would be a second copy of it, free to drift
/// from the endpoints the client is actually generated with.
pub fn op_name(op: &str, table: &str) -> String {
    let mut out = String::from(op);
    for word in table
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
    {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_catalog::{AccessRules, DataField, DbId, FileStoreId, TableId, TableSource};
    use sc_types::{BasicType, TypeRef};

    /// A table named `name` with an `id` primary key and a `title` text column.
    fn table(name: &str, access: AccessRules) -> Table {
        Table {
            id: TableId(name.to_owned()),
            name: name.to_owned(),
            database: DbId::primary(),
            source: TableSource::Database,
            fields: vec![
                DataField::plain("id", TypeRef::Basic(BasicType::Int)).primary_key(),
                DataField::plain("title", TypeRef::Basic(BasicType::Text)),
            ],
            primary_key: vec!["id".to_owned()],
            label: name.to_owned(),
            description: String::new(),
            access,
            attributes: Default::default(),
            overlay: None,
            ownership: None,
            ownership_error: None,
            rls_enabled: false,
            constraints: Vec::new(),
        }
    }

    /// `table(name, access)` with a `cover` column configured as a `File` field
    /// into store `uploads`, folder `covers`.
    fn table_with_file_field(name: &str, access: AccessRules) -> Table {
        let mut t = table(name, access);
        let mut cover = DataField::plain("cover", TypeRef::Basic(BasicType::Text));
        cover.kind = DataFieldKind::File {
            store: FileStoreId("uploads".to_owned()),
            folder: Some("covers".to_owned()),
            mime_allow: vec!["image/png".to_owned()],
        };
        t.fields.push(cover);
        t
    }

    /// A table with no primary key at all.
    fn keyless(name: &str) -> Table {
        let mut t = table(name, AccessRules::default());
        t.primary_key.clear();
        t.fields = vec![DataField::plain("title", TypeRef::Basic(BasicType::Text))];
        t
    }

    /// A user with the given role. Roles run 1..=100, lower = more privileged.
    fn user(role: u8) -> User {
        User::new(uuid::Uuid::new_v4(), role).expect("role in range")
    }

    /// Every app's projection carries `login`, `logout`, and `whoami` on top of
    /// its per-table endpoints.
    const AUTH_ENDPOINT_COUNT: usize = 3;

    #[test]
    fn projects_four_rest_endpoints_per_table() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert_eq!(p.name(), "rest");
        assert_eq!(p.mount(), "/api");
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 4);

        // The table is a literal segment — the app's own tables are its contract.
        let list = p.endpoints().find("listPosts").unwrap();
        assert_eq!(list.method, Method::Get);
        assert_eq!(list.path.pattern(), "/api/posts");

        let create = p.endpoints().find("createPosts").unwrap();
        assert_eq!(create.method, Method::Post);
        assert_eq!(create.path.pattern(), "/api/posts");

        // Row-addressed endpoints take the primary key as a typed parameter.
        let update = p.endpoints().find("updatePosts").unwrap();
        assert_eq!(update.method, Method::Put);
        assert_eq!(update.path.pattern(), "/api/posts/{id}");

        let delete = p.endpoints().find("deletePosts").unwrap();
        assert_eq!(delete.method, Method::Delete);
        assert_eq!(delete.path.pattern(), "/api/posts/{id}");
    }

    #[test]
    fn endpoint_names_are_camel_cased_typescript_identifiers() {
        assert_eq!(op_name("list", "blog_posts"), "listBlogPosts");
        assert_eq!(op_name("create", "posts"), "createPosts");
        // Non-alphanumeric separators are word boundaries, not literal output.
        assert_eq!(op_name("delete", "a-b"), "deleteAB");
    }

    #[test]
    fn table_access_rules_become_the_endpoints_auth() {
        let strict = AccessRules {
            min_role_read: 80,
            min_role_write: 1,
        };
        let p = RestProvider::project("/api", &[table("posts", strict)]);
        // Reads take min_role_read; writes take min_role_write (§7).
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().auth,
            AuthRequirement::MinRole(80)
        );
        for name in ["createPosts", "updatePosts", "deletePosts"] {
            assert_eq!(
                p.endpoints().find(name).unwrap().auth,
                AuthRequirement::MinRole(1),
                "{name}"
            );
        }
    }

    #[test]
    fn a_table_without_a_single_primary_key_gets_only_collection_endpoints() {
        // No key ⇒ no way to address a row, so no PUT/DELETE is promised.
        let p = RestProvider::project("/api", &[keyless("logs")]);
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 2);
        assert!(p.endpoints().find("listLogs").is_some());
        assert!(p.endpoints().find("createLogs").is_some());
        assert!(p.endpoints().find("updateLogs").is_none());
        assert!(p.endpoints().find("deleteLogs").is_none());
    }

    #[test]
    fn a_file_field_projects_download_and_upload_endpoints() {
        let access = AccessRules {
            min_role_read: 80,
            min_role_write: 40,
        };
        let p = RestProvider::project("/api", &[table_with_file_field("posts", access)]);
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 4 + 2);

        // Addressed by table, row id and field name — never by raw store path.
        let download = p.endpoints().find("downloadPostsCover").unwrap();
        assert_eq!(download.method, Method::Get);
        assert_eq!(download.path.pattern(), "/api/posts/{id}/cover");
        assert!(download.binary_output, "a download serves bytes, not JSON");
        assert!(!download.binary_input);
        // Reads carry the table's read rule (the path-cumulative file rule is
        // enforced at request time, on top).
        assert_eq!(download.auth, AuthRequirement::MinRole(80));

        // The upload's filename is a path parameter: one segment by
        // construction, so a traversing destination cannot be expressed.
        let upload = p.endpoints().find("uploadPostsCover").unwrap();
        assert_eq!(upload.method, Method::Post);
        assert_eq!(upload.path.pattern(), "/api/posts/{id}/cover/{filename}");
        assert!(upload.binary_input, "an upload takes bytes, not JSON");
        // Uploads carry the table's write rule.
        assert_eq!(upload.auth, AuthRequirement::MinRole(40));
    }

    #[test]
    fn a_keyless_table_gets_no_file_endpoints() {
        // No row addressing ⇒ no way to say whose file it is.
        let mut t = keyless("logs");
        let mut attachment = DataField::plain("attachment", TypeRef::Basic(BasicType::Text));
        attachment.kind = DataFieldKind::File {
            store: FileStoreId("uploads".to_owned()),
            folder: None,
            mime_allow: vec![],
        };
        t.fields.push(attachment);
        let p = RestProvider::project("/api", &[t]);
        assert!(p.endpoints().find("downloadLogsAttachment").is_none());
        assert!(p.endpoints().find("uploadLogsAttachment").is_none());
    }

    #[test]
    fn the_generated_client_types_file_endpoints_as_binary() {
        let p = RestProvider::project(
            "/api",
            &[table_with_file_field("posts", AccessRules::default())],
        );
        let ts = crate::generate_client(p.endpoints());
        // A file column hangs its two calls off the table's own object: a
        // download resolves to a Blob, an upload takes what fetch can send raw.
        assert!(ts.contains("  cover: FileApi<number>;"), "{ts}");
        assert!(
            ts.contains("      async download(id: number): Promise<Blob> {"),
            "{ts}"
        );
        assert!(
            ts.contains(
                "      async upload(id: number, filename: string, body: BodyInit): \
                 Promise<unknown> {"
            ),
            "{ts}"
        );
        // The upload body goes out unencoded, with no JSON content type.
        assert!(!ts.contains("export type UploadPostsCoverRequest"));
        assert!(ts.contains("return await res.blob();"));
    }

    #[test]
    fn only_the_declared_tables_are_projected() {
        // The app declared `posts`; `secrets` is not in its subset (§13.2), so
        // the projection has no route to it at all.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert!(p.endpoints().find("listSecrets").is_none());
        assert!(
            p.resolve(&ApiRequest::get("/api/secrets")).is_err(),
            "an undeclared table must not be routable"
        );
    }

    #[test]
    fn mount_is_normalised_and_reflected_in_paths() {
        let p = RestProvider::project("v1/api/", &[table("posts", AccessRules::default())]);
        assert_eq!(p.mount(), "/v1/api");
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().path.pattern(),
            "/v1/api/posts"
        );
    }

    #[test]
    fn resolve_matches_method_and_path_and_captures_params() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let (ep, params) = p
            .resolve(&ApiRequest::new(Method::Put, "/api/posts/42"))
            .unwrap();
        assert_eq!(ep.name, "updatePosts");
        assert_eq!(params.get("id").unwrap(), "42");

        // A collection path captures nothing.
        let (ep, params) = p.resolve(&ApiRequest::get("/api/posts")).unwrap();
        assert_eq!(ep.name, "listPosts");
        assert!(params.is_empty());
    }

    #[test]
    fn unknown_path_is_404_and_wrong_method_is_405() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let miss = p.resolve(&ApiRequest::get("/api/nope")).unwrap_err();
        assert_eq!(miss.status, 404);

        // `/api/posts` exists, but not for PATCH.
        let wrong = p
            .resolve(&ApiRequest::new(Method::Patch, "/api/posts"))
            .unwrap_err();
        assert_eq!(wrong.status, 405);
    }

    #[test]
    fn auth_is_enforced_before_anything_runs() {
        // Anonymous callers are rejected...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), None)
                .unwrap()
                .status,
            401
        );
        // ...under-privileged ones are forbidden...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), Some(&user(100)))
                .unwrap()
                .status,
            403
        );
        // ...and a sufficiently privileged one passes. Roles run 1..=100 with
        // lower = more privilege, so admin (1) clears a min_role of 80.
        assert!(enforce_auth(&AuthRequirement::MinRole(80), Some(&user(1))).is_none());
        assert!(enforce_auth(&AuthRequirement::Public, None).is_none());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, Some(&user(100))).is_none());
    }

    #[test]
    fn an_exposed_trigger_is_one_post_endpoint_carrying_its_own_role_floor() {
        use sc_action::{EventKind, Trigger};

        let open = Trigger::new("send_digest", EventKind::None, "fetch").min_role(80);
        // No `min_role`: nobody has decided who may call it.
        let unset = Trigger::new("purge_users", EventKind::None, "fetch");
        let p = RestProvider::project_with(
            "/api",
            &[table("posts", AccessRules::default())],
            &[open, unset],
        );
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 4 + 2);

        let ep = p.endpoints().find("runSendDigest").unwrap();
        assert_eq!(ep.method, Method::Post);
        // Under `actions/`, so a trigger can never be confused with a table.
        assert_eq!(ep.path.pattern(), "/api/actions/send_digest");
        assert_eq!(ep.auth, AuthRequirement::MinRole(80));

        // The undecided one is admin-only, not public.
        assert_eq!(
            p.endpoints().find("runPurgeUsers").unwrap().auth,
            AuthRequirement::MinRole(sc_auth::ROLE_ADMIN)
        );

        // It routes, and it is typed into the app's client like anything else.
        let (ep, params) = p
            .resolve(&ApiRequest::new(Method::Post, "/api/actions/send_digest"))
            .unwrap();
        assert_eq!(ep.name, "runSendDigest");
        assert!(params.is_empty());
        assert!(crate::generate_client(p.endpoints()).contains("runSendDigest("));
    }

    #[test]
    fn a_trigger_the_app_does_not_expose_has_no_endpoint_at_all() {
        // The 404/403 distinction matters: a trigger nobody exposed is not a
        // permission problem to be escalated, it is not there.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let miss = p
            .resolve(&ApiRequest::new(Method::Post, "/api/actions/send_digest"))
            .unwrap_err();
        assert_eq!(miss.status, 404);
    }

    #[test]
    fn custom_routes_are_projected_and_typed() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())])
            .with_custom_route(
                Endpoint::new("search", Method::Post, PathSpec::root().lit("api/search"))
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .handler(HandlerRef::Sql("select 1".to_owned())),
            );
        // The custom route is part of the contract even though it is stubbed.
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 4 + 1);
        let ep = p.endpoints().find("search").unwrap();
        assert!(matches!(ep.handler, HandlerRef::Sql(_)));

        // A generated client types it like any other endpoint.
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("search("));
        // …beside the table's own object, which is where its four endpoints went.
        assert!(ts.contains("posts: PostsApi;"), "{ts}");
    }

    /// A custom SQL query is an endpoint like any other — typed client method,
    /// role floor, query-string parameters — and its name is checked against
    /// what the API already projects rather than panicking the registry.
    #[test]
    fn custom_sql_queries_are_projected_with_their_own_authority() {
        let query = custom::CustomQuery::new(
            "topAuthors",
            Method::Get,
            "/reports/top-authors",
            "SELECT author FROM posts WHERE id > :since",
        )
        .params([custom::CustomParam::new("since", ValueType::Int)])
        .min_role(40);
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())])
            .with_queries(vec![query.clone()])
            .expect("projects");

        let ep = p.endpoints().find("topAuthors").unwrap();
        assert_eq!(ep.path.pattern(), "/api/reports/top-authors");
        // The query's own floor, not the tables' — a custom query's authority is
        // its own (§13.4).
        assert_eq!(ep.auth, AuthRequirement::MinRole(40));
        assert_eq!(ep.query.len(), 1);
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("topAuthors("), "{ts}");

        // A name the API already projects is a mount error, not a panic.
        let clash = custom::CustomQuery::new("listPosts", Method::Get, "/x", "SELECT 1 AS n");
        let err = match RestProvider::project("/api", &[table("posts", AccessRules::default())])
            .with_queries(vec![clash])
        {
            Err(e) => e.to_string(),
            Ok(_) => panic!("a name the API already projects must be refused"),
        };
        assert!(err.contains("listPosts"), "{err}");
    }

    #[test]
    fn every_app_projects_its_own_auth_endpoints() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        // The app authenticates against its own API, not the admin's (§7.2).
        let login = p.endpoints().find("login").unwrap();
        assert_eq!(login.method, Method::Post);
        assert_eq!(login.path.pattern(), "/api/login");
        // Login is the one public endpoint: it is how a caller stops being
        // anonymous. Everything else needs a session.
        assert_eq!(login.auth, AuthRequirement::Public);

        assert_eq!(
            p.endpoints().find("logout").unwrap().auth,
            AuthRequirement::LoggedIn
        );
        assert_eq!(
            p.endpoints().find("whoami").unwrap().auth,
            AuthRequirement::LoggedIn
        );

        // Anonymous callers are turned away from everything but login.
        assert!(p.resolve(&ApiRequest::get("/api/whoami")).is_ok());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&login.auth, None).is_none());
    }

    /// Sign-up is off unless the application's settings turn it on, and when
    /// they do it is one more public auth endpoint — ahead of every table's, so
    /// a table called `signup` cannot shadow it.
    #[test]
    fn signup_is_projected_only_where_the_settings_offer_it() {
        let tables = [
            table("posts", AccessRules::default()),
            table("signup", AccessRules::default()),
        ];
        let off = RestProvider::project("/api", &tables);
        assert!(off.endpoints().find("signup").is_none());
        assert!(!crate::generate_client(off.endpoints()).contains("signup(body"));

        let mut config = Attrs::new();
        assert_eq!(rest_signup_role(&config), None);
        config.insert(CFG_ALLOW_SIGNUP.to_owned(), Json::Bool(true));
        assert_eq!(rest_signup_role(&config), Some(DEFAULT_NEW_USER_ROLE));
        config.insert(CFG_NEW_USER_ROLE.to_owned(), Json::from(40));
        assert_eq!(rest_signup_role(&config), Some(40));

        let on = RestProvider::project("/api", &tables).with_signup(rest_signup_role(&config));
        let signup = on.endpoints().find("signup").expect("projected");
        assert_eq!(signup.method, Method::Post);
        assert_eq!(signup.path.pattern(), "/api/signup");
        assert_eq!(signup.auth, AuthRequirement::Public);
        assert_eq!(on.endpoints().len(), off.endpoints().len() + 1);
        // The table's own create is registered after it, so resolution finds
        // the sign-up.
        let (ep, _) = on
            .resolve(&ApiRequest::new(Method::Post, "/api/signup"))
            .unwrap();
        assert_eq!(ep.name, "signup");
        // The resources survive the rebuild, and the client gains the method.
        assert!(on.endpoints().resource("posts").is_some());
        let ts = crate::generate_client(on.endpoints());
        assert!(ts.contains("signup(body: SignupRequest)"), "{ts}");

        // A custom query cannot take the name once sign-up is on.
        let clash = custom::CustomQuery::new("signup", Method::Get, "/x", "SELECT 1 AS n");
        assert!(on.with_queries(vec![clash]).is_err());
    }

    /// Anybody can make an account through sign-up, so it may never make an
    /// administrator — refused on save, and failed closed if one got stored.
    #[test]
    fn signup_never_makes_an_administrator() {
        let mut config = Attrs::new();
        config.insert(CFG_ALLOW_SIGNUP.to_owned(), Json::Bool(true));
        config.insert(CFG_NEW_USER_ROLE.to_owned(), Json::from(1));
        let msg = check_rest_config(&config).unwrap_err().to_string();
        assert!(msg.contains(CFG_NEW_USER_ROLE), "{msg}");
        assert_eq!(rest_signup_role(&config), None);

        config.insert(CFG_NEW_USER_ROLE.to_owned(), Json::from(80));
        check_rest_config(&config).expect("an ordinary role is fine");
        // The spec validates the settings the form renders.
        sc_types::validate_attrs(&rest_config_spec(), &config).expect("declared settings");
    }

    #[test]
    fn a_table_cannot_collide_with_the_auth_endpoints() {
        // A table actually named `login` still projects `listLogin` etc., because
        // table operations are always prefixed — so it cannot shadow the app's
        // own `login`.
        let p = RestProvider::project("/api", &[table("login", AccessRules::default())]);
        assert_eq!(p.endpoints().find("login").unwrap().method, Method::Post);
        assert!(p.endpoints().find("listLogin").is_some());
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINT_COUNT + 4);

        // In the generated client the two would want the same property, so the
        // *table* yields: `login()` is a name the server fixed for every app,
        // and renaming it would break the ones that call it.
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("  loginTable: LoginApi;"), "{ts}");
        assert!(ts.contains("login(body: LoginRequest)"), "{ts}");
        assert_eq!(
            crate::client_property(p.endpoints(), "login").as_deref(),
            Some("loginTable")
        );
    }

    /// A table whose rows cannot be addressed gets the two operations it can
    /// answer and no others — the client says exactly what the projection did.
    #[test]
    fn a_keyless_table_gets_a_client_object_with_only_the_reads_it_can_answer() {
        let p = RestProvider::project("/api", &[keyless("logs")]);
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("  logs: LogsApi;"), "{ts}");
        assert!(ts.contains("  list<S extends string = \"\">"), "{ts}");
        assert!(ts.contains("  create(row: LogsInsert)"), "{ts}");
        // No key to address a row by, so no `get`, `update` or `delete` — and no
        // `LogsUpdate` type for a call that cannot be made.
        for absent in ["  get<S extends", "  update(id", "  delete(id"] {
            assert!(!ts.contains(absent), "{absent} must be absent:\n{ts}");
        }
    }

    /// The model names endpoints; a name the set does not have is a mistake in
    /// the projection, not something to discover in a generated client that
    /// calls a route the server never mounted.
    #[test]
    #[should_panic(expected = "which is not registered")]
    fn a_resource_naming_an_endpoint_the_set_lacks_is_refused() {
        let mut set = EndpointSet::new();
        let mut model = crate::ResourceModel::new("ghosts");
        model.ops.list = Some("listGhosts".to_owned());
        set.register_resource(model);
    }

    #[test]
    fn the_projection_generates_a_typed_client() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let ts = crate::generate_client(p.endpoints());
        // Same generator as the admin API: an app's client is not special-cased.
        assert!(ts.contains("export interface ApiClient {"));
        // A table is one object with methods over its own row type, not four
        // loose methods returning `unknown` (§13.1).
        assert!(ts.contains("  posts: PostsApi;"), "{ts}");
        assert!(ts.contains("export interface PostsRow {"), "{ts}");
        assert!(
            ts.contains(
                "  list<S extends string = \"\">(query?: PostsQuery<S>): \
                 Promise<Array<PostsSelected<S>>>;"
            ),
            "{ts}"
        );
        assert!(ts.contains("  update(id: number, row: PostsUpdate): Promise<PostsRow>;"));
        assert!(ts.contains("/api/posts/${id}"));
        // …and no loose method survives beside it.
        assert!(!ts.contains("listPosts("), "{ts}");
    }

    #[test]
    fn a_list_endpoint_declares_the_read_query_string_and_types_it() {
        // §13.1's rule applied to §13.4's query string: what a read may say is
        // part of the endpoint, so the client can say it. A hand-written `fetch`
        // beside a generated client is where drift starts.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let list = p.endpoints().find("listPosts").expect("the list endpoint");
        let names: Vec<&str> = list.query.iter().map(|q| q.name.as_str()).collect();
        assert_eq!(names, vec!["select", "order", "limit", "offset", "filter"]);
        // None of them is required: `listPosts()` still takes no argument.
        assert!(list.query.iter().all(|q| !q.required));
        // Writing endpoints declare none — a query string is a read's vocabulary.
        assert!(
            p.endpoints()
                .find("createPosts")
                .expect("the create endpoint")
                .query
                .is_empty()
        );

        let ts = crate::generate_client(p.endpoints());
        // The read's query type is the endpoint's parameters, typed against the
        // table's own columns: a column that is not there is a compile error
        // rather than the 400 it would otherwise become.
        assert!(
            ts.contains(
                "export type PostsQuery<S extends string = \"\"> = {\n\
                 \x20 /** Columns and embeds to return, e.g. `\"id,title\"`. Omit for whole rows. */\n\
                 \x20 select?: S;\n\
                 \x20 /** `\"published.desc\"`, or a precedence list of such keys. */\n\
                 \x20 order?: Order<PostsRow>;\n\
                 \x20 limit?: number;\n\
                 \x20 offset?: number;\n"
            ),
            "{ts}"
        );
        assert!(ts.contains("  filter?: Filters<PostsRow>;"), "{ts}");
        // A filter's *keys* are column names, so each entry is a pair of its own
        // — `?published=gte.2020-01-01`, not `?filter=…`.
        assert!(
            ts.contains(
                "for (const [key, value] of Object.entries(query?.filter ?? {})) \
                 search.append(key, String(value));"
            ),
            "{ts}"
        );
    }

    #[test]
    fn the_row_cap_comes_from_the_applications_provider_configuration() {
        let mut config = Attrs::new();
        assert_eq!(rest_row_cap(&config), DEFAULT_ROW_CAP);
        config.insert(CFG_ROW_CAP.to_owned(), Json::from(25));
        assert_eq!(rest_row_cap(&config), 25);
        // Unreadable is the default, not zero — which would be a REST API that
        // answers every list with nothing. The value was validated on save.
        config.insert(CFG_ROW_CAP.to_owned(), Json::String("lots".to_owned()));
        assert_eq!(rest_row_cap(&config), DEFAULT_ROW_CAP);
        // And the setting the spec declares is the setting this reads.
        let spec = rest_config_spec();
        assert!(spec.iter().any(|f| f.name() == CFG_ROW_CAP));
    }
}
