//! Phase 7: an application exposes a subset of the server's triggers as API
//! endpoints (§10.2/§13.4), driven through the assembled router against a real
//! database.
//!
//! The claim being tested is narrower than "a trigger can be called over HTTP".
//! It is that **an app's API surface is the app's declaration**:
//!
//! - a trigger the app names is one `POST {mount}/actions/{name}`, the body is
//!   the event's payload, and the answer is what the action returned — including
//!   the row it wrote through the ordinary write path;
//! - the endpoint is guarded by the **trigger's own** `min_role`, and a trigger
//!   with none is admin-only rather than open;
//! - a trigger the app does *not* name is a **404** — not a 403 — even though the
//!   server has it and can run it;
//! - and the set is live: changing a trigger's role through the admin API changes
//!   what the mounted app enforces, with no restart.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_action::{EventKind, Trigger, TriggerDispatcher, save_trigger};
use sc_app::{ApiConfig, Application, AssetBundle, CodeFramework, FrameworkRef, TriggerRef};
use sc_auth::{ROLE_ADMIN, Role, SessionStore, create_user, save_role};
use sc_catalog::{Catalog, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, MountedApp, ServerConfig, admin_handlers,
    build_router_with_apps, default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

const BASE_DOMAIN: &str = "example.com";
const APP_HOST: &str = "blog.example.com";

const SCHEMA: &str = "\
    CREATE TABLE posts (id bigint generated by default as identity primary key, \
        title text not null); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        title text, who text);";

const ADMIN: &str = "admin@example.com";
const EDITOR: &str = "editor@example.com";
const READER: &str = "reader@example.com";
const PASSWORD: &str = "correct-horse";

/// The role floor `visit_logged` is exposed at: an editor may call it, a reader
/// may not.
const ROLE_EDITOR: u8 = 80;
const ROLE_READER: u8 = 100;

/// A cookie-carrying client addressing one host — the app's subdomain, or the
/// admin (no app host).
struct Client {
    router: Router,
    host: String,
    cookies: HashMap<String, String>,
}

impl Client {
    fn new(router: Router, host: &str) -> Client {
        Client {
            router,
            host: host.to_owned(),
            cookies: HashMap::new(),
        }
    }

    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder()
            .method(method)
            .uri(path)
            .header(header::HOST, &self.host);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                if value.is_empty() {
                    self.cookies.remove(name);
                } else {
                    self.cookies.insert(name.to_owned(), value.to_owned());
                }
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    /// One GET before anything is posted, so the CSRF cookie a browser would
    /// already be carrying is set — the same handshake the SPA makes.
    async fn prime(&mut self) {
        self.send("GET", "/api/whoami", None).await;
    }

    /// Authenticate through the **app's own** login (§7.2), the way its React
    /// code would.
    async fn login(&mut self, email: &str) {
        self.prime().await;
        let (status, body) = self
            .send(
                "POST",
                "/api/login",
                Some(json!({ "email": email, "password": PASSWORD })),
            )
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
    }

    /// Authenticate against the admin API.
    async fn admin_login(&mut self) {
        self.send("GET", "/api/auth/status", None).await;
        self.prime().await;
        let (status, body) = self
            .send(
                "POST",
                "/api/login",
                Some(json!({ "email": ADMIN, "password": PASSWORD })),
            )
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
    }
}

/// A trigger with no intrinsic event, writing an audit row from the payload and
/// the caller. `none` is the kind an API call is *for*: it runs because something
/// asked it to.
fn audit_trigger(name: &str, min_role: Option<u8>) -> Trigger {
    let mut trigger = Trigger::new(name, EventKind::None, "insert_row")
        .config("table", "audit")
        .config(
            "values",
            json!({ "title": "payload.what", "who": "user.email" }),
        );
    if let Some(role) = min_role {
        trigger = trigger.min_role(role);
    }
    trigger
}

fn blog_app() -> Application {
    Application::new("Blog", "blog", FrameworkRef::new("code"))
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"))
        // The exposed subset: two of the server's three triggers.
        .with_trigger(TriggerRef::new("visit_logged"))
        .with_trigger(TriggerRef::new("purge_audit"))
}

struct Server {
    router: Router,
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    apps: Arc<AppMounts>,
    _db: TestDb,
}

impl Server {
    fn app_client(&self) -> Client {
        Client::new(self.router.clone(), APP_HOST)
    }

    fn admin_client(&self) -> Client {
        Client::new(self.router.clone(), BASE_DOMAIN)
    }

    /// The audit rows, oldest first — what a trigger's action actually wrote.
    async fn audit(&self) -> Vec<(String, String)> {
        let rows = self
            ._db
            .client()
            .await
            .unwrap()
            .query("SELECT title, who FROM audit ORDER BY id", &[])
            .await
            .unwrap();
        rows.iter().map(|r| (r.get(0), r.get(1))).collect()
    }
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    // A user's role has to be one the server defines; `public` (100) is built in.
    save_role(&catalog, &Role::new(ROLE_EDITOR, "Editor")).await?;
    create_user(&catalog, ADMIN, PASSWORD, ROLE_ADMIN).await?;
    create_user(&catalog, EDITOR, PASSWORD, ROLE_EDITOR).await?;
    create_user(&catalog, READER, PASSWORD, ROLE_READER).await?;

    let evaluator = default_js_evaluator();
    let dispatcher = install_triggers(&catalog, evaluator.clone()).await?;

    // Three triggers: one an editor may call, one nobody has decided the access
    // of (so: admins), and one the application does not expose at all.
    for trigger in [
        audit_trigger("visit_logged", Some(ROLE_EDITOR)),
        audit_trigger("purge_audit", None),
        audit_trigger("internal_only", Some(ROLE_READER)),
    ] {
        save_trigger(&catalog, dispatcher.registry(), &trigger).await?;
    }
    dispatcher.reload(&catalog).await?;

    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_evaluator(evaluator)
            .with_triggers(dispatcher.clone()),
    );
    // A built bundle stands in for the bundler's output: this test is about the
    // app's API, and what its UI serves is `app_serving`'s story.
    let framework = Arc::new(CodeFramework::new(
        "code",
        AssetBundle::new().with("index.html", "<!doctype html>"),
    ));
    apps.mount(MountedApp::new_with(
        blog_app(),
        framework,
        &catalog,
        apps.evaluator(),
        apps.triggers(),
    )?)?;

    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        ..ServerConfig::default()
    };
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &config,
        apps.clone(),
    )?;

    Ok(Server {
        router,
        catalog,
        dispatcher,
        apps,
        _db: db,
    })
}

#[tokio::test]
async fn an_exposed_trigger_runs_at_the_apps_mount_and_answers_with_its_result()
-> sc_error::Result<()> {
    let server = setup().await?;
    let mut app = server.app_client();
    app.login(EDITOR).await;

    let (status, body) = app
        .send(
            "POST",
            "/api/actions/visit_logged",
            Some(json!({ "what": "homepage" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    // The answer is the action's own result — here the row `insert_row` wrote,
    // so a caller can use what it just created.
    assert_eq!(body["title"], json!("homepage"));
    // The caller travelled with the call: the action's `user.email` is the app
    // user who made the request, not the server.
    assert_eq!(body["who"], json!(EDITOR));

    // And it really wrote it, through the ordinary row path.
    assert_eq!(
        server.audit().await,
        vec![("homepage".to_owned(), EDITOR.to_owned())]
    );

    // The app's generated client gets a typed method for it, which is what makes
    // the endpoint reachable from the app's own code without hand-written fetch.
    let ts = sc_app::app_client_with(&blog_app(), &server.catalog, Some(&server.dispatcher))?;
    assert!(ts.contains("runVisitLogged("), "{ts}");
    assert!(ts.contains("/api/actions/visit_logged"), "{ts}");
    Ok(())
}

#[tokio::test]
async fn the_triggers_own_min_role_guards_the_endpoint() -> sc_error::Result<()> {
    let server = setup().await?;

    // Anonymous: the endpoint exists, but not for you.
    let mut anon = server.app_client();
    anon.prime().await;
    let (status, _) = anon
        .send("POST", "/api/actions/visit_logged", Some(json!({})))
        .await;
    assert_eq!(status, StatusCode::UNAUTHORIZED);

    // A reader is below the trigger's floor.
    let mut reader = server.app_client();
    reader.login(READER).await;
    let (status, _) = reader
        .send("POST", "/api/actions/visit_logged", Some(json!({})))
        .await;
    assert_eq!(status, StatusCode::FORBIDDEN);

    // A trigger with **no** `min_role` is admin-only, not public: an editor who
    // may call the first one may not call this one.
    let mut editor = server.app_client();
    editor.login(EDITOR).await;
    let (status, _) = editor
        .send("POST", "/api/actions/purge_audit", Some(json!({})))
        .await;
    assert_eq!(status, StatusCode::FORBIDDEN);

    let mut admin = server.app_client();
    admin.login(ADMIN).await;
    let (status, body) = admin
        .send(
            "POST",
            "/api/actions/purge_audit",
            Some(json!({ "what": "cleanup" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    // Only the one call that passed wrote anything.
    assert_eq!(
        server.audit().await,
        vec![("cleanup".to_owned(), ADMIN.to_owned())]
    );
    Ok(())
}

#[tokio::test]
async fn a_trigger_the_app_does_not_expose_is_not_there_at_all() -> sc_error::Result<()> {
    let server = setup().await?;
    let mut admin = server.app_client();
    admin.login(ADMIN).await;

    // Not 403: exposing a trigger is the *application's* decision, so one it did
    // not name has no endpoint for any role to be refused at.
    let (status, body) = admin
        .send("POST", "/api/actions/internal_only", Some(json!({})))
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND, "{body}");

    // Which is not the same as the trigger being missing: the server has it, and
    // it runs when the server itself asks.
    let caller = sc_catalog::CallerContext::new(ROLE_ADMIN, Some(json!({ "email": ADMIN })));
    let result = server
        .dispatcher
        .run_trigger(
            &server.catalog,
            "internal_only",
            json!({ "what": "internal" }),
            Some(&caller),
        )
        .await?;
    assert_eq!(result["title"], json!("internal"));
    assert_eq!(server.audit().await.len(), 1);
    Ok(())
}

#[tokio::test]
async fn changing_a_triggers_role_re_projects_the_mounted_app() -> sc_error::Result<()> {
    let server = setup().await?;

    // The editor can call it today.
    let mut editor = server.app_client();
    editor.login(EDITOR).await;
    let (status, _) = editor
        .send(
            "POST",
            "/api/actions/visit_logged",
            Some(json!({ "what": "before" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK);

    // The admin tightens it to admins only, through the admin API.
    let mut admin = server.admin_client();
    admin.admin_login().await;
    let (status, listed) = admin.send("GET", "/api/triggers", None).await;
    assert_eq!(status, StatusCode::OK, "{listed}");
    let stored = listed
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == json!("visit_logged"))
        .expect("the trigger")
        .clone();
    let id = stored["id"].as_str().unwrap().to_owned();
    let mut body = stored.clone();
    body["min_role"] = json!(ROLE_ADMIN);
    let (status, updated) = admin
        .send("PUT", &format!("/api/triggers/{id}"), Some(body))
        .await;
    assert_eq!(status, StatusCode::OK, "{updated}");

    // The mounted app enforces the new floor **now**: a provider encodes the
    // role it was projected with, so without the re-projection this would go on
    // succeeding until the next restart.
    let (status, _) = editor
        .send(
            "POST",
            "/api/actions/visit_logged",
            Some(json!({ "what": "after" })),
        )
        .await;
    assert_eq!(status, StatusCode::FORBIDDEN);
    assert_eq!(server.audit().await.len(), 1, "only the first call ran");

    // The app is still mounted and serving everything else.
    assert_eq!(server.apps.subdomains(), vec!["blog".to_owned()]);
    let (status, _) = editor.send("GET", "/api/whoami", None).await;
    assert_eq!(status, StatusCode::OK);
    Ok(())
}

#[tokio::test]
async fn an_app_naming_a_trigger_that_is_not_there_refuses_to_mount() -> sc_error::Result<()> {
    let server = setup().await?;
    let framework = Arc::new(CodeFramework::new("code", AssetBundle::new()));

    // A declared trigger that does not resolve is a configuration error, exactly
    // as a declared table that is not in the catalog is — the app would otherwise
    // come up serving an API its own generated client does not match.
    let dangling = blog_app()
        .with_trigger(TriggerRef::new("was_deleted"))
        .with_id(sc_app::AppId::new());
    let Err(err) = MountedApp::new_with(
        dangling,
        framework.clone(),
        &server.catalog,
        server.apps.evaluator(),
        server.apps.triggers(),
    ) else {
        panic!("a dangling trigger reference must not mount")
    };
    let msg = err.to_string();
    assert!(
        msg.contains("was_deleted"),
        "should name the trigger: {msg}"
    );
    assert!(msg.contains("Blog"), "should name the application: {msg}");

    // And an app with exposed triggers cannot be projected at all without a
    // trigger set: silently dropping the endpoints would be the worse failure.
    let Err(err) = MountedApp::new_with(
        blog_app(),
        framework,
        &server.catalog,
        server.apps.evaluator(),
        None,
    ) else {
        panic!("an app with exposed triggers must not project without a trigger set")
    };
    assert!(err.to_string().contains("visit_logged"), "{err}");
    Ok(())
}

#[tokio::test]
async fn deleting_an_exposed_trigger_succeeds_and_leaves_the_app_serving() -> sc_error::Result<()> {
    let server = setup().await?;
    let mut admin = server.admin_client();
    admin.admin_login().await;

    let (_, listed) = admin.send("GET", "/api/triggers", None).await;
    let id = listed
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == json!("purge_audit"))
        .expect("the trigger")["id"]
        .as_str()
        .unwrap()
        .to_owned();

    // Deleting a trigger an application exposes is **allowed**: blocking it would
    // leave an admin unable to remove a trigger they no longer want. What it
    // costs is that the app's declaration now dangles — which is reported, not
    // returned, because the trigger really was deleted.
    let (status, body) = admin
        .send("DELETE", &format!("/api/triggers/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["deleted"], json!(true));

    // The app is still mounted and its other endpoints still work: one dangling
    // reference does not take a running application down.
    assert_eq!(server.apps.subdomains(), vec!["blog".to_owned()]);
    let mut editor = server.app_client();
    editor.login(EDITOR).await;
    let (status, _) = editor
        .send(
            "POST",
            "/api/actions/visit_logged",
            Some(json!({ "what": "still here" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK);
    Ok(())
}
