//! An application endpoint whose role floor is the **public** role (100) is open
//! to anybody: no user, no password, no session, and no CSRF token (§7).
//!
//! Role 100 is the role a caller nobody is logged in as holds, so a floor at it
//! is not "any logged-in user of role 100" — it is "everybody". Driven through
//! the assembled router against a real database, for each of the three places
//! an application sets such a floor:
//!
//! - a **table** whose `min_role_read` / `min_role_write` is 100 — its REST
//!   endpoints;
//! - a **custom query** whose `min_role` is 100;
//! - an exposed **trigger** whose `min_role` is 100.
//!
//! Each is called with no cookie at all, which is how a `curl`, a webhook or a
//! third-party page calls it. And the CSRF exemption is bounded: a request that
//! carries a session but no token is served as the anonymous caller it would be
//! without one — its cookie lends it no authority — while an endpoint with any
//! stricter floor still refuses a request without the token.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_action::{EventKind, Trigger, save_trigger};
use sc_api::{CustomQuery, Method, set_custom_queries};
use sc_app::{ApiConfig, Application, AssetBundle, CodeFramework, FrameworkRef, TriggerRef};
use sc_auth::{ROLE_PUBLIC, Role, SessionStore, create_user, save_role};
use sc_catalog::{Catalog, TableId, TableMeta, bootstrap_table_meta, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, MountedApp, SESSION_COOKIE, ServerConfig, admin_handlers,
    build_router_with_apps, default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

const BASE_DOMAIN: &str = "example.com";
const APP_HOST: &str = "guests.example.com";

const SCHEMA: &str = "\
    CREATE TABLE guestbook (id bigint generated by default as identity primary key, \
        message text not null, who text); \
    CREATE TABLE secrets (id bigint generated by default as identity primary key, \
        message text not null);";

const EDITOR: &str = "editor@example.com";
const PASSWORD: &str = "correct-horse";
const ROLE_EDITOR: u8 = 80;

/// One request, spelled out: exactly the cookies and the CSRF header given, and
/// nothing a helper might add behind the test's back.
async fn send(
    router: &Router,
    method: &str,
    path: &str,
    body: Option<Value>,
    cookies: &[(&str, &str)],
    csrf: Option<&str>,
) -> (StatusCode, Value, Vec<String>) {
    let mut builder = Request::builder()
        .method(method)
        .uri(path)
        .header(header::HOST, APP_HOST);
    if !cookies.is_empty() {
        let jar = cookies
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join("; ");
        builder = builder.header(header::COOKIE, jar);
    }
    if let Some(token) = csrf {
        builder = builder.header(CSRF_HEADER, token);
    }
    let request = match body {
        Some(b) => builder
            .header(header::CONTENT_TYPE, "application/json")
            .body(Body::from(serde_json::to_vec(&b).unwrap()))
            .unwrap(),
        None => builder.body(Body::empty()).unwrap(),
    };
    let response = router.clone().oneshot(request).await.unwrap();
    let status = response.status();
    let set_cookies = response
        .headers()
        .get_all(header::SET_COOKIE)
        .iter()
        .filter_map(|v| v.to_str().ok().map(str::to_owned))
        .collect();
    let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
        .await
        .unwrap();
    let value = serde_json::from_slice(&bytes)
        .unwrap_or_else(|_| Value::String(String::from_utf8_lossy(&bytes).into_owned()));
    (status, value, set_cookies)
}

/// The value `name` is set to among a response's `Set-Cookie` headers.
fn cookie(set_cookies: &[String], name: &str) -> Option<String> {
    set_cookies.iter().find_map(|raw| {
        let (k, v) = raw.split(';').next()?.split_once('=')?;
        (k == name && !v.is_empty()).then(|| v.to_owned())
    })
}

/// A trigger writing a guestbook row from the payload and the caller.
fn sign_trigger(name: &str, min_role: u8) -> Trigger {
    Trigger::new(name, EventKind::None, "insert_row")
        .config("table", "guestbook")
        .config(
            "values",
            json!({ "message": "payload.message", "who": "user?.email ?? null" }),
        )
        .min_role(min_role)
}

fn guests_app() -> Application {
    let mut api = ApiConfig::new("rest", "/api");
    set_custom_queries(
        &mut api.config,
        &[
            CustomQuery::new(
                "countSignatures",
                Method::Get,
                "/stats/count",
                "SELECT count(*) AS n FROM guestbook",
            )
            .min_role(ROLE_PUBLIC),
            // A POST, so the CSRF middleware has something to say about it.
            CustomQuery::new(
                "latestSignature",
                Method::Post,
                "/stats/latest",
                "SELECT message FROM guestbook ORDER BY id DESC LIMIT 1",
            )
            .min_role(ROLE_PUBLIC),
        ],
    )
    .unwrap();
    Application::new("Guests", "guests", FrameworkRef::new("code"))
        .with_table(TableId("guestbook".to_owned()))
        .with_table(TableId("secrets".to_owned()))
        .with_api(api)
        .with_trigger(TriggerRef::new("sign"))
        .with_trigger(TriggerRef::new("sign_as_editor"))
}

struct Server {
    router: Router,
    db: TestDb,
}

impl Server {
    async fn guestbook(&self) -> Vec<(String, Option<String>)> {
        let rows = self
            .db
            .client()
            .await
            .unwrap()
            .query("SELECT message, who FROM guestbook ORDER BY id", &[])
            .await
            .unwrap();
        rows.iter().map(|r| (r.get(0), r.get(1))).collect()
    }

    /// Log the editor in through the app's own login, returning the session and
    /// CSRF cookies a browser would then hold.
    async fn editor_session(&self) -> (String, String) {
        let (_, _, primed) = send(&self.router, "GET", "/api/whoami", None, &[], None).await;
        let csrf = cookie(&primed, CSRF_COOKIE).expect("a first contact mints the CSRF cookie");
        let (status, body, set) = send(
            &self.router,
            "POST",
            "/api/login",
            Some(json!({ "email": EDITOR, "password": PASSWORD })),
            &[(CSRF_COOKIE, &csrf)],
            Some(&csrf),
        )
        .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        (
            cookie(&set, SESSION_COOKIE).expect("a login sets the session"),
            csrf,
        )
    }
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    bootstrap_table_meta(&catalog).await?;
    save_role(&catalog, &Role::new(ROLE_EDITOR, "Editor")).await?;
    create_user(&catalog, EDITOR, PASSWORD, ROLE_EDITOR).await?;

    // The guestbook is open to everybody, both ways; `secrets` keeps the
    // default, admin-only.
    save_table_meta(
        &catalog,
        &TableMeta::new("guestbook").access(ROLE_PUBLIC, ROLE_PUBLIC),
    )
    .await?;

    let evaluator = default_js_evaluator();
    let agents = sc_server::install_agents(&catalog).await?;
    let models = sc_server::install_models(&catalog, sc_model::DEFAULT_MAX_ROWS).await?;
    let dispatcher = install_triggers(&catalog, evaluator.clone(), &agents, &models).await?;
    for trigger in [
        sign_trigger("sign", ROLE_PUBLIC),
        sign_trigger("sign_as_editor", ROLE_EDITOR),
    ] {
        save_trigger(&catalog, &dispatcher.registry(), &trigger).await?;
    }
    dispatcher.reload(&catalog).await?;

    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_evaluator(evaluator)
            .with_triggers(dispatcher.clone()),
    );
    let framework = Arc::new(CodeFramework::new(
        "code",
        AssetBundle::new().with("index.html", "<!doctype html>"),
    ));
    apps.mount(MountedApp::new_with(
        guests_app(),
        framework,
        &catalog,
        apps.evaluator(),
        apps.triggers(),
    )?)?;

    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        ..ServerConfig::default()
    };
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &config,
        apps,
    )?;
    Ok(Server { router, db })
}

#[tokio::test]
async fn a_public_table_is_read_and_written_with_no_cookie_at_all() -> sc_error::Result<()> {
    let server = setup().await?;
    let r = &server.router;

    // No cookie, no token: a first contact that writes.
    let (status, body, _) = send(
        r,
        "POST",
        "/api/guestbook",
        Some(json!({ "message": "hello" })),
        &[],
        None,
    )
    .await;
    assert!(status.is_success(), "{status}: {body}");

    let (status, body, _) = send(r, "GET", "/api/guestbook", None, &[], None).await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body.as_array().map(Vec::len), Some(1), "{body}");

    // The admin-only table beside it is still closed, to a reader and a writer.
    let (status, _, _) = send(r, "GET", "/api/secrets", None, &[], None).await;
    assert_eq!(status, StatusCode::UNAUTHORIZED);
    let (status, _, _) = send(
        r,
        "POST",
        "/api/secrets",
        Some(json!({ "message": "x" })),
        &[],
        None,
    )
    .await;
    assert_eq!(
        status,
        StatusCode::FORBIDDEN,
        "no token, not public: CSRF refuses"
    );
    Ok(())
}

#[tokio::test]
async fn a_public_custom_query_answers_anybody() -> sc_error::Result<()> {
    let server = setup().await?;
    let r = &server.router;
    send(
        r,
        "POST",
        "/api/guestbook",
        Some(json!({ "message": "first" })),
        &[],
        None,
    )
    .await;

    let (status, body, _) = send(r, "GET", "/api/stats/count", None, &[], None).await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body[0]["n"], json!(1), "{body}");

    let (status, body, _) = send(r, "POST", "/api/stats/latest", None, &[], None).await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body[0]["message"], json!("first"), "{body}");
    Ok(())
}

#[tokio::test]
async fn a_public_trigger_runs_for_anybody_as_nobody() -> sc_error::Result<()> {
    let server = setup().await?;
    let r = &server.router;

    let (status, body, _) = send(
        r,
        "POST",
        "/api/actions/sign",
        Some(json!({ "message": "drive-by" })),
        &[],
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(
        server.guestbook().await,
        vec![("drive-by".to_owned(), None)]
    );

    // A trigger with a stricter floor is not reachable the same way.
    let (status, _, _) = send(
        r,
        "POST",
        "/api/actions/sign_as_editor",
        Some(json!({ "message": "nope" })),
        &[],
        None,
    )
    .await;
    assert_eq!(status, StatusCode::FORBIDDEN);
    assert_eq!(server.guestbook().await.len(), 1);
    Ok(())
}

/// The exemption is not a hole: a session without the token lends a request no
/// authority. On a public endpoint it runs as nobody; anywhere stricter it is
/// refused, as it always was.
#[tokio::test]
async fn a_session_without_the_token_is_served_as_nobody() -> sc_error::Result<()> {
    let server = setup().await?;
    let r = &server.router;
    let (session, csrf) = server.editor_session().await;
    let jar = [
        (SESSION_COOKIE, session.as_str()),
        (CSRF_COOKIE, csrf.as_str()),
    ];

    // With the token, the editor is the caller.
    let (status, body, _) = send(
        r,
        "POST",
        "/api/actions/sign",
        Some(json!({ "message": "signed" })),
        &jar,
        Some(&csrf),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    // Without it — what a cross-site form would send — the call still runs, but
    // as nobody: the session cookie rode along and was not read.
    let (status, body, set) = send(
        r,
        "POST",
        "/api/actions/sign",
        Some(json!({ "message": "forged" })),
        &jar,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(
        server.guestbook().await,
        vec![
            ("signed".to_owned(), Some(EDITOR.to_owned())),
            ("forged".to_owned(), None),
        ]
    );
    // Nor did it touch the session.
    assert_eq!(cookie(&set, SESSION_COOKIE), None, "{set:?}");

    // The editor's own trigger, without the token: refused before it runs.
    let (status, body, _) = send(
        r,
        "POST",
        "/api/actions/sign_as_editor",
        Some(json!({ "message": "forged" })),
        &jar,
        None,
    )
    .await;
    assert_eq!(status, StatusCode::FORBIDDEN, "{body}");
    assert!(body.to_string().contains("CSRF"), "{body}");
    assert_eq!(server.guestbook().await.len(), 2);

    // And the session survived it all.
    let (status, body, _) = send(r, "GET", "/api/whoami", None, &jar, None).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body["email"], json!(EDITOR), "{body}");
    Ok(())
}
