//! A coding run's **preview mount** (TODO 6b.3): a green build of the run is
//! served at `<label>--<subdomain>`, beside the live mount and replacing
//! nothing, to that run's own session and to no one else; it is re-mounted
//! under the same label, unmounted when the run ends, and swept when idle.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_agent::{AppPreviewer, RunId};
use sc_app::{
    ApiConfig, Application, FrameworkRef, app_source_from_config, bootstrap, save_application,
};
use sc_auth::{SessionStore, User};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_server::{AppMounts, ServerConfig, admin_handlers, build_and_mount, build_router_with_apps};
use sc_test_harness::TestDb;
use tower::ServiceExt;

const BASE_DOMAIN: &str = "example.com";
const APP_HOST: &str = "blog.example.com";

struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> TempDir {
        let dir = std::env::temp_dir().join(format!(
            "sc-server-preview-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir).unwrap();
        TempDir(dir)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// A bundler that stamps `marker` into `index.html`.
fn write_bundler(root: &Path, marker: &str) {
    let web = root.join("web");
    std::fs::create_dir_all(web.join("src")).unwrap();
    let script = format!(
        "#!/bin/sh\nset -e\nmkdir -p dist\nprintf '<div id=root>{marker}</div>' > dist/index.html\n"
    );
    std::fs::write(web.join("build.sh"), script).unwrap();
}

fn blog_app() -> Application {
    let framework = FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/client.ts");
    Application::new("Blog", "blog", framework)
        .with_table(TableId("posts".to_owned()))
        .with_file_store(FileStoreId("apps".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"))
}

struct Env {
    apps: Arc<AppMounts>,
    router: Router,
    catalog: Arc<Catalog>,
    sessions: Arc<SessionStore>,
    app: Application,
    _db: TestDb,
}

async fn setup(tmp: &TempDir, idle: Duration) -> sc_error::Result<Env> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (id bigint generated by default as identity primary key, \
             title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    bootstrap(&catalog).await?;
    catalog.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_base_domain(Some(BASE_DOMAIN.to_owned()))
            .with_preview_idle(idle),
    );
    let sessions = Arc::new(SessionStore::default());
    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        ..ServerConfig::default()
    };
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        sessions.clone(),
        &config,
        apps.clone(),
    )?;

    // The live mount serves the published build.
    let app = blog_app();
    write_bundler(tmp.path(), "live");
    save_application(&catalog, &app).await?;
    build_and_mount(&apps, app.clone()).await?;
    Ok(Env {
        apps,
        router,
        catalog,
        sessions,
        app,
        _db: db,
    })
}

impl Env {
    /// Build the application with `marker` without mounting it, as `check`
    /// does, and mount the result as `run`'s preview.
    async fn preview_build(
        &self,
        tmp: &TempDir,
        run: RunId,
        marker: &str,
    ) -> sc_error::Result<sc_agent::PreviewInfo> {
        write_bundler(tmp.path(), marker);
        let source = app_source_from_config(&self.app.framework)?;
        let report = sc_app::build_application(&self.catalog, &self.app, &source, None).await?;
        AppPreviewer::mount_preview(self.apps.as_ref(), run, "blog", &report.output_dir).await
    }

    async fn get(&self, host: &str, session: Option<&str>) -> (StatusCode, String) {
        let mut request = Request::builder()
            .method("GET")
            .uri("/")
            .header(header::HOST, host);
        if let Some(token) = session {
            request = request.header(header::COOKIE, format!("sc_session={token}"));
        }
        let response = self
            .router
            .clone()
            .oneshot(request.body(Body::empty()).unwrap())
            .await
            .unwrap();
        let status = response.status();
        let bytes = axum::body::to_bytes(response.into_body(), 64 * 1024)
            .await
            .unwrap();
        (status, String::from_utf8_lossy(&bytes).into_owned())
    }

    async fn login(&self) -> String {
        let user = User::new(uuid::Uuid::new_v4(), 1).unwrap();
        self.sessions.login(user).await.unwrap()
    }
}

#[tokio::test]
async fn a_preview_serves_the_runs_build_to_the_runs_session_only() -> sc_error::Result<()> {
    let tmp = TempDir::new("routing");
    let env = setup(&tmp, Duration::from_secs(3600)).await?;
    let run = RunId::new();

    let preview = env.preview_build(&tmp, run, "run-v1").await?;
    assert_eq!(preview.subdomain, "blog");
    assert_eq!(preview.label.len(), 12);
    assert_eq!(
        preview.host,
        format!("{}--blog.{BASE_DOMAIN}", preview.label)
    );
    assert_eq!(
        AppPreviewer::preview(env.apps.as_ref(), run, "blog"),
        Some(preview.clone())
    );
    assert_eq!(
        AppPreviewer::preview(env.apps.as_ref(), RunId::new(), "blog"),
        None
    );

    // No session, and another admin's session: the answer an unknown host gets.
    let (status, _) = env.get(&preview.host, None).await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    let someone_else = env.login().await;
    let (status, _) = env.get(&preview.host, Some(&someone_else)).await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    // The run's own session.
    let token = env.login().await;
    env.apps.allow_preview_session(run, &token);
    let (status, body) = env.get(&preview.host, Some(&token)).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, "<div id=root>run-v1</div>");
    // The same label under another application is not this preview.
    let (status, _) = env
        .get(
            &format!("{}--other.{BASE_DOMAIN}", preview.label),
            Some(&token),
        )
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    // The live mount still serves what the admin published.
    let (status, body) = env.get(APP_HOST, None).await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, "<div id=root>live</div>");

    // A later green build re-mounts under the same label, and the session holds.
    let again = env.preview_build(&tmp, run, "run-v2").await?;
    assert_eq!(again, preview);
    assert_eq!(env.apps.preview_count(), 1);
    let (_, body) = env.get(&preview.host, Some(&token)).await;
    assert_eq!(body, "<div id=root>run-v2</div>");
    let (_, body) = env.get(APP_HOST, None).await;
    assert_eq!(body, "<div id=root>live</div>");

    // Another run's preview is another label, which the first run's session
    // does not reach.
    let other_run = RunId::new();
    let other = env.preview_build(&tmp, other_run, "other-run").await?;
    assert_ne!(other.label, preview.label);
    let (status, _) = env.get(&other.host, Some(&token)).await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    // The run ends: its preview goes, and its host is a 404 even with the
    // session it had.
    AppPreviewer::unmount_previews(env.apps.as_ref(), run);
    assert_eq!(env.apps.preview_count(), 1);
    let (status, _) = env.get(&preview.host, Some(&token)).await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert_eq!(AppPreviewer::preview(env.apps.as_ref(), run, "blog"), None);
    Ok(())
}

#[tokio::test]
async fn an_idle_preview_is_swept_and_a_used_one_is_kept() -> sc_error::Result<()> {
    let tmp = TempDir::new("sweep");
    let env = setup(&tmp, Duration::from_secs(60)).await?;
    let idle_run = RunId::new();
    let busy_run = RunId::new();
    let idle = env.preview_build(&tmp, idle_run, "idle").await?;
    env.preview_build(&tmp, busy_run, "busy").await?;

    // Nothing is stale yet.
    assert!(env.apps.sweep_previews(Instant::now()).is_empty());

    // The idle one was last used before `mid`, the busy one after it.
    tokio::time::sleep(Duration::from_millis(25)).await;
    let mid = Instant::now();
    tokio::time::sleep(Duration::from_millis(25)).await;
    assert!(AppPreviewer::preview(env.apps.as_ref(), busy_run, "blog").is_some());

    // A minute after `mid`, only the idle one is past the idle time.
    let swept = env.apps.sweep_previews(mid + Duration::from_secs(60));
    assert_eq!(swept, vec![idle.label.clone()]);
    assert_eq!(
        AppPreviewer::preview(env.apps.as_ref(), idle_run, "blog"),
        None
    );
    assert!(AppPreviewer::preview(env.apps.as_ref(), busy_run, "blog").is_some());
    env.apps
        .sweep_previews(Instant::now() + Duration::from_secs(61));
    assert_eq!(env.apps.preview_count(), 0);
    Ok(())
}

/// TODO 6b.5: `coding`'s `check` builds the application and mounts the green
/// build as the run's preview; the live mount keeps what the admin published.
#[tokio::test]
async fn a_green_check_mounts_the_runs_preview_and_leaves_the_live_mount() -> sc_error::Result<()> {
    use sc_agent::{RunCaller, RunMode, TraitContext};
    use serde_json::{Value as Json, json};

    let tmp = TempDir::new("check");
    let env = setup(&tmp, Duration::from_secs(3600)).await?;
    let registry = sc_core_traits::builtin_traits()?;
    let coding = registry.require("coding")?.clone();
    let config: sc_types::Attrs = [
        ("store", json!("apps")),
        ("root", json!("web")),
        ("may_check", json!(true)),
        ("checks", json!([])),
        ("application", json!("blog")),
    ]
    .into_iter()
    .map(|(k, v)| (k.to_owned(), v))
    .collect();

    write_bundler(tmp.path(), "agent-build");
    let run = RunId::new();
    let caller = RunCaller::system();
    let mut state = Json::Null;
    let previews: &dyn AppPreviewer = env.apps.as_ref();
    let mut ctx = TraitContext {
        catalog: &env.catalog,
        caller: &caller,
        agent: "builder",
        run,
        mode: RunMode::Act,
        trait_state: &mut state,
        evaluator: None,
        triggers: None,
        delegate: None,
        previews: Some(previews),
        browser: None,
        signals: Vec::new(),
        images: Vec::new(),
    };
    let report = coding
        .call(&config, "check_apps_web", &json!({}), &mut ctx)
        .await?;
    let report = report.as_str().unwrap_or_default().to_owned();
    assert!(report.starts_with("check: green"), "{report}");

    let preview = AppPreviewer::preview(env.apps.as_ref(), run, "blog").expect("mounted");
    assert!(
        report.contains(&format!(
            "preview: this build of `blog` is mounted for this run at {}",
            preview.host
        )),
        "{report}"
    );
    let token = env.login().await;
    env.apps.allow_preview_session(run, &token);
    let (_, body) = env.get(&preview.host, Some(&token)).await;
    assert_eq!(body, "<div id=root>agent-build</div>");
    let (_, body) = env.get(APP_HOST, None).await;
    assert_eq!(
        body, "<div id=root>live</div>",
        "publishing is still the admin's"
    );

    // A failed build leaves the preview as it was, and says nothing about it.
    std::fs::write(tmp.path().join("web/build.sh"), "#!/bin/sh\nexit 3\n").unwrap();
    let mut ctx = TraitContext {
        catalog: &env.catalog,
        caller: &caller,
        agent: "builder",
        run,
        mode: RunMode::Act,
        trait_state: &mut state,
        evaluator: None,
        triggers: None,
        delegate: None,
        previews: Some(previews),
        browser: None,
        signals: Vec::new(),
        images: Vec::new(),
    };
    let report = coding
        .call(&config, "check_apps_web", &json!({}), &mut ctx)
        .await?;
    let report = report.as_str().unwrap_or_default();
    assert!(report.starts_with("check: red"), "{report}");
    assert!(!report.contains("preview:"), "{report}");
    let (_, body) = env.get(&preview.host, Some(&token)).await;
    assert_eq!(body, "<div id=root>agent-build</div>");
    Ok(())
}
