//! `call_api`: a coding agent sends a request to its application through the
//! real router and sees the answer — as the person chatting, as another user,
//! or as nobody.
//!
//! The fixture's table is admin-only with an ownership formula, so which rows
//! come back says whose session the request carried: Alice gets her note, Bob
//! his, a visitor with no session an empty list. Asserted here:
//!
//! - the requester `serve` installs is the one a run reaches, and it answers
//!   through the router's providers, CSRF middleware included (a `POST` works);
//! - `user` picks the session, and naming someone else is an admin's alone;
//! - it is no grant: offered in every mode wherever there is an application;
//! - `plan` and `explore` only look, and a subdomain nothing is mounted at is refused;
//! - the per-request session is gone afterwards.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_agent::{RunCaller, RunId, RunMode, ToolsContext, TraitContext};
use sc_app::{
    ApiConfig, Application, CodeFramework, FrameworkRef, app_source_from_config, build_application,
    save_application,
};
use sc_auth::{ROLE_ADMIN, Role, SessionStore, User, create_user, save_role};
use sc_catalog::{Catalog, FileStoreId, TableId, TableMeta, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_files::LocalFileStore;
use sc_server::{
    AppMounts, MountedApp, ServerConfig, admin_handlers, default_js_evaluator, install_app_requests,
};
use sc_test_harness::TestDb;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

const BASE_DOMAIN: &str = "example.com";
const ALICE: &str = "alice@example.com";
const BOB: &str = "bob@example.com";
const TOOL: &str = "call_api_apps_web";

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> TempDir {
        let dir = std::env::temp_dir().join(format!(
            "sc-server-call-api-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir).unwrap();
        TempDir(dir)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// The app's source tree: a stand-in bundler that emits an SPA.
fn write_source(root: &Path) {
    std::fs::create_dir_all(root.join(".git")).unwrap();
    let web = root.join("web");
    std::fs::create_dir_all(web.join("src")).unwrap();
    std::fs::write(web.join("src/client.ts"), "export {};\n").unwrap();
    std::fs::write(
        web.join("build.sh"),
        "#!/bin/sh\nset -e\nmkdir -p dist\nprintf '<!doctype html><div id=root></div>' > \
         dist/index.html\n",
    )
    .unwrap();
}

fn framework() -> FrameworkRef {
    FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/client.ts")
}

fn notes_app() -> Application {
    Application::new("Notes", "notes", framework())
        .with_table(TableId("notes".to_owned()))
        .with_file_store(FileStoreId("apps".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"))
}

fn coding() -> Attrs {
    [
        ("store".to_owned(), json!("apps")),
        ("root".to_owned(), json!("web")),
        ("application".to_owned(), json!("notes")),
    ]
    .into_iter()
    .collect()
}

struct Env {
    catalog: Arc<Catalog>,
    agents: sc_server::AgentServices,
    admin: User,
    alice: User,
    _tmp: TempDir,
    db: TestDb,
}

async fn setup(tag: &str) -> Result<Env> {
    let tmp = TempDir::new(tag);
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; \
             CREATE TABLE notes (\
               id bigint generated by default as identity primary key, \
               title text not null, \
               owner text); \
             INSERT INTO notes (title, owner) VALUES \
               ('alice note', 'alice@example.com'), ('bob note', 'bob@example.com');",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    sc_catalog::bootstrap_table_meta(&catalog).await?;
    sc_catalog::bootstrap_field_meta(&catalog).await?;
    sc_catalog::bootstrap_file_stores(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    write_source(&tmp.0);
    catalog.connect_file_store(Arc::new(LocalFileStore::new("apps", &tmp.0)?))?;

    save_role(&catalog, &Role::new(80, "Member")).await?;
    let admin = create_user(&catalog, "admin@example.com", "admin-pw", ROLE_ADMIN).await?;
    let alice = create_user(&catalog, ALICE, "alice-pw", 80).await?;
    create_user(&catalog, BOB, "bob-pw", 80).await?;
    let mut meta = TableMeta::new("notes").access(1, 1);
    // Admin-only floors: the formula is the only way a member reads a row.
    meta.set_ownership_formula(Some("owner === user.email"));
    save_table_meta(&catalog, &meta).await?;
    save_application(&catalog, &notes_app()).await?;

    let agents = sc_server::install_agents(&catalog).await?;
    let evaluator = default_js_evaluator();
    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_evaluator(evaluator.clone())
            .with_agents(agents.clone())
            .with_base_domain(Some(BASE_DOMAIN.to_owned())),
    );
    let source = app_source_from_config(&framework())?;
    let report = build_application(&catalog, &notes_app(), &source, None).await?;
    let served = Arc::new(CodeFramework::new("code", report.bundle));
    apps.mount(MountedApp::new_with(
        notes_app(),
        served,
        &catalog,
        Some(evaluator),
        None,
    )?)?;

    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        ..ServerConfig::default()
    };
    install_app_requests(
        &config,
        &sc_api::admin_endpoints(),
        &admin_handlers(catalog.clone(), apps.clone()),
        &Arc::new(SessionStore::database(catalog.clone())),
        &apps,
    )?
    .expect("a base domain and agents, so the requester is installed");
    Ok(Env {
        catalog,
        agents,
        admin,
        alice,
        _tmp: tmp,
        db,
    })
}

impl Env {
    /// Call `call_api_apps_web` as `caller` in `mode`, with the requester the
    /// server installed, and return its text.
    async fn call(&self, caller: &RunCaller, mode: RunMode, args: Json) -> Result<String> {
        let registry = sc_core_traits::builtin_traits().unwrap();
        let coding_trait = registry.require("coding").unwrap().clone();
        let services = self.agents.registry().view_services();
        let requests = services.requests().expect("installed").as_ref();
        let mut state = Json::Null;
        let mut ctx = TraitContext {
            catalog: &self.catalog,
            caller,
            agent: "builder",
            run: RunId::new(),
            mode,
            trait_state: &mut state,
            evaluator: None,
            triggers: None,
            delegate: None,
            previews: None,
            browser: None,
            requests: Some(requests),
            signals: Vec::new(),
            images: Vec::new(),
        };
        coding_trait
            .call(&coding(), TOOL, &args, &mut ctx)
            .await
            .map(|j| j.as_str().unwrap_or_default().to_owned())
    }

    async fn sessions(&self) -> i64 {
        self.db
            .client()
            .await
            .unwrap()
            .query_one("SELECT count(*) FROM _fd_sessions", &[])
            .await
            .unwrap()
            .get(0)
    }
}

#[tokio::test]
async fn call_api_answers_as_the_user_it_names() -> Result<()> {
    let env = setup("as").await?;
    let alice = RunCaller::user(env.alice.clone());
    let admin = RunCaller::user(env.admin.clone());
    let sessions_before = env.sessions().await;

    // As the person chatting, by default: Alice's own row and nobody else's.
    let text = env
        .call(&alice, RunMode::Plan, json!({"path": "/api/notes"}))
        .await?;
    assert!(
        text.starts_with("GET /api/notes as alice@example.com → 200 OK\n"),
        "{text}"
    );
    assert!(text.contains("content-type: application/json"), "{text}");
    assert!(text.contains("alice note"), "{text}");
    assert!(!text.contains("bob note"), "{text}");
    // Naming herself is the same request.
    let named = env
        .call(
            &alice,
            RunMode::Plan,
            json!({"path": "/api/notes", "user": ALICE}),
        )
        .await?;
    assert!(named.contains("alice note"), "{named}");

    // As nobody: the anonymous answer, whoever is chatting.
    let public = env
        .call(
            &alice,
            RunMode::Plan,
            json!({"path": "/api/notes", "user": "public"}),
        )
        .await?;
    // The formula has no user to match, so no row is anybody's.
    assert!(
        public.starts_with("GET /api/notes as public → 200"),
        "{public}"
    );
    assert!(public.ends_with("body (2 bytes):\n[]"), "{public}");

    // Someone else is an admin's run only.
    let refused = env
        .call(
            &alice,
            RunMode::Plan,
            json!({"path": "/api/notes", "user": BOB}),
        )
        .await
        .unwrap_err()
        .to_string();
    assert!(refused.contains("only an administrator"), "{refused}");
    let as_bob = env
        .call(
            &admin,
            RunMode::Plan,
            json!({"path": "/api/notes", "user": BOB}),
        )
        .await?;
    assert!(as_bob.contains("as bob@example.com → 200"), "{as_bob}");
    assert!(as_bob.contains("bob note"), "{as_bob}");
    assert!(!as_bob.contains("alice note"), "{as_bob}");
    let nobody = env
        .call(
            &admin,
            RunMode::Plan,
            json!({"path": "/api/notes", "user": "carol@example.com"}),
        )
        .await
        .unwrap_err()
        .to_string();
    assert!(nobody.contains("no user has the email"), "{nobody}");

    // Every session a request made was ended after it.
    assert_eq!(env.sessions().await, sessions_before);
    Ok(())
}

#[tokio::test]
async fn call_api_writes_in_act_and_only_looks_in_plan() -> Result<()> {
    let env = setup("write").await?;
    let admin = RunCaller::user(env.admin.clone());
    let post = json!({
        "method": "POST",
        "path": "/api/notes",
        "body": {"title": "from the agent", "owner": "admin@example.com"},
    });

    // `plan` only looks.
    let refused = env
        .call(&admin, RunMode::Plan, post.clone())
        .await
        .unwrap_err()
        .to_string();
    assert!(refused.contains("only looks"), "{refused}");

    // `act` writes, through the CSRF middleware, with the JSON body labelled.
    let created = env.call(&admin, RunMode::Act, post).await?;
    assert!(
        created.starts_with("POST /api/notes as admin@example.com → 20"),
        "{created}"
    );
    let count: i64 = env
        .db
        .client()
        .await?
        .query_one(
            "SELECT count(*) FROM notes WHERE title = 'from the agent'",
            &[],
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?
        .get(0);
    assert_eq!(count, 1);

    // A path the API does not have is the application's own 404, not an error.
    let missing = env
        .call(&admin, RunMode::Plan, json!({"path": "/api/nope"}))
        .await?;
    assert!(missing.contains("→ 404"), "{missing}");
    Ok(())
}

#[tokio::test]
async fn call_api_needs_someone_to_send_as_and_a_served_application() -> Result<()> {
    let env = setup("refused").await?;

    // A triggered run with no `view_app_user` has no "you".
    let system = RunCaller::system();
    let err = env
        .call(&system, RunMode::Act, json!({"path": "/api/notes"}))
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("\"public\""), "{err}");
    // …but may send as a named user, being an admin's authority.
    let as_alice = env
        .call(
            &system,
            RunMode::Act,
            json!({"path": "/api/notes", "user": ALICE}),
        )
        .await?;
    assert!(as_alice.contains("alice note"), "{as_alice}");

    // An application nothing is mounted at is refused rather than reaching the
    // admin routes its host would otherwise fall through to.
    let registry = sc_core_traits::builtin_traits().unwrap();
    let coding_trait = registry.require("coding").unwrap().clone();
    let services = env.agents.registry().view_services();
    let requests = services.requests().unwrap().as_ref();
    let mut config = coding();
    config.insert("application".to_owned(), json!("elsewhere"));
    let alice = RunCaller::user(env.alice.clone());
    let mut state = Json::Null;
    let mut ctx = TraitContext {
        catalog: &env.catalog,
        caller: &alice,
        agent: "builder",
        run: RunId::new(),
        mode: RunMode::Act,
        trait_state: &mut state,
        evaluator: None,
        triggers: None,
        delegate: None,
        previews: None,
        browser: None,
        requests: Some(requests),
        signals: Vec::new(),
        images: Vec::new(),
    };
    let err = coding_trait
        .call(&config, TOOL, &json!({"path": "/api/notes"}), &mut ctx)
        .await
        .unwrap_err()
        .to_string();
    assert!(err.contains("no application is being served"), "{err}");
    Ok(())
}

/// Not a grant: every mode is offered the tool wherever the trait names an
/// application — `GET` only outside `act` — and a trait that names none is not.
#[tokio::test]
async fn call_api_is_offered_wherever_there_is_an_application() -> Result<()> {
    let env = setup("offered").await?;
    let registry = sc_core_traits::builtin_traits().unwrap();
    let coding_trait = registry.require("coding").unwrap().clone();
    let caps = sc_llm::ModelCapabilities::built_in("", "");
    let mut no_app = coding();
    no_app.remove("application");
    for mode in [RunMode::Explore, RunMode::Plan, RunMode::Act] {
        let cx = ToolsContext::new(&env.catalog, mode, &caps);
        let tools = coding_trait.tools(&cx, &coding());
        let tool = tools
            .iter()
            .find(|t| t.name == TOOL)
            .unwrap_or_else(|| panic!("offered in {mode} with no grant set"));
        let methods = tool.parameters["properties"]["method"]["enum"].to_string();
        assert_eq!(
            methods.contains("POST"),
            mode == RunMode::Act,
            "{mode}: {methods}"
        );
        assert!(
            !coding_trait
                .tools(&cx, &no_app)
                .iter()
                .any(|t| t.name == TOOL),
            "{mode}: nothing to send to"
        );
    }

    // An `explore` helper — where a planner sends a question — gets the answer…
    let alice = RunCaller::user(env.alice.clone());
    let text = env
        .call(
            &alice,
            RunMode::Explore,
            json!({"path": "/api/notes", "user": "public"}),
        )
        .await?;
    assert!(text.starts_with("GET /api/notes as public → 200"), "{text}");
    // …and may not write.
    let refused = env
        .call(
            &alice,
            RunMode::Explore,
            json!({"method": "DELETE", "path": "/api/notes/1"}),
        )
        .await
        .unwrap_err()
        .to_string();
    assert!(refused.contains("only looks"), "{refused}");
    Ok(())
}
