//! Tables in a code body, through the admin's **Run** button (the milestone
//! "Tables in code", phase 5).
//!
//! The milestone's definition of done is a claim about the whole stack at once:
//! an admin writes a `run_js_code` body that reads, joins, aggregates and writes,
//! presses Run, and **the rows are there**. Every layer under that is tested on
//! its own — `sc-expr` proves a chain becomes a plan, `sc-api` proves a plan
//! becomes a statement and a statement answers, `sc-core-actions` proves the
//! action binds `db` and delegates to the event's caller — and none of them
//! proves the button. So this file drives the assembled router: create the
//! trigger over HTTP, run it over HTTP, and read the written rows back over HTTP,
//! with the JSON the SPA would send and the JSON it would show.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// Customers, their invoices and the reminders a body writes — the milestone's
/// own example, as tables. Two invoices are overdue on the day the trigger is run
/// with, one is not yet due, and one is paid: enough for the `where` to be doing
/// something and for the totals to be checkable by hand.
const SCHEMA: &str = "\
    CREATE TABLE customers (id bigint generated by default as identity primary key, \
        email text not null, name text); \
    CREATE TABLE invoices (id bigint generated by default as identity primary key, \
        amount bigint, due date, paid boolean, customer bigint references customers(id)); \
    CREATE TABLE reminders (id bigint generated by default as identity primary key, \
        invoice bigint references invoices(id), sent_to text); \
    INSERT INTO customers (email, name) VALUES \
        ('ada@example.com', 'Ada'), ('bob@example.com', 'Bob'); \
    INSERT INTO invoices (amount, due, paid, customer) VALUES \
        (100, '2026-08-01', false, 1), \
        (250, '2026-07-15', false, 2), \
        (500, '2026-09-30', false, 1), \
        (75,  '2026-06-01', true,  2);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// The milestone's definition-of-done body, verbatim.
const CHASE: &str = r#"
const overdue = await db.invoices
  .where({ paid: false, due: { lt: payload.today } })
  .select("id", "amount", "customerⱵemail", { chased: "remindersↃinvoice.length" })
  .orderBy("due")
  .limit(50)
  .rows();

for (const inv of overdue) {
  await db.reminders.insert({ invoice: inv.id, sent_to: inv.customerⱵemail });
}
return {
  chased: overdue.length,
  owed: await db.invoices.where({ paid: false }).sum("amount"),
};
"#;

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    /// Create a `none` trigger running `code`, and answer its id.
    async fn code_trigger(&mut self, name: &str, code: &str) -> String {
        let (status, created) = self
            .send(
                "POST",
                "/api/triggers",
                Some(json!({
                    "name": name,
                    "description": "",
                    "when": "none",
                    "channel": Value::Null,
                    "only_if": Value::Null,
                    "action": "run_js_code",
                    "configuration": { "code": code },
                    "min_role": Value::Null,
                    "enabled": true,
                })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{created}");
        created["id"].as_str().unwrap().to_owned()
    }

    async fn rows(&mut self, table: &str) -> Vec<Value> {
        let (status, body) = self
            .send("GET", &format!("/api/tables/{table}/rows"), None)
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }
}

struct Server {
    client: Client,
    _db: TestDb,
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents).await?;

    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(sc_auth::SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server { client, _db: db })
}

#[tokio::test]
async fn the_run_button_reads_joins_aggregates_and_writes() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let id = server.client.code_trigger("chase", CHASE).await;

    // Press Run, with the payload the form posts.
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(json!({ "today": "2026-08-17" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(
        body["result"],
        // Two invoices are overdue; the money owed is every unpaid one, as an
        // exact decimal rather than a float that might not be.
        json!({ "chased": 2, "owed": "850" }),
        "{body}"
    );

    // And the rows are there — read back the way the admin would see them, not
    // out of the action's own answer.
    let reminders = server.client.rows("reminders").await;
    let sent: Vec<(&str, i64)> = reminders
        .iter()
        .map(|r| {
            (
                r["sent_to"].as_str().unwrap_or_default(),
                r["invoice"].as_i64().unwrap_or_default(),
            )
        })
        .collect();
    assert_eq!(
        sent,
        // Ordered by `due`, so bob's July invoice was chased before ada's
        // August one: the `orderBy` in the read decided the order of the writes.
        vec![("bob@example.com", 2), ("ada@example.com", 1)],
        "{reminders:?}"
    );

    // Run it again and the same two are chased — and the join projection the
    // body asked for (`remindersↃinvoice.length`) now counts what the first run
    // wrote, which is the one assertion that the child aggregation is really a
    // read of the database and not a constant.
    let already = server
        .client
        .code_trigger(
            "count_chased",
            r#"const rows = await db.invoices
                 .where({ paid: false })
                 .select("id", { chased: "remindersↃinvoice.length" })
                 .orderBy("id")
                 .rows();
               return rows.map((i) => i.chased);"#,
        )
        .await;
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{already}/run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["result"], json!([1, 1, 0]), "{body}");
    Ok(())
}

#[tokio::test]
async fn the_run_button_groups_and_answers_a_row_per_group() -> sc_error::Result<()> {
    let mut server = setup().await?;
    // "Who owes for more than one invoice, and how much?" — one statement, one
    // round trip, and the group key is a Ⱶ-path so the answer names the customer
    // rather than their id.
    let id = server
        .client
        .code_trigger(
            "owing",
            r#"return await db.invoices
                 .where({ paid: false })
                 .groupBy("customerⱵemail")
                 .aggregate({ n: "count()", owed: "sum(amount)" })
                 .having({ n: { gt: 1 } })
                 .orderBy("owed", "desc")
                 .rows();"#,
        )
        .await;
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(
        body["result"],
        // Ada has two unpaid invoices totalling 600 — exact, as a decimal
        // crosses this seam everywhere else. Bob has one, so `.having()` left
        // him out.
        json!([{ "customerⱵemail": "ada@example.com", "n": 2, "owed": "600" }]),
        "{body}"
    );

    // The scalar terminals still answer a value rather than a row per group, and
    // a `.groupBy()` with nothing to compute is refused in the body itself.
    let id = server
        .client
        .code_trigger(
            "owed_total",
            r#"try {
                 await db.invoices.groupBy("customer").count();
               } catch (e) {
                 return {
                   refused: e.message,
                   total: await db.invoices.where({ paid: false }).sum("amount"),
                 };
               }
               return null;"#,
        )
        .await;
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(Value::Null),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["result"]["total"], json!("850"), "{body}");
    assert!(
        body["result"]["refused"]
            .as_str()
            .unwrap_or_default()
            .contains("answers one value"),
        "{body}"
    );
    Ok(())
}

#[tokio::test]
async fn a_plan_the_catalog_refuses_comes_back_as_a_message_the_admin_can_act_on()
-> sc_error::Result<()> {
    let mut server = setup().await?;

    // A table that is not there, a column that is not on it, and a whole-table
    // update: three mistakes an admin makes while writing a body, each of which
    // must come back from the button as its own sentence rather than as "500".
    for (code, expected) in [
        ("return await db.nope.rows();", "nope"),
        (
            "return await db.invoices.select(\"colour\").rows();",
            "colour",
        ),
        (
            "return await db.invoices.update({ paid: true });",
            ".where()",
        ),
    ] {
        let id = server
            .client
            .code_trigger(&format!("t{}", expected.len()), code)
            .await;
        let (status, body) = server
            .client
            .send(
                "POST",
                &format!("/api/triggers/{id}/run"),
                Some(Value::Null),
            )
            .await;
        assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");
        let message = body["error"].as_str().unwrap_or_default();
        assert!(message.contains(expected), "{message}");
    }

    // Nothing was written by the refused update.
    let (status, invoices) = server
        .client
        .send("GET", "/api/tables/invoices/rows", None)
        .await;
    assert_eq!(status, StatusCode::OK, "{invoices}");
    assert_eq!(
        invoices
            .as_array()
            .unwrap()
            .iter()
            .filter(|i| i["paid"] == json!(true))
            .count(),
        1,
        "the unfiltered update touched rows: {invoices}"
    );
    Ok(())
}
