//! The milestone's definition of done: **500 concurrent `run_js_code` fires**,
//! on the default pool, all served and none timing out.
//!
//! Every layer under this has its own proof — `sc-expr` shows one isolate
//! holding hundreds of runs against a fake host, and that the wall clock of two
//! hundred runs is one round trip's rather than two hundred — but none of them
//! is the claim the milestone makes. That claim is about the assembled server:
//! five hundred HTTP requests arrive at once, each fires a trigger whose body
//! reads and writes through the real catalog and the real database, and every
//! one of them is answered inside its own five-second wall clock.
//!
//! Before this milestone the same test could not have passed at any pool size a
//! person would pick: a host call blocked its isolate's thread for the whole
//! round trip, so the number of bodies this server could serve at once was the
//! number of isolates. Two. The other 498 waited for a thread and died at the
//! clock. What is asserted here is therefore not throughput but **arithmetic**:
//! 500 > 2, and every one of the 500 was served anyway.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// How many fires go out at once. The number in the milestone's definition of
/// done, and comfortably more than the pool's 2 isolates — which is the whole
/// point of it.
const FIRES: usize = 500;

/// One table, written by every run and read by every run. Nothing about the
/// schema is interesting; what is interesting is that both halves of the body
/// are real database round trips through the row layer.
const SCHEMA: &str = "\
    CREATE TABLE notes (id bigint generated by default as identity primary key, \
        n bigint, seen bigint);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// A body that reads *and* writes, because a read-only body would exercise half
/// the seam. Each fire carries its own `n`, so what the read answers is decided
/// by that fire alone and cannot be an accident of the order they ran in.
const NOTE: &str = r#"
const mine = await db.notes.where({ n: payload.n }).count();
await db.notes.insert({ n: payload.n, seen: mine });
return { n: payload.n, mine };
"#;

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let (status, value, set) = send_with(&self.router, &self.cookies, method, path, body).await;
        self.cookies.extend(set);
        (status, value)
    }

    /// Create a `none` trigger running `code`, and answer its id.
    async fn code_trigger(&mut self, name: &str, code: &str) -> String {
        let (status, created) = self
            .send(
                "POST",
                "/api/triggers",
                Some(json!({
                    "name": name,
                    "description": "",
                    "when": "none",
                    "channel": Value::Null,
                    "only_if": Value::Null,
                    "action": "run_js_code",
                    "configuration": { "code": code },
                    "min_role": Value::Null,
                    "enabled": true,
                })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{created}");
        created["id"].as_str().unwrap().to_owned()
    }
}

/// One request, against a borrowed cookie jar rather than a `&mut` one — which
/// is what lets five hundred of them be in flight at once over one session.
async fn send_with(
    router: &Router,
    cookies: &HashMap<String, String>,
    method: &str,
    path: &str,
    body: Option<Value>,
) -> (StatusCode, Value, HashMap<String, String>) {
    let mut builder = Request::builder().method(method).uri(path);
    if !cookies.is_empty() {
        let jar = cookies
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join("; ");
        builder = builder.header(header::COOKIE, jar);
    }
    if method != "GET"
        && let Some(csrf) = cookies.get(CSRF_COOKIE)
    {
        builder = builder.header(CSRF_HEADER, csrf);
    }
    let request = match body {
        Some(ref b) => builder
            .header(header::CONTENT_TYPE, "application/json")
            .body(Body::from(serde_json::to_vec(b).unwrap()))
            .unwrap(),
        None => builder.body(Body::empty()).unwrap(),
    };
    let response = router.clone().oneshot(request).await.unwrap();
    let status = response.status();
    let mut set = HashMap::new();
    for raw in response.headers().get_all(header::SET_COOKIE) {
        if let Ok(text) = raw.to_str()
            && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
        {
            set.insert(name.to_owned(), value.to_owned());
        }
    }
    let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
        .await
        .unwrap();
    let value = if bytes.is_empty() {
        Value::Null
    } else {
        serde_json::from_slice(&bytes).unwrap_or(Value::Null)
    };
    (status, value, set)
}

struct Server {
    client: Client,
    _db: TestDb,
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    // The **default** evaluator, deliberately: the claim is about the pool an
    // operator gets without configuring anything (2 isolates, 256 resident runs
    // each), not about a pool sized for this test.
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents).await?;

    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(sc_auth::SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server { client, _db: db })
}

#[tokio::test(flavor = "multi_thread")]
async fn five_hundred_concurrent_fires_are_all_served() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let id = server.client.code_trigger("note", NOTE).await;

    // Warm the trigger once, so the failure of a *first* run — a table the
    // catalog has not seen, a body not yet compiled — is not mistaken for a
    // failure of concurrency.
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(json!({ "n": 0 })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    let router = server.client.router.clone();
    let cookies = Arc::new(server.client.cookies.clone());
    let started = std::time::Instant::now();
    let mut fires = Vec::with_capacity(FIRES);
    for n in 1..=FIRES {
        let (router, cookies, path) = (
            router.clone(),
            Arc::clone(&cookies),
            format!("/api/triggers/{id}/run"),
        );
        fires.push(tokio::spawn(async move {
            let (status, body, _) =
                send_with(&router, &cookies, "POST", &path, Some(json!({ "n": n }))).await;
            (n, status, body)
        }));
    }

    // Every one of them answered, with the answer its own `n` decides: no run
    // read another's payload, and each saw only its own row missing.
    for fire in fires {
        let (n, status, body) = fire.await.unwrap();
        assert_eq!(status, StatusCode::OK, "fire {n} was not served: {body}");
        assert_eq!(body["result"], json!({ "n": n, "mine": 0 }), "fire {n}");
    }
    let elapsed = started.elapsed();

    // The rows are there — 500 fires wrote 500 rows, one each, so nothing was
    // served twice either. (501 with the warm-up's.)
    let (status, rows) = server
        .client
        .send("GET", "/api/tables/notes/rows", None)
        .await;
    assert_eq!(status, StatusCode::OK, "{rows}");
    let mut ns: Vec<i64> = rows
        .as_array()
        .unwrap()
        .iter()
        .map(|r| r["n"].as_i64().unwrap())
        .collect();
    ns.sort_unstable();
    assert_eq!(
        ns,
        (0..=FIRES as i64).collect::<Vec<_>>(),
        "{} rows",
        ns.len()
    );

    // That none of them timed out is the assertion above and not this one: a
    // run's five-second wall clock is running while it queues, so 500 runs
    // serialised two at a time would have been answered with the clock rather
    // than with a result. This is only a guard against the whole thing being
    // slow in some way the per-run clock cannot see — deliberately loose,
    // because a debug build against a real database on an unknown machine is
    // not a benchmark.
    assert!(
        elapsed < std::time::Duration::from_secs(60),
        "500 fires took {elapsed:?}"
    );
    Ok(())
}
