//! Phase 10 "live mounting" integration test: applications are mounted, edited,
//! rebuilt and unmounted **against a running server, with no restart** (design
//! §13.2 "the mount registry is live; a full restart should never be required").
//!
//! The router is built **once** with an empty, shared [`AppMounts`] handle and is
//! never rebuilt. Everything else — an app appearing on its subdomain, a rebuild
//! changing what it serves, a failed rebuild leaving the old bundle up, an
//! unmount making the subdomain stop resolving — happens by mutating that live
//! handle while the same `router` answers every request.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_app::{
    ApiConfig, Application, FrameworkRef, bootstrap, delete_application, save_application,
};
use sc_auth::SessionStore;
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_server::{
    AppMounts, ServerConfig, admin_handlers, build_and_mount, build_router_with_apps, mount_all,
    reload_all,
};
use sc_test_harness::TestDb;
use tower::ServiceExt;

const BASE_DOMAIN: &str = "example.com";
const APP_HOST: &str = "blog.example.com";

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> TempDir {
        let dir = std::env::temp_dir().join(format!(
            "sc-server-live-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir).unwrap();
        TempDir(dir)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// Install a bundler that stamps `marker` into the served `index.html`, so a
/// later rebuild with a different marker proves the *new* bundle is being served.
/// When `succeed` is false the bundler exits non-zero with a bundler-style
/// diagnostic instead, to exercise the failed-rebuild path.
fn write_bundler(root: &Path, marker: &str, succeed: bool) {
    let web = root.join("web");
    std::fs::create_dir_all(web.join("src")).unwrap();
    // The client import must resolve for the real build path (emit_client) to
    // have somewhere to land; the bundler just copies it through.
    let script = if succeed {
        format!(
            "#!/bin/sh\n\
             set -e\n\
             mkdir -p dist/assets\n\
             printf '<!doctype html><div id=root>{marker}</div>' > dist/index.html\n\
             printf 'console.log(1)' > dist/assets/app.js\n"
        )
    } else {
        "#!/bin/sh\n\
         echo 'TS2304: Cannot find name TypeError' >&2\n\
         exit 2\n"
            .to_owned()
    };
    let path = web.join("build.sh");
    std::fs::write(&path, script).unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).unwrap();
    }
}

fn code_framework() -> FrameworkRef {
    FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/client.ts")
}

fn blog_app() -> Application {
    Application::new("Blog", "blog", code_framework())
        .with_table(TableId("posts".to_owned()))
        .with_file_store(FileStoreId("apps".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"))
}

/// Bring up a catalog with the applications + posts tables and an `apps` file
/// store rooted at `tmp`, plus the assembled router over a *shared, empty*
/// [`AppMounts`]. The returned handle is what the test mutates live.
async fn setup(tmp: &TempDir) -> sc_error::Result<(Arc<AppMounts>, Router, Arc<Catalog>, TestDb)> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    bootstrap(&catalog).await?;
    catalog.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // The live registry: empty now, mutated at runtime. The router closes over
    // this exact handle, so a later mount serves without a rebuild.
    let apps = Arc::new(AppMounts::new(catalog.clone()));
    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        // How an Android emulator reaches this machine.
        extra_base_domains: vec!["10.0.2.2.nip.io".to_owned()],
        ..ServerConfig::default()
    };
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &config,
        apps.clone(),
    )?;
    Ok((apps, router, catalog, db))
}

/// GET `path` on `host` and return the status and body bytes.
async fn get(router: &Router, host: &str, path: &str) -> (StatusCode, Vec<u8>) {
    let request = Request::builder()
        .method("GET")
        .uri(path)
        .header(header::HOST, host)
        .body(Body::empty())
        .unwrap();
    let response = router.clone().oneshot(request).await.unwrap();
    let status = response.status();
    let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
        .await
        .unwrap();
    (status, bytes.to_vec())
}

#[tokio::test]
async fn an_app_is_created_edited_and_deleted_without_a_restart() -> sc_error::Result<()> {
    let tmp = TempDir::new("lifecycle");
    let (apps, router, catalog, _db) = setup(&tmp).await?;
    // One stable app instance (a fresh `blog_app()` would mint a new id each call).
    let app = blog_app();

    // --- before it is mounted, the subdomain is not an app --------------------
    // `/` on the blog host reaches the admin's bootstrap document, not an app.
    let (status, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, sc_server::BOOTSTRAP_HTML.as_bytes());

    // --- create: build + mount at runtime -------------------------------------
    write_bundler(tmp.path(), "v1", true);
    save_application(&catalog, &app).await?;
    build_and_mount(&apps, app.clone()).await?;

    // The very same router now serves the app on its subdomain — no rebuild.
    let (status, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, b"<!doctype html><div id=root>v1</div>");
    // …and on every extra base domain, which is the same app under another
    // name: the emulator's `blog.10.0.2.2.nip.io` is not a second mount.
    let (status, body) = get(&router, "blog.10.0.2.2.nip.io:3032", "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, b"<!doctype html><div id=root>v1</div>");

    // --- edit: rebuild re-mounts the new bundle -------------------------------
    write_bundler(tmp.path(), "v2", true);
    build_and_mount(&apps, app.clone()).await?;
    let (_, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(
        body, b"<!doctype html><div id=root>v2</div>",
        "the rebuild should be what is served"
    );

    // --- a failed rebuild keeps the old bundle up -----------------------------
    write_bundler(tmp.path(), "v3", false);
    let err = build_and_mount(&apps, app.clone())
        .await
        .expect_err("a failing build must be reported, not swallowed");
    // The bundler's own diagnostics reach the caller (§16).
    assert!(
        err.to_string()
            .contains("TS2304: Cannot find name TypeError"),
        "the bundler's diagnostics should surface: {err}"
    );
    // ...and the previously mounted v2 is still serving.
    let (status, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        body, b"<!doctype html><div id=root>v2</div>",
        "a failed rebuild must leave the previous version serving"
    );

    // --- delete: unmount + drop the row; the subdomain stops resolving --------
    assert!(apps.unmount("blog"), "the app was mounted");
    assert!(
        delete_application(&catalog, app.id).await?,
        "the saved row should be deleted"
    );
    let (status, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        body,
        sc_server::BOOTSTRAP_HTML.as_bytes(),
        "an unmounted subdomain falls back to the admin"
    );
    Ok(())
}

/// `SIGHUP`'s reload: the bundle a developer (or a coding agent) built by hand is
/// what the server serves, and the definitions around it are re-read too — with
/// no bundler run and no restart.
#[tokio::test]
async fn a_reload_serves_what_was_built_on_disk_without_building_anything() -> sc_error::Result<()>
{
    let tmp = TempDir::new("reload");
    let (apps, router, catalog, db) = setup(&tmp).await?;
    let app = blog_app();

    write_bundler(tmp.path(), "v1", true);
    save_application(&catalog, &app).await?;
    build_and_mount(&apps, app.clone()).await?;
    let (_, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(body, b"<!doctype html><div id=root>v1</div>");

    // --- what `npm run build` in the project directory does --------------------
    // The bundler writes `dist/` and nothing else; the server is unaware.
    let dist = tmp.path().join("web/dist");
    std::fs::write(
        dist.join("index.html"),
        "<!doctype html><div id=root>by-hand</div>",
    )
    .unwrap();
    let (_, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(
        body, b"<!doctype html><div id=root>v1</div>",
        "the served bundle is a snapshot, so a build on disk is invisible until a reload"
    );

    // A schema change and an application edit made from *another* process, which
    // the running server likewise cannot see: its catalog was introspected at
    // boot and its mount was built from the row as it was.
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE comments (\
               id bigint generated by default as identity primary key, \
               body text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let edited = app.clone().with_table(TableId("comments".to_owned()));
    save_application(&catalog, &edited).await?;

    // Any build now fails, which is how this test proves a reload runs none: if
    // it invoked the bundler the reload would fail and `v1` would still be up.
    write_bundler(tmp.path(), "unreachable", false);

    // --- the reload ------------------------------------------------------------
    let report = reload_all(&apps).await;
    assert!(
        report.is_ok(),
        "the reload should have nothing to report: {report:?}"
    );
    assert_eq!(report.reloaded, vec!["blog".to_owned()]);
    assert_eq!(report.assets, 2, "index.html and assets/app.js");
    assert!(report.unmounted.is_empty());

    // The serving cache is vacated: the bytes on disk are the bytes served.
    let (status, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        body, b"<!doctype html><div id=root>by-hand</div>",
        "the hand-built bundle should be what is served after a reload"
    );

    // The catalog is reloaded: the table created by another process is there.
    assert!(
        catalog.get("comments")?.is_some(),
        "the reload should have re-introspected the database"
    );

    // ...and so are the application definitions, and the API definitions with
    // them: the app now declares `comments`, so its REST provider projects it.
    let mounted = apps.get("blog").expect("blog is mounted");
    assert!(
        mounted.app.tables.contains(&TableId("comments".to_owned())),
        "the stored row should have been re-read"
    );
    let provider = mounted
        .provider_for("/api")
        .expect("the REST API is mounted");
    assert!(
        provider.endpoints().find("listComments").is_some(),
        "the reloaded providers should serve the newly declared table"
    );

    // Timing is reported, and it is the number the caller is waiting on.
    assert!(report.total >= report.catalog, "{report:?}");

    // --- a row deleted elsewhere is unmounted by the reload --------------------
    delete_application(&catalog, app.id).await?;
    let report = reload_all(&apps).await;
    assert_eq!(report.unmounted, vec!["blog".to_owned()]);
    assert!(report.reloaded.is_empty());
    let (_, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(
        body,
        sc_server::BOOTSTRAP_HTML.as_bytes(),
        "an app whose row is gone should stop resolving"
    );
    Ok(())
}

/// An application that has never been built has nothing to reload — and says so
/// without disturbing the app beside it, which keeps serving.
#[tokio::test]
async fn an_unbuilt_app_fails_its_reload_alone() -> sc_error::Result<()> {
    let tmp = TempDir::new("reload-unbuilt");
    let (apps, router, catalog, _db) = setup(&tmp).await?;

    write_bundler(tmp.path(), "good", true);
    let good = blog_app();
    save_application(&catalog, &good).await?;
    build_and_mount(&apps, good).await?;

    // A second app whose store has no build output at all.
    let never = tmp.path().join("never-built");
    std::fs::create_dir_all(never.join("web")).unwrap();
    catalog.connect_file_store(Arc::new(LocalFileStore::new("never", &never)?))?;
    save_application(
        &catalog,
        &Application::new(
            "Never",
            "never",
            FrameworkRef::new("code")
                .with("store", "never")
                .with("source", "web")
                .with("output", "web/dist")
                .with("command", "sh build.sh"),
        ),
    )
    .await?;

    let report = reload_all(&apps).await;
    assert_eq!(report.reloaded, vec!["blog".to_owned()]);
    assert_eq!(report.failed.len(), 1, "{report:?}");
    assert_eq!(report.failed[0].0, "never");
    assert!(
        report.failed[0].1.contains("build the application first"),
        "the reason should say what to do: {}",
        report.failed[0].1
    );
    // The app that did reload is serving, which is the whole point of reporting
    // rather than returning an error.
    let (_, body) = get(&router, APP_HOST, "/").await;
    assert_eq!(body, b"<!doctype html><div id=root>good</div>");
    Ok(())
}

#[tokio::test]
async fn boot_mounts_every_stored_app_and_a_failing_one_does_not_stop_the_others()
-> sc_error::Result<()> {
    let tmp = TempDir::new("boot");
    let (apps, router, catalog, _db) = setup(&tmp).await?;

    // One good app whose bundler succeeds...
    write_bundler(tmp.path(), "good", true);
    save_application(&catalog, &blog_app()).await?;

    // ...and a second app in a *separate* store whose bundler will fail.
    let broken_dir = tmp.path().join("broken-store");
    std::fs::create_dir_all(&broken_dir).unwrap();
    catalog.connect_file_store(Arc::new(LocalFileStore::new("broken", &broken_dir)?))?;
    write_bundler(&broken_dir, "irrelevant", false);
    let broken = Application::new(
        "Broken",
        "broken",
        FrameworkRef::new("code")
            .with("store", "broken")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh"),
    );
    save_application(&catalog, &broken).await?;

    // Boot mounts everything it can; the broken app is logged and skipped, not
    // fatal, so the good app comes up regardless.
    mount_all(&apps).await;

    let (status, body) = get(&router, "blog.example.com", "/").await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body, b"<!doctype html><div id=root>good</div>");

    // The broken app never mounted, so its subdomain is not an app.
    let (_, body) = get(&router, "broken.example.com", "/").await;
    assert_eq!(body, sc_server::BOOTSTRAP_HTML.as_bytes());

    // A subsequent successful build mounts the previously-broken app live.
    write_bundler(&broken_dir, "fixed", true);
    build_and_mount(&apps, broken).await?;
    let (_, body) = get(&router, "broken.example.com", "/").await;
    assert_eq!(body, b"<!doctype html><div id=root>fixed</div>");
    Ok(())
}
