//! Phase 5 end-to-end: the events that are not a row write — `login`, `startup`,
//! `error`, and the `none` trigger that runs because something asked it to
//! (§10.2, §16).
//!
//! Each is asserted where it actually happens. A login is fired from the one
//! place a session starts, so it is provoked by signing in through the router; an
//! error is fired where an `Error` becomes a response, so it is provoked by two
//! genuinely broken requests — one the caller got wrong, one the server did —
//! and *not* by a rejection, which is a distinction an alerting trigger lives or
//! dies by. `startup` is fired by the boot path, so the test calls the boot path.
//!
//! The `error` event's re-entrancy guard has its own test in `sc-action`
//! (`error_reentrancy.rs`), where an action can raise an error event from inside
//! one; what is asserted here is the consequence an operator sees: a throwing
//! error trigger costs itself and nothing else.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_action::{EventKind, Trigger, TriggerDispatcher, save_trigger};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, fire_startup, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// One table for the triggers to write into, and one to fail a write against.
const SCHEMA: &str = "\
    CREATE TABLE journal (id bigint generated by default as identity primary key, \
        what text, detail text, who text, route text); \
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text not null, pages bigint);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    async fn journal(&mut self) -> Vec<Value> {
        let (status, body) = self.send("GET", "/api/tables/journal/rows", None).await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }
}

struct Server {
    client: Client,
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    _db: TestDb,
}

impl Server {
    async fn add_trigger(&self, trigger: Trigger) -> sc_error::Result<()> {
        save_trigger(&self.catalog, self.dispatcher.registry(), &trigger).await?;
        self.dispatcher.reload(&self.catalog).await
    }
}

/// A trigger writing one `journal` row from the event.
fn journal_trigger(name: &str, when: EventKind, values: Value) -> Trigger {
    Trigger::new(name, when, "insert_row")
        .config("table", "journal")
        .config("values", values)
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let dispatcher = install_triggers(&catalog, default_js_evaluator()).await?;

    // The dispatcher rides on the mount registry, which is the handle the router
    // and the admin handlers both already hold — so a login or an error raised by
    // either reaches the same triggers.
    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    // `build_router_with_apps`, not `build_router`: the mount registry is what
    // carries the dispatcher to the router, and `build_router` builds its own
    // empty one. This is the assembly `saltcorn serve` performs.
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server {
        client,
        catalog,
        dispatcher,
        _db: db,
    })
}

#[tokio::test]
async fn a_login_trigger_records_who_signed_in() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(journal_trigger(
            "record_login",
            EventKind::Login,
            json!({ "what": "\"login\"", "who": "user.email", "detail": "user.role" }),
        ))
        .await?;

    let (status, body) = server
        .client
        .send(
            "POST",
            "/api/login",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    let journal = server.client.journal().await;
    assert_eq!(journal.len(), 1, "{journal:?}");
    assert_eq!(journal[0]["what"], json!("login"));
    // The user object is the one every other caller gets, so `user.email` means
    // here what it means in an insert trigger.
    assert_eq!(journal[0]["who"], json!(ADMIN));
    assert_eq!(journal[0]["detail"], json!("1"));

    // A *failed* login is not a login: the credentials are rejected and nothing
    // is recorded.
    let (status, _) = server
        .client
        .send(
            "POST",
            "/api/login",
            Some(json!({ "email": ADMIN, "password": "wrong-password" })),
        )
        .await;
    assert_eq!(status, StatusCode::UNAUTHORIZED);
    assert_eq!(server.client.journal().await.len(), 1);
    Ok(())
}

#[tokio::test]
async fn a_startup_trigger_runs_when_the_server_comes_up() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(journal_trigger(
            "on_boot",
            EventKind::Startup,
            json!({ "what": "\"startup\"" }),
        ))
        .await?;

    // Nothing has started up yet in this process, so nothing has fired: the event
    // is raised by the boot path, not by the trigger existing.
    assert!(server.client.journal().await.is_empty());

    // The boot path, which `saltcorn serve` runs once the catalog, the file
    // stores, the applications and the triggers are all up.
    fire_startup(&server.catalog, &server.dispatcher).await;

    let journal = server.client.journal().await;
    assert_eq!(journal.len(), 1, "{journal:?}");
    assert_eq!(journal[0]["what"], json!("startup"));
    // A startup event has no caller — nobody did this, the server did.
    assert_eq!(journal[0]["who"], Value::Null);
    Ok(())
}

#[tokio::test]
async fn an_error_trigger_sees_both_error_kinds_and_no_rejections() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(journal_trigger(
            "on_error",
            EventKind::Error,
            json!({
                "what": "payload.kind",
                "detail": "payload.message",
                "route": "payload.path",
                "who": "user.email",
            }),
        ))
        .await?;

    // An application error: the caller asked for a table that is not there.
    let (status, _) = server
        .client
        .send("GET", "/api/tables/nope/rows", None)
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    // A system error: the write is well-formed as far as the API is concerned and
    // the database refuses it (`title` is NOT NULL). This is the class an
    // alerting trigger actually wants, which is why the two are distinguished.
    let (status, _) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "pages": 100 })),
        )
        .await;
    assert_eq!(status, StatusCode::INTERNAL_SERVER_ERROR);

    let journal = server.client.journal().await;
    let kinds: Vec<&str> = journal.iter().filter_map(|r| r["what"].as_str()).collect();
    assert_eq!(kinds, vec!["application", "system"], "{journal:?}");
    assert_eq!(journal[0]["route"], json!("/api/tables/nope/rows"));
    assert!(
        journal[0]["detail"]
            .as_str()
            .is_some_and(|d| d.contains("nope")),
        "{journal:?}"
    );
    assert_eq!(journal[0]["who"], json!(ADMIN), "the caller travels");
    assert_eq!(journal[1]["route"], json!("/api/tables/books/rows"));

    // A **rejection** is not a failure: an unauthenticated request is turned away
    // by the auth gate, not by an `Error` becoming a response. Firing an alerting
    // trigger for every probe of a protected URL would make the event useless for
    // what it is for.
    let mut stranger = Client {
        router: server.client.router.clone(),
        cookies: HashMap::new(),
    };
    let (status, _) = stranger.send("GET", "/api/tables/nope/rows", None).await;
    assert_eq!(status, StatusCode::UNAUTHORIZED);
    assert_eq!(server.client.journal().await.len(), 2, "no third row");
    Ok(())
}

#[tokio::test]
async fn a_throwing_error_trigger_costs_itself_and_nothing_else() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(
            Trigger::new("boom", EventKind::Error, "run_js_code")
                .config("code", "throw new Error('the alerting webhook is down');"),
        )
        .await?;
    server
        .add_trigger(journal_trigger(
            "record",
            EventKind::Error,
            json!({ "what": "payload.kind", "detail": "payload.message" }),
        ))
        .await?;

    let (status, body) = server
        .client
        .send("GET", "/api/tables/nope/rows", None)
        .await;
    // The caller still gets the error they caused — not the trigger's, and not a
    // different status because a trigger failed.
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert!(
        body["error"].as_str().is_some_and(|e| e.contains("nope")),
        "{body}"
    );

    // Exactly one journal row: the throwing trigger did not stop the recording
    // one, and its own failure did not raise a second error event (the guard —
    // asserted directly in `sc-action`'s `error_reentrancy.rs`).
    let journal = server.client.journal().await;
    assert_eq!(journal.len(), 1, "{journal:?}");
    assert_eq!(journal[0]["what"], json!("application"));
    Ok(())
}

#[tokio::test]
async fn a_none_trigger_runs_by_name_with_its_payload() -> sc_error::Result<()> {
    let server = setup().await?;
    server
        .add_trigger(
            Trigger::new("double", EventKind::None, "run_js_code")
                .config("code", "return { doubled: payload.n * 2, who: user };"),
        )
        .await?;

    // The posted body becomes the event's payload and the action's result is the
    // answer — the whole contract of a trigger with no intrinsic occurrence.
    let result = server
        .dispatcher
        .run_trigger(&server.catalog, "double", json!({ "n": 21 }), None)
        .await?;
    assert_eq!(result, json!({ "doubled": 42, "who": Value::Null }));

    // The caller travels here too, when one is given.
    let caller = sc_catalog::CallerContext::new(1, Some(json!({ "email": ADMIN })));
    let result = server
        .dispatcher
        .run_trigger(&server.catalog, "double", json!({ "n": 1 }), Some(&caller))
        .await?;
    assert_eq!(result["who"], json!({ "email": ADMIN }));

    // A name nobody defined and a trigger that is switched off are different
    // answers, because they call for different fixes.
    let err = server
        .dispatcher
        .run_trigger(&server.catalog, "nope", Value::Null, None)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("no trigger named"), "{err}");

    let mut off = server
        .dispatcher
        .triggers()?
        .by_name("double")
        .cloned()
        .unwrap();
    off.set_enabled(false);
    server.add_trigger(off).await?;
    let err = server
        .dispatcher
        .run_trigger(&server.catalog, "double", json!({ "n": 1 }), None)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("disabled"), "{err}");
    Ok(())
}
