//! A **Python** trigger through the assembled server (the Python code adapter,
//! phase 2.5).
//!
//! `code_body_tables.rs` presses the admin's Run button on a `run_js_code` body
//! and reads the written rows back over HTTP. This file asks the same question
//! of the same schema in the other language, because what phase 2.5 wires is not
//! the interpreter — that is `sc-python`'s own suite — but the **boot**: that the
//! adapter is built from this process's flags, registered on the dispatcher
//! whether or not this binary has an interpreter linked in, and that a stored
//! Python trigger is therefore a meaningful configuration in every build.
//!
//! So the assertions are deliberately different in the two builds, and both are
//! the point:
//!
//! - built **with** `--features python`: the body runs, and the rows are there —
//!   the same rows, from the same plans, as the JavaScript body's;
//! - built **without** it (the default, and what the release tarball ships): the
//!   trigger still exists, still validates, and firing it answers with the
//!   sentence naming the rebuild.
//!
//! The interpreter is **not** started by booting a server, in either build, and
//! that is asserted before anything fires.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_expr::{CodeAdapter, CodeCall};
use sc_python::PythonState;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, PythonMode, ServerConfig, admin_handlers,
    build_router_with_apps, default_js_evaluator, install_triggers_with_adapters, python_adapter,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// `code_body_tables.rs`'s schema, so the two languages are asked the same
/// question of the same rows.
const SCHEMA: &str = "\
    CREATE TABLE customers (id bigint generated by default as identity primary key, \
        email text not null, name text); \
    CREATE TABLE invoices (id bigint generated by default as identity primary key, \
        amount bigint, due date, paid boolean, customer bigint references customers(id)); \
    CREATE TABLE reminders (id bigint generated by default as identity primary key, \
        invoice bigint references invoices(id), sent_to text); \
    INSERT INTO customers (email, name) VALUES \
        ('ada@example.com', 'Ada'), ('bob@example.com', 'Bob'); \
    INSERT INTO invoices (amount, due, paid, customer) VALUES \
        (100, '2026-08-01', false, 1), \
        (250, '2026-07-15', false, 2), \
        (500, '2026-09-30', false, 1), \
        (75,  '2026-06-01', true,  2);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// The milestone's own example, in Python — the JavaScript one word for word,
/// spelled the way this surface spells it.
const CHASE: &str = r#"
overdue = (db.invoices
    .where(paid=False, due__lt=payload["today"])
    .select("id", "amount", "customerⱵemail", chased="remindersↃinvoice.length")
    .order_by("due")
    .limit(50)
    .rows())
for inv in overdue:
    db.reminders.insert(invoice=inv["id"], sent_to=inv["customerⱵemail"])
return {"chased": len(overdue), "owed": db.invoices.where(paid=False).sum("amount")}
"#;

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    /// Create a `none` trigger whose action is a **Python** body, and answer its
    /// id. That this is accepted at all in a build with no interpreter is half
    /// of what the file is about.
    async fn python_trigger(&mut self, name: &str, code: &str) -> String {
        let (status, created) = self
            .send(
                "POST",
                "/api/triggers",
                Some(json!({
                    "name": name,
                    "description": "",
                    "when": "none",
                    "channel": Value::Null,
                    "only_if": Value::Null,
                    "action": "run_python_code",
                    "configuration": { "code": code },
                    "min_role": Value::Null,
                    "enabled": true,
                })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{created}");
        created["id"].as_str().unwrap().to_owned()
    }

    async fn rows(&mut self, table: &str) -> Vec<Value> {
        let (status, body) = self
            .send("GET", &format!("/api/tables/{table}/rows"), None)
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }
}

struct Server {
    client: Client,
    _db: TestDb,
}

/// The boot path, with the Python adapter built from a `ServerConfig` exactly as
/// `serve` builds it.
async fn setup(config: &ServerConfig) -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    // One runtime, handed to the dispatcher as an adapter and to the mounts as
    // itself — which is how `serve` builds it, and what lets the diagnostics
    // endpoint report the same interpreter a trigger runs on.
    let python = python_adapter(config);
    let dispatcher = install_triggers_with_adapters(
        &catalog,
        default_js_evaluator(),
        &agents,
        [python.clone() as Arc<dyn sc_server::CodeAdapter>],
    )
    .await?;

    let apps = Arc::new(
        AppMounts::new(catalog.clone())
            .with_triggers(dispatcher.clone())
            .with_python(python),
    );
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(sc_auth::SessionStore::default()),
        config,
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server { client, _db: db })
}

/// The whole of phase 2.5, in the order an admin meets it: a Python trigger is
/// saved, booting the server started no interpreter, and pressing Run answers
/// either the rows or the reason.
///
/// One test rather than three because the interpreter is **per process**: an
/// assertion that nothing has started one is only true before something does,
/// and this file is the only thing in this binary that ever fires Python.
#[tokio::test]
async fn a_python_trigger_is_saved_in_every_build_and_runs_where_there_is_an_interpreter()
-> sc_error::Result<()> {
    let mut server = setup(&ServerConfig::default()).await?;
    let id = server.client.python_trigger("chase", CHASE).await;

    // Booting a server does not start an interpreter — the same laziness the
    // code isolate pool has. A server that fires no Python body pays for none.
    assert_ne!(
        sc_python::PythonRuntime::new().state(),
        PythonState::Running {
            version: String::new()
        },
        "nothing has fired yet"
    );
    #[cfg(feature = "python")]
    assert_eq!(
        sc_python::PythonRuntime::new().state(),
        PythonState::NotInitialised
    );
    #[cfg(not(feature = "python"))]
    assert_eq!(
        sc_python::PythonRuntime::new().state(),
        PythonState::NotBuilt
    );

    // And that is what Settings → Development says (phase 4.2), before anything
    // has fired: the state, and a sentence naming the remedy for *this* state
    // rather than a generic one.
    let (status, before) = server.client.send("GET", "/api/python", None).await;
    assert_eq!(status, StatusCode::OK, "{before}");
    // The bounds are this process's flags either way, so they are reported in
    // both builds; nothing is resident, because nothing has run.
    assert_eq!(
        before["max_inflight"],
        json!(sc_python::DEFAULT_MAX_INFLIGHT)
    );
    assert_eq!(before["max_stuck"], json!(sc_python::DEFAULT_MAX_STUCK));
    assert_eq!(before["resident"], json!(0));
    assert_eq!(before["stuck"], json!(0));
    #[cfg(feature = "python")]
    {
        assert_eq!(before["state"], json!("not_initialised"), "{before}");
        assert_eq!(before["version"], Value::Null);
        let said = before["explanation"].as_str().unwrap_or_default();
        assert!(said.contains("has not needed it yet"), "{said}");
        assert_eq!(before["threads"], json!(0), "no run, no thread");
    }
    #[cfg(not(feature = "python"))]
    {
        assert_eq!(before["state"], json!("not_built"), "{before}");
        // The remedy is a rebuild, and the screen names it — the same sentence
        // firing the trigger answers with, for the admin who has not fired it.
        let said = before["explanation"].as_str().unwrap_or_default();
        assert!(said.contains("--features python"), "{said}");
    }

    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/triggers/{id}/run"),
            Some(json!({ "today": "2026-08-17" })),
        )
        .await;

    #[cfg(feature = "python")]
    {
        assert_eq!(status, StatusCode::OK, "{body}");
        // The JavaScript body's answer, to the digit: the same plans against the
        // same rows, and `owed` an exact decimal rather than a float.
        assert_eq!(
            body["result"],
            json!({ "chased": 2, "owed": "850" }),
            "{body}"
        );
        let reminders = server.client.rows("reminders").await;
        let mut sent: Vec<(String, i64)> = reminders
            .iter()
            .map(|r| {
                (
                    r["sent_to"].as_str().unwrap_or_default().to_owned(),
                    r["invoice"].as_i64().unwrap_or_default(),
                )
            })
            .collect();
        sent.sort();
        assert_eq!(
            sent,
            vec![
                ("ada@example.com".to_owned(), 1),
                ("bob@example.com".to_owned(), 2)
            ]
        );
        // And the interpreter is up now, with its version — §7's third state,
        // reached by a trigger rather than by boot.
        assert!(matches!(
            sc_python::PythonRuntime::new().state(),
            PythonState::Running { .. }
        ));
        // Which the screen now reports, with the version, and with a thread
        // that has been kept for the next run.
        let (status, after) = server.client.send("GET", "/api/python", None).await;
        assert_eq!(status, StatusCode::OK, "{after}");
        assert_eq!(after["state"], json!("running"), "{after}");
        let version = after["version"].as_str().unwrap_or_default();
        assert!(
            version.starts_with("3.") && version.split('.').count() == 3,
            "the interpreter's own version: {after}"
        );
        assert_eq!(after["resident"], json!(0), "the run is over");
        assert!(
            after["threads"].as_i64().unwrap_or_default() >= 1,
            "a finished thread is kept for the next run: {after}"
        );
        // No environment was configured, so there is nowhere for a package to
        // be and the screen says so by having neither.
        assert_eq!(after["dir"], Value::Null);
        assert_eq!(after["site_packages"], Value::Null);
        assert_eq!(after["packages"], json!([]));
    }
    #[cfg(not(feature = "python"))]
    {
        assert_ne!(status, StatusCode::OK, "{body}");
        let said = body.to_string();
        assert!(said.contains("built without Python support"), "{said}");
        // The remedy is a rebuild, and it is named: no flag and no restart
        // changes this one.
        assert!(said.contains("--features python"), "{said}");
        // Nothing was written, because nothing ran.
        assert!(server.client.rows("reminders").await.is_empty());
    }
    Ok(())
}

/// `--python off` and a build without Python are **different facts with
/// different remedies**, and the adapter says which one this is.
///
/// No database and no router: what is under test is the sentence
/// [`python_adapter`] builds from a [`ServerConfig`], which is the only thing
/// phase 2.5 adds between the flag and the run.
#[tokio::test]
async fn the_flag_and_the_build_are_different_refusals() {
    let config = ServerConfig {
        python: PythonMode::Off,
        ..ServerConfig::default()
    };
    let adapter = python_adapter(&config);
    assert_eq!(adapter.language(), "python");
    let said = adapter
        .run_code(CodeCall {
            code: "return 1".to_owned(),
            ..CodeCall::default()
        })
        .await
        .expect_err("a process told not to start an interpreter must not run one")
        .to_string();

    #[cfg(feature = "python")]
    {
        // The flag, and the restart that undoes it.
        assert!(said.contains("--python off"), "{said}");
        assert!(said.contains("--python auto"), "{said}");
    }
    #[cfg(not(feature = "python"))]
    {
        // The build has no interpreter for the flag to turn off, so the answer
        // is the one about the rebuild — the deeper fact wins.
        assert!(said.contains("built without Python support"), "{said}");
    }
}

/// `--python off`, on the screen (phase 4.2).
///
/// The fourth state, and the one that is not in §7's list of three: a
/// Python-capable binary that was *told* not to start an interpreter is a
/// different fact from one that has not needed to yet, and an admin who could
/// not tell them apart would go looking for a rebuild when a restart is the fix.
/// No trigger and no run — the state is a property of the process, and asking
/// for it must not be what starts anything.
#[tokio::test]
async fn the_screen_tells_a_process_that_was_turned_off_from_one_that_is_merely_idle()
-> sc_error::Result<()> {
    let config = ServerConfig {
        python: PythonMode::Off,
        ..ServerConfig::default()
    };
    let mut server = setup(&config).await?;
    let (status, body) = server.client.send("GET", "/api/python", None).await;
    assert_eq!(status, StatusCode::OK, "{body}");

    #[cfg(feature = "python")]
    {
        assert_eq!(body["state"], json!("off"), "{body}");
        let said = body["explanation"].as_str().unwrap_or_default();
        assert!(said.contains("--python off"), "{said}");
        assert!(said.contains("--python auto"), "{said}");
    }
    #[cfg(not(feature = "python"))]
    {
        // A build with no interpreter has nothing for the flag to turn off, so
        // the deeper fact wins here exactly as it does in the refusal.
        assert_eq!(body["state"], json!("not_built"), "{body}");
    }
    Ok(())
}

/// A process that booted no Python runtime at all — a test, or an admin-only
/// server — is a fifth answer, and it is not "not built with Python": that
/// binary may well have an interpreter, nobody attached it to this process's
/// mounts. Said plainly rather than reported as a state the specification does
/// not have.
#[tokio::test]
async fn a_server_with_no_runtime_attached_says_that_rather_than_guessing() -> sc_error::Result<()>
{
    let db = TestDb::new().await?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let apps = Arc::new(AppMounts::new(catalog.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(sc_auth::SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;
    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    let (status, body) = client.send("GET", "/api/python", None).await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert_eq!(body["state"], json!("unavailable"), "{body}");
    Ok(())
}
