//! Phase 5 end-to-end: an element arriving on a stream **fires a trigger**
//! (TODO "Streams" §8, task 5.5).
//!
//! The milestone's definition of done says "a trigger with `when = stream` on
//! that stream fires once per element and inserts a row", and this is that
//! scenario with the broker replaced by `sc_stream::testing::ScriptedProvider`
//! — the whole point of the scripted provider being that no test in this tree
//! needs a broker.
//!
//! What is pinned here, and why each of them is a thing that could plausibly
//! have been got wrong:
//!
//!   - an element fires the trigger, which **inserts a row**, so the flow has
//!     become durable the one way §4 says a flow becomes durable;
//!   - the trigger's `only_if` reads the **envelope** (`payload.value.…`) and
//!     filters, which is the whole of "a stream element is not a row" working:
//!     the formula validated on save in a table-less scope and evaluated in the
//!     same one at fire time;
//!   - a trigger **slower than its stream drops rather than queues** (§7), and
//!     the drop is counted on the running stream where an admin can see it;
//!   - the **cascade bound** still holds from a stream-originated event — the
//!     row the trigger inserts raises an event of its own, and a chain of them
//!     is refused at [`sc_action::MAX_DEPTH`] exactly as one begun by a request
//!     is.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;
use std::time::Duration;

use sc_action::{Event, EventKind, Trigger, TriggerDispatcher, save_trigger};
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_stream::testing::ScriptedProvider;
use sc_stream::{
    ElementField, ElementType, RawPayload, Stream, StreamConfig, StreamRegistry, save_stream,
};
use sc_test_harness::TestDb;
use sc_types::BasicType;
use serde_json::json;

/// One table for the trigger to write into, and one that fires on its own
/// writes so the cascade bound has something to run away with.
const SCHEMA: &str = "\
    CREATE TABLE readings (id bigint generated by default as identity primary key, \
        temperature double precision, topic text); \
    CREATE TABLE echoes (id bigint generated by default as identity primary key, \
        n bigint);";

/// The element type the boiler publishes: `{temperature, unit}`.
fn boiler_reading() -> ElementType {
    ElementType::json([
        ElementField::new("temperature", BasicType::Float).required(),
        ElementField::new("unit", BasicType::Text),
    ])
}

/// A registry holding one scripted provider, and the provider itself so a test
/// can ask how many times it was subscribed.
fn registry(provider: ScriptedProvider) -> Arc<StreamRegistry> {
    let mut registry = StreamRegistry::new();
    registry
        .register(Arc::new(provider) as Arc<dyn sc_stream::StreamProvider>)
        .unwrap();
    Arc::new(registry)
}

async fn setup(db: &TestDb) -> Result<Arc<Catalog>> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    // `install_streams_with` bootstraps it too, but these tests save a stream
    // *before* starting the supervisor — which is the ordering a second process
    // defining a stream really has.
    sc_stream::bootstrap_streams(&catalog).await?;
    Ok(catalog)
}

async fn dispatcher(catalog: &Arc<Catalog>) -> Result<Arc<TriggerDispatcher>> {
    let agents = sc_server::install_agents(catalog).await?;
    let models = sc_server::install_models(catalog, sc_model::DEFAULT_MAX_ROWS).await?;
    sc_server::install_triggers(catalog, sc_server::default_js_evaluator(), &agents, &models).await
}

/// How many rows a table holds — asked of the database directly, because what
/// is being asserted is that the trigger's write really landed.
async fn count(db: &TestDb, table: &str) -> Result<i64> {
    let row = db
        .client()
        .await?
        .query_one(&format!("SELECT count(*) FROM {table}"), &[])
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    Ok(row.get(0))
}

/// Long enough for a spawned firing to reach the database on any machine that
/// can run the rest of this suite.
async fn settle() {
    tokio::time::sleep(Duration::from_millis(400)).await;
}

#[tokio::test]
async fn an_element_fires_a_trigger_that_inserts_a_row() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let triggers = dispatcher(&catalog).await?;

    // The stream: three readings, two of them hot.
    // Spaced out, so each firing finishes before the next element arrives:
    // "fires once per element" is true of a trigger that keeps up, and a
    // trigger that does not is the *next* test's subject (§7).
    let provider = ScriptedProvider::new("scripted", boiler_reading())
        .json_elements([
            json!({ "temperature": 31.5, "unit": "C" }),
            json!({ "temperature": 12.0, "unit": "C" }),
            json!({ "temperature": 40.25, "unit": "C" }),
        ])
        .every(Duration::from_millis(250));
    let registry = registry(provider);
    let stream = Stream::new("boiler", "scripted").description("the boiler's thermometer");
    save_stream(&catalog, &registry, &stream).await?;

    // The trigger: `when = stream`, channel = the stream's name, and an
    // `only_if` over the **envelope** — the row-less scope §8 gives it.
    save_trigger(
        &catalog,
        &triggers.registry(),
        &Trigger::new("record_hot", EventKind::Stream, "insert_row")
            .on("boiler")
            .only_if("payload.value.temperature > 30")
            .config("table", "readings")
            .config(
                "values",
                json!({ "temperature": "payload.value.temperature" }),
            ),
    )
    .await?;
    triggers.reload(&catalog).await?;

    // Warm the JavaScript isolate before the flow starts, with an element the
    // `only_if` declines: the first formula evaluation in a process builds V8,
    // and a timing assertion about whether the trigger kept up must not be an
    // assertion about that. It also pins the negative half of the filter.
    triggers
        .fire(
            &catalog,
            &Event::stream(
                "boiler",
                json!({ "stream": "boiler", "value": { "temperature": 1.0 },
                        "received_at": "2026-09-17T09:00:00.000Z" }),
            ),
        )
        .await;
    assert_eq!(
        count(&db, "readings").await?,
        0,
        "the cold one was declined"
    );

    // Starting the streams is what subscribes the provider and installs the
    // bridge; from here the flow is real.
    let streams =
        sc_server::install_streams_with(&catalog, &triggers, registry, StreamConfig::default())
            .await?;
    tokio::time::sleep(Duration::from_millis(2_000)).await;

    let running = streams
        .supervisor()
        .by_name("boiler")
        .expect("the stream is running");
    assert_eq!(
        running.counters().elements,
        3,
        "every element the script wrote reached the supervisor"
    );

    assert_eq!(
        running.counters().dropped_for_triggers,
        0,
        "the trigger kept up, so nothing was dropped"
    );

    // Two rows, not three: the `only_if` read the envelope and declined the
    // cold one. That is the assertion that a stream trigger's formula ranges
    // over `payload` rather than over a row it does not have.
    assert_eq!(count(&db, "readings").await?, 2);
    // And the row carries the element's own value, so the trigger's settings
    // read the envelope too — not just its `only_if`.
    let hottest: f64 = db
        .client()
        .await?
        .query_one("SELECT max(temperature) FROM readings", &[])
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?
        .get(0);
    assert!((hottest - 40.25).abs() < 1e-9, "{hottest}");
    Ok(())
}

#[tokio::test]
async fn a_trigger_slower_than_its_stream_drops_rather_than_queues() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let triggers = dispatcher(&catalog).await?;

    // A stream that never goes quiet, and a trigger that takes a tenth of a
    // second per element. There is no arrangement of those two numbers under
    // which the trigger keeps up, which is the point: §7 says the extra
    // firings are dropped and counted, never queued, because an unbounded
    // queue in front of a trigger is a memory leak with a delay built in.
    let provider = ScriptedProvider::new("scripted", ElementType::text())
        .elements(vec![RawPayload::bytes(b"tick".to_vec())])
        .every(Duration::from_millis(5))
        .repeating();
    let registry = registry(provider);
    save_stream(&catalog, &registry, &Stream::new("fast", "scripted")).await?;

    save_trigger(
        &catalog,
        &triggers.registry(),
        &Trigger::new("slow", EventKind::Stream, "run_js_code")
            .on("fast")
            // Busy rather than asleep: the code isolate has no timers, and
            // what this needs is a body that takes longer than the interval
            // between elements, not one that yields.
            .config(
                "code",
                "const end = Date.now() + 100; let n = 0; \
                 while (Date.now() < end) { n += 1; } return n;",
            ),
    )
    .await?;
    triggers.reload(&catalog).await?;

    let streams =
        sc_server::install_streams_with(&catalog, &triggers, registry, StreamConfig::default())
            .await?;
    settle().await;
    // Read the counters before hanging up: `shutdown` forgets the stream, and
    // what is being asserted is what it saw while it was running.
    let counters = streams
        .supervisor()
        .by_name("fast")
        .expect("the stream is running")
        .counters();
    streams.supervisor().shutdown();
    assert!(
        counters.elements > 10,
        "the stream produced plenty: {} elements",
        counters.elements
    );
    // The flow was not slowed to the trigger's pace, and the drops are a number
    // an admin can see on the Streams list rather than a silence.
    assert!(
        counters.dropped_for_triggers > 0,
        "a trigger that cannot keep up must drop and count: {counters:?}"
    );
    Ok(())
}

#[tokio::test]
async fn the_cascade_bound_holds_from_a_stream_originated_event() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let triggers = dispatcher(&catalog).await?;

    // One element, and a trigger on `echoes` that inserts into `echoes` — the
    // runaway shape. Begun by a stream rather than by a request, which is the
    // only thing this test changes: `Event::firing` counts the chain the same
    // way, so the cascade stops at MAX_DEPTH and not at the disk filling up.
    let provider = ScriptedProvider::new("scripted", ElementType::text())
        .elements(vec![RawPayload::bytes(b"go".to_vec())]);
    let registry = registry(provider);
    save_stream(&catalog, &registry, &Stream::new("kick", "scripted")).await?;

    save_trigger(
        &catalog,
        &triggers.registry(),
        &Trigger::new("seed", EventKind::Stream, "insert_row")
            .on("kick")
            .config("table", "echoes")
            .config("values", json!({ "n": "1" })),
    )
    .await?;
    save_trigger(
        &catalog,
        &triggers.registry(),
        &Trigger::new("echo", EventKind::Insert, "insert_row")
            .on("echoes")
            .config("table", "echoes")
            .config("values", json!({ "n": "row.n + 1" })),
    )
    .await?;
    triggers.reload(&catalog).await?;

    let _streams =
        sc_server::install_streams_with(&catalog, &triggers, registry, StreamConfig::default())
            .await?;
    settle().await;

    // The stream's own firing is depth 0, so `seed` writes one row and `echo`
    // may descend MAX_DEPTH times from it before it is refused by name.
    let rows = count(&db, "echoes").await?;
    assert!(
        rows >= 2 && rows <= sc_action::MAX_DEPTH as i64 + 1,
        "the cascade was bounded, not unbounded: {rows} rows"
    );
    Ok(())
}

#[tokio::test]
async fn a_stream_nobody_triggers_on_still_flows() -> Result<()> {
    // The bridge asks the live trigger set before it takes anything, so a
    // stream that only feeds the Observe screen costs no task per element and —
    // more to the point — is never recorded as dropping.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let triggers = dispatcher(&catalog).await?;

    let provider = ScriptedProvider::new("scripted", ElementType::text())
        .elements(vec![RawPayload::bytes(b"quiet".to_vec())]);
    let registry = registry(provider);
    save_stream(&catalog, &registry, &Stream::new("unwatched", "scripted")).await?;

    let streams =
        sc_server::install_streams_with(&catalog, &triggers, registry, StreamConfig::default())
            .await?;
    settle().await;

    let counters = streams
        .supervisor()
        .by_name("unwatched")
        .expect("the stream is running")
        .counters();
    assert_eq!(counters.elements, 1);
    assert_eq!(
        counters.dropped_for_triggers, 0,
        "an element nobody asked for is not a trigger that fell behind"
    );
    Ok(())
}

#[tokio::test]
async fn a_stream_saved_after_boot_starts_on_a_reload() -> Result<()> {
    // What `SIGHUP` and the admin API's save both do (task 5.4): the supervisor
    // diffs the stored rows against the running set, so a stream defined by
    // another process starts without a restart.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let triggers = dispatcher(&catalog).await?;

    let provider = ScriptedProvider::new("scripted", ElementType::text())
        .elements(vec![RawPayload::bytes(b"later".to_vec())]);
    let registry = registry(provider);
    let streams = sc_server::install_streams_with(
        &catalog,
        &triggers,
        Arc::clone(&registry),
        StreamConfig::default(),
    )
    .await?;
    assert!(streams.supervisor().streams().is_empty());

    save_stream(&catalog, &registry, &Stream::new("late", "scripted")).await?;
    assert!(streams.reload(&catalog).await?, "the set changed");
    settle().await;
    assert_eq!(
        streams
            .supervisor()
            .by_name("late")
            .expect("the stream is running")
            .counters()
            .elements,
        1
    );

    // And a reload that changes nothing leaves the connection alone — the
    // load-bearing half of the diff, since a `SIGHUP` reloads everything.
    assert!(!streams.reload(&catalog).await?, "nothing moved");

    // Firing a stream event by hand for a stream nothing is listening to is
    // still just an event: nothing fires, and nothing fails.
    triggers
        .fire(&catalog, &Event::stream("late", json!({ "value": "x" })))
        .await;
    Ok(())
}
