//! Phase 4 end-to-end: a row written through the real router fires the triggers
//! that listen for it (§10.2, decision 1 and decision 2).
//!
//! Everything here goes in as an **HTTP request** to the admin API and is
//! asserted by reading the database back the same way, because the claim being
//! tested spans the whole stack: the row layer raises an event through a seam it
//! cannot see the other side of, the dispatcher matches it against the cached
//! trigger set, an `only_if` runs in the real V8 engine against the real row, and
//! the action writes through the same `rows` layer the request itself used. A
//! unit test of any one of those would assert a shape rather than the behaviour.
//!
//! What is pinned:
//!
//! - an **insert** trigger writing an audit row, with the event's row *and its
//!   caller* — who is only there because the caller travels with every write;
//! - an **update** trigger reading `old` and `row` in the same formula;
//! - a **delete** trigger carrying the row as it was, after it is gone;
//! - an **`only_if`** gating firing, both over the row's own fields and over a
//!   **Ⱶ-join path** (which the dispatcher has to prefetch, and which therefore
//!   only works if the row's key value is typed as its column);
//! - the **depth limit** stopping a self-feeding trigger, and naming the chain;
//! - a **failing action** neither failing the request nor losing the write.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_action::{Event, EventKind, Trigger, TriggerDispatcher, save_trigger};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router,
    default_js_evaluator, install_triggers,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// The tables every test works over: books with a Key to authors (so an
/// `only_if` has a Ⱶ-path to walk), an audit table for triggers to write into,
/// and one self-referential table for the cascade limit.
const SCHEMA: &str = "\
    CREATE TABLE authors (id bigint generated by default as identity primary key, \
        name text, tier text); \
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text not null, pages bigint, author bigint references authors(id)); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        what text, title text, was text, pages bigint, who text); \
    CREATE TABLE links (id bigint generated by default as identity primary key, depth bigint); \
    INSERT INTO authors (name, tier) VALUES ('Ada', 'gold'), ('Bob', 'silver');";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

/// A cookie-jar-carrying client over the router, as `admin_api.rs` uses: it
/// keeps the CSRF and session cookies between requests and echoes the token on
/// mutations, exactly as the SPA does.
struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 256 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    /// Every row of `table`, through the API.
    async fn rows(&mut self, table: &str) -> Vec<Value> {
        let (status, body) = self
            .send("GET", &format!("/api/tables/{table}/rows"), None)
            .await;
        assert_eq!(status, StatusCode::OK, "{body}");
        body.as_array().cloned().unwrap_or_default()
    }
}

/// One booted server: the router, the catalog the triggers are stored in, and
/// the live dispatcher (so a test can add a trigger and reload the set the way
/// Phase 6's admin API will).
struct Server {
    client: Client,
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    _db: TestDb,
}

impl Server {
    /// Store `trigger` and put it in the live set — what saving one in the admin
    /// UI will do once Phase 6 exposes it.
    async fn add_trigger(&self, trigger: Trigger) -> sc_error::Result<()> {
        save_trigger(&self.catalog, self.dispatcher.registry(), &trigger).await?;
        self.dispatcher.reload(&self.catalog).await
    }
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            // The multi-tenant v1 test template carries `users` tables in several
            // schemas; drop them all so bootstrap creates the clean MVP table.
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;

    // The boot path itself: the built-in actions, the stored triggers, and the
    // dispatcher installed into the catalog. Before this call nothing observes a
    // write — which is exactly what every other test in this suite relies on.
    let dispatcher = install_triggers(&catalog, default_js_evaluator()).await?;

    let apps = Arc::new(AppMounts::new(catalog.clone()));
    let router = build_router(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    // One GET first, for the CSRF cookie every mutation has to echo — the same
    // handshake the SPA makes when it loads.
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server {
        client,
        catalog,
        dispatcher,
        _db: db,
    })
}

/// An `insert_row` action writing one audit row from a field → formula map.
fn audit_action(trigger: Trigger, values: Value) -> Trigger {
    trigger.config("table", "audit").config("values", values)
}

#[tokio::test]
async fn an_insert_writes_the_audit_row_its_trigger_configures() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(audit_action(
            Trigger::new("audit_insert", EventKind::Insert, "insert_row").on("books"),
            json!({
                "what": "\"insert\"",
                "title": "row.title",
                "pages": "row.pages",
                // The caller only reaches here because a `CallerContext` travels
                // with every write, not only with the RLS ones.
                "who": "user.email",
            }),
        ))
        .await?;

    let (status, book) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Dune", "pages": 412 })),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED, "{book}");
    assert_eq!(book["title"], json!("Dune"));

    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "{audit:?}");
    assert_eq!(audit[0]["what"], json!("insert"));
    assert_eq!(audit[0]["title"], json!("Dune"));
    assert_eq!(audit[0]["pages"], json!(412));
    assert_eq!(audit[0]["who"], json!(ADMIN), "the event knows who wrote");

    // Nothing listens for updates or deletes on `books`, so neither raises an
    // audit row — the match is by (kind, table), not by table alone.
    let id = book["id"].as_i64().unwrap();
    server
        .client
        .send(
            "PUT",
            &format!("/api/tables/books/rows/{id}"),
            Some(json!({ "pages": 500 })),
        )
        .await;
    server
        .client
        .send("DELETE", &format!("/api/tables/books/rows/{id}"), None)
        .await;
    assert_eq!(server.client.rows("audit").await.len(), 1);
    Ok(())
}

#[tokio::test]
async fn an_update_trigger_sees_both_the_new_row_and_the_one_it_replaced() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(audit_action(
            Trigger::new("audit_update", EventKind::Update, "insert_row").on("books"),
            json!({ "what": "\"update\"", "title": "row.title", "was": "old.title" }),
        ))
        .await?;

    let (_, book) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Dune", "pages": 412 })),
        )
        .await;
    let id = book["id"].as_i64().unwrap();

    let (status, updated) = server
        .client
        .send(
            "PUT",
            &format!("/api/tables/books/rows/{id}"),
            Some(json!({ "title": "Dune (revised)" })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{updated}");

    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "{audit:?}");
    // The pre-image is read *before* the update, and only because something is
    // listening for it: `old` is the row as it was, `row` as it now is.
    assert_eq!(audit[0]["was"], json!("Dune"));
    assert_eq!(audit[0]["title"], json!("Dune (revised)"));
    Ok(())
}

#[tokio::test]
async fn a_delete_trigger_carries_the_row_as_it_was() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(audit_action(
            Trigger::new("audit_delete", EventKind::Delete, "insert_row").on("books"),
            json!({ "what": "\"delete\"", "title": "row.title", "pages": "row.pages" }),
        ))
        .await?;

    let (_, book) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Dune", "pages": 412 })),
        )
        .await;
    let id = book["id"].as_i64().unwrap();

    let (status, body) = server
        .client
        .send("DELETE", &format!("/api/tables/books/rows/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert!(server.client.rows("books").await.is_empty(), "it is gone");

    // …and the audit row has what it said, which is the only copy left.
    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "{audit:?}");
    assert_eq!(audit[0]["title"], json!("Dune"));
    assert_eq!(audit[0]["pages"], json!(412));
    Ok(())
}

#[tokio::test]
async fn an_only_if_decides_whether_the_action_runs() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(
            audit_action(
                Trigger::new("audit_long", EventKind::Insert, "insert_row").on("books"),
                json!({ "what": "\"long\"", "title": "row.title" }),
            )
            // A bare identifier is the affected row's own field (decision 7).
            .only_if("pages > 100"),
        )
        .await?;

    for (title, pages) in [("Dune", 412), ("A Pamphlet", 30)] {
        let (status, body) = server
            .client
            .send(
                "POST",
                "/api/tables/books/rows",
                Some(json!({ "title": title, "pages": pages })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{body}");
    }

    // Both rows were written; only the one the predicate selects was audited,
    // and the other passed in silence — not as an error.
    assert_eq!(server.client.rows("books").await.len(), 2);
    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "{audit:?}");
    assert_eq!(audit[0]["title"], json!("Dune"));
    Ok(())
}

#[tokio::test]
async fn an_only_if_can_read_through_a_join_path() -> sc_error::Result<()> {
    let mut server = setup().await?;
    server
        .add_trigger(
            audit_action(
                Trigger::new("audit_gold", EventKind::Insert, "insert_row").on("books"),
                json!({ "what": "\"gold\"", "title": "row.title" }),
            )
            // The value is not in the row: the dispatcher has to walk the Key
            // link to `authors`, correlating on the row's own `author` value —
            // which only works because that value is typed as its column.
            .only_if("authorⱵtier === \"gold\""),
        )
        .await?;

    let authors = server.client.rows("authors").await;
    let id_of = |name: &str| -> i64 {
        authors
            .iter()
            .find(|a| a["name"] == json!(name))
            .and_then(|a| a["id"].as_i64())
            .unwrap()
    };

    for (title, author) in [("Ada's Book", id_of("Ada")), ("Bob's Book", id_of("Bob"))] {
        let (status, body) = server
            .client
            .send(
                "POST",
                "/api/tables/books/rows",
                Some(json!({ "title": title, "pages": 100, "author": author })),
            )
            .await;
        assert_eq!(status, StatusCode::CREATED, "{body}");
    }

    let audit = server.client.rows("audit").await;
    assert_eq!(audit.len(), 1, "{audit:?}");
    assert_eq!(audit[0]["title"], json!("Ada's Book"));
    Ok(())
}

#[tokio::test]
async fn a_self_feeding_trigger_is_stopped_by_the_depth_limit() -> sc_error::Result<()> {
    let mut server = setup().await?;
    // Every insert into `links` inserts another one. Nothing about this trigger
    // is wrong — a write causing a write is the point of decision 5 — so what
    // stops it has to be the bound, not a refusal to save it.
    server
        .add_trigger(
            Trigger::new("feed", EventKind::Insert, "insert_row")
                .on("links")
                .config("table", "links")
                .config("values", json!({ "depth": "row.depth + 1" })),
        )
        .await?;

    let (status, body) = server
        .client
        .send(
            "POST",
            "/api/tables/links/rows",
            Some(json!({ "depth": 0 })),
        )
        .await;
    // The request that started it succeeds: the cascade is bounded, not fatal.
    assert_eq!(status, StatusCode::CREATED, "{body}");

    let depths: Vec<i64> = server
        .client
        .rows("links")
        .await
        .iter()
        .filter_map(|r| r["depth"].as_i64())
        .collect();
    // The original row plus one per firing, and firings stop at MAX_DEPTH.
    assert_eq!(
        depths,
        (0..=i64::try_from(sc_action::MAX_DEPTH).unwrap()).collect::<Vec<_>>()
    );

    // And the refusal names the whole chain, because "too deep" without the path
    // is a diagnosis the admin would have to redo by hand.
    let deep = Event::new(EventKind::Insert)
        .on("links")
        .row(json!({ "id": 1, "depth": 1 }))
        .chained(vec!["feed".into(); sc_action::MAX_DEPTH]);
    let runs = server.dispatcher.dispatch(&server.catalog, &deep).await;
    assert_eq!(runs.len(), 1);
    let message = runs[0].outcome.as_ref().unwrap_err().to_string();
    assert!(message.contains("feed → feed → feed"), "{message}");
    assert!(message.contains("was not run"), "{message}");
    Ok(())
}

#[tokio::test]
async fn a_failing_action_costs_the_trigger_and_nothing_else() -> sc_error::Result<()> {
    let mut server = setup().await?;
    // Two triggers on the same event: the first one throws, and the second must
    // still run — one trigger's failure is one trigger's failure.
    server
        .add_trigger(
            Trigger::new("boom", EventKind::Insert, "run_js_code")
                .on("books")
                .config("code", "throw new Error('the audit service is down');"),
        )
        .await?;
    server
        .add_trigger(audit_action(
            Trigger::new("still_runs", EventKind::Insert, "insert_row").on("books"),
            json!({ "what": "\"insert\"", "title": "row.title" }),
        ))
        .await?;

    let (status, book) = server
        .client
        .send(
            "POST",
            "/api/tables/books/rows",
            Some(json!({ "title": "Dune", "pages": 412 })),
        )
        .await;
    // The write happened and the request succeeded: dispatch is after the
    // commit, so a broken trigger cannot undo it or fail it.
    assert_eq!(status, StatusCode::CREATED, "{book}");
    assert_eq!(server.client.rows("books").await.len(), 1);
    assert_eq!(server.client.rows("audit").await.len(), 1);

    // The failure is not swallowed either — dispatch reports it per trigger,
    // which is what the emit path logs.
    let event = Event::new(EventKind::Insert)
        .on("books")
        .row(json!({ "id": 1, "title": "Dune", "pages": 412 }));
    let runs = server.dispatcher.dispatch(&server.catalog, &event).await;
    let names: Vec<&str> = runs.iter().map(|r| r.trigger.as_str()).collect();
    assert_eq!(names, vec!["boom", "still_runs"], "in name order");
    let message = runs[0].outcome.as_ref().unwrap_err().to_string();
    assert!(message.contains("the audit service is down"), "{message}");
    assert!(runs[1].fired(), "the second trigger still ran");
    Ok(())
}
