//! The workflows tutorial, executed: the program `docs/tutorial-workflows.md`
//! asks the reader to draw, saved and run for real (§10.3, TODO 8.1).
//!
//! The precedent is `sc-core-actions`' `tutorial_triggers.rs`, and the reason is
//! the same: a tutorial is a promise that the words in the boxes work, and the
//! ways it stops being true are quiet ones — a formula rule tightens, an action
//! renames a setting, a step kind gains a required field. None of those break a
//! test that only reads the markdown, so this one **copies the program out of the
//! document** and puts it through the admin API the tutorial drives by hand:
//! create the trigger, save the workflow, submit an order, watch the run suspend
//! at the approval, answer it, and read back the two rows the workflow wrote.
//!
//! What it pins, in the tutorial's own order:
//!
//! - the `only_if` that keeps the workflow's own write from starting a second run
//!   — the hazard a workflow on a table it also writes actually has;
//! - a code step whose **return value** is the context key later steps read;
//! - the loop: a `Set` before it, a `for_each` over the code step's answer, and a
//!   body that accumulates — which is the only shape a loop can have while an
//!   action step cannot read the context (see the last test);
//! - the branch, the approval form's declaration, and the answer merged under
//!   `context.approval`;
//! - the two endings, one of which is the tutorial's example of an **idempotent**
//!   step (an update keyed by the event's row) and the other of which is its
//!   example of a step made idempotent **by hand** (a code body that checks
//!   before it writes);
//! - and the gap the tutorial's "trips people up" section names: an action step's
//!   settings cannot read `context`. That test exists to fail the day the gap is
//!   closed, because the document has a paragraph that must change with it.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers, start_workflow_engine,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

/// The three tables of the tutorial's step 1.
const SCHEMA: &str = "\
    CREATE TABLE orders (id bigint generated by default as identity primary key, \
        customer text, email text, total bigint, status text); \
    CREATE TABLE order_lines (id bigint generated by default as identity primary key, \
        \"order\" bigint references orders(id), item text, qty bigint); \
    CREATE TABLE order_events (id bigint generated by default as identity primary key, \
        \"order\" bigint references orders(id), kind text, at bigint);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

// ---------------------------------------------------------------------------
// The tutorial's own text
// ---------------------------------------------------------------------------

/// Step 3's code body, verbatim.
const LOAD_LINES: &str = r#"return await db.order_lines
  .where({ order: row.id })
  .select("id", "item", "qty")
  .orderBy("id")
  .rows();"#;

/// Step 7's code body, verbatim — the tutorial's worked example of a step that
/// is **not** naturally idempotent being made so by hand.
const LOG: &str = r#"const already = await db.order_events
  .where({ order: row.id, kind: "decided" })
  .exists();
if (already) return { wrote: false };
await db.order_events.insert({ order: row.id, kind: "decided", at: Date.now() });
return { wrote: true };"#;

/// Step 2's trigger: an **update** that becomes `submitted`, so the order's lines
/// exist by the time the run reads them and the workflow's own write to `status`
/// does not start a second run.
fn tutorial_trigger() -> Value {
    json!({
        "name": "order_approval",
        "description": "",
        "when": "update",
        "channel": "orders",
        "only_if": "status === 'submitted' && old.status !== 'submitted'",
        "body": "workflow",
        "action": Value::Null,
        "configuration": Value::Null,
        "min_role": Value::Null,
        "enabled": true,
    })
}

/// The whole program of steps 3–7, in the shape the editor saves and the engine
/// reads — there is no second spelling.
fn tutorial_workflow() -> Value {
    json!({
        "start": "load_lines",
        "trace": true,
        "steps": [
            {
                "name": "load_lines",
                "kind": {
                    "type": "action",
                    "action": "run_js_code",
                    "configuration": { "code": LOAD_LINES }
                },
                "next": { "type": "step", "step": "start_count" }
            },
            {
                "name": "start_count",
                "kind": { "type": "set", "assignments": [{ "target": "units", "formula": "0" }] },
                "next": { "type": "step", "step": "per_line" }
            },
            {
                "name": "per_line",
                "kind": {
                    "type": "for_each",
                    "over": "context.load_lines",
                    "var": "line",
                    "body": "add_line"
                },
                "next": { "type": "step", "step": "classify" }
            },
            {
                "name": "add_line",
                "kind": {
                    "type": "set",
                    "assignments": [
                        { "target": "units", "formula": "context.units + context.line.qty" }
                    ]
                },
                "next": { "type": "end" }
            },
            {
                "name": "classify",
                "kind": {
                    "type": "set",
                    "assignments": [
                        { "target": "large", "formula": "row.total > 100 || context.units > 20" }
                    ]
                },
                "next": {
                    "type": "branch",
                    "arms": [{ "when": "context.large", "step": "approve" }],
                    "otherwise": "ship"
                }
            },
            {
                "name": "approve",
                "kind": {
                    "type": "user_form",
                    "fields": [
                        { "name": "approved", "label": "Approved?", "type": "bool", "required": true },
                        { "name": "note", "label": "Note", "type": "text" }
                    ],
                    "assign_to": "approval",
                    "timeout": "1000 * 60 * 60 * 24 * 3"
                },
                "next": {
                    "type": "branch",
                    "arms": [{ "when": "context.approval.approved", "step": "ship" }],
                    "otherwise": "reject"
                },
                "error_policy": { "type": "handler", "step": "reject" }
            },
            {
                "name": "ship",
                "kind": {
                    "type": "action",
                    "action": "update_rows",
                    "configuration": {
                        "table": "orders",
                        "where": "id === row.id",
                        "assignments": { "status": "'shipped'" }
                    }
                },
                "next": { "type": "step", "step": "log" }
            },
            {
                "name": "reject",
                "kind": {
                    "type": "action",
                    "action": "update_rows",
                    "configuration": {
                        "table": "orders",
                        "where": "id === row.id",
                        "assignments": { "status": "'rejected'" }
                    }
                },
                "next": { "type": "step", "step": "log" }
            },
            {
                "name": "log",
                "kind": {
                    "type": "action",
                    "action": "run_js_code",
                    "configuration": { "code": LOG }
                },
                "next": { "type": "end" }
            }
        ]
    })
}

// ---------------------------------------------------------------------------
// The fixture: the admin API, as the tutorial's reader drives it
// ---------------------------------------------------------------------------

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 512 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    async fn ok(&mut self, method: &str, path: &str, body: Option<Value>) -> Value {
        let (status, value) = self.send(method, path, body).await;
        assert!(status.is_success(), "{method} {path}: {status} {value}");
        value
    }
}

struct Server {
    client: Client,
    _engine: Arc<sc_workflow::WorkflowEngineTask>,
    _db: TestDb,
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents).await?;
    // The tutorial's reader is running `serve`, which is the only thing that
    // starts the engine (§10.3, phase 3.3).
    let (engine, _handle) = start_workflow_engine(&catalog, &dispatcher);

    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server {
        client,
        _engine: engine,
        _db: db,
    })
}

/// Steps 2 and 8: the trigger, and the program saved into it. Answers the
/// trigger's id.
async fn drawn(server: &mut Server) -> String {
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(tutorial_trigger()))
        .await;
    let id = created["id"].as_str().expect("an id").to_owned();
    let saved = server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": tutorial_workflow(), "description": "the tutorial" })),
        )
        .await;
    // Everything the tutorial types holds together: no unreachable step, no
    // formula that will not resolve, no action setting that does not validate.
    assert_eq!(saved["issues"], json!([]), "{saved}");
    assert_eq!(saved["version"], json!(2), "creating the trigger minted v1");
    id
}

/// Step 9: an order with its lines, then the update that submits it.
async fn submit(server: &mut Server, total: i64, quantities: &[i64]) -> i64 {
    let order = server
        .client
        .ok(
            "POST",
            "/api/tables/orders/rows",
            Some(json!({ "customer": "Acme", "email": "buyer@example.com", "total": total })),
        )
        .await;
    let id = order["id"].as_i64().expect("the order's id");
    for (n, qty) in quantities.iter().enumerate() {
        server
            .client
            .ok(
                "POST",
                "/api/tables/order_lines/rows",
                Some(json!({ "order": id, "item": format!("thing {n}"), "qty": qty })),
            )
            .await;
    }
    server
        .client
        .ok(
            "PUT",
            &format!("/api/tables/orders/rows/{id}"),
            Some(json!({ "status": "submitted" })),
        )
        .await;
    id
}

/// The one run of this workflow.
async fn the_run(server: &mut Server, trigger: &str) -> Value {
    let runs = server
        .client
        .ok("GET", &format!("/api/workflows/{trigger}/runs"), None)
        .await;
    let runs = runs.as_array().cloned().unwrap_or_default();
    assert_eq!(runs.len(), 1, "{runs:?}");
    runs[0].clone()
}

async fn order(server: &mut Server, id: i64) -> Value {
    let rows = server
        .client
        .ok("GET", "/api/tables/orders/rows", None)
        .await;
    rows.as_array()
        .and_then(|rows| {
            rows.iter()
                .find(|row| row["id"].as_i64() == Some(id))
                .cloned()
        })
        .expect("the order")
}

// ---------------------------------------------------------------------------
// The tutorial, run
// ---------------------------------------------------------------------------

#[tokio::test]
async fn a_large_order_loops_over_its_lines_waits_for_a_person_and_ships() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let trigger = drawn(&mut server).await;

    // Step 9: two lines, seven units, £500 — large on either count.
    let id = submit(&mut server, 500, &[3, 4]).await;

    // The engine drove the run as far as it could the moment the row was
    // updated, and that is as far as a person.
    let run = the_run(&mut server, &trigger).await;
    assert_eq!(run["state"], json!("waiting"), "{run}");
    assert_eq!(run["current_step"], json!("approve"));
    assert_eq!(run["subject_version"], json!(2));
    // The form has a **timeout**, so the run does have a wake-up: three days
    // out, when "nobody answered" becomes the failure its error policy routes.
    // A form with no timeout waits with `wake_at` NULL, which is what "no clock
    // will make this runnable" means.
    assert!(run["wake_at"].is_string(), "{run}");
    let run_id = run["id"].as_str().expect("a run id").to_owned();

    // Step 11's screen: the form as the step declared it, and the trace of the
    // steps that got here — including the loop, which ran its body once per line.
    let detail = server
        .client
        .ok("GET", &format!("/api/runs/{run_id}"), None)
        .await;
    let form = &detail["pending_form"];
    assert_eq!(form["assign_to"], json!("approval"));
    let fields = form["fields"].as_array().unwrap();
    assert_eq!(fields.len(), 2);
    assert_eq!(fields[0]["name"], json!("approved"));
    assert_eq!(fields[0]["type"], json!("bool"));
    assert_eq!(fields[0]["required"], json!(true));
    let steps: Vec<&str> = detail["trace"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| t["step"].as_str().unwrap())
        .collect();
    // One entry per **advance**, which is not quite one per iteration: a loop
    // body that is a single step keeps the driver on the same step name, so both
    // iterations are serviced in one pass and share one trace row (and one
    // write). The tutorial says so, because it is what a reader sees here.
    assert_eq!(
        steps,
        vec![
            "load_lines",
            "start_count",
            "per_line",
            "add_line",
            "classify",
            "approve",
        ],
        "{:?}",
        detail["trace"]
    );
    let context = &detail["context"]["context"];
    assert_eq!(
        context["units"],
        json!(7),
        "3 + 4: the body ran once per line, whatever the trace's granularity"
    );
    assert_eq!(
        context["line"],
        json!({ "id": 2, "item": "thing 1", "qty": 4 }),
        "the loop variable is left bound to the last item"
    );
    assert_eq!(context["large"], json!(true));
    assert_eq!(
        context["load_lines"].as_array().map(Vec::len),
        Some(2),
        "the code step's return value is the context key its name spells"
    );

    // Step 11: the answer, checked against the declaration and merged under
    // `context.approval`.
    let answered = server
        .client
        .ok(
            "POST",
            &format!("/api/runs/{run_id}/resume"),
            Some(json!({ "approved": true, "note": "fine by me" })),
        )
        .await;
    assert_eq!(answered["state"], json!("done"), "{answered}");
    assert_eq!(
        answered["context"]["context"]["approval"],
        json!({ "approved": true, "note": "fine by me" })
    );

    // The two endings wrote what the tutorial says they write.
    assert_eq!(order(&mut server, id).await["status"], json!("shipped"));
    let events = server
        .client
        .ok("GET", "/api/tables/order_events/rows", None)
        .await;
    let events = events.as_array().cloned().unwrap_or_default();
    assert_eq!(events.len(), 1, "{events:?}");
    assert_eq!(events[0]["kind"], json!("decided"));

    // And the workflow's own write to `status` did **not** start a second run:
    // that is the whole job of the tutorial's `only_if`.
    let runs = server
        .client
        .ok("GET", &format!("/api/workflows/{trigger}/runs"), None)
        .await;
    assert_eq!(runs.as_array().map(Vec::len), Some(1), "{runs}");
    Ok(())
}

#[tokio::test]
async fn a_small_order_takes_the_other_arm_and_never_stops() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let trigger = drawn(&mut server).await;

    // £10, one unit: neither test in `classify` is true, so the branch takes its
    // `otherwise` and the run walks to the end without a person.
    let id = submit(&mut server, 10, &[1]).await;

    let run = the_run(&mut server, &trigger).await;
    assert_eq!(run["state"], json!("done"), "{run}");
    assert_eq!(run["current_step"], Value::Null);
    let run_id = run["id"].as_str().expect("a run id").to_owned();
    let detail = server
        .client
        .ok("GET", &format!("/api/runs/{run_id}"), None)
        .await;
    assert_eq!(detail["pending_form"], Value::Null);
    let steps: Vec<&str> = detail["trace"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| t["step"].as_str().unwrap())
        .collect();
    assert_eq!(
        steps,
        vec![
            "load_lines",
            "start_count",
            "per_line",
            "add_line",
            "classify",
            "ship",
            "log"
        ]
    );
    assert_eq!(order(&mut server, id).await["status"], json!("shipped"));
    Ok(())
}

#[tokio::test]
async fn a_rejected_order_takes_the_other_ending() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let trigger = drawn(&mut server).await;
    let id = submit(&mut server, 500, &[1]).await;

    let run = the_run(&mut server, &trigger).await;
    let run_id = run["id"].as_str().expect("a run id").to_owned();
    let answered = server
        .client
        .ok(
            "POST",
            &format!("/api/runs/{run_id}/resume"),
            Some(json!({ "approved": false })),
        )
        .await;
    assert_eq!(answered["state"], json!("done"), "{answered}");
    assert_eq!(order(&mut server, id).await["status"], json!("rejected"));
    Ok(())
}

#[tokio::test]
async fn an_action_steps_settings_cannot_read_the_context_and_the_tutorial_says_so()
-> sc_error::Result<()> {
    // The "trips people up" entry, pinned. A `Set`, a branch guard, a loop's
    // collection and a form's timeout are evaluated by the **engine**, in the
    // scope `workflow_shape` decides, and see `context`; an action's own settings
    // are evaluated by the **action**, in the scope a trigger's settings have,
    // and do not.
    //
    // This test is a promise about a *document*, not an endorsement of the
    // behaviour: decision 8 intends an action's settings to see the run. The day
    // that gap is closed this test fails, and the tutorial's paragraph and
    // §10.3's note have to change with it — which is exactly what it is for.
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(tutorial_trigger()))
        .await;
    let id = created["id"].as_str().expect("an id").to_owned();

    let program = json!({
        "start": "classify",
        "steps": [
            {
                "name": "classify",
                "kind": {
                    "type": "set",
                    "assignments": [{ "target": "large", "formula": "row.total > 100" }]
                },
                "next": { "type": "step", "step": "write" }
            },
            {
                "name": "write",
                "kind": {
                    "type": "action",
                    "action": "update_rows",
                    "configuration": {
                        "table": "orders",
                        "where": "id === row.id",
                        // The formula an admin reaches for, and the one that is
                        // refused.
                        "assignments": { "status": "context.large ? 'big' : 'small'" }
                    }
                },
                "next": { "type": "end" }
            }
        ]
    });
    let (status, body) = server
        .client
        .send(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": program, "description": "probe" })),
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");
    let message = body["error"].as_str().unwrap_or_default();
    assert!(message.contains("unknown identifier `context`"), "{message}");
    assert!(message.contains("step `write`"), "{message}");
    Ok(())
}
