//! Phase 5: the admin API for workflows, driven through the assembled router
//! against a real database (§10.3).
//!
//! This is the milestone's **definition of done, minus the browser**: create a
//! trigger whose body is a workflow, save a program into it, insert a row, watch
//! the run suspend waiting for a person, answer the form the API renders from the
//! step's own declaration, and read the finished context and its trace back.
//!
//! What else is pinned here: a workflow that does not hold together is refused
//! *with every problem at once* and stores nothing; versions are **append-only**,
//! so a revert is a new version rather than a rewrite; `listActions` says which
//! actions the step palette may offer; and the three buttons an admin has for a
//! stuck run — resume, cancel, retry — each answer the run's new state.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::HashMap;
use std::sync::Arc;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode, header};
use sc_auth::SessionStore;
use sc_catalog::Catalog;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{
    AppMounts, CSRF_COOKIE, CSRF_HEADER, ServerConfig, admin_handlers, build_router_with_apps,
    default_js_evaluator, install_triggers, start_workflow_engine,
};
use sc_test_harness::TestDb;
use serde_json::{Value, json};
use tower::ServiceExt;

const SCHEMA: &str = "\
    CREATE TABLE orders (id bigint generated by default as identity primary key, \
        customer text not null, total bigint); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        title text, who text);";

const ADMIN: &str = "admin@example.com";
const PASSWORD: &str = "hunter2pass";

struct Client {
    router: Router,
    cookies: HashMap<String, String>,
}

impl Client {
    async fn send(&mut self, method: &str, path: &str, body: Option<Value>) -> (StatusCode, Value) {
        let mut builder = Request::builder().method(method).uri(path);
        if !self.cookies.is_empty() {
            let jar = self
                .cookies
                .iter()
                .map(|(k, v)| format!("{k}={v}"))
                .collect::<Vec<_>>()
                .join("; ");
            builder = builder.header(header::COOKIE, jar);
        }
        if method != "GET"
            && let Some(csrf) = self.cookies.get(CSRF_COOKIE)
        {
            builder = builder.header(CSRF_HEADER, csrf);
        }
        let request = match body {
            Some(ref b) => builder
                .header(header::CONTENT_TYPE, "application/json")
                .body(Body::from(serde_json::to_vec(b).unwrap()))
                .unwrap(),
            None => builder.body(Body::empty()).unwrap(),
        };
        let response = self.router.clone().oneshot(request).await.unwrap();
        let status = response.status();
        for raw in response.headers().get_all(header::SET_COOKIE) {
            if let Ok(text) = raw.to_str()
                && let Some((name, value)) = text.split(';').next().unwrap_or("").split_once('=')
            {
                self.cookies.insert(name.to_owned(), value.to_owned());
            }
        }
        let bytes = axum::body::to_bytes(response.into_body(), 512 * 1024)
            .await
            .unwrap();
        let value = if bytes.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&bytes).unwrap_or(Value::Null)
        };
        (status, value)
    }

    async fn ok(&mut self, method: &str, path: &str, body: Option<Value>) -> Value {
        let (status, value) = self.send(method, path, body).await;
        assert!(status.is_success(), "{method} {path}: {status} {value}");
        value
    }
}

struct Server {
    client: Client,
    _engine: Arc<sc_workflow::WorkflowEngineTask>,
    _db: TestDb,
}

async fn setup() -> sc_error::Result<Server> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(&format!(
            "DO $$ DECLARE r record; BEGIN \
               FOR r IN SELECT table_schema FROM information_schema.tables \
               WHERE table_name = 'users' AND table_type = 'BASE TABLE' LOOP \
                 EXECUTE format('DROP TABLE IF EXISTS %I.users CASCADE', r.table_schema); \
               END LOOP; END $$; {SCHEMA}"
        ))
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    let agents = sc_server::install_agents(&catalog).await?;
    let models = sc_server::install_models(&catalog, sc_model::DEFAULT_MAX_ROWS).await?;
    let dispatcher = install_triggers(&catalog, default_js_evaluator(), &agents, &models).await?;
    // Only `serve` starts the engine (§10.3, phase 3.3), and this test is
    // standing in for `serve`: without it a workflow trigger refuses by name
    // rather than starting a run, which is a different test.
    let (engine, _handle) = start_workflow_engine(&catalog, &dispatcher);

    let apps = Arc::new(AppMounts::new(catalog.clone()).with_triggers(dispatcher.clone()));
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &ServerConfig::default(),
        apps,
    )?;

    let mut client = Client {
        router,
        cookies: HashMap::new(),
    };
    client.send("GET", "/api/auth/status", None).await;
    let (status, body) = client
        .send(
            "POST",
            "/api/first-user",
            Some(json!({ "email": ADMIN, "password": PASSWORD })),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");

    Ok(Server {
        client,
        _engine: engine,
        _db: db,
    })
}

/// The body that creates a trigger whose body is a **workflow**: no action, no
/// configuration, and `body: "workflow"` as the discriminator.
fn workflow_trigger(name: &str) -> Value {
    json!({
        "name": name,
        "description": "",
        "when": "insert",
        "channel": "orders",
        "only_if": Value::Null,
        "body": "workflow",
        "action": Value::Null,
        "configuration": Value::Null,
        "min_role": Value::Null,
        "enabled": true,
    })
}

/// The order-approval program of the definition of done, in the stored shape:
/// branch on the order's value, ask a person, then record what they said.
fn approval_program() -> Value {
    json!({
        "start": "classify",
        "trace": true,
        "steps": [
            {
                "name": "classify",
                "kind": {
                    "type": "set",
                    "assignments": [{ "target": "large", "formula": "row.total > 100" }]
                },
                "next": {
                    "type": "branch",
                    "arms": [{ "when": "context.large", "step": "approve" }],
                    "otherwise": "record"
                }
            },
            {
                "name": "approve",
                "description": "a person has to say yes",
                "kind": {
                    "type": "user_form",
                    "fields": [
                        { "name": "approved", "type": "bool", "required": true },
                        { "name": "note", "type": "text" }
                    ],
                    "assign_to": "approval"
                },
                "next": { "type": "step", "step": "record" }
            },
            {
                "name": "record",
                "kind": {
                    "type": "set",
                    "assignments": [{ "target": "customer", "formula": "row.customer" }]
                },
                "next": { "type": "end" }
            }
        ]
    })
}

#[tokio::test]
async fn a_workflow_is_drawn_saved_run_suspended_and_answered_over_http() -> sc_error::Result<()> {
    let mut server = setup().await?;

    // --- a new workflow opens on a canvas, not on an error ------------------
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("approval")))
        .await;
    let id = created["id"].as_str().expect("an id").to_owned();
    assert_eq!(created["body"], json!("workflow"));
    assert_eq!(created["action"], Value::Null);

    let opened = server
        .client
        .ok("GET", &format!("/api/workflows/{id}"), None)
        .await;
    // Version 1 was minted by the create: one no-op start step, and no issues —
    // so the first thing an admin sees is a canvas rather than "nothing has been
    // saved yet".
    assert_eq!(opened["version"], json!(1));
    assert_eq!(opened["name"], json!("approval"));
    assert_eq!(opened["channel"], json!("orders"));
    assert_eq!(opened["issues"], json!([]));
    assert_eq!(opened["workflow"]["steps"].as_array().unwrap().len(), 1);
    assert_eq!(opened["versions"].as_array().unwrap().len(), 1);

    // --- save the program: a new version, not a rewrite ---------------------
    let saved = server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": approval_program(), "description": "the approval flow" })),
        )
        .await;
    assert_eq!(saved["version"], json!(2));
    assert_eq!(saved["issues"], json!([]));
    assert_eq!(saved["workflow"]["steps"].as_array().unwrap().len(), 3);
    let history = saved["versions"].as_array().unwrap();
    assert_eq!(history.len(), 2, "append-only: version 1 is still there");
    assert_eq!(history[0]["version"], json!(2));
    assert_eq!(history[0]["description"], json!("the approval flow"));
    assert!(history[0]["created_by"].is_string(), "who saved it");

    // --- an insert on `orders` starts a run, which suspends -----------------
    let (status, _) = server
        .client
        .send(
            "POST",
            "/api/tables/orders/rows",
            Some(json!({ "customer": "Acme", "total": 500 })),
        )
        .await;
    assert_eq!(status, StatusCode::CREATED);

    let runs = server
        .client
        .ok("GET", &format!("/api/workflows/{id}/runs"), None)
        .await;
    let runs = runs.as_array().cloned().unwrap_or_default();
    assert_eq!(runs.len(), 1, "{runs:?}");
    let run = &runs[0];
    assert_eq!(run["state"], json!("waiting"));
    assert_eq!(run["current_step"], json!("approve"));
    // Pinned to the version it started on, and waiting on a person: no clock
    // will wake it.
    assert_eq!(run["subject_version"], json!(2));
    assert_eq!(run["wake_at"], Value::Null);
    let run_id = run["id"].as_str().unwrap().to_owned();

    // --- the form, rendered from the step's own declaration -----------------
    let detail = server
        .client
        .ok("GET", &format!("/api/runs/{run_id}"), None)
        .await;
    let form = &detail["pending_form"];
    assert_eq!(form["assign_to"], json!("approval"));
    let fields = form["fields"].as_array().unwrap();
    assert_eq!(fields.len(), 2);
    // The ordinary `FormField` vocabulary, so the same component that renders a
    // trigger's action settings renders an approval.
    assert_eq!(fields[0]["name"], json!("approved"));
    assert_eq!(fields[0]["type"], json!("bool"));
    assert_eq!(fields[0]["required"], json!(true));
    // The trace up to here: the branch step, then the suspension.
    let trace = detail["trace"].as_array().unwrap();
    assert_eq!(trace.len(), 2, "{trace:?}");
    assert_eq!(trace[0]["step"], json!("classify"));
    assert_eq!(trace[0]["outcome"], json!("ok"));
    assert_eq!(trace[0]["context"]["large"], json!(true));
    assert_eq!(trace[1]["step"], json!("approve"));
    assert_eq!(trace[1]["outcome"], json!("suspended"));

    // --- the workflow is edited twice while the run waits -------------------
    let mut edited = approval_program();
    edited["steps"][2]["kind"]["assignments"] =
        json!([{ "target": "customer", "formula": "'v3'" }]);
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": edited.clone(), "description": "third" })),
        )
        .await;
    edited["steps"][2]["kind"]["assignments"] =
        json!([{ "target": "customer", "formula": "'v4'" }]);
    let latest = server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": edited, "description": "fourth" })),
        )
        .await;
    assert_eq!(latest["version"], json!(4));

    // --- the approval arrives, and the run finishes on **version 2** --------
    let answered = server
        .client
        .ok(
            "POST",
            &format!("/api/runs/{run_id}/resume"),
            Some(json!({ "approved": true, "note": "fine by me" })),
        )
        .await;
    assert_eq!(answered["state"], json!("done"), "{answered}");
    assert_eq!(answered["subject_version"], json!(2));
    assert_eq!(answered["current_step"], Value::Null);
    let context = &answered["context"]["context"];
    assert_eq!(
        context["approval"],
        json!({"approved": true, "note": "fine by me"})
    );
    assert_eq!(
        context["customer"],
        json!("Acme"),
        "version 2's `record` step ran, not version 4's"
    );

    // --- and the trace shows the whole path, in order -----------------------
    let finished = server
        .client
        .ok("GET", &format!("/api/runs/{run_id}"), None)
        .await;
    let steps: Vec<&str> = finished["trace"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| t["step"].as_str().unwrap())
        .collect();
    assert_eq!(steps, vec!["classify", "approve", "record"]);
    assert_eq!(finished["pending_form"], Value::Null);
    Ok(())
}

#[tokio::test]
async fn a_workflow_that_does_not_hold_together_is_refused_with_every_problem()
-> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("broken")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();

    let (status, refused) = server
        .client
        .send(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({
                "workflow": {
                    "start": "a",
                    "steps": [
                        {
                            "name": "a",
                            "kind": { "type": "action", "action": "no_such_action" },
                            "next": { "type": "step", "step": "nowhere" }
                        },
                        {
                            "name": "orphan",
                            "kind": {
                                "type": "set",
                                "assignments": [{ "target": "x", "formula": "row.nonesuch" }]
                            },
                            "next": { "type": "end" }
                        }
                    ]
                }
            })),
        )
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    let message = refused["error"]
        .as_str()
        .or_else(|| refused["message"].as_str())
        .unwrap_or_default()
        .to_owned();
    // Every problem at once, each naming its step: an admin told about one of
    // four fixes it and is told about the next one, which is four round trips to
    // save one workflow.
    for expected in ["no_such_action", "nowhere", "orphan", "nonesuch"] {
        assert!(
            message.contains(expected),
            "{expected} missing from: {message}"
        );
    }

    // And nothing was stored: the workflow is still the empty one the create
    // minted.
    let current = server
        .client
        .ok("GET", &format!("/api/workflows/{id}"), None)
        .await;
    assert_eq!(current["version"], json!(1));
    assert_eq!(current["versions"].as_array().unwrap().len(), 1);
    Ok(())
}

#[tokio::test]
async fn reverting_mints_a_new_version_rather_than_rewriting_history() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("versioned")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();

    let mut program = approval_program();
    program["steps"][2]["kind"]["assignments"] = json!([{ "target": "mark", "formula": "'two'" }]);
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": program.clone(), "description": "two" })),
        )
        .await;
    program["steps"][2]["kind"]["assignments"] =
        json!([{ "target": "mark", "formula": "'three'" }]);
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": program, "description": "three" })),
        )
        .await;

    let reverted = server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}/revert"),
            Some(json!({ "version": 2 })),
        )
        .await;
    // Version **4**, whose steps are version 2's — not a version 2 that has been
    // rewritten, and not version 3 deleted: a run pinned to either still has to
    // be able to load it tomorrow.
    assert_eq!(reverted["version"], json!(4));
    assert_eq!(
        reverted["workflow"]["steps"][2]["kind"]["assignments"][0]["formula"],
        json!("'two'")
    );
    let history = reverted["versions"].as_array().unwrap();
    assert_eq!(history.len(), 4);
    assert_eq!(history[0]["description"], json!("reverted to version 2"));
    assert_eq!(history[1]["description"], json!("three"));
    assert_eq!(history[2]["description"], json!("two"));
    Ok(())
}

#[tokio::test]
async fn a_stuck_run_can_be_cancelled_and_a_failed_one_retried() -> sc_error::Result<()> {
    let mut server = setup().await?;

    // A workflow that waits for a person, so there is something to cancel.
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("stuck")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": approval_program(), "description": "v2" })),
        )
        .await;
    server
        .client
        .ok(
            "POST",
            "/api/tables/orders/rows",
            Some(json!({ "customer": "Acme", "total": 500 })),
        )
        .await;
    let runs = server
        .client
        .ok("GET", &format!("/api/workflows/{id}/runs"), None)
        .await;
    let run_id = runs[0]["id"].as_str().unwrap().to_owned();

    let cancelled = server
        .client
        .ok(
            "POST",
            &format!("/api/runs/{run_id}/cancel"),
            Some(json!({ "reason": "the order was withdrawn" })),
        )
        .await;
    assert_eq!(cancelled["state"], json!("aborted"));
    assert!(
        cancelled["error"].as_str().unwrap().contains("withdrawn"),
        "{cancelled}"
    );
    // The machine state is kept, so the detail screen still shows where it had
    // got to when somebody stopped it.
    assert_eq!(cancelled["current_step"], json!("approve"));

    // Cancelling something that has already stopped is refused, not repeated.
    let (status, _) = server
        .client
        .send("POST", &format!("/api/runs/{run_id}/cancel"), None)
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST);

    // Retrying one that did not fail is refused too, and by name.
    let (status, refused) = server
        .client
        .send("POST", &format!("/api/runs/{run_id}/retry"), None)
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");

    // Filtering the list by state is what the screen does to find stuck runs.
    let aborted = server
        .client
        .ok(
            "GET",
            &format!("/api/workflows/{id}/runs?state=aborted"),
            None,
        )
        .await;
    assert_eq!(aborted.as_array().unwrap().len(), 1);
    let waiting = server
        .client
        .ok(
            "GET",
            &format!("/api/workflows/{id}/runs?state=waiting"),
            None,
        )
        .await;
    assert!(waiting.as_array().unwrap().is_empty());
    Ok(())
}

#[tokio::test]
async fn the_step_palette_is_told_which_actions_it_may_offer() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let actions = server.client.ok("GET", "/api/actions", None).await;
    let actions = actions.as_array().cloned().unwrap_or_default();
    assert!(!actions.is_empty());
    // Every action declares whether the palette may offer it as a step, so the
    // editor never renders a settings form that cannot be completed. The
    // built-ins all can be, on a channel-less workflow and on one with a table.
    for action in &actions {
        assert!(
            action["workflow_step"].is_boolean(),
            "every action says: {action}"
        );
        assert_eq!(
            action["workflow_step"],
            json!(true),
            "the built-ins are all usable as steps: {}",
            action["name"]
        );
    }
    Ok(())
}

#[tokio::test]
async fn the_workflow_endpoints_refuse_a_trigger_that_runs_an_action() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok(
            "POST",
            "/api/triggers",
            Some(json!({
                "name": "plain",
                "description": "",
                "when": "insert",
                "channel": "orders",
                "only_if": Value::Null,
                "action": "insert_row",
                "configuration": { "table": "audit", "values": { "title": "row.customer" } },
                "min_role": Value::Null,
                "enabled": true,
            })),
        )
        .await;
    let id = created["id"].as_str().unwrap().to_owned();
    // Answering an empty canvas here would invite an admin to draw a program
    // nothing would ever run.
    let (status, refused) = server
        .client
        .send("GET", &format!("/api/workflows/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::BAD_REQUEST, "{refused}");
    Ok(())
}

#[tokio::test]
async fn switching_an_action_trigger_to_a_workflow_gives_it_a_canvas() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok(
            "POST",
            "/api/triggers",
            Some(json!({
                "name": "converted",
                "description": "",
                "when": "insert",
                "channel": "orders",
                "only_if": Value::Null,
                "action": "insert_row",
                "configuration": { "table": "audit", "values": { "title": "row.customer" } },
                "min_role": Value::Null,
                "enabled": true,
            })),
        )
        .await;
    let id = created["id"].as_str().unwrap().to_owned();

    // The other way a trigger comes to need a version 1.
    let switched = server
        .client
        .ok(
            "PUT",
            &format!("/api/triggers/{id}"),
            Some(workflow_trigger("converted")),
        )
        .await;
    assert_eq!(switched["body"], json!("workflow"));
    assert_eq!(switched["action"], Value::Null);
    let opened = server
        .client
        .ok("GET", &format!("/api/workflows/{id}"), None)
        .await;
    assert_eq!(opened["version"], json!(1));
    assert_eq!(opened["issues"], json!([]));
    Ok(())
}

#[tokio::test]
async fn deleting_a_workflow_trigger_takes_its_versions_with_it() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("temporary")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": approval_program(), "description": "v2" })),
        )
        .await;

    server
        .client
        .ok("DELETE", &format!("/api/triggers/{id}"), None)
        .await;

    // Append-only is a rule about editing a workflow, not a promise that a
    // deleted trigger leaves rows nobody can reach.
    let (status, _) = server
        .client
        .send("GET", &format!("/api/workflows/{id}"), None)
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);

    // Re-creating a trigger of the same name starts at version 1 again, which is
    // only true if the old versions really went.
    let again = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("temporary")))
        .await;
    let again_id = again["id"].as_str().unwrap().to_owned();
    let opened = server
        .client
        .ok("GET", &format!("/api/workflows/{again_id}"), None)
        .await;
    assert_eq!(opened["version"], json!(1));
    Ok(())
}

/// Phase 6 asks the run detail screen to draw a run's path **on the graph that
/// run actually ran** — which for a run suspended across two edits is not
/// today's steps. So `getWorkflow` takes the version to read, and the two
/// answers are different programs.
#[tokio::test]
async fn a_pinned_version_can_be_read_back_for_the_canvas_a_run_ran_on() -> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("drawn")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();

    // Version 2: the program as first drawn.
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": approval_program(), "description": "as drawn" })),
        )
        .await;
    // Version 3: the same program, edited.
    let mut edited = approval_program();
    edited["steps"][2]["kind"]["assignments"] = json!([{ "target": "mark", "formula": "'later'" }]);
    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": edited, "description": "edited" })),
        )
        .await;

    // With no version asked for, the current one — which is what the editor
    // opens on.
    let current = server
        .client
        .ok("GET", &format!("/api/workflows/{id}"), None)
        .await;
    assert_eq!(current["version"], json!(3));
    assert_eq!(
        current["workflow"]["steps"][2]["kind"]["assignments"][0]["target"],
        json!("mark")
    );

    // With one, that one: the steps a run pinned to version 2 is running, which
    // is the graph its path has to be drawn on. Anything else would be the path
    // of one program drawn on the picture of another.
    let pinned = server
        .client
        .ok("GET", &format!("/api/workflows/{id}?version=2"), None)
        .await;
    assert_eq!(pinned["version"], json!(2));
    assert_eq!(
        pinned["workflow"]["steps"][2]["kind"]["assignments"][0]["target"],
        json!("customer")
    );

    // A version that was never saved is a 404 naming it, not the current one
    // quietly substituted — a canvas showing the wrong program is worse than a
    // canvas that says it cannot be drawn.
    let (status, _) = server
        .client
        .send("GET", &format!("/api/workflows/{id}?version=99"), None)
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    Ok(())
}

/// The triggers list says how big a workflow is and which version is live —
/// because "workflow" on its own tells one row from another not at all, and the
/// alternative was one `getWorkflow` per row from the browser.
#[tokio::test]
async fn the_trigger_list_says_how_big_a_workflow_is_and_which_version_is_live()
-> sc_error::Result<()> {
    let mut server = setup().await?;
    let created = server
        .client
        .ok("POST", "/api/triggers", Some(workflow_trigger("listed")))
        .await;
    let id = created["id"].as_str().unwrap().to_owned();

    // Creating the trigger minted version 1: the empty canvas, one start step.
    let listed = server.client.ok("GET", "/api/triggers", None).await;
    let row = listed
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["id"] == json!(id))
        .unwrap()
        .clone();
    assert_eq!(row["body"], json!("workflow"));
    assert_eq!(row["workflow_version"], json!(1));
    assert_eq!(row["workflow_steps"], json!(1));
    // …and none of the action body's fields, which is what a workflow having no
    // action means.
    assert_eq!(row["action"], Value::Null);

    server
        .client
        .ok(
            "POST",
            &format!("/api/workflows/{id}"),
            Some(json!({ "workflow": approval_program(), "description": "three steps" })),
        )
        .await;
    let listed = server.client.ok("GET", "/api/triggers", None).await;
    let row = listed
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["id"] == json!(id))
        .unwrap()
        .clone();
    assert_eq!(row["workflow_version"], json!(2));
    assert_eq!(row["workflow_steps"], json!(3));

    // An **action** trigger answers null for both rather than 0: it has no
    // workflow, which is not the same as having an empty one.
    server
        .client
        .ok(
            "POST",
            "/api/triggers",
            Some(json!({
                "name": "plain",
                "description": "",
                "when": "none",
                "channel": Value::Null,
                "only_if": Value::Null,
                "action": "run_js_code",
                "configuration": { "code": "return 1;" },
                "min_role": Value::Null,
                "enabled": true,
            })),
        )
        .await;
    let listed = server.client.ok("GET", "/api/triggers", None).await;
    let plain = listed
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == json!("plain"))
        .unwrap()
        .clone();
    assert_eq!(plain["workflow_version"], Value::Null);
    assert_eq!(plain["workflow_steps"], Value::Null);
    Ok(())
}
