/**
 * The Key field form's model.
 *
 * Each claim here is one the browser used to leave to the admin: a key whose
 * target field belongs to the table that *was* selected is a reference to a
 * column of the wrong table; an empty summary field sent as "" is a reference to
 * a column no table has; and a storage type chosen by hand is a column Postgres
 * refuses whenever the guess and the target disagree.
 */

import { describe, expect, it } from "vitest";

import {
  EMPTY_KEY,
  defaultTargetField,
  keyIsComplete,
  keyKindRequest,
  keyStorage,
  reconcileKey,
} from "./keyField";

/** A target table with a primary key, a unique code and a label. */
const people = [
  { name: "id", sql_type: "int8", unique: false, primary_key: true },
  { name: "code", sql_type: "text", unique: true, primary_key: false },
  { name: "full_name", sql_type: "text", unique: false, primary_key: false },
];

describe("defaultTargetField", () => {
  it("prefers the primary key", () => {
    expect(defaultTargetField(people)).toBe("id");
  });

  it("falls back to a unique column, then to the first, on a table with no key", () => {
    const keyless = people.map((f) => ({ ...f, primary_key: false }));
    expect(defaultTargetField(keyless)).toBe("code");
    expect(
      defaultTargetField(keyless.map((f) => ({ ...f, unique: false }))),
    ).toBe("id");
    expect(defaultTargetField([])).toBe("");
  });
});

describe("reconcileKey", () => {
  it("re-defaults a target field the newly chosen table does not have", () => {
    const stale = { target_table: "people", target_field: "isbn", summary_field: "title" };
    expect(reconcileKey(stale, people)).toEqual({
      target_table: "people",
      target_field: "id",
      summary_field: "",
    });
  });

  it("keeps selections the table does have", () => {
    const chosen = { target_table: "people", target_field: "code", summary_field: "full_name" };
    expect(reconcileKey(chosen, people)).toEqual(chosen);
  });
});

describe("keyKindRequest", () => {
  it("omits an unset summary field rather than sending it empty", () => {
    const kind = keyKindRequest({
      target_table: "people",
      target_field: "id",
      summary_field: "",
    });
    expect(kind).toEqual({ type: "key", target_table: "people", target_field: "id" });
    expect("summary_field" in kind).toBe(false);
  });

  it("sends a chosen summary field", () => {
    expect(
      keyKindRequest({
        target_table: "people",
        target_field: "id",
        summary_field: "full_name",
      }),
    ).toEqual({
      type: "key",
      target_table: "people",
      target_field: "id",
      summary_field: "full_name",
    });
  });

  it("never carries a storage type — the server takes it from the target", () => {
    const kind = keyKindRequest({ target_table: "people", target_field: "id", summary_field: "" });
    expect("type_name" in kind).toBe(false);
    expect(Object.keys(kind).sort()).toEqual(["target_field", "target_table", "type"]);
  });
});

describe("keyStorage", () => {
  it("reports the target column's type, without any identity clause", () => {
    expect(
      keyStorage({ target_table: "people", target_field: "id", summary_field: "" }, people),
    ).toBe("int8");
    expect(
      keyStorage({ target_table: "people", target_field: "id", summary_field: "" }, [
        { ...people[0], sql_type: "bigint generated by default as identity" },
      ]),
    ).toBe("bigint");
    expect(
      keyStorage({ target_table: "people", target_field: "code", summary_field: "" }, people),
    ).toBe("text");
  });

  it("reports nothing until a target is chosen", () => {
    expect(keyStorage(EMPTY_KEY, people)).toBe("");
    expect(keyIsComplete(EMPTY_KEY)).toBe(false);
    expect(
      keyIsComplete({ target_table: "people", target_field: "id", summary_field: "" }),
    ).toBe(true);
  });
});
