//! `fetch` **inside a code body**, against a real socket and the real engine.
//!
//! Pinned to bytes on a wire for the reason the `fetch` action's tests are: what
//! can be wrong here is what was sent and what was made of the reply, and a
//! mocked client would assert those about a request that never happened. What is
//! new is that the request is written in **JavaScript by the trigger's author**,
//! so what is really under test is the whole path — the guest's `fetch`, the
//! plan it builds, the host that sends it, and the `Response` the body reads
//! back.
//!
//! Asserted here: a body's GET and POST arrive as written (method, path,
//! headers, body); the response's status, headers and JSON come back to the
//! body; a non-2xx is a value rather than a throw, so a body can branch on it; a
//! request the endpoint never answers fails inside the body's own time limit and
//! is catchable; and what a body fetches can be written to a table in the same
//! run, which is the point of having it here rather than in an action.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;
use std::time::{Duration, Instant};

use sc_action::{ActionContext, Event, EventKind};
use sc_catalog::Catalog;
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{DenoEvaluator, JsEvaluator};
use sc_test_harness::TestDb;
use sc_types::Attrs;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio::sync::oneshot;

use serde_json::{Value as Json, json};

/// Somewhere for a body to put what it fetched.
const SCHEMA: &str = "\
    CREATE TABLE quotes (id bigint generated by default as identity primary key, \
        who text, what text);";

async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// The event every test fires: a directly-run trigger with a payload.
fn fired(payload: Json) -> Event {
    Event::new(EventKind::None)
        .payload(payload)
        .caller(1, Some(json!({ "email": "admin@example.com" })))
}

/// Run `run_js_code` through the registry — the path a firing trigger takes.
async fn run(catalog: &Catalog, event: &Event, code: &str) -> Result<Json> {
    let engine: Arc<dyn JsEvaluator> = Arc::new(DenoEvaluator::new());
    let registry = builtin_actions()?;
    let action = registry.require("run_js_code")?.clone();
    let cfg: Attrs = [("code".to_owned(), json!(code))].into_iter().collect();
    let mut ctx = ActionContext::new(catalog, event, &cfg, "sync").with_evaluator(&engine);
    action.run(&mut ctx).await
}

/// What the listener saw.
struct Received {
    start_line: String,
    headers: Vec<(String, String)>,
    body: String,
}

impl Received {
    fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, v)| v.as_str())
    }
}

/// A listener that answers `count` requests with the same reply, and hands each
/// request it read back through the channel.
async fn serving(
    count: usize,
    status: u16,
    content_type: &str,
    body: &str,
) -> (String, oneshot::Receiver<Vec<Received>>) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/hook", listener.local_addr().unwrap());
    let response = format!(
        "HTTP/1.1 {status} X\r\ncontent-type: {content_type}\r\ncontent-length: {}\r\n\
         connection: close\r\n\r\n{body}",
        body.len()
    );
    let (tx, rx) = oneshot::channel();
    tokio::spawn(async move {
        let mut seen = Vec::new();
        for _ in 0..count {
            let (mut socket, _) = listener.accept().await.unwrap();
            seen.push(read_request(&mut socket).await);
            socket.write_all(response.as_bytes()).await.unwrap();
            socket.flush().await.unwrap();
        }
        let _ = tx.send(seen);
    });
    (url, rx)
}

/// The same, answering **bytes** that are not text — a PNG, as far as anything
/// here is concerned.
async fn serving_bytes(body: Vec<u8>) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/blob", listener.local_addr().unwrap());
    let head = format!(
        "HTTP/1.1 200 OK\r\ncontent-type: application/octet-stream\r\n\
         content-length: {}\r\nconnection: close\r\n\r\n",
        body.len()
    );
    tokio::spawn(async move {
        let (mut socket, _) = listener.accept().await.unwrap();
        read_request(&mut socket).await;
        socket.write_all(head.as_bytes()).await.unwrap();
        socket.write_all(&body).await.unwrap();
        socket.flush().await.unwrap();
    });
    url
}

/// A listener that accepts and then says nothing — a hung endpoint.
async fn hangs() -> String {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/hook", listener.local_addr().unwrap());
    tokio::spawn(async move {
        let (socket, _) = listener.accept().await.unwrap();
        tokio::time::sleep(Duration::from_secs(30)).await;
        drop(socket);
    });
    url
}

/// Read one HTTP request: headers, then exactly `content-length` bytes of body.
async fn read_request(socket: &mut tokio::net::TcpStream) -> Received {
    let mut buf = Vec::new();
    let mut chunk = [0_u8; 1024];
    loop {
        if let Some(head_end) = find(&buf, b"\r\n\r\n") {
            let head = String::from_utf8_lossy(&buf[..head_end]).to_string();
            let wanted = content_length(&head);
            if buf.len() >= head_end + 4 + wanted {
                let mut lines = head.split("\r\n");
                let start_line = lines.next().unwrap_or_default().to_owned();
                let headers = lines
                    .filter_map(|line| line.split_once(": "))
                    .map(|(n, v)| (n.to_ascii_lowercase(), v.to_owned()))
                    .collect();
                let body = String::from_utf8_lossy(&buf[head_end + 4..]).to_string();
                return Received {
                    start_line,
                    headers,
                    body,
                };
            }
        }
        let n = socket.read(&mut chunk).await.unwrap_or(0);
        assert!(n > 0, "the client closed before sending a whole request");
        buf.extend_from_slice(&chunk[..n]);
    }
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

fn content_length(head: &str) -> usize {
    head.split("\r\n")
        .filter_map(|line| line.split_once(": "))
        .find(|(name, _)| name.eq_ignore_ascii_case("content-length"))
        .and_then(|(_, value)| value.trim().parse().ok())
        .unwrap_or(0)
}

#[tokio::test]
async fn a_body_fetches_json_and_reads_the_response() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(1, 200, "application/json", r#"{"who":"Ada","what":"hi"}"#).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"const res = await fetch(payload.url, { headers: { "x-token": "s3cret" } });
           if (!res.ok) throw new Error("unexpected " + res.status);
           const quote = await res.json();
           return {
             status: res.status,
             type: res.headers.get("content-type"),
             who: quote.who,
           };"#,
    )
    .await?;
    assert_eq!(
        result,
        json!({ "status": 200, "type": "application/json", "who": "Ada" })
    );

    let requests = received.await.unwrap();
    assert_eq!(requests.len(), 1);
    // A GET, at the path the body asked for, carrying the header it set and no
    // body at all.
    assert!(
        requests[0].start_line.starts_with("GET /hook "),
        "{}",
        requests[0].start_line
    );
    assert_eq!(requests[0].header("x-token"), Some("s3cret"));
    assert_eq!(requests[0].body, "");
    Ok(())
}

#[tokio::test]
async fn a_body_posts_json_and_writes_what_it_got_back() -> Result<()> {
    // The reason `fetch` belongs in a body rather than only in an action: the
    // response is a value, and the next thing the body does is write it.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(1, 201, "application/json", r#"{"who":"Bob","what":"ta"}"#).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"const res = await fetch(payload.url, {
             method: "POST",
             body: { asking: "for a quote", n: 2 },
           });
           const quote = await res.json();
           const written = await db.quotes.insert({ who: quote.who, what: quote.what });
           return { status: res.status, id: written.id, who: written.who };"#,
    )
    .await?;
    assert_eq!(result["status"], json!(201));
    assert_eq!(result["who"], json!("Bob"));

    let requests = received.await.unwrap();
    assert!(
        requests[0].start_line.starts_with("POST /hook "),
        "{}",
        requests[0].start_line
    );
    // An object body is JSON, with the content type that implies — the one
    // deliberate difference from the web API, where it would have been
    // `[object Object]`.
    assert_eq!(requests[0].header("content-type"), Some("application/json"));
    assert_eq!(requests[0].body, r#"{"asking":"for a quote","n":2}"#);

    // And the row is really there, in the same run that fetched it — read out
    // of the database rather than out of the action's own answer.
    let stored = db
        .client()
        .await?
        .query("SELECT who, what FROM quotes ORDER BY id", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let quotes: Vec<(String, String)> = stored
        .iter()
        .map(|r| (r.get::<_, String>(0), r.get::<_, String>(1)))
        .collect();
    assert_eq!(quotes, vec![("Bob".to_owned(), "ta".to_owned())]);
    Ok(())
}

#[tokio::test]
async fn a_status_the_endpoint_did_not_like_is_a_value_the_body_can_branch_on() -> Result<()> {
    // The web API's rule, and the one that makes a body readable: a 500 is an
    // answer, so the retry or the fallback is written in the body rather than
    // being a trigger that failed.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(2, 503, "text/plain", "busy, try later").await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"let tries = 0;
           let last = null;
           while (tries < 2) {
             tries++;
             const res = await fetch(payload.url);
             if (res.ok) return { tries: tries, body: await res.text() };
             last = { status: res.status, text: await res.text() };
           }
           return { tries: tries, gaveUp: last };"#,
    )
    .await?;
    assert_eq!(
        result,
        json!({ "tries": 2, "gaveUp": { "status": 503, "text": "busy, try later" } })
    );
    assert_eq!(received.await.unwrap().len(), 2, "both tries were sent");
    Ok(())
}

#[tokio::test]
async fn an_endpoint_that_never_answers_fails_inside_the_bodys_own_time_limit() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let url = hangs().await;

    // A request is clamped to what is left of the run, so a body that catches
    // the failure still gets to finish — and the trigger's caller is held for
    // the body's timeout and not for the endpoint's silence.
    let started = Instant::now();
    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"try {
             await fetch(payload.url, { timeout_ms: 60000 });
             return "answered";
           } catch (e) {
             return { failed: e.constructor.name, message: e.message };
           }"#,
    )
    .await?;
    let elapsed = started.elapsed();
    assert_eq!(result["failed"], json!("TypeError"), "{result}");
    assert!(
        result["message"].as_str().unwrap().contains("timed out"),
        "{result}"
    );
    assert!(
        elapsed < Duration::from_secs(15),
        "the minute the body asked for was allowed: {elapsed:?}"
    );
    Ok(())
}

#[tokio::test]
async fn a_response_that_is_not_text_arrives_as_bytes() -> Result<()> {
    // The seam is JSON and JSON has no bytes, so a response that is not valid
    // UTF-8 crosses base64'd — and `res.text()` still answers what a browser's
    // would, which is the same bytes decoded lossily.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let url = serving_bytes(vec![0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a]).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"const res = await fetch(payload.url);
           const asText = res.clone();          // clone before reading, as on the web
           const bytes = await res.bytes();
           return {
             type: res.headers.get("content-type"),
             bytes: Array.from(bytes),
             signature: bytes[1] === 80 && bytes[2] === 78 && bytes[3] === 71,
             text: (await asText.text()).length > 0,
           };"#,
    )
    .await?;
    assert_eq!(
        result["bytes"],
        json!([0x89, 80, 78, 71, 0x0d, 0x0a, 0x1a, 0x0a]),
        "{result}"
    );
    assert_eq!(result["signature"], json!(true));
    assert_eq!(result["type"], json!("application/octet-stream"));
    assert_eq!(result["text"], json!(true), "text() answered nothing");
    Ok(())
}

#[tokio::test]
async fn a_scheme_that_is_not_http_is_refused_by_name() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    // The rule the `fetch` action has, in the place a body would reach for it:
    // "call an endpoint" is not "read a file on the server".
    let result = run(
        &catalog,
        &fired(Json::Null),
        r#"try {
             await fetch("file:///etc/passwd");
             return "read it";
           } catch (e) {
             return e.message;
           }"#,
    )
    .await?;
    assert!(
        result
            .as_str()
            .unwrap()
            .contains("scheme must be http or https"),
        "{result}"
    );
    Ok(())
}
