//! The `run_js_code` action against the real V8 engine (TODO Phase 3, and the
//! "Tables in code" milestone's phase 5).
//!
//! Pinned against a `DenoEvaluator` rather than a stub, because everything that
//! can be wrong here is inside the isolate: whether statements and a `return`
//! actually run, what the event binds and what it deliberately does not, what a
//! throw or a runaway loop does to the caller — and now, the wiring this action
//! gained with `db`: that a body reads and writes its tables at all, that
//! `asUser()` delegates to **this event's** caller rather than to whoever the
//! server is, and that the configured timeout is the bound on a run. A mock
//! evaluator would assert those against an isolate that never existed.
//!
//! The catalog is real too, so the sandbox assertions are made in a process that
//! genuinely has a database — and the `db` assertions in one where the rows are
//! really there afterwards.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;
use std::time::{Duration, Instant};

use sc_action::{ActionContext, Event, EventKind, Trigger, validate_trigger};
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, save_table_meta};
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{DenoEvaluator, JsEvaluator};
use sc_test_harness::TestDb;
use sc_types::Attrs;

use serde_json::{Value as Json, json};

/// One table with one row in it: something for the sandbox to fail to reach.
const SCHEMA: &str = "CREATE TABLE books (id bigint primary key, title text, pages bigint);\
                      INSERT INTO books VALUES (7, 'A Book', 100);";

async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// A table an ownership formula divides: three notes, two of them ada's.
const OWNED_SCHEMA: &str = "\
    CREATE TABLE notes (id bigint generated by default as identity primary key, \
        what text, owner text); \
    INSERT INTO notes (what, owner) VALUES \
        ('ada one', 'ada@example.com'), \
        ('bob one', 'bob@example.com'), \
        ('ada two', 'ada@example.com');";

/// [`OWNED_SCHEMA`], with `owner === user.email` live as the ownership formula —
/// what `asUser()` has to obey and what the trigger's own authority does not.
async fn owned_setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(OWNED_SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    bootstrap_table_meta(&catalog).await?;
    let mut notes = TableMeta::new("notes");
    notes.set_ownership_formula(Some("owner === user.email"));
    save_table_meta(&catalog, &notes).await?;
    assert!(
        catalog.require("notes")?.ownership.is_some(),
        "the formula is live"
    );
    Ok(catalog)
}

/// The event most tests fire for: an insert of a book by a known admin.
fn book_insert() -> Event {
    Event::new(EventKind::Insert)
        .on("books")
        .row(json!({ "id": 7, "title": "A Book", "pages": 100 }))
        .caller(1, Some(json!({ "email": "admin@example.com", "id": 3 })))
}

fn config(code: &str) -> Attrs {
    [("code".to_owned(), json!(code))].into_iter().collect()
}

/// The same, plus the settings a test names explicitly (`timeout_ms`).
fn config_with(code: &str, extra: &[(&str, Json)]) -> Attrs {
    let mut cfg = config(code);
    for (name, value) in extra {
        cfg.insert((*name).to_owned(), value.clone());
    }
    cfg
}

/// Run `run_js_code` through the registry — the path a firing trigger takes.
async fn run(catalog: &Catalog, event: &Event, code: &str) -> Result<Json> {
    run_with(catalog, event, code, &Arc::new(DenoEvaluator::new())).await
}

async fn run_with(
    catalog: &Catalog,
    event: &Event,
    code: &str,
    engine: &Arc<DenoEvaluator>,
) -> Result<Json> {
    run_configured(catalog, event, config(code), engine).await
}

/// Run the action with a configuration built by the caller — the path a test that
/// is about a *setting* rather than about the code takes.
async fn run_configured(
    catalog: &Catalog,
    event: &Event,
    cfg: Attrs,
    engine: &Arc<DenoEvaluator>,
) -> Result<Json> {
    let engine: Arc<dyn JsEvaluator> = engine.clone();
    let registry = builtin_actions()?;
    let action = registry.require("run_js_code")?.clone();
    let mut ctx = ActionContext::new(catalog, event, &cfg, "compute").with_evaluator(&engine);
    action.run(&mut ctx).await
}

#[tokio::test]
async fn code_computes_a_result_from_the_event() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // Statements, a loop, a local declaration and a `return` — everything a
    // formula (one expression) cannot be, which is what this action is for.
    let result = run(
        &catalog,
        &book_insert(),
        "const words = row.title.split(' ');\n\
         let initials = '';\n\
         for (const word of words) { initials += word[0]; }\n\
         return { initials, per_page: row.pages / words.length, by: user.email };",
    )
    .await?;
    assert_eq!(
        result,
        // 100 / 2 is 50, and JSON says so: a JS number that is integral comes
        // back as an integer, not as `50.0`.
        json!({ "initials": "AB", "per_page": 50, "by": "admin@example.com" })
    );

    // The result is whatever JSON the body returns — including a scalar, and
    // including nothing at all (an action that only had an effect).
    assert_eq!(
        run(&catalog, &book_insert(), "return row.id * 6;").await?,
        json!(42)
    );
    assert_eq!(
        run(&catalog, &book_insert(), "const x = 1;").await?,
        Json::Null
    );
    Ok(())
}

#[tokio::test]
async fn the_event_binds_what_it_has_and_nothing_else() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // On an insert `old` is in scope *and null* — a value the code can branch on,
    // which is the whole reason presence and nullity are different things here.
    assert_eq!(
        run(&catalog, &book_insert(), "return old === null;").await?,
        json!(true)
    );
    // On an update it is the row that was replaced.
    let update = Event::new(EventKind::Update)
        .on("books")
        .row(json!({ "id": 7, "title": "A Book", "pages": 120 }))
        .old_row(json!({ "id": 7, "title": "A Book", "pages": 100 }));
    assert_eq!(
        run(&catalog, &update, "return row.pages - old.pages;").await?,
        json!(20)
    );

    // A `none` trigger: the payload it was called with is in scope, and `user` is
    // null when nobody is logged in.
    let called = Event::new(EventKind::None).payload(json!({ "n": 5 }));
    assert_eq!(
        run(
            &catalog,
            &called,
            "return { double: payload.n * 2, who: user };"
        )
        .await?,
        json!({ "double": 10, "who": Json::Null })
    );
    // …and naming a row it does not have is an error naming `row`, not the
    // silent `undefined` that would make the trigger quietly do the wrong thing.
    let err = run(&catalog, &called, "return row.id;").await.unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("compute") && msg.contains("`code`"), "{msg}");
    assert!(msg.contains("row"), "{msg}");
    Ok(())
}

#[tokio::test]
async fn the_sandbox_has_exactly_one_host_surface_and_it_is_tables() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // The bound this action keeps: `db` is the *whole* host API, so a body still
    // cannot reach the network, a subprocess or the disk — even though this
    // process can, and even though the same body can now read the `books` table.
    let probes = [
        "Deno",
        "fetch",
        "require",
        "process",
        "XMLHttpRequest",
        "WebSocket",
        "setTimeout",
        "globalThis.saltcorn",
        "globalThis.books",
    ];
    for probe in probes {
        let code = format!("return typeof {probe} === 'undefined';");
        assert_eq!(
            run(&catalog, &book_insert(), &code).await?,
            json!(true),
            "sandbox leak: {probe}"
        );
    }
    // And the surface that *is* there is reached by name, not by a global per
    // table: `db.books` is a query builder, `books` is nothing.
    assert_eq!(
        run(&catalog, &book_insert(), "return typeof db.books.rows;").await?,
        json!("function")
    );
    // What the event bound is still exactly what it bound.
    assert_eq!(
        run(&catalog, &book_insert(), "return Object.keys(row);").await?,
        json!(["id", "title", "pages"])
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// `db`: the tables (the "Tables in code" milestone, phase 5)
// ---------------------------------------------------------------------------

#[tokio::test]
async fn the_body_reads_and_writes_its_tables_through_db() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // One body that reads, aggregates and writes — the shape the milestone is
    // for, through the action rather than through the host directly.
    let out = run(
        &catalog,
        &book_insert(),
        "const long = db.books.where({ pages: { gte: 100 } }).select(\"id\", \"title\").rows();\n\
         const made = db.books.insert({ id: 8, title: 'Second', pages: 20 });\n\
         db.books.where({ id: 8 }).update({ pages: 21 });\n\
         return { long: long.map((b) => b.title), made: made.title, \
                  pages: db.books.sum('pages'), n: db.books.count() };",
    )
    .await?;
    assert_eq!(
        out,
        // `sum` over a bigint column is a Decimal, and the wire shape of a
        // Decimal is an exact string rather than a float that might not be.
        json!({ "long": ["A Book"], "made": "Second", "pages": "121", "n": 2 })
    );

    // And the write is really there afterwards — the action's result is not the
    // only evidence, because a body that only *said* it wrote would pass that.
    let rows = db
        .client()
        .await?
        .query("SELECT title, pages FROM books ORDER BY id", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let stored: Vec<(String, i64)> = rows
        .iter()
        .map(|r| (r.get::<_, String>(0), r.get::<_, i64>(1)))
        .collect();
    assert_eq!(
        stored,
        vec![("A Book".to_owned(), 100), ("Second".to_owned(), 21)]
    );
    Ok(())
}

#[tokio::test]
async fn as_user_delegates_to_the_event_own_caller() -> Result<()> {
    let db = TestDb::new().await?;
    // A table with an owner column and an ownership formula over it, so
    // delegation has something to divide.
    let catalog = owned_setup(&db).await?;

    // The event was caused by ada, at a role below the table's admin-only floors:
    // an undelegated read is the trigger's own (admin) authority and sees every
    // row, while `asUser()` sees exactly what ada's ownership formula grants.
    let event = Event::new(EventKind::None)
        .payload(Json::Null)
        // The caller object as an event carries it: the id is a uuid, because
        // acting as somebody requires knowing which somebody.
        .caller(
            40,
            Some(json!({
                "id": "6b1c2d64-3f3a-4a52-9a8b-0f4d2b7f1a11",
                "role": 40,
                "email": "ada@example.com",
            })),
        );
    let body = "return { mine: db.asUser().notes.select('what').orderBy('id').rows().map((n) => n.what),\n\
                          all: db.notes.count() };";
    assert_eq!(
        run(&catalog, &event, body).await?,
        json!({ "mine": ["ada one", "ada two"], "all": 3 })
    );

    // A delegated write outside the formula is refused — and catchable, which is
    // §5's "try a delegated write and fall back".
    let out = run(
        &catalog,
        &event,
        "try { db.asUser().notes.insert({ what: 'not mine', owner: 'bob@example.com' }); }\n\
         catch (e) { return { refused: e.message }; }\n\
         return { refused: null };",
    )
    .await?;
    let refused = out["refused"].as_str().unwrap_or_default();
    assert!(!refused.is_empty(), "the delegated insert was allowed");
    // The same insert at the trigger's own authority is what a trigger is for.
    run(
        &catalog,
        &event,
        "return db.notes.insert({ what: 'audited', owner: 'bob@example.com' }).id;",
    )
    .await?;
    Ok(())
}

#[tokio::test]
async fn the_configured_timeout_bounds_the_run_and_is_checked_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let engine = Arc::new(DenoEvaluator::new());

    // 100 ms of a spinning body, and the caller is released with a named error —
    // the engine's own default (5 s) is not what bounded this.
    let started = Instant::now();
    let err = run_configured(
        &catalog,
        &book_insert(),
        config_with("while (true) {}", &[("timeout_ms", json!(100))]),
        &engine,
    )
    .await
    .unwrap_err();
    assert!(err.to_string().contains("timed out"), "{err}");
    assert!(
        started.elapsed() < Duration::from_secs(2),
        "took {:?}",
        started.elapsed()
    );

    // Out of range is refused while the admin is looking at the form, rather
    // than at the firing that would have held its caller for five minutes.
    let registry = builtin_actions()?;
    let trigger = |cfg: Attrs| {
        Trigger::new("compute", EventKind::Insert, "run_js_code")
            .on("books")
            .configuration(cfg)
    };
    for bad in [json!(300_000), json!(0), json!(-1), json!("soon")] {
        let cfg = config_with("return 1;", &[("timeout_ms", bad.clone())]);
        let err = validate_trigger(&catalog, &registry, &trigger(cfg))
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("timeout_ms"), "{bad}: {msg}");
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }
    // In range saves, and so does saying nothing at all.
    let cfg = config_with("return 1;", &[("timeout_ms", json!(30_000))]);
    validate_trigger(&catalog, &registry, &trigger(cfg)).await?;
    validate_trigger(&catalog, &registry, &trigger(config("return 1;"))).await?;
    Ok(())
}

#[tokio::test]
async fn a_failing_body_is_an_application_error_naming_the_trigger() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    for (code, expected) in [
        ("throw new Error('no good');", "no good"),
        ("return row.title.nope();", "not a function"),
        // Syntax is not checkable on save (there is no engine there), so a typo
        // surfaces here — as an error naming the trigger and the setting.
        ("retrun 1;", "SyntaxError"),
    ] {
        let err = run(&catalog, &book_insert(), code).await.unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("compute") && msg.contains("`code`"), "{msg}");
        assert!(msg.contains(expected), "expected `{expected}` in: {msg}");
        // The admin's code failing is a fact about their configuration, not a
        // bug in the server.
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }
    Ok(())
}

#[tokio::test]
async fn a_runaway_body_is_terminated_and_the_engine_survives() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    // The code runtime's per-run timeout, which is the code pool's own and not
    // the formula watchdog's: a code body runs on its own isolates (decision 1),
    // so bounding it does not bound every ownership check in the process. The
    // production default is `DEFAULT_CODE_TIMEOUT`; the test wants it in
    // milliseconds so the assertion below is quick.
    let engine = Arc::new(DenoEvaluator::new().with_code_timeout(Duration::from_millis(100)));

    let started = Instant::now();
    let err = run_with(&catalog, &book_insert(), "while (true) {}", &engine)
        .await
        .unwrap_err();
    let elapsed = started.elapsed();
    let msg = err.to_string();
    assert!(
        msg.contains("timed out") && msg.contains("compute"),
        "{msg}"
    );
    // The caller is released, not held by the loop.
    assert!(elapsed < Duration::from_secs(5), "took {elapsed:?}");

    // And the isolate is usable afterwards: one trigger's mistake does not take
    // the process's only JavaScript engine with it.
    assert_eq!(
        run_with(&catalog, &book_insert(), "return row.id;", &engine).await?,
        json!(7)
    );
    Ok(())
}

#[tokio::test]
async fn a_body_with_no_code_in_it_is_refused_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let registry = builtin_actions()?;

    let trigger = |cfg: Attrs| {
        Trigger::new("compute", EventKind::Insert, "run_js_code")
            .on("books")
            .configuration(cfg)
    };

    // Absent (the generic spec check) and blank (the action's own): both are a
    // trigger that would fire and do nothing.
    for cfg in [Attrs::new(), config("   ")] {
        let err = validate_trigger(&catalog, &registry, &trigger(cfg))
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("compute") && msg.contains("code"), "{msg}");
        assert!(msg.contains("required"), "{msg}");
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }

    // A body that has code in it saves — including on an event with no row,
    // since only the engine can say what a body means.
    validate_trigger(&catalog, &registry, &trigger(config("return row.id;"))).await?;
    let login = Trigger::new("compute", EventKind::Login, "run_js_code")
        .configuration(config("return user.email;"));
    validate_trigger(&catalog, &registry, &login).await?;
    Ok(())
}

/// A trigger configured to run code, in a context with no JavaScript engine at
/// all (client generation, a test harness), must say so rather than skip.
#[tokio::test]
async fn without_an_engine_the_action_fails_by_name() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let registry = builtin_actions()?;
    let action = registry.require("run_js_code")?.clone();
    let event = book_insert();
    let cfg = config("return 1;");
    let mut ctx = ActionContext::new(&catalog, &event, &cfg, "compute");

    let err = action.run(&mut ctx).await.unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("compute") && msg.contains("JavaScript engine"),
        "{msg}"
    );
    Ok(())
}
