//! The `run_js_code` action against the real V8 engine (TODO Phase 3, and the
//! "Tables in code" milestone's phase 5).
//!
//! Pinned against a `DenoEvaluator` rather than a stub, because everything that
//! can be wrong here is inside the isolate: whether statements and a `return`
//! actually run, what the event binds and what it deliberately does not, what a
//! throw or a runaway loop does to the caller — and now, the wiring this action
//! gained with `db`: that a body reads and writes its tables at all, that
//! `asUser()` delegates to **this event's** caller rather than to whoever the
//! server is, and that the configured timeout is the bound on a run. A mock
//! evaluator would assert those against an isolate that never existed.
//!
//! The catalog is real too, so the sandbox assertions are made in a process that
//! genuinely has a database — and the `db` assertions in one where the rows are
//! really there afterwards.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;
use std::time::{Duration, Instant};

use sc_action::{ActionContext, Event, EventKind, Trigger, validate_trigger};
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, save_table_meta};
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{DenoEvaluator, JsEvaluator};
use sc_test_harness::TestDb;
use sc_types::Attrs;

use serde_json::{Value as Json, json};

/// One table with one row in it: something for the sandbox to fail to reach.
const SCHEMA: &str = "CREATE TABLE books (id bigint primary key, title text, pages bigint);\
                      INSERT INTO books VALUES (7, 'A Book', 100);";

async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// A table an ownership formula divides: three notes, two of them ada's.
const OWNED_SCHEMA: &str = "\
    CREATE TABLE notes (id bigint generated by default as identity primary key, \
        what text, owner text); \
    INSERT INTO notes (what, owner) VALUES \
        ('ada one', 'ada@example.com'), \
        ('bob one', 'bob@example.com'), \
        ('ada two', 'ada@example.com');";

/// [`OWNED_SCHEMA`], with `owner === user.email` live as the ownership formula —
/// what `asUser()` has to obey and what the trigger's own authority does not.
async fn owned_setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(OWNED_SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    bootstrap_table_meta(&catalog).await?;
    let mut notes = TableMeta::new("notes");
    notes.set_ownership_formula(Some("owner === user.email"));
    save_table_meta(&catalog, &notes).await?;
    assert!(
        catalog.require("notes")?.ownership.is_some(),
        "the formula is live"
    );
    Ok(catalog)
}

/// The event most tests fire for: an insert of a book by a known admin.
fn book_insert() -> Event {
    Event::new(EventKind::Insert)
        .on("books")
        .row(json!({ "id": 7, "title": "A Book", "pages": 100 }))
        .caller(1, Some(json!({ "email": "admin@example.com", "id": 3 })))
}

fn config(code: &str) -> Attrs {
    [("code".to_owned(), json!(code))].into_iter().collect()
}

/// The same, plus the settings a test names explicitly (`timeout_ms`).
fn config_with(code: &str, extra: &[(&str, Json)]) -> Attrs {
    let mut cfg = config(code);
    for (name, value) in extra {
        cfg.insert((*name).to_owned(), value.clone());
    }
    cfg
}

/// Run `run_js_code` through the registry — the path a firing trigger takes.
async fn run(catalog: &Catalog, event: &Event, code: &str) -> Result<Json> {
    run_with(catalog, event, code, &Arc::new(DenoEvaluator::new())).await
}

async fn run_with(
    catalog: &Catalog,
    event: &Event,
    code: &str,
    engine: &Arc<DenoEvaluator>,
) -> Result<Json> {
    run_configured(catalog, event, config(code), engine).await
}

/// Run the action with a configuration built by the caller — the path a test that
/// is about a *setting* rather than about the code takes.
async fn run_configured(
    catalog: &Catalog,
    event: &Event,
    cfg: Attrs,
    engine: &Arc<DenoEvaluator>,
) -> Result<Json> {
    let engine: Arc<dyn JsEvaluator> = engine.clone();
    let registry = builtin_actions()?;
    let action = registry.require("run_js_code")?.clone();
    let mut ctx = ActionContext::new(catalog, event, &cfg, "compute").with_evaluator(&engine);
    action.run(&mut ctx).await
}

#[tokio::test]
async fn code_computes_a_result_from_the_event() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // Statements, a loop, a local declaration and a `return` — everything a
    // formula (one expression) cannot be, which is what this action is for.
    let result = run(
        &catalog,
        &book_insert(),
        "const words = row.title.split(' ');\n\
         let initials = '';\n\
         for (const word of words) { initials += word[0]; }\n\
         return { initials, per_page: row.pages / words.length, by: user.email };",
    )
    .await?;
    assert_eq!(
        result,
        // 100 / 2 is 50, and JSON says so: a JS number that is integral comes
        // back as an integer, not as `50.0`.
        json!({ "initials": "AB", "per_page": 50, "by": "admin@example.com" })
    );

    // The result is whatever JSON the body returns — including a scalar, and
    // including nothing at all (an action that only had an effect).
    assert_eq!(
        run(&catalog, &book_insert(), "return row.id * 6;").await?,
        json!(42)
    );
    assert_eq!(
        run(&catalog, &book_insert(), "const x = 1;").await?,
        Json::Null
    );
    Ok(())
}

#[tokio::test]
async fn the_event_binds_what_it_has_and_nothing_else() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // On an insert `old` is in scope *and null* — a value the code can branch on,
    // which is the whole reason presence and nullity are different things here.
    assert_eq!(
        run(&catalog, &book_insert(), "return old === null;").await?,
        json!(true)
    );
    // On an update it is the row that was replaced.
    let update = Event::new(EventKind::Update)
        .on("books")
        .row(json!({ "id": 7, "title": "A Book", "pages": 120 }))
        .old_row(json!({ "id": 7, "title": "A Book", "pages": 100 }));
    assert_eq!(
        run(&catalog, &update, "return row.pages - old.pages;").await?,
        json!(20)
    );

    // A `none` trigger: the payload it was called with is in scope, and `user` is
    // null when nobody is logged in.
    let called = Event::new(EventKind::None).payload(json!({ "n": 5 }));
    assert_eq!(
        run(
            &catalog,
            &called,
            "return { double: payload.n * 2, who: user };"
        )
        .await?,
        json!({ "double": 10, "who": Json::Null })
    );
    // …and naming a row it does not have is an error naming `row`, not the
    // silent `undefined` that would make the trigger quietly do the wrong thing.
    let err = run(&catalog, &called, "return row.id;").await.unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("compute") && msg.contains("`code`"), "{msg}");
    assert!(msg.contains("row"), "{msg}");
    Ok(())
}

#[tokio::test]
async fn the_sandbox_has_three_host_surfaces_and_nothing_else() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // The bound this action keeps. There are exactly three ways out of a body —
    // `db`, `fetch` and `fs` — and everything else a JavaScript runtime usually
    // has is still absent: no subprocess, no timers, no second way to the
    // network that would have its own rules, and no path to a *file* except
    // through a store an admin connected.
    let probes = [
        "Deno",
        "process",
        "XMLHttpRequest",
        "WebSocket",
        "EventSource",
        "setTimeout",
        "globalThis.saltcorn",
        "globalThis.books",
        // The disk, except through `fs`: no module and no path, and `fs`
        // itself is a parameter rather than a global, so a body cannot reach
        // another run's stores by taking one off `globalThis`.
        "globalThis.fs",
    ];
    for probe in probes {
        let code = format!("return typeof {probe} === 'undefined';");
        assert_eq!(
            run(&catalog, &book_insert(), &code).await?,
            json!(true),
            "sandbox leak: {probe}"
        );
    }
    // And the surfaces that *are* there are reached by name, not by a global per
    // table: `db.books` is a query builder, `books` is nothing.
    assert_eq!(
        run(&catalog, &book_insert(), "return typeof db.books.rows;").await?,
        json!("function")
    );
    // `fetch` is the web's name for the web's shape, with the two classes that
    // go with it — an author who knows the browser knows this.
    assert_eq!(
        run(
            &catalog,
            &book_insert(),
            "return [typeof fetch, typeof Headers, typeof Response];"
        )
        .await?,
        json!(["function", "function", "function"])
    );
    // It is a **parameter**, not a global: a body cannot reach another run's
    // network by taking one off `globalThis`.
    assert_eq!(
        run(
            &catalog,
            &book_insert(),
            "return typeof globalThis.fetch === 'undefined';"
        )
        .await?,
        json!(true)
    );
    // `fs` is the third, and it is a function because this server has many
    // stores and no default one. This catalog has none connected, so `fs.stores`
    // is empty — and a body that names one is refused when it asks the store for
    // anything, naming the store it could not find.
    assert_eq!(
        run(
            &catalog,
            &book_insert(),
            "return [typeof fs, fs.stores.length];"
        )
        .await?,
        json!(["function", 0]),
        "a server with no connected store has an empty list, not no `fs`"
    );
    let refused = run(
        &catalog,
        &book_insert(),
        r#"try { await fs("nope").open("a.txt").text(); return "read it"; }
           catch (e) { return e.message; }"#,
    )
    .await?;
    assert!(
        refused.as_str().unwrap_or_default().contains("nope"),
        "a store nothing connected cannot be read: {refused}"
    );
    // `require` is the one name a body reaches for that exists and reaches
    // nothing: it is a refusal that says what to write instead, because the
    // first line of eight years of Saltcorn 1 code is a `require` and an admin
    // who pastes one deserves the answer rather than `require is not a
    // function`.
    let said = run(
        &catalog,
        &book_insert(),
        r#"try { require("@saltcorn/data/models/table"); return "loaded it"; }
           catch (e) { return e.message; }"#,
    )
    .await?;
    let said = said.as_str().unwrap_or_default();
    assert!(said.contains("not available in a code body"), "{said}");
    assert!(said.contains("already in scope"), "{said}");
    // What the event bound is still exactly what it bound.
    assert_eq!(
        run(&catalog, &book_insert(), "return Object.keys(row);").await?,
        json!(["id", "title", "pages"])
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// `Table` and `Field`: Saltcorn 1's own API (the "v1 `Table` API" milestone,
// phase 6)
// ---------------------------------------------------------------------------

#[tokio::test]
async fn the_v1_table_is_in_scope_in_a_trigger_and_reads_and_writes() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // The milestone's definition of done, minus its first line — a code body is
    // handed `Table` rather than requiring it (§8), and the `require` that used
    // to fetch it says so by name (above). Everything after that line is v1's
    // own text: a synchronous `findOne`, a v1 `where`, v1 `selopts`, and a
    // write addressed by primary key.
    let out = run(
        &catalog,
        &book_insert(),
        r#"const books = Table.findOne({ name: "books" });
           const recent = await books.getRows({ pages: { gt: 50 } },
                                              { orderBy: "title", limit: 10 });
           await books.updateRow({ pages: recent[0].pages + 1 }, recent[0].id);
           return {
             pk: books.pk_name,
             fields: books.fields.map((f) => f.name),
             label: Field.nameToLabel("published_at"),
             titles: recent.map((b) => b.title),
           };"#,
    )
    .await?;
    assert_eq!(
        out,
        // The metadata half of that answered from the snapshot the run carried:
        // no host call, and nothing awaited.
        json!({
            "pk": "id",
            "fields": ["id", "title", "pages"],
            // v1's `nameToLabel`, which does not capitalise.
            "label": "published at",
            "titles": ["A Book"],
        })
    );

    // And the write is really there afterwards, which is the half of the
    // definition of done the returned value cannot show.
    let rows = db
        .client()
        .await?
        .query("SELECT pages FROM books WHERE id = 7", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    assert_eq!(
        rows[0].get::<_, i64>(0),
        101,
        "the v1 write reached the row"
    );
    Ok(())
}

#[tokio::test]
async fn a_v1_bodys_own_first_line_is_where_it_fails() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // The body's own shadow is legal JavaScript and means what it says: the
    // wrapper compiles a body as a nested function, so a `const Table` of its
    // own is the author's variable and the class is what it was until that
    // line.
    assert_eq!(
        run(
            &catalog,
            &book_insert(),
            r#"const before = Table.findOne("books").pk_name;
               const Table2 = 5;
               return before;"#,
        )
        .await?,
        json!("id")
    );
    // A v1 body's real first line, though, is the one an admin will paste, and
    // it fails on the `require` rather than three lines later on something that
    // is not a class.
    let err = run(
        &catalog,
        &book_insert(),
        r#"const Table = require("@saltcorn/data/models/table");
           return Table.findOne("books").pk_name;"#,
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("not available in a code body"), "{err}");
    assert!(err.contains("delete the line"), "{err}");
    Ok(())
}

// ---------------------------------------------------------------------------
// `db`: the tables (the "Tables in code" milestone, phase 5)
// ---------------------------------------------------------------------------

#[tokio::test]
async fn the_body_reads_and_writes_its_tables_through_db() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    // One body that reads, aggregates and writes — the shape the milestone is
    // for, through the action rather than through the host directly.
    let out = run(
        &catalog,
        &book_insert(),
        "const long = await db.books.where({ pages: { gte: 100 } }).select(\"id\", \"title\").rows();\n\
         const made = await db.books.insert({ id: 8, title: 'Second', pages: 20 });\n\
         await db.books.where({ id: 8 }).update({ pages: 21 });\n\
         return { long: long.map((b) => b.title), made: made.title, \
                  pages: await db.books.sum('pages'), n: await db.books.count() };",
    )
    .await?;
    assert_eq!(
        out,
        // `sum` over a bigint column is a Decimal, and the wire shape of a
        // Decimal is an exact string rather than a float that might not be.
        json!({ "long": ["A Book"], "made": "Second", "pages": "121", "n": 2 })
    );

    // And the write is really there afterwards — the action's result is not the
    // only evidence, because a body that only *said* it wrote would pass that.
    let rows = db
        .client()
        .await?
        .query("SELECT title, pages FROM books ORDER BY id", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let stored: Vec<(String, i64)> = rows
        .iter()
        .map(|r| (r.get::<_, String>(0), r.get::<_, i64>(1)))
        .collect();
    assert_eq!(
        stored,
        vec![("A Book".to_owned(), 100), ("Second".to_owned(), 21)]
    );
    Ok(())
}

/// The writes a model guesses from another ORM — `update(id, values)`,
/// `delete(id)` — are refused naming the call to write instead, with the
/// author's own id and values in it, and touch nothing; the form
/// `describe_code_api` teaches is the one that writes.
#[tokio::test]
async fn a_write_by_id_is_refused_naming_the_where_to_write_instead() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    let err = run(
        &catalog,
        &book_insert(),
        "await db.books.update(row.id, { pages: 5 });",
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(
        err.contains(r#"write db.books.where({ id: 7 }).update({"pages":5})"#),
        "{err}"
    );
    let err = run(&catalog, &book_insert(), "await db.books.delete(row.id);")
        .await
        .unwrap_err()
        .to_string();
    assert!(
        err.contains("write db.books.where({ id: 7 }).delete()"),
        "{err}"
    );
    // Refused even with a `.where()` in front: the second argument is not
    // something the call reads, and silently dropping it would be worse.
    let err = run(
        &catalog,
        &book_insert(),
        "await db.books.where({ id: row.id }).update(row.id, { pages: 5 });",
    )
    .await
    .unwrap_err()
    .to_string();
    assert!(err.contains("takes one argument"), "{err}");

    let untouched = run(
        &catalog,
        &book_insert(),
        "return (await db.books.get(7)).pages;",
    )
    .await?;
    assert_eq!(untouched, json!(100));

    // The reference's own shape.
    let out = run(
        &catalog,
        &book_insert(),
        "return await db.books.where({ id: row.id }).update({ pages: 5 });",
    )
    .await?;
    assert_eq!(out["updated"], json!(1), "{out}");
    let pages = run(
        &catalog,
        &book_insert(),
        "return (await db.books.get(7)).pages;",
    )
    .await?;
    assert_eq!(pages, json!(5));
    Ok(())
}

#[tokio::test]
async fn as_user_delegates_to_the_event_own_caller() -> Result<()> {
    let db = TestDb::new().await?;
    // A table with an owner column and an ownership formula over it, so
    // delegation has something to divide.
    let catalog = owned_setup(&db).await?;

    // The event was caused by ada, at a role below the table's admin-only floors:
    // an undelegated read is the trigger's own (admin) authority and sees every
    // row, while `asUser()` sees exactly what ada's ownership formula grants.
    let event = Event::new(EventKind::None)
        .payload(Json::Null)
        // The caller object as an event carries it: the id is a uuid, because
        // acting as somebody requires knowing which somebody.
        .caller(
            40,
            Some(json!({
                "id": "6b1c2d64-3f3a-4a52-9a8b-0f4d2b7f1a11",
                "role": 40,
                "email": "ada@example.com",
            })),
        );
    let body = "const mine = await db.asUser().notes.select('what').orderBy('id').rows();\n\
                 return { mine: mine.map((n) => n.what), all: await db.notes.count() };";
    assert_eq!(
        run(&catalog, &event, body).await?,
        json!({ "mine": ["ada one", "ada two"], "all": 3 })
    );

    // A delegated write outside the formula is refused — and catchable, which is
    // §5's "try a delegated write and fall back".
    let out = run(
        &catalog,
        &event,
        "try { await db.asUser().notes.insert({ what: 'not mine', owner: 'bob@example.com' }); }\n\
         catch (e) { return { refused: e.message }; }\n\
         return { refused: null };",
    )
    .await?;
    let refused = out["refused"].as_str().unwrap_or_default();
    assert!(!refused.is_empty(), "the delegated insert was allowed");
    // The same insert at the trigger's own authority is what a trigger is for.
    run(
        &catalog,
        &event,
        "return (await db.notes.insert({ what: 'audited', owner: 'bob@example.com' })).id;",
    )
    .await?;
    Ok(())
}

#[tokio::test]
async fn the_configured_timeout_bounds_the_run_and_is_checked_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let engine = Arc::new(DenoEvaluator::new());

    // 100 ms of a spinning body, and the caller is released with a named error —
    // the engine's own default (5 s) is not what bounded this.
    let started = Instant::now();
    let err = run_configured(
        &catalog,
        &book_insert(),
        config_with("while (true) {}", &[("timeout_ms", json!(100))]),
        &engine,
    )
    .await
    .unwrap_err();
    assert!(err.to_string().contains("100 ms time limit"), "{err}");
    assert!(
        started.elapsed() < Duration::from_secs(2),
        "took {:?}",
        started.elapsed()
    );

    // Out of range is refused while the admin is looking at the form, rather
    // than at the firing that would have held its caller for five minutes.
    let registry = builtin_actions()?;
    let trigger = |cfg: Attrs| {
        Trigger::new("compute", EventKind::Insert, "run_js_code")
            .on("books")
            .with_configuration(cfg)
    };
    for bad in [json!(300_000), json!(0), json!(-1), json!("soon")] {
        let cfg = config_with("return 1;", &[("timeout_ms", bad.clone())]);
        let err = validate_trigger(&catalog, &registry, &trigger(cfg))
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("timeout_ms"), "{bad}: {msg}");
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }
    // In range saves, and so does saying nothing at all.
    let cfg = config_with("return 1;", &[("timeout_ms", json!(30_000))]);
    validate_trigger(&catalog, &registry, &trigger(cfg)).await?;
    validate_trigger(&catalog, &registry, &trigger(config("return 1;"))).await?;
    Ok(())
}

#[tokio::test]
async fn a_failing_body_is_an_application_error_naming_the_trigger() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;

    for (code, expected) in [
        ("throw new Error('no good');", "no good"),
        ("return row.title.nope();", "not a function"),
        // Syntax is not checkable on save (there is no engine there), so a typo
        // surfaces here — as an error naming the trigger and the setting.
        ("retrun 1;", "SyntaxError"),
    ] {
        let err = run(&catalog, &book_insert(), code).await.unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("compute") && msg.contains("`code`"), "{msg}");
        assert!(msg.contains(expected), "expected `{expected}` in: {msg}");
        // The admin's code failing is a fact about their configuration, not a
        // bug in the server.
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }
    Ok(())
}

#[tokio::test]
async fn a_runaway_body_is_terminated_and_the_engine_survives() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    // The code runtime's per-run timeout, which is the code pool's own and not
    // the formula watchdog's: a code body runs on its own isolates (decision 1),
    // so bounding it does not bound every ownership check in the process. The
    // production default is `DEFAULT_CODE_TIMEOUT`; the test wants it in
    // milliseconds so the assertion below is quick.
    let engine = Arc::new(DenoEvaluator::new().with_code_timeout(Duration::from_millis(100)));

    let started = Instant::now();
    let err = run_with(&catalog, &book_insert(), "while (true) {}", &engine)
        .await
        .unwrap_err();
    let elapsed = started.elapsed();
    let msg = err.to_string();
    // A body's JS slice is never longer than what is left of its wall clock, so
    // 100 ms of timeout is what stops this one — and the error names the trigger
    // that did it, because it is answered to that trigger's own caller.
    assert!(
        msg.contains("100 ms time limit") && msg.contains("compute"),
        "{msg}"
    );
    // The caller is released, not held by the loop.
    assert!(elapsed < Duration::from_secs(5), "took {elapsed:?}");

    // Given room to spin, the same body meets the *other* clock: a code body may
    // not hold its isolate — which every other trigger's body shares — for a
    // whole second without awaiting anything. Still named, still the trigger's.
    let roomy = Arc::new(DenoEvaluator::new().with_code_timeout(Duration::from_secs(20)));
    let started = Instant::now();
    let msg = run_with(&catalog, &book_insert(), "while (true) {}", &roomy)
        .await
        .unwrap_err()
        .to_string();
    assert!(
        msg.contains("without awaiting anything") && msg.contains("compute"),
        "{msg}"
    );
    assert!(
        started.elapsed() < Duration::from_secs(5),
        "it waited for the wall clock: {:?}",
        started.elapsed()
    );

    // And the isolate is usable afterwards: one trigger's mistake does not take
    // the process's only JavaScript engine with it.
    assert_eq!(
        run_with(&catalog, &book_insert(), "return row.id;", &engine).await?,
        json!(7)
    );
    Ok(())
}

#[tokio::test]
async fn a_body_with_no_code_in_it_is_refused_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let registry = builtin_actions()?;

    let trigger = |cfg: Attrs| {
        Trigger::new("compute", EventKind::Insert, "run_js_code")
            .on("books")
            .with_configuration(cfg)
    };

    // Absent (the generic spec check) and blank (the action's own): both are a
    // trigger that would fire and do nothing.
    for cfg in [Attrs::new(), config("   ")] {
        let err = validate_trigger(&catalog, &registry, &trigger(cfg))
            .await
            .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("compute") && msg.contains("code"), "{msg}");
        assert!(msg.contains("required"), "{msg}");
        assert_eq!(err.kind(), sc_error::ErrorKind::Application, "{msg}");
    }

    // A body that has code in it saves — including on an event with no row,
    // since only the engine can say what a body means.
    validate_trigger(&catalog, &registry, &trigger(config("return row.id;"))).await?;
    let login = Trigger::new("compute", EventKind::Login, "run_js_code")
        .with_configuration(config("return user.email;"));
    validate_trigger(&catalog, &registry, &login).await?;
    Ok(())
}

/// A trigger configured to run code, in a context with no JavaScript engine at
/// all (client generation, a test harness), must say so rather than skip.
#[tokio::test]
async fn without_an_engine_the_action_fails_by_name() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let registry = builtin_actions()?;
    let action = registry.require("run_js_code")?.clone();
    let event = book_insert();
    let cfg = config("return 1;");
    let mut ctx = ActionContext::new(&catalog, &event, &cfg, "compute");

    let err = action.run(&mut ctx).await.unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("compute") && msg.contains("JavaScript engine"),
        "{msg}"
    );
    Ok(())
}

/// Nine rows whose sort key **ties and goes missing**: four share a rank, three
/// have none at all, and the two that are unique sit at either end.
///
/// Both properties are the ones streaming gets wrong. A batch boundary that falls
/// inside a tie serves some of those rows twice and skips the rest unless the
/// order is total; a null compares as neither greater nor smaller than the cursor
/// it is resumed from, so the whole block of them vanishes unless the predicate
/// says where they sort. Nine rows read two at a time straddles both.
const TIED_SCHEMA: &str = "\
    CREATE TABLE entries (id bigint generated by default as identity primary key, \
        label text, rank bigint); \
    INSERT INTO entries (label, rank) VALUES \
        ('a', NULL), ('b', 5), ('c', 5), ('d', 1), ('e', NULL), \
        ('f', 5), ('g', 9), ('h', NULL), ('i', 5);";

async fn tied_setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(TIED_SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

#[tokio::test]
async fn iter_streams_the_same_rows_the_unstreamed_read_answers() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = tied_setup(&db).await?;

    // The claim, in the only form worth making: what an `.iter()` yields is what
    // `.rows()` answers — every row, once, in the same order — for an ordering
    // that ties and for a column that is null in places, in both directions. The
    // comparison is against the *total* order (`.orderBy(rank).orderBy(id)`),
    // because that is the order streaming imposes, and comparing against an order
    // that leaves ties unbroken would be comparing against something the database
    // is free to answer two ways.
    let out = run(
        &catalog,
        &book_insert(),
        "const ids = async (q) => (await q.rows()).map((r) => r.id);\n\
         const walk = async (q, n) => { const out = []; for await (const r of q.iter(n)) out.push(r.id); \
                                  return out; };\n\
         return {\n\
           asc: await ids(db.entries.orderBy('rank').orderBy('id')),\n\
           asc_streamed: await walk(db.entries.orderBy('rank'), 2),\n\
           desc: await ids(db.entries.orderBy('rank', 'desc').orderBy('id')),\n\
           desc_streamed: await walk(db.entries.orderBy('rank', 'desc'), 2),\n\
           by_pk: await ids(db.entries.orderBy('id')),\n\
           by_pk_streamed: await walk(db.entries, 4),\n\
           filtered: await ids(db.entries.where({ rank: 5 }).orderBy('id')),\n\
           filtered_streamed: await walk(db.entries.where({ rank: 5 }), 1),\n\
           capped: await walk(db.entries.orderBy('rank').limit(3), 2),\n\
         };",
    )
    .await?;

    assert_eq!(out["asc_streamed"], out["asc"], "ascending, nulls last");
    assert_eq!(out["desc_streamed"], out["desc"], "descending, nulls first");
    assert_eq!(
        out["by_pk_streamed"], out["by_pk"],
        "no ordering of its own"
    );
    assert_eq!(
        out["filtered_streamed"], out["filtered"],
        "the filter rides along on every batch, one row at a time"
    );
    // Nine rows, none missing and none twice — asserted here as well as against
    // `.rows()`, because two reads that were wrong the same way would agree.
    let asc: Vec<i64> = serde_json::from_value(out["asc_streamed"].clone()).unwrap();
    let mut sorted = asc.clone();
    sorted.sort_unstable();
    assert_eq!(
        sorted,
        (1..=9).collect::<Vec<i64>>(),
        "every row exactly once"
    );
    // The nulls sort last ascending and first descending, so the two directions
    // are not each other's reverse — which is the thing a predicate that quietly
    // dropped the nulls would still get right.
    assert_eq!(&asc[6..], &[1, 5, 8], "the nulls are last, in key order");

    // A `.limit()` bounds the iteration rather than the batch: three rows, and
    // they are the first three of the same order.
    assert_eq!(out["capped"], json!(asc[..3].to_vec()));

    // A narrowed `.select()` is the case the cursor cannot be read off the
    // answer: the rows carry `label` and nothing else, while resuming needs
    // `rank` and the primary key. Both are projected under reserved aliases and
    // dropped again, so what the body sees is exactly what it asked for.
    let out = run(
        &catalog,
        &book_insert(),
        "const rows = [];
         for await (const r of db.entries.select('label').orderBy('rank').iter(2)) rows.push(r);
         return { labels: rows.map((r) => r.label), keys: Object.keys(rows[0]) };",
    )
    .await?;
    assert_eq!(
        out["keys"],
        json!(["label"]),
        "no cursor column leaked into the row"
    );
    assert_eq!(
        out["labels"].as_array().map(Vec::len),
        Some(9),
        "and the stream still walked the whole table: {out}"
    );
    Ok(())
}

#[tokio::test]
async fn iter_pays_one_database_call_per_batch_and_stops_when_the_loop_does() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = tied_setup(&db).await?;

    // The bound a streamed read is really under: the call budget. Nine rows in
    // batches of two is five calls — four full and the short one that ends the
    // stream — and a body that stops after the first row has spent one.
    let out = run(
        &catalog,
        &book_insert(),
        "let n = 0;\n\
         for await (const r of db.entries.iter(2)) n += 1;\n\
         let first = null;\n\
         for await (const r of db.entries.iter(2)) { first = r.id; break; }\n\
         return { n: n, first: first };",
    )
    .await?;
    assert_eq!(out["n"], json!(9));
    assert_eq!(out["first"], json!(1));

    // A batch is a database call like any other, so an iteration is bounded by
    // the call budget rather than by the isolate's memory — which is the trade
    // `.iter()` makes, and the reason a body may walk a table it could never
    // hold. Nine rows one at a time is ten calls; twenty-five walks of it is
    // more than the two hundred a run may spend, and it is stopped there.
    let refused = run(
        &catalog,
        &book_insert(),
        "let n = 0;\n\
         for (let i = 0; i < 25; i++) { for await (const r of db.entries.iter(1)) n += 1; }\n\
         return n;",
    )
    .await
    .expect_err("the budget is spent");
    assert!(
        refused.to_string().contains("database calls in one run"),
        "{refused}"
    );
    Ok(())
}

#[tokio::test]
async fn a_delegated_stream_obeys_the_ownership_formula_or_says_it_cannot() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = owned_setup(&db).await?;
    // Ada, at a role below the table's floors — the same caller delegation is
    // tested with above, because whose rows these are is the whole question.
    let event = Event::new(EventKind::None).payload(Json::Null).caller(
        40,
        Some(json!({
            "id": "6b1c2d64-3f3a-4a52-9a8b-0f4d2b7f1a11",
            "role": 40,
            "email": "ada@example.com",
        })),
    );

    // `owner === user.email` translates, so the database can bound each batch
    // over the rows the caller may see: ada's two notes and no more.
    let out = run(
        &catalog,
        &event,
        "const mine = []; \
         for await (const n of db.asUser().notes.iter(1)) mine.push(n.what); \
         return mine;",
    )
    .await?;
    assert_eq!(out, json!(["ada one", "ada two"]));

    // The trigger's own authority sees all three, which is the same body without
    // the delegation — so the narrowing above is the formula and not an accident
    // of the paging.
    let out = run(
        &catalog,
        &event,
        "const all = []; for await (const n of db.notes.iter(1)) all.push(n.what); return all;",
    )
    .await?;
    assert_eq!(out, json!(["ada one", "bob one", "ada two"]));
    Ok(())
}
