//! The triggers tutorial, executed: every formula `docs/tutorial-triggers.md`
//! asks the reader to type, saved and fired for real.
//!
//! A tutorial is a promise that the words in the boxes work, and the ways it can
//! stop being true are quiet ones: the formula language gains a rule, an action
//! renames a setting, validation tightens. None of those break a test that only
//! reads the markdown — so this one **copies the formulas out of the document**
//! and puts them through `save_trigger` (which is the validator the admin's Save
//! button runs) and then through a real write.
//!
//! What it pins, in the tutorial's own order:
//!
//! - the audit trigger: `done && !old.done` fires on *becoming* done and not on
//!   any later save, and its four field values — including `Date.now()`, which is
//!   why the tutorial's `at` column is a `bigint` and not a `timestamptz`;
//! - the `none` trigger the app exposes: a `where` over the target table naming
//!   `user`, deleting the caller's rows and nobody else's;
//! - the daily one: the same action with a periodic event and its timing.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_action::{
    ATTR_HOUR, ATTR_MINUTE, EventKind, Schedule, Trigger, TriggerDispatcher, bootstrap_triggers,
    save_trigger,
};
use sc_api::rows;
use sc_catalog::{CallerContext, Catalog, TableEvents};
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::DenoEvaluator;
use sc_test_harness::TestDb;
use serde_json::json;

/// The tables the tutorial builds: `tasks` as the reader already has it (the
/// React tutorial's `title`/`done` plus the ownership tutorial's `owner`), and
/// the `task_audit` table step 1 creates — with `at` as a **bigint**, which is
/// the point the tutorial makes about `Date.now()`.
const SCHEMA: &str = "
    CREATE TABLE tasks (id bigint generated by default as identity primary key,
        title text not null, done boolean, owner text);
    CREATE TABLE task_audit (id bigint generated by default as identity primary key,
        task bigint, what text, who text, at bigint);
";

/// Step 2's trigger, verbatim from the document.
fn audit_completed() -> Trigger {
    Trigger::new("audit_completed", EventKind::Update, "insert_row")
        .on("tasks")
        .only_if("done && !old.done")
        .config("table", "task_audit")
        .config(
            "values",
            json!({
                "task": "row.id",
                "what": "'completed: ' + row.title",
                "who": "user ? user.email : 'nobody'",
                "at": "Date.now()"
            }),
        )
}

/// Step 3's trigger, verbatim.
fn archive_done() -> Trigger {
    Trigger::new("archive_done", EventKind::None, "delete_rows")
        .min_role(40)
        .config("table", "tasks")
        .config("where", "done && owner === user.email")
}

/// Step 4's trigger, verbatim.
fn nightly_sweep() -> Trigger {
    Trigger::new("nightly_sweep", EventKind::Daily, "delete_rows")
        .timing(ATTR_HOUR, 3)
        .timing(ATTR_MINUTE, 30)
        .config("table", "task_audit")
        .config("where", "at < Date.now() - 30*24*3600*1000")
}

struct Tutorial {
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    _db: TestDb,
}

impl Tutorial {
    /// The audit rows, oldest first, as `(task, what, who)`.
    async fn audit(&self) -> Result<Vec<(i64, String, String)>> {
        let rows = self
            ._db
            .client()
            .await?
            .query("SELECT task, what, who FROM task_audit ORDER BY id", &[])
            .await
            .map_err(|e| Error::database(e.to_string()))?;
        Ok(rows
            .iter()
            .map(|r| (r.get(0), r.get(1), r.get(2)))
            .collect())
    }

    /// Update a task the way the app does: through the row layer, with the
    /// signed-in member as the caller — which is what makes the audit row know
    /// who ticked the box.
    async fn tick(&self, id: &str, done: bool, member: &str) -> Result<()> {
        let tasks = self.catalog.require("tasks")?;
        let caller = CallerContext::new(40, Some(json!({ "email": member })));
        rows::update_row_ctx(
            &self.catalog,
            &tasks,
            id,
            &json!({ "done": done }),
            Some(&caller),
        )
        .await?;
        Ok(())
    }
}

async fn setup() -> Result<Tutorial> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    bootstrap_triggers(&catalog).await?;

    let registry = Arc::new(builtin_actions()?);
    let dispatcher = Arc::new(
        TriggerDispatcher::new(Arc::clone(&registry))
            .with_evaluator(Arc::new(DenoEvaluator::new())),
    );

    // Saving validates — this is the admin's Save button — and every formula in
    // the tutorial goes through it.
    for trigger in [audit_completed(), archive_done(), nightly_sweep()] {
        save_trigger(&catalog, &registry, &trigger).await?;
    }
    dispatcher.reload(&catalog).await?;
    // Nothing observes a write until the dispatcher is installed; from here the
    // reader's `tasks` table is live.
    catalog.set_table_events(Arc::clone(&dispatcher) as Arc<dyn TableEvents>)?;

    Ok(Tutorial {
        catalog,
        dispatcher,
        _db: db,
    })
}

#[tokio::test]
async fn the_audit_trigger_fires_on_becoming_done_and_only_then() -> Result<()> {
    let t = setup().await?;
    let tasks = t.catalog.require("tasks")?;
    let member = "member@example.com";
    let created = rows::create_row(
        &t.catalog,
        &tasks,
        &json!({ "title": "Draft the report", "done": false, "owner": member }),
    )
    .await?;
    let id = created["id"].as_i64().expect("an id").to_string();
    assert!(t.audit().await?.is_empty(), "creating one audits nothing");

    // Tick it off, as the member, through the app's write path.
    t.tick(&id, true, member).await?;
    let audit = t.audit().await?;
    assert_eq!(audit.len(), 1, "{audit:?}");
    let (task, what, who) = &audit[0];
    assert_eq!(task.to_string(), id);
    // The formula concatenated a literal and the row's title…
    assert_eq!(what, "completed: Draft the report");
    // …and `user` is the member who ticked it, not the server.
    assert_eq!(who, member);

    // Saving an already-done task does not audit again: `!old.done` is what makes
    // the condition "became done" rather than "is done". This is the claim the
    // tutorial makes about untick-and-re-tick, in one direction…
    t.tick(&id, true, member).await?;
    assert_eq!(t.audit().await?.len(), 1);
    // …and the other: unticking is not a completion, and re-ticking is one more.
    t.tick(&id, false, member).await?;
    assert_eq!(t.audit().await?.len(), 1);
    t.tick(&id, true, member).await?;
    assert_eq!(t.audit().await?.len(), 2);
    Ok(())
}

#[tokio::test]
async fn the_none_trigger_archives_the_callers_own_finished_tasks() -> Result<()> {
    let t = setup().await?;
    let tasks = t.catalog.require("tasks")?;
    let member = "member@example.com";
    let other = "member2@example.com";
    for (title, done, owner) in [
        ("Draft the report", true, member),
        ("Book the venue", false, member),
        ("Renew the domain", true, other),
    ] {
        rows::create_row(
            &t.catalog,
            &tasks,
            &json!({ "title": title, "done": done, "owner": owner }),
        )
        .await?;
    }

    // What the app's `POST /api/actions/archive_done` does, with the member as
    // the caller: the same `run_trigger` the admin's Run button calls.
    let caller = CallerContext::new(40, Some(json!({ "email": member })));
    let result = t
        .dispatcher
        .run_trigger(&t.catalog, "archive_done", json!({}), Some(&caller))
        .await?;
    assert_eq!(result["deleted"], json!(1), "{result}");

    // The member's finished task is gone; their unfinished one and the other
    // member's finished one are untouched — `owner === user.email` is doing the
    // selecting.
    let left = rows::list_rows(&t.catalog, &tasks).await?;
    let titles: Vec<&str> = left
        .as_array()
        .expect("an array")
        .iter()
        .filter_map(|r| r["title"].as_str())
        .collect();
    assert_eq!(titles, vec!["Book the venue", "Renew the domain"]);
    Ok(())
}

#[tokio::test]
async fn the_nightly_trigger_is_saved_with_the_timing_the_tutorial_states() -> Result<()> {
    let t = setup().await?;
    // It saved (so the `where` resolves against `task_audit`), and its timing
    // reads back as the 03:30 UTC the document says.
    let stored = t
        .dispatcher
        .triggers()?
        .by_name("nightly_sweep")
        .cloned()
        .expect("the daily trigger is in the live set");
    assert_eq!(
        Schedule::of(&stored)?,
        Some(Schedule::Daily {
            hour: 3,
            minute: 30
        })
    );
    // And it describes itself the way the list does, in UTC.
    assert_eq!(
        Schedule::of(&stored)?.expect("a schedule").to_string(),
        "daily at 03:30 UTC"
    );
    Ok(())
}
