//! Build the table of **embedded `core` catalogues** from `locales/*.json`.
//!
//! The `core` domain ships inside the binary (design decision D4): a server with
//! no database, no file store and no network still has its own messages. That
//! means `include_str!`, and `include_str!` takes a literal path — so something
//! has to turn "whatever is in `locales/`" into a list of literals. Doing it here
//! rather than in a hand-maintained `const` is the difference between adding a
//! locale being *one* act (drop `fr.json` in) and being two, the second of which
//! is the one people forget: a committed catalogue that is never loaded looks
//! exactly like a catalogue that is loaded and empty.
//!
//! The generated file is a single `&[(&str, &str)]` — locale tag, then the file's
//! text — which `crate::core` parses on first use.

use std::error::Error;
use std::fmt::Write as _;
use std::path::Path;

fn main() -> Result<(), Box<dyn Error>> {
    // The directory itself, so a *new* file is noticed; each file below, so an
    // edited one is.
    println!("cargo:rerun-if-changed=locales");

    let dir = Path::new("locales");
    let mut found: Vec<(String, String)> = Vec::new();
    if dir.is_dir() {
        for entry in std::fs::read_dir(dir)? {
            let path = entry?.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            let Some(tag) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
                continue;
            };
            println!("cargo:rerun-if-changed=locales/{name}");
            found.push((tag.to_owned(), name.to_owned()));
        }
    }
    // Sorted so the generated file is stable: an unsorted `read_dir` would churn
    // the build output for no reason.
    found.sort();

    let mut out = String::from(
        "// Generated by build.rs from crates/sc-i18n/locales/*.json — do not edit.\n\
         pub(crate) static CORE_CATALOGUES: &[(&str, &str)] = &[\n",
    );
    for (tag, name) in &found {
        writeln!(
            out,
            "    ({tag:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/locales/{name}\"))),"
        )?;
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR")?).join("core_catalogues.rs");
    std::fs::write(dest, out)?;
    Ok(())
}
