//! An API provider's **configuration**: what an admin sets on the API row of an
//! application, what it changes about the API that is served, and what happens
//! to a setting that is wrong (TODO "API improvements" Phase 3).
//!
//! Three claims, and the third is the reason for the other two:
//!
//! - the settings survive the row an application *is* (§13.2), so a switch an
//!   admin turned on is still on the next time the app mounts;
//! - the GraphQL aggregation switch decides what is **in the schema**, and the
//!   SDL an application's build writes is the schema its mount answers — the two
//!   come from one projection, so they cannot disagree;
//! - and a setting outside the provider's declared spec is refused **on save**,
//!   where the admin can fix it. A misspelled `aggregate` stored happily and read
//!   as nothing is the failure this milestone's switch would otherwise be: a
//!   control that appears to work and does nothing.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_api::{GRAPHQL_CFG_AGGREGATES, GraphqlLimits};
use sc_app::{
    ApiConfig, Application, FrameworkRef, api_provider_config_spec, app_graphql, bootstrap,
    load_application, save_application, validate_api_config,
};
use sc_catalog::{Catalog, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;

/// A parent and a child, which is the smallest schema with both a root
/// aggregate and an aggregate on a relation.
const FIXTURE: &str = "
    CREATE TABLE departments (id bigint generated by default as identity primary key,
                              name text not null);
    CREATE TABLE employees (id bigint generated by default as identity primary key,
                            name text not null,
                            salary bigint,
                            department bigint references departments(id));
";

async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(FIXTURE)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let cat = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;
    bootstrap(&cat).await?;
    Ok(cat)
}

/// The app, with its GraphQL API configured as `api` says.
fn staff_app(api: ApiConfig) -> Application {
    Application::new(
        "Staff",
        "staff",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh"),
    )
    .with_table(TableId("departments".to_owned()))
    .with_table(TableId("employees".to_owned()))
    .with_api(api)
}

#[tokio::test]
async fn the_limits_round_trip_through_save_and_load() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    let limits = GraphqlLimits::new()
        .aggregates(true)
        .max_depth(6)
        .max_complexity(300)
        .row_cap(50)
        .statement_budget(9);
    let app = staff_app(ApiConfig::new("graphql", "/graphql").with_config(limits.to_config()));
    save_application(&cat, &app).await?;

    let loaded = load_application(&cat, app.id).await?.expect("saved app");
    assert_eq!(loaded.apis[0].config, app.apis[0].config);
    // And they are the limits the *provider* is built under, not merely five
    // numbers in a bag: an application's stored configuration is where its
    // bounds come from, rather than the defaults at the call site.
    assert_eq!(GraphqlLimits::from_config(&loaded.apis[0].config), limits);
    Ok(())
}

#[tokio::test]
async fn the_switch_decides_whether_the_aggregates_are_in_the_schema() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // Off — which is what an application that never mentions the setting gets.
    let off = staff_app(ApiConfig::new("graphql", "/graphql"));
    let sdl = app_graphql(&off, &cat)?
        .expect("the app enables graphql")
        .sdl;
    assert!(sdl.contains("type Departments {"), "{sdl}");
    for absent in [
        "departments_aggregate",
        "employees_aggregate",
        "DepartmentsAggregate",
        "EmployeesSelectColumn",
    ] {
        assert!(!sdl.contains(absent), "`{absent}` should be absent:\n{sdl}");
    }

    // On, by the one setting.
    let on = staff_app(ApiConfig::new("graphql", "/graphql").with(GRAPHQL_CFG_AGGREGATES, true));
    let sdl = app_graphql(&on, &cat)?
        .expect("the app enables graphql")
        .sdl;
    assert!(
        sdl.contains("departments_aggregate(where: DepartmentsBoolExp): DepartmentsAggregate!"),
        "{sdl}"
    );
    assert!(
        sdl.contains("employees_aggregate(where: EmployeesBoolExp): EmployeesAggregate!"),
        "{sdl}"
    );
    Ok(())
}

#[tokio::test]
async fn a_setting_outside_the_providers_spec_is_refused_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // The misspelling that would otherwise be a switch nobody notices is off.
    let typo = staff_app(ApiConfig::new("graphql", "/graphql").with("aggregate", true));
    let msg = save_application(&cat, &typo).await.unwrap_err().to_string();
    assert!(msg.contains("aggregate"), "should name the setting: {msg}");
    assert!(msg.contains("graphql"), "should name the provider: {msg}");

    // An ill-typed one is caught the same way, against the same spec.
    let ill_typed =
        staff_app(ApiConfig::new("graphql", "/graphql").with(GRAPHQL_CFG_AGGREGATES, "yes"));
    let msg = save_application(&cat, &ill_typed)
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains(GRAPHQL_CFG_AGGREGATES), "{msg}");
    assert!(msg.contains("bool"), "{msg}");

    // A provider nothing registers has no spec to be configured against, and
    // says so rather than accepting anything.
    let unknown = staff_app(ApiConfig::new("grpc", "/grpc").with("reflection", true));
    let msg = save_application(&cat, &unknown)
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("grpc"), "{msg}");
    assert!(api_provider_config_spec("grpc").is_err());

    // Nothing was written: a refused configuration never becomes a row.
    assert!(sc_app::list_applications(&cat).await?.is_empty());

    // …and the same application with the setting spelled right saves.
    let ok = staff_app(ApiConfig::new("graphql", "/graphql").with(GRAPHQL_CFG_AGGREGATES, true));
    validate_api_config(&ok, &ok.apis[0])?;
    save_application(&cat, &ok).await?;
    assert_eq!(sc_app::list_applications(&cat).await?.len(), 1);
    Ok(())
}
