//! The generated `SKILL.md` (design §13.6): what a coding agent holding this
//! repository is told about the half of the application it cannot see.
//!
//! The property worth a test is not the prose, it is that the tool listing is
//! **derived**: every tool the administration MCP server offers — the composite
//! ones and the ones projected from tagged endpoints — is named in it, grouped
//! by the area flag that governs whether a token is offered it at all. A tool
//! added or tagged without appearing here is a tool a coding agent will not know
//! it has.

use std::sync::Arc;

use sc_api::mcp::{Area, Areas, Projection};
use sc_api::schema_edit::Grants;
use sc_app::{ApiConfig, Application, FrameworkRef, generate_skill};
use sc_catalog::{Catalog, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;

async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

fn blog() -> Application {
    Application::new(
        "My Blog",
        "blog",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh")
            .with("client", "web/src/client.ts"),
    )
    .with_table(TableId("posts".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn the_skill_names_every_tool_the_mcp_server_offers() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let skill = generate_skill(&cat, &blog(), "client.ts");

    // The whole surface, both tiers: the nine composite tools the copilot and the
    // MCP server share, and every endpoint carrying an `.mcp()` tag.
    let composite = sc_app::mcp::tool_set(Grants::all(), Areas::all());
    let admin = sc_api::admin_endpoints();
    let generated: Vec<String> = Projection::all(&admin)
        .map(|p| p.name().to_owned())
        .collect();
    assert!(
        generated.len() >= 15,
        "expected the tagged endpoints, got {generated:?}"
    );
    for name in composite
        .all_names()
        .into_iter()
        .map(str::to_owned)
        .chain(generated)
    {
        assert!(
            skill.contains(&format!("- `{name}` — ")),
            "`{name}` is offered by the MCP server and missing from SKILL.md"
        );
    }

    // Grouped by the flag that decides whether a token sees them at all, so an
    // agent whose `tools/list` is short knows which checkbox is off.
    let (always, triggers, applications) = (
        skill.find("### Always offered").expect("always section"),
        skill
            .find(&format!(
                "### Offered when the token carries `{}`",
                Area::Triggers.key()
            ))
            .expect("triggers section"),
        skill
            .find(&format!(
                "### Offered when the token carries `{}`",
                Area::Applications.key()
            ))
            .expect("applications section"),
    );
    let at = |name: &str| skill.find(&format!("- `{name}` — ")).expect(name);
    assert!(always < at("edit_schema") && at("edit_schema") < triggers);
    assert!(triggers < at("save_trigger") && at("save_trigger") < applications);
    assert!(triggers < at("listWorkflowRuns") && at("listWorkflowRuns") < applications);
    assert!(applications < at("save_api_query"));
    assert!(applications < at("buildApplication"));

    // A generated tool that changes something says which grant it needs, from
    // the tag rather than from prose: `buildApplication` is `allow_edit`.
    assert!(
        skill.contains(
            "- `buildApplication` — Build an application and mount it live (needs `allow_edit`)"
        ),
        "{skill}"
    );
    // ...and a read needs none.
    assert!(
        skill.contains("- `listApplications` — List the applications\n"),
        "{skill}"
    );

    // The summary is the first clause of the description the model is given, not
    // a second description written beside it.
    assert!(skill.contains("- `describe_schema` — Describe the database schema\n"));

    // Tier 3 — the capabilities this server deliberately does not project — is
    // as much of the map as tier 1 and 2.
    assert!(skill.contains("Writing files."));
    assert!(skill.contains("Row data."));

    // It is a skill: front matter naming the application, and the app's own
    // identity in the body.
    assert!(skill.starts_with("---\nname: saltcorn-blog\n"), "{skill}");
    assert!(skill.contains("# The Saltcorn application `My Blog`"));
    assert!(skill.contains("served at `blog`"));
    assert!(skill.contains("`client.ts`"));

    if std::env::var("SC_PRINT_SKILL").is_ok() {
        println!("{skill}");
    }
    Ok(())
}
