//! Phase 10 integration test: an application round-tripping through its
//! `_fd_applications` row, against a real database (design §9, §13.2).
//!
//! An application is created in the admin UI and exists *only* as stored
//! configuration — its row is its whole definition, with nothing to introspect
//! it from. So the three things this asserts are the three things that make that
//! claim true: what is saved comes back identical, the subdomain routing
//! dispatches on cannot be claimed twice, and a database that has never seen
//! Saltcorn grows the table without a migration step.

use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, CspPolicy, FrameworkRef, StaticDir, bootstrap, delete_application,
    list_applications, load_application, load_application_by_subdomain, save_application,
};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;

/// A catalog over a per-test database holding a couple of ordinary tables — the
/// "legacy database" an app's table subset is declared against.
async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null); \
             CREATE TABLE comments (\
               id bigint generated by default as identity primary key, \
               body text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Catalog::init(driver as Arc<dyn DatabaseDriver>).await?;

    // The `store` setting is a pick-list of the stores that exist (§1.6), so an
    // app's framework config is only valid if its store is one of them. The
    // stores these apps name have to actually be defined — which is the point of
    // the change: an app cannot be saved pointing at a store that is not there.
    // They need no directory on disk: saving a definition validates its settings,
    // not its reachability (§1.2).
    sc_catalog::bootstrap_file_stores(&catalog).await?;
    for name in ["apps", "uploads"] {
        sc_catalog::save_file_store(&catalog, &sc_files::FileStoreDef::local(name, "/srv/x"))
            .await?;
    }
    Ok(catalog)
}

/// A `code` framework config that satisfies `code_config_spec` — what the admin
/// UI's form would post back.
fn code_framework() -> FrameworkRef {
    FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/client.ts")
}

/// An application exercising every column: both §9 required extras
/// (description, attributes), a configured framework, both subsets, an API, a
/// static dir, and a non-default CSP.
fn blog() -> Application {
    Application::new("My Blog", "blog", code_framework())
        .description("The company blog")
        .with_table(TableId("posts".to_owned()))
        .with_table(TableId("comments".to_owned()))
        .with_file_store(FileStoreId("uploads".to_owned()))
        .with_api(ApiConfig::new("rest", "/api").with("row_cap", 100))
        .with_static_dir(StaticDir::new(
            "/docs",
            FileStoreId("uploads".to_owned()),
            "handbook",
        ))
        .csp(CspPolicy::strict().directive("img-src", ["'self'", "data:"]))
        .attribute("theme", "dark")
}

#[tokio::test]
async fn an_application_round_trips_through_the_table() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let app = blog();
    save_application(&cat, &app).await?;

    // Everything the admin configured comes back byte-for-byte: the row is the
    // app's only definition, so anything lost here is lost for good.
    let loaded = load_application(&cat, app.id).await?.expect("saved app");
    assert_eq!(loaded, app);

    // Including each API provider's own settings, which are as much part of the
    // app's definition as the framework's: a row that lost them would be an app
    // whose GraphQL aggregates quietly switched themselves off.
    assert_eq!(loaded.apis[0].config["row_cap"], serde_json::json!(100));

    // Including the framework's own settings and the sparse attributes.
    assert_eq!(loaded.framework.config["store"], serde_json::json!("apps"));
    assert_eq!(
        loaded.framework.config["command"],
        serde_json::json!("sh build.sh")
    );
    assert_eq!(loaded.attributes["theme"], serde_json::json!("dark"));
    assert_eq!(
        loaded.csp.header_value(),
        "default-src 'self'; img-src 'self' data:"
    );

    // Subdomain is the routing key, so it is a lookup in its own right.
    let by_subdomain = load_application_by_subdomain(&cat, "blog")
        .await?
        .expect("app on `blog`");
    assert_eq!(by_subdomain.id, app.id);
    assert!(load_application_by_subdomain(&cat, "nope").await?.is_none());

    Ok(())
}

#[tokio::test]
async fn saving_an_existing_application_updates_it_in_place() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let mut app = blog();
    save_application(&cat, &app).await?;

    // Editing in the admin UI saves the same app (same id), it does not add one.
    app.name = "The Blog".to_owned();
    app.description = String::new();
    app.tables = vec![TableId("posts".to_owned())];
    app.apis.push(ApiConfig::new("rest", "/api/v2"));
    save_application(&cat, &app).await?;

    let all = list_applications(&cat).await?;
    assert_eq!(all.len(), 1, "an edit should not create a second row");
    assert_eq!(all[0], app);
    assert_eq!(all[0].name, "The Blog");
    assert_eq!(all[0].description, "");
    assert_eq!(all[0].tables, vec![TableId("posts".to_owned())]);

    // Keeping its own subdomain across an edit is not a clash with itself.
    save_application(&cat, &app).await?;
    assert_eq!(list_applications(&cat).await?.len(), 1);

    Ok(())
}

#[tokio::test]
async fn a_misconfigured_framework_is_rejected_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    // The point of validating on save (§13.3): the admin is standing in front of
    // the form, so this is where a missing setting should be caught — not at
    // build time as a bundler error, and not at serve time as a broken app.
    let missing = Application::new(
        "Blog",
        "blog",
        FrameworkRef::new("code").with("store", "apps"),
    );
    let err = save_application(&cat, &missing).await.unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains("output"), "should name the setting: {msg}");
    assert!(msg.contains("code"), "should name the framework: {msg}");

    // An ill-typed setting is caught the same way.
    let ill_typed = Application::new("Blog", "blog", code_framework().with("source", 42));
    let msg = save_application(&cat, &ill_typed)
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("source"), "{msg}");
    assert!(msg.contains("text"), "{msg}");

    // A framework nothing has registered cannot be configured at all.
    let unknown = Application::new("Blog", "blog", FrameworkRef::new("nextjs"));
    let msg = save_application(&cat, &unknown)
        .await
        .unwrap_err()
        .to_string();
    assert!(msg.contains("nextjs"), "{msg}");

    // Rejected means nothing was written — a bad config never becomes a row.
    assert!(list_applications(&cat).await?.is_empty());

    // And the same app with its settings filled in saves.
    save_application(&cat, &Application::new("Blog", "blog", code_framework())).await?;
    assert_eq!(list_applications(&cat).await?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn a_duplicate_subdomain_is_rejected() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    save_application(&cat, &blog()).await?;

    // A different app (different id) claiming the same subdomain: routing
    // dispatches on the subdomain, so this is not a state the server can serve.
    let clash = Application::new("Other", "blog", code_framework());
    let err = save_application(&cat, &clash).await.unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("blog"),
        "error should name the subdomain: {msg}"
    );
    assert!(
        msg.contains("My Blog"),
        "error should name the app already holding it: {msg}"
    );

    // Rejected means not written: the original still owns the subdomain.
    let apps = list_applications(&cat).await?;
    assert_eq!(apps.len(), 1);
    assert_eq!(apps[0].name, "My Blog");

    // And the constraint is in the database, not only in this pre-check: going
    // around the check with a raw insert of the same subdomain still fails.
    let raw = db
        .client()
        .await?
        .execute(
            "INSERT INTO _fd_applications \
             (id, name, subdomain, framework, extra_frameworks, tables, file_stores, \
              apis, static_dirs, csp, attributes) \
             VALUES ($1, 'Sneaky', 'blog', '{}', '[]', '[]', '[]', '[]', '[]', '{}', '{}')",
            &[&uuid::Uuid::new_v4()],
        )
        .await;
    assert!(raw.is_err(), "the database must enforce unique subdomains");

    Ok(())
}

#[tokio::test]
async fn applications_are_listed_and_deleted() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let blog = blog();
    let shop = Application::new("Shop", "shop", code_framework());
    save_application(&cat, &blog).await?;
    save_application(&cat, &shop).await?;

    // What the server mounts at boot, in a stable order.
    let all = list_applications(&cat).await?;
    let subdomains: Vec<&str> = all.iter().map(|a| a.subdomain.as_str()).collect();
    assert_eq!(subdomains, ["blog", "shop"]);

    // Deleting removes the definition and frees the subdomain.
    assert!(delete_application(&cat, blog.id).await?);
    assert!(load_application(&cat, blog.id).await?.is_none());
    assert!(load_application_by_subdomain(&cat, "blog").await?.is_none());
    assert_eq!(list_applications(&cat).await?.len(), 1);

    // Deleting again is not an error, it just deletes nothing.
    assert!(!delete_application(&cat, blog.id).await?);

    // The subdomain is now free for another app to claim.
    let replacement = Application::new("New Blog", "blog", code_framework());
    save_application(&cat, &replacement).await?;
    let now_serving = load_application_by_subdomain(&cat, "blog").await?.unwrap();
    assert_eq!(now_serving.name, "New Blog");

    Ok(())
}

#[tokio::test]
async fn a_legacy_database_with_no_applications_table_bootstraps_cleanly() -> Result<()> {
    let db = TestDb::new().await?;
    // A database that has never seen Saltcorn: ordinary tables, no `_fd_*`.
    let cat = catalog(&db).await?;
    assert!(cat.get("_fd_applications")?.is_none());
    assert!(cat.get("posts")?.is_some());

    let table = bootstrap(&cat).await?;
    assert_eq!(table.name, "_fd_applications");
    // An `_fd_*` table is hidden from users (§9).
    assert!(table.is_system());
    // It bootstraps empty — no migration, nothing to introspect an app from.
    assert!(list_applications(&cat).await?.is_empty());

    // Idempotent: a second bootstrap is a no-op, not a duplicate-table error,
    // and the apps already saved survive it.
    save_application(&cat, &blog()).await?;
    let again = bootstrap(&cat).await?;
    assert_eq!(again.name, "_fd_applications");
    assert_eq!(list_applications(&cat).await?.len(), 1);

    // The introspected tables of the legacy database are untouched by any of it.
    assert!(cat.get("posts")?.is_some());
    assert!(cat.get("comments")?.is_some());

    Ok(())
}

/// Phase 7: a column a release adds reaches a database that already has
/// applications in it, without a migration framework.
///
/// The situation is the real one: `_fd_applications` exists, it has rows, and
/// then `triggers` is declared. Nothing may be lost and nothing may break — a row
/// written before the column existed reads back as an app that exposes no
/// triggers, which is exactly what it was.
#[tokio::test]
async fn a_column_added_by_a_release_is_reconciled_onto_an_existing_table() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    // Rewind to the previous release's schema: the table as it was before
    // `triggers` was declared, holding an application saved by that release.
    let client = db.client().await?;
    client
        .batch_execute("ALTER TABLE _fd_applications DROP COLUMN triggers")
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let old_id = uuid::Uuid::new_v4();
    client
        .execute(
            "INSERT INTO _fd_applications \
             (id, name, description, subdomain, framework, extra_frameworks, tables, \
              file_stores, apis, static_dirs, csp, attributes) \
             VALUES ($1, 'Old Blog', '', 'old', '{\"name\": \"code\", \"config\": {}}', \
                     '[]', '[]', '[]', '[]', '[]', '{}', '{}')",
            &[&old_id],
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    cat.reload().await?;
    assert!(cat.require("_fd_applications")?.field("triggers").is_none());

    // Booting the new release: the declared column the table does not have is
    // created, and nothing else is touched.
    bootstrap(&cat).await?;
    assert!(cat.require("_fd_applications")?.field("triggers").is_some());

    // The row written by the old release still reads, as the app it was.
    let old = load_application(&cat, sc_app::AppId(old_id))
        .await?
        .expect("the pre-existing application");
    assert_eq!(old.name, "Old Blog");
    assert!(old.triggers.is_empty());

    // And the new column is a column like any other: it round-trips.
    let exposing = blog().with_trigger(sc_app::TriggerRef::new("send_digest"));
    save_application(&cat, &exposing).await?;
    let loaded = load_application(&cat, exposing.id).await?.expect("saved");
    assert_eq!(loaded, exposing);
    assert!(loaded.exposes_trigger("send_digest"));

    // Reconciling is additive only: the second boot changes nothing.
    bootstrap(&cat).await?;
    assert_eq!(list_applications(&cat).await?.len(), 2);
    Ok(())
}

/// Phase 1.1: the application-level half of the file-store reference check.
///
/// This is the half that actually protects a store today — the catalog-level
/// `File`-field scan is inert until the `_fd_fields` overlay exists — so all
/// three ways an application can reference a store need to be caught.
#[tokio::test]
async fn applications_are_found_by_every_way_they_reference_a_store() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;
    save_application(&cat, &blog()).await?;

    // `blog()` references `uploads` twice — as a declared store subset and as a
    // static dir — and `apps` once, as its code framework's source store. All
    // three must find the app, because a store serving an app's source is
    // precisely the one that must not vanish under it.
    assert_eq!(
        sc_app::applications_using_file_store(&cat, "uploads").await?,
        ["application `My Blog`"],
        "the subset and static-dir references"
    );
    assert_eq!(
        sc_app::applications_using_file_store(&cat, "apps").await?,
        ["application `My Blog`"],
        "the framework's `store` setting — where the app's source lives"
    );

    // An app is named once however many ways it references the store, and an
    // unreferenced store is free to delete.
    assert!(
        sc_app::applications_using_file_store(&cat, "scratch")
            .await?
            .is_empty()
    );

    Ok(())
}

/// §1.6: the `store` setting is a pick-list of the stores that exist, so naming
/// one that does not is rejected **on save** — where the admin is still looking
/// at the form — rather than at build time, where it surfaces as a bundler
/// failure, or at serve time, where it is a broken app.
#[tokio::test]
async fn an_unknown_store_is_rejected_on_save() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let app = Application::new(
        "Typo",
        "typo",
        FrameworkRef::new("code")
            // `aps`, not `apps` — exactly the typo this is meant to catch.
            .with("store", "aps")
            .with("output", "web/dist")
            .with("command", "npm run build"),
    );
    let err = save_application(&cat, &app).await.unwrap_err();
    assert!(matches!(err.repr(), sc_error::Repr::Invalid(_)), "{err}");
    let text = err.to_string();
    assert!(text.contains("store"), "should name the setting: {text}");
    // The message lists what is allowed, so the admin can see the near-miss
    // rather than guess.
    assert!(text.contains("apps"), "should list the real stores: {text}");
    assert!(
        list_applications(&cat).await?.is_empty(),
        "nothing was stored"
    );

    // The same app with the store that does exist saves fine.
    let ok = Application::new(
        "Fine",
        "fine",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("output", "web/dist")
            .with("command", "npm run build"),
    );
    save_application(&cat, &ok).await?;
    assert_eq!(list_applications(&cat).await?.len(), 1);

    Ok(())
}

/// A store that is defined but currently unreachable is still a valid choice.
///
/// This is the interaction between §1.6 and §1.2 that would be easy to get
/// wrong: if the pick-list were "connected stores", an app could not be saved
/// while its store's disk was unmounted — so an unrelated outage would block
/// editing an application, and the admin repairing the store could not
/// reconfigure the app that uses it.
#[tokio::test]
async fn a_defined_but_unconnected_store_is_still_choosable() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    // Defined, never connected — nothing was ever mounted at `/srv/x`.
    assert!(cat.file_store("apps")?.is_none());

    let app = Application::new(
        "Blog",
        "blog",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("output", "web/dist")
            .with("command", "npm run build"),
    );
    save_application(&cat, &app).await?;
    assert_eq!(list_applications(&cat).await?.len(), 1);
    Ok(())
}
