//! Phase 9 integration test: an application's typed TypeScript client, generated
//! from its own `Endpoint` set by the same machinery the admin API uses
//! (design §13.1/§13.4).
//!
//! The admin's client is a checked-in artifact guarded by a drift test, because
//! its endpoints are compile-time constants. An app's endpoints depend on which
//! tables it declares, so its client is generated per app and emitted into its
//! source tree at build time — which is what this exercises, against a real
//! catalog.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, FrameworkRef, app_client, app_endpoints, app_providers,
    app_source_from_config, build_application, emit_client,
};
use sc_catalog::{Catalog, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-client-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// A catalog over a per-test database holding `posts` and `secrets`.
async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null); \
             CREATE TABLE secrets (\
               id bigint generated by default as identity primary key, \
               token text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// An app declaring only `posts`, with one REST API at `/api`.
/// The framework config an admin would have filled in; the build settings are
/// resolved from it rather than hand-built (§13.2).
fn code_framework() -> FrameworkRef {
    FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh")
        .with("client", "web/src/client.ts")
}

fn blog() -> Application {
    Application::new("Blog", "blog", code_framework())
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn app_client_is_generated_from_the_apps_own_endpoint_set() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    let endpoints = app_endpoints(&blog(), &cat)?;
    // Four endpoints for the one declared table, plus the app's own login /
    // logout / whoami.
    assert_eq!(endpoints.len(), 4 + 3);

    let ts = app_client(&blog(), &cat)?;

    // The same generator the admin SPA's client comes from: same interface, same
    // factory, typed methods over the app's own tables.
    assert!(ts.contains("export interface ApiClient {"));
    assert!(ts.contains("export function createClient("));
    assert!(ts.contains("listPosts()"));
    assert!(ts.contains("createPosts("));
    assert!(ts.contains("/api/posts"));

    // The app authenticates through its own API, so the client has login too.
    assert!(ts.contains("login("));
    assert!(ts.contains("/api/login"));

    // The app declared only `posts`, so `secrets` — which exists in the catalog —
    // is nowhere in its client (§13.2).
    assert!(
        !ts.contains("Secrets"),
        "undeclared table leaked into client"
    );
    assert!(!ts.contains("secrets"));
    Ok(())
}

#[tokio::test]
async fn an_app_with_no_apis_gets_an_empty_client() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // Declaring a table but enabling no provider exposes nothing.
    let app =
        Application::new("Blog", "blog", code_framework()).with_table(TableId("posts".to_owned()));
    assert!(app_providers(&app, &cat)?.is_empty());
    assert!(app_endpoints(&app, &cat)?.is_empty());

    // The client is still well-formed, just empty of methods.
    let ts = app_client(&app, &cat)?;
    assert!(ts.contains("export interface ApiClient {"));
    assert!(!ts.contains("listPosts"));
    Ok(())
}

#[tokio::test]
async fn a_declared_table_missing_from_the_catalog_is_an_error() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // The app declares a table nobody created: a misconfiguration, not an app
    // with a quietly smaller API.
    let app = Application::new("Blog", "blog", code_framework())
        .with_table(TableId("ghosts".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"));
    let err = app_endpoints(&app, &cat).expect_err("a missing table must fail");
    assert!(err.to_string().contains("ghosts"), "{err}");
    Ok(())
}

#[tokio::test]
async fn an_unknown_api_provider_is_a_configuration_error() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // GraphQL is in the design but not the MVP; enabling it fails loudly rather
    // than serving an app with a silently missing API.
    let app = Application::new("Blog", "blog", code_framework())
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("graphql", "/graphql"));
    let err = app_providers(&app, &cat)
        .map(|_| ())
        .expect_err("an unknown provider must fail");
    let msg = err.to_string();
    assert!(msg.contains("graphql"), "{msg}");
    assert!(msg.contains("rest"), "{msg}");
    Ok(())
}

#[tokio::test]
async fn an_api_mounted_at_the_root_is_refused_before_anything_is_built() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // A provider at `/` claims every path, so the `code` framework's bundle would
    // never be reached — an app that answers `{"error":"no endpoint for /"}` in a
    // browser. `app_providers` is what both building and mounting go through, so
    // this is where an app stored that way is stopped, with the reason.
    let app = Application::new("Blog", "blog", code_framework())
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("rest", "/"));
    let err = app_providers(&app, &cat)
        .map(|_| ())
        .expect_err("a root mount must fail");
    let msg = err.to_string();
    assert!(msg.contains("claims every path"), "{msg}");
    assert!(msg.contains("/api"), "{msg}");

    // The same app on a sub-path is exactly what it meant to be.
    let ok = Application::new("Blog", "blog", code_framework())
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"));
    assert_eq!(app_providers(&ok, &cat)?.len(), 1);
    Ok(())
}

#[tokio::test]
async fn two_providers_projecting_the_same_names_collide() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    // Two REST providers both project the same operation names (`login` first,
    // then the per-table ones); the name keys client methods and dispatch, so the
    // collision is reported rather than silently resolved.
    let app = blog().with_api(ApiConfig::new("rest", "/api/v2"));
    let err = app_endpoints(&app, &cat).expect_err("duplicate endpoint names must fail");
    assert!(err.to_string().contains("two API endpoints named"), "{err}");
    Ok(())
}

#[tokio::test]
async fn the_client_is_emitted_into_the_apps_source_tree_before_the_bundler_runs() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    let tmp = TempDir::new("emit")?;
    let web = tmp.path().join("web");
    std::fs::create_dir_all(web.join("src"))?;

    // A stand-in bundler that proves the client is on disk *before* it runs: it
    // copies the generated client into its output, and `set -e` fails the build
    // if the import target is missing. This is the real contract — the app's
    // source does `import { createClient } from "./client"`, so a client emitted
    // after bundling would be useless.
    let script = web.join("build.sh");
    std::fs::write(
        &script,
        "#!/bin/sh\n\
         set -e\n\
         test -f src/client.ts\n\
         mkdir -p dist\n\
         printf '<!doctype html><div id=root></div>' > dist/index.html\n\
         cp src/client.ts dist/client.js\n",
    )?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755))?;
    }

    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // Every build setting comes from the stored framework config, including
    // where the generated client goes (§13.2) — nothing is hand-built here.
    let source = app_source_from_config(&code_framework())?;
    assert_eq!(source.client_path.as_deref(), Some("web/src/client.ts"));

    let report = build_application(&cat, &blog(), &source, None).await?;

    // The build reports where the client landed...
    assert_eq!(report.client_path.as_deref(), Some("web/src/client.ts"));

    // ...it is really in the app's source tree...
    let emitted = std::fs::read_to_string(web.join("src").join("client.ts"))?;
    assert!(emitted.contains("listPosts()"));
    assert_eq!(emitted, app_client(&blog(), &cat)?);

    // ...and the bundler consumed it: the build only succeeds if the client
    // existed when it ran, and its output carries the client through.
    assert_eq!(report.bundle.len(), 2);
    let bundled = report.bundle.get("client.js").expect("client in bundle");
    assert!(String::from_utf8_lossy(&bundled.bytes).contains("createClient"));
    Ok(())
}

#[tokio::test]
async fn emit_client_is_a_no_op_without_a_client_path() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;

    let tmp = TempDir::new("noclient")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // The `client` setting is optional, and leaving it out of the config is how
    // an admin says "this app does not consume a generated client".
    let no_client = FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh");
    let source = app_source_from_config(&no_client)?;
    assert_eq!(source.client_path, None);
    let written = emit_client(&cat, &source, &app_endpoints(&blog(), &cat)?).await?;
    assert!(written.is_none());

    // Nothing was written to the store.
    let store = cat.require_file_store("apps")?;
    assert!(store.list("").await?.is_empty());
    Ok(())
}
