//! Phase 10 integration test: an application round-tripping through its
//! `_sc_applications` row, against a real database (design §9, §13.2).
//!
//! An application is created in the admin UI and exists *only* as stored
//! configuration — its row is its whole definition, with nothing to introspect
//! it from. So the three things this asserts are the three things that make that
//! claim true: what is saved comes back identical, the subdomain routing
//! dispatches on cannot be claimed twice, and a database that has never seen
//! Saltcorn grows the table without a migration step.

use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, CspPolicy, FrameworkRef, StaticDir, bootstrap, delete_application,
    list_applications, load_application, load_application_by_subdomain, save_application,
};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_test_harness::TestDb;

/// A catalog over a per-test database holding a couple of ordinary tables — the
/// "legacy database" an app's table subset is declared against.
async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null); \
             CREATE TABLE comments (\
               id bigint generated by default as identity primary key, \
               body text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// An application exercising every column: both §9 required extras
/// (description, attributes), a framework with non-string config, extra
/// frameworks, both subsets, an API, a static dir, and a non-default CSP.
fn blog() -> Application {
    Application::new(
        "My Blog",
        "blog",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("minify", true)
            .with("workers", 4),
    )
    .description("The company blog")
    .with_table(TableId("posts".to_owned()))
    .with_table(TableId("comments".to_owned()))
    .with_file_store(FileStoreId("uploads".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
    .with_static_dir(StaticDir::new(
        "/docs",
        FileStoreId("uploads".to_owned()),
        "handbook",
    ))
    .csp(CspPolicy::strict().directive("img-src", ["'self'", "data:"]))
    .attribute("theme", "dark")
}

#[tokio::test]
async fn an_application_round_trips_through_the_table() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let app = blog();
    save_application(&cat, &app).await?;

    // Everything the admin configured comes back byte-for-byte: the row is the
    // app's only definition, so anything lost here is lost for good.
    let loaded = load_application(&cat, app.id).await?.expect("saved app");
    assert_eq!(loaded, app);

    // Including the parts that are not plain strings.
    assert_eq!(loaded.framework.config["minify"], serde_json::json!(true));
    assert_eq!(loaded.framework.config["workers"], serde_json::json!(4));
    assert_eq!(loaded.attributes["theme"], serde_json::json!("dark"));
    assert_eq!(
        loaded.csp.header_value(),
        "default-src 'self'; img-src 'self' data:"
    );

    // Subdomain is the routing key, so it is a lookup in its own right.
    let by_subdomain = load_application_by_subdomain(&cat, "blog")
        .await?
        .expect("app on `blog`");
    assert_eq!(by_subdomain.id, app.id);
    assert!(load_application_by_subdomain(&cat, "nope").await?.is_none());

    Ok(())
}

#[tokio::test]
async fn saving_an_existing_application_updates_it_in_place() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let mut app = blog();
    save_application(&cat, &app).await?;

    // Editing in the admin UI saves the same app (same id), it does not add one.
    app.name = "The Blog".to_owned();
    app.description = String::new();
    app.tables = vec![TableId("posts".to_owned())];
    app.apis.push(ApiConfig::new("rest", "/api/v2"));
    save_application(&cat, &app).await?;

    let all = list_applications(&cat).await?;
    assert_eq!(all.len(), 1, "an edit should not create a second row");
    assert_eq!(all[0], app);
    assert_eq!(all[0].name, "The Blog");
    assert_eq!(all[0].description, "");
    assert_eq!(all[0].tables, vec![TableId("posts".to_owned())]);

    // Keeping its own subdomain across an edit is not a clash with itself.
    save_application(&cat, &app).await?;
    assert_eq!(list_applications(&cat).await?.len(), 1);

    Ok(())
}

#[tokio::test]
async fn a_duplicate_subdomain_is_rejected() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    save_application(&cat, &blog()).await?;

    // A different app (different id) claiming the same subdomain: routing
    // dispatches on the subdomain, so this is not a state the server can serve.
    let clash = Application::new("Other", "blog", FrameworkRef::new("code"));
    let err = save_application(&cat, &clash).await.unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("blog"),
        "error should name the subdomain: {msg}"
    );
    assert!(
        msg.contains("My Blog"),
        "error should name the app already holding it: {msg}"
    );

    // Rejected means not written: the original still owns the subdomain.
    let apps = list_applications(&cat).await?;
    assert_eq!(apps.len(), 1);
    assert_eq!(apps[0].name, "My Blog");

    // And the constraint is in the database, not only in this pre-check: going
    // around the check with a raw insert of the same subdomain still fails.
    let raw = db
        .client()
        .await?
        .execute(
            "INSERT INTO _sc_applications \
             (id, name, subdomain, framework, extra_frameworks, tables, file_stores, \
              apis, static_dirs, csp, attributes) \
             VALUES ($1, 'Sneaky', 'blog', '{}', '[]', '[]', '[]', '[]', '[]', '{}', '{}')",
            &[&uuid::Uuid::new_v4()],
        )
        .await;
    assert!(raw.is_err(), "the database must enforce unique subdomains");

    Ok(())
}

#[tokio::test]
async fn applications_are_listed_and_deleted() -> Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    bootstrap(&cat).await?;

    let blog = blog();
    let shop = Application::new("Shop", "shop", FrameworkRef::new("code"));
    save_application(&cat, &blog).await?;
    save_application(&cat, &shop).await?;

    // What the server mounts at boot, in a stable order.
    let all = list_applications(&cat).await?;
    let subdomains: Vec<&str> = all.iter().map(|a| a.subdomain.as_str()).collect();
    assert_eq!(subdomains, ["blog", "shop"]);

    // Deleting removes the definition and frees the subdomain.
    assert!(delete_application(&cat, blog.id).await?);
    assert!(load_application(&cat, blog.id).await?.is_none());
    assert!(load_application_by_subdomain(&cat, "blog").await?.is_none());
    assert_eq!(list_applications(&cat).await?.len(), 1);

    // Deleting again is not an error, it just deletes nothing.
    assert!(!delete_application(&cat, blog.id).await?);

    // The subdomain is now free for another app to claim.
    let replacement = Application::new("New Blog", "blog", FrameworkRef::new("code"));
    save_application(&cat, &replacement).await?;
    let now_serving = load_application_by_subdomain(&cat, "blog").await?.unwrap();
    assert_eq!(now_serving.name, "New Blog");

    Ok(())
}

#[tokio::test]
async fn a_legacy_database_with_no_applications_table_bootstraps_cleanly() -> Result<()> {
    let db = TestDb::new().await?;
    // A database that has never seen Saltcorn: ordinary tables, no `_sc_*`.
    let cat = catalog(&db).await?;
    assert!(cat.get("_sc_applications")?.is_none());
    assert!(cat.get("posts")?.is_some());

    let table = bootstrap(&cat).await?;
    assert_eq!(table.name, "_sc_applications");
    // An `_sc_*` table is hidden from users (§9).
    assert!(table.is_system());
    // It bootstraps empty — no migration, nothing to introspect an app from.
    assert!(list_applications(&cat).await?.is_empty());

    // Idempotent: a second bootstrap is a no-op, not a duplicate-table error,
    // and the apps already saved survive it.
    save_application(&cat, &blog()).await?;
    let again = bootstrap(&cat).await?;
    assert_eq!(again.name, "_sc_applications");
    assert_eq!(list_applications(&cat).await?.len(), 1);

    // The introspected tables of the legacy database are untouched by any of it.
    assert!(cat.get("posts")?.is_some());
    assert!(cat.get("comments")?.is_some());

    Ok(())
}
