//! The boot path's build: `build_application_if_changed` skips the bundler when
//! the app's source tree, build spec and generated client are what they were at
//! its last successful build, and runs it when any of them moved (design §13.2).
//!
//! The key itself — which git states change it and which do not — is
//! unit-tested in `sc-app`'s `build_cache` module. What needs a database is the
//! generated client: it is emitted before every build, so it must come out
//! byte-identical from an unchanged schema, or the cache would never hit.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, FrameworkRef, app_source_from_config, build_application,
    build_application_if_changed,
};
use sc_catalog::{Catalog, DataField, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::Result;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;
use sc_types::{BasicType, TypeRef};

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-build-cache-it-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

fn git(dir: &Path, args: &[&str]) -> bool {
    std::process::Command::new("git")
        .args(["-c", "commit.gpgsign=false"])
        .args(args)
        .current_dir(dir)
        .env("GIT_AUTHOR_NAME", "t")
        .env("GIT_AUTHOR_EMAIL", "t@example.com")
        .env("GIT_COMMITTER_NAME", "t")
        .env("GIT_COMMITTER_EMAIL", "t@example.com")
        .status()
        .is_ok_and(|s| s.success())
}

/// A committed git repository whose `web/` holds a stand-in bundler. Each run
/// appends a line to `builds.log` at the repository root — outside the source
/// directory, so the log is not itself an input — which is how the test tells
/// a build from a reuse without trusting the report.
fn write_repo(root: &Path) -> Result<()> {
    let web = root.join("web");
    std::fs::create_dir_all(web.join("src"))?;
    std::fs::write(web.join("src").join("main.ts"), "import './client';\n")?;
    std::fs::write(
        web.join("build.sh"),
        "#!/bin/sh\n\
         set -e\n\
         echo built >> ../builds.log\n\
         mkdir -p dist\n\
         cat src/main.ts > dist/index.html\n",
    )?;
    std::fs::write(root.join(".gitignore"), "dist\nbuilds.log\n")?;
    assert!(git(root, &["init", "-q"]));
    assert!(git(root, &["add", "-A"]));
    assert!(git(root, &["commit", "-q", "-m", "init"]));
    Ok(())
}

fn builds(root: &Path) -> usize {
    std::fs::read_to_string(root.join("builds.log"))
        .map(|log| log.lines().count())
        .unwrap_or(0)
}

async fn catalog(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

fn blog() -> Application {
    Application::new(
        "Blog",
        "blog",
        FrameworkRef::new("code")
            .with("store", "apps")
            .with("source", "web")
            .with("output", "web/dist")
            .with("command", "sh build.sh")
            .with("client", "web/src/client.ts"),
    )
    .with_table(TableId("posts".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn an_unchanged_app_is_not_rebuilt_and_a_changed_one_is() -> Result<()> {
    let tmp = TempDir::new("reuse")?;
    let root = tmp.path();
    if !git(root, &["--version"]) {
        eprintln!("skipping: git is not installed");
        return Ok(());
    }
    write_repo(root)?;

    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", root)?))?;
    let app = blog();
    let source = app_source_from_config(&app.framework)?;

    // The first boot builds: there is no stamp yet. The generated client is new,
    // untracked and not ignored, so it is part of the key from here on.
    let first = build_application_if_changed(&cat, &app, &source, None).await?;
    assert!(!first.reused);
    assert_eq!(builds(root), 1);

    // The second boot does not — though the client was emitted again, byte for
    // byte — and serves the same bundle.
    let second = build_application_if_changed(&cat, &app, &source, None).await?;
    assert!(second.reused, "nothing changed, so nothing is rebuilt");
    assert_eq!(builds(root), 1);
    assert_eq!(second.bundle.len(), first.bundle.len());
    assert_eq!(second.client_path.as_deref(), Some("web/src/client.ts"));

    // An uncommitted edit is a change.
    std::fs::write(
        root.join("web/src/main.ts"),
        "import './client'; // edited\n",
    )?;
    assert!(
        !build_application_if_changed(&cat, &app, &source, None)
            .await?
            .reused
    );
    assert_eq!(builds(root), 2);
    assert!(
        build_application_if_changed(&cat, &app, &source, None)
            .await?
            .reused
    );

    // So is a schema change, which reaches the build only through the client.
    cat.create_field(
        "posts",
        &DataField::plain("body", TypeRef::Basic(BasicType::Text)),
    )
    .await?;
    assert!(
        !build_application_if_changed(&cat, &app, &source, None)
            .await?
            .reused
    );
    assert_eq!(builds(root), 3);

    // A missing output directory is rebuilt whatever the stamp says.
    std::fs::remove_dir_all(root.join("web/dist"))?;
    assert!(
        !build_application_if_changed(&cat, &app, &source, None)
            .await?
            .reused
    );
    assert_eq!(builds(root), 4);

    // And an explicit build always runs the bundler.
    let forced = build_application(&cat, &app, &source, None).await?;
    assert!(!forced.reused);
    assert_eq!(builds(root), 5);
    Ok(())
}
