//! What an application that enables the **GraphQL provider** gets in its source
//! tree (TODO "GraphQL API" Phase 8).
//!
//! Three claims, and each is asserted where it can actually fail:
//!
//! - the build writes `src/saltcorn/schema.graphql` and `src/saltcorn/graphql.ts`
//!   **for an app that enables the provider, and only for one**;
//! - the schema is regenerated on every build, so a column added in the admin UI
//!   is in the SDL the app type-checks against at the next build, with nobody
//!   exporting an SDL by hand;
//! - and the whole thing **type-checks**: a page that runs a query with a
//!   constrained child aggregate through the generated client compiles under the
//!   project's own `tsc --noEmit`. That last one needs a real Node toolchain, so
//!   it skips when `npm` is not on `PATH` — and runs by default everywhere else,
//!   because a test nobody runs proves nothing.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, FrameworkRef, app_source_from_config, build_application,
    emit_react_runtime, scaffold_app,
};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;

/// A department per manager and employees under it: the milestone's own example,
/// and the smallest schema with an inverse relation to aggregate over.
const FIXTURE: &str = "
    CREATE TABLE departments (id bigint generated by default as identity primary key,
                              name text not null);
    CREATE TABLE employees (id bigint generated by default as identity primary key,
                            name text not null,
                            salary bigint,
                            department bigint references departments(id));
";

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-graphql-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

async fn catalog(db: &TestDb) -> sc_error::Result<Catalog> {
    db.client()
        .await?
        .batch_execute(FIXTURE)
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// The app both providers are enabled on: REST at `/api`, GraphQL at `/graphql`.
fn staff_app(apis: Vec<ApiConfig>) -> Application {
    let mut app = Application::new(
        "Staff",
        "staff",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "staff"),
    )
    .with_table(TableId("departments".to_owned()))
    .with_table(TableId("employees".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()));
    for api in apis {
        app = app.with_api(api);
    }
    app
}

fn both_providers() -> Vec<ApiConfig> {
    vec![
        ApiConfig::new("rest", "/api"),
        ApiConfig::new("graphql", "/graphql"),
    ]
}

/// Whether a Node toolchain is available to type-check with.
fn npm_available() -> bool {
    std::env::var_os("PATH")
        .map(|paths| {
            std::env::split_paths(&paths)
                .any(|dir| dir.join("npm").is_file() || dir.join("npm.cmd").is_file())
        })
        .unwrap_or(false)
}

#[tokio::test]
async fn the_scaffold_writes_the_graphql_client_and_schema() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let tmp = TempDir::new("scaffold")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = staff_app(both_providers());
    scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("staff");

    // The SDL of the schema this app will actually serve, beside the REST client
    // rather than in place of it: the two providers coexist, and so do the two
    // generated clients.
    let sdl = std::fs::read_to_string(project.join("src/saltcorn/schema.graphql"))?;
    assert!(sdl.starts_with("# Schema generated by Saltcorn"), "{sdl}");
    assert!(sdl.contains("type Departments {"), "{sdl}");
    // The milestone's motivating field: a constrained aggregate over the child
    // relation, right there in the contract the app type-checks against.
    assert!(
        sdl.contains("employees_aggregate(where: EmployeesBoolExp): EmployeesAggregate!"),
        "{sdl}"
    );

    let client = std::fs::read_to_string(project.join("src/saltcorn/graphql.ts"))?;
    assert!(
        client.contains(r#"GRAPHQL_ENDPOINT = "/graphql""#),
        "{client}"
    );
    // Dependency-free (decision 7) and CSRF-carrying, like the REST client.
    assert!(!client.contains("\nimport "), "{client}");
    assert!(client.contains("x-csrf-token"), "{client}");
    assert!(project.join("src/saltcorn/client.ts").is_file());

    // `gql.tada` is *configured* against the emitted SDL — a language-service
    // plugin, so nothing was added to `package.json` to satisfy it.
    let tsconfig = std::fs::read_to_string(project.join("tsconfig.json"))?;
    assert!(tsconfig.contains("gql.tada/ts-plugin"), "{tsconfig}");
    assert!(
        tsconfig.contains("./src/saltcorn/schema.graphql"),
        "{tsconfig}"
    );
    let package = std::fs::read_to_string(project.join("package.json"))?;
    assert!(!package.contains("gql.tada"), "{package}");
    assert!(!package.contains("graphql"), "{package}");
    Ok(())
}

#[tokio::test]
async fn an_app_without_the_provider_gets_no_schema_at_all() -> sc_error::Result<()> {
    // A `schema.graphql` in the tree of an app that serves no GraphQL is a file
    // every editor would believe and no server would honour.
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let tmp = TempDir::new("restonly")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = staff_app(vec![ApiConfig::new("rest", "/api")]);
    let report = scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("staff");

    assert!(!project.join("src/saltcorn/schema.graphql").exists());
    assert!(!project.join("src/saltcorn/graphql.ts").exists());
    assert!(project.join("src/saltcorn/client.ts").is_file());
    assert!(
        !report
            .files
            .iter()
            .any(|f| f.contains("graphql") || f.contains("schema.graphql")),
        "{:?}",
        report.files
    );
    let tsconfig = std::fs::read_to_string(project.join("tsconfig.json"))?;
    assert!(!tsconfig.contains("gql.tada"), "{tsconfig}");
    Ok(())
}

#[tokio::test]
async fn the_schema_is_rewritten_on_every_build() -> sc_error::Result<()> {
    // The reason the SDL is generated rather than exported once: an admin adds a
    // column in the admin UI, and the app's queries are type-checked against it
    // at the next build with nobody running an export.
    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let tmp = TempDir::new("rebuild")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = staff_app(both_providers());
    scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("staff");
    let before = std::fs::read_to_string(project.join("src/saltcorn/schema.graphql"))?;
    assert!(!before.contains("started"), "{before}");

    db.client()
        .await?
        .batch_execute("ALTER TABLE employees ADD COLUMN started date")
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    cat.reload().await?;

    let source = app_source_from_config(&app.framework)?;
    let written = emit_react_runtime(&cat, &app, &source, None).await?;
    assert_eq!(
        written,
        [
            "staff/src/saltcorn/client.ts",
            "staff/src/saltcorn/hooks.ts",
            "staff/src/saltcorn/graphql.ts",
            "staff/src/saltcorn/schema.graphql",
        ]
    );

    let after = std::fs::read_to_string(project.join("src/saltcorn/schema.graphql"))?;
    assert!(after.contains("started: Date"), "{after}");
    // And the new column is filterable and orderable, not merely selectable —
    // the SDL is the whole contract, regenerated as one thing.
    assert!(after.contains("started: DateComparison"), "{after}");
    Ok(())
}

/// The Phase 8 acceptance test: a query using a **constrained child aggregate**,
/// written against the generated client, compiles under the scaffolded project's
/// own `tsc --noEmit`.
///
/// This is what makes a stale query a build failure rather than a runtime
/// surprise, and it is only true if the generated client's signature, the
/// project's TypeScript configuration and the app's own code agree. Nothing
/// short of running `tsc` establishes that.
#[tokio::test]
async fn a_scaffolded_project_type_checks_a_query_using_an_aggregate_field() -> sc_error::Result<()>
{
    if !npm_available() {
        eprintln!("skipping: `npm` is not on PATH, so the project cannot be type-checked");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let cat = catalog(&db).await?;
    let tmp = TempDir::new("typecheck")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = staff_app(both_providers());
    scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("staff");

    // The app's own code — the milestone's motivating query, typed by hand
    // because `gql.tada` is a package the developer installs, not one Saltcorn
    // installs for them. `tsc` sees it because the project compiles `src`.
    std::fs::write(
        project.join("src/report.ts"),
        r#"import { graphql, GraphqlError } from "./saltcorn/graphql";

type Report = {
  departments: {
    name: string;
    employees: { name: string; salary: string | null }[] | null;
    employees_aggregate: {
      count: number;
      avg: { salary: string | null };
    };
  }[];
};

export async function report(): Promise<Report["departments"]> {
  try {
    const data = await graphql<Report, { max: number }>(
      `query Report($max: BigInt) {
         departments(order_by: [{ name: asc }]) {
           name
           employees(where: { salary: { lt: $max } }, limit: 5) { name salary }
           employees_aggregate(where: { salary: { lt: $max } }) { count avg { salary } }
         }
       }`,
      { max: 50000 },
    );
    return data.departments;
  } catch (e) {
    if (e instanceof GraphqlError) throw new Error(`${e.code ?? "graphql"}: ${e.message}`);
    throw e;
  }
}
"#,
    )?;

    // `npm run build` is `tsc --noEmit && vite build`, so a type error here is a
    // failed build carrying `tsc`'s own diagnostics (§16).
    let source = app_source_from_config(&app.framework)?;
    let report = build_application(&cat, &app, &source, None).await?;
    assert!(report.installed, "the first build installs dependencies");
    Ok(())
}
