//! Integration test for §2.3: the **server** creates a React application's
//! project, and what it creates builds and serves.
//!
//! The generator itself is pure and unit-tested in `sc-app`'s `scaffold::files`
//! module. What needs a database and a real tree is everything around it: the
//! project is generated against the app's *actual* tables (which come from the
//! catalog), written through the file store, refused when the directory is
//! occupied, and handed to `git init` when the store is not already a repo.
//!
//! **The real `npm install` + `vite build` is opt-in**, behind `SC_TEST_NPM=1`.
//! It is the only honest end-to-end proof that a scaffolded project builds — it
//! type-checks the generated hooks against the generated client — but it needs a
//! Node toolchain and a network, which the rest of the Rust suite deliberately
//! does not. Everything else here runs unconditionally.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, AppRequest, Application, CodeFramework, FrameworkRef, app_source_from_config,
    build_application, emit_react_runtime, scaffold_app,
};
use sc_catalog::{Catalog, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-scaffold-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// A catalog over a real Postgres holding one `tasks` table — the app's data
/// model, and what the scaffold generates its pages and hooks against.
async fn catalog_with_tasks(db: &TestDb) -> sc_error::Result<Catalog> {
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE tasks (\
               id bigint generated by default as identity primary key, \
               title text not null, \
               done boolean)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// The whole configuration of a React app: a store and a project name.
fn todo_app() -> Application {
    Application::new(
        "Todo",
        "todo",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "todo"),
    )
    .with_table(TableId("tasks".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn the_server_writes_a_complete_project_against_the_apps_own_tables() -> sc_error::Result<()>
{
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("write")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let report = scaffold_app(&cat, &todo_app(), None).await?;
    assert_eq!(report.project, "todo");

    // Everything `npm install && npm run build` needs, with no shell step: the
    // MVP tutorial's `npm create vite`, `npm install` and `git init` are all
    // gone from the admin's hands.
    let project = tmp.path().join("todo");
    for expected in [
        "package.json",
        "vite.config.ts",
        "tsconfig.json",
        "index.html",
        ".gitignore",
        "src/main.tsx",
        "src/App.tsx",
        "src/routes.tsx",
        "src/auth.tsx",
        "src/Login.tsx",
        "src/app.css",
        "src/saltcorn/client.ts",
        "src/saltcorn/hooks.ts",
    ] {
        assert!(project.join(expected).is_file(), "missing {expected}");
    }
    // 11 project files + one page for the app's one table + the two-file runtime.
    assert_eq!(report.files.len(), 14);

    // Generated against the app's real table, not a placeholder: there is a page
    // for `tasks`, and the hooks carry its columns and their nullability.
    assert!(project.join("src/pages/Tasks.tsx").is_file());
    let hooks = std::fs::read_to_string(project.join("src/saltcorn/hooks.ts"))?;
    assert!(hooks.contains("export type TasksRow"), "{hooks}");
    assert!(hooks.contains("title: string;"), "{hooks}");
    assert!(hooks.contains("done?: boolean | null;"), "{hooks}");
    assert!(hooks.contains("api.listTasks()"), "{hooks}");

    // The client is generated at the conventional path the scaffold imports
    // from, so the two halves of the runtime meet without a setting.
    let client = std::fs::read_to_string(project.join("src/saltcorn/client.ts"))?;
    assert!(client.contains("listTasks("), "{client}");
    assert!(client.contains("/api/tasks"), "{client}");
    let routes = std::fs::read_to_string(project.join("src/routes.tsx"))?;
    assert!(routes.contains("./pages/Tasks"), "{routes}");

    // §13.3 expects an app's source to be a git repo; the store here is not one,
    // so the project became one. The MVP left this to the admin's shell.
    assert!(report.git_initialized);
    assert!(project.join(".git").exists());
    Ok(())
}

#[tokio::test]
async fn scaffolding_never_overwrites_an_occupied_directory() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("occupied")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // An admin's existing work — the case that must never be clobbered.
    let project = tmp.path().join("todo");
    std::fs::create_dir_all(project.join("src"))?;
    std::fs::write(project.join("src/App.tsx"), "// six months of work\n")?;

    let err = scaffold_app(&cat, &todo_app(), None)
        .await
        .expect_err("an occupied directory is refused")
        .to_string();
    assert!(err.contains("todo"), "should name the directory: {err}");
    assert!(err.contains("not empty"), "{err}");

    // And it is refused *before* anything is written: the file is byte-identical
    // and no scaffolded file appeared beside it.
    assert_eq!(
        std::fs::read_to_string(project.join("src/App.tsx"))?,
        "// six months of work\n"
    );
    assert!(!project.join("package.json").exists());
    Ok(())
}

#[tokio::test]
async fn a_store_that_is_already_a_repo_does_not_get_a_nested_one() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("gitstore")?;
    // A store rooted at a git repo: the project lands *inside* it, so initialising
    // another repo in the sub-directory would leave the source tracked by a repo
    // nobody expects.
    std::fs::create_dir_all(tmp.path().join(".git"))?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let report = scaffold_app(&cat, &todo_app(), None).await?;
    assert!(!report.git_initialized);
    assert!(!tmp.path().join("todo/.git").exists());
    Ok(())
}

#[tokio::test]
async fn the_generated_runtime_is_rewritten_on_build_and_nothing_else_is() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("regen")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let mut app = todo_app();
    scaffold_app(&cat, &app, None).await?;
    let project = tmp.path().join("todo");

    // The admin edits their own code — the half of the project that is theirs.
    let mine = "// my app\nexport default function App() { return null; }\n";
    std::fs::write(project.join("src/App.tsx"), mine)?;

    // A table is added to the app later. The runtime is regenerated from the
    // app's endpoints, so the new table's hooks simply exist — this is what makes
    // generating the runtime better than shipping it as a package (§2.1).
    db.client()
        .await?
        .batch_execute("CREATE TABLE notes (id bigint generated by default as identity primary key, body text)")
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    cat.reload().await?;
    app.tables.push(TableId("notes".to_owned()));

    let source = app_source_from_config(&app.framework)?;
    let written = emit_react_runtime(&cat, &app, &source, None).await?;
    assert_eq!(
        written,
        ["todo/src/saltcorn/client.ts", "todo/src/saltcorn/hooks.ts"]
    );

    let hooks = std::fs::read_to_string(project.join("src/saltcorn/hooks.ts"))?;
    assert!(hooks.contains("export function useNotes()"), "{hooks}");
    assert!(hooks.contains("export type NotesRow"), "{hooks}");
    // Everything outside `src/saltcorn/` is untouched — including the page for
    // the new table, which is the admin's to add or not.
    assert_eq!(std::fs::read_to_string(project.join("src/App.tsx"))?, mine);
    assert!(!project.join("src/pages/Notes.tsx").exists());
    Ok(())
}

/// Scaffold → install → build → serve, with a real Node toolchain.
///
/// Opt-in (`SC_TEST_NPM=1`) because it needs `npm` and a network; it is slow and
/// would make the whole suite depend on both. What it buys, and nothing else
/// does: the generated hooks are **type-checked against the generated client**
/// (the project's build script is `tsc --noEmit && vite build`), so a drift
/// between what `sc-api` emits and what the scaffold calls fails here.
#[tokio::test]
async fn a_scaffolded_app_installs_builds_and_serves_end_to_end() -> sc_error::Result<()> {
    if std::env::var("SC_TEST_NPM").as_deref() != Ok("1") {
        eprintln!("skipping: set SC_TEST_NPM=1 to run the real npm build");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let cat = catalog_with_tasks(&db).await?;
    let tmp = TempDir::new("e2e")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = todo_app();
    let report = scaffold_app(&cat, &app, None).await?;
    assert!(!report.files.is_empty());

    // No shell step between scaffolding and a served bundle: the build installs
    // the dependencies the scaffold declared, then runs the bundler.
    let source = app_source_from_config(&app.framework)?;
    let report = build_application(&cat, &app, &source, None).await?;
    assert!(report.installed, "the first build installs dependencies");
    assert!(tmp.path().join("todo/node_modules").is_dir());

    let fw = CodeFramework::new("react", report.bundle);
    let index = fw.serve(&AppRequest::get("/"));
    assert_eq!(index.status, 200);
    assert_eq!(index.content_type, "text/html; charset=utf-8");
    assert!(String::from_utf8_lossy(&index.body).contains("<div id=\"root\">"));
    // A client-routed deep link resolves to the entry point.
    assert_eq!(fw.serve(&AppRequest::get("/tasks/42")).status, 200);

    // A second build does not reinstall — the marker is on disk.
    let again = build_application(&cat, &app, &source, None).await?;
    assert!(!again.installed);
    Ok(())
}
