//! The tutorial, executed: `docs/tutorial-react-todo.md` from its data model to a
//! built bundle, with nothing stubbed.
//!
//! Every other test around the React framework either stops at the generated text
//! or stubs the toolchain, which is exactly the seam a real failure hides in: the
//! scaffold can be word-perfect and still not compile. So this one creates the
//! `tasks` table **through the catalog API the admin UI calls**, scaffolds the
//! app, and then runs the real `npm install` + `tsc --noEmit` + `vite build`.
//!
//! It **skips when `npm` is not on `PATH`**, so a Rust-only checkout stays green,
//! and it runs by default everywhere else — deliberately not behind an opt-in
//! variable. An opt-in test is one nobody runs, and the whole point of this one is
//! to fail when the generated project stops building.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use sc_app::{
    ApiConfig, AppRequest, Application, CodeFramework, FrameworkRef, app_source_from_config,
    build_application, scaffold_app,
};
use sc_catalog::{Catalog, DataField, FileStoreId, TableId};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;
use sc_types::{BasicType, TypeRef};

/// The primary key `createTable` gives a new table in the admin UI.
const PK_SQL_TYPE: &str = "bigint generated by default as identity";

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-app-tutorial-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// Whether a Node toolchain is available to build with.
fn npm_available() -> bool {
    std::env::var_os("PATH")
        .map(|paths| {
            std::env::split_paths(&paths)
                .any(|dir| dir.join("npm").is_file() || dir.join("npm.cmd").is_file())
        })
        .unwrap_or(false)
}

/// **Tutorial step 2**, through the same calls the admin UI makes: create the
/// `tasks` table, then add `title` and `done`.
///
/// Not raw SQL, because the point is to build what an admin building it in a
/// browser would get — including whatever the catalog decides a column's type is
/// on the way back out of `information_schema`.
async fn tutorial_catalog(db: &TestDb) -> sc_error::Result<Arc<Catalog>> {
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);

    let id = DataField::plain("id", TypeRef::from_sql_type(PK_SQL_TYPE))
        .required()
        .primary_key();
    catalog.create_table("tasks", &[id]).await?;
    catalog
        .create_field(
            "tasks",
            &DataField::plain("title", TypeRef::Basic(BasicType::Text)).required(),
        )
        .await?;
    catalog
        .create_field(
            "tasks",
            &DataField::plain("done", TypeRef::Basic(BasicType::Bool)),
        )
        .await?;
    Ok(catalog)
}

/// **Tutorial step 3**: the application, as the create form posts it — a store, a
/// project name, the one table, and REST at `/api`.
fn todo_app() -> Application {
    Application::new(
        "Todo",
        "todo",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "todo"),
    )
    .with_table(TableId("tasks".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"))
}

#[tokio::test]
async fn the_tutorial_app_scaffolds_installs_type_checks_builds_and_serves() -> sc_error::Result<()>
{
    if !npm_available() {
        eprintln!("skipping: `npm` is not on PATH, so the tutorial build cannot run");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let cat = tutorial_catalog(&db).await?;
    let tmp = TempDir::new("build")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // Step 3: creating the app scaffolds its project.
    let app = todo_app();
    let scaffold = scaffold_app(&cat, &app).await?;
    assert!(scaffold.files.iter().any(|f| f.ends_with("package.json")));

    // Step 4: Build. Installs dependencies, regenerates the runtime, type-checks
    // and bundles. A failure here carries the tool's own diagnostics, which is
    // what makes this test worth having: `tsc` names the file and line in the
    // *generated* code that no longer compiles.
    let source = app_source_from_config(&app.framework)?;
    let report = build_application(&cat, &app, &source).await?;
    assert!(report.installed, "the first build installs dependencies");

    // Step 5: what is served is a real Vite bundle — an entry point plus hashed
    // assets, not the scaffold's own `index.html` copied through.
    let fw = CodeFramework::new("react", report.bundle.clone());
    let index = fw.serve(&AppRequest::get("/"));
    assert_eq!(index.status, 200);
    let html = String::from_utf8_lossy(&index.body);
    assert!(html.contains("<div id=\"root\">"), "{html}");
    assert!(
        html.contains("<script type=\"module\""),
        "the bundler's entry script should be in the served index: {html}"
    );
    assert!(!html.contains("/src/main.tsx"), "unbundled source: {html}");

    // Deep links resolve to the entry point, so the app's own routes work.
    assert_eq!(fw.serve(&AppRequest::get("/tasks/42")).status, 200);

    // A second build reuses the installed dependencies.
    let again = build_application(&cat, &app, &source).await?;
    assert!(!again.installed);
    Ok(())
}

/// The same path, for the app shapes an admin produces that the tutorial does
/// not: no tables at all, a table whose rows are not addressable, and column
/// types beyond text and boolean.
///
/// These are not exotic. "Create the app, then add the tables" is an ordinary
/// order to work in, and a table without a single-column primary key is whatever
/// the admin's legacy schema happens to contain. Each generates a *different*
/// project, and a project that does not compile is a build failure with a
/// TypeScript error in code the admin never wrote — the worst error this
/// framework can produce.
#[tokio::test]
async fn projects_for_unusual_table_sets_also_build() -> sc_error::Result<()> {
    if !npm_available() {
        eprintln!("skipping: `npm` is not on PATH, so the tutorial build cannot run");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let cat = tutorial_catalog(&db).await?;
    // A table with no primary key (so no row-addressed endpoints) and a spread of
    // column types: a date, a number and a nullable text.
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE events (name text not null, starts date, seats int, note text)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;
    cat.reload().await?;

    let tmp = TempDir::new("shapes")?;
    cat.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    // (a) An application with **no tables yet** — created before its data model,
    //     which is an ordinary order to work in.
    let bare = Application::new(
        "Bare",
        "bare",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "bare"),
    )
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"));
    scaffold_app(&cat, &bare).await?;
    let source = app_source_from_config(&bare.framework)?;
    build_application(&cat, &bare, &source).await?;

    // (b) Two tables, one of them keyless and carrying date/int columns.
    let mixed = Application::new(
        "Mixed",
        "mixed",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "mixed"),
    )
    .with_table(TableId("tasks".to_owned()))
    .with_table(TableId("events".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"));
    scaffold_app(&cat, &mixed).await?;
    let source = app_source_from_config(&mixed.framework)?;
    let report = build_application(&cat, &mixed, &source).await?;

    // Both tables have a page, and the second one is reachable at its own path.
    let fw = CodeFramework::new("react", report.bundle);
    assert_eq!(fw.serve(&AppRequest::get("/events")).status, 200);
    Ok(())
}
