//! The files a scaffolded React project is made of (TODO §2.3).
//!
//! Every function here is **pure**: table metadata and an endpoint set in, file
//! contents out. Nothing touches a file store, so the whole generator is
//! assertable in unit tests, and the store-writing half ([`super`]) has no
//! templates in it.
//!
//! Two kinds of file come out, and the difference is load-bearing (§2.1):
//!
//! - **Generated runtime** under `src/saltcorn/` — the typed client and the hooks
//!   over it, plus the GraphQL client and schema of an app that enables that
//!   provider. Rewritten on every build, so a table added later shows up in the
//!   types. Carries a "DO NOT EDIT" header because it means it.
//! - **The project itself** — `package.json`, the Vite/TS config, the app shell,
//!   the login screen, the routes and one page per table. Written **once**, at
//!   scaffold time, and never touched again. This is the admin's code from the
//!   moment it exists, which is why it is generated against their *actual*
//!   tables: a scaffold that comes up showing a placeholder counter is a
//!   template, while one that comes up showing their rows is a working app they
//!   can edit.
//!
//! The shell comes in two shapes, decided by [`has_auth`]: the authenticated one
//! §13.3 describes, and — for an application that exposes no auth endpoints — an
//! anonymous one with no auth layer at all.

use sc_api::{
    EndpointSet, GRAPHQL_CLIENT_FILE, GRAPHQL_SCHEMA_FILE, generate_client,
    generate_graphql_client, op_name,
};
use sc_catalog::Table;
use sc_types::BasicType;

use crate::api::AppGraphql;
use crate::react::{REACT_CLIENT_FILE, REACT_RUNTIME_SUBDIR};

/// A generated file: a path relative to the project directory, and its contents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the project directory, `/`-separated (e.g. `src/App.tsx`).
    pub path: String,
    /// The file's contents.
    pub contents: String,
}

impl GeneratedFile {
    fn new(path: impl Into<String>, contents: impl Into<String>) -> GeneratedFile {
        GeneratedFile {
            path: path.into(),
            contents: contents.into(),
        }
    }
}

/// The header every regenerated file carries, so the boundary between "yours"
/// and "ours" is visible in the file rather than only in the documentation.
const GENERATED_HEADER: &str = "// Code generated by Saltcorn. DO NOT EDIT.\n\
                                // Rewritten on every build; edits here are lost.\n";

/// The header a generated **GraphQL schema** carries. The same sentence as
/// [`GENERATED_HEADER`] in the comment syntax SDL actually has: `//` is not a
/// comment in GraphQL, and a header that made the schema unparseable would
/// break the one tool the file exists for.
const GENERATED_SDL_HEADER: &str = "# Schema generated by Saltcorn. DO NOT EDIT.\n\
                                    # Rewritten on every build; edits here are lost.\n\n";

/// The files under `src/saltcorn/`: the typed client, the typed hooks, and —
/// for an app that enables the GraphQL provider — its client and its schema.
///
/// Emitted by the scaffold *and* by every subsequent build, which is what keeps
/// them honest when the app's tables change. The schema is written **only** for
/// an app that enables the provider: an app without one has no GraphQL contract,
/// and a `schema.graphql` sitting in its tree describing an API it does not
/// serve would be a lie its editor believed.
pub fn runtime_files(
    tables: &[Table],
    endpoints: &EndpointSet,
    graphql: Option<&AppGraphql>,
) -> Vec<GeneratedFile> {
    let mut files = vec![
        GeneratedFile::new(
            format!("{REACT_RUNTIME_SUBDIR}/{REACT_CLIENT_FILE}"),
            generate_client(endpoints),
        ),
        GeneratedFile::new(
            format!("{REACT_RUNTIME_SUBDIR}/hooks.ts"),
            hooks_ts(tables, endpoints),
        ),
    ];
    if let Some(graphql) = graphql {
        files.push(GeneratedFile::new(
            format!("{REACT_RUNTIME_SUBDIR}/{GRAPHQL_CLIENT_FILE}"),
            generate_graphql_client(&graphql.mount),
        ));
        files.push(GeneratedFile::new(
            format!("{REACT_RUNTIME_SUBDIR}/{GRAPHQL_SCHEMA_FILE}"),
            format!("{GENERATED_SDL_HEADER}{}", graphql.sdl),
        ));
    }
    files
}

/// The tables the generated project may have pages and hooks for: those the
/// app's API actually exposes.
///
/// **The endpoint set is the source of truth, not the table list**, and the
/// difference is not academic. An application declares tables *and* API
/// providers; a table it declares but does not expose has no `listTasks` on the
/// generated client, so a page calling one would not compile — which is exactly
/// what a real app hit. Deriving "what can this project talk to?" from the same
/// value the client is generated from makes that class of mismatch unable to
/// occur, where re-deriving it from the tables only made the two agree *by
/// coincidence* while they happened to be computed the same way.
fn exposed_tables<'a>(tables: &'a [Table], endpoints: &EndpointSet) -> Vec<&'a Table> {
    tables
        .iter()
        .filter(|t| endpoints.find(&op_name("list", &t.name)).is_some())
        .collect()
}

/// Whether this application can sign anyone in.
///
/// The scaffold's auth layer is generated code calling `login` / `logout` /
/// `whoami` through the typed client, so it can only exist when the application
/// exposes them — which today means the REST provider (§13.4). An app that does
/// not gets the anonymous shell instead of a login screen whose three calls do
/// not compile: **authenticated by default** (§13.3) is a statement about a
/// scaffold's *routes*, and it cannot lock a door that has no key.
///
/// All three or none: a partial set is a provider having changed under us, and
/// generating half an auth layer against it is how you get the error this branch
/// exists to prevent.
pub fn has_auth(endpoints: &EndpointSet) -> bool {
    sc_api::AUTH_ENDPOINTS
        .iter()
        .all(|name| endpoints.find(name).is_some())
}

/// The whole project: the runtime plus everything written once.
pub fn project_files(
    project: &str,
    tables: &[Table],
    endpoints: &EndpointSet,
    graphql: Option<&AppGraphql>,
) -> Vec<GeneratedFile> {
    let exposed = exposed_tables(tables, endpoints);
    let auth = has_auth(endpoints);
    let mut files = vec![
        GeneratedFile::new("package.json", package_json(project)),
        GeneratedFile::new("vite.config.ts", VITE_CONFIG),
        GeneratedFile::new("tsconfig.json", tsconfig(graphql.is_some())),
        GeneratedFile::new("index.html", index_html(project)),
        GeneratedFile::new(".gitignore", GITIGNORE),
        GeneratedFile::new("src/main.tsx", main_tsx(auth)),
        GeneratedFile::new("src/App.tsx", app_tsx(project, auth)),
        GeneratedFile::new("src/routes.tsx", routes_tsx(&exposed, auth)),
        GeneratedFile::new("src/app.css", APP_CSS),
    ];
    if auth {
        files.push(GeneratedFile::new("src/auth.tsx", AUTH_TSX));
        files.push(GeneratedFile::new("src/Login.tsx", LOGIN_TSX));
    }
    for table in &exposed {
        files.push(GeneratedFile::new(
            format!("src/pages/{}.tsx", pascal(&table.name)),
            page_tsx(table, endpoints),
        ));
    }
    files.extend(runtime_files(tables, endpoints, graphql));
    files
}

// --- the project's own files -----------------------------------------------

/// Dependency versions are **ranges, pinned to a major**: a scaffolded project is
/// the admin's from the moment it exists, so it should pick up patches without
/// the server having an opinion, while a major bump stays their deliberate act.
fn package_json(project: &str) -> String {
    format!(
        r#"{{
  "name": "{project}",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc --noEmit && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "react-router-dom": "^7.9.0"
  }},
  "devDependencies": {{
    "@types/react": "^19.2.0",
    "@types/react-dom": "^19.2.0",
    "@vitejs/plugin-react": "^6.0.0",
    "typescript": "^5.9.0",
    "vite": "^8.0.0"
  }}
}}
"#
    )
}

/// `tsc --noEmit` runs *before* `vite build` in the build script on purpose: the
/// client is regenerated from the app's endpoints on every build, so a table
/// removed in the admin UI should fail the build with a type error naming the
/// call site, not produce a bundle that 404s at runtime.
const VITE_CONFIG: &str = "import { defineConfig } from \"vite\";\n\
                           import react from \"@vitejs/plugin-react\";\n\n\
                           export default defineConfig({\n\
                           \x20 plugins: [react()],\n\
                           });\n";

/// The project's TypeScript configuration.
///
/// With `graphql`, it also carries the **`gql.tada` plugin** pointed at the
/// emitted `schema.graphql` (decision 7). Nothing is added to `package.json` for
/// it: a `plugins` entry is a *language service* setting that `tsc` ignores
/// entirely, so the project builds identically with or without the package
/// installed, and a developer who wants their queries type-checked in the editor
/// installs `gql.tada` themselves and finds it already configured. Which is the
/// whole arrangement: no codegen step, and the app's dependencies stay the
/// developer's business.
fn tsconfig(graphql: bool) -> String {
    let plugins = if graphql {
        format!(
            r#",
    "plugins": [
      {{
        "name": "gql.tada/ts-plugin",
        "schema": "./{REACT_RUNTIME_SUBDIR}/{GRAPHQL_SCHEMA_FILE}",
        "tadaOutputLocation": "./{REACT_RUNTIME_SUBDIR}/graphql-env.d.ts"
      }}
    ]"#
        )
    } else {
        String::new()
    };
    format!(
        r#"{{
  "compilerOptions": {{
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "verbatimModuleSyntax": true,
    "skipLibCheck": true,
    "noEmit": true,
    "types": ["vite/client"]{plugins}
  }},
  "include": ["src", "vite.config.ts"]
}}
"#
    )
}

fn index_html(project: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{project}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"#
    )
}

/// `node_modules` and `dist` only. The generated runtime is **not** ignored: it
/// is part of the source an admin reads and type-checks against, and a git repo
/// that omits it cannot be built anywhere but here.
const GITIGNORE: &str = "node_modules\ndist\n*.local\n";

/// The entry point. The auth provider wraps the router when there is one, so the
/// current user is known before any route renders.
fn main_tsx(auth: bool) -> String {
    let (import, open, close) = if auth {
        (
            "import { AuthProvider } from \"./auth\";\n",
            "    <AuthProvider>\n",
            "    </AuthProvider>\n",
        )
    } else {
        ("", "", "")
    };
    // The router's indentation follows the wrapper it is (or is not) inside.
    let pad = if auth { "  " } else { "" };
    format!(
        r#"import {{ StrictMode }} from "react";
import {{ createRoot }} from "react-dom/client";
import {{ BrowserRouter }} from "react-router-dom";
{import}import App from "./App";
import "./app.css";

const root = document.getElementById("root");
if (!root) throw new Error("no #root element in index.html");

createRoot(root).render(
  <StrictMode>
{open}{pad}    <BrowserRouter>
{pad}      <App />
{pad}    </BrowserRouter>
{close}  </StrictMode>,
);
"#
    )
}

/// The auth layer: a provider, a `useUser` hook and a gate.
///
/// It talks to the app's own `/api/login`, `/api/logout` and `/api/whoami`
/// through the generated client, so the session is a cookie the browser carries
/// and nothing here stores a credential. **This is a UI convenience, never the
/// enforcement point** (§2.1): every request is authorized again server-side, so
/// a route wrongly marked public renders a screen whose data calls fail, not a
/// leak.
const AUTH_TSX: &str = r#"import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";
import { api } from "./saltcorn/hooks";

export type User = { id: string; email: string; role: number };

export type AuthState = {
  /** The signed-in user, or null when anonymous. `undefined` while unknown. */
  user: User | null | undefined;
  signIn: (email: string, password: string) => Promise<void>;
  signOut: () => Promise<void>;
};

const AuthContext = createContext<AuthState | undefined>(undefined);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null | undefined>(undefined);

  useEffect(() => {
    let cancelled = false;
    // A 401 here is the ordinary anonymous case, not an error to report.
    api.whoami().then(
      (u) => !cancelled && setUser(u),
      () => !cancelled && setUser(null),
    );
    return () => {
      cancelled = true;
    };
  }, []);

  const signIn = useCallback(async (email: string, password: string) => {
    setUser(await api.login({ email, password }));
  }, []);

  const signOut = useCallback(async () => {
    await api.logout();
    setUser(null);
  }, []);

  return (
    <AuthContext.Provider value={{ user, signIn, signOut }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useUser(): AuthState {
  const state = useContext(AuthContext);
  if (!state) throw new Error("useUser must be used inside <AuthProvider>");
  return state;
}
"#;

const LOGIN_TSX: &str = r#"import { useState, type FormEvent } from "react";
import { useUser } from "./auth";

export default function Login() {
  const { signIn } = useUser();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | undefined>(undefined);
  const [busy, setBusy] = useState(false);

  const submit = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(undefined);
    try {
      await signIn(email, password);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <form className="card sc-login" onSubmit={submit}>
      <h1>Sign in</h1>
      <label>
        Email
        <input
          type="email"
          value={email}
          autoComplete="username"
          onChange={(e) => setEmail(e.target.value)}
        />
      </label>
      <label>
        Password
        <input
          type="password"
          value={password}
          autoComplete="current-password"
          onChange={(e) => setPassword(e.target.value)}
        />
      </label>
      {error && <p className="sc-error">{error}</p>}
      <button type="submit" disabled={busy}>
        {busy ? "Signing in…" : "Sign in"}
      </button>
    </form>
  );
}
"#;

/// The shell: a header naming the app, a nav built from the route list, the
/// signed-in user, and the routes themselves.
///
/// Without auth there is no user to show and no gate to apply, so the header's
/// last cell and the route element's condition are simply not written. The
/// alternative — keeping them against a `user` that is always `null` — would
/// generate an app permanently displaying "not signed in" beside a sign-in button
/// that cannot exist.
fn app_tsx(project: &str, auth: bool) -> String {
    let (auth_imports, user_hook, user_cell, element) = if auth {
        (
            "import { useUser } from \"./auth\";\nimport Login from \"./Login\";\n",
            "  const { user, signOut } = useUser();\n",
            r#"        <span className="sc-user">
          {user ? (
            <>
              {user.email} <button onClick={() => void signOut()}>Sign out</button>
            </>
          ) : (
            "not signed in"
          )}
        </span>
"#,
            "r.public || user ? r.element : <Login />",
        )
    } else {
        ("", "", "", "r.element")
    };
    format!(
        r#"import {{ Link, Route, Routes, useLocation }} from "react-router-dom";
import {{ routes }} from "./routes";
{auth_imports}
export default function App() {{
{user_hook}  const location = useLocation();

  return (
    <div className="sc-app">
      <header className="sc-header">
        <strong>{project}</strong>
        <nav>
          {{routes
            .filter((r) => r.label)
            .map((r) => (
              <Link
                key={{r.path}}
                to={{r.path}}
                className={{location.pathname === r.path ? "active" : ""}}
              >
                {{r.label}}
              </Link>
            ))}}
        </nav>
{user_cell}      </header>
      <main>
        <Routes>
          {{routes.map((r) => (
            <Route key={{r.path}} path={{r.path}} element={{{element}}} />
          ))}}
        </Routes>
      </main>
    </div>
  );
}}
"#
    )
}

/// The route list, as data.
///
/// §2.1 chose this over a file-system convention: the scaffold knows the app's
/// tables, so it can write the list, and a list is inspectable and editable
/// without a build-time plugin scanning directories. `public` is the per-route
/// opt-out from the authenticated-by-default rule — one word, and its absence
/// means "signed in", which is the direction a forgotten flag should fail in.
///
/// An app with no auth has no login route to reach and no flag to carry: every
/// route is reachable, and a `public?: boolean` nothing reads would be a promise
/// about a gate that is not there.
fn routes_tsx(tables: &[&Table], auth: bool) -> String {
    let mut imports = String::from("import type { ReactNode } from \"react\";\n");
    if auth {
        imports.push_str("import Login from \"./Login\";\n");
    }
    let mut entries = String::new();
    for table in tables {
        let component = format!("{}Page", pascal(&table.name));
        imports.push_str(&format!(
            "import {component} from \"./pages/{}\";\n",
            pascal(&table.name)
        ));
        entries.push_str(&format!(
            "  {{ path: \"{}\", label: \"{}\", element: <{component} /> }},\n",
            route_path(&table.name, tables),
            title(&table.name)
        ));
    }
    let (public_field, login_route) = if auth {
        (
            "  /** Reachable without signing in. Absent means: sign-in required. */\n  public?: boolean;\n",
            "  { path: \"/login\", label: \"\", element: <Login />, public: true },\n",
        )
    } else {
        ("", "")
    };
    format!(
        r#"{imports}
export type AppRoute = {{
  /** The path within the app. */
  path: string;
  /** Shown in the nav; an empty label hides the route from it. */
  label: string;
  element: ReactNode;
{public_field}}};

export const routes: AppRoute[] = [
{entries}{login_route}];
"#
    )
}

/// The first table owns `/`; the rest get `/<table>`. An app whose only table is
/// `tasks` should not open on an empty index page.
fn route_path(table: &str, tables: &[&Table]) -> String {
    if tables.first().is_some_and(|t| t.name == table) {
        "/".to_owned()
    } else {
        format!("/{table}")
    }
}

/// One page per table: the list, a create form, and (when rows are addressable)
/// per-row edit and delete.
///
/// This is what "generate against the app's *actual* tables" buys — the app comes
/// up showing real rows in real columns, so the admin's first act is editing
/// working code rather than replacing a placeholder.
fn page_tsx(table: &Table, endpoints: &EndpointSet) -> String {
    let pascal = pascal(&table.name);
    let row_type = format!("{pascal}Row");
    // What the page may do is what the app's API offers, not what the table looks
    // like: a table the app declares but does not expose has no hooks to call.
    let can_create = has_op(endpoints, "create", &table.name);
    let can_delete = has_op(endpoints, "delete", &table.name);

    let headers = table
        .fields
        .iter()
        .map(|f| format!("            <th>{}</th>", f.base.label))
        .collect::<Vec<_>>()
        .join("\n");
    let cells = table
        .fields
        .iter()
        .map(|f| {
            format!(
                "              <td>{{String(row.{} ?? \"\")}}</td>",
                f.base.name
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    // Imports, hooks and state are assembled rather than templated, because a
    // page that imports a hook it does not call — or declares state it does not
    // use — fails the project's own type-check (`noUnusedLocals`), in generated
    // code the admin never wrote.
    let mut hook_imports = format!("use{pascal}");
    if can_create {
        hook_imports.push_str(&format!(", useCreate{pascal}"));
    }
    if can_delete {
        hook_imports.push_str(&format!(", useDelete{pascal}"));
    }

    let mut head = String::new();
    if can_create {
        head.push_str("import { useState } from \"react\";\n");
    }
    head.push_str(&format!(
        "import {{ {hook_imports}, type {row_type} }} from \"../saltcorn/hooks\";\n"
    ));

    let (empty_const, create_form) = if can_create {
        // Primary-key columns get no input. A v2 table's key is a
        // database-generated identity, so offering a control for it would invite
        // an insert that fights the database for the value — and the catalog does
        // not record "generated" as a property, so "is it the key?" is the honest
        // question available. A table with an admin-supplied key is the case this
        // gets wrong, and the fix is to edit the page, which is the admin's file.
        let inputs: Vec<&sc_catalog::DataField> =
            table.fields.iter().filter(|f| !f.primary_key).collect();
        let empty_form = inputs
            .iter()
            .map(|f| format!("  {}: {}", f.base.name, ts_empty(f)))
            .collect::<Vec<_>>()
            .join(",\n");
        let form_fields = inputs
            .iter()
            .map(|f| form_control(&f.base.name, basic_type(f)))
            .collect::<Vec<_>>()
            .join("\n");
        (
            format!("\nconst empty = {{\n{empty_form}\n}};\n"),
            format!(
                r#"      <form
        className="card"
        onSubmit={{(e) => {{
          e.preventDefault();
          void create.run(form).then(() => setForm(empty));
        }}}}
      >
{form_fields}
        <button type="submit" disabled={{create.pending}}>
          Add
        </button>
        {{create.error && <p className="sc-error">{{create.error.message}}</p>}}
      </form>
"#
            ),
        )
    } else {
        (String::new(), String::new())
    };

    let mut hooks = format!("  const {{ data, loading, error }} = use{pascal}();\n");
    if can_create {
        hooks.push_str(&format!("  const create = useCreate{pascal}();\n"));
        hooks.push_str("  const [form, setForm] = useState(empty);\n");
    }
    if can_delete {
        hooks.push_str(&format!("  const remove = useDelete{pascal}();\n"));
    }

    let (delete_column, delete_cell) = if can_delete {
        let pk = single_pk(table).unwrap_or_default();
        (
            "            <th />\n".to_owned(),
            format!(
                r#"              <td>
                <button onClick={{() => void remove.run(row.{pk})}}>Delete</button>
              </td>
"#
            ),
        )
    } else {
        (String::new(), String::new())
    };

    format!(
        r#"{head}{empty_const}
export default function {pascal}Page() {{
{hooks}
  if (error) return <p className="sc-error">{{error.message}}</p>;

  return (
    <section>
      <h1>{title}</h1>
{create_form}      {{loading && !data ? (
        <p>Loading…</p>
      ) : (
        <table>
          <thead>
            <tr>
{headers}
{delete_column}            </tr>
          </thead>
          <tbody>
            {{(data ?? []).map((row: {row_type}, i: number) => (
              <tr key={{i}}>
{cells}
{delete_cell}              </tr>
            ))}}
          </tbody>
        </table>
      )}}
    </section>
  );
}}
"#,
        title = title(&table.name)
    )
}

/// Whether the app's API exposes `op` on `table` — the single question every
/// "should this be generated?" decision here reduces to.
fn has_op(endpoints: &EndpointSet, op: &str, table: &str) -> bool {
    endpoints.find(&op_name(op, table)).is_some()
}

/// A labelled input bound into the create form's state, typed by the column.
fn form_control(name: &str, ty: BasicType) -> String {
    match ty {
        BasicType::Bool => format!(
            r#"        <label>
          {name}
          <input
            type="checkbox"
            checked={{form.{name}}}
            onChange={{(e) => setForm({{ ...form, {name}: e.target.checked }})}}
          />
        </label>"#
        ),
        BasicType::Int | BasicType::Float | BasicType::Decimal => format!(
            r#"        <label>
          {name}
          <input
            type="number"
            value={{form.{name}}}
            onChange={{(e) => setForm({{ ...form, {name}: Number(e.target.value) }})}}
          />
        </label>"#
        ),
        _ => format!(
            r#"        <label>
          {name}
          <input
            value={{form.{name}}}
            onChange={{(e) => setForm({{ ...form, {name}: e.target.value }})}}
          />
        </label>"#
        ),
    }
}

/// Plain CSS with custom properties, both themes (§2.1: no framework, no
/// CSS-in-JS — the latter would have forced `style-src 'unsafe-inline'` into
/// every scaffolded app's policy). Written once and never regenerated, so
/// replacing it wholesale is an ordinary thing to do.
const APP_CSS: &str = r#":root {
  --bg: #ffffff;
  --fg: #1a1c1e;
  --muted: #5c6470;
  --line: #dfe3e8;
  --accent: #2f6feb;
  --radius: 8px;
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16181c;
    --fg: #e8eaed;
    --muted: #9aa3af;
    --line: #2c3038;
    --accent: #6d9bff;
  }
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 16px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
}

.sc-header {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0.75rem 1.25rem;
  border-bottom: 1px solid var(--line);
}

.sc-header nav {
  display: flex;
  gap: 0.75rem;
  flex: 1;
}

.sc-header a {
  color: var(--muted);
  text-decoration: none;
}

.sc-header a.active {
  color: var(--accent);
  font-weight: 600;
}

.sc-user {
  color: var(--muted);
  font-size: 0.875rem;
}

main {
  max-width: 60rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem;
}

.card {
  display: flex;
  flex-wrap: wrap;
  align-items: end;
  gap: 0.75rem;
  padding: 1rem;
  border: 1px solid var(--line);
  border-radius: var(--radius);
  margin-bottom: 1.5rem;
}

label {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  font-size: 0.875rem;
  color: var(--muted);
}

input {
  font: inherit;
  color: var(--fg);
  background: var(--bg);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 0.4rem 0.6rem;
}

button {
  font: inherit;
  cursor: pointer;
  color: #fff;
  background: var(--accent);
  border: 0;
  border-radius: var(--radius);
  padding: 0.45rem 0.9rem;
}

button:disabled {
  opacity: 0.6;
  cursor: default;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  text-align: left;
  padding: 0.5rem 0.6rem;
  border-bottom: 1px solid var(--line);
}

th {
  color: var(--muted);
  font-size: 0.8125rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.sc-error {
  color: #c0392b;
}

.sc-login {
  flex-direction: column;
  align-items: stretch;
  max-width: 22rem;
  margin: 3rem auto;
}
"#;

// --- the generated runtime --------------------------------------------------

/// `src/saltcorn/hooks.ts`: a row type and a hook set **per table**, over the
/// generated client.
///
/// This is the file that justifies generating the runtime instead of shipping it
/// as an npm package (§2.1): `useTasks()` returns `TasksRow[]`, and `TasksRow`
/// comes from this app's own columns. A registry package could only offer
/// `useRows("tasks"): unknown[]`, which is the part worth having thrown away.
///
/// The cache is deliberately tiny: one version counter per table, bumped by any
/// mutation of that table, with `useSyncExternalStore` re-running the affected
/// queries. That is the whole invalidation model a per-table REST API needs, and
/// it is why no query library is a dependency.
fn hooks_ts(tables: &[Table], endpoints: &EndpointSet) -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str(
        r#"
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";
import { createClient, type ApiClient } from "./client";

/** The app's typed API client. Endpoint paths already include the API mount. */
export const api: ApiClient = createClient();

/** The state of one read: data, plus what is happening to it. */
export type Query<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
  /** Re-run this query (and any other on the same table). */
  refresh: () => void;
};

/** The state of one write. */
export type Mutation<A> = {
  run: (arg: A) => Promise<void>;
  pending: boolean;
  error: Error | undefined;
};

// One version counter per table: every read subscribes to its table, every
// write bumps it. Keys are table names, which the server already guarantees to
// be unique — there is no query-key scheme to invent or get wrong.
const versions = new Map<string, number>();
const listeners = new Map<string, Set<() => void>>();

function versionOf(table: string): number {
  return versions.get(table) ?? 0;
}

function subscribe(table: string, listener: () => void): () => void {
  const set = listeners.get(table) ?? new Set<() => void>();
  listeners.set(table, set);
  set.add(listener);
  return () => set.delete(listener);
}

/** Discard what is cached for `table`, re-running every query over it. */
export function invalidate(table: string): void {
  versions.set(table, versionOf(table) + 1);
  listeners.get(table)?.forEach((l) => l());
}

/**
 * Read something from the API, cached under `table` and re-run whenever anything
 * writes to that table.
 *
 * Exported because the per-table hooks below cannot cover a custom endpoint, and
 * an app that adds one should be able to join the same cache rather than build a
 * second one beside it.
 */
export function useQuery<T>(table: string, load: () => Promise<T>): Query<T> {
  const version = useSyncExternalStore(
    (cb) => subscribe(table, cb),
    () => versionOf(table),
    () => 0,
  );
  const [state, setState] = useState<{
    data: T | undefined;
    error: Error | undefined;
    loading: boolean;
  }>({ data: undefined, error: undefined, loading: true });

  useEffect(() => {
    let cancelled = false;
    setState((s) => ({ ...s, loading: true }));
    load().then(
      (data) => !cancelled && setState({ data, error: undefined, loading: false }),
      (e: unknown) =>
        !cancelled &&
        setState({
          data: undefined,
          error: e instanceof Error ? e : new Error(String(e)),
          loading: false,
        }),
    );
    return () => {
      cancelled = true;
    };
    // `load` closes over its arguments and is rebuilt every render; the query is
    // keyed by the table's version, which is what actually changes the answer.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [table, version]);

  return { ...state, refresh: () => invalidate(table) };
}

/**
 * Write through `fn`, then invalidate `table` so every query over it re-runs.
 * Exported for the same reason as `useQuery`.
 */
export function useMutation<A>(table: string, fn: (arg: A) => Promise<unknown>): Mutation<A> {
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<Error | undefined>(undefined);
  const run = useCallback(
    async (arg: A) => {
      setPending(true);
      setError(undefined);
      try {
        await fn(arg);
        invalidate(table);
      } catch (e: unknown) {
        setError(e instanceof Error ? e : new Error(String(e)));
      } finally {
        setPending(false);
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [table],
  );
  return { run, pending, error };
}
"#,
    );

    for table in exposed_tables(tables, endpoints) {
        out.push('\n');
        out.push_str(&table_hooks(table, endpoints));
    }
    out
}

/// The hooks for one table: its row type, the list query, and one mutation per
/// write **the app's API actually projects**.
///
/// Each hook is emitted only when the client has the method it calls. Asking the
/// endpoint set rather than re-deriving the rule (a keyless table has no
/// row-addressed endpoints, an unexposed table has none at all) is what keeps the
/// two halves of the runtime from disagreeing.
fn table_hooks(table: &Table, endpoints: &EndpointSet) -> String {
    let name = &table.name;
    let pascal = pascal(name);
    let row = format!("{pascal}Row");
    let fields = table
        .fields
        .iter()
        .map(|f| {
            let optional = if f.required { "" } else { "?" };
            let null = if f.required { "" } else { " | null" };
            format!(
                "  {}{optional}: {}{null};",
                f.base.name,
                ts_type(basic_type(f))
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let list = op_name("list", name);
    let mut out = format!(
        r#"// --- {name} ---

/** A row of `{name}`, as its columns are today. */
export type {row} = {{
{fields}
}};

/** Every row of `{name}`, re-fetched when anything writes to it. */
export function use{pascal}(): Query<{row}[]> {{
  return useQuery("{name}", () => api.{list}() as Promise<{row}[]>);
}}
"#
    );

    if has_op(endpoints, "create", name) {
        let create = op_name("create", name);
        out.push_str(&format!(
            r#"
/** Insert a row into `{name}`. */
export function useCreate{pascal}(): Mutation<Partial<{row}>> {{
  return useMutation("{name}", (body) => api.{create}(body));
}}
"#
        ));
    }

    // Row-addressed operations: the API projects these only for a table with a
    // single-column primary key, so the hooks follow the endpoints rather than
    // re-deciding it.
    if let Some(pk) = single_pk(table) {
        let pk_ty = table
            .fields
            .iter()
            .find(|f| f.base.name == pk)
            .map_or("string", |f| ts_type(basic_type(f)));
        out.push_str(&format!(
            r#"
/** One row of `{name}`, selected from the list by its primary key. */
export function use{pascal}Row(id: {pk_ty}): Query<{row} | undefined> {{
  const rows = use{pascal}();
  return {{ ...rows, data: rows.data?.find((r) => r.{pk} === id) }};
}}
"#
        ));
        if has_op(endpoints, "update", name) {
            let update = op_name("update", name);
            out.push_str(&format!(
                r#"
/** Replace a row of `{name}`. */
export function useUpdate{pascal}(): Mutation<{{ id: {pk_ty}; body: Partial<{row}> }}> {{
  return useMutation("{name}", ({{ id, body }}) => api.{update}(id, body));
}}
"#
            ));
        }
        if has_op(endpoints, "delete", name) {
            let delete = op_name("delete", name);
            out.push_str(&format!(
                r#"
/** Delete a row of `{name}`. */
export function useDelete{pascal}(): Mutation<{pk_ty}> {{
  return useMutation("{name}", (id) => api.{delete}(id));
}}
"#
            ));
        }
    }
    out
}

// --- naming and type helpers ------------------------------------------------

/// `blog_posts` → `BlogPosts`, matching [`op_name`]'s capitalisation so a hook
/// and the endpoint it calls are named from the same rule.
pub fn pascal(name: &str) -> String {
    op_name("", name)
}

/// A human-facing heading for a table: `blog_posts` → `Blog posts`.
fn title(name: &str) -> String {
    let mut words = name
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty());
    let mut out = String::new();
    if let Some(first) = words.next() {
        let mut chars = first.chars();
        if let Some(c) = chars.next() {
            out.extend(c.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    for word in words {
        out.push(' ');
        out.push_str(word);
    }
    out
}

/// The table's single primary-key column, or `None` when its rows are not
/// addressable (no key, or a composite one).
fn single_pk(table: &Table) -> Option<String> {
    match table.primary_key.as_slice() {
        [pk] => Some(pk.clone()),
        _ => None,
    }
}

fn basic_type(field: &sc_catalog::DataField) -> BasicType {
    field
        .base
        .type_
        .as_basic()
        .cloned()
        .unwrap_or(BasicType::Text)
}

/// The TypeScript type a column's values arrive as over JSON.
fn ts_type(ty: BasicType) -> &'static str {
    match ty {
        BasicType::Bool => "boolean",
        BasicType::Int | BasicType::Float => "number",
        BasicType::Json => "unknown",
        // Decimal, uuid, dates and times all cross the wire as strings.
        _ => "string",
    }
}

/// The empty value a create form starts a column at.
fn ts_empty(field: &sc_catalog::DataField) -> &'static str {
    match basic_type(field) {
        BasicType::Bool => "false",
        BasicType::Int | BasicType::Float | BasicType::Decimal => "0",
        _ => "\"\"",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_api::{ApiProvider, RestProvider};
    use sc_catalog::{AccessRules, DataField, DbId, TableId, TableSource};
    use sc_types::TypeRef;

    fn tasks() -> Table {
        Table {
            id: TableId("tasks".to_owned()),
            name: "tasks".to_owned(),
            database: DbId::primary(),
            source: TableSource::Database,
            fields: vec![
                DataField::plain(
                    "id",
                    TypeRef::from_sql_type("bigint generated by default as identity"),
                )
                .required()
                .primary_key(),
                DataField::plain("title", TypeRef::Basic(BasicType::Text)).required(),
                DataField::plain("done", TypeRef::Basic(BasicType::Bool)),
            ],
            primary_key: vec!["id".to_owned()],
            label: "tasks".to_owned(),
            description: String::new(),
            access: AccessRules::default(),
            attributes: Default::default(),
            overlay: None,
            ownership: None,
            ownership_error: None,
            rls_enabled: false,
        }
    }

    fn endpoints(tables: &[Table]) -> EndpointSet {
        let provider = RestProvider::project("/api", tables);
        let mut set = EndpointSet::new();
        for ep in provider.endpoints().iter() {
            set.register(ep.clone());
        }
        set
    }

    fn file<'a>(files: &'a [GeneratedFile], path: &str) -> &'a str {
        &files
            .iter()
            .find(|f| f.path == path)
            .unwrap_or_else(|| panic!("no {path} in {:?}", files.iter().map(|f| &f.path)))
            .contents
    }

    #[test]
    fn a_project_has_everything_needed_to_build_without_a_shell() {
        let tables = [tasks()];
        let files = project_files("todo", &tables, &endpoints(&tables), None);
        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
        for expected in [
            "package.json",
            "vite.config.ts",
            "tsconfig.json",
            "index.html",
            ".gitignore",
            "src/main.tsx",
            "src/App.tsx",
            "src/routes.tsx",
            "src/auth.tsx",
            "src/Login.tsx",
            "src/app.css",
            "src/pages/Tasks.tsx",
            "src/saltcorn/client.ts",
            "src/saltcorn/hooks.ts",
        ] {
            assert!(paths.contains(&expected), "missing {expected}: {paths:?}");
        }
        // The project is named after the project directory, so `npm` and the
        // admin agree about what this is.
        assert!(file(&files, "package.json").contains("\"name\": \"todo\""));
        // Type-checking is part of building: a generated client that no longer
        // matches the app's calls must fail the build, not the browser.
        assert!(file(&files, "package.json").contains("tsc --noEmit && vite build"));
    }

    #[test]
    fn the_generated_boundary_is_marked_in_the_files_themselves() {
        let tables = [tasks()];
        let files = runtime_files(&tables, &endpoints(&tables), None);
        assert_eq!(files.len(), 2);
        // Both regenerated files say so; nothing else does, because nothing else
        // is overwritten.
        assert!(file(&files, "src/saltcorn/hooks.ts").contains("DO NOT EDIT"));
        assert!(file(&files, "src/saltcorn/client.ts").contains("DO NOT EDIT"));
        let project = project_files("todo", &tables, &endpoints(&tables), None);
        for f in &project {
            if !f.path.starts_with("src/saltcorn/") {
                assert!(!f.contents.contains("DO NOT EDIT"), "{}", f.path);
            }
        }
    }

    /// An app with the GraphQL provider gets two more generated files, and the
    /// schema is marked generated in the comment syntax SDL actually has.
    #[test]
    fn the_graphql_client_and_schema_are_generated_only_for_an_app_that_enables_it() {
        let tables = [tasks()];
        let eps = endpoints(&tables);

        let without = runtime_files(&tables, &eps, None);
        let paths: Vec<&str> = without.iter().map(|f| f.path.as_str()).collect();
        assert!(!paths.contains(&"src/saltcorn/graphql.ts"), "{paths:?}");
        assert!(!paths.contains(&"src/saltcorn/schema.graphql"), "{paths:?}");

        let graphql = AppGraphql {
            mount: "/graphql".to_owned(),
            sdl: "type Query {\n  tasks: [Tasks!]\n}\n".to_owned(),
        };
        let with = runtime_files(&tables, &eps, Some(&graphql));
        // The client posts to the mount the provider is actually mounted at.
        let client = file(&with, "src/saltcorn/graphql.ts");
        assert!(
            client.contains(r#"GRAPHQL_ENDPOINT = "/graphql""#),
            "{client}"
        );
        assert!(client.contains("DO NOT EDIT"), "{client}");
        // The schema is the SDL, under a header GraphQL can parse: `//` is not a
        // comment there, and an unparseable schema breaks the one tool it is for.
        let sdl = file(&with, "src/saltcorn/schema.graphql");
        assert!(sdl.starts_with("# Schema generated by Saltcorn"), "{sdl}");
        assert!(sdl.contains("type Query {"), "{sdl}");
        assert!(!sdl.contains("//"), "{sdl}");
    }

    #[test]
    fn gql_tada_is_configured_against_the_emitted_schema_and_only_then() {
        // Decision 7: no codegen step and nothing new in `package.json` — the
        // configuration is a language-service plugin `tsc` ignores, so the
        // project builds identically whether or not `gql.tada` is installed.
        let plain = tsconfig(false);
        assert!(!plain.contains("gql.tada"), "{plain}");

        let with = tsconfig(true);
        assert!(with.contains("gql.tada/ts-plugin"), "{with}");
        assert!(
            with.contains(r#""schema": "./src/saltcorn/schema.graphql""#),
            "{with}"
        );
        // Still valid JSON with the plugins appended.
        let parsed: serde_json::Value = serde_json::from_str(&with).expect("tsconfig is JSON");
        assert!(parsed["compilerOptions"]["plugins"].is_array(), "{parsed}");
        let plain_parsed: serde_json::Value =
            serde_json::from_str(&plain).expect("tsconfig is JSON");
        assert!(plain_parsed["compilerOptions"]["plugins"].is_null());
    }

    #[test]
    fn hooks_are_typed_per_table_from_the_apps_own_columns() {
        let tables = [tasks()];
        let hooks = hooks_ts(&tables, &endpoints(&tables));
        // The row type is this app's columns, with nullability from the schema —
        // the thing an npm package could not have contained (§2.1).
        assert!(hooks.contains("export type TasksRow = {"), "{hooks}");
        assert!(hooks.contains("  title: string;"), "{hooks}");
        assert!(hooks.contains("  done?: boolean | null;"), "{hooks}");
        // And the hooks call the endpoint names the client was generated with.
        assert!(hooks.contains("api.listTasks()"), "{hooks}");
        assert!(hooks.contains("api.createTasks(body)"), "{hooks}");
        assert!(hooks.contains("api.updateTasks(id, body)"), "{hooks}");
        assert!(hooks.contains("api.deleteTasks(id)"), "{hooks}");
        assert!(hooks.contains("export function useTasks(): Query<TasksRow[]>"));
    }

    #[test]
    fn the_runtime_declares_nothing_it_does_not_export() {
        // The generated project type-checks with `noUnusedLocals`, so a helper
        // that is only *sometimes* called is a build failure waiting for the app
        // that does not call it. That is not hypothetical: an application created
        // before its tables generates a hooks file with no per-table hooks at all,
        // and the shared `useQuery`/`useMutation` underneath them are then dead —
        // `TS6133`, in generated code the admin never wrote, on their first build.
        // Exporting them is also honest: an app adding a custom endpoint should be
        // able to join this cache rather than build a second one beside it.
        let empty = hooks_ts(&[], &EndpointSet::new());
        for declaration in ["function useQuery", "function useMutation"] {
            assert!(
                empty.contains(&format!("export {declaration}")),
                "`{declaration}` must be exported:\n{empty}"
            );
        }
        // The general rule the compiler applies: nothing declared privately may
        // be dead. Private module state (the cache maps) is fine — the exported
        // helpers use it, in every table set — so the check is "is it referenced
        // at all", which is exactly what `noUnusedLocals` asks.
        for tables in [vec![], vec![tasks()]] {
            let hooks = hooks_ts(&tables, &endpoints(&tables));
            for line in hooks.lines() {
                let Some(name) = line
                    .strip_prefix("function ")
                    .or_else(|| line.strip_prefix("const "))
                    .and_then(|rest| {
                        rest.split(['<', '(', ' ', ':', '='].as_slice())
                            .next()
                            .filter(|n| !n.is_empty())
                    })
                else {
                    continue;
                };
                assert!(
                    hooks.matches(name).count() > 1,
                    "`{name}` is declared but never used with {} table(s); \
                     `noUnusedLocals` fails the admin's build over it",
                    tables.len()
                );
            }
        }
    }

    #[test]
    fn a_table_with_no_addressable_row_gets_no_row_hooks() {
        // The REST projection gives a keyless table only list/create, so the
        // hooks must offer only those: generating `useUpdateEvents` would call a
        // method the client does not have, and the build would fail on generated
        // code the admin did not write.
        let mut keyless = tasks();
        keyless.name = "events".to_owned();
        keyless.primary_key.clear();
        keyless.fields.retain(|f| !f.primary_key);
        let tables = [keyless];
        let eps = endpoints(&tables);
        let hooks = hooks_ts(&tables, &eps);
        assert!(hooks.contains("export function useEvents()"));
        assert!(hooks.contains("useCreateEvents"));
        assert!(!hooks.contains("useUpdateEvents"), "{hooks}");
        assert!(!hooks.contains("useDeleteEvents"), "{hooks}");
        // The page for it must not reach for the delete hook either.
        let page = page_tsx(&tables[0], &eps);
        assert!(!page.contains("useDeleteEvents"), "{page}");
    }

    #[test]
    fn routes_are_data_and_authenticated_unless_marked_public() {
        let tables = [tasks(), {
            let mut t = tasks();
            t.name = "notes".to_owned();
            t.id = TableId("notes".to_owned());
            t
        }];
        let eps = endpoints(&tables);
        let exposed = exposed_tables(&tables, &eps);
        let routes = routes_tsx(&exposed, has_auth(&eps));
        // The first table owns `/`; later ones get their own path.
        assert!(routes.contains(r#"{ path: "/", label: "Tasks", element: <TasksPage /> }"#));
        assert!(routes.contains(r#"{ path: "/notes", label: "Notes", element: <NotesPage /> }"#));
        // Only the login route is public — the default is the locked door.
        assert_eq!(routes.matches("public: true").count(), 1);
        assert!(routes.contains(r#"path: "/login""#));
    }

    /// The endpoint set of an app whose provider projects no auth — the GraphQL
    /// provider's two endpoints, and the table endpoints a GraphQL-only app does
    /// not have either. What a page reads is beside the point here; what matters
    /// is that nothing can sign in.
    fn endpoints_without_auth() -> EndpointSet {
        let mut set = EndpointSet::new();
        for ep in endpoints(&[tasks()]).iter() {
            if !sc_api::AUTH_ENDPOINTS.contains(&ep.name.as_str()) {
                set.register(ep.clone());
            }
        }
        set
    }

    /// An application with no auth endpoints — a wholly public API — scaffolds a
    /// client with no auth layer, rather than one that cannot compile.
    #[test]
    fn an_app_that_cannot_sign_anyone_in_gets_a_public_client() {
        let tables = [tasks()];
        let eps = endpoints_without_auth();
        assert!(!has_auth(&eps));
        let files = project_files("todo", &tables, &eps, None);
        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();

        // No auth layer at all: not the files, not the imports of them.
        assert!(!paths.contains(&"src/auth.tsx"), "{paths:?}");
        assert!(!paths.contains(&"src/Login.tsx"), "{paths:?}");
        for path in ["src/main.tsx", "src/App.tsx", "src/routes.tsx"] {
            let src = file(&files, path);
            assert!(!src.contains("./auth"), "{path}: {src}");
            assert!(!src.contains("./Login"), "{path}: {src}");
        }
        // The pages are still there, and still typed against the app's tables:
        // public is a statement about who may read, not about how much app there
        // is.
        assert!(paths.contains(&"src/pages/Tasks.tsx"), "{paths:?}");

        // Every route renders, and none carries a flag about a gate that does not
        // exist.
        let routes = file(&files, "src/routes.tsx");
        assert!(routes.contains(r#"{ path: "/", label: "Tasks", element: <TasksPage /> }"#));
        assert!(!routes.contains("public"), "{routes}");
        assert!(!routes.contains("/login"), "{routes}");
        let app = file(&files, "src/App.tsx");
        assert!(app.contains("element={r.element}"), "{app}");
        assert!(!app.contains("useUser"), "{app}");
        assert!(!app.contains("not signed in"), "{app}");
    }

    /// The same app *with* auth keeps every one of those, so the branch above is a
    /// difference between two apps rather than a feature quietly lost.
    #[test]
    fn an_app_that_can_sign_in_still_gets_the_authenticated_shell() {
        let tables = [tasks()];
        let eps = endpoints(&tables);
        assert!(has_auth(&eps));
        let files = project_files("todo", &tables, &eps, None);
        assert!(file(&files, "src/main.tsx").contains("<AuthProvider>"));
        assert!(file(&files, "src/App.tsx").contains("useUser"));
        assert!(file(&files, "src/App.tsx").contains("r.public || user ? r.element : <Login />"));
        assert!(file(&files, "src/auth.tsx").contains("api.whoami("));
    }

    #[test]
    fn a_create_form_omits_database_generated_keys() {
        // `id` is `generated by default as identity`: offering an input for it
        // would invite an insert that fights the database for the key.
        let tables = [tasks()];
        let page = page_tsx(&tables[0], &endpoints(&tables));
        assert!(!page.contains("form.id"), "{page}");
        assert!(page.contains("form.title"), "{page}");
        // A boolean column gets a checkbox, not a text box.
        assert!(page.contains(r#"type="checkbox""#), "{page}");
        // Every column is still *shown*, including the key.
        assert!(page.contains("String(row.id ?? \"\")"), "{page}");
    }

    #[test]
    fn table_names_become_identifiers_the_same_way_endpoints_do() {
        assert_eq!(pascal("blog_posts"), "BlogPosts");
        assert_eq!(title("blog_posts"), "Blog posts");
        // The hook and the endpoint it calls come from one rule, not two.
        assert_eq!(
            format!("list{}", pascal("blog_posts")),
            op_name("list", "blog_posts")
        );
    }
}
