[package]
name = "sc-auth"
description = "User, Role, sessions, authentication (layer 5)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
sc-error.workspace = true
sc-query.workspace = true
sc-db.workspace = true
sc-catalog.workspace = true
sc-types.workspace = true
serde.workspace = true
uuid.workspace = true

[dev-dependencies]
sc-db-postgres.workspace = true
sc-test-harness.workspace = true
tokio = { workspace = true }

[lints]
workspace = true
