//! A **Python** body running other triggers — `trigger(name).run(...)` — against
//! a real dispatcher, a real database and real trigger rows (phase 3.3 and 3.5).
//!
//! `sc-core-actions/tests/code_run_triggers.rs` in the other language, and it is
//! the same file for the same reason: what is worth pinning is not the surface's
//! shape but the **wiring** — that the call goes through *the* dispatcher, so the
//! target's `only_if`, its floor, its disabled switch and the cascade bound all
//! apply exactly as they do when that trigger fires by itself.
//!
//! Two of these triggers are JavaScript on purpose. A Python body running a
//! JavaScript trigger and a JavaScript body running a Python one are what "one
//! dispatcher, two languages" has to mean, and neither is a special case
//! anywhere in the code — which is worth an assertion rather than an argument.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_action::{
    EventKind, MAX_DEPTH, Trigger, TriggerDispatcher, bootstrap_triggers, save_trigger,
};
use sc_catalog::{CallerContext, Catalog};
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{CodeAdapter, DenoEvaluator};
use sc_python::PythonRuntime;
use sc_test_harness::TestDb;
use serde_json::{Value as Json, json};

/// One table for the children to write into.
const SCHEMA: &str = "
    CREATE TABLE notes (id bigint generated by default as identity primary key,
        what text, who text);
";

struct World {
    catalog: Arc<Catalog>,
    dispatcher: Arc<TriggerDispatcher>,
    _db: TestDb,
}

impl World {
    /// Run `name` as the admin's Run button does, with a caller at `role`.
    async fn run(&self, name: &str, payload: Json, role: u8) -> Result<Json> {
        let caller = CallerContext::new(role, Some(json!({ "email": "ada@example.com" })));
        self.dispatcher
            .run_trigger(&self.catalog, name, payload, Some(&caller))
            .await
    }

    /// The notes, oldest first, as `(what, who)`.
    async fn notes(&self) -> Result<Vec<(String, Option<String>)>> {
        let rows = self
            ._db
            .client()
            .await?
            .query("SELECT what, who FROM notes ORDER BY id", &[])
            .await
            .map_err(|e| Error::database(e.to_string()))?;
        Ok(rows.iter().map(|r| (r.get(0), r.get(1))).collect())
    }
}

/// The trigger set: a child that writes, parents that run it, and the ones whose
/// refusals are the point.
fn triggers() -> Vec<Trigger> {
    vec![
        // The child, in **JavaScript** — so what a Python body runs here is a
        // trigger in the other language, which is the point of there being one
        // dispatcher. It writes a row and reports what it saw: the payload it was
        // handed and the user the *parent's* event carried.
        Trigger::new("write_note", EventKind::None, "run_js_code")
            .min_role(1)
            .config(
                "code",
                r#"await db.notes.insert({ what: payload.what, who: user && user.email });
                   return { wrote: payload.what, by: user && user.email };"#,
            ),
        // The parent, and the whole of the API in three lines. Both spellings of
        // the payload: keywords, and one dict.
        Trigger::new("chase", EventKind::None, "run_python_code").config(
            "code",
            r#"
first = trigger("write_note").run(what=payload["what"])
second = trigger("write_note").run({"what": "and again"})
return {"first": first, "second": second, "known": len(trigger.names) > 0}
"#,
        ),
        // The same call on the caller's behalf, which is where `min_role` decides.
        Trigger::new("chase_as_user", EventKind::None, "run_python_code").config(
            "code",
            r#"
import saltcorn as sc
try:
    return {"ran": trigger("write_note").as_user().run(what="delegated")}
except sc.TriggerError as e:
    return {"refused": str(e)}
"#,
        ),
        // A trigger whose `only_if` is false for this caller: it does not run, and
        // that is not a failure — the body must read `None`.
        Trigger::new("declines", EventKind::Update, "run_python_code")
            .on("notes")
            .only_if("user.email === 'nobody@example.com'")
            .config("code", "return 'ran'"),
        Trigger::new("run_the_decliner", EventKind::None, "run_python_code")
            .config("code", r#"return {"declined": trigger("declines").run()}"#),
        // The one that runs itself: bounded by the chain, not by luck.
        Trigger::new("recurse", EventKind::None, "run_python_code")
            .config("code", r#"return {"deeper": trigger("recurse").run()}"#),
        // A child that fails, and a parent that catches it and carries on.
        Trigger::new("explodes", EventKind::None, "run_python_code")
            .config("code", "raise RuntimeError('the endpoint said no')"),
        Trigger::new("survives", EventKind::None, "run_python_code").config(
            "code",
            r#"
import saltcorn as sc
caught = None
try:
    trigger("explodes").run()
except sc.TriggerError as e:
    caught = str(e)
db.notes.insert(what="carried on", who=None)
return {"caught": caught}
"#,
        ),
        // The two refusals the dispatcher already had, reached this way.
        Trigger::new("run_the_disabled", EventKind::None, "run_python_code").config(
            "code",
            r#"
import saltcorn as sc
try:
    return trigger("switched_off").run()
except sc.TriggerError as e:
    return str(e)
"#,
        ),
        Trigger::new("run_a_typo", EventKind::None, "run_python_code").config(
            "code",
            r#"
import saltcorn as sc
try:
    return trigger("switched_of").run()
except sc.TriggerError as e:
    return str(e)
"#,
        ),
        // The other direction: a **JavaScript** body running a Python trigger, so
        // that "one dispatcher, two languages" is asserted both ways round.
        Trigger::new("in_python", EventKind::None, "run_python_code").config(
            "code",
            r#"
db.notes.insert(what="from python", who=payload.get("by"))
return {"language": "python", "rows": db.notes.count()}
"#,
        ),
        Trigger::new("js_runs_python", EventKind::None, "run_js_code").config(
            "code",
            r#"return await trigger("in_python").run({ by: "javascript" });"#,
        ),
    ]
}

async fn setup() -> Result<World> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    bootstrap_triggers(&catalog).await?;

    let registry = Arc::new(builtin_actions()?);
    let dispatcher = Arc::new(
        TriggerDispatcher::new(Arc::clone(&registry))
            .with_evaluator(Arc::new(DenoEvaluator::new()))
            .with_adapter(Arc::new(PythonRuntime::new()) as Arc<dyn CodeAdapter>),
    );
    for trigger in triggers() {
        save_trigger(&catalog, &registry, &trigger).await?;
    }
    // One that exists and is switched off, which is a different answer from one
    // that does not exist.
    let mut off = Trigger::new("switched_off", EventKind::None, "run_python_code")
        .config("code", "return 'never'");
    off.set_enabled(false);
    save_trigger(&catalog, &registry, &off).await?;
    dispatcher.reload(&catalog).await?;

    Ok(World {
        catalog,
        dispatcher,
        _db: db,
    })
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_python_body_runs_another_trigger_which_really_writes() -> Result<()> {
    let world = setup().await?;
    let result = world
        .run("chase", json!({ "what": "chase the invoice" }), 1)
        .await?;

    // What comes back is what the child's action returned — the same value its
    // caller would get from the Run button — and the child saw the payload this
    // body passed and the user *this* event carried.
    assert_eq!(
        result,
        json!({
            "first": { "wrote": "chase the invoice", "by": "ada@example.com" },
            "second": { "wrote": "and again", "by": "ada@example.com" },
            "known": true,
        })
    );
    // And the rows are there: a child's write is a write, through the row layer.
    assert_eq!(
        world.notes().await?,
        vec![
            (
                "chase the invoice".to_owned(),
                Some("ada@example.com".to_owned())
            ),
            ("and again".to_owned(), Some("ada@example.com".to_owned())),
        ]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_javascript_body_runs_a_python_trigger() -> Result<()> {
    // The other direction, on the one dispatcher: neither language knows the
    // other exists, and the seam between them is a stored trigger's `action`.
    let world = setup().await?;
    let result = world.run("js_runs_python", Json::Null, 1).await?;
    assert_eq!(result, json!({ "language": "python", "rows": 1 }));
    assert_eq!(
        world.notes().await?,
        vec![("from python".to_owned(), Some("javascript".to_owned()))]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn the_targets_floor_decides_a_delegated_run_and_not_the_default_one() -> Result<()> {
    let world = setup().await?;

    // `write_note` is admin-only. Delegated, a caller at role 40 is refused —
    // and it is a *catchable* `TriggerError`, so the body's fallback ran.
    let refused = world.run("chase_as_user", Json::Null, 40).await?;
    let message = refused["refused"].as_str().expect("a refusal");
    assert!(message.contains("write_note"), "{message}");
    assert!(message.contains("role 1"), "{message}");
    assert!(world.notes().await?.is_empty(), "nothing was written");

    // The same body, the same trigger, an admin caller: delegation is the floor,
    // and the floor is met.
    let ran = world.run("chase_as_user", Json::Null, 1).await?;
    assert_eq!(ran["ran"]["wrote"], json!("delegated"));

    // And without `as_user()` the floor is not consulted at all: a trigger is
    // server-side configuration, so a body run by a public caller may still run
    // an admin-only trigger — which is what `chase` does here at role 100.
    let world = setup().await?;
    let result = world
        .run("chase", json!({ "what": "by the server" }), 100)
        .await?;
    assert_eq!(result["first"]["wrote"], json!("by the server"));
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_declining_only_if_is_none_and_not_a_failure() -> Result<()> {
    let world = setup().await?;
    // The target's `only_if` is false for this event's caller, so its action does
    // not run — which is not a failure, and reads as `None` in the body exactly
    // as it reads as `null` in a JavaScript one.
    assert_eq!(
        world.run("run_the_decliner", Json::Null, 1).await?,
        json!({ "declined": null })
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_python_body_that_runs_itself_stops_at_the_cascade_bound() -> Result<()> {
    let world = setup().await?;
    let error = world
        .run("recurse", Json::Null, 1)
        .await
        .expect_err("the chain is bounded");
    let message = error.to_string();
    // The bound `Event::firing` applies to every other cascade, reached this way
    // — and the diagnosis is the chain, not a depth counter. Nesting is what §6's
    // admission exemption exists for: every level but the innermost is parked in
    // a host call, so without it this would deadlock rather than answer.
    assert!(
        message.contains(&format!("limit of {MAX_DEPTH}")),
        "{message}"
    );
    assert!(
        message.matches("recurse").count() > MAX_DEPTH,
        "the whole chain is named: {message}"
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_failing_child_is_catchable_and_the_parent_carries_on() -> Result<()> {
    let world = setup().await?;
    let result = world.run("survives", Json::Null, 1).await?;
    let caught = result["caught"].as_str().expect("the child's failure");
    assert!(caught.contains("the endpoint said no"), "{caught}");
    // The parent finished: its own write is there, and it returned normally.
    assert_eq!(world.notes().await?, vec![("carried on".to_owned(), None)]);
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_disabled_trigger_and_a_typo_are_different_answers() -> Result<()> {
    let world = setup().await?;

    // Disabled means disabled however it is asked — including from a Python body.
    let disabled = world.run("run_the_disabled", Json::Null, 1).await?;
    let message = disabled.as_str().expect("a message");
    assert!(message.contains("switched_off"), "{message}");
    assert!(message.contains("disabled"), "{message}");

    // A name that does not exist is refused where the typo is, naming what does:
    // the list travelled into the run when it started, and is read off the run's
    // own thread rather than fetched.
    let typo = world.run("run_a_typo", Json::Null, 1).await?;
    let message = typo.as_str().expect("a message");
    assert!(
        message.contains("no trigger named `switched_of`"),
        "{message}"
    );
    assert!(message.contains("switched_off"), "{message}");
    Ok(())
}
