//! `fetch` from a **Python** body, against a real socket and the real action
//! (phase 3.1 and 3.5).
//!
//! `python_db_live.rs`'s argument, applied to the second surface: what can be
//! wrong here is what was sent and what was made of the reply, and a mocked
//! client would assert those about a request that never happened. So this file
//! holds the production pieces — the `run_python_code` action from the registry,
//! the five hosts it builds from an `ActionContext`, `CodeFetchHost` and its
//! `reqwest` client — and a one-shot listener that reports the bytes it read.
//! It is `sc-core-actions/tests/code_fetch.rs` question for question, in the
//! other language, because the `FetchHost` under both is the same one.
//!
//! Asserted here: a body's GET and POST arrive as written; the response's
//! status, headers and JSON come back; a non-2xx is a value rather than an
//! exception, so a retry is something the body writes; a request the endpoint
//! never answers fails inside the body's own time limit and is catchable as a
//! `FetchError`; bytes that are not text arrive as `bytes`; the fetch budget's
//! refusal names the bound; and a body with no network at all says so as a
//! `NameError`.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use sc_action::{ActionContext, Event, EventKind};
use sc_catalog::{Catalog, bootstrap_file_stores};
use sc_core_actions::builtin_actions;
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{CodeAdapter, CodeCall, PYTHON};
use sc_files::LocalFileStore;
use sc_python::PythonRuntime;
use sc_test_harness::TestDb;
use sc_types::Attrs;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio::sync::oneshot;

use serde_json::{Value as Json, json};

/// Somewhere for a body to put what it fetched.
const SCHEMA: &str = "\
    CREATE TABLE quotes (id bigint generated by default as identity primary key, \
        who text, what text);";

async fn setup(db: &TestDb) -> Result<Catalog> {
    db.client()
        .await?
        .batch_execute(SCHEMA)
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    Catalog::init(driver as Arc<dyn DatabaseDriver>).await
}

/// The event every test fires: a directly-run trigger with a payload.
fn fired(payload: Json) -> Event {
    Event::new(EventKind::None)
        .payload(payload)
        .caller(1, Some(json!({ "email": "admin@example.com" })))
}

/// The adapters a dispatcher hands every action it runs — here, one.
fn adapters() -> BTreeMap<String, Arc<dyn CodeAdapter>> {
    let runtime: Arc<dyn CodeAdapter> = Arc::new(PythonRuntime::new());
    [(PYTHON.to_owned(), runtime)].into_iter().collect()
}

/// Run `run_python_code` through the registry — the path a firing trigger takes,
/// and the reason this is not `PythonRuntime::run` with hosts built by hand: the
/// five surfaces come from `ActionContext` exactly as they do in a server.
async fn run(catalog: &Catalog, event: &Event, code: &str) -> Result<Json> {
    let adapters = adapters();
    let registry = builtin_actions()?;
    let action = registry.require("run_python_code")?.clone();
    let cfg: Attrs = [("code".to_owned(), json!(code))].into_iter().collect();
    let mut ctx = ActionContext::new(catalog, event, &cfg, "sync").with_adapters(&adapters);
    action.run(&mut ctx).await
}

/// What the listener saw.
struct Received {
    start_line: String,
    headers: Vec<(String, String)>,
    body: String,
}

impl Received {
    fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, v)| v.as_str())
    }
}

/// A listener that answers `count` requests with the same reply, and hands each
/// request it read back through the channel.
async fn serving(
    count: usize,
    status: u16,
    content_type: &str,
    body: &str,
) -> (String, oneshot::Receiver<Vec<Received>>) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/hook", listener.local_addr().unwrap());
    let response = format!(
        "HTTP/1.1 {status} X\r\ncontent-type: {content_type}\r\ncontent-length: {}\r\n\
         connection: close\r\n\r\n{body}",
        body.len()
    );
    let (tx, rx) = oneshot::channel();
    tokio::spawn(async move {
        let mut seen = Vec::new();
        for _ in 0..count {
            let (mut socket, _) = listener.accept().await.unwrap();
            seen.push(read_request(&mut socket).await);
            socket.write_all(response.as_bytes()).await.unwrap();
            socket.flush().await.unwrap();
        }
        let _ = tx.send(seen);
    });
    (url, rx)
}

/// The same, answering **bytes** that are not text — a PNG, as far as anything
/// here is concerned.
async fn serving_bytes(body: Vec<u8>) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/blob", listener.local_addr().unwrap());
    let head = format!(
        "HTTP/1.1 200 OK\r\ncontent-type: application/octet-stream\r\n\
         content-length: {}\r\nconnection: close\r\n\r\n",
        body.len()
    );
    tokio::spawn(async move {
        let (mut socket, _) = listener.accept().await.unwrap();
        read_request(&mut socket).await;
        socket.write_all(head.as_bytes()).await.unwrap();
        socket.write_all(&body).await.unwrap();
        socket.flush().await.unwrap();
    });
    url
}

/// A listener that accepts and then says nothing — a hung endpoint.
async fn hangs() -> String {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let url = format!("http://{}/hook", listener.local_addr().unwrap());
    tokio::spawn(async move {
        let (socket, _) = listener.accept().await.unwrap();
        tokio::time::sleep(Duration::from_secs(30)).await;
        drop(socket);
    });
    url
}

/// Read one HTTP request: headers, then exactly `content-length` bytes of body.
async fn read_request(socket: &mut tokio::net::TcpStream) -> Received {
    let mut buf = Vec::new();
    let mut chunk = [0_u8; 1024];
    loop {
        if let Some(head_end) = find(&buf, b"\r\n\r\n") {
            let head = String::from_utf8_lossy(&buf[..head_end]).to_string();
            let wanted = content_length(&head);
            if buf.len() >= head_end + 4 + wanted {
                let mut lines = head.split("\r\n");
                let start_line = lines.next().unwrap_or_default().to_owned();
                let headers = lines
                    .filter_map(|line| line.split_once(": "))
                    .map(|(n, v)| (n.to_ascii_lowercase(), v.to_owned()))
                    .collect();
                let body = String::from_utf8_lossy(&buf[head_end + 4..]).to_string();
                return Received {
                    start_line,
                    headers,
                    body,
                };
            }
        }
        let n = socket.read(&mut chunk).await.unwrap_or(0);
        assert!(n > 0, "the client closed before sending a whole request");
        buf.extend_from_slice(&chunk[..n]);
    }
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

fn content_length(head: &str) -> usize {
    head.split("\r\n")
        .filter_map(|line| line.split_once(": "))
        .find(|(name, _)| name.eq_ignore_ascii_case("content-length"))
        .and_then(|(_, value)| value.trim().parse().ok())
        .unwrap_or(0)
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_body_fetches_json_and_reads_the_response() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(1, 200, "application/json", r#"{"who":"Ada","what":"hi"}"#).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
res = fetch(payload["url"], headers={"x-token": "s3cret"})
if not res.ok:
    raise RuntimeError(f"unexpected {res.status}")
quote = res.json()
return {
    "status": res.status,
    # Case-insensitively, as every other header API reads them.
    "type": res.headers["Content-Type"],
    "who": quote["who"],
    "ok": res.ok,
    "text_is_the_body": res.text == '{"who":"Ada","what":"hi"}',
}
"#,
    )
    .await?;
    assert_eq!(
        result,
        json!({
            "status": 200,
            "type": "application/json",
            "who": "Ada",
            "ok": true,
            "text_is_the_body": true,
        })
    );

    let requests = received.await.unwrap();
    assert_eq!(requests.len(), 1);
    // A GET, at the path the body asked for, carrying the header it set and no
    // body at all.
    assert!(
        requests[0].start_line.starts_with("GET /hook "),
        "{}",
        requests[0].start_line
    );
    assert_eq!(requests[0].header("x-token"), Some("s3cret"));
    assert_eq!(requests[0].body, "");
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_body_posts_json_and_writes_what_it_got_back() -> Result<()> {
    // The reason `fetch` belongs in a body rather than only in an action: the
    // response is a value, and the next thing the body does is write it — with
    // no `await` between the two, which is this language's whole difference.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(1, 201, "application/json", r#"{"who":"Bob","what":"ta"}"#).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
res = fetch(payload["url"], "POST", json={"asking": "for a quote", "n": 2})
quote = res.json()
written = db.quotes.insert(who=quote["who"], what=quote["what"])
return {"status": res.status, "id": written["id"], "who": written["who"]}
"#,
    )
    .await?;
    assert_eq!(result["status"], json!(201));
    assert_eq!(result["who"], json!("Bob"));

    let requests = received.await.unwrap();
    assert!(
        requests[0].start_line.starts_with("POST /hook "),
        "{}",
        requests[0].start_line
    );
    // `json=` sends JSON and sets the content type — the one thing `requests`
    // spells the same way and the one `data=` deliberately refuses to guess at.
    assert_eq!(requests[0].header("content-type"), Some("application/json"));
    assert_eq!(requests[0].body, r#"{"asking": "for a quote", "n": 2}"#);

    // And the row is really there, in the same run that fetched it — read out of
    // the database rather than out of the action's own answer.
    let stored = db
        .client()
        .await?
        .query("SELECT who, what FROM quotes ORDER BY id", &[])
        .await
        .map_err(|e| Error::database(e.to_string()))?;
    let quotes: Vec<(String, String)> = stored
        .iter()
        .map(|r| (r.get::<_, String>(0), r.get::<_, String>(1)))
        .collect();
    assert_eq!(quotes, vec![("Bob".to_owned(), "ta".to_owned())]);
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_body_writes_what_it_fetched_into_a_file_store() -> Result<()> {
    // The milestone's own sentence, in one body: call an endpoint, write what it
    // said into a store, run nothing else. Two surfaces in one run, with no
    // `await` between them — and the bytes never enter the interpreter for the
    // second one, because `write(response)` hands the host what it already has.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    bootstrap_file_stores(&catalog).await?;
    let dir = std::env::temp_dir().join(format!("sc-python-fetch-fs-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    catalog.connect_file_store(Arc::new(LocalFileStore::new("docs", &dir)?))?;
    let (url, _received) = serving(1, 200, "application/json", r#"{"usd":1.07}"#).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
res = fetch(payload["url"])
saved = fs("docs").open("rates/today.json").write(res)
return {"saved": saved, "usd": fs("docs").open("rates/today.json").read_json()["usd"]}
"#,
    )
    .await?;
    assert_eq!(result["saved"], json!(12));
    assert_eq!(result["usd"], json!(1.07));
    assert_eq!(
        std::fs::read_to_string(dir.join("rates/today.json")).unwrap(),
        r#"{"usd":1.07}"#,
        "the endpoint's own bytes, not a re-encoding of them"
    );

    std::fs::remove_dir_all(&dir).ok();
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_request_body_travels_as_written_for_text_and_for_bytes() -> Result<()> {
    // `data=` is `requests`' "send this as it is", and here it means exactly
    // that for both of the two things it can be. What it is **not** is a form
    // encoder: a dict in `data=` is refused naming `json=`, because an object
    // that reached an endpoint as `a=1&b=2` when JSON was meant is a bug that
    // looks like a working request.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(2, 200, "text/plain", "ok").await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
fetch(payload["url"], "PUT", data="plain words")
fetch(payload["url"], "POST", data=b"", headers={"x-kind": "raw"})
said = {}
try:
    fetch(payload["url"], "POST", data={"a": 1})
except TypeError as e:
    said["dict"] = str(e)
try:
    fetch(payload["url"], json={"a": 1})
except TypeError as e:
    said["get"] = str(e)
try:
    fetch(payload["url"], timeout=1, timeout_ms=1000)
except TypeError as e:
    said["clocks"] = str(e)
return said
"#,
    )
    .await?;
    assert!(
        result["dict"].as_str().unwrap().contains("`json=`"),
        "{result}"
    );
    assert!(
        result["get"]
            .as_str()
            .unwrap()
            .contains("cannot carry a body"),
        "{result}"
    );
    assert!(
        result["clocks"].as_str().unwrap().contains("not both"),
        "{result}"
    );

    let requests = received.await.unwrap();
    assert!(
        requests[0].start_line.starts_with("PUT "),
        "{}",
        requests[0].start_line
    );
    assert_eq!(requests[0].body, "plain words");
    assert_eq!(
        requests[0].header("content-type"),
        Some("text/plain;charset=UTF-8"),
        "text says so, unless the body set one itself"
    );
    // Bytes cross the seam base64'd and arrive as themselves.
    assert_eq!(requests[1].body.as_bytes(), b"");
    assert_eq!(
        requests[1].header("content-type"),
        Some("application/octet-stream")
    );
    assert_eq!(requests[1].header("x-kind"), Some("raw"));
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_status_the_endpoint_did_not_like_is_a_value_the_body_can_branch_on() -> Result<()> {
    // `requests`' rule and the web's, and the one that makes a body readable: a
    // 503 is an answer, so the retry is written in the body rather than being a
    // trigger that failed.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, received) = serving(2, 503, "text/plain", "busy, try later").await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
tries = 0
last = None
while tries < 2:
    tries += 1
    res = fetch(payload["url"])
    if res.ok:
        return {"tries": tries, "body": res.text}
    last = {"status": res.status, "text": res.text}
return {"tries": tries, "gave_up": last}
"#,
    )
    .await?;
    assert_eq!(
        result,
        json!({ "tries": 2, "gave_up": { "status": 503, "text": "busy, try later" } })
    );
    assert_eq!(received.await.unwrap().len(), 2, "both tries were sent");

    // And `raise_for_status()` is the other spelling, for a body that would
    // rather not branch — an ordinary catchable `FetchError`.
    let (url, _received) = serving(1, 503, "text/plain", "busy").await;
    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
import saltcorn as sc
try:
    fetch(payload["url"]).raise_for_status()
    return "allowed"
except sc.FetchError as e:
    return str(e)
"#,
    )
    .await?;
    assert!(result.as_str().unwrap().contains("503"), "{result}");
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn an_endpoint_that_never_answers_fails_inside_the_bodys_own_time_limit() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let url = hangs().await;

    // A request is clamped to what is left of the run, so a body that catches the
    // failure still gets to finish — and the trigger's caller is held for the
    // body's timeout and not for the endpoint's silence. `timeout=60` is
    // `requests`' spelling, in seconds, and it is a ceiling rather than a grant.
    let started = Instant::now();
    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
import saltcorn as sc
try:
    fetch(payload["url"], timeout=60)
    return "answered"
except sc.FetchError as e:
    return {"failed": type(e).__name__, "message": str(e)}
"#,
    )
    .await?;
    let elapsed = started.elapsed();
    assert_eq!(result["failed"], json!("FetchError"), "{result}");
    assert!(
        result["message"].as_str().unwrap().contains("timed out"),
        "{result}"
    );
    assert!(
        elapsed < Duration::from_secs(15),
        "the minute the body asked for was allowed: {elapsed:?}"
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_response_that_is_not_text_arrives_as_bytes() -> Result<()> {
    // The seam is JSON and JSON has no bytes, so a response that is not valid
    // UTF-8 crosses base64'd — and `.text` still answers what a browser's would,
    // which is the same bytes decoded lossily. Both are properties, as
    // `requests`' are: the body arrived with the response, so reading it twice is
    // not a second read.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let url = serving_bytes(vec![0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a]).await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
res = fetch(payload["url"])
raw = res.content
return {
    "type": res.headers.get("content-type"),
    "bytes": list(raw),
    "signature": raw[1:4] == b"PNG",
    "text_still_reads": len(res.text) > 0,
    "read_twice": res.content == raw,
}
"#,
    )
    .await?;
    assert_eq!(
        result["bytes"],
        json!([0x89, 80, 78, 71, 0x0d, 0x0a, 0x1a, 0x0a]),
        "{result}"
    );
    assert_eq!(result["signature"], json!(true));
    assert_eq!(result["type"], json!("application/octet-stream"));
    assert_eq!(result["text_still_reads"], json!(true));
    assert_eq!(
        result["read_twice"],
        json!(true),
        "a property, not a stream"
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_scheme_that_is_not_http_is_refused_by_name() -> Result<()> {
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    // The rule the `fetch` action has, in the place a body would reach for it:
    // "call an endpoint" is not "read a file on the server". Refused by the
    // **host**, which is why it is the same sentence in both languages.
    let result = run(
        &catalog,
        &fired(Json::Null),
        r#"
import saltcorn as sc
try:
    fetch("file:///etc/passwd")
    return "read it"
except sc.FetchError as e:
    return str(e)
"#,
    )
    .await?;
    assert!(
        result
            .as_str()
            .unwrap()
            .contains("scheme must be http or https"),
        "{result}"
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn the_fetch_budget_is_the_javascript_ones_and_names_what_it_is_for() -> Result<()> {
    // The budget is a bound on what the **host** is asked to do, so it is the
    // same number and the same sentence in both languages — asserted here rather
    // than trusted, because a per-language counter is exactly the kind of thing
    // that drifts.
    let db = TestDb::new().await?;
    let catalog = setup(&db).await?;
    let (url, _received) = serving(64, 200, "text/plain", "ok").await;

    let result = run(
        &catalog,
        &fired(json!({ "url": url })),
        r#"
import saltcorn as sc
sent = 0
try:
    while True:
        fetch(payload["url"])
        sent += 1
except sc.FetchError as e:
    return {"sent": sent, "said": str(e)}
return {"sent": sent, "said": None}
"#,
    )
    .await?;
    assert_eq!(
        result["sent"].as_u64(),
        Some(u64::from(sc_expr::DEFAULT_MAX_FETCHES)),
        "{result}"
    );
    let said = result["said"].as_str().unwrap_or_default();
    assert!(said.contains("fetch requests in one run"), "{said}");
    assert!(
        said.contains("hammer somebody else's server"),
        "the bound says what it is for: {said}"
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_body_with_no_network_has_no_name_for_it() -> Result<()> {
    // Presence is scope: a run with no `FetchHost` is not handed a `fetch` that
    // refuses, it is handed nothing at all.
    let error = PythonRuntime::new()
        .run(CodeCall {
            code: "return fetch(\"http://example.com\")".to_owned(),
            ..CodeCall::default()
        })
        .await
        .expect_err("a pure body cannot reach the network");
    let said = error.to_string();
    assert!(said.contains("NameError"), "{said}");
    assert!(said.contains("fetch"), "{said}");

    // And reached the long way round, through the package, it refuses by saying
    // what this run does not have.
    let error = PythonRuntime::new()
        .run(CodeCall {
            code: "import saltcorn\nreturn saltcorn.fetch(\"http://example.com\")".to_owned(),
            ..CodeCall::default()
        })
        .await
        .expect_err("still no network");
    assert!(
        error.to_string().contains("cannot reach the network"),
        "{error}"
    );
    Ok(())
}
