//! `db` from a Python body, against a **real** database (phase 2.6 and 2.7).
//!
//! `python_db.rs` pins the lowering: every chain method against a recorder, so a
//! plan can be read and compared with the JavaScript one. What a recorder cannot
//! answer is whether the plan a chain lowers to is one this server's host
//! actually executes, and against which rows — a spelling mistake in an operator,
//! a projection the host reads differently, an aggregate whose argument never
//! reaches SQL would all pass there and fail here.
//!
//! So this file holds the production pieces and nothing else: the catalog over
//! Postgres, the `TableHost` an action builds, the ownership formula on the V8
//! isolate, the dispatcher a write's event reaches. It mirrors
//! `sc-core-actions/tests/run_js_code.rs`, question for question, and ends with
//! the one that is the point of the milestone — the same question in the two
//! languages, answered the same way, **because it is the same plan**.

use std::sync::{Arc, Mutex};

use async_trait::async_trait;
use sc_action::{
    Action, ActionContext, ActionRegistry, EventKind, Trigger, TriggerDispatcher,
    bootstrap_triggers, save_trigger,
};
use sc_api::code_host::TableHost;
use sc_catalog::{Catalog, TableMeta, bootstrap_table_meta, save_table_meta};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_error::{Error, Result};
use sc_expr::{CodeCall, DenoEvaluator, JsEvaluator};
use sc_python::PythonRuntime;
use sc_test_harness::TestDb;
use sc_types::FormField;
use serde_json::{Value as Json, json};

/// Authors, their books, an audit table for a trigger to write into, and notes
/// an ownership formula divides — `run_js_code.rs`'s tables, so the two suites
/// ask their questions of the same rows.
const SCHEMA: &str = "\
    CREATE TABLE authors (id bigint generated by default as identity primary key, \
        name text, tier text); \
    CREATE TABLE books (id bigint generated by default as identity primary key, \
        title text not null, pages bigint, author bigint references authors(id)); \
    CREATE TABLE audit (id bigint generated by default as identity primary key, \
        what text, who text); \
    CREATE TABLE notes (id bigint generated by default as identity primary key, \
        what text, owner text); \
    INSERT INTO authors (name, tier) VALUES ('Ada', 'gold'), ('Bob', 'silver'); \
    INSERT INTO books (title, pages, author) VALUES \
        ('Dune', 412, 1), \
        ('Emma', 474, 1), \
        ('Ficciones', 174, 2), \
        ('Solaris', NULL, 2); \
    INSERT INTO notes (what, owner) VALUES \
        ('ada one', 'ada@example.com'), \
        ('bob one', 'bob@example.com'), \
        ('ada two', 'ada@example.com');";

/// The caller every body here runs on behalf of: ada, at a role well below
/// admin, so `as_user()` has something to be different from.
fn ada() -> Json {
    json!({
        "id": "6b1c2d64-3f3a-4a52-9a8b-0f4d2b7f1a11",
        "role": 40,
        "email": "ada@example.com",
    })
}

/// The database, the catalog, and the JavaScript engine an ownership formula is
/// decided on.
struct Live {
    catalog: Arc<Catalog>,
    evaluator: Arc<dyn JsEvaluator>,
    db: TestDb,
}

impl Live {
    async fn new() -> Result<Live> {
        let db = TestDb::new().await?;
        db.client()
            .await?
            .batch_execute(SCHEMA)
            .await
            .map_err(|e| Error::database(e.to_string()))?;
        let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
        let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
        Ok(Live {
            catalog,
            evaluator: Arc::new(DenoEvaluator::new()) as Arc<dyn JsEvaluator>,
            db,
        })
    }

    /// `owner === user.email` live on `notes`, which is what `as_user()` has to
    /// obey and what the body's own authority does not.
    async fn own_the_notes(&self) -> Result<()> {
        bootstrap_table_meta(&self.catalog).await?;
        let mut notes = TableMeta::new("notes");
        notes.set_ownership_formula(Some("owner === user.email"));
        save_table_meta(&self.catalog, &notes).await?;
        assert!(
            self.catalog.require("notes")?.ownership.is_some(),
            "the formula is live"
        );
        Ok(())
    }

    /// The host an action builds for one run: this catalog, caused by ada, with
    /// the formula engine behind a delegated read.
    fn host(&self) -> TableHost<'_> {
        TableHost::new(&self.catalog)
            .caused_by(40, Some(ada()))
            .with_evaluator(Some(Arc::clone(&self.evaluator)))
    }

    /// Run a Python body over that host and answer what it returned.
    async fn run(&self, code: &str) -> Result<Json> {
        let host = self.host();
        PythonRuntime::new()
            .run(CodeCall {
                code: code.to_owned(),
                host: Some(&host as &dyn sc_expr::CodeHost),
                bindings: [("payload".to_owned(), json!({ "least": 200 }))]
                    .into_iter()
                    .collect(),
                ..CodeCall::default()
            })
            .await
    }

    /// The same, for a body that is meant to fail: the message it failed with.
    async fn fails(&self, code: &str) -> String {
        self.run(code)
            .await
            .expect_err("this body was supposed to fail")
            .to_string()
    }

    /// The same question as a **JavaScript** body, on the engine that runs one —
    /// phase 2.7's other half.
    async fn run_js(&self, code: &str) -> Result<Json> {
        let host = self.host();
        self.evaluator
            .run_code(CodeCall {
                code: code.to_owned(),
                host: Some(&host as &dyn sc_expr::CodeHost),
                bindings: [("payload".to_owned(), json!({ "least": 200 }))]
                    .into_iter()
                    .collect(),
                ..CodeCall::default()
            })
            .await
    }

    /// One column of one table, read back with SQL rather than through the
    /// surface under test.
    async fn column(&self, sql: &str) -> Result<Vec<String>> {
        let rows = self
            .db
            .client()
            .await?
            .query(sql, &[])
            .await
            .map_err(|e| Error::database(e.to_string()))?;
        Ok(rows.iter().map(|r| r.get::<_, String>(0)).collect())
    }
}

// ---------------------------------------------------------------------------
// The chain and the terminals, against rows that are really there
// ---------------------------------------------------------------------------

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn every_chain_method_and_terminal_answers_the_real_rows() -> Result<()> {
    let live = Live::new().await?;

    // The reads: a narrowed, projected, sorted, bounded select, and then each
    // scalar terminal over the same table.
    let out = live
        .run(
            r#"
long = (db.books
    .where(pages__gte=payload["least"])
    .select("title", "pages")
    .order_by("pages", "desc")
    .limit(2)
    .rows())
paged = db.books.order_by("title").offset(1).limit(2).select("title").rows()
return {
    "long": [b["title"] for b in long],
    "paged": [b["title"] for b in paged],
    "first": db.books.order_by("title").first()["title"],
    "got": db.books.get(3)["title"],
    "missing": db.books.get(999),
    "exists": db.books.where(title="Dune").exists(),
    "absent": db.books.where(title="Nothing").exists(),
    "n": db.books.count(),
    "pages": db.books.sum("pages"),
    "least": db.books.min("pages"),
    "most": db.books.max("pages"),
}
"#,
        )
        .await?;
    assert_eq!(
        out,
        json!({
            "long": ["Emma", "Dune"],
            "paged": ["Emma", "Ficciones"],
            "first": "Dune",
            "got": "Ficciones",
            "missing": Json::Null,
            "exists": true,
            "absent": false,
            "n": 4,
            // `sum` over a bigint column is an exact decimal on the wire, not a
            // float that might not be — the JavaScript body sees the same.
            "pages": "1060",
            "least": 174,
            "most": 474,
        })
    );

    // And the writes, each read back with SQL rather than believed from the
    // body's own answer.
    let out = live
        .run(
            r#"
made = db.books.insert(title="Ubik", pages=224, author=2)
changed = db.books.where(title="Ubik").update(pages=225)
gone = db.books.where(title="Solaris").delete()
return {"made": made["title"], "changed": changed, "gone": gone}
"#,
        )
        .await?;
    // A write answers what the **host** answers, which is what a JavaScript body
    // gets: the new row for an insert, and how many rows changed *and which* for
    // an update or a delete — the keys are the caller's evidence and the surface
    // does not reshape them on the way past.
    assert_eq!(
        out,
        json!({
            "made": "Ubik",
            "changed": { "updated": 1, "ids": [5] },
            "gone": { "deleted": 1, "ids": [4] },
        })
    );
    assert_eq!(
        live.column("SELECT title FROM books ORDER BY title")
            .await?,
        vec!["Dune", "Emma", "Ficciones", "Ubik"]
    );
    assert_eq!(
        live.column("SELECT pages::text FROM books WHERE title = 'Ubik'")
            .await?,
        vec!["225"]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn the_two_where_spellings_and_the_keyword_operators_choose_the_same_rows() -> Result<()> {
    let live = Live::new().await?;

    let out = live
        .run(
            r#"
import saltcorn as sc

def titles(query):
    return sorted(b["title"] for b in query.select("title").rows())

return {
    "eq": titles(db.books.where(title="Dune")),
    "ne": titles(db.books.where(title__ne="Dune")),
    "gt": titles(db.books.where(pages__gt=412)),
    "gte": titles(db.books.where(pages__gte=412)),
    "lt": titles(db.books.where(pages__lt=412)),
    "lte": titles(db.books.where(pages__lte=412)),
    "in": titles(db.books.where(title__in=["Dune", "Emma"])),
    "nin": titles(db.books.where(title__nin=["Dune", "Emma"])),
    # A pattern is SQL's, bound as the text it is rather than wrapped: what the
    # body writes is what LIKE gets.
    "like": titles(db.books.where(title__like="%mm%")),
    "ilike": titles(db.books.where(title__ilike="dun%")),
    "is_null": titles(db.books.where(pages__is_null=True)),
    # The dict DSL every other surface speaks, and the formula for what it
    # cannot say — the same rows as the keywords above.
    "dict": titles(db.books.where({"pages": {"gte": 412}})),
    "formula": titles(db.books.where("pages >= 412")),
    # Several kwargs and several calls are ANDed; or_/not_ say the rest.
    "and": titles(db.books.where(author=1).where(pages__lt=450)),
    "or": titles(db.books.where(sc.or_({"title": "Dune"}, {"title": "Solaris"}))),
    "not": titles(db.books.where(sc.not_({"author": 1}))),
}
"#,
        )
        .await?;
    assert_eq!(
        out,
        json!({
            "eq": ["Dune"],
            "ne": ["Emma", "Ficciones", "Solaris"],
            "gt": ["Emma"],
            "gte": ["Dune", "Emma"],
            "lt": ["Ficciones"],
            "lte": ["Dune", "Ficciones"],
            "in": ["Dune", "Emma"],
            "nin": ["Ficciones", "Solaris"],
            "like": ["Emma"],
            "ilike": ["Dune"],
            "is_null": ["Solaris"],
            "dict": ["Dune", "Emma"],
            "formula": ["Dune", "Emma"],
            "and": ["Dune"],
            "or": ["Dune", "Solaris"],
            "not": ["Ficciones", "Solaris"],
        })
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_join_path_in_a_select_and_an_aggregate_with_a_group() -> Result<()> {
    let live = Live::new().await?;

    let out = live
        .run(
            r#"
joined = (db.books
    .where(pages__is_null=False)
    .select("title", "authorⱵname", written="authorⱵtier")
    .order_by("title")
    .rows())
by_author = (db.books
    .group_by("author")
    .aggregate(total="sum(pages)", n="count()")
    .having(n__gte=2)
    .order_by("author")
    .rows())
return {"joined": joined, "by_author": by_author}
"#,
        )
        .await?;
    assert_eq!(
        out["joined"],
        json!([
            { "title": "Dune", "authorⱵname": "Ada", "written": "gold" },
            { "title": "Emma", "authorⱵname": "Ada", "written": "gold" },
            { "title": "Ficciones", "authorⱵname": "Bob", "written": "silver" },
        ])
    );
    // Both authors have two books; Bob's pages are one row short of two values,
    // which is what makes `sum` over a null worth asserting.
    assert_eq!(
        out["by_author"],
        json!([
            { "author": 1, "total": "886", "n": 2 },
            { "author": 2, "total": "174", "n": 2 },
        ])
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn iter_walks_more_rows_than_one_batch_and_stops_where_the_loop_does() -> Result<()> {
    let live = Live::new().await?;
    // Enough rows that a batch of five is several host calls rather than one.
    live.db
        .client()
        .await?
        .batch_execute(
            "INSERT INTO books (title, pages, author) \
             SELECT 'B' || lpad(n::text, 3, '0'), n, 1 FROM generate_series(1, 25) n;",
        )
        .await
        .map_err(|e| Error::database(e.to_string()))?;

    let out = live
        .run(
            r#"
walked = [b["title"] for b in db.books.where(title__like="B%").order_by("title").iter(batch=5)]
# A loop that stops early has paid for only what it read: nothing is fetched
# until the loop asks for it.
early = []
for b in db.books.where(title__like="B%").order_by("title").iter(batch=5):
    early.append(b["title"])
    if len(early) == 3:
        break
# Iterating the query itself is the same walk, and a query is reusable.
q = db.books.where(title__like="B%").order_by("title")
twice = [len([b for b in q]), len([b for b in q])]
return {"walked": walked, "early": early, "twice": twice}
"#,
        )
        .await?;
    let walked = out["walked"].as_array().expect("a list");
    assert_eq!(walked.len(), 25, "every row, over several batches");
    assert_eq!(walked[0], json!("B001"));
    assert_eq!(walked[24], json!("B025"));
    assert_eq!(out["early"], json!(["B001", "B002", "B003"]));
    assert_eq!(out["twice"], json!([25, 25]));

    // And the unstreamed read answers exactly the same rows in the same order,
    // which is the property a cursor has to preserve.
    let out = live
        .run(
            "walked = [b[\"title\"] for b in db.books.where(title__like=\"B%\")\
             .order_by(\"title\").iter(batch=5)]\n\
             whole = [b[\"title\"] for b in db.books.where(title__like=\"B%\")\
             .order_by(\"title\").select(\"title\").rows()]\n\
             return walked == whole",
        )
        .await?;
    assert_eq!(out, json!(true));
    Ok(())
}

// ---------------------------------------------------------------------------
// What a write is: an event, an authority, and a bound
// ---------------------------------------------------------------------------

/// An action that writes one audit row saying what fired it — something for a
/// Python body's insert to set off.
struct Audit {
    fired: Arc<Mutex<Vec<String>>>,
}

#[async_trait]
impl Action for Audit {
    fn name(&self) -> &str {
        "audit"
    }
    fn description(&self) -> &str {
        "Record that a book was written"
    }
    fn config_spec(&self) -> Vec<FormField> {
        Vec::new()
    }
    async fn run(&self, ctx: &mut ActionContext<'_>) -> Result<Json> {
        let title = ctx
            .event
            .row
            .as_ref()
            .and_then(|row| row.get("title"))
            .and_then(Json::as_str)
            .unwrap_or_default()
            .to_owned();
        let who = ctx
            .event
            .user
            .as_ref()
            .and_then(|user| user.get("email"))
            .and_then(Json::as_str)
            .unwrap_or("nobody")
            .to_owned();
        self.fired
            .lock()
            .expect("not poisoned")
            .push(format!("{title} by {who}"));
        Ok(Json::Null)
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn an_insert_from_a_body_fires_the_trigger_that_listens_for_it() -> Result<()> {
    let live = Live::new().await?;
    let fired = Arc::new(Mutex::new(Vec::new()));

    // The dispatcher, with one trigger on `insert books` — installed into the
    // catalog, which is what makes a write observed at all.
    let mut registry = ActionRegistry::new();
    registry.register(Arc::new(Audit {
        fired: Arc::clone(&fired),
    }))?;
    bootstrap_triggers(&live.catalog).await?;
    let trigger = Trigger::new("on_book", EventKind::Insert, "audit").on("books");
    save_trigger(&live.catalog, &registry, &trigger).await?;
    let dispatcher = Arc::new(TriggerDispatcher::new(Arc::new(registry)));
    dispatcher.reload(&live.catalog).await?;
    live.catalog
        .set_table_events(Arc::clone(&dispatcher) as Arc<dyn sc_catalog::TableEvents>)?;

    // The body's insert goes through the row layer, so it is observed exactly as
    // an API caller's write is — and the event carries **this** run's caller,
    // because the caller travels with every write a body makes.
    let out = live
        .run("return db.books.insert(title=\"Ubik\", pages=224, author=2)[\"title\"]")
        .await?;
    assert_eq!(out, json!("Ubik"));
    assert_eq!(
        fired.lock().expect("not poisoned").as_slice(),
        ["Ubik by ada@example.com"]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_delegated_read_obeys_the_ownership_formula_and_a_refusal_is_catchable() -> Result<()> {
    let live = Live::new().await?;
    live.own_the_notes().await?;

    // Undelegated is the trigger's own authority and sees every note; `as_user`
    // is ada's, and the formula decides — evaluated on the JavaScript isolate
    // while this Python run waits for it.
    let out = live
        .run(
            r#"
mine = db.as_user().notes.select("what").order_by("id").rows()
return {"mine": [n["what"] for n in mine], "all": db.notes.count()}
"#,
        )
        .await?;
    assert_eq!(out, json!({ "mine": ["ada one", "ada two"], "all": 3 }));

    // A delegated write outside the formula is refused — as a `DbError`, at the
    // call site, so a body may try and fall back. That it is catchable is the
    // whole difference between a refusal and a mistake.
    let out = live
        .run(
            r#"
import saltcorn as sc
try:
    db.as_user().notes.insert(what="not mine", owner="bob@example.com")
    return {"refused": None}
except sc.DbError as e:
    return {"refused": str(e), "fell_back": db.notes.insert(what="audited", owner="bob@example.com")["what"]}
"#,
        )
        .await?;
    assert!(
        !out["refused"].as_str().unwrap_or_default().is_empty(),
        "the delegated insert was allowed: {out}"
    );
    // The fallback at the trigger's own authority is what a trigger is for, and
    // it really wrote.
    assert_eq!(out["fell_back"], json!("audited"));
    assert_eq!(
        live.column("SELECT what FROM notes WHERE owner = 'bob@example.com' ORDER BY id")
            .await?,
        vec!["bob one", "audited"]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_whole_table_write_is_refused_before_it_reaches_the_database() -> Result<()> {
    let live = Live::new().await?;
    for (call, op) in [
        ("db.books.update(pages=1)", "update"),
        ("db.books.delete()", "delete"),
    ] {
        let said = live.fails(&format!("return {call}")).await;
        assert!(said.contains(op), "{said}");
        assert!(said.contains(".where()"), "{said}");
    }
    // Nothing was touched: the refusal is in front of the host, not after it.
    assert_eq!(
        live.column("SELECT title FROM books ORDER BY title")
            .await?,
        vec!["Dune", "Emma", "Ficciones", "Solaris"]
    );
    assert_eq!(
        live.column("SELECT pages::text FROM books WHERE title = 'Dune'")
            .await?,
        vec!["412"]
    );
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn the_bodys_own_sql_runs_as_written_with_its_values_as_binds() -> Result<()> {
    let live = Live::new().await?;
    let out = live
        .run(
            r#"
ranked = db.sql(
    "select title, rank() over (order by pages desc) as r from books "
    "where pages > $1 order by pages desc",
    [200],
)
# The value is a bind and never part of the text: a string that would end the
# literal is a value that matches nothing, not a second statement.
none = db.sql("select title from books where title = $1", ["' or 1=1 --"])
return {"ranked": ranked, "none": none}
"#,
        )
        .await?;
    assert_eq!(
        out["ranked"],
        json!([
            { "title": "Emma", "r": 1 },
            { "title": "Dune", "r": 2 },
        ])
    );
    assert_eq!(out["none"], json!([]));
    Ok(())
}

// ---------------------------------------------------------------------------
// Phase 2.7 — the parity case
// ---------------------------------------------------------------------------

/// The same question, asked from a JavaScript body and from a Python body,
/// answers the same rows — **because it is the same plan**.
///
/// This is the property the whole adapter shape exists for: `CodeCall` and the
/// five host traits were never JavaScript's, so a second language is a second
/// implementation of one trait and there is no second place for authority,
/// budgets or events to be decided. If the two ever disagreed here, one of them
/// would have grown a lowering of its own — which is the failure this test is
/// watching for, and it is why the two bodies are written idiomatically in their
/// own language rather than transliterated.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn the_same_question_in_two_languages_answers_the_same_rows() -> Result<()> {
    let live = Live::new().await?;
    live.own_the_notes().await?;

    let python = live
        .run(
            r#"
long = (db.books
    .where(pages__gte=payload["least"])
    .select("title", "authorⱵname", tier="authorⱵtier")
    .order_by("pages", "desc")
    .limit(10)
    .rows())
by_author = (db.books
    .group_by("author")
    .aggregate(total="sum(pages)", n="count()")
    .order_by("author")
    .rows())
return {
    "long": long,
    "by_author": by_author,
    "n": db.books.count(),
    "pages": db.books.sum("pages"),
    "first": db.books.order_by("title").first(),
    "mine": db.as_user().notes.select("what").order_by("id").rows(),
}
"#,
        )
        .await?;

    let javascript = live
        .run_js(
            r#"
const long = await db.books
  .where({ pages: { gte: payload.least } })
  .select("title", "authorⱵname", { tier: "authorⱵtier" })
  .orderBy("pages", "desc")
  .limit(10)
  .rows();
const byAuthor = await db.books
  .groupBy("author")
  .aggregate({ total: "sum(pages)", n: "count()" })
  .orderBy("author")
  .rows();
return {
  long,
  by_author: byAuthor,
  n: await db.books.count(),
  pages: await db.books.sum("pages"),
  first: await db.books.orderBy("title").first(),
  mine: await db.asUser().notes.select("what").orderBy("id").rows(),
};
"#,
        )
        .await?;

    assert_eq!(python, javascript, "the two languages disagreed");
    // And not vacuously: the answer is the rows, including the join path, the
    // exact decimal and the ownership formula's verdict.
    assert_eq!(python["long"][0]["authorⱵname"], json!("Ada"));
    assert_eq!(python["pages"], json!("1060"));
    assert_eq!(
        python["mine"],
        json!([{ "what": "ada one" }, { "what": "ada two" }])
    );
    Ok(())
}
