//! `saltcorn api add-query` / `list-queries` / `remove-query`: an application's
//! custom SQL queries from a terminal (TODO "API improvements" Phase 5).
//!
//! Driven through the **real binary** against a **real Postgres**, because both
//! halves of the claim need the real thing: a query is validated by *preparing*
//! it, which only a database can do, and adding one **rewrites the application's
//! generated client**, which only the file store can show. A command that
//! changed the API and left the client describing the old one would be the drift
//! §13.1 exists to prevent, introduced by the tool meant to avoid it.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use sc_app::{
    ApiConfig, Application, FrameworkRef, load_application_by_subdomain, react_client_path,
    save_application, scaffold_app,
};
use sc_catalog::{Catalog, DataField, FileStoreId, TableId};
use sc_cli::{DbConfig, connect_catalog};
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;
use sc_types::{BasicType, TypeRef};

/// Matches the harness fallback so a bare `cargo test` works in CI.
const DEFAULT_URL: &str = "postgres://saltcorn:saltcorn@localhost:5432/saltcorn_test";

/// A connection URL for the per-test database.
fn url_for(db: &TestDb) -> String {
    let base = std::env::var("DATABASE_URL").unwrap_or_else(|_| DEFAULT_URL.to_owned());
    let (authority_and_path, query) = match base.split_once('?') {
        Some((head, q)) => (head, Some(q)),
        None => (base.as_str(), None),
    };
    let cut = authority_and_path.rfind('/').expect("URL has a path");
    let mut url = format!("{}/{}", &authority_and_path[..cut], db.name());
    if let Some(q) = query {
        url.push('?');
        url.push_str(q);
    }
    url
}

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-cli-api-queries-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

/// Run `saltcorn api …`, returning (success, stdout, stderr).
fn api(args: &[&str]) -> (bool, String, String) {
    let out = Command::new(env!("CARGO_BIN_EXE_saltcorn"))
        .arg("api")
        .args(args)
        .output()
        .expect("run the saltcorn binary");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

/// A scaffolded `books` application with a REST API, and the catalog it lives
/// in. Scaffolding writes files only — no `npm` — which is all this test needs:
/// what it asserts on is the *generated* client, not a bundle.
async fn books_app(db: &TestDb, tmp: &TempDir) -> sc_error::Result<Arc<Catalog>> {
    let catalog = connect_catalog(&DbConfig::from_url(url_for(db))).await?;
    let id = DataField::plain(
        "id",
        TypeRef::from_sql_type("bigint generated by default as identity"),
    )
    .required()
    .primary_key();
    catalog.create_table("books", &[id]).await?;
    catalog
        .create_field(
            "books",
            &DataField::plain("title", TypeRef::Basic(BasicType::Text)).required(),
        )
        .await?;
    catalog
        .create_field(
            "books",
            &DataField::plain("year", TypeRef::Basic(BasicType::Int)),
        )
        .await?;
    catalog.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = Application::new(
        "Books",
        "books",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "books"),
    )
    .with_table(TableId("books".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"));
    save_application(&catalog, &app).await?;
    scaffold_app(&catalog, &app, None).await?;
    Ok(catalog)
}

/// The generated client of the scaffolded app.
fn client_ts(tmp: &TempDir) -> String {
    std::fs::read_to_string(tmp.path().join(react_client_path("books"))).expect("client.ts")
}

#[test]
fn it_says_what_it_wanted_without_a_subcommand() {
    let (ok, _, stderr) = api(&[]);
    assert!(!ok);
    assert!(stderr.contains("add-query"), "{stderr}");
    let (ok, _, stderr) = api(&["add-queries"]);
    assert!(!ok);
    assert!(stderr.contains("add-queries"), "{stderr}");
}

#[tokio::test]
async fn a_query_added_from_the_cli_reaches_the_endpoints_and_the_client() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let tmp = TempDir::new("add")?;
    let catalog = books_app(&db, &tmp).await?;
    let url = url_for(&db);
    let store = format!("apps={}", tmp.path().display());

    // Before: the client has the table's own methods and nothing else.
    assert!(client_ts(&tmp).contains("listBooks"));
    assert!(!client_ts(&tmp).contains("topYears"));

    let (ok, stdout, stderr) = api(&[
        "add-query",
        "--app",
        "books",
        "--name",
        "topYears",
        "--path",
        "/reports/top-years",
        "--min-role",
        "40",
        "--param",
        "since:int",
        "--sql",
        "select year, count(*) as n from books where year > :since group by year",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(ok, "add-query failed:\n{stderr}\n{stdout}");
    // The columns the *database* reported, which is what the client method now
    // returns — the answer an admin came to the command for.
    assert!(stdout.contains("year"), "{stdout}");
    assert!(stdout.contains("n (int)"), "{stdout}");

    // It is stored, with the described columns beside the SQL.
    let app = load_application_by_subdomain(&catalog, "books")
        .await?
        .expect("the app");
    let stored = sc_api::custom_queries(&app.apis[0].config)?;
    assert_eq!(stored.len(), 1);
    assert_eq!(stored[0].name, "topYears");
    assert_eq!(stored[0].min_role, 40);
    assert_eq!(
        stored[0]
            .columns
            .iter()
            .map(|c| c.name.as_str())
            .collect::<Vec<_>>(),
        vec!["year", "n"]
    );

    // …the app's endpoint set has it…
    let endpoints = sc_app::app_endpoints(&app, &catalog)?;
    let endpoint = endpoints
        .iter()
        .find(|e| e.name == "topYears")
        .expect("the custom query's endpoint");
    assert_eq!(endpoint.path.pattern(), "/api/reports/top-years");
    assert_eq!(endpoint.auth, sc_api::AuthRequirement::MinRole(40));

    // …and the generated client was rewritten with no build and no restart,
    // which is the half of this that a save alone would not have done.
    let client = client_ts(&tmp);
    assert!(client.contains("topYears("), "{client}");
    assert!(client.contains("/api/reports/top-years"), "{client}");

    // `list-queries` reports it, parameters and result columns included.
    let (ok, stdout, stderr) = api(&[
        "list-queries",
        "--app",
        "books",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(ok, "{stderr}");
    assert!(stdout.contains("GET /api/reports/top-years"), "{stdout}");
    assert!(stdout.contains("since: int"), "{stdout}");
    assert!(stdout.contains("n: int"), "{stdout}");

    // …and `remove-query` takes it back out of both places, which is the reason
    // the command exists: the first typo must not need a browser to fix.
    let (ok, _, stderr) = api(&[
        "remove-query",
        "--app",
        "books",
        "--name",
        "topYears",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(ok, "{stderr}");
    let app = load_application_by_subdomain(&catalog, "books")
        .await?
        .expect("the app");
    assert!(sc_api::custom_queries(&app.apis[0].config)?.is_empty());
    assert!(!client_ts(&tmp).contains("topYears("));

    // Removing one that is not there names the ones that are, rather than
    // succeeding at nothing.
    let (ok, _, stderr) = api(&[
        "remove-query",
        "--app",
        "books",
        "--name",
        "topYears",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(!ok);
    assert!(stderr.contains("topYears"), "{stderr}");
    Ok(())
}

#[tokio::test]
async fn a_query_that_will_not_prepare_is_refused_and_changes_nothing() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    let tmp = TempDir::new("bad")?;
    let catalog = books_app(&db, &tmp).await?;
    let url = url_for(&db);
    let store = format!("apps={}", tmp.path().display());

    let (ok, _, stderr) = api(&[
        "add-query",
        "--app",
        "books",
        "--name",
        "typo",
        "--path",
        "/reports/typo",
        "--sql",
        "select titel from books",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(!ok, "a query that will not prepare must not be saved");
    // Postgres's own message, unedited: the column it could not find is the
    // whole of what the author needs to know.
    assert!(stderr.contains("titel"), "{stderr}");

    // Nothing was stored, and nothing was written: the save prepares every
    // query before it writes anything.
    let app = load_application_by_subdomain(&catalog, "books")
        .await?
        .expect("the app");
    assert!(sc_api::custom_queries(&app.apis[0].config)?.is_empty());
    assert!(!client_ts(&tmp).contains("typo("));

    // The same for a query the *model* refuses — a path the books table's own
    // routes already answer — which never reaches the database at all.
    let (ok, _, stderr) = api(&[
        "add-query",
        "--app",
        "books",
        "--name",
        "bookSummary",
        "--path",
        "/books/summary",
        "--sql",
        "select count(*) as n from books",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(!ok);
    assert!(stderr.contains("books"), "{stderr}");

    // …and an application that is not there is not a database error.
    let (ok, _, stderr) = api(&[
        "list-queries",
        "--app",
        "nosuchapp",
        "--database-url",
        &url,
        "--file-store",
        &store,
    ]);
    assert!(!ok);
    assert!(stderr.contains("nosuchapp"), "{stderr}");
    Ok(())
}
