//! `saltcorn auth token` against a **real running server** on a real socket.
//!
//! The point of this command is that the session it writes is one the server
//! will actually accept, and nothing short of an end-to-end sign-in tests that:
//! the CSRF handshake, the `Host` header the app is routed by, the cookies the
//! response carries and the file a browser would load. So this binds a port,
//! serves an application on it, and signs in over HTTP exactly as the command
//! does — because it *is* what the command does.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::sync::Arc;

use sc_app::{ApiConfig, Application, AssetBundle, CodeFramework, FrameworkRef};
use sc_auth::SessionStore;
use sc_catalog::{Catalog, PublicOrigin, TableId};
use sc_cli::auth::{self, SessionFormat, Target};
use sc_db::DatabaseDriver;
use sc_db_postgres::PgDriver;
use sc_server::{AppMounts, MountedApp, ServerConfig, admin_handlers, build_router_with_apps};
use sc_test_harness::TestDb;

const BASE_DOMAIN: &str = "example.com";
const EMAIL: &str = "agent@example.com";
const PASSWORD: &str = "correct horse battery staple";

/// A server on a real port, serving one application on its subdomain.
struct Running {
    /// `http://127.0.0.1:<port>` — what a client connects to.
    url: String,
    /// The application's own host, which is what routes the request.
    host: String,
    _db: TestDb,
}

/// Bring up a database, a user, an application mounted with an empty bundle, and
/// the server, bound to a port the OS picks.
///
/// The bundle is empty on purpose: this test is about `/api/login`, and a
/// framework with no assets serves 404s for everything else without needing a
/// bundler to have run.
async fn start() -> sc_error::Result<Running> {
    let db = TestDb::new().await?;
    db.client()
        .await?
        .batch_execute(
            "CREATE TABLE posts (\
               id bigint generated by default as identity primary key, \
               title text not null)",
        )
        .await
        .map_err(|e| sc_error::Error::database(e.to_string()))?;

    let driver = Arc::new(PgDriver::from_pool(db.pool().clone()));
    let catalog = Arc::new(Catalog::init(driver as Arc<dyn DatabaseDriver>).await?);
    sc_auth::bootstrap(&catalog).await?;
    sc_app::bootstrap(&catalog).await?;
    sc_auth::create_user(&catalog, EMAIL, PASSWORD, sc_auth::ROLE_ADMIN).await?;

    // A valid `code` configuration: it is never built here (the mount below
    // carries an empty bundle), but saving validates it like any other row.
    let framework = FrameworkRef::new("code")
        .with("store", "apps")
        .with("source", "web")
        .with("output", "web/dist")
        .with("command", "sh build.sh");
    let app = Application::new("Blog", "blog", framework)
        .with_table(TableId("posts".to_owned()))
        .with_api(ApiConfig::new("rest", "/api"));
    sc_app::save_application(&catalog, &app).await?;

    let apps = Arc::new(AppMounts::new(catalog.clone()));
    apps.mount(MountedApp::new(
        app,
        Arc::new(CodeFramework::new("code", AssetBundle::new())),
        &catalog,
    )?)?;

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .map_err(|e| sc_error::Error::msg(e.to_string()))?;
    let port = listener
        .local_addr()
        .map_err(|e| sc_error::Error::msg(e.to_string()))?
        .port();

    let config = ServerConfig {
        base_domain: Some(BASE_DOMAIN.to_owned()),
        ..ServerConfig::default()
    };
    let router = build_router_with_apps(
        &sc_api::admin_endpoints(),
        admin_handlers(catalog.clone(), apps.clone()),
        Arc::new(SessionStore::default()),
        &config,
        apps.clone(),
    )?;
    tokio::spawn(async move {
        let _ = axum::serve(listener, router).await;
    });

    Ok(Running {
        url: format!("http://127.0.0.1:{port}"),
        host: PublicOrigin::new(BASE_DOMAIN, port).host_for("blog"),
        _db: db,
    })
}

fn target(server: &Running) -> Target {
    Target {
        url: server.url.clone(),
        host: server.host.clone(),
        login_path: "/api/login".to_owned(),
        secure: false,
    }
}

#[tokio::test]
async fn signing_in_writes_a_session_a_browser_could_use() -> sc_error::Result<()> {
    let server = start().await?;
    let target = target(&server);

    let (cookies, user) = auth::mint_session(&target, EMAIL, PASSWORD).await?;

    // The session cookie is there, and it is the server's — opaque, and long
    // enough to be the 256-bit token §7.2 mints.
    let session = cookies
        .iter()
        .find(|c| c.name == "sc_session")
        .expect("a session cookie");
    assert_eq!(session.value.len(), 64, "{}", session.value);
    assert!(
        session.http_only,
        "the session cookie must not be readable by script"
    );
    assert_eq!(session.path, "/");
    // The CSRF cookie rides along, so a mutation from the restored browser works
    // too rather than 403ing on the first save.
    assert!(cookies.iter().any(|c| c.name == "sc_csrf"), "{cookies:?}");
    // The server said who we are.
    assert_eq!(user["email"], EMAIL);

    // The Playwright file is scoped to the application's own host — not the
    // loopback address the command happened to connect to.
    let state: serde_json::Value = serde_json::from_str(&auth::render(
        &cookies,
        &target.host,
        SessionFormat::Playwright,
    ))
    .expect("valid JSON");
    assert_eq!(state["cookies"][0]["domain"], "blog.example.com");

    // And it is written where nobody else can read it.
    let path = std::env::temp_dir().join(format!("sc-auth-token-{}.json", std::process::id()));
    auth::write_private(
        &path,
        &auth::render(&cookies, &target.host, SessionFormat::Playwright),
    )?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&path).expect("stat").permissions().mode();
        assert_eq!(mode & 0o777, 0o600, "a session file is a password");
    }
    std::fs::remove_file(&path).ok();
    Ok(())
}

#[tokio::test]
async fn the_session_it_writes_is_accepted_by_the_server() -> sc_error::Result<()> {
    let server = start().await?;
    let target = target(&server);
    let (cookies, _) = auth::mint_session(&target, EMAIL, PASSWORD).await?;

    // The whole promise of the command in one request: replay the cookie at an
    // endpoint that requires a session, as a browser loading the file would.
    let jar: Vec<String> = cookies
        .iter()
        .map(|c| format!("{}={}", c.name, c.value))
        .collect();
    let response = reqwest::Client::new()
        .get(format!("{}/api/whoami", server.url))
        .header(reqwest::header::HOST, &server.host)
        .header(reqwest::header::COOKIE, jar.join("; "))
        .send()
        .await
        .map_err(|e| sc_error::Error::msg(e.to_string()))?;
    assert_eq!(
        response.status(),
        200,
        "whoami should recognise the session"
    );
    let body: serde_json::Value = response
        .json()
        .await
        .map_err(|e| sc_error::Error::msg(e.to_string()))?;
    assert_eq!(body["email"], EMAIL);

    // Without it, the same request is anonymous — which is the state a
    // screenshot script is in until it loads the file.
    let anonymous = reqwest::Client::new()
        .get(format!("{}/api/whoami", server.url))
        .header(reqwest::header::HOST, &server.host)
        .send()
        .await
        .map_err(|e| sc_error::Error::msg(e.to_string()))?;
    assert_eq!(anonymous.status(), 401);
    Ok(())
}

#[tokio::test]
async fn a_wrong_password_is_refused_with_the_servers_own_words() -> sc_error::Result<()> {
    let server = start().await?;
    let err = auth::mint_session(&target(&server), EMAIL, "not the password")
        .await
        .expect_err("a wrong password must not mint a session");
    let message = err.to_string();
    // The status and the server's message, so the caller can tell a bad password
    // from an unreachable server without reading the code.
    assert!(message.contains("401"), "{message}");
    assert!(message.to_lowercase().contains("invalid"), "{message}");
    Ok(())
}

#[tokio::test]
async fn an_unreachable_server_says_where_it_tried() -> sc_error::Result<()> {
    // Port 1 on the loopback: nothing is listening, and nothing can be.
    let target = Target {
        url: "http://127.0.0.1:1".to_owned(),
        host: "blog.example.com".to_owned(),
        login_path: "/api/login".to_owned(),
        secure: false,
    };
    let err = auth::mint_session(&target, EMAIL, PASSWORD)
        .await
        .expect_err("nothing is listening");
    let message = err.to_string();
    assert!(message.contains("127.0.0.1:1"), "{message}");
    assert!(message.contains("saltcorn serve"), "{message}");
    Ok(())
}

/// The cookie and header names this crate spells for itself must be the ones the
/// server actually sets — the comment in `auth.rs` promises this test exists.
#[test]
fn the_wire_names_match_the_servers() {
    assert_eq!(sc_server::SESSION_COOKIE, "sc_session");
    assert_eq!(sc_server::CSRF_COOKIE, "sc_csrf");
    assert_eq!(sc_server::CSRF_HEADER, "x-csrf-token");
}
