//! `saltcorn build-app SUBDOMAIN`: building one application from a terminal.
//!
//! Driven through the **real binary**, because that is the whole point of the
//! command — a build an admin can run where its output can be piped, grepped and
//! kept, when the UI that would otherwise run it is not the tool at hand.
//!
//! The failure paths run everywhere; the build itself skips when `npm` is not on
//! `PATH`.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use sc_app::{ApiConfig, Application, FrameworkRef, save_application, scaffold_app};
use sc_catalog::{DataField, FileStoreId, TableId};
use sc_cli::{DbConfig, connect_catalog};
use sc_files::LocalFileStore;
use sc_test_harness::TestDb;
use sc_types::{BasicType, TypeRef};

/// Matches the harness fallback so a bare `cargo test` works in CI.
const DEFAULT_URL: &str = "postgres://saltcorn:saltcorn@localhost:5432/saltcorn_test";

/// A connection URL for the per-test database.
fn url_for(db: &TestDb) -> String {
    let base = std::env::var("DATABASE_URL").unwrap_or_else(|_| DEFAULT_URL.to_owned());
    let (authority_and_path, query) = match base.split_once('?') {
        Some((head, q)) => (head, Some(q)),
        None => (base.as_str(), None),
    };
    let cut = authority_and_path.rfind('/').expect("URL has a path");
    let mut url = format!("{}/{}", &authority_and_path[..cut], db.name());
    if let Some(q) = query {
        url.push('?');
        url.push_str(q);
    }
    url
}

/// A scratch directory removed when the guard drops.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> sc_error::Result<TempDir> {
        let dir = std::env::temp_dir().join(format!(
            "sc-cli-build-app-{}-{tag}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        std::fs::remove_dir_all(&dir).ok();
        std::fs::create_dir_all(&dir)?;
        Ok(TempDir(dir))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        std::fs::remove_dir_all(&self.0).ok();
    }
}

fn npm_available() -> bool {
    std::env::var_os("PATH")
        .map(|paths| {
            std::env::split_paths(&paths)
                .any(|dir| dir.join("npm").is_file() || dir.join("npm.cmd").is_file())
        })
        .unwrap_or(false)
}

/// Run the binary's `build-app` with the given arguments, returning
/// (success, stdout, stderr).
fn build_app(args: &[&str]) -> (bool, String, String) {
    let out = Command::new(env!("CARGO_BIN_EXE_saltcorn"))
        .arg("build-app")
        .args(args)
        .output()
        .expect("run the saltcorn binary");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

#[test]
fn without_a_subdomain_it_says_what_it_wanted() {
    let (ok, _, stderr) = build_app(&[]);
    assert!(!ok);
    assert!(stderr.contains("subdomain"), "{stderr}");
    // A flag in the subdomain's place is the same mistake, not a database error.
    let (ok, _, stderr) = build_app(&["--database-url", DEFAULT_URL]);
    assert!(!ok);
    assert!(stderr.contains("subdomain"), "{stderr}");
}

#[tokio::test]
async fn an_unknown_subdomain_is_reported_as_such() -> sc_error::Result<()> {
    let db = TestDb::new().await?;
    // Bootstrap the tables so the failure is genuinely "no such app" rather than
    // "no such table".
    connect_catalog(&DbConfig::from_url(url_for(&db))).await?;

    let (ok, _, stderr) = build_app(&["nosuchapp", "--database-url", &url_for(&db)]);
    assert!(!ok);
    assert!(stderr.contains("nosuchapp"), "{stderr}");
    Ok(())
}

#[tokio::test]
async fn it_builds_a_scaffolded_app_and_prints_the_tool_output() -> sc_error::Result<()> {
    if !npm_available() {
        eprintln!("skipping: `npm` is not on PATH");
        return Ok(());
    }

    let db = TestDb::new().await?;
    let tmp = TempDir::new("ok")?;
    let catalog = connect_catalog(&DbConfig::from_url(url_for(&db))).await?;

    // The tutorial's data model and application, set up through the library, then
    // handed to the *binary* to build.
    let id = DataField::plain(
        "id",
        TypeRef::from_sql_type("bigint generated by default as identity"),
    )
    .required()
    .primary_key();
    catalog.create_table("tasks", &[id]).await?;
    catalog
        .create_field(
            "tasks",
            &DataField::plain("title", TypeRef::Basic(BasicType::Text)).required(),
        )
        .await?;
    catalog.connect_file_store(Arc::new(LocalFileStore::new("apps", tmp.path())?))?;

    let app = Application::new(
        "Todo",
        "todo",
        FrameworkRef::new("react")
            .with("store", "apps")
            .with("project", "todo"),
    )
    .with_table(TableId("tasks".to_owned()))
    .with_file_store(FileStoreId("apps".to_owned()))
    .with_api(ApiConfig::new("rest", "/api"));
    save_application(&catalog, &app).await?;
    scaffold_app(&catalog, &app, None).await?;

    let store_flag = format!("apps={}", tmp.path().display());
    let (ok, stdout, stderr) = build_app(&[
        "todo",
        "--database-url",
        &url_for(&db),
        "--file-store",
        &store_flag,
    ]);
    assert!(ok, "build failed:\n{stderr}\n{stdout}");
    // The bundler's own output reaches the terminal — the reason to run this
    // rather than click Build.
    assert!(stdout.contains("vite"), "no bundler output:\n{stdout}");
    assert!(stderr.contains("built"), "{stderr}");
    // And it really produced a bundle.
    assert!(tmp.path().join("todo/dist/index.html").is_file());
    Ok(())
}
