// Code generated by sc-api. DO NOT EDIT.
// Regenerate with the sc-api TypeScript generator (design §13.1).

import { clientError, requestHeaders, type ClientOptions } from "./helper";

export type { ClientOptions } from "./helper";

export type AuthStatusResponse = { any_user_exists: boolean; current_user?: { id: string; email: string; role: number } | null };
export type CreateFirstUserRequest = { email: string; password: string };
export type CreateFirstUserResponse = { id: string; email: string; role: number };
export type LoginRequest = { email: string; password: string };
export type LoginResponse = { id: string; email: string; role: number };
export type ListTablesResponse = Array<{ name: string; label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean; configured: boolean; ownership_error?: string | null; rls_available: boolean }>;
export type CreateTableRequest = { name: string };
export type CreateTableResponse = { name: string; label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean; configured: boolean; ownership_error?: string | null; rls_available: boolean };
export type CreateTableFromCsvRequest = { name: string; csv: string };
export type CreateTableFromCsvResponse = { table: { name: string; label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean; configured: boolean; ownership_error?: string | null; rls_available: boolean }; inserted: number };
export type UpdateTableRequest = { label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean };
export type UpdateTableResponse = { name: string; label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean; configured: boolean; ownership_error?: string | null; rls_available: boolean };
export type DropTableResponse = { dropped: string };
export type DeleteTableSettingsResponse = { deleted: boolean };
export type ListOrphanTableSettingsResponse = Array<{ name: string; label: string; description: string; min_role_read: number; min_role_write: number; ownership_formula: string; rls_enabled: boolean }>;
export type ListRolesResponse = Array<{ role: number; name: string; description: string; builtin: boolean }>;
export type CreateRoleRequest = { role: number; name: string; description: string };
export type CreateRoleResponse = { role: number; name: string; description: string; builtin: boolean };
export type DeleteRoleResponse = { deleted: boolean };
export type ListFieldsResponse = Array<{ name: string; label: string; description: string; sql_type: string; type: string; nullable: boolean; required: boolean; unique: boolean; primary_key: boolean; generated: boolean; kind: unknown; attributes: unknown }>;
export type CreateFieldRequest = { name: string; type?: string | null; kind?: unknown | null; attributes?: unknown | null; label?: string | null; description?: string | null; required?: boolean | null; unique?: boolean | null; primary_key?: boolean | null };
export type CreateFieldResponse = { name: string; label: string; description: string; sql_type: string; type: string; nullable: boolean; required: boolean; unique: boolean; primary_key: boolean; generated: boolean; kind: unknown; attributes: unknown };
export type UpdateFieldRequest = { type?: string | null; kind?: unknown | null; attributes?: unknown | null; label?: string | null; description?: string | null; primary_key?: boolean | null };
export type UpdateFieldResponse = { name: string; label: string; description: string; sql_type: string; type: string; nullable: boolean; required: boolean; unique: boolean; primary_key: boolean; generated: boolean; kind: unknown; attributes: unknown };
export type DeleteFieldResponse = { dropped: string };
export type ListConstraintsResponse = Array<{ name: string; type: string; fields: Array<string>; expression?: string | null; method?: string | null; language?: string | null; formula?: string | null; error_message?: string | null; managed: boolean }>;
export type CreateConstraintRequest = { type: string; fields?: Array<string> | null; language?: string | null; formula?: string | null; name?: string | null; error_message?: string | null };
export type CreateConstraintResponse = { name: string; type: string; fields: Array<string>; expression?: string | null; method?: string | null; language?: string | null; formula?: string | null; error_message?: string | null; managed: boolean };
export type DeleteConstraintResponse = { dropped: string };
export type ListFieldTypesResponse = Array<{ name: string; label: string; category: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }> }>;
export type ListRowsResponse = Array<unknown>;
export type CountRowsResponse = { count: number };
export type CreateRowRequest = unknown;
export type CreateRowResponse = unknown;
export type UpdateRowRequest = unknown;
export type UpdateRowResponse = unknown;
export type ExportTableCsvResponse = { filename: string; csv: string };
export type ImportTableCsvRequest = { csv: string };
export type ImportTableCsvResponse = { inserted: number; updated: number; errors: Array<string> };
export type ListFileStoresResponse = Array<{ id?: string | null; name: string; description: string; backend: string; config: unknown; min_role?: number | null; connected: boolean; error?: string | null; is_git_repo?: boolean | null }>;
export type CreateFileStoreRequest = { name: string; description: string; backend: string; config: unknown; min_role?: number | null };
export type CreateFileStoreResponse = { id?: string | null; name: string; description: string; backend: string; config: unknown; min_role?: number | null; connected: boolean; error?: string | null; is_git_repo?: boolean | null };
export type UpdateFileStoreRequest = { name: string; description: string; backend: string; config: unknown; min_role?: number | null };
export type UpdateFileStoreResponse = { id?: string | null; name: string; description: string; backend: string; config: unknown; min_role?: number | null; connected: boolean; error?: string | null; is_git_repo?: boolean | null };
export type DeleteFileStoreResponse = { deleted: boolean };
export type ListFileStoreBackendsResponse = Array<{ name: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }>; operations: Array<{ name: string; label: string; description: string; scope: string; input_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }>; on_create: boolean; automatic: boolean }> }>;
export type RunBackendOperationRequest = { name: string; config: unknown; input: unknown };
export type RunBackendOperationResponse = { config: unknown; output: string; data?: unknown | null };
export type RunFileStoreOperationRequest = { input: unknown };
export type RunFileStoreOperationResponse = { config: unknown; output: string; data?: unknown | null; connected: boolean };
export type ListLlmProvidersResponse = Array<{ id: string; name: string; description: string; backend: string; config: unknown }>;
export type CreateLlmProviderRequest = { name: string; description: string; backend: string; config: unknown };
export type CreateLlmProviderResponse = { id: string; name: string; description: string; backend: string; config: unknown };
export type UpdateLlmProviderRequest = { name: string; description: string; backend: string; config: unknown };
export type UpdateLlmProviderResponse = { id: string; name: string; description: string; backend: string; config: unknown };
export type DeleteLlmProviderResponse = { deleted: boolean };
export type ListLlmProviderBackendsResponse = Array<{ name: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }> }>;
export type TestLlmProviderRequest = { id?: string | null; backend: string; config: unknown; model?: string | null };
export type TestLlmProviderResponse = { ok: boolean; message: string; model: string };
export type ListAgentsResponse = Array<{ id: string; name: string; description: string; provider: string; model?: string | null; system_prompt: string; traits: Array<{ trait: string; config: unknown }>; min_role?: number | null; attributes: unknown; error?: string | null }>;
export type CreateAgentRequest = { name: string; description: string; provider: string; model?: string | null; system_prompt: string; traits: Array<{ trait: string; config: unknown }>; min_role?: number | null; attributes: unknown };
export type CreateAgentResponse = { id: string; name: string; description: string; provider: string; model?: string | null; system_prompt: string; traits: Array<{ trait: string; config: unknown }>; min_role?: number | null; attributes: unknown; error?: string | null };
export type UpdateAgentRequest = { name: string; description: string; provider: string; model?: string | null; system_prompt: string; traits: Array<{ trait: string; config: unknown }>; min_role?: number | null; attributes: unknown };
export type UpdateAgentResponse = { id: string; name: string; description: string; provider: string; model?: string | null; system_prompt: string; traits: Array<{ trait: string; config: unknown }>; min_role?: number | null; attributes: unknown; error?: string | null };
export type DeleteAgentResponse = { deleted: boolean };
export type ListAgentTraitsResponse = Array<{ name: string; description: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }> }>;
export type ListRunsResponse = Array<{ id: string; kind: string; subject: string; description: string; state: string; error?: string | null; user?: string | null; created_at: string; updated_at: string }>;
export type GetRunResponse = { id: string; kind: string; subject: string; description: string; state: string; error?: string | null; user?: string | null; created_at: string; updated_at: string; context: unknown; attributes: unknown };
export type DeleteRunResponse = { deleted: boolean };
export type BrowseFilesRequest = { dir: string };
export type BrowseFilesResponse = Array<{ name: string; path: string; is_dir: boolean; size?: number | null }>;
export type SearchFilesRequest = { pattern: string; regex?: boolean | null; case_sensitive?: boolean | null; whole_word?: boolean | null; glob?: string | null; dir?: string | null; max_results?: number | null };
export type SearchFilesResponse = { matches: Array<{ path: string; line: number; column: number; length: number; text: string }>; files_searched: number; truncated: boolean };
export type ReadFileRequest = { path: string };
export type ReadFileResponse = { path: string; size: number; base64: string; text?: string | null };
export type WriteFileRequest = { path: string; base64?: string | null; text?: string | null };
export type WriteFileResponse = { name: string; path: string; is_dir: boolean; size?: number | null };
export type MakeDirectoryRequest = { path: string };
export type MakeDirectoryResponse = { name: string; path: string; is_dir: boolean; size?: number | null };
export type DeleteFileRequest = { path: string };
export type DeleteFileResponse = { deleted: boolean };
export type RenameFileRequest = { from: string; to: string };
export type RenameFileResponse = { name: string; path: string; is_dir: boolean; size?: number | null };
export type GetFileMetaRequest = { path: string };
export type GetFileMetaResponse = { path: string; min_role?: number | null; effective_min_role?: number | null; attributes: unknown };
export type SetFileMetaRequest = { path: string; min_role?: number | null; attributes: unknown };
export type SetFileMetaResponse = { path: string; min_role?: number | null; effective_min_role?: number | null; attributes: unknown };
export type ListApplicationsResponse = Array<{ id: string; name: string; description: string; subdomain: string; framework: { name: string; config: unknown }; extra_frameworks: Array<{ name: string; config: unknown }>; tables: Array<string>; file_stores: Array<string>; triggers: Array<string>; apis: Array<{ provider: string; mount: string; config: unknown }>; static_dirs: Array<{ mount: string; store: string; path: string }>; csp: unknown; attributes: unknown; source?: { store: string; path: string } | null }>;
export type CreateApplicationRequest = { name: string; description: string; subdomain: string; framework: { name: string; config: unknown }; extra_frameworks: Array<{ name: string; config: unknown }>; tables: Array<string>; file_stores: Array<string>; triggers: Array<string>; apis: Array<{ provider: string; mount: string; config: unknown }>; static_dirs: Array<{ mount: string; store: string; path: string }>; csp: unknown; attributes: unknown };
export type CreateApplicationResponse = { id: string; name: string; description: string; subdomain: string; framework: { name: string; config: unknown }; extra_frameworks: Array<{ name: string; config: unknown }>; tables: Array<string>; file_stores: Array<string>; triggers: Array<string>; apis: Array<{ provider: string; mount: string; config: unknown }>; static_dirs: Array<{ mount: string; store: string; path: string }>; csp: unknown; attributes: unknown; source?: { store: string; path: string } | null; scaffolded?: string | null; scaffold_error?: string | null; agent?: string | null; agent_error?: string | null };
export type UpdateApplicationRequest = { name: string; description: string; subdomain: string; framework: { name: string; config: unknown }; extra_frameworks: Array<{ name: string; config: unknown }>; tables: Array<string>; file_stores: Array<string>; triggers: Array<string>; apis: Array<{ provider: string; mount: string; config: unknown }>; static_dirs: Array<{ mount: string; store: string; path: string }>; csp: unknown; attributes: unknown };
export type UpdateApplicationResponse = { id: string; name: string; description: string; subdomain: string; framework: { name: string; config: unknown }; extra_frameworks: Array<{ name: string; config: unknown }>; tables: Array<string>; file_stores: Array<string>; triggers: Array<string>; apis: Array<{ provider: string; mount: string; config: unknown }>; static_dirs: Array<{ mount: string; store: string; path: string }>; csp: unknown; attributes: unknown; source?: { store: string; path: string } | null };
export type DeleteApplicationResponse = { deleted: boolean; agent?: string | null };
export type BuildApplicationResponse = { built: boolean; git_repo: boolean; log: string };
export type UpdateApplicationClientResponse = { scaffolded: boolean; files: Array<string>; log: string };
export type RunApplicationGraphqlRequest = { query: string; variables?: unknown | null; operationName?: string | null };
export type RunApplicationGraphqlResponse = unknown;
export type ListFrameworksResponse = Array<{ name: string; label: string; description: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }> }>;
export type ListApiProvidersResponse = Array<{ name: string; label: string; description: string; default_mount: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }>; supports_custom_queries: boolean }>;
export type DescribeCustomQueryRequest = { name: string; description?: string | null; method: string; path: string; sql: string; params: Array<{ name: string; type: string; required?: boolean | null }>; min_role?: number | null; tables?: Array<string> | null };
export type DescribeCustomQueryResponse = { columns: Array<{ name: string; type: string }> };
export type ListUsersResponse = Array<{ id: string; email: string; role: number; disabled: boolean; extra: unknown }>;
export type CreateUserRequest = { email: string; password?: string | null; role: number; extra?: unknown | null };
export type CreateUserResponse = { user: { id: string; email: string; role: number; disabled: boolean; extra: unknown }; generated_password?: string | null };
export type UpdateUserRequest = { email: string; password?: string | null; role: number; extra?: unknown | null };
export type UpdateUserResponse = { id: string; email: string; role: number; disabled: boolean; extra: unknown };
export type DeleteUserResponse = { deleted: boolean };
export type SetUserDisabledRequest = { disabled: boolean };
export type SetUserDisabledResponse = { id: string; email: string; role: number; disabled: boolean; extra: unknown };
export type ForceLogoutUserResponse = { ok: boolean };
export type BecomeUserResponse = { id: string; email: string; role: number };
export type SetRandomPasswordResponse = { email: string; password: string };
export type ListTriggersResponse = Array<{ id: string; name: string; description: string; when: string; channel?: string | null; only_if?: string | null; action: string; configuration: unknown; min_role?: number | null; enabled: boolean; minute?: number | null; hour?: number | null; day_of_week?: number | null; error?: string | null; last_run_at?: string | null }>;
export type CreateTriggerRequest = { name: string; description: string; when: string; channel?: string | null; only_if?: string | null; action: string; configuration: unknown; min_role?: number | null; enabled: boolean; minute?: number | null; hour?: number | null; day_of_week?: number | null };
export type CreateTriggerResponse = { id: string; name: string; description: string; when: string; channel?: string | null; only_if?: string | null; action: string; configuration: unknown; min_role?: number | null; enabled: boolean; minute?: number | null; hour?: number | null; day_of_week?: number | null; error?: string | null; last_run_at?: string | null };
export type UpdateTriggerRequest = { name: string; description: string; when: string; channel?: string | null; only_if?: string | null; action: string; configuration: unknown; min_role?: number | null; enabled: boolean; minute?: number | null; hour?: number | null; day_of_week?: number | null };
export type UpdateTriggerResponse = { id: string; name: string; description: string; when: string; channel?: string | null; only_if?: string | null; action: string; configuration: unknown; min_role?: number | null; enabled: boolean; minute?: number | null; hour?: number | null; day_of_week?: number | null; error?: string | null; last_run_at?: string | null };
export type DeleteTriggerResponse = { deleted: boolean };
export type RunTriggerRequest = unknown;
export type RunTriggerResponse = { result: unknown };
export type ListActionsQuery = { table?: string };
export type ListActionsResponse = Array<{ name: string; description: string; config_spec: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean }> }>;
export type GetSettingsResponse = { sections: Array<{ name: string; label: string; description: string; fields: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean; help: string }> }>; values: unknown };
export type UpdateSettingsRequest = { values: unknown };
export type UpdateSettingsResponse = { sections: Array<{ name: string; label: string; description: string; fields: Array<{ name: string; label: string; type: string; required: boolean; default?: unknown | null; options: Array<unknown>; multiline: boolean; secret: boolean; create_only: boolean; help: string }> }>; values: unknown };
export type SendTestEmailRequest = { to?: string | null };
export type SendTestEmailResponse = { sent_to: string };
export type GetBackupOptionsResponse = { available: { tables: Array<{ name: string; label: string; count?: number | null }>; applications: Array<{ name: string; label: string; count?: number | null }>; file_stores: Array<{ name: string; label: string; count?: number | null }>; users: number; agents: number; triggers: number; ssl: boolean }; include: { tables: Array<string>; table_data: Array<string>; applications: Array<string>; file_stores: Array<string>; users: boolean; agents: boolean; triggers: boolean; ssl: boolean } };
export type RestoreBackupRequest = { id: string; include: { tables: Array<string>; table_data: Array<string>; applications: Array<string>; file_stores: Array<string>; users: boolean; agents: boolean; triggers: boolean; ssl: boolean } };
export type RestoreBackupResponse = { restored: Array<string>; warnings: Array<string> };

export interface ApiClient {
  authStatus(): Promise<AuthStatusResponse>;
  createFirstUser(body: CreateFirstUserRequest): Promise<CreateFirstUserResponse>;
  login(body: LoginRequest): Promise<LoginResponse>;
  logout(): Promise<void>;
  listTables(): Promise<ListTablesResponse>;
  createTable(body: CreateTableRequest): Promise<CreateTableResponse>;
  createTableFromCsv(body: CreateTableFromCsvRequest): Promise<CreateTableFromCsvResponse>;
  updateTable(table: string, body: UpdateTableRequest): Promise<UpdateTableResponse>;
  dropTable(table: string): Promise<DropTableResponse>;
  deleteTableSettings(table: string): Promise<DeleteTableSettingsResponse>;
  listOrphanTableSettings(): Promise<ListOrphanTableSettingsResponse>;
  listRoles(): Promise<ListRolesResponse>;
  createRole(body: CreateRoleRequest): Promise<CreateRoleResponse>;
  deleteRole(role: number): Promise<DeleteRoleResponse>;
  listFields(table: string): Promise<ListFieldsResponse>;
  createField(table: string, body: CreateFieldRequest): Promise<CreateFieldResponse>;
  updateField(table: string, field: string, body: UpdateFieldRequest): Promise<UpdateFieldResponse>;
  deleteField(table: string, field: string): Promise<DeleteFieldResponse>;
  listConstraints(table: string): Promise<ListConstraintsResponse>;
  createConstraint(table: string, body: CreateConstraintRequest): Promise<CreateConstraintResponse>;
  deleteConstraint(table: string, constraint: string): Promise<DeleteConstraintResponse>;
  listFieldTypes(): Promise<ListFieldTypesResponse>;
  listRows(table: string): Promise<ListRowsResponse>;
  countRows(table: string): Promise<CountRowsResponse>;
  createRow(table: string, body: CreateRowRequest): Promise<CreateRowResponse>;
  updateRow(table: string, id: string, body: UpdateRowRequest): Promise<UpdateRowResponse>;
  deleteRow(table: string, id: string): Promise<void>;
  exportTableCsv(table: string): Promise<ExportTableCsvResponse>;
  importTableCsv(table: string, body: ImportTableCsvRequest): Promise<ImportTableCsvResponse>;
  listFileStores(): Promise<ListFileStoresResponse>;
  createFileStore(body: CreateFileStoreRequest): Promise<CreateFileStoreResponse>;
  updateFileStore(id: string, body: UpdateFileStoreRequest): Promise<UpdateFileStoreResponse>;
  deleteFileStore(id: string): Promise<DeleteFileStoreResponse>;
  listFileStoreBackends(): Promise<ListFileStoreBackendsResponse>;
  runBackendOperation(backend: string, operation: string, body: RunBackendOperationRequest): Promise<RunBackendOperationResponse>;
  runFileStoreOperation(id: string, operation: string, body: RunFileStoreOperationRequest): Promise<RunFileStoreOperationResponse>;
  listLlmProviders(): Promise<ListLlmProvidersResponse>;
  createLlmProvider(body: CreateLlmProviderRequest): Promise<CreateLlmProviderResponse>;
  updateLlmProvider(id: string, body: UpdateLlmProviderRequest): Promise<UpdateLlmProviderResponse>;
  deleteLlmProvider(id: string): Promise<DeleteLlmProviderResponse>;
  listLlmProviderBackends(): Promise<ListLlmProviderBackendsResponse>;
  testLlmProvider(body: TestLlmProviderRequest): Promise<TestLlmProviderResponse>;
  listAgents(): Promise<ListAgentsResponse>;
  createAgent(body: CreateAgentRequest): Promise<CreateAgentResponse>;
  updateAgent(id: string, body: UpdateAgentRequest): Promise<UpdateAgentResponse>;
  deleteAgent(id: string): Promise<DeleteAgentResponse>;
  listAgentTraits(): Promise<ListAgentTraitsResponse>;
  listRuns(agent: string): Promise<ListRunsResponse>;
  getRun(id: string): Promise<GetRunResponse>;
  deleteRun(id: string): Promise<DeleteRunResponse>;
  browseFiles(store: string, body: BrowseFilesRequest): Promise<BrowseFilesResponse>;
  searchFiles(store: string, body: SearchFilesRequest): Promise<SearchFilesResponse>;
  readFile(store: string, body: ReadFileRequest): Promise<ReadFileResponse>;
  writeFile(store: string, body: WriteFileRequest): Promise<WriteFileResponse>;
  makeDirectory(store: string, body: MakeDirectoryRequest): Promise<MakeDirectoryResponse>;
  deleteFile(store: string, body: DeleteFileRequest): Promise<DeleteFileResponse>;
  renameFile(store: string, body: RenameFileRequest): Promise<RenameFileResponse>;
  getFileMeta(store: string, body: GetFileMetaRequest): Promise<GetFileMetaResponse>;
  setFileMeta(store: string, body: SetFileMetaRequest): Promise<SetFileMetaResponse>;
  listApplications(): Promise<ListApplicationsResponse>;
  createApplication(body: CreateApplicationRequest): Promise<CreateApplicationResponse>;
  updateApplication(id: string, body: UpdateApplicationRequest): Promise<UpdateApplicationResponse>;
  deleteApplication(id: string): Promise<DeleteApplicationResponse>;
  buildApplication(id: string): Promise<BuildApplicationResponse>;
  updateApplicationClient(id: string): Promise<UpdateApplicationClientResponse>;
  runApplicationGraphql(id: string, body: RunApplicationGraphqlRequest): Promise<RunApplicationGraphqlResponse>;
  listFrameworks(): Promise<ListFrameworksResponse>;
  listApiProviders(): Promise<ListApiProvidersResponse>;
  describeCustomQuery(body: DescribeCustomQueryRequest): Promise<DescribeCustomQueryResponse>;
  listUsers(): Promise<ListUsersResponse>;
  createUser(body: CreateUserRequest): Promise<CreateUserResponse>;
  updateUser(id: string, body: UpdateUserRequest): Promise<UpdateUserResponse>;
  deleteUser(id: string): Promise<DeleteUserResponse>;
  setUserDisabled(id: string, body: SetUserDisabledRequest): Promise<SetUserDisabledResponse>;
  forceLogoutUser(id: string): Promise<ForceLogoutUserResponse>;
  becomeUser(id: string): Promise<BecomeUserResponse>;
  setRandomPassword(id: string): Promise<SetRandomPasswordResponse>;
  listTriggers(): Promise<ListTriggersResponse>;
  createTrigger(body: CreateTriggerRequest): Promise<CreateTriggerResponse>;
  updateTrigger(id: string, body: UpdateTriggerRequest): Promise<UpdateTriggerResponse>;
  deleteTrigger(id: string): Promise<DeleteTriggerResponse>;
  runTrigger(id: string, body: RunTriggerRequest): Promise<RunTriggerResponse>;
  listActions(query?: ListActionsQuery): Promise<ListActionsResponse>;
  getSettings(): Promise<GetSettingsResponse>;
  updateSettings(body: UpdateSettingsRequest): Promise<UpdateSettingsResponse>;
  sendTestEmail(body: SendTestEmailRequest): Promise<SendTestEmailResponse>;
  getBackupOptions(): Promise<GetBackupOptionsResponse>;
  restoreBackup(body: RestoreBackupRequest): Promise<RestoreBackupResponse>;
}

export function createClient(options: ClientOptions = {}): ApiClient {
  const baseUrl = options.baseUrl ?? "";
  const doFetch = options.fetch ?? fetch;
  return {
    async authStatus() {
      const res = await doFetch(`${baseUrl}/api/auth/status`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("authStatus", res);
      return (await res.json()) as AuthStatusResponse;
    },
    async createFirstUser(body) {
      const res = await doFetch(`${baseUrl}/api/first-user`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createFirstUser", res);
      return (await res.json()) as CreateFirstUserResponse;
    },
    async login(body) {
      const res = await doFetch(`${baseUrl}/api/login`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("login", res);
      return (await res.json()) as LoginResponse;
    },
    async logout() {
      const res = await doFetch(`${baseUrl}/api/logout`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("logout", res);
      return;
    },
    async listTables() {
      const res = await doFetch(`${baseUrl}/api/tables`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listTables", res);
      return (await res.json()) as ListTablesResponse;
    },
    async createTable(body) {
      const res = await doFetch(`${baseUrl}/api/tables`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createTable", res);
      return (await res.json()) as CreateTableResponse;
    },
    async createTableFromCsv(body) {
      const res = await doFetch(`${baseUrl}/api/tables/csv`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createTableFromCsv", res);
      return (await res.json()) as CreateTableFromCsvResponse;
    },
    async updateTable(table, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateTable", res);
      return (await res.json()) as UpdateTableResponse;
    },
    async dropTable(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("dropTable", res);
      return (await res.json()) as DropTableResponse;
    },
    async deleteTableSettings(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/settings`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteTableSettings", res);
      return (await res.json()) as DeleteTableSettingsResponse;
    },
    async listOrphanTableSettings() {
      const res = await doFetch(`${baseUrl}/api/table-settings/orphans`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listOrphanTableSettings", res);
      return (await res.json()) as ListOrphanTableSettingsResponse;
    },
    async listRoles() {
      const res = await doFetch(`${baseUrl}/api/roles`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listRoles", res);
      return (await res.json()) as ListRolesResponse;
    },
    async createRole(body) {
      const res = await doFetch(`${baseUrl}/api/roles`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createRole", res);
      return (await res.json()) as CreateRoleResponse;
    },
    async deleteRole(role) {
      const res = await doFetch(`${baseUrl}/api/roles/${role}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteRole", res);
      return (await res.json()) as DeleteRoleResponse;
    },
    async listFields(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/fields`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listFields", res);
      return (await res.json()) as ListFieldsResponse;
    },
    async createField(table, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/fields`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createField", res);
      return (await res.json()) as CreateFieldResponse;
    },
    async updateField(table, field, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/fields/${field}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateField", res);
      return (await res.json()) as UpdateFieldResponse;
    },
    async deleteField(table, field) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/fields/${field}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteField", res);
      return (await res.json()) as DeleteFieldResponse;
    },
    async listConstraints(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/constraints`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listConstraints", res);
      return (await res.json()) as ListConstraintsResponse;
    },
    async createConstraint(table, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/constraints`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createConstraint", res);
      return (await res.json()) as CreateConstraintResponse;
    },
    async deleteConstraint(table, constraint) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/constraints/${constraint}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteConstraint", res);
      return (await res.json()) as DeleteConstraintResponse;
    },
    async listFieldTypes() {
      const res = await doFetch(`${baseUrl}/api/field-types`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listFieldTypes", res);
      return (await res.json()) as ListFieldTypesResponse;
    },
    async listRows(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/rows`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listRows", res);
      return (await res.json()) as ListRowsResponse;
    },
    async countRows(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/rows/count`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("countRows", res);
      return (await res.json()) as CountRowsResponse;
    },
    async createRow(table, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/rows`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createRow", res);
      return (await res.json()) as CreateRowResponse;
    },
    async updateRow(table, id, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/rows/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateRow", res);
      return (await res.json()) as UpdateRowResponse;
    },
    async deleteRow(table, id) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/rows/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteRow", res);
      return;
    },
    async exportTableCsv(table) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/csv`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("exportTableCsv", res);
      return (await res.json()) as ExportTableCsvResponse;
    },
    async importTableCsv(table, body) {
      const res = await doFetch(`${baseUrl}/api/tables/${table}/csv`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("importTableCsv", res);
      return (await res.json()) as ImportTableCsvResponse;
    },
    async listFileStores() {
      const res = await doFetch(`${baseUrl}/api/file-stores`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listFileStores", res);
      return (await res.json()) as ListFileStoresResponse;
    },
    async createFileStore(body) {
      const res = await doFetch(`${baseUrl}/api/file-stores`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createFileStore", res);
      return (await res.json()) as CreateFileStoreResponse;
    },
    async updateFileStore(id, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateFileStore", res);
      return (await res.json()) as UpdateFileStoreResponse;
    },
    async deleteFileStore(id) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteFileStore", res);
      return (await res.json()) as DeleteFileStoreResponse;
    },
    async listFileStoreBackends() {
      const res = await doFetch(`${baseUrl}/api/file-store-backends`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listFileStoreBackends", res);
      return (await res.json()) as ListFileStoreBackendsResponse;
    },
    async runBackendOperation(backend, operation, body) {
      const res = await doFetch(`${baseUrl}/api/file-store-backends/${backend}/operations/${operation}`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("runBackendOperation", res);
      return (await res.json()) as RunBackendOperationResponse;
    },
    async runFileStoreOperation(id, operation, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${id}/operations/${operation}`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("runFileStoreOperation", res);
      return (await res.json()) as RunFileStoreOperationResponse;
    },
    async listLlmProviders() {
      const res = await doFetch(`${baseUrl}/api/llm-providers`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listLlmProviders", res);
      return (await res.json()) as ListLlmProvidersResponse;
    },
    async createLlmProvider(body) {
      const res = await doFetch(`${baseUrl}/api/llm-providers`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createLlmProvider", res);
      return (await res.json()) as CreateLlmProviderResponse;
    },
    async updateLlmProvider(id, body) {
      const res = await doFetch(`${baseUrl}/api/llm-providers/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateLlmProvider", res);
      return (await res.json()) as UpdateLlmProviderResponse;
    },
    async deleteLlmProvider(id) {
      const res = await doFetch(`${baseUrl}/api/llm-providers/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteLlmProvider", res);
      return (await res.json()) as DeleteLlmProviderResponse;
    },
    async listLlmProviderBackends() {
      const res = await doFetch(`${baseUrl}/api/llm-provider-backends`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listLlmProviderBackends", res);
      return (await res.json()) as ListLlmProviderBackendsResponse;
    },
    async testLlmProvider(body) {
      const res = await doFetch(`${baseUrl}/api/llm-provider-test`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("testLlmProvider", res);
      return (await res.json()) as TestLlmProviderResponse;
    },
    async listAgents() {
      const res = await doFetch(`${baseUrl}/api/agents`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listAgents", res);
      return (await res.json()) as ListAgentsResponse;
    },
    async createAgent(body) {
      const res = await doFetch(`${baseUrl}/api/agents`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createAgent", res);
      return (await res.json()) as CreateAgentResponse;
    },
    async updateAgent(id, body) {
      const res = await doFetch(`${baseUrl}/api/agents/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateAgent", res);
      return (await res.json()) as UpdateAgentResponse;
    },
    async deleteAgent(id) {
      const res = await doFetch(`${baseUrl}/api/agents/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteAgent", res);
      return (await res.json()) as DeleteAgentResponse;
    },
    async listAgentTraits() {
      const res = await doFetch(`${baseUrl}/api/agent-traits`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listAgentTraits", res);
      return (await res.json()) as ListAgentTraitsResponse;
    },
    async listRuns(agent) {
      const res = await doFetch(`${baseUrl}/api/agent-runs/${agent}`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listRuns", res);
      return (await res.json()) as ListRunsResponse;
    },
    async getRun(id) {
      const res = await doFetch(`${baseUrl}/api/runs/${id}`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("getRun", res);
      return (await res.json()) as GetRunResponse;
    },
    async deleteRun(id) {
      const res = await doFetch(`${baseUrl}/api/runs/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteRun", res);
      return (await res.json()) as DeleteRunResponse;
    },
    async browseFiles(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/browse`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("browseFiles", res);
      return (await res.json()) as BrowseFilesResponse;
    },
    async searchFiles(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/search`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("searchFiles", res);
      return (await res.json()) as SearchFilesResponse;
    },
    async readFile(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/read`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("readFile", res);
      return (await res.json()) as ReadFileResponse;
    },
    async writeFile(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/write`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("writeFile", res);
      return (await res.json()) as WriteFileResponse;
    },
    async makeDirectory(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/mkdir`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("makeDirectory", res);
      return (await res.json()) as MakeDirectoryResponse;
    },
    async deleteFile(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/delete`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("deleteFile", res);
      return (await res.json()) as DeleteFileResponse;
    },
    async renameFile(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/rename`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("renameFile", res);
      return (await res.json()) as RenameFileResponse;
    },
    async getFileMeta(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/meta`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("getFileMeta", res);
      return (await res.json()) as GetFileMetaResponse;
    },
    async setFileMeta(store, body) {
      const res = await doFetch(`${baseUrl}/api/file-stores/${store}/set-meta`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("setFileMeta", res);
      return (await res.json()) as SetFileMetaResponse;
    },
    async listApplications() {
      const res = await doFetch(`${baseUrl}/api/applications`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listApplications", res);
      return (await res.json()) as ListApplicationsResponse;
    },
    async createApplication(body) {
      const res = await doFetch(`${baseUrl}/api/applications`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createApplication", res);
      return (await res.json()) as CreateApplicationResponse;
    },
    async updateApplication(id, body) {
      const res = await doFetch(`${baseUrl}/api/applications/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateApplication", res);
      return (await res.json()) as UpdateApplicationResponse;
    },
    async deleteApplication(id) {
      const res = await doFetch(`${baseUrl}/api/applications/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteApplication", res);
      return (await res.json()) as DeleteApplicationResponse;
    },
    async buildApplication(id) {
      const res = await doFetch(`${baseUrl}/api/applications/${id}/build`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("buildApplication", res);
      return (await res.json()) as BuildApplicationResponse;
    },
    async updateApplicationClient(id) {
      const res = await doFetch(`${baseUrl}/api/applications/${id}/client`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("updateApplicationClient", res);
      return (await res.json()) as UpdateApplicationClientResponse;
    },
    async runApplicationGraphql(id, body) {
      const res = await doFetch(`${baseUrl}/api/applications/${id}/graphql`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("runApplicationGraphql", res);
      return (await res.json()) as RunApplicationGraphqlResponse;
    },
    async listFrameworks() {
      const res = await doFetch(`${baseUrl}/api/frameworks`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listFrameworks", res);
      return (await res.json()) as ListFrameworksResponse;
    },
    async listApiProviders() {
      const res = await doFetch(`${baseUrl}/api/api-providers`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listApiProviders", res);
      return (await res.json()) as ListApiProvidersResponse;
    },
    async describeCustomQuery(body) {
      const res = await doFetch(`${baseUrl}/api/custom-queries/describe`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("describeCustomQuery", res);
      return (await res.json()) as DescribeCustomQueryResponse;
    },
    async listUsers() {
      const res = await doFetch(`${baseUrl}/api/users`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listUsers", res);
      return (await res.json()) as ListUsersResponse;
    },
    async createUser(body) {
      const res = await doFetch(`${baseUrl}/api/users`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createUser", res);
      return (await res.json()) as CreateUserResponse;
    },
    async updateUser(id, body) {
      const res = await doFetch(`${baseUrl}/api/users/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateUser", res);
      return (await res.json()) as UpdateUserResponse;
    },
    async deleteUser(id) {
      const res = await doFetch(`${baseUrl}/api/users/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteUser", res);
      return (await res.json()) as DeleteUserResponse;
    },
    async setUserDisabled(id, body) {
      const res = await doFetch(`${baseUrl}/api/users/${id}/disabled`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("setUserDisabled", res);
      return (await res.json()) as SetUserDisabledResponse;
    },
    async forceLogoutUser(id) {
      const res = await doFetch(`${baseUrl}/api/users/${id}/force-logout`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("forceLogoutUser", res);
      return (await res.json()) as ForceLogoutUserResponse;
    },
    async becomeUser(id) {
      const res = await doFetch(`${baseUrl}/api/users/${id}/become`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("becomeUser", res);
      return (await res.json()) as BecomeUserResponse;
    },
    async setRandomPassword(id) {
      const res = await doFetch(`${baseUrl}/api/users/${id}/random-password`, {
        method: "POST",
        headers: requestHeaders("POST", false),
      });
      if (!res.ok) throw await clientError("setRandomPassword", res);
      return (await res.json()) as SetRandomPasswordResponse;
    },
    async listTriggers() {
      const res = await doFetch(`${baseUrl}/api/triggers`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listTriggers", res);
      return (await res.json()) as ListTriggersResponse;
    },
    async createTrigger(body) {
      const res = await doFetch(`${baseUrl}/api/triggers`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("createTrigger", res);
      return (await res.json()) as CreateTriggerResponse;
    },
    async updateTrigger(id, body) {
      const res = await doFetch(`${baseUrl}/api/triggers/${id}`, {
        method: "PUT",
        headers: requestHeaders("PUT", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateTrigger", res);
      return (await res.json()) as UpdateTriggerResponse;
    },
    async deleteTrigger(id) {
      const res = await doFetch(`${baseUrl}/api/triggers/${id}`, {
        method: "DELETE",
        headers: requestHeaders("DELETE", false),
      });
      if (!res.ok) throw await clientError("deleteTrigger", res);
      return (await res.json()) as DeleteTriggerResponse;
    },
    async runTrigger(id, body) {
      const res = await doFetch(`${baseUrl}/api/triggers/${id}/run`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("runTrigger", res);
      return (await res.json()) as RunTriggerResponse;
    },
    async listActions(query) {
      const search = new URLSearchParams();
      if (query?.table !== undefined && query?.table !== null) search.append("table", String(query?.table));
      const qs = search.toString();
      const res = await doFetch(`${baseUrl}/api/actions${qs ? `?${qs}` : ""}`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("listActions", res);
      return (await res.json()) as ListActionsResponse;
    },
    async getSettings() {
      const res = await doFetch(`${baseUrl}/api/settings`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("getSettings", res);
      return (await res.json()) as GetSettingsResponse;
    },
    async updateSettings(body) {
      const res = await doFetch(`${baseUrl}/api/settings`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("updateSettings", res);
      return (await res.json()) as UpdateSettingsResponse;
    },
    async sendTestEmail(body) {
      const res = await doFetch(`${baseUrl}/api/settings/email/test`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("sendTestEmail", res);
      return (await res.json()) as SendTestEmailResponse;
    },
    async getBackupOptions() {
      const res = await doFetch(`${baseUrl}/api/backup`, {
        method: "GET",
        headers: requestHeaders("GET", false),
      });
      if (!res.ok) throw await clientError("getBackupOptions", res);
      return (await res.json()) as GetBackupOptionsResponse;
    },
    async restoreBackup(body) {
      const res = await doFetch(`${baseUrl}/api/backup/restore`, {
        method: "POST",
        headers: requestHeaders("POST", true),
        body: JSON.stringify(body),
      });
      if (!res.ok) throw await clientError("restoreBackup", res);
      return (await res.json()) as RestoreBackupResponse;
    },
  };
}
