//! The REST [`ApiProvider`] (design §13.4).
//!
//! Projects an application's tables into a REST API in the shape the design's
//! quality bar (Hasura / PostgREST / Supabase) sets: a table `posts` becomes
//! `GET /api/posts`, `POST /api/posts`, `PUT /api/posts/{id}`, and
//! `DELETE /api/posts/{id}`. The table is a **literal** path segment, not a
//! `{table}` parameter — an app's API exposes the app's own tables, so they are
//! part of the contract and get typed client methods (`listPosts`, `createPosts`,
//! …) rather than a stringly-typed table argument. That projection is the same
//! [`EndpointSet`](crate::EndpointSet) machinery the admin API uses, so an app's
//! client is generated by the same [`generate_client`](crate::generate_client).
//!
//! **Authorization** comes from each table's own [`AccessRules`](sc_catalog::AccessRules)
//! (§7): reads require `min_role_read`, writes `min_role_write`. The provider
//! enforces the requirement before running anything, so a REST caller sees
//! exactly what a user of that role would — there is no path into the data that
//! skips the check.
//!
//! **Authentication**: the projection includes the app's own `login` / `logout` /
//! `whoami`, so a React app authenticates against `sc-auth` through its own API
//! rather than borrowing the admin's (§7.2). `login` is the one public endpoint —
//! it is how a caller stops being anonymous — and it verifies credentials against
//! the same `sc_auth::authenticate` the admin login uses, for any role rather
//! than admins only. The provider never touches cookies: it returns a
//! [`SessionAction`] and the transport mints and carries the token.
//!
//! **Custom routes** (developer-authored guest code or SQL, §13.4) are carried by
//! the endpoint model and rejected with `501 Not Implemented` at runtime: the
//! MVP stubs them (see `TODO.md` Phase 9), and the honest failure is better than
//! pretending. **Actions** are not projected: the actions registry (`sc-action`)
//! is explicitly outside MVP scope, so there is nothing yet to project.

use std::collections::HashMap;

use async_trait::async_trait;
use sc_auth::{User, authenticate};
use sc_catalog::{Catalog, Table};
use sc_error::{Error, Result};
use serde_json::{Value as Json, json};

use crate::auth::{credentials, credentials_schema, user_summary_json, user_summary_schema};
use crate::endpoint::{AuthRequirement, Endpoint, EndpointSet, HandlerRef, Method, PathSpec};
use crate::provider::{ApiProvider, ApiRequest, ApiResponse};
use crate::rows;
use crate::schema::{TypeSchema, ValueType};

/// The provider's registered name.
pub const REST_PROVIDER: &str = "rest";

/// Which table operation an endpoint runs. Recorded per endpoint at projection
/// time so dispatch is a lookup rather than a re-parse of the path.
#[derive(Debug, Clone, PartialEq, Eq)]
enum RestOp {
    /// `GET /{table}` — every row.
    List,
    /// `POST /{table}` — insert a row.
    Create,
    /// `PUT /{table}/{id}` — update the row with that primary key.
    Update,
    /// `DELETE /{table}/{id}` — delete the row with that primary key.
    Delete,
}

/// A projected table endpoint: the operation and the table it runs against.
#[derive(Debug, Clone)]
struct TableRoute {
    op: RestOp,
    table: String,
}

/// The endpoint names of the app's own auth operations. They are fixed rather
/// than derived from a table, so a table cannot collide with them: `op_name`
/// always prefixes a table's operations with `list`/`create`/`update`/`delete`.
const LOGIN: &str = "login";
const LOGOUT: &str = "logout";
const WHOAMI: &str = "whoami";

/// A REST projection of an application's endpoint set (design §13.4).
pub struct RestProvider {
    mount: String,
    endpoints: EndpointSet,
    /// Endpoint name → the table operation it runs. Custom routes are absent
    /// here; they resolve through their [`HandlerRef`] instead.
    routes: HashMap<String, TableRoute>,
}

impl RestProvider {
    /// Project `tables` into a REST API mounted at `mount`.
    ///
    /// The tables are the application's declared subset, already resolved
    /// against the catalog by the caller — an app only ever exposes the tables it
    /// declares (§13.2), and this crate sits below `sc-app` so it takes the
    /// resolved tables rather than the `Application`.
    ///
    /// Each table contributes four endpoints, each carrying the auth requirement
    /// its own access rules dictate. A table with no single-column primary key
    /// gets only the collection endpoints (list/create): there is no way to
    /// address one of its rows, so `PUT`/`DELETE` would be undeliverable
    /// promises.
    pub fn project(mount: impl Into<String>, tables: &[Table]) -> RestProvider {
        let mount = normalize_mount(&mount.into());
        let mut endpoints = EndpointSet::new();
        let mut routes = HashMap::new();

        // The app's own auth (§7.2). Projected for every app: an app whose users
        // cannot log in can only ever serve public-role data, and a caller has to
        // have some way to stop being anonymous. Public-role browsing still works
        // without ever calling these.
        endpoints.register(
            Endpoint::new(LOGIN, Method::Post, path_at(&mount).lit("login"))
                .input(credentials_schema())
                .output(user_summary_schema())
                // The only public endpoint: it is what turns an anonymous caller
                // into an authenticated one.
                .auth(AuthRequirement::Public),
        );
        endpoints.register(
            Endpoint::new(LOGOUT, Method::Post, path_at(&mount).lit("logout"))
                .auth(AuthRequirement::LoggedIn),
        );
        endpoints.register(
            Endpoint::new(WHOAMI, Method::Get, path_at(&mount).lit("whoami"))
                .output(user_summary_schema())
                .auth(AuthRequirement::LoggedIn),
        );

        for table in tables {
            let name = &table.name;
            let read = AuthRequirement::MinRole(table.access.min_role_read);
            let write = AuthRequirement::MinRole(table.access.min_role_write);
            let collection = || path_at(&mount).lit(name);

            let mut add = |op: RestOp, ep: Endpoint| {
                routes.insert(
                    ep.name.clone(),
                    TableRoute {
                        op,
                        table: name.clone(),
                    },
                );
                endpoints.register(ep);
            };

            add(
                RestOp::List,
                Endpoint::new(op_name("list", name), Method::Get, collection())
                    .output(TypeSchema::array(TypeSchema::json()))
                    .auth(read.clone())
                    .handler(HandlerRef::named(op_name("list", name))),
            );
            add(
                RestOp::Create,
                Endpoint::new(op_name("create", name), Method::Post, collection())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("create", name))),
            );

            // Row-addressing endpoints need exactly one primary-key column to
            // address by; `single_pk` is the same rule the row layer enforces.
            let Ok(pk) = rows::single_pk(table) else {
                continue;
            };
            let id_ty = table
                .field(&pk)
                .and_then(|f| f.base.type_.as_basic())
                .map_or(ValueType::Text, ValueType::from_basic);
            let item = || path_at(&mount).lit(name).param("id", id_ty);

            add(
                RestOp::Update,
                Endpoint::new(op_name("update", name), Method::Put, item())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("update", name))),
            );
            add(
                RestOp::Delete,
                Endpoint::new(op_name("delete", name), Method::Delete, item())
                    .output(TypeSchema::json())
                    .auth(write)
                    .handler(HandlerRef::named(op_name("delete", name))),
            );
        }

        RestProvider {
            mount,
            endpoints,
            routes,
        }
    }

    /// Add a developer-authored custom route (guest code or SQL, §13.4).
    ///
    /// The endpoint is projected and typed like any other, but running it is
    /// stubbed for the MVP: [`handle`](RestProvider::handle) answers `501 Not
    /// Implemented` for a [`HandlerRef::GuestCode`]/[`HandlerRef::Sql`] handler.
    pub fn with_custom_route(mut self, endpoint: Endpoint) -> RestProvider {
        self.endpoints.register(endpoint);
        self
    }

    /// Find the endpoint matching `req`, with its captured path parameters.
    ///
    /// `Err` distinguishes the two ways a request can miss: a path no endpoint
    /// claims (`404`) versus a path that exists but not for this method (`405`).
    fn resolve(&self, req: &ApiRequest) -> std::result::Result<(&Endpoint, Params), ApiResponse> {
        let mut path_matched = false;
        for ep in self.endpoints.iter() {
            match ep.path.match_path(&req.path) {
                Some(params) if ep.method == req.method => return Ok((ep, params)),
                Some(_) => path_matched = true,
                None => {}
            }
        }
        Err(if path_matched {
            ApiResponse::error(
                405,
                format!("{} is not allowed on {}", req.method.as_str(), req.path),
            )
        } else {
            ApiResponse::error(404, format!("no endpoint for {}", req.path))
        })
    }

    /// Verify credentials against `sc-auth` and start a session.
    ///
    /// Uses the same `authenticate` the admin login does, but for **any** role —
    /// an app's users are not admins. A bad password and an unknown user are the
    /// same `401` with the same message: distinguishing them would tell an
    /// attacker which emails are registered.
    async fn login(&self, body: &Json, cat: &Catalog) -> Result<ApiResponse> {
        let (email, password) = credentials(body)?;
        match authenticate(cat, &email, &password).await? {
            Some(user) => {
                let summary = user_summary_json(&user);
                Ok(ApiResponse::start_session(user, summary))
            }
            None => Ok(ApiResponse::error(401, "invalid credentials")),
        }
    }

    /// Run a resolved table operation.
    async fn run(
        &self,
        route: &TableRoute,
        params: &Params,
        body: &Json,
        cat: &Catalog,
    ) -> Result<ApiResponse> {
        let table = cat.require(&route.table)?;
        let id = || -> Result<&str> {
            params
                .get("id")
                .map(String::as_str)
                .ok_or_else(|| Error::invalid("missing path parameter `id`"))
        };
        Ok(match route.op {
            RestOp::List => ApiResponse::ok(rows::list_rows(cat, &table).await?),
            RestOp::Create => {
                ApiResponse::with_status(201, rows::create_row(cat, &table, body).await?)
            }
            RestOp::Update => ApiResponse::ok(rows::update_row(cat, &table, id()?, body).await?),
            RestOp::Delete => ApiResponse::ok(rows::delete_row(cat, &table, id()?).await?),
        })
    }
}

/// Captured path parameters.
type Params = HashMap<String, String>;

#[async_trait]
impl ApiProvider for RestProvider {
    fn name(&self) -> &str {
        REST_PROVIDER
    }

    fn mount(&self) -> String {
        self.mount.clone()
    }

    fn endpoints(&self) -> &EndpointSet {
        &self.endpoints
    }

    async fn handle(
        &self,
        req: ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let (endpoint, params) = match self.resolve(&req) {
            Ok(found) => found,
            Err(rejection) => return Ok(rejection),
        };

        // Authorization first, always: every API surface goes through the §7
        // layer, and nothing below this line runs until it passes.
        if let Some(rejection) = enforce_auth(&endpoint.auth, user) {
            return Ok(rejection);
        }

        match &endpoint.handler {
            HandlerRef::Named(_) if endpoint.name == LOGIN => self.login(&req.body, cat).await,
            HandlerRef::Named(_) if endpoint.name == LOGOUT => {
                Ok(ApiResponse::end_session(json!({ "ok": true })))
            }
            HandlerRef::Named(_) if endpoint.name == WHOAMI => Ok(ApiResponse::ok(
                // `LoggedIn` is enforced above, so a caller is present here.
                user.map_or(Json::Null, user_summary_json),
            )),
            HandlerRef::Named(_) => match self.routes.get(&endpoint.name) {
                Some(route) => self.run(route, &params, &req.body, cat).await,
                // A named handler with no projected table route: the set was
                // extended with a route this provider cannot run.
                None => Ok(ApiResponse::error(
                    501,
                    format!("endpoint `{}` has no implementation", endpoint.name),
                )),
            },
            // Custom routes are carried by the model but not executable in the
            // MVP (design §13.4; TODO Phase 9).
            HandlerRef::GuestCode { language, .. } => Ok(ApiResponse::error(
                501,
                format!("custom {language} routes are not implemented yet"),
            )),
            HandlerRef::Sql(_) => Ok(ApiResponse::error(
                501,
                "custom SQL routes are not implemented yet",
            )),
        }
    }
}

/// Check a caller against an [`AuthRequirement`], returning a rejection when it
/// does not pass. Mirrors the server's own dispatch check, in the provider's
/// JSON vocabulary.
fn enforce_auth(auth: &AuthRequirement, user: Option<&User>) -> Option<ApiResponse> {
    let unauthenticated = || ApiResponse::error(401, "authentication required");
    match auth {
        AuthRequirement::Public => None,
        AuthRequirement::LoggedIn => user.is_none().then(unauthenticated),
        AuthRequirement::MinRole(min) => match user {
            None => Some(unauthenticated()),
            Some(u) if u.meets_role(*min) => None,
            Some(_) => Some(ApiResponse::error(403, "insufficient privilege")),
        },
    }
}

/// A `PathSpec` rooted at the provider's mount.
fn path_at(mount: &str) -> PathSpec {
    PathSpec::root().lit(mount)
}

/// Normalise a mount to a single leading slash and no trailing slash.
fn normalize_mount(raw: &str) -> String {
    let trimmed = raw.trim_matches('/');
    if trimmed.is_empty() {
        "/".to_owned()
    } else {
        format!("/{trimmed}")
    }
}

/// The endpoint (and generated client method) name for an operation on a table:
/// `list` + `blog_posts` → `listBlogPosts`. Table names are unique, so these are
/// unique too; the result is a valid TypeScript identifier as long as the table
/// name is alphanumeric-ish, which the catalog's own naming already requires.
fn op_name(op: &str, table: &str) -> String {
    let mut out = String::from(op);
    for word in table
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
    {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_catalog::{AccessRules, DataField, DbId, TableId, TableSource};
    use sc_types::{BasicType, TypeRef};

    /// A table named `name` with an `id` primary key and a `title` text column.
    fn table(name: &str, access: AccessRules) -> Table {
        Table {
            id: TableId(name.to_owned()),
            name: name.to_owned(),
            database: DbId::primary(),
            source: TableSource::Database,
            fields: vec![
                DataField::plain("id", TypeRef::Basic(BasicType::Int)).primary_key(),
                DataField::plain("title", TypeRef::Basic(BasicType::Text)),
            ],
            primary_key: vec!["id".to_owned()],
            access,
            attributes: Default::default(),
        }
    }

    /// A table with no primary key at all.
    fn keyless(name: &str) -> Table {
        let mut t = table(name, AccessRules::default());
        t.primary_key.clear();
        t.fields = vec![DataField::plain("title", TypeRef::Basic(BasicType::Text))];
        t
    }

    /// A user with the given role. Roles run 1..=100, lower = more privileged.
    fn user(role: u8) -> User {
        User::new(uuid::Uuid::new_v4(), role).expect("role in range")
    }

    /// Every app's projection carries `login`, `logout`, and `whoami` on top of
    /// its per-table endpoints.
    const AUTH_ENDPOINTS: usize = 3;

    #[test]
    fn projects_four_rest_endpoints_per_table() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert_eq!(p.name(), "rest");
        assert_eq!(p.mount(), "/api");
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4);

        // The table is a literal segment — the app's own tables are its contract.
        let list = p.endpoints().find("listPosts").unwrap();
        assert_eq!(list.method, Method::Get);
        assert_eq!(list.path.pattern(), "/api/posts");

        let create = p.endpoints().find("createPosts").unwrap();
        assert_eq!(create.method, Method::Post);
        assert_eq!(create.path.pattern(), "/api/posts");

        // Row-addressed endpoints take the primary key as a typed parameter.
        let update = p.endpoints().find("updatePosts").unwrap();
        assert_eq!(update.method, Method::Put);
        assert_eq!(update.path.pattern(), "/api/posts/{id}");

        let delete = p.endpoints().find("deletePosts").unwrap();
        assert_eq!(delete.method, Method::Delete);
        assert_eq!(delete.path.pattern(), "/api/posts/{id}");
    }

    #[test]
    fn endpoint_names_are_camel_cased_typescript_identifiers() {
        assert_eq!(op_name("list", "blog_posts"), "listBlogPosts");
        assert_eq!(op_name("create", "posts"), "createPosts");
        // Non-alphanumeric separators are word boundaries, not literal output.
        assert_eq!(op_name("delete", "a-b"), "deleteAB");
    }

    #[test]
    fn table_access_rules_become_the_endpoints_auth() {
        let strict = AccessRules {
            min_role_read: 80,
            min_role_write: 1,
        };
        let p = RestProvider::project("/api", &[table("posts", strict)]);
        // Reads take min_role_read; writes take min_role_write (§7).
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().auth,
            AuthRequirement::MinRole(80)
        );
        for name in ["createPosts", "updatePosts", "deletePosts"] {
            assert_eq!(
                p.endpoints().find(name).unwrap().auth,
                AuthRequirement::MinRole(1),
                "{name}"
            );
        }
    }

    #[test]
    fn a_table_without_a_single_primary_key_gets_only_collection_endpoints() {
        // No key ⇒ no way to address a row, so no PUT/DELETE is promised.
        let p = RestProvider::project("/api", &[keyless("logs")]);
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 2);
        assert!(p.endpoints().find("listLogs").is_some());
        assert!(p.endpoints().find("createLogs").is_some());
        assert!(p.endpoints().find("updateLogs").is_none());
        assert!(p.endpoints().find("deleteLogs").is_none());
    }

    #[test]
    fn only_the_declared_tables_are_projected() {
        // The app declared `posts`; `secrets` is not in its subset (§13.2), so
        // the projection has no route to it at all.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert!(p.endpoints().find("listSecrets").is_none());
        assert!(
            p.resolve(&ApiRequest::get("/api/secrets")).is_err(),
            "an undeclared table must not be routable"
        );
    }

    #[test]
    fn mount_is_normalised_and_reflected_in_paths() {
        let p = RestProvider::project("v1/api/", &[table("posts", AccessRules::default())]);
        assert_eq!(p.mount(), "/v1/api");
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().path.pattern(),
            "/v1/api/posts"
        );
    }

    #[test]
    fn resolve_matches_method_and_path_and_captures_params() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let (ep, params) = p
            .resolve(&ApiRequest::new(Method::Put, "/api/posts/42"))
            .unwrap();
        assert_eq!(ep.name, "updatePosts");
        assert_eq!(params.get("id").unwrap(), "42");

        // A collection path captures nothing.
        let (ep, params) = p.resolve(&ApiRequest::get("/api/posts")).unwrap();
        assert_eq!(ep.name, "listPosts");
        assert!(params.is_empty());
    }

    #[test]
    fn unknown_path_is_404_and_wrong_method_is_405() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let miss = p.resolve(&ApiRequest::get("/api/nope")).unwrap_err();
        assert_eq!(miss.status, 404);

        // `/api/posts` exists, but not for PATCH.
        let wrong = p
            .resolve(&ApiRequest::new(Method::Patch, "/api/posts"))
            .unwrap_err();
        assert_eq!(wrong.status, 405);
    }

    #[test]
    fn auth_is_enforced_before_anything_runs() {
        // Anonymous callers are rejected...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), None)
                .unwrap()
                .status,
            401
        );
        // ...under-privileged ones are forbidden...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), Some(&user(100)))
                .unwrap()
                .status,
            403
        );
        // ...and a sufficiently privileged one passes. Roles run 1..=100 with
        // lower = more privilege, so admin (1) clears a min_role of 80.
        assert!(enforce_auth(&AuthRequirement::MinRole(80), Some(&user(1))).is_none());
        assert!(enforce_auth(&AuthRequirement::Public, None).is_none());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, Some(&user(100))).is_none());
    }

    #[test]
    fn custom_routes_are_projected_and_typed() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())])
            .with_custom_route(
                Endpoint::new("search", Method::Post, PathSpec::root().lit("api/search"))
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .handler(HandlerRef::Sql("select 1".to_owned())),
            );
        // The custom route is part of the contract even though it is stubbed.
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4 + 1);
        let ep = p.endpoints().find("search").unwrap();
        assert!(matches!(ep.handler, HandlerRef::Sql(_)));

        // A generated client types it like any other endpoint.
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("search("));
        assert!(ts.contains("listPosts()"));
    }

    #[test]
    fn every_app_projects_its_own_auth_endpoints() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        // The app authenticates against its own API, not the admin's (§7.2).
        let login = p.endpoints().find("login").unwrap();
        assert_eq!(login.method, Method::Post);
        assert_eq!(login.path.pattern(), "/api/login");
        // Login is the one public endpoint: it is how a caller stops being
        // anonymous. Everything else needs a session.
        assert_eq!(login.auth, AuthRequirement::Public);

        assert_eq!(
            p.endpoints().find("logout").unwrap().auth,
            AuthRequirement::LoggedIn
        );
        assert_eq!(
            p.endpoints().find("whoami").unwrap().auth,
            AuthRequirement::LoggedIn
        );

        // Anonymous callers are turned away from everything but login.
        assert!(p.resolve(&ApiRequest::get("/api/whoami")).is_ok());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&login.auth, None).is_none());
    }

    #[test]
    fn a_table_cannot_collide_with_the_auth_endpoints() {
        // A table actually named `login` still projects `listLogin` etc., because
        // table operations are always prefixed — so it cannot shadow the app's
        // own `login`.
        let p = RestProvider::project("/api", &[table("login", AccessRules::default())]);
        assert_eq!(p.endpoints().find("login").unwrap().method, Method::Post);
        assert!(p.endpoints().find("listLogin").is_some());
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4);
    }

    #[test]
    fn the_projection_generates_a_typed_client() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let ts = crate::generate_client(p.endpoints());
        // Same generator as the admin API: an app's client is not special-cased.
        assert!(ts.contains("export interface ApiClient {"));
        assert!(ts.contains("listPosts(): Promise<ListPostsResponse>"));
        assert!(ts.contains("updatePosts(id: number"));
        assert!(ts.contains("/api/posts/${id}"));
    }
}
