//! The REST [`ApiProvider`] (design §13.4).
//!
//! Projects an application's tables into a REST API in the shape the design's
//! quality bar (Hasura / PostgREST / Supabase) sets: a table `posts` becomes
//! `GET /api/posts`, `POST /api/posts`, `PUT /api/posts/{id}`, and
//! `DELETE /api/posts/{id}`. The table is a **literal** path segment, not a
//! `{table}` parameter — an app's API exposes the app's own tables, so they are
//! part of the contract and get typed client methods (`listPosts`, `createPosts`,
//! …) rather than a stringly-typed table argument. That projection is the same
//! [`EndpointSet`](crate::EndpointSet) machinery the admin API uses, so an app's
//! client is generated by the same [`generate_client`](crate::generate_client).
//!
//! **Authorization** comes from each table's own [`AccessRules`](sc_catalog::AccessRules)
//! (§7): reads require `min_role_read`, writes `min_role_write`. The provider
//! enforces the requirement before running anything, so a REST caller sees
//! exactly what a user of that role would — there is no path into the data that
//! skips the check.
//!
//! **Authentication**: the projection includes the app's own `login` / `logout` /
//! `whoami`, so a React app authenticates against `sc-auth` through its own API
//! rather than borrowing the admin's (§7.2). `login` is the one public endpoint —
//! it is how a caller stops being anonymous — and it verifies credentials against
//! the same `sc_auth::authenticate` the admin login uses, for any role rather
//! than admins only. The provider never touches cookies: it returns a
//! [`SessionAction`] and the transport mints and carries the token.
//!
//! **Custom routes** (developer-authored guest code or SQL, §13.4) are carried by
//! the endpoint model and rejected with `501 Not Implemented` at runtime: the
//! MVP stubs them (see `TODO.md` Phase 9), and the honest failure is better than
//! pretending.
//!
//! **Triggers** are projected one endpoint each — `POST {mount}/actions/{name}`,
//! request body → the event's payload, the action's result → the response — but
//! only for the triggers the *application* names ([`project_with`](RestProvider::project_with)).
//! Server-side automation is not an API surface by default: a trigger becomes
//! callable from outside because an app said so, and one nobody named is a 404
//! rather than a 403. Authorization is the trigger's own `min_role`, defaulting
//! to **admin** when it has none — a trigger whose access nobody has thought
//! about must not be the one that turns out to be public.

use std::collections::HashMap;
use std::sync::Arc;

use async_trait::async_trait;
use sc_auth::{User, authenticate};
use sc_catalog::{CallerContext, Catalog, DataFieldKind, Table, load_file_store_by_name};
use sc_error::{Error, Result};
use sc_expr::{JsEvaluator, Operation};
use sc_files::{ROLE_PUBLIC, check_access, mime_for_path, validate_file_path};
use sc_query::Value;
use serde_json::{Value as Json, json};

use crate::auth::{credentials, credentials_schema, user_summary_json, user_summary_schema};
use crate::endpoint::{AuthRequirement, Endpoint, EndpointSet, HandlerRef, Method, PathSpec};
use crate::ownership;
use crate::provider::{ApiProvider, ApiRequest, ApiResponse};
use crate::rows;
use crate::schema::{TypeSchema, ValueType};

/// The provider's registered name.
pub const REST_PROVIDER: &str = "rest";

/// Which table operation an endpoint runs. Recorded per endpoint at projection
/// time so dispatch is a lookup rather than a re-parse of the path.
#[derive(Debug, Clone, PartialEq, Eq)]
enum RestOp {
    /// `GET /{table}` — every row.
    List,
    /// `POST /{table}` — insert a row.
    Create,
    /// `PUT /{table}/{id}` — update the row with that primary key.
    Update,
    /// `DELETE /{table}/{id}` — delete the row with that primary key.
    Delete,
    /// `GET /{table}/{id}/{field}` — serve the bytes behind the row's `File`
    /// field (§4).
    Download {
        /// The `File` field whose stored path is resolved and served.
        field: String,
    },
    /// `POST /{table}/{id}/{field}/{filename}` — store the raw request body in
    /// the field's store and folder and point the row's field at it (§4).
    Upload {
        /// The `File` field the upload lands in.
        field: String,
    },
}

/// A projected table endpoint: the operation and the table it runs against.
#[derive(Debug, Clone)]
struct TableRoute {
    op: RestOp,
    table: String,
}

/// The path segment an app's exposed triggers live under: `POST
/// {mount}/actions/{name}`.
///
/// A literal segment rather than the trigger name at the mount's root, so a
/// trigger can never collide with a table (`/api/posts` is the `posts` table
/// whatever anyone calls a trigger) and a reader of a URL can tell which of the
/// two they are looking at.
const ACTIONS_SEGMENT: &str = "actions";

/// The endpoint names of the app's own auth operations. They are fixed rather
/// than derived from a table, so a table cannot collide with them: `op_name`
/// always prefixes a table's operations with `list`/`create`/`update`/`delete`.
const LOGIN: &str = "login";
const LOGOUT: &str = "logout";
const WHOAMI: &str = "whoami";

/// A REST projection of an application's endpoint set (design §13.4).
pub struct RestProvider {
    mount: String,
    endpoints: EndpointSet,
    /// Endpoint name → the table operation it runs. Custom routes are absent
    /// here; they resolve through their [`HandlerRef`] instead.
    routes: HashMap<String, TableRoute>,
    /// Endpoint name → the trigger it runs, for the app's exposed subset.
    trigger_routes: HashMap<String, String>,
    /// The dispatcher an exposed trigger is run through. Injected by the server
    /// via [`with_dispatcher`](RestProvider::with_dispatcher); absent in the
    /// contexts that only need the endpoint *shapes* (client generation), where
    /// calling one is a configuration error rather than a silent no-op.
    dispatcher: Option<Arc<sc_action::TriggerDispatcher>>,
    /// The engine behind ownership formulas' reified path (§7.3). Injected by
    /// the server via [`with_evaluator`](RestProvider::with_evaluator); when
    /// absent, a formula that needs it **fails closed** with a configuration
    /// error rather than granting anything.
    evaluator: Option<Arc<dyn JsEvaluator>>,
}

impl RestProvider {
    /// Project `tables` into a REST API mounted at `mount`.
    ///
    /// The tables are the application's declared subset, already resolved
    /// against the catalog by the caller — an app only ever exposes the tables it
    /// declares (§13.2), and this crate sits below `sc-app` so it takes the
    /// resolved tables rather than the `Application`.
    ///
    /// Each table contributes four endpoints, each carrying the auth requirement
    /// its own access rules dictate. A table with no single-column primary key
    /// gets only the collection endpoints (list/create): there is no way to
    /// address one of its rows, so `PUT`/`DELETE` would be undeliverable
    /// promises.
    pub fn project(mount: impl Into<String>, tables: &[Table]) -> RestProvider {
        RestProvider::project_with(mount, tables, &[])
    }

    /// [`project`](RestProvider::project) plus one endpoint per exposed trigger
    /// (§10.2).
    ///
    /// The triggers are the application's declared subset, already resolved
    /// against the live trigger set by the caller — the same arrangement the
    /// tables have, and for the same reason: this crate sits below `sc-app`, so
    /// it takes what an app resolved rather than the `Application`.
    pub fn project_with(
        mount: impl Into<String>,
        tables: &[Table],
        triggers: &[sc_action::Trigger],
    ) -> RestProvider {
        let mount = normalize_mount(&mount.into());
        let mut endpoints = EndpointSet::new();
        let mut routes = HashMap::new();
        let mut trigger_routes = HashMap::new();

        // The app's own auth (§7.2). Projected for every app: an app whose users
        // cannot log in can only ever serve public-role data, and a caller has to
        // have some way to stop being anonymous. Public-role browsing still works
        // without ever calling these.
        endpoints.register(
            Endpoint::new(LOGIN, Method::Post, path_at(&mount).lit("login"))
                .input(credentials_schema())
                .output(user_summary_schema())
                // The only public endpoint: it is what turns an anonymous caller
                // into an authenticated one.
                .auth(AuthRequirement::Public),
        );
        endpoints.register(
            Endpoint::new(LOGOUT, Method::Post, path_at(&mount).lit("logout"))
                .auth(AuthRequirement::LoggedIn),
        );
        endpoints.register(
            Endpoint::new(WHOAMI, Method::Get, path_at(&mount).lit("whoami"))
                .output(user_summary_schema())
                .auth(AuthRequirement::LoggedIn),
        );

        for table in tables {
            let name = &table.name;
            // A table with an ownership formula relaxes its endpoints to
            // Public (§7.3): the formula decides `user === null` — an admin
            // may grant anonymous callers rows — so the gate moves from the
            // endpoint's auth into the handler, where the rule becomes
            // "meets the role floor OR the formula grants the row". A table
            // without a formula keeps the MinRole gate exactly as before.
            let (read, write) = if table.ownership.is_some() {
                (AuthRequirement::Public, AuthRequirement::Public)
            } else {
                (
                    AuthRequirement::MinRole(table.access.min_role_read),
                    AuthRequirement::MinRole(table.access.min_role_write),
                )
            };
            let collection = || path_at(&mount).lit(name);

            let mut add = |op: RestOp, ep: Endpoint| {
                routes.insert(
                    ep.name.clone(),
                    TableRoute {
                        op,
                        table: name.clone(),
                    },
                );
                endpoints.register(ep);
            };

            add(
                RestOp::List,
                Endpoint::new(op_name("list", name), Method::Get, collection())
                    .output(TypeSchema::array(TypeSchema::json()))
                    .auth(read.clone())
                    .handler(HandlerRef::named(op_name("list", name))),
            );
            add(
                RestOp::Create,
                Endpoint::new(op_name("create", name), Method::Post, collection())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("create", name))),
            );

            // Row-addressing endpoints need exactly one primary-key column to
            // address by; `single_pk` is the same rule the row layer enforces.
            let Ok(pk) = rows::single_pk(table) else {
                continue;
            };
            let id_ty = table
                .field(&pk)
                .and_then(|f| f.base.type_.as_basic())
                .map_or(ValueType::Text, ValueType::from_basic);
            let item = || path_at(&mount).lit(name).param("id", id_ty);

            add(
                RestOp::Update,
                Endpoint::new(op_name("update", name), Method::Put, item())
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("update", name))),
            );
            add(
                RestOp::Delete,
                Endpoint::new(op_name("delete", name), Method::Delete, item())
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("delete", name))),
            );

            // A `File` field's bytes (§4), addressed **by table, row id and
            // field name** — never by raw store path. The row is what the caller
            // is allowed to see, and letting an app name an arbitrary path would
            // make the field's folder restriction advisory. Reads carry the
            // table's read rule, uploads its write rule; the file's own
            // path-cumulative `min_role` is enforced on top at request time, so
            // the stricter of the two always decides.
            for data_field in &table.fields {
                if !matches!(data_field.kind, DataFieldKind::File { .. }) {
                    continue;
                }
                let field = &data_field.base.name;
                let scoped = format!("{name}_{field}");
                let file_item = || path_at(&mount).lit(name).param("id", id_ty).lit(field);
                add(
                    RestOp::Download {
                        field: field.clone(),
                    },
                    Endpoint::new(op_name("download", &scoped), Method::Get, file_item())
                        .binary_output()
                        .auth(read.clone())
                        .handler(HandlerRef::named(op_name("download", &scoped))),
                );
                add(
                    RestOp::Upload {
                        field: field.clone(),
                    },
                    Endpoint::new(
                        op_name("upload", &scoped),
                        Method::Post,
                        // The filename is a path parameter, so it is one
                        // segment by construction — a nested or traversing
                        // destination cannot even be expressed in the URL.
                        file_item().param("filename", ValueType::Text),
                    )
                    .binary_input()
                    .output(TypeSchema::json())
                    .auth(write.clone())
                    .handler(HandlerRef::named(op_name("upload", &scoped))),
                );
            }
        }

        // The app's exposed triggers, one `POST {mount}/actions/{name}` each.
        // The role floor is the trigger's own, and an unset one is **admin**:
        // `min_role` is optional on a trigger because most triggers are never
        // called from outside at all, so its absence means "nobody has decided",
        // which must not read as "everybody".
        for trigger in triggers {
            let name = op_name("run", &trigger.name);
            trigger_routes.insert(name.clone(), trigger.name.clone());
            endpoints.register(
                Endpoint::new(
                    name.clone(),
                    Method::Post,
                    path_at(&mount).lit(ACTIONS_SEGMENT).lit(&trigger.name),
                )
                // The posted body *is* the event's payload, whatever shape the
                // action's configuration reads out of it, so it is typed as
                // json rather than as a struct nobody could derive.
                .input(TypeSchema::json())
                .output(TypeSchema::json())
                .auth(AuthRequirement::MinRole(
                    trigger.min_role.unwrap_or(sc_auth::ROLE_ADMIN),
                ))
                .handler(HandlerRef::named(name)),
            );
        }

        RestProvider {
            mount,
            endpoints,
            routes,
            trigger_routes,
            dispatcher: None,
            evaluator: None,
        }
    }

    /// Inject the JavaScript evaluator ownership formulas' reified path runs
    /// on. The server constructs one engine and shares it across every
    /// provider; a provider without one still enforces translatable formulas
    /// symbolically and fails closed on the rest.
    pub fn with_evaluator(mut self, evaluator: Arc<dyn JsEvaluator>) -> RestProvider {
        self.evaluator = Some(evaluator);
        self
    }

    /// Inject the trigger dispatcher an exposed trigger's endpoint runs through
    /// — the *same* dispatcher every other event fires on, so a trigger called
    /// over an app's API is the trigger the admin configured, with the same
    /// `only_if`, the same cascade bound and the same action.
    pub fn with_dispatcher(
        mut self,
        dispatcher: Arc<sc_action::TriggerDispatcher>,
    ) -> RestProvider {
        self.dispatcher = Some(dispatcher);
        self
    }

    /// Run one of the app's exposed triggers, with the request body as the
    /// event's payload and the caller travelling with it (§10.2).
    ///
    /// The caller is not merely recorded: it is what the trigger's action sees as
    /// `user`, and what a row the action writes reports as the cause of its own
    /// event. A failing action comes back as an **error** — somebody asked for
    /// this one, so somebody is waiting for the answer — which is the same
    /// contract the admin's "run this now" button has.
    async fn run_trigger(
        &self,
        trigger: &str,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let dispatcher = self.dispatcher.as_ref().ok_or_else(|| {
            Error::config(format!(
                "this application exposes trigger `{trigger}` but no trigger \
                 dispatcher is available in this context, so it cannot be run"
            ))
        })?;
        let caller = ownership::caller_context(user);
        let result = dispatcher
            .run_trigger(cat, trigger, req.body.clone(), Some(&caller))
            .await?;
        Ok(ApiResponse::ok(result))
    }

    /// Add a developer-authored custom route (guest code or SQL, §13.4).
    ///
    /// The endpoint is projected and typed like any other, but running it is
    /// stubbed for the MVP: [`handle`](RestProvider::handle) answers `501 Not
    /// Implemented` for a [`HandlerRef::GuestCode`]/[`HandlerRef::Sql`] handler.
    pub fn with_custom_route(mut self, endpoint: Endpoint) -> RestProvider {
        self.endpoints.register(endpoint);
        self
    }

    /// Find the endpoint matching `req`, with its captured path parameters.
    ///
    /// `Err` distinguishes the two ways a request can miss: a path no endpoint
    /// claims (`404`) versus a path that exists but not for this method (`405`).
    // `clippy::result_large_err` does not apply: the `Err` here is not an error
    // being propagated up a call stack, it *is* the response to send — the one
    // caller either dispatches the endpoint or returns this `ApiResponse`
    // unchanged. Boxing it would add an indirection at seven call sites to shrink
    // a value that is constructed once per missed request and immediately
    // returned. (`ApiResponse` already boxes the one field worth boxing, `raw`.)
    #[allow(clippy::result_large_err)]
    fn resolve(&self, req: &ApiRequest) -> std::result::Result<(&Endpoint, Params), ApiResponse> {
        let mut path_matched = false;
        for ep in self.endpoints.iter() {
            match ep.path.match_path(&req.path) {
                Some(params) if ep.method == req.method => return Ok((ep, params)),
                Some(_) => path_matched = true,
                None => {}
            }
        }
        Err(if path_matched {
            ApiResponse::error(
                405,
                format!("{} is not allowed on {}", req.method.as_str(), req.path),
            )
        } else {
            ApiResponse::error(404, format!("no endpoint for {}", req.path))
        })
    }

    /// Verify credentials against `sc-auth` and start a session.
    ///
    /// Uses the same `authenticate` the admin login does, but for **any** role —
    /// an app's users are not admins. A bad password and an unknown user are the
    /// same `401` with the same message: distinguishing them would tell an
    /// attacker which emails are registered.
    async fn login(&self, body: &Json, cat: &Catalog) -> Result<ApiResponse> {
        let (email, password) = credentials(body)?;
        match authenticate(cat, &email, &password).await? {
            Some(user) => {
                let summary = user_summary_json(&user);
                Ok(ApiResponse::start_session(user, summary))
            }
            None => Ok(ApiResponse::error(401, "invalid credentials")),
        }
    }

    /// Run a resolved table operation, enforcing the §7.3 access rule:
    /// **meets the operation's role floor OR the ownership formula grants the
    /// row**. Callers at or above the floor take exactly the pre-formula
    /// paths; everyone else exists only where the formula says so — and a row
    /// the formula withholds answers with the *same* not-found a missing row
    /// gets, so nothing about the table's contents can be probed.
    async fn run(
        &self,
        route: &TableRoute,
        params: &Params,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let table = cat.require(&route.table)?;
        let body = &req.body;
        let id = || -> Result<&str> {
            params
                .get("id")
                .map(String::as_str)
                .ok_or_else(|| Error::invalid("missing path parameter `id`"))
        };
        // When the database enforces this table's ownership (§6), the runtime
        // checks below are switched off entirely: every row operation runs in a
        // caller-context transaction and the generated policies decide. "You no
        // longer have to check" (GOALS), and joinfields are not refetched — the
        // policies' correlated subselects do that in the database.
        if table.rls_enabled {
            return self.run_rls(route, &table, params, req, cat, user).await;
        }
        // The caller's role for the path-cumulative file rule. Anonymous is
        // public; the table-level gate (floor or formula) runs separately.
        let role = user.map_or(ROLE_PUBLIC, |u| u.role);
        let meets_read = ownership::meets(user, table.access.min_role_read);
        let meets_write = ownership::meets(user, table.access.min_role_write);
        // The formula, for callers below the floor. Its absence there means
        // the endpoint was Public only by a stale projection — deny exactly as
        // the MinRole gate would have.
        // `Err(())` is "deny as the MinRole gate would" — the response is built
        // at the call site to keep this closure's error small.
        let formula = |allowed: bool| -> std::result::Result<Option<&sc_expr::Formula>, ()> {
            if allowed {
                Ok(None)
            } else {
                match &table.ownership {
                    Some(f) => Ok(Some(f)),
                    None => Err(()),
                }
            }
        };
        let evaluator = self.evaluator.as_ref();
        // The caller, travelling with every write so the event it raises knows
        // who caused it (§10.2). On this path it sets no GUCs — the table is not
        // RLS-enforced, and `rows` routes by the table, not by the context's
        // presence — it is identity, not authority.
        let caller = ownership::caller_context(user);

        Ok(match &route.op {
            RestOp::List => match formula(meets_read) {
                Err(()) => forbidden(user),
                Ok(None) => ApiResponse::ok(rows::list_rows(cat, &table).await?),
                Ok(Some(f)) => ApiResponse::ok(
                    ownership::list_owned_rows(cat, &table, f, user, evaluator).await?,
                ),
            },
            RestOp::Create => {
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // An insert is checked against the proposed row, `_insert`
                    // folded true (§7.3) — WITH CHECK semantics at runtime.
                    Ok(Some(f)) => {
                        let proposed = rows::coerce_row_values(&table, body)?;
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Insert,
                            user,
                            evaluator,
                            &proposed,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "this row is outside your ownership",
                            ));
                        }
                    }
                }
                ApiResponse::with_status(
                    201,
                    rows::create_row_ctx(cat, &table, body, Some(&caller)).await?,
                )
            }
            RestOp::Update => {
                let id = id()?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => ApiResponse::ok(
                        rows::update_row_ctx(cat, &table, id, body, Some(&caller)).await?,
                    ),
                    Ok(Some(f)) => {
                        // USING: granted on the existing row…
                        let existing = self
                            .owned_row(cat, &table, f, Operation::Update, user, id)
                            .await?;
                        // …and WITH CHECK: granted on the proposed row too, so
                        // an update cannot move the row out of the caller's
                        // ownership.
                        let changes = rows::coerce_row_values(&table, body)?;
                        let merged = ownership::merged_row(&table, &existing, &changes);
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Update,
                            user,
                            evaluator,
                            &merged,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "the update would move this row out of your ownership",
                            ));
                        }
                        // The translated predicate rides in the UPDATE's WHERE
                        // when it can, closing the check-to-write race.
                        let guard =
                            ownership::write_guard(cat, &table, f, Operation::Update, user)?;
                        ApiResponse::ok(
                            rows::update_row_guarded(cat, &table, id, body, guard, Some(&caller))
                                .await?,
                        )
                    }
                }
            }
            RestOp::Delete => {
                let id = id()?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {
                        ApiResponse::ok(rows::delete_row_ctx(cat, &table, id, Some(&caller)).await?)
                    }
                    Ok(Some(f)) => {
                        self.owned_row(cat, &table, f, Operation::Delete, user, id)
                            .await?;
                        let guard =
                            ownership::write_guard(cat, &table, f, Operation::Delete, user)?;
                        ApiResponse::ok(
                            rows::delete_row_guarded(cat, &table, id, guard, Some(&caller)).await?,
                        )
                    }
                }
            }
            RestOp::Download { field } => {
                match formula(meets_read) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // A file read is a read of the row (§7.3); the file's own
                    // path-cumulative rule still runs inside `download`.
                    Ok(Some(f)) => {
                        self.owned_row(cat, &table, f, Operation::Read, user, id()?)
                            .await?;
                    }
                }
                download(cat, &table, field, id()?, role).await?
            }
            RestOp::Upload { field } => {
                let filename = params
                    .get("filename")
                    .map(String::as_str)
                    .ok_or_else(|| Error::invalid("missing path parameter `filename`"))?;
                match formula(meets_write) {
                    Err(()) => return Ok(forbidden(user)),
                    Ok(None) => {}
                    // An upload updates the row's field: granted on the
                    // existing row, and on the row as it will be — the formula
                    // may read the very field being written.
                    Ok(Some(f)) => {
                        let id = id()?;
                        let existing = self
                            .owned_row(cat, &table, f, Operation::Update, user, id)
                            .await?;
                        let (_, folder, _) = file_field(&table, field)?;
                        let path = upload_path(folder, filename);
                        let mut changes = std::collections::BTreeMap::new();
                        changes.insert(field.clone(), Value::Text(path));
                        let merged = ownership::merged_row(&table, &existing, &changes);
                        if !ownership::row_allowed(
                            cat,
                            &table,
                            f,
                            Operation::Update,
                            user,
                            evaluator,
                            &merged,
                        )
                        .await?
                        {
                            return Ok(ApiResponse::error(
                                403,
                                "the upload would move this row out of your ownership",
                            ));
                        }
                    }
                }
                upload_ctx(
                    cat,
                    &table,
                    field,
                    id()?,
                    filename,
                    req.raw.clone(),
                    role,
                    &caller,
                )
                .await?
            }
        })
    }

    /// The existing row `id`, granted to the caller by the formula for `op` —
    /// or the **same not-found a missing row gets**, which is what makes
    /// denial indistinguishable from absence.
    async fn owned_row(
        &self,
        cat: &Catalog,
        table: &Table,
        formula: &sc_expr::Formula,
        op: Operation,
        user: Option<&User>,
        id: &str,
    ) -> Result<std::collections::BTreeMap<String, Value>> {
        let not_found = || {
            let pk = rows::single_pk(table)?;
            Err(Error::not_found(format!("no row with {pk} = {id}")))
        };
        let Some(existing) = ownership::fetch_row_values(cat, table, formula, id).await? else {
            return not_found();
        };
        if !ownership::row_allowed(
            cat,
            table,
            formula,
            op,
            user,
            self.evaluator.as_ref(),
            &existing,
        )
        .await?
        {
            return not_found();
        }
        Ok(existing)
    }

    /// Run a row operation on an **RLS-enabled** table (§6): the database's
    /// policies do all the gating, so there is no formula translation, no
    /// evaluator, and no fetch-then-check here. Every statement runs through a
    /// caller-context transaction, and a policy that withholds a row surfaces
    /// as the same not-found an absent row gets (`run_in_context` maps `42501`).
    /// The file endpoints still layer the path-cumulative file rule on top.
    async fn run_rls(
        &self,
        route: &TableRoute,
        table: &Table,
        params: &Params,
        req: &ApiRequest,
        cat: &Catalog,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let ctx = ownership::caller_context(user);
        let body = &req.body;
        let role = user.map_or(ROLE_PUBLIC, |u| u.role);
        let id = || -> Result<&str> {
            params
                .get("id")
                .map(String::as_str)
                .ok_or_else(|| Error::invalid("missing path parameter `id`"))
        };
        Ok(match &route.op {
            RestOp::List => {
                ApiResponse::ok(rows::list_rows_where(cat, table, None, Some(&ctx)).await?)
            }
            RestOp::Create => ApiResponse::with_status(
                201,
                rows::create_row_ctx(cat, table, body, Some(&ctx)).await?,
            ),
            RestOp::Update => ApiResponse::ok(
                rows::update_row_guarded(cat, table, id()?, body, None, Some(&ctx)).await?,
            ),
            RestOp::Delete => ApiResponse::ok(
                rows::delete_row_guarded(cat, table, id()?, None, Some(&ctx)).await?,
            ),
            RestOp::Download { field } => {
                download_ctx(cat, table, field, id()?, role, &ctx).await?
            }
            RestOp::Upload { field } => {
                let filename = params
                    .get("filename")
                    .map(String::as_str)
                    .ok_or_else(|| Error::invalid("missing path parameter `filename`"))?;
                upload_ctx(
                    cat,
                    table,
                    field,
                    id()?,
                    filename,
                    req.raw.clone(),
                    role,
                    &ctx,
                )
                .await?
            }
        })
    }
}

/// The rejection a caller below the floor gets when no formula extends access:
/// exactly what the `MinRole` gate answers, per caller state.
fn forbidden(user: Option<&User>) -> ApiResponse {
    match user {
        None => ApiResponse::error(401, "authentication required"),
        Some(_) => ApiResponse::error(403, "insufficient privilege"),
    }
}

/// The store-relative path an upload of `filename` lands at — the same shape
/// `upload` itself builds, factored so the ownership pre-check sees the row
/// exactly as it will be written.
fn upload_path(folder: Option<&str>, filename: &str) -> String {
    match folder
        .map(|f| f.trim_matches('/'))
        .filter(|f| !f.is_empty())
    {
        Some(folder) => format!("{folder}/{filename}"),
        None => filename.to_owned(),
    }
}

/// Serve the bytes behind a row's `File` field (§4).
///
/// The table's `min_role_read` was enforced as the endpoint's auth before this
/// ran; here the file's own **path-cumulative** `min_role` (§14.1) is enforced
/// on top — the stricter of the two decides, never the looser, because both
/// checks must pass. The projection only routes file endpoints for `File`
/// fields, but the catalog may have changed under a mounted app, so the current
/// field is re-checked rather than trusted.
async fn download(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
) -> Result<ApiResponse> {
    download_inner(cat, table, field, id, role, None).await
}

/// [`download`] resolving the row's file path through an RLS caller context
/// (§6), so a file behind a row the policies withhold is a not-found.
async fn download_ctx(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
    context: &CallerContext,
) -> Result<ApiResponse> {
    download_inner(cat, table, field, id, role, Some(context)).await
}

async fn download_inner(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    role: u8,
    context: Option<&CallerContext>,
) -> Result<ApiResponse> {
    let (store_name, _, _) = file_field(table, field)?;
    let path = match rows::read_field_ctx(cat, table, field, id, context).await? {
        Value::Text(path) if !path.is_empty() => path,
        // The row exists but references nothing: for the caller that is "no
        // file here", the same not-found an empty shelf gets.
        _ => {
            return Err(Error::not_found(format!(
                "row {id} has no file in `{field}`"
            )));
        }
    };
    let store = cat.require_file_store(store_name)?;
    let floor = store_floor(cat, store_name).await?;
    check_access(store.as_ref(), floor, &path, role).await?;
    let bytes = store.read(&path).await?;
    // Content type by extension, exactly as the field's MIME allow-list is
    // enforced — the two must agree on what a path is.
    let content_type =
        mime_for_path(&path).unwrap_or_else(|| "application/octet-stream".to_owned());
    Ok(ApiResponse::file(bytes, content_type))
}

/// Store an upload's bytes behind a row's `File` field (§4).
///
/// The table's `min_role_write` was enforced as the endpoint's auth. The bytes
/// land in the **field's** store and folder — the caller names only a filename,
/// one path segment by route construction — and the field's MIME restrictions
/// are applied here, server-side: a client-side accept filter is a convenience,
/// not a control. The row is updated to reference the stored path, through the
/// same `update_row` any JSON write takes (so the field's rules are enforced
/// twice, harmlessly).
///
/// The caller travels with it: on an RLS table it is the authority the
/// pre-existence check and the field update both run under, so a caller cannot
/// upload into a row they may not write; on any table it is who the update event
/// reports as its cause.
#[allow(clippy::too_many_arguments)]
async fn upload_ctx(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    filename: &str,
    data: Option<bytes::Bytes>,
    role: u8,
    context: &CallerContext,
) -> Result<ApiResponse> {
    upload_inner(cat, table, field, id, filename, data, role, Some(context)).await
}

#[allow(clippy::too_many_arguments)]
async fn upload_inner(
    cat: &Catalog,
    table: &Table,
    field: &str,
    id: &str,
    filename: &str,
    data: Option<bytes::Bytes>,
    role: u8,
    context: Option<&CallerContext>,
) -> Result<ApiResponse> {
    let (store_name, folder, mime_allow) = file_field(table, field)?;
    let Some(data) = data else {
        return Err(Error::invalid(
            "expected the request body to be the file's bytes, sent with its own \
             content type (not application/json)",
        ));
    };

    let path = upload_path(folder, filename);
    validate_file_path(&path, folder, mime_allow).map_err(|e| rows::field_error(field, e))?;

    let store = cat.require_file_store(store_name)?;
    let floor = store_floor(cat, store_name).await?;
    // Writing into a restricted place is as governed as reading from one.
    check_access(store.as_ref(), floor, &path, role).await?;

    // The row must exist (and be writable by the caller) before the bytes land:
    // failing afterwards would leave an orphaned file no row references.
    rows::read_field_ctx(cat, table, field, id, context).await?;
    store.write(&path, data).await?;
    let updated =
        rows::update_row_guarded(cat, table, id, &json!({ field: path }), None, context).await?;
    Ok(ApiResponse::with_status(201, updated))
}

/// The `File` kind parameters of `field` on `table`: its store name, folder and
/// MIME allow-list. A field that is not (or is no longer) a `File` is a
/// not-found — the endpoint's own existence is what claimed otherwise.
fn file_field<'t>(
    table: &'t Table,
    field: &str,
) -> Result<(&'t str, Option<&'t str>, &'t [String])> {
    let found = table
        .field(field)
        .ok_or_else(|| Error::not_found(format!("`{}` has no field `{field}`", table.name)))?;
    match &found.kind {
        DataFieldKind::File {
            store,
            folder,
            mime_allow,
        } => Ok((store.0.as_str(), folder.as_deref(), mime_allow.as_slice())),
        _ => Err(Error::not_found(format!(
            "`{}.{field}` is not a File field",
            table.name
        ))),
    }
}

/// The store-wide access floor from the store's stored definition, `None` for a
/// store with no definition row (an ephemeral `--file-store`) — the same answer
/// the admin file endpoints resolve.
async fn store_floor(cat: &Catalog, store: &str) -> Result<Option<u8>> {
    Ok(load_file_store_by_name(cat, store)
        .await?
        .and_then(|def| def.min_role))
}

/// Captured path parameters.
type Params = HashMap<String, String>;

#[async_trait]
impl ApiProvider for RestProvider {
    fn name(&self) -> &str {
        REST_PROVIDER
    }

    fn mount(&self) -> String {
        self.mount.clone()
    }

    fn endpoints(&self) -> &EndpointSet {
        &self.endpoints
    }

    async fn handle(
        &self,
        req: ApiRequest,
        cat: &Arc<Catalog>,
        user: Option<&User>,
    ) -> Result<ApiResponse> {
        let (endpoint, params) = match self.resolve(&req) {
            Ok(found) => found,
            Err(rejection) => return Ok(rejection),
        };

        // Authorization first, always: every API surface goes through the §7
        // layer, and nothing below this line runs until it passes.
        if let Some(rejection) = enforce_auth(&endpoint.auth, user) {
            return Ok(rejection);
        }

        match &endpoint.handler {
            HandlerRef::Named(_) if endpoint.name == LOGIN => self.login(&req.body, cat).await,
            HandlerRef::Named(_) if endpoint.name == LOGOUT => {
                Ok(ApiResponse::end_session(json!({ "ok": true })))
            }
            HandlerRef::Named(_) if endpoint.name == WHOAMI => Ok(ApiResponse::ok(
                // `LoggedIn` is enforced above, so a caller is present here.
                user.map_or(Json::Null, user_summary_json),
            )),
            HandlerRef::Named(_) => match self.routes.get(&endpoint.name) {
                Some(route) => self.run(route, &params, &req, cat, user).await,
                None => match self.trigger_routes.get(&endpoint.name) {
                    Some(trigger) => self.run_trigger(trigger, &req, cat, user).await,
                    // A named handler with no projected route of either kind: the
                    // set was extended with a route this provider cannot run.
                    None => Ok(ApiResponse::error(
                        501,
                        format!("endpoint `{}` has no implementation", endpoint.name),
                    )),
                },
            },
            // Custom routes are carried by the model but not executable in the
            // MVP (design §13.4; TODO Phase 9).
            HandlerRef::GuestCode { language, .. } => Ok(ApiResponse::error(
                501,
                format!("custom {language} routes are not implemented yet"),
            )),
            HandlerRef::Sql(_) => Ok(ApiResponse::error(
                501,
                "custom SQL routes are not implemented yet",
            )),
        }
    }
}

/// Check a caller against an [`AuthRequirement`], returning a rejection when it
/// does not pass. Mirrors the server's own dispatch check, in the provider's
/// JSON vocabulary.
fn enforce_auth(auth: &AuthRequirement, user: Option<&User>) -> Option<ApiResponse> {
    let unauthenticated = || ApiResponse::error(401, "authentication required");
    match auth {
        AuthRequirement::Public => None,
        AuthRequirement::LoggedIn => user.is_none().then(unauthenticated),
        AuthRequirement::MinRole(min) => match user {
            None => Some(unauthenticated()),
            Some(u) if u.meets_role(*min) => None,
            Some(_) => Some(ApiResponse::error(403, "insufficient privilege")),
        },
    }
}

/// A `PathSpec` rooted at the provider's mount.
fn path_at(mount: &str) -> PathSpec {
    PathSpec::root().lit(mount)
}

/// Normalise a mount to a single leading slash and no trailing slash.
fn normalize_mount(raw: &str) -> String {
    let trimmed = raw.trim_matches('/');
    if trimmed.is_empty() {
        "/".to_owned()
    } else {
        format!("/{trimmed}")
    }
}

/// The endpoint (and generated client method) name for an operation on a table:
/// `list` + `blog_posts` → `listBlogPosts`. Table names are unique, so these are
/// unique too; the result is a valid TypeScript identifier as long as the table
/// name is alphanumeric-ish, which the catalog's own naming already requires.
///
/// Public because generated code has to call these methods by name: `sc-app`'s
/// React scaffold writes hooks that invoke `listTasks`/`createTasks`/…, and
/// recomputing the convention there would be a second copy of it, free to drift
/// from the endpoints the client is actually generated with.
pub fn op_name(op: &str, table: &str) -> String {
    let mut out = String::from(op);
    for word in table
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
    {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_catalog::{AccessRules, DataField, DbId, FileStoreId, TableId, TableSource};
    use sc_types::{BasicType, TypeRef};

    /// A table named `name` with an `id` primary key and a `title` text column.
    fn table(name: &str, access: AccessRules) -> Table {
        Table {
            id: TableId(name.to_owned()),
            name: name.to_owned(),
            database: DbId::primary(),
            source: TableSource::Database,
            fields: vec![
                DataField::plain("id", TypeRef::Basic(BasicType::Int)).primary_key(),
                DataField::plain("title", TypeRef::Basic(BasicType::Text)),
            ],
            primary_key: vec!["id".to_owned()],
            label: name.to_owned(),
            description: String::new(),
            access,
            attributes: Default::default(),
            overlay: None,
            ownership: None,
            ownership_error: None,
            rls_enabled: false,
        }
    }

    /// `table(name, access)` with a `cover` column configured as a `File` field
    /// into store `uploads`, folder `covers`.
    fn table_with_file_field(name: &str, access: AccessRules) -> Table {
        let mut t = table(name, access);
        let mut cover = DataField::plain("cover", TypeRef::Basic(BasicType::Text));
        cover.kind = DataFieldKind::File {
            store: FileStoreId("uploads".to_owned()),
            folder: Some("covers".to_owned()),
            mime_allow: vec!["image/png".to_owned()],
        };
        t.fields.push(cover);
        t
    }

    /// A table with no primary key at all.
    fn keyless(name: &str) -> Table {
        let mut t = table(name, AccessRules::default());
        t.primary_key.clear();
        t.fields = vec![DataField::plain("title", TypeRef::Basic(BasicType::Text))];
        t
    }

    /// A user with the given role. Roles run 1..=100, lower = more privileged.
    fn user(role: u8) -> User {
        User::new(uuid::Uuid::new_v4(), role).expect("role in range")
    }

    /// Every app's projection carries `login`, `logout`, and `whoami` on top of
    /// its per-table endpoints.
    const AUTH_ENDPOINTS: usize = 3;

    #[test]
    fn projects_four_rest_endpoints_per_table() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert_eq!(p.name(), "rest");
        assert_eq!(p.mount(), "/api");
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4);

        // The table is a literal segment — the app's own tables are its contract.
        let list = p.endpoints().find("listPosts").unwrap();
        assert_eq!(list.method, Method::Get);
        assert_eq!(list.path.pattern(), "/api/posts");

        let create = p.endpoints().find("createPosts").unwrap();
        assert_eq!(create.method, Method::Post);
        assert_eq!(create.path.pattern(), "/api/posts");

        // Row-addressed endpoints take the primary key as a typed parameter.
        let update = p.endpoints().find("updatePosts").unwrap();
        assert_eq!(update.method, Method::Put);
        assert_eq!(update.path.pattern(), "/api/posts/{id}");

        let delete = p.endpoints().find("deletePosts").unwrap();
        assert_eq!(delete.method, Method::Delete);
        assert_eq!(delete.path.pattern(), "/api/posts/{id}");
    }

    #[test]
    fn endpoint_names_are_camel_cased_typescript_identifiers() {
        assert_eq!(op_name("list", "blog_posts"), "listBlogPosts");
        assert_eq!(op_name("create", "posts"), "createPosts");
        // Non-alphanumeric separators are word boundaries, not literal output.
        assert_eq!(op_name("delete", "a-b"), "deleteAB");
    }

    #[test]
    fn table_access_rules_become_the_endpoints_auth() {
        let strict = AccessRules {
            min_role_read: 80,
            min_role_write: 1,
        };
        let p = RestProvider::project("/api", &[table("posts", strict)]);
        // Reads take min_role_read; writes take min_role_write (§7).
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().auth,
            AuthRequirement::MinRole(80)
        );
        for name in ["createPosts", "updatePosts", "deletePosts"] {
            assert_eq!(
                p.endpoints().find(name).unwrap().auth,
                AuthRequirement::MinRole(1),
                "{name}"
            );
        }
    }

    #[test]
    fn a_table_without_a_single_primary_key_gets_only_collection_endpoints() {
        // No key ⇒ no way to address a row, so no PUT/DELETE is promised.
        let p = RestProvider::project("/api", &[keyless("logs")]);
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 2);
        assert!(p.endpoints().find("listLogs").is_some());
        assert!(p.endpoints().find("createLogs").is_some());
        assert!(p.endpoints().find("updateLogs").is_none());
        assert!(p.endpoints().find("deleteLogs").is_none());
    }

    #[test]
    fn a_file_field_projects_download_and_upload_endpoints() {
        let access = AccessRules {
            min_role_read: 80,
            min_role_write: 40,
        };
        let p = RestProvider::project("/api", &[table_with_file_field("posts", access)]);
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4 + 2);

        // Addressed by table, row id and field name — never by raw store path.
        let download = p.endpoints().find("downloadPostsCover").unwrap();
        assert_eq!(download.method, Method::Get);
        assert_eq!(download.path.pattern(), "/api/posts/{id}/cover");
        assert!(download.binary_output, "a download serves bytes, not JSON");
        assert!(!download.binary_input);
        // Reads carry the table's read rule (the path-cumulative file rule is
        // enforced at request time, on top).
        assert_eq!(download.auth, AuthRequirement::MinRole(80));

        // The upload's filename is a path parameter: one segment by
        // construction, so a traversing destination cannot be expressed.
        let upload = p.endpoints().find("uploadPostsCover").unwrap();
        assert_eq!(upload.method, Method::Post);
        assert_eq!(upload.path.pattern(), "/api/posts/{id}/cover/{filename}");
        assert!(upload.binary_input, "an upload takes bytes, not JSON");
        // Uploads carry the table's write rule.
        assert_eq!(upload.auth, AuthRequirement::MinRole(40));
    }

    #[test]
    fn a_keyless_table_gets_no_file_endpoints() {
        // No row addressing ⇒ no way to say whose file it is.
        let mut t = keyless("logs");
        let mut attachment = DataField::plain("attachment", TypeRef::Basic(BasicType::Text));
        attachment.kind = DataFieldKind::File {
            store: FileStoreId("uploads".to_owned()),
            folder: None,
            mime_allow: vec![],
        };
        t.fields.push(attachment);
        let p = RestProvider::project("/api", &[t]);
        assert!(p.endpoints().find("downloadLogsAttachment").is_none());
        assert!(p.endpoints().find("uploadLogsAttachment").is_none());
    }

    #[test]
    fn the_generated_client_types_file_endpoints_as_binary() {
        let p = RestProvider::project(
            "/api",
            &[table_with_file_field("posts", AccessRules::default())],
        );
        let ts = crate::generate_client(p.endpoints());
        // A download resolves to a Blob; an upload takes what fetch can send raw.
        assert!(
            ts.contains("downloadPostsCover(id: number): Promise<Blob>"),
            "{ts}"
        );
        assert!(
            ts.contains("uploadPostsCover(id: number, filename: string, body: BodyInit)"),
            "{ts}"
        );
        // The upload body goes out unencoded, with no JSON content type.
        assert!(!ts.contains("export type UploadPostsCoverRequest"));
        assert!(ts.contains("return await res.blob();"));
    }

    #[test]
    fn only_the_declared_tables_are_projected() {
        // The app declared `posts`; `secrets` is not in its subset (§13.2), so
        // the projection has no route to it at all.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        assert!(p.endpoints().find("listSecrets").is_none());
        assert!(
            p.resolve(&ApiRequest::get("/api/secrets")).is_err(),
            "an undeclared table must not be routable"
        );
    }

    #[test]
    fn mount_is_normalised_and_reflected_in_paths() {
        let p = RestProvider::project("v1/api/", &[table("posts", AccessRules::default())]);
        assert_eq!(p.mount(), "/v1/api");
        assert_eq!(
            p.endpoints().find("listPosts").unwrap().path.pattern(),
            "/v1/api/posts"
        );
    }

    #[test]
    fn resolve_matches_method_and_path_and_captures_params() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let (ep, params) = p
            .resolve(&ApiRequest::new(Method::Put, "/api/posts/42"))
            .unwrap();
        assert_eq!(ep.name, "updatePosts");
        assert_eq!(params.get("id").unwrap(), "42");

        // A collection path captures nothing.
        let (ep, params) = p.resolve(&ApiRequest::get("/api/posts")).unwrap();
        assert_eq!(ep.name, "listPosts");
        assert!(params.is_empty());
    }

    #[test]
    fn unknown_path_is_404_and_wrong_method_is_405() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        let miss = p.resolve(&ApiRequest::get("/api/nope")).unwrap_err();
        assert_eq!(miss.status, 404);

        // `/api/posts` exists, but not for PATCH.
        let wrong = p
            .resolve(&ApiRequest::new(Method::Patch, "/api/posts"))
            .unwrap_err();
        assert_eq!(wrong.status, 405);
    }

    #[test]
    fn auth_is_enforced_before_anything_runs() {
        // Anonymous callers are rejected...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), None)
                .unwrap()
                .status,
            401
        );
        // ...under-privileged ones are forbidden...
        assert_eq!(
            enforce_auth(&AuthRequirement::MinRole(1), Some(&user(100)))
                .unwrap()
                .status,
            403
        );
        // ...and a sufficiently privileged one passes. Roles run 1..=100 with
        // lower = more privilege, so admin (1) clears a min_role of 80.
        assert!(enforce_auth(&AuthRequirement::MinRole(80), Some(&user(1))).is_none());
        assert!(enforce_auth(&AuthRequirement::Public, None).is_none());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, Some(&user(100))).is_none());
    }

    #[test]
    fn an_exposed_trigger_is_one_post_endpoint_carrying_its_own_role_floor() {
        use sc_action::{EventKind, Trigger};

        let open = Trigger::new("send_digest", EventKind::None, "fetch").min_role(80);
        // No `min_role`: nobody has decided who may call it.
        let unset = Trigger::new("purge_users", EventKind::None, "fetch");
        let p = RestProvider::project_with(
            "/api",
            &[table("posts", AccessRules::default())],
            &[open, unset],
        );
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4 + 2);

        let ep = p.endpoints().find("runSendDigest").unwrap();
        assert_eq!(ep.method, Method::Post);
        // Under `actions/`, so a trigger can never be confused with a table.
        assert_eq!(ep.path.pattern(), "/api/actions/send_digest");
        assert_eq!(ep.auth, AuthRequirement::MinRole(80));

        // The undecided one is admin-only, not public.
        assert_eq!(
            p.endpoints().find("runPurgeUsers").unwrap().auth,
            AuthRequirement::MinRole(sc_auth::ROLE_ADMIN)
        );

        // It routes, and it is typed into the app's client like anything else.
        let (ep, params) = p
            .resolve(&ApiRequest::new(Method::Post, "/api/actions/send_digest"))
            .unwrap();
        assert_eq!(ep.name, "runSendDigest");
        assert!(params.is_empty());
        assert!(crate::generate_client(p.endpoints()).contains("runSendDigest("));
    }

    #[test]
    fn a_trigger_the_app_does_not_expose_has_no_endpoint_at_all() {
        // The 404/403 distinction matters: a trigger nobody exposed is not a
        // permission problem to be escalated, it is not there.
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let miss = p
            .resolve(&ApiRequest::new(Method::Post, "/api/actions/send_digest"))
            .unwrap_err();
        assert_eq!(miss.status, 404);
    }

    #[test]
    fn custom_routes_are_projected_and_typed() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())])
            .with_custom_route(
                Endpoint::new("search", Method::Post, PathSpec::root().lit("api/search"))
                    .input(TypeSchema::json())
                    .output(TypeSchema::json())
                    .handler(HandlerRef::Sql("select 1".to_owned())),
            );
        // The custom route is part of the contract even though it is stubbed.
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4 + 1);
        let ep = p.endpoints().find("search").unwrap();
        assert!(matches!(ep.handler, HandlerRef::Sql(_)));

        // A generated client types it like any other endpoint.
        let ts = crate::generate_client(p.endpoints());
        assert!(ts.contains("search("));
        assert!(ts.contains("listPosts()"));
    }

    #[test]
    fn every_app_projects_its_own_auth_endpoints() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);

        // The app authenticates against its own API, not the admin's (§7.2).
        let login = p.endpoints().find("login").unwrap();
        assert_eq!(login.method, Method::Post);
        assert_eq!(login.path.pattern(), "/api/login");
        // Login is the one public endpoint: it is how a caller stops being
        // anonymous. Everything else needs a session.
        assert_eq!(login.auth, AuthRequirement::Public);

        assert_eq!(
            p.endpoints().find("logout").unwrap().auth,
            AuthRequirement::LoggedIn
        );
        assert_eq!(
            p.endpoints().find("whoami").unwrap().auth,
            AuthRequirement::LoggedIn
        );

        // Anonymous callers are turned away from everything but login.
        assert!(p.resolve(&ApiRequest::get("/api/whoami")).is_ok());
        assert!(enforce_auth(&AuthRequirement::LoggedIn, None).is_some());
        assert!(enforce_auth(&login.auth, None).is_none());
    }

    #[test]
    fn a_table_cannot_collide_with_the_auth_endpoints() {
        // A table actually named `login` still projects `listLogin` etc., because
        // table operations are always prefixed — so it cannot shadow the app's
        // own `login`.
        let p = RestProvider::project("/api", &[table("login", AccessRules::default())]);
        assert_eq!(p.endpoints().find("login").unwrap().method, Method::Post);
        assert!(p.endpoints().find("listLogin").is_some());
        assert_eq!(p.endpoints().len(), AUTH_ENDPOINTS + 4);
    }

    #[test]
    fn the_projection_generates_a_typed_client() {
        let p = RestProvider::project("/api", &[table("posts", AccessRules::default())]);
        let ts = crate::generate_client(p.endpoints());
        // Same generator as the admin API: an app's client is not special-cased.
        assert!(ts.contains("export interface ApiClient {"));
        assert!(ts.contains("listPosts(): Promise<ListPostsResponse>"));
        assert!(ts.contains("updatePosts(id: number"));
        assert!(ts.contains("/api/posts/${id}"));
    }
}
