//! The rule for **changing the schema**: creating and altering tables, adding,
//! altering and dropping fields, dropping tables, and writing a table's access
//! rules (technical design §3.3, §7.3, §13.1; TODO Phase 7).
//!
//! ## Why it is here and not in a handler
//!
//! Creating a table and creating a field used to exist only as closures inside
//! `sc-server`'s admin handlers: the default primary key, the `type` →
//! storage-type resolution, the DDL-then-overlay sequence, the calculated-field
//! check, the ownership validation and the RLS sync. That was fine while an
//! HTTP request was the only way to change a schema. It stopped being fine the
//! moment an **agent** could (§11.3's `manage_table_admin`): `sc-core-traits` is
//! layer 9 and cannot name `sc-server`, so a trait that re-implemented any of it
//! would be a second answer to "what does creating a field mean", and the two
//! would drift within a release.
//!
//! So the rule lives here, beside [`rows`](crate::rows) and for the same reason:
//! the admin API and an agent are two callers of one implementation, not two
//! implementations. The handlers are thin callers of this module exactly as the
//! REST provider is a thin caller of `rows`.
//!
//! ## A batch is one transaction and one reload
//!
//! [`apply`] takes an **ordered list** of [`Operation`]s, not one operation. A
//! schema is a set of *connected* tables — `matters` carries a key to `clients`,
//! `time_entries` a key to `matters` — so one-at-a-time would turn a twelve-table
//! schema into forty round trips, each able to fail halfway with no way back.
//! Instead:
//!
//! - **Every operation is resolved against a projected schema**
//!   ([`SchemaProjection`]), so a key pointing at a table created three
//!   operations earlier and a formula naming a field added two operations earlier
//!   both validate. The batch validates against the schema it *ends* with.
//! - **All the DDL goes through one [`Transaction`](sc_db::Transaction)**, so a
//!   refused operation rolls the whole batch back and a half-built schema is
//!   never a state anybody has to clean up by hand. The RLS policies join that
//!   transaction too (they are raw SQL through
//!   [`SchemaStep::Sql`](sc_catalog::SchemaStep)), emitted after the column
//!   changes they may reference.
//! - **The catalog reloads once**, at the end, rather than once per operation.
//! - **The `_sc_tables`/`_sc_fields` overlay rows are written after the commit**
//!   and cannot join that transaction — they go through the row layer, not the
//!   driver handle. So the partial-failure message `createField` always carried —
//!   the column exists, its settings did not save, edit or drop it and retry —
//!   becomes the batch's, naming the operation that half-applied.
//!
//! ## Grants
//!
//! [`Grants`] bounds what a batch may contain, checked **before** anything is
//! applied and refusing the batch **whole**. The admin API passes
//! [`Grants::all`]; an agent passes what its trait's four checkboxes say. They
//! are one struct rather than four entry points because the operations share a
//! batch: creating `matters` with a key to an existing `clients` is a create
//! *and* an edit, and a batch that half-applied for want of a grant is the state
//! the transaction exists to avoid.

use std::collections::{BTreeMap, BTreeSet};

use sc_catalog::{
    ATTR_OWNERSHIP_FORMULA, Attrs, Catalog, DataField, DataFieldKind, FIELD_META_TABLE, FieldId,
    FieldMeta, SchemaChanged, SchemaProjection, SchemaStep, Table, TableId, TableMeta,
    disable_rls_sql, enable_rls_sql, load_field_meta_by_field, load_table_meta_by_name,
    save_field_meta_row, save_table_meta_row,
};
use sc_db::SchemaChange;
use sc_error::{Error, Result};
use sc_types::{BasicType, RichTypeRef, TypeRef};

/// The SQL type of the default primary key a created table gets: a
/// database-generated identity, so rows can be inserted without supplying an id
/// while still allowing an explicit one.
///
/// Given **unasked**, to every table this module creates. A table with no
/// addressable primary key cannot be served by the row editor, cannot be
/// referenced by a `Key` field and is refused by half the agent traits, so
/// leaving the decision open would only produce tables that do not work.
pub const DEFAULT_PK_SQL_TYPE: &str = "bigint generated by default as identity";

/// The name of the default primary key column.
pub const DEFAULT_PK_NAME: &str = "id";

/// The users table, which is described and may gain a field but is never dropped
/// and never loses a built-in column.
const USERS_TABLE: &str = "users";
/// The role table, protected for the same reason.
const ROLES_TABLE: &str = "_sc_roles";

/// The columns of `users` and `_sc_roles` that the rest of the system requires
/// to exist. Dropping one is refused regardless of grant: authentication reads
/// them by name, so "it dropped and now nobody can log in" is not a state any
/// checkbox should be able to produce.
const PROTECTED_COLUMNS: &[(&str, &[&str])] = &[
    (USERS_TABLE, &["id", "email", "password_hash", "role"]),
    (ROLES_TABLE, &["id", "role", "name"]),
];

// --- what a batch may do ------------------------------------------------------

/// The four grants a batch is checked against (§11.3).
///
/// Four rather than one for the reason `insert_row`/`update_rows`/`delete_rows`
/// are three traits: each is a different thing to trust a caller with. Dropping
/// and access changes default **off**, and access changes sit above dropping —
/// a drop announces itself, a widened role floor does not.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Grants {
    /// May create tables and their fields.
    pub create: bool,
    /// May alter a table's label/description and add or alter its fields.
    pub edit: bool,
    /// May drop tables and fields.
    pub drop: bool,
    /// May write `min_role_read`, `min_role_write`, the ownership formula and
    /// the RLS flag.
    pub access_changes: bool,
}

/// The configuration key each grant is stored under, so the refusal can name the
/// checkbox that would allow the operation rather than describe it.
pub const GRANT_CREATE: &str = "allow_create";
/// See [`GRANT_CREATE`].
pub const GRANT_EDIT: &str = "allow_edit";
/// See [`GRANT_CREATE`].
pub const GRANT_DROP: &str = "allow_drop";
/// See [`GRANT_CREATE`].
pub const GRANT_ACCESS_CHANGES: &str = "allow_access_changes";

impl Grants {
    /// Everything permitted — what the admin API passes, because an admin
    /// reaching these endpoints has already been checked by
    /// [`AuthRequirement::admin`](crate::AuthRequirement).
    pub fn all() -> Grants {
        Grants {
            create: true,
            edit: true,
            drop: true,
            access_changes: true,
        }
    }

    /// Nothing permitted — the base an agent's checkboxes turn on.
    pub fn none() -> Grants {
        Grants {
            create: false,
            edit: false,
            drop: false,
            access_changes: false,
        }
    }

    fn check(&self, granted: bool, what: &str, key: &str) -> Result<()> {
        if granted {
            return Ok(());
        }
        Err(Error::invalid(format!(
            "not permitted to {what}; the whole batch was refused and nothing was applied. \
             Turn on `{key}` to allow it."
        )))
    }
}

/// How a batch is applied.
#[derive(Debug, Clone)]
pub struct ApplyOptions {
    /// What the caller may do.
    pub grants: Grants,
    /// Validate the whole batch and apply **none** of it. The same refusals, the
    /// same messages, no DDL and no overlay writes.
    pub dry_run: bool,
}

impl Default for ApplyOptions {
    fn default() -> ApplyOptions {
        ApplyOptions {
            grants: Grants::all(),
            dry_run: false,
        }
    }
}

// --- the operations -----------------------------------------------------------

/// A field to create, as a caller describes it.
///
/// `type_name` may be **empty for a `Key` field**, in which case the storage type
/// is taken from the target's primary key — so the pair cannot disagree, which
/// is the mistake a caller asked for both would eventually make.
#[derive(Debug, Clone)]
pub struct FieldSpec {
    /// The column name.
    pub name: String,
    /// A basic type name, a registered rich type's name, or empty for a `Key`.
    pub type_name: String,
    /// The human label; empty for none.
    pub label: String,
    /// The description; empty for none.
    pub description: String,
    /// `NOT NULL`.
    pub required: bool,
    /// A `UNIQUE` constraint.
    pub unique: bool,
    /// What the field references, if anything. A `Key` whose `target_field` is
    /// empty resolves to the target's primary key.
    pub kind: DataFieldKind,
    /// Rich-type attributes.
    pub attributes: Attrs,
}

impl Default for FieldSpec {
    fn default() -> FieldSpec {
        FieldSpec {
            name: String::new(),
            type_name: String::new(),
            label: String::new(),
            description: String::new(),
            required: false,
            unique: false,
            kind: DataFieldKind::Plain,
            attributes: Attrs::new(),
        }
    }
}

/// Settings on a table, each `None` meaning **leave it as it is**.
///
/// A deliberate divergence from `updateTable`'s whole-object contract (§13.1),
/// recorded as one: that endpoint takes every setting on purpose, because the
/// admin UI edits a table it has loaded and an omitted role could otherwise mean
/// either "leave it" or "reset it". A caller that has *not* loaded the table —
/// an agent — has no such object, and under the whole-object contract
/// `{op: alter_table, table: "clients", min_role_read: 40}` would blank the
/// ownership formula and turn RLS off. So here, omitted means unchanged, and the
/// handler that wants the whole-object contract passes every field as `Some`.
#[derive(Debug, Clone, Default)]
pub struct TableSettings {
    /// The human label.
    pub label: Option<String>,
    /// The description.
    pub description: Option<String>,
    /// Least-privileged role that may read rows.
    pub min_role_read: Option<u8>,
    /// Least-privileged role that may write rows.
    pub min_role_write: Option<u8>,
    /// The ownership formula source; `Some("")` clears it.
    pub ownership_formula: Option<String>,
    /// Whether the database enforces the formula with policies.
    pub rls_enabled: Option<bool>,
}

impl TableSettings {
    /// Whether anything here touches the access rules — the four settings behind
    /// [`Grants::access_changes`].
    pub fn touches_access(&self) -> bool {
        self.min_role_read.is_some()
            || self.min_role_write.is_some()
            || self.ownership_formula.is_some()
            || self.rls_enabled.is_some()
    }

    fn is_empty(&self) -> bool {
        self.label.is_none() && self.description.is_none() && !self.touches_access()
    }
}

/// Overlay-only settings on an existing field, each `None` meaning leave it.
///
/// There is no `required`, `unique` or storage type here for the reason
/// `updateField` has none (§3.3): retyping or re-constraining a column is a
/// migration, and a migration framework is out of scope.
#[derive(Debug, Clone, Default)]
pub struct FieldSettings {
    /// The human label.
    pub label: Option<String>,
    /// The description.
    pub description: Option<String>,
    /// The rich type's name; `Some("")` clears it back to the basic column type.
    pub type_name: Option<String>,
    /// What the field references.
    pub kind: Option<DataFieldKind>,
    /// Rich-type attributes.
    pub attributes: Option<Attrs>,
}

/// One schema operation.
#[derive(Debug, Clone)]
pub enum Operation {
    /// Create a table with an identity primary key and these fields.
    CreateTable {
        /// The new table's name.
        name: String,
        /// Its settings.
        settings: TableSettings,
        /// Its fields, beside the primary key it is given unasked.
        fields: Vec<FieldSpec>,
    },
    /// Change a table's settings, leaving what is not named.
    AlterTable {
        /// The table.
        table: String,
        /// What to change.
        settings: TableSettings,
    },
    /// Add a field to an existing table.
    AddField {
        /// The table.
        table: String,
        /// The field.
        field: FieldSpec,
    },
    /// Change an existing field's overlay settings.
    AlterField {
        /// The table.
        table: String,
        /// The field.
        field: String,
        /// What to change.
        settings: FieldSettings,
    },
    /// Drop a field and its overlay row.
    DropField {
        /// The table.
        table: String,
        /// The field.
        field: String,
    },
    /// Drop a table, its columns, its rows and its overlay rows.
    DropTable {
        /// The table.
        table: String,
    },
}

impl Operation {
    /// The `op` name this operation is spelled with on the wire, for messages
    /// that have to name the operation the caller wrote.
    pub fn op_name(&self) -> &'static str {
        match self {
            Operation::CreateTable { .. } => "create_table",
            Operation::AlterTable { .. } => "alter_table",
            Operation::AddField { .. } => "add_field",
            Operation::AlterField { .. } => "alter_field",
            Operation::DropField { .. } => "drop_field",
            Operation::DropTable { .. } => "drop_table",
        }
    }

    /// The table this operation is about.
    pub fn table(&self) -> &str {
        match self {
            Operation::CreateTable { name, .. } => name,
            Operation::AlterTable { table, .. }
            | Operation::AddField { table, .. }
            | Operation::AlterField { table, .. }
            | Operation::DropField { table, .. }
            | Operation::DropTable { table } => table,
        }
    }
}

/// What a batch did (or, for a dry run, would have done).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Applied {
    /// Whether nothing was actually written.
    pub dry_run: bool,
    /// Tables created, in order.
    pub tables_created: Vec<String>,
    /// Tables whose settings changed.
    pub tables_altered: Vec<String>,
    /// Tables dropped.
    pub tables_dropped: Vec<String>,
    /// Fields added, as `table.field`.
    pub fields_added: Vec<String>,
    /// Fields whose settings changed, as `table.field`.
    pub fields_altered: Vec<String>,
    /// Fields dropped, as `table.field`.
    pub fields_dropped: Vec<String>,
    /// Things the caller has to be told in words, because they are not visible
    /// in the schema afterwards — chiefly that a table stopped enforcing RLS.
    pub notes: Vec<String>,
}

// --- applying -----------------------------------------------------------------

/// Apply an ordered batch of schema operations.
///
/// Either every operation is applied or none is. See the module docs for the
/// shape; the short version is: validate the whole batch against the schema it
/// would leave behind, then one transaction for the DDL, then the overlay rows,
/// then one reload, then one notification per changed table.
pub async fn apply(
    catalog: &Catalog,
    operations: &[Operation],
    options: &ApplyOptions,
) -> Result<Applied> {
    if operations.is_empty() {
        return Err(Error::invalid("a schema edit needs at least one operation"));
    }
    let mut plan = Plan::new(catalog).await?;
    for (index, op) in operations.iter().enumerate() {
        plan.push(catalog, index, op, &options.grants)
            .await
            .map_err(|e| at(index, op, e))?;
    }
    // Deferred to here on purpose: an ownership formula naming a field the batch
    // adds, and a calculated field reading one, must both validate against the
    // schema the batch *ends* with (§7.3, Phase 8).
    plan.validate_deferred(catalog)?;
    let steps = plan.steps(catalog)?;

    if options.dry_run {
        let mut applied = plan.applied;
        applied.dry_run = true;
        applied
            .notes
            .push("dry run: nothing was applied".to_owned());
        return Ok(applied);
    }

    catalog.apply_schema_batch(&steps).await?;

    // Past the commit. The columns are there; the overlay rows are not yet, and
    // cannot join the transaction that made them — so a failure here is reported
    // as exactly what it is rather than as a failure of the batch.
    for write in &plan.metas {
        write.run(catalog).await.map_err(|e| {
            Error::invalid(format!(
                "the schema changes were applied, but saving the settings for \
                 operation {} ({}) failed: {e}. The columns exist as plain columns; \
                 edit or drop them and retry.",
                write.index, write.op_name
            ))
        })?;
    }

    catalog.reload().await?;

    let mut applied = plan.applied;
    for change in &plan.changes {
        if let Err(e) = catalog.notify_schema_changed(change) {
            applied.notes.push(format!(
                "the schema changed, but re-projecting `{}` for the running \
                 applications failed: {e}",
                change.table()
            ));
        }
    }
    Ok(applied)
}

/// Forget a table's stored settings: delete its `_sc_tables` row, drop the
/// row-level-security policies if the row was what turned them on, and notify
/// the observers.
///
/// **Not an [`Operation`]**, because it is not a change to the schema: the table,
/// its columns and every row in it are untouched, and this is also how an
/// *orphan* row — one whose table is gone (§1.1) — is cleaned up, which means it
/// must work when there is no table to resolve. It lives here rather than in the
/// handler for the half that *is* this module's: "was RLS on? then drop the
/// policies", which is the same rule `alter_table` applies when it turns the flag
/// off. A `FORCE`'d table whose policies outlived the settings that generated
/// them would deny everyone.
pub async fn forget_table_settings(catalog: &Catalog, table: &str) -> Result<bool> {
    let was_rls = catalog.get(table)?.is_some_and(|t| t.rls_enabled);
    let Some(meta) = load_table_meta_by_name(catalog, table).await? else {
        return Ok(false);
    };
    if !sc_catalog::delete_table_meta(catalog, meta.id).await? {
        return Ok(false);
    }
    if was_rls {
        sc_catalog::disable_rls(catalog, table).await?;
    }
    // Forgetting reverts the table to the admin-only default, and a mounted app
    // exposing it must pick that up now rather than at the next restart.
    catalog.notify_schema_changed(&SchemaChanged::TableChanged(table.to_owned()))?;
    Ok(true)
}

/// Prefix an operation's error with which operation it was, by index and by the
/// `op` name the caller wrote. A model that is told "table `clients` not found"
/// with a twelve-operation batch cannot act; told "operation 4 (add_field on
/// clients)", it can.
fn at(index: usize, op: &Operation, e: Error) -> Error {
    let message = format!(
        "operation {index} ({} on `{}`): {e}",
        op.op_name(),
        op.table()
    );
    match e.repr() {
        sc_error::Repr::NotFound(_) => Error::not_found(message),
        _ => Error::invalid(message),
    }
}

/// One pending overlay write, with the operation that asked for it.
struct MetaWrite {
    index: usize,
    op_name: &'static str,
    what: MetaOp,
}

enum MetaOp {
    SaveTable(Box<TableMeta>),
    ForgetTable(String),
    SaveField(Box<FieldMeta>),
    ForgetField(String, String),
}

impl MetaWrite {
    async fn run(&self, catalog: &Catalog) -> Result<()> {
        match &self.what {
            MetaOp::SaveTable(meta) => save_table_meta_row(catalog, meta).await,
            MetaOp::ForgetTable(name) => catalog.forget_table_meta(name).await,
            MetaOp::SaveField(meta) => save_field_meta_row(catalog, meta).await,
            MetaOp::ForgetField(table, field) => catalog.forget_field_meta(table, field).await,
        }
    }
}

/// The batch under construction: the schema as it will be, the DDL that gets it
/// there, the overlay rows that follow, and what to report.
struct Plan {
    projection: SchemaProjection,
    ddl: Vec<SchemaChange>,
    metas: Vec<MetaWrite>,
    /// The pending `_sc_tables` row per table, so two `alter_table`s on one table
    /// update one row rather than racing to create two.
    table_metas: BTreeMap<String, TableMeta>,
    /// Whether each table was enforcing RLS *before* the batch — what decides,
    /// after it, whether policies are created, recreated or dropped.
    was_rls: BTreeMap<String, bool>,
    /// Tables whose policies must be re-emitted or dropped at the end.
    rls_dirty: BTreeSet<String>,
    /// Tables dropped by this batch, so nothing is emitted for them afterwards.
    dropped: BTreeSet<String>,
    /// Calculated-field expressions to validate against the final schema, as
    /// `(table, field, expression)`.
    deferred_calc: Vec<(String, String, String)>,
    changes: Vec<SchemaChanged>,
    applied: Applied,
}

impl Plan {
    async fn new(catalog: &Catalog) -> Result<Plan> {
        let projection = SchemaProjection::live(catalog)?;
        let was_rls = projection
            .tables()
            .iter()
            .map(|t| (t.name.clone(), t.rls_enabled))
            .collect();
        Ok(Plan {
            projection,
            was_rls,
            ddl: Vec::new(),
            metas: Vec::new(),
            table_metas: BTreeMap::new(),
            rls_dirty: BTreeSet::new(),
            dropped: BTreeSet::new(),
            deferred_calc: Vec::new(),
            changes: Vec::new(),
            applied: Applied::default(),
        })
    }

    async fn push(
        &mut self,
        catalog: &Catalog,
        index: usize,
        op: &Operation,
        grants: &Grants,
    ) -> Result<()> {
        match op {
            Operation::CreateTable {
                name,
                settings,
                fields,
            } => {
                grants.check(grants.create, "create a table", GRANT_CREATE)?;
                self.create_table(catalog, index, op, name, settings, fields)
                    .await
            }
            Operation::AlterTable { table, settings } => {
                grants.check(grants.edit, "change a table's settings", GRANT_EDIT)?;
                if settings.touches_access() {
                    grants.check(
                        grants.access_changes,
                        "change a table's access rules",
                        GRANT_ACCESS_CHANGES,
                    )?;
                }
                self.alter_table(catalog, index, op, table, settings).await
            }
            Operation::AddField { table, field } => {
                grants.check(grants.edit, "add a field", GRANT_EDIT)?;
                self.add_field(catalog, index, op, table, field).await
            }
            Operation::AlterField {
                table,
                field,
                settings,
            } => {
                grants.check(grants.edit, "change a field's settings", GRANT_EDIT)?;
                self.alter_field(catalog, index, op, table, field, settings)
                    .await
            }
            Operation::DropField { table, field } => {
                grants.check(grants.drop, "drop a field", GRANT_DROP)?;
                self.drop_field(index, op, table, field)
            }
            Operation::DropTable { table } => {
                grants.check(grants.drop, "drop a table", GRANT_DROP)?;
                self.drop_table(index, op, table)
            }
        }
    }

    // --- create ---------------------------------------------------------------

    async fn create_table(
        &mut self,
        catalog: &Catalog,
        index: usize,
        op: &Operation,
        name: &str,
        settings: &TableSettings,
        fields: &[FieldSpec],
    ) -> Result<()> {
        let name = name.trim();
        check_identifier(name, "table")?;
        if name.starts_with("_sc_") {
            return Err(Error::invalid(format!(
                "`{name}` is a system table name; the `_sc_` prefix is reserved"
            )));
        }
        if self.projection.get(name).is_some() {
            return Err(Error::invalid(format!("table `{name}` already exists")));
        }

        // The identity primary key, unasked. Every table this module makes is
        // addressable, which is what the row editor, a `Key` field pointing at
        // it and half the agent traits all require.
        let pk = DataField::plain(DEFAULT_PK_NAME, TypeRef::from_sql_type(DEFAULT_PK_SQL_TYPE))
            .required()
            .primary_key();
        let mut table = Table::projected(
            sc_catalog::DbId::primary(),
            name,
            vec![pk],
            vec![DEFAULT_PK_NAME.to_owned()],
        );
        // In the projection before the fields resolve, so a self-referencing key
        // (`employees.manager` → `employees`) finds its own primary key.
        self.projection.insert(table.clone());

        let mut columns = vec![
            DataField::plain(DEFAULT_PK_NAME, TypeRef::from_sql_type(DEFAULT_PK_SQL_TYPE))
                .required()
                .primary_key(),
        ];
        let mut pending_meta: Vec<FieldMeta> = Vec::new();
        for spec in fields {
            if spec.name.trim() == DEFAULT_PK_NAME {
                return Err(Error::invalid(format!(
                    "field `{DEFAULT_PK_NAME}` is the primary key every created table \
                     is given; do not declare it"
                )));
            }
            let resolved = self.resolve_field(name, spec)?;
            if table.field(&resolved.field.base.name).is_some() {
                return Err(Error::invalid(format!(
                    "table `{name}` is declared with two fields called `{}`",
                    resolved.field.base.name
                )));
            }
            if !resolved.field.is_calc() {
                columns.push(resolved.field.clone());
            }
            if let Some(expression) = resolved.field.calc_expression() {
                self.deferred_calc.push((
                    name.to_owned(),
                    resolved.field.base.name.clone(),
                    expression.to_owned(),
                ));
            }
            table.fields.push(resolved.field);
            if let Some(meta) = resolved.meta {
                pending_meta.push(meta);
            }
            self.projection.insert(table.clone());
        }

        self.ddl.push(SchemaChange::CreateTable {
            name: name.to_owned(),
            columns: columns.iter().map(DataField::to_column_def).collect(),
            primary_key: vec![DEFAULT_PK_NAME.to_owned()],
            unlogged: false,
        });
        for meta in pending_meta {
            self.metas.push(MetaWrite {
                index,
                op_name: op.op_name(),
                what: MetaOp::SaveField(Box::new(meta)),
            });
        }
        // A brand-new table has no stored overlay to read, so the settings start
        // from a fresh row rather than being loaded.
        if !settings.is_empty() {
            self.table_metas
                .insert(name.to_owned(), TableMeta::new(name));
            self.write_settings(catalog, index, op, name, settings)
                .await?;
        } else {
            self.projection.insert(table);
        }
        self.applied.tables_created.push(name.to_owned());
        self.changes
            .push(SchemaChanged::TableCreated(name.to_owned()));
        Ok(())
    }

    // --- alter table ----------------------------------------------------------

    async fn alter_table(
        &mut self,
        catalog: &Catalog,
        index: usize,
        op: &Operation,
        table: &str,
        settings: &TableSettings,
    ) -> Result<()> {
        self.require_editable(table)?;
        if settings.is_empty() {
            return Err(Error::invalid(
                "nothing to change; name at least one setting",
            ));
        }
        self.load_table_meta(catalog, table).await?;
        self.write_settings(catalog, index, op, table, settings)
            .await?;
        if !self.applied.tables_altered.iter().any(|t| t == table) {
            self.applied.tables_altered.push(table.to_owned());
        }
        self.note_changed(table);
        Ok(())
    }

    /// Seed the pending overlay row for `table` from the stored one, so an edit
    /// updates the existing row and an omitted setting keeps the value that row
    /// already carries.
    async fn load_table_meta(&mut self, catalog: &Catalog, table: &str) -> Result<()> {
        if self.table_metas.contains_key(table) {
            return Ok(());
        }
        let stored = load_table_meta_by_name(catalog, table).await?;
        self.table_metas.insert(
            table.to_owned(),
            stored.unwrap_or_else(|| TableMeta::new(table)),
        );
        Ok(())
    }

    async fn write_settings(
        &mut self,
        _catalog: &Catalog,
        index: usize,
        op: &Operation,
        table: &str,
        settings: &TableSettings,
    ) -> Result<()> {
        let meta = self
            .table_metas
            .get_mut(table)
            .ok_or_else(|| Error::msg("settings row missing from the plan"))?;
        if let Some(label) = &settings.label {
            meta.label = label.trim().to_owned();
        }
        if let Some(description) = &settings.description {
            meta.description = description.trim().to_owned();
        }
        let mut access = meta.access.clone();
        if let Some(role) = settings.min_role_read {
            access.min_role_read = check_role(role, "min_role_read")?;
        }
        if let Some(role) = settings.min_role_write {
            access.min_role_write = check_role(role, "min_role_write")?;
        }
        let access_moved = access != meta.access;
        meta.access = access;
        if let Some(formula) = &settings.ownership_formula {
            meta.set_ownership_formula(Some(formula.trim()));
        }
        if let Some(enabled) = settings.rls_enabled {
            meta.set_rls_enabled(enabled);
        }
        let meta = meta.clone();

        // Mirror the row onto the projection exactly as `Catalog::reload` will,
        // so the rest of the batch sees the table as it will be.
        let mut projected =
            self.projection.get(table).cloned().ok_or_else(|| {
                Error::not_found(format!("table `{table}` is not in the catalog"))
            })?;
        projected.apply_overlay(&meta);
        self.projection.insert(projected);

        if settings.touches_access() || access_moved {
            self.rls_dirty.insert(table.to_owned());
        }
        self.metas.push(MetaWrite {
            index,
            op_name: op.op_name(),
            what: MetaOp::SaveTable(Box::new(meta)),
        });
        Ok(())
    }

    // --- fields ---------------------------------------------------------------

    async fn add_field(
        &mut self,
        catalog: &Catalog,
        index: usize,
        op: &Operation,
        table: &str,
        spec: &FieldSpec,
    ) -> Result<()> {
        self.require_editable(table)?;
        let resolved = self.resolve_field(table, spec)?;
        let name = resolved.field.base.name.clone();
        let projected = self
            .projection
            .get(table)
            .ok_or_else(|| Error::not_found(format!("table `{table}` is not in the catalog")))?;
        if projected.field(&name).is_some() {
            return Err(Error::invalid(format!(
                "table `{table}` already has a field `{name}`"
            )));
        }
        if let Some(expression) = resolved.field.calc_expression() {
            self.deferred_calc
                .push((table.to_owned(), name.clone(), expression.to_owned()));
        } else {
            self.ddl.push(SchemaChange::AddColumn {
                table: table.to_owned(),
                column: resolved.field.to_column_def(),
            });
        }
        let mut projected = projected.clone();
        projected.fields.push(resolved.field);
        self.projection.insert(projected);

        if let Some(mut meta) = resolved.meta {
            // Reuse the stored row when one is somehow already there (a column
            // dropped and re-added inside one batch), so the save updates rather
            // than colliding with the one-row-per-field rule.
            if let Some(existing) = stored_field_meta(catalog, table, &name).await? {
                meta = meta.id(existing.id);
            }
            self.metas.push(MetaWrite {
                index,
                op_name: op.op_name(),
                what: MetaOp::SaveField(Box::new(meta)),
            });
        }
        self.applied.fields_added.push(format!("{table}.{name}"));
        self.note_changed(table);
        Ok(())
    }

    async fn alter_field(
        &mut self,
        catalog: &Catalog,
        index: usize,
        op: &Operation,
        table: &str,
        field: &str,
        settings: &FieldSettings,
    ) -> Result<()> {
        self.require_editable(table)?;
        let projected = self
            .projection
            .get(table)
            .ok_or_else(|| Error::not_found(format!("table `{table}` is not in the catalog")))?
            .clone();
        let existing = projected
            .field(field)
            .ok_or_else(|| {
                Error::not_found(format!(
                    "table `{table}` has no field `{field}`; it has {}",
                    field_list(&projected)
                ))
            })?
            .clone();

        let stored = stored_field_meta(catalog, table, field).await?;
        let mut meta = FieldMeta::new(table, field);
        if let Some(row) = &stored {
            meta = meta.id(row.id);
            meta.label.clone_from(&row.label);
            meta.description.clone_from(&row.description);
            meta.type_name.clone_from(&row.type_name);
            meta.kind = row.kind.clone();
            meta.attributes = row.attributes.clone();
        } else {
            meta.kind = existing.kind.clone();
        }
        if let Some(label) = &settings.label {
            meta.label = label.trim().to_owned();
        }
        if let Some(description) = &settings.description {
            meta.description = description.trim().to_owned();
        }
        if let Some(type_name) = &settings.type_name {
            let type_name = type_name.trim();
            meta.type_name = if type_name.is_empty() {
                None
            } else {
                // An unknown type name is refused here; whether a known rich type
                // fits the column is the merge's to report (§3.2).
                //
                // Only a *rich* name is recorded, which is what `resolve_field_type`
                // returns and what `resolve_field` stores when the field is created.
                // A caller that names the column's basic type — `text` for a field
                // that reads back as `text`, which is what an editor round-tripping a
                // field sends — is saying "no rich type", not "the rich type `text`":
                // recording the latter would leave an overlay naming a rich type that
                // is not registered, and the merge would report the field as broken.
                resolve_field_type(type_name)?.1
            };
        }
        if let Some(kind) = &settings.kind {
            meta.kind = self.resolve_kind(table, field, kind)?;
        }
        if let Some(attributes) = &settings.attributes {
            meta.attributes = attributes.clone();
        }
        if let DataFieldKind::Calc { expression } = &meta.kind {
            self.deferred_calc
                .push((table.to_owned(), field.to_owned(), expression.clone()));
        }

        // Mirror onto the projection **in place**, so a later operation reads the
        // field as it will be — and reads the table's fields in the order
        // introspection will hand them back, which is the order every message in
        // this module lists them in.
        let mut projected = projected;
        if let Some(slot) = projected.fields.iter_mut().find(|f| f.base.name == field) {
            slot.kind = meta.kind.clone();
            if !meta.label.is_empty() {
                slot.base.label.clone_from(&meta.label);
            }
        }
        self.projection.insert(projected);

        self.metas.push(MetaWrite {
            index,
            op_name: op.op_name(),
            what: MetaOp::SaveField(Box::new(meta)),
        });
        self.applied.fields_altered.push(format!("{table}.{field}"));
        self.note_changed(table);
        Ok(())
    }

    fn drop_field(&mut self, index: usize, op: &Operation, table: &str, field: &str) -> Result<()> {
        self.require_editable(table)?;
        let projected = self
            .projection
            .get(table)
            .ok_or_else(|| Error::not_found(format!("table `{table}` is not in the catalog")))?
            .clone();
        let existing = projected.field(field).ok_or_else(|| {
            Error::not_found(format!(
                "table `{table}` has no field `{field}`; it has {}",
                field_list(&projected)
            ))
        })?;

        // Everything the database would otherwise refuse with an error nobody can
        // act on, refused here by name and before any DDL.
        if projected.primary_key.iter().any(|k| k == field) {
            return Err(Error::invalid(format!(
                "`{table}.{field}` is the primary key; a table without one cannot be \
                 addressed, so it cannot be dropped. Drop the table instead."
            )));
        }
        if let Some((_, columns)) = PROTECTED_COLUMNS.iter().find(|(t, _)| *t == table)
            && columns.contains(&field)
        {
            return Err(Error::invalid(format!(
                "`{table}.{field}` is a built-in column of `{table}` and is never dropped"
            )));
        }
        let readers = calc_readers(&projected, field);
        if !readers.is_empty() {
            return Err(Error::invalid(format!(
                "`{table}.{field}` is read by the calculated field(s) {}; \
                 drop or change them first",
                quoted(&readers)
            )));
        }
        let referencing = keys_targeting(&self.projection, table, field);
        if !referencing.is_empty() {
            return Err(Error::invalid(format!(
                "`{table}.{field}` is referenced by {}; drop those fields first",
                quoted(&referencing)
            )));
        }
        if projected
            .ownership
            .as_ref()
            .is_some_and(|f| f.source().contains(field))
        {
            // Not a parse of the formula — a name check, because the formula is
            // re-validated at the end of the batch anyway and this message is the
            // one that says which table's rule is in the way.
            self.rls_dirty.insert(table.to_owned());
        }

        if !existing.is_calc() {
            self.ddl.push(SchemaChange::DropColumn {
                table: table.to_owned(),
                column: field.to_owned(),
                if_exists: false,
            });
        }
        let mut projected = projected;
        projected.fields.retain(|f| f.base.name != field);
        self.projection.insert(projected);

        self.metas.push(MetaWrite {
            index,
            op_name: op.op_name(),
            what: MetaOp::ForgetField(table.to_owned(), field.to_owned()),
        });
        self.applied.fields_dropped.push(format!("{table}.{field}"));
        self.note_changed(table);
        Ok(())
    }

    fn drop_table(&mut self, index: usize, op: &Operation, table: &str) -> Result<()> {
        self.require_editable(table)?;
        if table == USERS_TABLE || table == ROLES_TABLE {
            return Err(Error::invalid(format!(
                "`{table}` is a built-in table and is never dropped"
            )));
        }
        let referencing = self.projection.referencing_fields(table);
        if !referencing.is_empty() {
            let names: Vec<String> = referencing
                .iter()
                .map(|(t, f)| format!("{t}.{f}"))
                .collect();
            return Err(Error::invalid(format!(
                "table `{table}` is referenced by {}; drop those fields (or their \
                 tables) first",
                quoted(&names)
            )));
        }
        self.ddl.push(SchemaChange::DropTable {
            name: table.to_owned(),
            if_exists: false,
        });
        self.projection.remove(table);
        self.dropped.insert(table.to_owned());
        self.rls_dirty.remove(table);
        self.table_metas.remove(table);
        self.metas.push(MetaWrite {
            index,
            op_name: op.op_name(),
            what: MetaOp::ForgetTable(table.to_owned()),
        });
        self.applied.tables_dropped.push(table.to_owned());
        self.changes
            .push(SchemaChanged::TableDropped(table.to_owned()));
        Ok(())
    }

    // --- shared checks --------------------------------------------------------

    /// The table exists, is not a system table, and is not one this batch has
    /// already dropped.
    fn require_editable(&self, table: &str) -> Result<()> {
        if table.starts_with("_sc_") {
            return Err(Error::invalid(format!(
                "`{table}` is a system table; its schema is not editable"
            )));
        }
        if self.dropped.contains(table) {
            return Err(Error::invalid(format!(
                "table `{table}` was dropped earlier in this batch"
            )));
        }
        if self.projection.get(table).is_none() {
            return Err(Error::not_found(format!(
                "table `{table}` is not in the catalog"
            )));
        }
        Ok(())
    }

    fn note_changed(&mut self, table: &str) {
        let change = SchemaChanged::TableChanged(table.to_owned());
        if !self.changes.contains(&change) {
            self.changes.push(change);
        }
    }

    /// Resolve a caller's field description into the column to create and the
    /// overlay row that describes it, against the projected schema.
    fn resolve_field(&self, table: &str, spec: &FieldSpec) -> Result<ResolvedField> {
        let name = spec.name.trim();
        check_identifier(name, "field")?;
        let kind = self.resolve_kind(table, name, &spec.kind)?;

        // `sql_type` is derived from `type`, never asked for — a rich type sits on
        // its own storage type, and a Key sits on its target's.
        let type_name = spec.type_name.trim();
        let (storage, rich_name) = if type_name.is_empty() {
            match &kind {
                DataFieldKind::Key {
                    target_table,
                    target_field,
                    ..
                } => (self.key_storage_type(target_table, target_field)?, None),
                DataFieldKind::Calc { .. } => (TypeRef::Basic(BasicType::Text), None),
                _ => {
                    return Err(Error::invalid(format!(
                        "field `{name}` needs a type; it is only optional for a \
                         reference, whose type comes from the table it points at"
                    )));
                }
            }
        } else {
            resolve_field_type(type_name)?
        };

        let mut field = DataField::plain(name, storage);
        field.required = spec.required;
        field.unique = spec.unique;
        field.kind = kind.clone();
        if !spec.label.trim().is_empty() {
            field.base.label = spec.label.trim().to_owned();
        }
        field.base.attributes = spec.attributes.clone();

        let label = spec.label.trim().to_owned();
        let description = spec.description.trim().to_owned();
        let needs_overlay = rich_name.is_some()
            || !matches!(kind, DataFieldKind::Plain)
            || !label.is_empty()
            || !description.is_empty()
            || !spec.attributes.is_empty();
        let meta = needs_overlay.then(|| {
            let mut meta = FieldMeta::new(table, name)
                .label(&label)
                .description(&description)
                .kind(kind);
            meta.type_name = rich_name;
            meta.attributes = spec.attributes.clone();
            meta
        });
        Ok(ResolvedField { field, meta })
    }

    /// Fill in a `Key`'s target field when the caller named only a table, and
    /// check that the target exists — against the *projected* schema, so a key
    /// onto a table created earlier in the same batch resolves.
    fn resolve_kind(
        &self,
        table: &str,
        field: &str,
        kind: &DataFieldKind,
    ) -> Result<DataFieldKind> {
        let DataFieldKind::Key {
            target_table,
            target_field,
            summary_field,
        } = kind
        else {
            return Ok(kind.clone());
        };
        let target = self.projection.get(&target_table.0).ok_or_else(|| {
            Error::invalid(format!(
                "field `{table}.{field}` references table `{}`, which does not exist; \
                 the tables are {}",
                target_table.0,
                quoted(&self.table_names())
            ))
        })?;
        let target_field = if target_field.0.trim().is_empty() {
            match target.primary_key.as_slice() {
                [pk] => FieldId(pk.clone()),
                _ => {
                    return Err(Error::invalid(format!(
                        "field `{table}.{field}` references `{}`, which has no single-column \
                         primary key to point at",
                        target_table.0
                    )));
                }
            }
        } else {
            if target.field(&target_field.0).is_none() {
                return Err(Error::invalid(format!(
                    "field `{table}.{field}` references `{}.{}`, which does not exist",
                    target_table.0, target_field.0
                )));
            }
            target_field.clone()
        };
        if let Some(summary) = summary_field
            && target.field(&summary.0).is_none()
        {
            return Err(Error::invalid(format!(
                "field `{table}.{field}` names summary field `{}`, which `{}` does not have",
                summary.0, target_table.0
            )));
        }
        Ok(DataFieldKind::Key {
            target_table: target_table.clone(),
            target_field,
            summary_field: summary_field.clone(),
        })
    }

    /// The storage type a foreign key takes: the target column's, never the
    /// caller's — a key whose type disagrees with what it points at is a column
    /// Postgres refuses, and the caller has no reason to know the answer.
    fn key_storage_type(&self, target_table: &TableId, target_field: &FieldId) -> Result<TypeRef> {
        let target = self
            .projection
            .get(&target_table.0)
            .ok_or_else(|| Error::invalid(format!("table `{}` does not exist", target_table.0)))?;
        let field = target.field(&target_field.0).ok_or_else(|| {
            Error::invalid(format!(
                "`{}.{}` does not exist",
                target_table.0, target_field.0
            ))
        })?;
        // An identity primary key's stored type is `bigint`; the identity clause
        // belongs to the target, not to what references it.
        Ok(TypeRef::from_sql_type(
            field
                .base
                .type_
                .sql_type()
                .split(" generated ")
                .next()
                .unwrap_or("bigint"),
        ))
    }

    fn table_names(&self) -> Vec<String> {
        self.projection
            .tables()
            .iter()
            .filter(|t| !t.is_system())
            .map(|t| t.name.clone())
            .collect()
    }

    // --- end of batch ---------------------------------------------------------

    /// Everything that can only be checked once every operation has been read:
    /// the calculated-field expressions and the ownership formulas, both against
    /// the schema the batch ends with.
    fn validate_deferred(&self, catalog: &Catalog) -> Result<()> {
        let shape = self.projection.shape();
        for (table, field, expression) in &self.deferred_calc {
            validate_calc_expression(&shape, table, field, expression)?;
        }
        for name in &self.rls_dirty {
            let Some(table) = self.projection.get(name) else {
                continue;
            };
            validate_ownership(catalog, &self.projection, table)?;
        }
        Ok(())
    }

    /// The whole batch as steps of one transaction: the structured DDL in the
    /// order the caller wrote it, then the policy DDL, which is emitted last
    /// because it may reference columns the DDL above it creates.
    fn steps(&mut self, catalog: &Catalog) -> Result<Vec<SchemaStep>> {
        let mut steps: Vec<SchemaStep> = self.ddl.iter().cloned().map(SchemaStep::Change).collect();
        let dialect = catalog.primary().dialect();
        for name in &self.rls_dirty {
            let Some(table) = self.projection.get(name) else {
                continue;
            };
            let was = self.was_rls.get(name).copied().unwrap_or(false);
            if table.rls_enabled {
                steps.push(SchemaStep::Sql(enable_rls_sql(
                    dialect,
                    &self.projection,
                    table,
                )?));
            } else if was {
                steps.push(SchemaStep::Sql(disable_rls_sql(dialect, name)));
                self.applied.notes.push(format!(
                    "row-level security is no longer enforced on `{name}`: its policies \
                     were dropped, and the database now returns every row of it to any \
                     caller the role floors let through"
                ));
            }
        }
        Ok(steps)
    }
}

/// The stored `_sc_fields` row for a field, or `None` — including on a database
/// that has no overlay table at all, which is how a catalog behaves before
/// bootstrap and how §9 says a legacy database must go on behaving.
async fn stored_field_meta(
    catalog: &Catalog,
    table: &str,
    field: &str,
) -> Result<Option<FieldMeta>> {
    if catalog.get(FIELD_META_TABLE)?.is_none() {
        return Ok(None);
    }
    load_field_meta_by_field(catalog, table, field).await
}

/// A field spec resolved into the column to create and the overlay row that
/// describes it (`None` when the column alone records everything).
struct ResolvedField {
    field: DataField,
    meta: Option<FieldMeta>,
}

// --- validation shared with the handlers --------------------------------------

/// Validate a table's ownership settings against a projected schema (§7.3).
///
/// The formula must parse and validate; enabling RLS additionally requires a
/// backend that can enforce it and a formula the symbolic translator can turn
/// into policies for **all four** operations under the GUC environment. Enabling
/// and disabling are not symmetric on purpose: enabling is refused when it cannot
/// be honoured, because a flag that silently does nothing is worse than a
/// refusal, while disabling always succeeds and is *reported* — it is the one
/// operation here whose damage is invisible in the schema afterwards.
fn validate_ownership(
    catalog: &Catalog,
    projection: &SchemaProjection,
    table: &Table,
) -> Result<()> {
    let source = table
        .ownership
        .as_ref()
        .map(|f| f.source().to_owned())
        .or_else(|| {
            table
                .attributes
                .get(ATTR_OWNERSHIP_FORMULA)
                .and_then(serde_json::Value::as_str)
                .map(str::to_owned)
        })
        .unwrap_or_default();
    if source.trim().is_empty() {
        if table.rls_enabled {
            return Err(Error::invalid(format!(
                "table `{}`: row-level security needs an ownership formula to enforce; \
                 set a formula or leave RLS off",
                table.name
            )));
        }
        return Ok(());
    }
    let formula = sc_expr::Formula::parse(&source)
        .map_err(|e| Error::invalid(format!("table `{}`: {e}", table.name)))?;
    let shape = projection.shape();
    formula
        .validate(&shape, &table.name)
        .map_err(|e| Error::invalid(format!("table `{}`: {e}", table.name)))?;
    if !table.rls_enabled {
        return Ok(());
    }
    if !catalog.primary().capabilities().row_level_security {
        return Err(Error::invalid(
            "the connected database does not support row-level security",
        ));
    }
    let env = sc_expr::UserEnv::Guc {
        field_types: projection.user_field_types(),
    };
    let calc = table.calc_formulas();
    for op in [
        sc_expr::Operation::Read,
        sc_expr::Operation::Insert,
        sc_expr::Operation::Update,
        sc_expr::Operation::Delete,
    ] {
        if let Err(e) = sc_expr::translate(
            &formula,
            op,
            &sc_expr::Env::new(&env).with_calc(&calc),
            &shape,
            &table.name,
        ) {
            return Err(Error::invalid(format!(
                "table `{}`: cannot enable row-level security: {e}",
                table.name
            )));
        }
    }
    Ok(())
}

/// Validate a calculated field's expression against a projected schema, so a
/// broken formula is refused by name rather than becoming an overlay row the
/// merge silently drops. Validated over the calc scope: **no `user` and no
/// operation flags** — a calc field has no caller.
fn validate_calc_expression(
    shape: &sc_expr::SchemaShape,
    table: &str,
    field: &str,
    expression: &str,
) -> Result<()> {
    let formula = sc_expr::Formula::parse(expression)
        .map_err(|e| Error::invalid(format!("calculated field `{table}.{field}`: {e}")))?;
    let analysis = formula
        .validate(shape, table)
        .map_err(|e| Error::invalid(format!("calculated field `{table}.{field}`: {e}")))?;
    if analysis.uses(sc_expr::Ambient::User) || !analysis.flags.is_empty() {
        return Err(Error::invalid(format!(
            "calculated field `{table}.{field}`: a calculated field cannot use `user` \
             or the operation flags"
        )));
    }
    Ok(())
}

// --- the type vocabulary ------------------------------------------------------

/// The basic types offered in a field-type picker — the fixed scalar families
/// (the `Other` catch-all is not a thing anyone picks).
pub fn basic_field_types() -> Vec<BasicType> {
    use BasicType::{
        Bool, Bytes, Date, Decimal, Float, Int, Json as JsonT, Text, Time, Timestamp, Uuid,
    };
    vec![
        Text, Int, Float, Decimal, Bool, Uuid, Date, Time, Timestamp, JsonT, Bytes,
    ]
}

/// Every type name a field may be created with: the basic types then the
/// registered rich types, in that order.
///
/// The one list a picker and a tool's JSON-Schema `enum` are both built from
/// (§11.3), so a model cannot invent `varchar(255)` and an admin cannot be
/// offered a type the server would refuse.
pub fn field_type_names() -> Vec<String> {
    let mut names: Vec<String> = basic_field_types()
        .into_iter()
        .map(|b| b.name().to_owned())
        .collect();
    names.extend(sc_types::registered_rich_types());
    names
}

/// Resolve a `type` name into the column's storage type and, for a rich type, the
/// overlay type name to record. A name that is neither a registered rich type nor
/// a known basic type is refused (§3.3).
pub fn resolve_field_type(name: &str) -> Result<(TypeRef, Option<String>)> {
    if let Ok(rich) = RichTypeRef::resolve(name) {
        return Ok((
            TypeRef::from_sql_type(rich.sql_type()),
            Some(name.to_owned()),
        ));
    }
    if let Some(basic) = basic_field_types().into_iter().find(|b| b.name() == name) {
        return Ok((TypeRef::Basic(basic), None));
    }
    // Also accept a raw SQL alias (e.g. `int8`, `varchar`) for the basic case.
    match BasicType::from_sql_type(name) {
        BasicType::Other(_) => Err(Error::invalid(format!(
            "unknown field type `{name}`; it is neither a basic type nor a registered \
             rich type. The types are {}",
            quoted(&field_type_names())
        ))),
        known => Ok((TypeRef::Basic(known), None)),
    }
}

// --- small shared checks ------------------------------------------------------

/// A table or field name that can be a SQL identifier without quoting games.
///
/// Stricter than "not empty" on purpose: these names end up in DDL, in generated
/// TypeScript, in REST paths and in a model's tool arguments, and a name that
/// needs quoting in one of those is a bug waiting somewhere else.
fn check_identifier(name: &str, what: &str) -> Result<()> {
    if name.is_empty() {
        return Err(Error::invalid(format!("a {what} needs a name")));
    }
    if name.len() > 63 {
        return Err(Error::invalid(format!(
            "{what} name `{name}` is longer than the 63 characters a database identifier allows"
        )));
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap_or_default();
    if !(first.is_ascii_alphabetic() || first == '_')
        || !chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return Err(Error::invalid(format!(
            "{what} name `{name}` must start with a letter or underscore and contain \
             only letters, digits and underscores"
        )));
    }
    Ok(())
}

/// A role on the `1..=100` scale. Rejected rather than clamped, for the reason
/// the storage layer rejects: the nearest legal role is still a decision about
/// who reaches the data.
fn check_role(role: u8, key: &str) -> Result<u8> {
    if (1..=100).contains(&role) {
        Ok(role)
    } else {
        Err(Error::invalid(format!(
            "`{key}` must be a role between 1 and 100, got {role}"
        )))
    }
}

/// The calculated fields of `table` whose expression names `field`.
fn calc_readers(table: &Table, field: &str) -> Vec<String> {
    table
        .fields
        .iter()
        .filter(|f| {
            f.calc_expression()
                .is_some_and(|e| names_identifier(e, field))
        })
        .map(|f| format!("{}.{}", table.name, f.base.name))
        .collect()
}

/// Every `Key` field anywhere in the projection whose target is `table.field`.
fn keys_targeting(projection: &SchemaProjection, table: &str, field: &str) -> Vec<String> {
    let mut out = Vec::new();
    for other in projection.tables() {
        for f in &other.fields {
            if let DataFieldKind::Key {
                target_table,
                target_field,
                ..
            } = &f.kind
                && target_table.0 == table
                && target_field.0 == field
                && !(other.name == table && f.base.name == field)
            {
                out.push(format!("{}.{}", other.name, f.base.name));
            }
        }
    }
    out
}

/// Whether `source` uses `name` as a whole identifier — a token check, not a
/// parse, which is all a "is this field still read?" question needs and is what
/// keeps `owner_id` from matching `owner`.
fn names_identifier(source: &str, name: &str) -> bool {
    let bytes = source.as_bytes();
    let mut from = 0;
    while let Some(offset) = source[from..].find(name) {
        let start = from + offset;
        let end = start + name.len();
        let before_ok = start == 0 || !is_ident_byte(bytes[start - 1]);
        let after_ok = end == bytes.len() || !is_ident_byte(bytes[end]);
        if before_ok && after_ok {
            return true;
        }
        from = start + 1;
    }
    false
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// A list of names as `` `a`, `b` and `c` `` — the shape every refusal in this
/// module lists alternatives in, because these errors are read by a model that
/// can only recover if it is told what it should have said.
fn quoted(names: &[String]) -> String {
    match names.len() {
        0 => "nothing".to_owned(),
        1 => format!("`{}`", names[0]),
        _ => {
            let head: Vec<String> = names[..names.len() - 1]
                .iter()
                .map(|n| format!("`{n}`"))
                .collect();
            format!("{} and `{}`", head.join(", "), names[names.len() - 1])
        }
    }
}

/// A table's fields as a quoted list, for a "no such field" refusal.
fn field_list(table: &Table) -> String {
    let names: Vec<String> = table.fields.iter().map(|f| f.base.name.clone()).collect();
    quoted(&names)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_identifier_that_would_need_quoting_is_refused() {
        assert!(check_identifier("clients", "table").is_ok());
        assert!(check_identifier("time_entries2", "table").is_ok());
        assert!(check_identifier("_internal", "field").is_ok());
        assert!(check_identifier("", "table").is_err());
        assert!(check_identifier("2fast", "table").is_err());
        assert!(check_identifier("drop table", "table").is_err());
        assert!(check_identifier("naïve", "field").is_err());
        assert!(check_identifier(&"x".repeat(64), "table").is_err());
    }

    #[test]
    fn the_type_enum_is_the_live_registry_and_nothing_invented() {
        let names = field_type_names();
        assert!(names.contains(&"text".to_owned()));
        assert!(names.contains(&"int".to_owned()));
        assert!(!names.iter().any(|n| n.contains("varchar(")));
        // Every name in the list resolves; that is what makes it safe to publish
        // as an `enum` in a tool's JSON schema.
        for name in &names {
            resolve_field_type(name)
                .unwrap_or_else(|e| panic!("`{name}` is offered but does not resolve: {e}"));
        }
        assert!(resolve_field_type("varchar(255)").is_err());
    }

    #[test]
    fn a_field_is_read_by_a_formula_only_when_it_is_a_whole_identifier() {
        assert!(names_identifier("owner === user.id", "owner"));
        assert!(names_identifier("a + owner", "owner"));
        assert!(!names_identifier("owner_id === user.id", "owner"));
        assert!(!names_identifier("the_owner", "owner"));
        assert!(names_identifier("owner", "owner"));
    }

    #[test]
    fn a_refusal_lists_the_alternatives_the_way_a_reader_can_use() {
        assert_eq!(quoted(&[]), "nothing");
        assert_eq!(quoted(&["a".to_owned()]), "`a`");
        assert_eq!(
            quoted(&["a".to_owned(), "b".to_owned(), "c".to_owned()]),
            "`a`, `b` and `c`"
        );
    }

    #[test]
    fn omitted_settings_leave_what_they_do_not_name() {
        let settings = TableSettings {
            min_role_read: Some(40),
            ..TableSettings::default()
        };
        assert!(settings.touches_access());
        assert!(settings.label.is_none());
        assert!(settings.ownership_formula.is_none());
        assert!(settings.rls_enabled.is_none());
        assert!(!TableSettings::default().touches_access());
        assert!(TableSettings::default().is_empty());
    }

    #[test]
    fn a_grant_refusal_names_the_checkbox_that_would_allow_it() {
        let grants = Grants::none();
        let err = grants
            .check(grants.drop, "drop a table", GRANT_DROP)
            .unwrap_err()
            .to_string();
        assert!(err.contains("allow_drop"), "{err}");
        assert!(err.contains("nothing was applied"), "{err}");
        assert!(Grants::all().check(true, "x", "y").is_ok());
    }
}
