//! TypeScript consumer generation (design §13.1).
//!
//! [`generate_client`] turns an [`EndpointSet`] into a single TypeScript module
//! containing (a) request/response **type declarations** for every endpoint and
//! (b) a typed **API-consumer client** — an `ApiClient` interface plus a
//! `createClient` factory that calls the endpoints over `fetch`. Both the admin
//! UI and every code-framework application get a type-checked client generated
//! this way, so the client cannot drift from the server contract.
//!
//! The output is deterministic (endpoints in registration order) and is valid
//! strict-mode TypeScript: the factory's implementation is contextually typed by
//! the `ApiClient` interface, so a mismatch between a declared endpoint and the
//! generated call is a compile error — which is what the type-check test asserts.

use crate::endpoint::{Endpoint, EndpointSet, PathSegment};
use crate::schema::TypeSchema;
use std::fmt::Write;

/// Generate a TypeScript client module from an endpoint set.
pub fn generate_client(set: &EndpointSet) -> String {
    let mut out = String::new();

    out.push_str("// Code generated by sc-api. DO NOT EDIT.\n");
    out.push_str("// Regenerate with the sc-api TypeScript generator (design §13.1).\n\n");

    // --- per-endpoint request/response type declarations --------------------
    // Binary bodies get no named type: the client speaks `BodyInit` (upload) and
    // `Blob` (download) directly, which are the platform's own names for them.
    for ep in set {
        let pascal = to_pascal_case(&ep.name);
        if !ep.input.is_empty() && !ep.binary_input {
            let _ = writeln!(out, "export type {pascal}Request = {};", ts_type(&ep.input));
        }
        if !ep.output.is_empty() && !ep.binary_output {
            let _ = writeln!(
                out,
                "export type {pascal}Response = {};",
                ts_type(&ep.output)
            );
        }
    }
    out.push('\n');

    // --- ApiClient interface ------------------------------------------------
    out.push_str("export interface ApiClient {\n");
    for ep in set {
        let _ = writeln!(out, "  {};", method_signature(ep));
    }
    out.push_str("}\n\n");

    // --- client factory -----------------------------------------------------
    out.push_str("export interface ClientOptions {\n");
    out.push_str("  /** Prepended to every request path. */\n");
    out.push_str("  baseUrl?: string;\n");
    out.push_str("  /** Fetch implementation to use (defaults to global `fetch`). */\n");
    out.push_str("  fetch?: typeof fetch;\n");
    out.push_str("}\n\n");

    // Everything below exists to *make* requests, so an endpoint set with nothing
    // in it emits none of it. This is not a curiosity: an application that
    // enables no API provider has an empty set, and a generated file whose
    // helpers are declared and never called fails the consumer's own type-check
    // under `noUnusedLocals` — an error in generated code, about generated code,
    // for a mistake made somewhere else entirely.
    if set.is_empty() {
        out.push_str(
            "export function createClient(_options: ClientOptions = {}): ApiClient {\n             \x20 // This application enables no API provider, so it has no endpoints.\n             \x20 return {};\n             }\n",
        );
        return out;
    }

    // A shared error builder so a failed request carries the server's own message
    // (the `{ "error": ... }` body every endpoint returns), not just its status —
    // this is what lets a caller surface, e.g., a failed build's bundler
    // diagnostics. The `failed: <status>` prefix is kept stable for callers that
    // parse the status out of the message.
    out.push_str("async function clientError(op: string, res: Response): Promise<Error> {\n");
    out.push_str("  let detail = \"\";\n");
    out.push_str("  try {\n");
    out.push_str("    const body: unknown = await res.json();\n");
    out.push_str(
        "    if (body && typeof body === \"object\" && \"error\" in body && \
         typeof (body as { error: unknown }).error === \"string\") {\n",
    );
    out.push_str("      detail = `: ${(body as { error: string }).error}`;\n");
    out.push_str("    }\n");
    out.push_str("  } catch {\n");
    out.push_str("    // Non-JSON body: the status alone will have to describe the failure.\n");
    out.push_str("  }\n");
    out.push_str("  return new Error(`${op} failed: ${res.status}${detail}`);\n");
    out.push_str("}\n\n");

    // The double-submit CSRF check every mutating request must satisfy (§16).
    // The session cookie is what authenticates a browser client, so the server
    // refuses a state-changing request that does not echo the non-`HttpOnly`
    // CSRF cookie in the header — including `login` itself, which is a POST like
    // any other. Emitting it here rather than leaving it to each consumer is the
    // point: a client generated from the server's own endpoint set should be able
    // to call the server it was generated from.
    //
    // Guarded on `document` so the module stays usable where there is none (a
    // test, a node script); there is no cookie to echo there, and a caller with
    // its own scheme can still supply `options.fetch`.
    let _ = write!(
        out,
        r#"function csrfToken(): string | undefined {{
  if (typeof document === "undefined") return undefined;
  for (const part of document.cookie.split(";")) {{
    const [name, ...rest] = part.trim().split("=");
    if (name === "{cookie}") return decodeURIComponent(rest.join("="));
  }}
  return undefined;
}}

function requestHeaders(method: string, hasBody: boolean): Record<string, string> {{
  const headers: Record<string, string> = {{}};
  if (hasBody) headers["content-type"] = "application/json";
  if (method !== "GET" && method !== "HEAD") {{
    const token = csrfToken();
    if (token) headers["{header}"] = token;
  }}
  return headers;
}}

"#,
        cookie = crate::auth::CSRF_COOKIE,
        header = crate::auth::CSRF_HEADER,
    );

    out.push_str("export function createClient(options: ClientOptions = {}): ApiClient {\n");
    out.push_str("  const baseUrl = options.baseUrl ?? \"\";\n");
    out.push_str("  const doFetch = options.fetch ?? fetch;\n");
    out.push_str("  return {\n");
    for ep in set {
        emit_method_impl(&mut out, ep);
    }
    out.push_str("  };\n");
    out.push_str("}\n");

    out
}

/// The `ApiClient` interface signature for one endpoint, e.g.
/// `listRows(table: string): Promise<ListRowsResponse>`.
fn method_signature(ep: &Endpoint) -> String {
    let pascal = to_pascal_case(&ep.name);
    let mut params: Vec<String> = ep
        .path
        .params()
        .map(|(name, ty)| format!("{name}: {}", ty.ts_type()))
        .collect();
    if ep.binary_input {
        // An upload takes whatever `fetch` can send raw: a `Blob`/`File` from an
        // `<input type=file>`, an `ArrayBuffer`, a string.
        params.push("body: BodyInit".to_owned());
    } else if !ep.input.is_empty() {
        params.push(format!("body: {pascal}Request"));
    }
    let ret = if ep.binary_output {
        "Blob".to_owned()
    } else if ep.output.is_empty() {
        "void".to_owned()
    } else {
        format!("{pascal}Response")
    };
    format!("{}({}): Promise<{ret}>", ep.name, params.join(", "))
}

/// Emit the factory's implementation of one endpoint method.
fn emit_method_impl(out: &mut String, ep: &Endpoint) {
    let pascal = to_pascal_case(&ep.name);
    let mut param_names: Vec<String> = ep.path.params().map(|(n, _)| n.to_owned()).collect();
    let has_body = ep.binary_input || !ep.input.is_empty();
    if has_body {
        param_names.push("body".to_owned());
    }

    let _ = writeln!(out, "    async {}({}) {{", ep.name, param_names.join(", "));
    let _ = writeln!(
        out,
        "      const res = await doFetch(`${{baseUrl}}{}`, {{",
        url_template(ep)
    );
    let _ = writeln!(out, "        method: \"{}\",", ep.method.as_str());
    // A binary body goes out as-is with no JSON content type — `fetch` derives
    // one from a `Blob` itself — so `hasBody` is false for the header helper
    // (which only decides the JSON content type; CSRF rides on the method).
    let _ = writeln!(
        out,
        "        headers: requestHeaders(\"{}\", {}),",
        ep.method.as_str(),
        has_body && !ep.binary_input
    );
    if ep.binary_input {
        out.push_str("        body,\n");
    } else if has_body {
        out.push_str("        body: JSON.stringify(body),\n");
    }
    out.push_str("      });\n");
    let _ = writeln!(
        out,
        "      if (!res.ok) throw await clientError(\"{}\", res);",
        ep.name
    );
    if ep.binary_output {
        out.push_str("      return await res.blob();\n");
    } else if ep.output.is_empty() {
        out.push_str("      return;\n");
    } else {
        let _ = writeln!(out, "      return (await res.json()) as {pascal}Response;");
    }
    out.push_str("    },\n");
}

/// The request URL as a JS template-literal body (path params interpolated),
/// e.g. `/api/tables/${table}/rows/${id}`.
fn url_template(ep: &Endpoint) -> String {
    let mut out = String::from("/");
    for (i, seg) in ep.path.segments.iter().enumerate() {
        if i > 0 {
            out.push('/');
        }
        match seg {
            PathSegment::Literal(s) => out.push_str(s),
            PathSegment::Param { name, .. } => {
                let _ = write!(out, "${{{name}}}");
            }
        }
    }
    out
}

/// Render a [`TypeSchema`] as an inline TypeScript type.
fn ts_type(schema: &TypeSchema) -> String {
    match schema {
        TypeSchema::Value(v) => v.ts_type().to_owned(),
        TypeSchema::Struct(fields) if fields.is_empty() => "Record<string, never>".to_owned(),
        TypeSchema::Struct(fields) => {
            let members: Vec<String> = fields
                .iter()
                .map(|f| match &f.schema {
                    // An optional field is both `?`-optional and `| null`.
                    TypeSchema::Optional(inner) => {
                        format!("{}?: {} | null", f.name, ts_type(inner))
                    }
                    other => format!("{}: {}", f.name, ts_type(other)),
                })
                .collect();
            format!("{{ {} }}", members.join("; "))
        }
        TypeSchema::Array(inner) => format!("Array<{}>", ts_type(inner)),
        TypeSchema::Optional(inner) => format!("{} | null", ts_type(inner)),
    }
}

/// Convert a `camelCase` operation name to `PascalCase` for type names.
fn to_pascal_case(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}
