//! `run_agent`: an agent as a trigger body, against a real database (TODO Phase
//! 6, §11.5).
//!
//! What is pinned here:
//!
//! - the milestone's **done when** — an insert on a table fires a trigger that
//!   runs an agent, the row's data reaches the prompt (checked where it matters:
//!   in the request the model was actually sent), and the run is readable
//!   afterwards out of `_fd_runs`, which is where the chat panel's history reads
//!   it from;
//! - a triggered run carries the **trigger's authority** (decision 5): its tools
//!   run, its row is written, and the run records no user because nobody was
//!   there;
//! - the action **returns** the final message and the run id rather than
//!   streaming, so a directly-run trigger answers its caller;
//! - and the configuration is checked **on save and on load**: an unknown agent,
//!   a prompt naming something that is not in the event's scope, and an agent
//!   deleted after the trigger was saved, which leaves the trigger out of the
//!   live set with a reason instead of failing when a row is inserted.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use crate::common;

use std::sync::{Arc, Mutex};

use common::{Env, config};
use sc_action::{ActionRegistry, EventKind, Trigger, save_trigger};
use sc_agent::testing::{FakeProvider, Reply};
use sc_agent::{
    Agent, EnabledTrait, ProviderConnector, RunState, delete_agent, list_runs, load_agent_by_name,
    save_agent,
};
use sc_catalog::Catalog;
use sc_core_actions::builtin_actions;
use sc_core_traits::{CFG_AGENT, CFG_PROMPT, builtin_traits, register_agent_actions};
use sc_error::Result;
use sc_llm::{ConnectedModel, LlmProvider};
use sc_types::Attrs;
use serde_json::json;

/// Posts that are written, and the summaries an agent files about them.
const SCHEMA: &str = "
    CREATE TABLE posts (
        id bigint generated by default as identity primary key,
        title text,
        body text
    );
    CREATE TABLE summaries (
        id bigint generated by default as identity primary key,
        post text,
        summary text
    );
";

/// What the scripted model answers with once it has filed its summary.
const ANSWER: &str = "Filed a summary.";

// --- a model that answers, and remembers what it was asked -------------------

/// A connector that hands out a fresh script per run and keeps every provider it
/// made.
///
/// Fresh per run because a triggered run connects once and a test may fire the
/// trigger more than once; kept because "the row's data reached the prompt" is a
/// claim about the **request the model saw**, and the only way to check it at
/// that boundary is to still have the provider afterwards.
struct Scripted {
    script: Vec<Reply>,
    made: Mutex<Vec<Arc<FakeProvider>>>,
}

impl Scripted {
    fn new(script: impl IntoIterator<Item = Reply>) -> Arc<Scripted> {
        Arc::new(Scripted {
            script: script.into_iter().collect(),
            made: Mutex::new(Vec::new()),
        })
    }

    /// The provider the most recent run talked to.
    fn last(&self) -> Arc<FakeProvider> {
        let made = self.made.lock().unwrap();
        Arc::clone(made.last().expect("a run should have connected a provider"))
    }

    /// How many runs connected.
    fn runs(&self) -> usize {
        self.made.lock().unwrap().len()
    }
}

#[async_trait::async_trait]
impl ProviderConnector for Scripted {
    async fn connect(
        &self,
        _catalog: &Catalog,
        _agent: &Agent,
        _role: sc_agent::ModelRole,
    ) -> Result<ConnectedModel> {
        let provider = Arc::new(FakeProvider::new(self.script.clone()));
        self.made.lock().unwrap().push(Arc::clone(&provider));
        Ok(ConnectedModel::unconfigured(
            provider as Arc<dyn LlmProvider>,
        ))
    }
}

// --- the world under test ----------------------------------------------------

/// The agent the trigger runs: one grant, to file a summary.
fn summariser() -> Agent {
    Agent::new("summariser", "main")
        .system_prompt("You summarise posts.")
        .with_trait(EnabledTrait::new("insert_row").config("table", "summaries"))
}

/// `run_agent` configured to summarise the row that was just written.
///
/// A **template literal**, not `'…' + row.title`: arithmetic is null-guarded in
/// this language (§7.3), so a concatenation with a null column would compute
/// null and the run would be refused for having nothing to ask.
fn summarise_trigger() -> Trigger {
    Trigger::new("summarise_post", EventKind::Insert, "run_agent")
        .on("posts")
        .config(CFG_AGENT, "summariser")
        .config(
            CFG_PROMPT,
            "`Summarise the post \"${row.title}\": ${row.body}`",
        )
}

/// An environment whose dispatcher can run agents, with `summariser` stored.
async fn setup(script: impl IntoIterator<Item = Reply>) -> Result<(Env, Arc<Scripted>)> {
    let providers = Scripted::new(script);
    let mut actions: ActionRegistry = builtin_actions()?;
    register_agent_actions(
        &mut actions,
        Arc::new(builtin_traits()?),
        Arc::clone(&providers) as Arc<dyn ProviderConnector>,
    )?;
    let env = Env::with_schema(SCHEMA).await?.with_triggers(actions)?;
    save_agent(&env.catalog, &env.registry, &summariser()).await?;
    Ok((env, providers))
}

/// The action registry the dispatcher was built over.
fn registry(env: &Env) -> Arc<ActionRegistry> {
    env.dispatcher.as_ref().expect("a dispatcher").registry()
}

/// The summaries the agent filed, oldest first.
async fn summaries(env: &Env) -> Result<Vec<(String, String)>> {
    let mut rows = env.rows("summaries").await?;
    rows.sort_by_key(|r| r["id"].as_i64().unwrap_or_default());
    Ok(rows
        .iter()
        .map(|r| {
            (
                r["post"].as_str().unwrap_or_default().to_owned(),
                r["summary"].as_str().unwrap_or_default().to_owned(),
            )
        })
        .collect())
}

// --- the tests ---------------------------------------------------------------

/// The milestone's **done when**: a row is inserted, the trigger fires, the
/// agent runs with a prompt built from that row, and the run it left behind is
/// readable afterwards.
#[tokio::test]
async fn an_insert_starts_an_agent_with_a_prompt_built_from_the_row() -> Result<()> {
    let (env, providers) = setup([
        Reply::calls(
            "insert_into_summaries",
            json!({ "post": "Hello", "summary": "A greeting." }),
        ),
        Reply::says(ANSWER),
    ])
    .await?;
    save_trigger(&env.catalog, &registry(&env), &summarise_trigger()).await?;
    env.reload_triggers().await?;

    // An ordinary write through the row layer — which is what raises the event.
    let posts = env.catalog.require("posts")?;
    sc_api::insert_row_as(
        &env.catalog,
        &posts,
        &json!({ "title": "Hello", "body": "The first post." }),
        sc_auth::ROLE_ADMIN,
        None,
        None,
        &[],
        &sc_api::rows::Executor::Pooled,
    )
    .await?;

    // One run, of that agent, finished.
    let runs = list_runs(&env.catalog, "summariser").await?;
    assert_eq!(runs.len(), 1, "the insert should have started one run");
    let run = &runs[0];
    assert_eq!(run.state, RunState::Done);
    // Nobody was there: a triggered run carries the trigger's authority, and the
    // row says so (decision 5).
    assert_eq!(run.user, None);
    // The history list has something to show it as, which a run created by
    // `Runner::start` alone would not have.
    assert!(run.description.contains("summarise_post"), "{run:?}");

    // The row's data reached the prompt — checked in the run's transcript…
    let messages = run.agent_loop()?.messages().to_vec();
    let sc_llm::LlmMessage::User { content } = &messages[0] else {
        panic!("the run should open with the prompt: {messages:?}")
    };
    assert_eq!(content, r#"Summarise the post "Hello": The first post."#);
    // …and in the request the model was actually sent, which is the boundary the
    // claim is about. The system prompt is the agent's own.
    let request = providers.last().requests().remove(0);
    assert_eq!(request.messages, messages[..1]);
    assert_eq!(request.system.as_deref(), Some("You summarise posts."));

    // The agent's tool ran with the trigger's authority and wrote its row
    // through the ordinary write path.
    assert_eq!(
        summaries(&env).await?,
        vec![("Hello".to_owned(), "A greeting.".to_owned())]
    );

    // And the whole exchange is on the run: prompt, tool call, tool result,
    // answer.
    assert_eq!(messages.len(), 4, "{messages:?}");
    assert!(matches!(
        &messages[2],
        sc_llm::LlmMessage::ToolResult { name, .. } if name == "insert_into_summaries"
    ));
    let sc_llm::LlmMessage::Assistant { content, .. } = &messages[3] else {
        panic!("the model's answer should end it: {messages:?}")
    };
    assert_eq!(content, ANSWER);
    Ok(())
}

/// Asked directly, the action **answers**: the final assistant message and the
/// run id, not a stream (§11.5).
#[tokio::test]
async fn running_the_trigger_directly_returns_the_answer_and_the_run_id() -> Result<()> {
    let (env, providers) = setup([Reply::says(ANSWER)]).await?;
    // A `none` trigger, because a directly-run table trigger has no row — and a
    // prompt over the payload is what such a trigger's whole vocabulary is.
    let trigger = Trigger::new("summarise_now", EventKind::None, "run_agent")
        .config(CFG_AGENT, "summariser")
        .config(CFG_PROMPT, "`Summarise: ${payload.title}`");
    save_trigger(&env.catalog, &registry(&env), &trigger).await?;
    env.reload_triggers().await?;

    let result = env
        .dispatcher
        .as_ref()
        .expect("a dispatcher")
        .run_trigger(
            &env.catalog,
            "summarise_now",
            json!({ "title": "Ubik" }),
            None,
        )
        .await?;

    assert_eq!(result["agent"], json!("summariser"));
    assert_eq!(result["answer"], json!(ANSWER));
    assert_eq!(result["conclusion"], json!("answered"));

    // The run id resolves to the run, which is what makes a triggered
    // conversation readable in the chat panel afterwards.
    let id = result["run"].as_str().expect("a run id");
    let run =
        sc_agent::require_run(&env.catalog, sc_agent::RunId(id.parse().expect("a uuid"))).await?;
    assert_eq!(run.subject, "summariser");
    assert_eq!(run.state, RunState::Done);
    assert_eq!(providers.runs(), 1);
    Ok(())
}

/// A prompt that computed nothing is refused rather than asked — an agent sent
/// an empty question spends a provider call to answer nothing.
#[tokio::test]
async fn a_prompt_that_computes_nothing_refuses_before_the_model_is_called() -> Result<()> {
    let (env, providers) = setup([Reply::says(ANSWER)]).await?;
    let trigger = Trigger::new("summarise_now", EventKind::None, "run_agent")
        .config(CFG_AGENT, "summariser")
        .config(CFG_PROMPT, "payload.missing");
    save_trigger(&env.catalog, &registry(&env), &trigger).await?;
    env.reload_triggers().await?;

    let err = env
        .dispatcher
        .as_ref()
        .expect("a dispatcher")
        .run_trigger(&env.catalog, "summarise_now", json!({}), None)
        .await
        .unwrap_err();
    assert!(err.to_string().contains(CFG_PROMPT), "{err}");
    // Nothing was connected and no run was left half-written.
    assert_eq!(providers.runs(), 0);
    assert_eq!(list_runs(&env.catalog, "summariser").await?.len(), 0);
    Ok(())
}

/// The configuration is checked **on save**, in front of the admin: an agent
/// that does not exist, and a prompt naming something the event will not have.
#[tokio::test]
async fn the_configuration_is_refused_on_save() -> Result<()> {
    let (env, _providers) = setup([]).await?;

    let unknown = Trigger::new("t1", EventKind::None, "run_agent")
        .config(CFG_AGENT, "assistant")
        .config(CFG_PROMPT, "'hello'");
    let err = save_trigger(&env.catalog, &registry(&env), &unknown)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("assistant"), "{err}");

    // `row` is not in scope on an event with no row, so a prompt that reads it
    // is a message on the form rather than a firing that fails.
    let no_row = Trigger::new("t2", EventKind::None, "run_agent")
        .config(CFG_AGENT, "summariser")
        .config(CFG_PROMPT, "`${row.title}`");
    let err = save_trigger(&env.catalog, &registry(&env), &no_row)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("row"), "{err}");

    // And a bare identifier is refused by name: a formula that only reads the
    // event ranges over no table, so `title` is not `row.title` spelled shorter.
    let bare = Trigger::new("t3", EventKind::Insert, "run_agent")
        .on("posts")
        .config(CFG_AGENT, "summariser")
        .config(CFG_PROMPT, "title");
    let err = save_trigger(&env.catalog, &registry(&env), &bare)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("title"), "{err}");
    Ok(())
}

/// …and **on load**: an agent deleted after the trigger was saved leaves the
/// trigger out of the live set with a reason, rather than failing when a row is
/// inserted.
#[tokio::test]
async fn deleting_the_agent_leaves_the_trigger_out_of_the_live_set_with_a_reason() -> Result<()> {
    let (env, providers) = setup([Reply::says(ANSWER)]).await?;
    save_trigger(&env.catalog, &registry(&env), &summarise_trigger()).await?;
    env.reload_triggers().await?;

    let stored = load_agent_by_name(&env.catalog, "summariser")
        .await?
        .expect("the agent");
    assert!(delete_agent(&env.catalog, stored.id).await?);
    env.reload_triggers().await?;

    let triggers = env.dispatcher.as_ref().expect("a dispatcher").triggers()?;
    let issue = triggers
        .issues()
        .iter()
        .find(|i| i.trigger == "summarise_post")
        .expect("the trigger should be listed as broken")
        .problem
        .clone();
    assert!(issue.contains("summariser"), "{issue}");

    // It is out of the live set, so the insert that would have fired it does not
    // — and the failure is one the admin can see and repair rather than one a
    // writer discovers.
    assert!(triggers.require("summarise_post").is_err());
    let posts = env.catalog.require("posts")?;
    sc_api::insert_row_as(
        &env.catalog,
        &posts,
        &json!({ "title": "Hello", "body": "…" }),
        sc_auth::ROLE_ADMIN,
        None,
        None,
        &[],
        &sc_api::rows::Executor::Pooled,
    )
    .await?;
    assert_eq!(providers.runs(), 0);
    Ok(())
}

/// The action declares its two settings, and both are required — the form the
/// admin UI renders for a trigger whose action is an agent.
#[tokio::test]
async fn the_action_declares_the_settings_the_form_renders() -> Result<()> {
    let (env, _providers) = setup([]).await?;
    let action = registry(&env).require("run_agent")?.clone();
    let spec = action.config_spec();
    let names: Vec<&str> = spec.iter().map(|f| f.name()).collect();
    assert_eq!(names, vec![CFG_AGENT, CFG_PROMPT]);
    assert!(spec.iter().all(|f| f.required));
    assert!(!action.description().is_empty());
    // And it is not one of `sc-core-actions`' built-ins: it needs the trait
    // registry and a provider connector, which no other action does.
    assert!(builtin_actions()?.get("run_agent").is_none());
    Ok(())
}

/// A configuration is a configuration: `Attrs` in, and the same reader on the
/// save path and the fire path.
#[tokio::test]
async fn an_empty_configuration_names_the_setting_it_wants() -> Result<()> {
    let (env, _providers) = setup([]).await?;
    let empty: Attrs = config(&[]);
    let trigger = Trigger::new("t", EventKind::None, "run_agent").with_configuration(empty);
    let err = save_trigger(&env.catalog, &registry(&env), &trigger)
        .await
        .unwrap_err();
    let msg = err.to_string();
    assert!(msg.contains(CFG_AGENT) || msg.contains(CFG_PROMPT), "{msg}");
    Ok(())
}
