//! `run_trigger` against real triggers (TODO Phase 3).
//!
//! What is pinned here:
//!
//! - the tool **runs the dispatcher's trigger**, not a copy of it: the action
//!   configured against the trigger does its work, and what it returned comes
//!   back as the tool result;
//! - the trigger's own **`min_role` still gates it**, so exposing an agent to a
//!   role does not thereby expose everything the agent can reach — and a
//!   trigger-started run, which carries the trigger's authority, clears the
//!   floor;
//! - a **disabled** trigger stays disabled however it is asked;
//! - a trait naming a trigger that does not exist is refused **on save**, and one
//!   whose trigger is deleted afterwards leaves its agent out of the live set
//!   with a reason;
//! - a run driven with no dispatcher at all says so rather than finding another
//!   way to fire an event;
//! - and the Phase 3 "done when": an agent asks about the data and then performs
//!   the action, with the whole exchange in its run's context.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use crate::common;

use std::sync::Arc;

use common::{Env, as_user, config, titles};
use sc_action::{ATTR_ENABLED, ActionRegistry, EventKind, Trigger, delete_trigger, save_trigger};
use sc_agent::testing::{FakeProvider, Reply};
use sc_agent::{Agent, Agents, EnabledTrait, RunCaller, Runner, save_agent};
use sc_core_actions::builtin_actions;
use sc_core_traits::{CFG_TABLE, CFG_TRIGGER};
use sc_error::Result;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

/// The library plus somewhere for a trigger to write.
const SCHEMA: &str = "
    CREATE TABLE books (
        id bigint primary key,
        title text,
        pages bigint,
        owner text,
        notes text
    );
    INSERT INTO books VALUES
        (1, 'Dune',   412, 'ada@example.com', 'ada''s copy'),
        (2, 'Emma',   474, 'bob@example.com', 'bob''s copy'),
        (3, 'Ilium',  576, 'ada@example.com', 'also ada''s'),
        (4, 'Ubik',   224, 'bob@example.com', NULL);
    CREATE TABLE reorders (
        id bigint generated by default as identity primary key,
        title text,
        who text
    );
";

/// The trigger every test here exposes: a `none` trigger — one with no intrinsic
/// occurrence, which runs when something asks — that files a reorder from the
/// payload the caller sends.
fn reorder(min_role: Option<u8>) -> Trigger {
    let trigger = Trigger::new("file_reorder", EventKind::None, "insert_row")
        .description("File a reorder for a book")
        .config("table", "reorders")
        .config(
            "values",
            json!({ "title": "payload.title", "who": "user ? user.email : 'nobody'" }),
        );
    match min_role {
        Some(role) => trigger.min_role(role),
        None => trigger,
    }
}

/// An environment with the dispatcher installed and `file_reorder` saved.
async fn setup(min_role: Option<u8>) -> Result<Env> {
    let env = Env::with_schema(SCHEMA)
        .await?
        .with_triggers(builtin_actions()?)?;
    save_trigger(&env.catalog, &registry(&env), &reorder(min_role)).await?;
    env.reload_triggers().await?;
    Ok(env)
}

/// The action registry the dispatcher was built over.
fn registry(env: &Env) -> Arc<ActionRegistry> {
    env.dispatcher.as_ref().expect("a dispatcher").registry()
}

/// `run_trigger` configured against it.
fn cfg() -> Attrs {
    config(&[(CFG_TRIGGER, json!("file_reorder"))])
}

#[tokio::test]
async fn the_tool_is_named_for_its_trigger_and_takes_the_event_payload() -> Result<()> {
    let env = setup(None).await?;
    let tools = env.tools("run_trigger", &cfg());
    assert_eq!(tools.len(), 1);
    assert_eq!(tools[0].name, "run_file_reorder");
    // The payload is the action's business, so the schema is open: a closed one
    // would be this crate guessing at another crate's contract.
    assert_eq!(tools[0].parameters["additionalProperties"], json!(true));
    // And the model is told this *does* something, because a tool it calls to
    // find out what would happen is a tool that has already happened.
    assert!(
        tools[0].description.contains("do not call it to find out"),
        "{}",
        tools[0].description
    );
    Ok(())
}

#[tokio::test]
async fn running_it_runs_the_trigger_the_admin_configured() -> Result<()> {
    let env = setup(Some(40)).await?;
    let result = env
        .call(
            "run_trigger",
            &cfg(),
            json!({"title": "Dune"}),
            &RunCaller::system(),
        )
        .await?;
    assert_eq!(result["trigger"], json!("file_reorder"));
    // What the action returned is what the tool returns — the inserted row.
    assert_eq!(result["result"]["title"], json!("Dune"));

    let reorders = env.rows("reorders").await?;
    assert_eq!(reorders.len(), 1, "{reorders:?}");
    assert_eq!(reorders[0]["title"], json!("Dune"));
    // A system run has no user, and the trigger's own formula says so rather
    // than failing: the caller travels with the event either way.
    assert_eq!(reorders[0]["who"], json!("nobody"));

    // The caller reaches the trigger's formulas: a chat turn's user is the
    // `user` an action sees.
    env.call(
        "run_trigger",
        &cfg(),
        json!({"title": "Ilium"}),
        &as_user("ada@example.com"),
    )
    .await?;
    let reorders = env.rows("reorders").await?;
    assert_eq!(reorders.len(), 2);
    assert_eq!(reorders[1]["who"], json!("ada@example.com"));
    Ok(())
}

#[tokio::test]
async fn the_triggers_own_min_role_still_gates_it() -> Result<()> {
    // Admin-only: `min_role` absent is the safe reading everywhere else in §10,
    // and reaching the trigger through an agent must not relax it.
    let env = setup(None).await?;
    let err = env
        .call(
            "run_trigger",
            &cfg(),
            json!({"title": "Dune"}),
            &as_user("ada@example.com"),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("file_reorder"), "{err}");
    assert!(env.rows("reorders").await?.is_empty(), "nothing ran");

    // …while a run started by a trigger carries that trigger's authority
    // (decision 5) and clears the floor, which is the same rule read the other
    // way round.
    env.call(
        "run_trigger",
        &cfg(),
        json!({"title": "Dune"}),
        &RunCaller::system(),
    )
    .await?;
    assert_eq!(env.rows("reorders").await?.len(), 1);

    // Opened to role 40, the same caller may run it — and a caller below that
    // floor still may not.
    let env = setup(Some(40)).await?;
    env.call(
        "run_trigger",
        &cfg(),
        json!({"title": "Dune"}),
        &as_user("ada@example.com"),
    )
    .await?;
    assert_eq!(env.rows("reorders").await?.len(), 1);

    let mut public = as_user("anon@example.com");
    public.role = 100;
    if let Some(user) = &mut public.user {
        user.role = 100;
    }
    let err = env
        .call("run_trigger", &cfg(), json!({"title": "Dune"}), &public)
        .await
        .unwrap_err();
    assert!(err.to_string().contains("role 40"), "{err}");
    assert_eq!(env.rows("reorders").await?.len(), 1, "still just the one");
    Ok(())
}

#[tokio::test]
async fn a_disabled_trigger_stays_disabled_however_it_is_asked() -> Result<()> {
    let env = Env::with_schema(SCHEMA)
        .await?
        .with_triggers(builtin_actions()?)?;
    let mut trigger = reorder(None);
    trigger
        .attributes
        .insert(ATTR_ENABLED.to_owned(), json!(false));
    save_trigger(&env.catalog, &registry(&env), &trigger).await?;
    env.reload_triggers().await?;

    let err = env
        .call(
            "run_trigger",
            &cfg(),
            json!({"title": "Dune"}),
            &RunCaller::system(),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("disabled"), "{err}");
    assert!(env.rows("reorders").await?.is_empty());
    Ok(())
}

#[tokio::test]
async fn a_trigger_that_is_not_there_is_refused_on_save_and_again_on_load() -> Result<()> {
    let env = setup(None).await?;
    // On save, in front of the admin.
    env.check("run_trigger", &cfg()).await?;
    let err = env
        .check("run_trigger", &config(&[(CFG_TRIGGER, json!("nope"))]))
        .await
        .unwrap_err();
    assert!(err.to_string().contains("nope"), "{err}");
    assert!(env.check("run_trigger", &Attrs::new()).await.is_err());

    // …and again on load: an agent whose trigger was deleted underneath it
    // leaves the live set with its reason kept, and stays stored and editable.
    let agent = Agent::new("librarian", "main")
        .with_trait(EnabledTrait::new("run_trigger").config(CFG_TRIGGER, "file_reorder"));
    save_agent(&env.catalog, &env.registry, &agent).await?;
    assert_eq!(
        Agents::load(&env.catalog, &env.registry).await?.all().len(),
        1
    );

    let stored = sc_action::load_trigger_by_name(&env.catalog, "file_reorder")
        .await?
        .expect("the trigger");
    delete_trigger(&env.catalog, stored.id).await?;

    let agents = Agents::load(&env.catalog, &env.registry).await?;
    assert!(agents.all().is_empty());
    assert!(
        agents.issues()[0].problem.contains("file_reorder"),
        "{}",
        agents.issues()[0].problem
    );
    // The tool keeps the name the configuration gives it, so the collision check
    // and the admin UI still have something to say about a broken agent.
    assert_eq!(
        env.tools("run_trigger", &agent.traits[0].config)[0].name,
        "run_file_reorder"
    );
    Ok(())
}

#[tokio::test]
async fn a_context_with_no_dispatcher_says_so_rather_than_firing_another_way() -> Result<()> {
    // The honest failure: `Env::new` installs no dispatcher, so the tool has no
    // way to reach the trigger set — and it says that, in the same shape a
    // missing evaluator does, rather than reaching for a second implementation.
    let env = Env::with_schema(SCHEMA).await?;
    save_trigger(&env.catalog, &Arc::new(builtin_actions()?), &reorder(None)).await?;
    // It still validates — the trigger is stored, and validation reads storage.
    env.check("run_trigger", &cfg()).await?;
    let err = env
        .call("run_trigger", &cfg(), json!({}), &RunCaller::system())
        .await
        .unwrap_err();
    assert!(err.to_string().contains("dispatcher"), "{err}");
    Ok(())
}

#[tokio::test]
async fn an_agent_answers_a_question_and_then_performs_the_action() -> Result<()> {
    // Phase 3's "done when": an agent given `query_table` over a real table and
    // `run_trigger` over a real trigger answers a question about the data and
    // then performs the action, with the whole exchange in its run's context.
    let env = setup(Some(40)).await?;
    // Ada is below the table's read floor, so what the agent can tell her about
    // is what her ownership grants: her own two books.
    env.own("books", "owner === user.email").await?;
    let agent = Agent::new("librarian", "main")
        .system_prompt("You look after the library.")
        .with_trait(EnabledTrait::new("query_table").config(CFG_TABLE, "books"))
        .with_trait(EnabledTrait::new("run_trigger").config(CFG_TRIGGER, "file_reorder"));
    save_agent(&env.catalog, &env.registry, &agent).await?;

    let provider = Arc::new(FakeProvider::new([
        Reply::calls("query_books", json!({"order_by": "pages"}))
            .with_preamble("Let me see which is shortest."),
        Reply::calls("run_file_reorder", json!({"title": "Dune"})),
        Reply::says("Dune is your shortest at 412 pages, and I have reordered it."),
    ]));
    let dispatcher = env.dispatcher.clone().expect("a dispatcher");
    let runner = Runner::new(
        &env.catalog,
        &env.registry,
        &agent,
        provider.clone(),
        as_user("ada@example.com"),
    )
    .with_triggers(&dispatcher);

    let (run, conclusion) = runner.start("reorder my shortest book").await?;
    assert_eq!(
        conclusion.answer(),
        Some("Dune is your shortest at 412 pages, and I have reordered it.")
    );

    // The action ran, as the person chatting.
    let reorders = env.rows("reorders").await?;
    assert_eq!(reorders.len(), 1, "{reorders:?}");
    assert_eq!(reorders[0]["title"], json!("Dune"));
    assert_eq!(reorders[0]["who"], json!("ada@example.com"));

    // Both tools were offered under their derived names, and both exchanges are
    // on the run — the read that found the book and the action that reordered it.
    let requests = provider.requests();
    let offered: Vec<&str> = requests[0].tools.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(offered, vec!["query_books", "run_file_reorder"]);

    let state = sc_agent::load_run(&env.catalog, run.id)
        .await?
        .expect("the run row")
        .agent_loop()?;
    let results: Vec<(String, Json)> = state
        .messages()
        .iter()
        .filter_map(|m| match m {
            sc_llm::LlmMessage::ToolResult { content, name, .. } => Some((
                name.clone(),
                serde_json::from_str(content).unwrap_or(Json::Null),
            )),
            _ => None,
        })
        .collect();
    assert_eq!(results.len(), 2);
    assert_eq!(titles(&results[0].1), ["Dune", "Ilium"]);
    assert_eq!(results[1].0, "run_file_reorder");
    assert_eq!(results[1].1["result"]["title"], json!("Dune"));
    Ok(())
}
