//! `insert_row`, `update_rows` and `delete_rows` against a real database
//! (TODO Phase 3).
//!
//! The read trait's tests pin what an agent may *see*; these pin what it may
//! *change*, which is the half where being wrong costs data:
//!
//! - a write goes **through `sc-api`**, so the table's own trigger fires with the
//!   row the model wrote — an agent's insert is an insert, not a special one;
//! - **the caller's access is the tool's access** on a write as on a read: under
//!   an ownership formula each user changes their own rows and nobody else's,
//!   and an update that would move a row out of the caller's reach is refused
//!   even though every individual value in it is valid;
//! - the **field allow-list** bounds what may be set while leaving the filter
//!   free to name any field, which is how a model addresses a row it may not
//!   rename;
//! - `max_rows` **refuses** rather than truncating, and nothing is written;
//! - `update_rows` and `delete_rows` **require a `where`**, so no omission can
//!   ask for the whole table;
//! - and each trait's `validate_config` refuses, in front of the admin, a table
//!   that is gone, a field that is not real and a field that cannot be written.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use crate::common;

use std::sync::Arc;

use common::{Env, as_user, config, row_titles};
use sc_action::{EventKind, Trigger, save_trigger};
use sc_agent::testing::{FakeProvider, Reply};
use sc_agent::{Agent, EnabledTrait, RunCaller, Runner, save_agent};
use sc_core_actions::builtin_actions;
use sc_core_traits::{CFG_FIELDS, CFG_MAX_ROWS, CFG_TABLE};
use sc_error::Result;
use sc_types::Attrs;
use serde_json::{Value as Json, json};

/// The library plus the table a trigger writes to, so "the write went through
/// the row layer" can be asserted rather than assumed.
const SCHEMA_WITH_AUDIT: &str = "
    CREATE TABLE books (
        id bigint primary key,
        title text,
        pages bigint,
        owner text,
        notes text
    );
    INSERT INTO books VALUES
        (1, 'Dune',   412, 'ada@example.com', 'ada''s copy'),
        (2, 'Emma',   474, 'bob@example.com', 'bob''s copy'),
        (3, 'Ilium',  576, 'ada@example.com', 'also ada''s'),
        (4, 'Ubik',   224, 'bob@example.com', NULL);
    CREATE TABLE arrivals (
        id bigint generated by default as identity primary key,
        what text
    );
";

/// Every write trait over the whole of `books`.
fn books() -> Attrs {
    config(&[(CFG_TABLE, json!("books"))])
}

#[tokio::test]
async fn each_write_tool_describes_the_table_it_may_change() -> Result<()> {
    let env = Env::new().await?;

    // An insert takes the row itself, flat, with the fields as properties —
    // including the primary key, which this table has no default for.
    let insert = &env.tools("insert_row", &books())[0];
    assert_eq!(insert.name, "insert_into_books");
    let props = insert.parameters["properties"].as_object().unwrap();
    assert_eq!(props.len(), 5);
    assert_eq!(props["title"]["type"], json!(["string", "null"]));
    assert_eq!(insert.parameters["additionalProperties"], json!(false));
    // No `required` list: this crate cannot see column defaults, and a schema
    // that demanded every NOT NULL column would make the model invent values the
    // database was going to fill in.
    assert!(insert.parameters.get("required").is_none());

    // An update takes a `where` and a `set`, both required, and cannot set the
    // primary key — moving a row's identity is not an edit.
    let update = &env.tools("update_rows", &books())[0];
    assert_eq!(update.name, "update_books");
    assert_eq!(update.parameters["required"], json!(["where", "set"]));
    let settable = update.parameters["properties"]["set"]["properties"]
        .as_object()
        .unwrap();
    assert!(!settable.contains_key("id"), "the key is not settable");
    assert!(settable.contains_key("title"));
    // …while the filter may name any field of the table, including the key.
    let filterable = update.parameters["properties"]["where"]["properties"]
        .as_object()
        .unwrap();
    assert!(filterable.contains_key("id"));
    assert!(update.description.contains("20"), "{}", update.description);

    // A delete takes a `where` and nothing else, and says so both in the schema
    // and in the words the model reads when it is choosing.
    let delete = &env.tools("delete_rows", &books())[0];
    assert_eq!(delete.name, "delete_from_books");
    assert_eq!(delete.parameters["required"], json!(["where"]));
    assert_eq!(
        delete.parameters["properties"].as_object().unwrap().len(),
        1
    );
    assert!(
        delete.description.contains("cannot be undone"),
        "{}",
        delete.description
    );
    Ok(())
}

#[tokio::test]
async fn an_agents_insert_fires_the_tables_own_trigger() -> Result<()> {
    // The whole reason this crate sits above the row layer: a trait's write is
    // the *same* write an API caller makes, so everything hung off a write —
    // coercion, validation, and the table's own triggers — happens.
    let env = Env::with_schema(SCHEMA_WITH_AUDIT)
        .await?
        .with_triggers(builtin_actions()?)?;
    save_trigger(
        &env.catalog,
        &env.dispatcher.as_ref().unwrap().registry(),
        &Trigger::new("note_arrival", EventKind::Insert, "insert_row")
            .on("books")
            .config("table", "arrivals")
            .config("values", json!({ "what": "row.title" })),
    )
    .await?;
    env.reload_triggers().await?;

    let result = env
        .call(
            "insert_row",
            &books(),
            json!({"id": 5, "title": "Solaris", "pages": 204, "owner": "ada@example.com"}),
            &RunCaller::system(),
        )
        .await?;
    // The stored row comes back whole, so the model can refer to what it made.
    assert_eq!(result["inserted"]["id"], json!(5));
    assert_eq!(result["inserted"]["notes"], json!(null));

    let arrivals = env.rows("arrivals").await?;
    assert_eq!(arrivals.len(), 1, "{arrivals:?}");
    assert_eq!(arrivals[0]["what"], json!("Solaris"));

    // The type rules apply too: a text value in a bigint column is refused by
    // name, in words the model can act on, rather than reaching the database.
    let err = env
        .call(
            "insert_row",
            &books(),
            json!({"id": 6, "title": "Roadside Picnic", "pages": "many"}),
            &RunCaller::system(),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("pages"), "{err}");
    Ok(())
}

#[tokio::test]
async fn a_write_reaches_only_the_rows_the_caller_may_reach() -> Result<()> {
    // With the engine: a sub-floor write is checked **on the row**, existing and
    // proposed, and a proposed row is not something a SQL predicate can be asked
    // about — so this path is reified whether or not the formula translates.
    let env = Env::new().await?.with_engine();
    env.own("books", "owner === user.email").await?;
    let ada = as_user("ada@example.com");
    let bob = as_user("bob@example.com");

    // Ada renames her own book…
    let result = env
        .call(
            "update_rows",
            &books(),
            json!({"where": {"title": "Dune"}, "set": {"title": "Dune (1965)"}}),
            &ada,
        )
        .await?;
    assert_eq!(result["updated"], json!(1));
    assert_eq!(result["ids"], json!([1]));

    // …and cannot touch Bob's, which she cannot see: no row matched, so nothing
    // was changed and nothing about `Emma` was disclosed.
    let result = env
        .call(
            "update_rows",
            &books(),
            json!({"where": {"title": "Emma"}, "set": {"title": "Emma (1815)"}}),
            &ada,
        )
        .await?;
    assert_eq!(result["updated"], json!(0));
    assert_eq!(
        row_titles(&env.rows("books").await?),
        ["Dune (1965)", "Emma", "Ilium", "Ubik"]
    );

    // An update that would move a row out of her own ownership is refused even
    // though every value in it is valid — §6's WITH CHECK, at runtime.
    let err = env
        .call(
            "update_rows",
            &books(),
            json!({"where": {"id": 1}, "set": {"owner": "bob@example.com"}}),
            &ada,
        )
        .await
        .unwrap_err();
    assert!(
        err.to_string().contains("out of what you may reach"),
        "{err}"
    );

    // Deleting divides the same way: Bob deletes his, Ada's are untouched.
    let result = env
        .call(
            "delete_rows",
            &books(),
            json!({"where": {"pages": {"lt": 300}}}),
            &bob,
        )
        .await?;
    assert_eq!(result["deleted"], json!(1));
    assert_eq!(
        row_titles(&env.rows("books").await?),
        ["Dune (1965)", "Emma", "Ilium"]
    );

    // And an insert is checked against the row proposed: Ada may add her own
    // book and may not add one of Bob's.
    env.call(
        "insert_row",
        &books(),
        json!({"id": 7, "title": "Hyperion", "owner": "ada@example.com"}),
        &ada,
    )
    .await?;
    let err = env
        .call(
            "insert_row",
            &books(),
            json!({"id": 8, "title": "Persuasion", "owner": "bob@example.com"}),
            &ada,
        )
        .await
        .unwrap_err();
    assert!(
        err.to_string().contains("outside what you may write"),
        "{err}"
    );

    // A table with **no** ownership formula denies a caller below its floors
    // outright, rather than falling through to an unguarded write. An insert
    // says so in the write's own words; a delete refuses one step earlier,
    // because selecting the rows to delete is a read this caller may not make —
    // and either way the table is untouched.
    let plain = Env::new().await?.with_engine();
    let ada_alone = as_user("ada@example.com");
    let err = plain
        .call(
            "insert_row",
            &books(),
            json!({"id": 9, "title": "Hyperion"}),
            &ada_alone,
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("may not write"), "{err}");
    let err = plain
        .call(
            "delete_rows",
            &books(),
            json!({"where": {"id": 1}}),
            &ada_alone,
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("may not read"), "{err}");
    assert_eq!(plain.rows("books").await?.len(), 4);
    Ok(())
}

#[tokio::test]
async fn the_allow_list_bounds_what_may_be_set_but_not_what_may_be_matched() -> Result<()> {
    let env = Env::new().await?;
    let cfg = config(&[
        (CFG_TABLE, json!("books")),
        (CFG_FIELDS, json!(["notes", "pages"])),
    ]);

    // Matching on a field outside the list is fine — that is how a model
    // addresses a row it may not rename…
    let result = env
        .call(
            "update_rows",
            &cfg,
            json!({"where": {"title": "Ubik"}, "set": {"notes": "shelved"}}),
            &RunCaller::system(),
        )
        .await?;
    assert_eq!(result["updated"], json!(1));

    // …but setting one is refused by name, with the fields that are allowed
    // listed, because a model that cannot read what it got wrong cannot fix it.
    let err = env
        .call(
            "update_rows",
            &cfg,
            json!({"where": {"id": 1}, "set": {"title": "Doon"}}),
            &RunCaller::system(),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("`title`"), "{err}");
    assert!(err.to_string().contains("pages, notes"), "{err}");

    // The same for an insert, which is the row itself.
    let err = env
        .call(
            "insert_row",
            &cfg,
            json!({"id": 9, "pages": 100}),
            &RunCaller::system(),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("`id`"), "{err}");
    Ok(())
}

#[tokio::test]
async fn a_write_without_a_filter_is_refused_and_too_many_rows_change_nothing() -> Result<()> {
    let env = Env::new().await?;
    let caller = RunCaller::system();
    let before = row_titles(&env.rows("books").await?);

    // No `where` at all, and an empty one, are both "every row of the table",
    // and neither is something an omitted argument may ask for.
    for args in [json!({}), json!({"where": {}})] {
        let err = env
            .call("delete_rows", &books(), args.clone(), &caller)
            .await
            .unwrap_err();
        assert!(err.to_string().contains("`where` is required"), "{err}");
        let mut args = args;
        args["set"] = json!({"notes": "everything"});
        let err = env
            .call("update_rows", &books(), args, &caller)
            .await
            .unwrap_err();
        assert!(err.to_string().contains("`where` is required"), "{err}");
    }
    // An update with a filter but nothing to set is equally a mistake.
    let err = env
        .call(
            "update_rows",
            &books(),
            json!({"where": {"id": 1}}),
            &caller,
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("`set` is required"), "{err}");

    // A filter that matches more rows than the ceiling changes **nothing** and
    // says how to recover: a half-applied bulk write is the one outcome nobody
    // can tell apart from a whole one.
    let bounded = config(&[(CFG_TABLE, json!("books")), (CFG_MAX_ROWS, json!(2))]);
    let err = env
        .call(
            "delete_rows",
            &bounded,
            json!({"where": {"pages": {"gt": 1}}}),
            &caller,
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("more than 2 rows"), "{err}");
    assert!(err.to_string().contains("nothing was changed"), "{err}");
    assert_eq!(row_titles(&env.rows("books").await?), before);

    // Exactly the ceiling is allowed, and matching nothing is a count of zero
    // rather than a failure — an idempotent call must not look broken the second
    // time it is made.
    let result = env
        .call(
            "delete_rows",
            &bounded,
            json!({"where": {"pages": {"lt": 420}}}),
            &caller,
        )
        .await?;
    assert_eq!(result["deleted"], json!(2));
    let result = env
        .call(
            "delete_rows",
            &bounded,
            json!({"where": {"pages": {"lt": 420}}}),
            &caller,
        )
        .await?;
    assert_eq!(result["deleted"], json!(0));
    Ok(())
}

#[tokio::test]
async fn a_write_trait_the_catalog_contradicts_is_refused_on_save() -> Result<()> {
    let env = Env::new().await?;
    for trait_ in ["insert_row", "update_rows", "delete_rows"] {
        env.check(trait_, &books()).await?;
        // A table that is not there.
        let err = env
            .check(trait_, &config(&[(CFG_TABLE, json!("shelves"))]))
            .await
            .unwrap_err();
        assert!(err.to_string().contains("shelves"), "{trait_}: {err}");
        // A configuration with no table at all.
        assert!(env.check(trait_, &Attrs::new()).await.is_err(), "{trait_}");
    }
    // A field the table does not have, on the two traits that take a list.
    for trait_ in ["insert_row", "update_rows"] {
        let err = env
            .check(
                trait_,
                &config(&[
                    (CFG_TABLE, json!("books")),
                    (CFG_FIELDS, json!(["title", "athor"])),
                ]),
            )
            .await
            .unwrap_err();
        assert!(err.to_string().contains("athor"), "{trait_}: {err}");
    }
    // An allow-list that leaves an update with nothing it could change is a
    // configuration mistake, not a very safe grant.
    let err = env
        .check(
            "update_rows",
            &config(&[(CFG_TABLE, json!("books")), (CFG_FIELDS, json!(["id"]))]),
        )
        .await
        .unwrap_err();
    assert!(err.to_string().contains("changeable"), "{err}");
    Ok(())
}

#[tokio::test]
async fn an_agent_reads_and_then_changes_its_table_through_a_whole_run() -> Result<()> {
    // Phase 3's "done when", for the write half: an agent given a read trait and
    // a write trait over the same table looks something up and then changes it,
    // with both exchanges in the run's context and both bounded by what the
    // person chatting may reach.
    let env = Env::new().await?.with_engine();
    env.own("books", "owner === user.email").await?;
    let agent = Agent::new("librarian", "main")
        .system_prompt("You look after the library.")
        .with_trait(EnabledTrait::new("query_table").config(CFG_TABLE, "books"))
        .with_trait(
            EnabledTrait::new("update_rows")
                .config(CFG_TABLE, "books")
                .config(CFG_FIELDS, json!(["notes"])),
        );
    save_agent(&env.catalog, &env.registry, &agent).await?;

    let provider = Arc::new(FakeProvider::new([
        Reply::calls("query_books", json!({"where": {"title": "Dune"}})),
        Reply::calls(
            "update_books",
            json!({"where": {"id": 1}, "set": {"notes": "signed first edition"}}),
        ),
        Reply::says("Noted on Dune."),
    ]));
    let engine = env.evaluator.clone().expect("the engine");
    let runner = Runner::new(
        &env.catalog,
        &env.registry,
        &agent,
        provider.clone(),
        as_user("ada@example.com"),
    )
    .with_evaluator(&engine);
    let (run, conclusion) = runner.start("note that my copy of Dune is signed").await?;
    assert_eq!(conclusion.answer(), Some("Noted on Dune."));

    // Both tools were offered, under the names their configurations derive.
    let requests = provider.requests();
    let offered: Vec<&str> = requests[0].tools.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(offered, vec!["query_books", "update_books"]);

    // The change happened, on the row the query found and no other.
    let books = env.rows("books").await?;
    let dune = books.iter().find(|b| b["id"] == json!(1)).unwrap();
    assert_eq!(dune["notes"], json!("signed first edition"));
    let emma = books.iter().find(|b| b["id"] == json!(2)).unwrap();
    assert_eq!(emma["notes"], json!("bob's copy"));

    // And the whole exchange is on the run, tool results included.
    let state = sc_agent::load_run(&env.catalog, run.id)
        .await?
        .expect("the run row")
        .agent_loop()?;
    let results: Vec<(String, Json)> = state
        .messages()
        .iter()
        .filter_map(|m| match m {
            sc_llm::LlmMessage::ToolResult { content, name, .. } => Some((
                name.clone(),
                serde_json::from_str(content).unwrap_or(Json::Null),
            )),
            _ => None,
        })
        .collect();
    assert_eq!(results.len(), 2);
    assert_eq!(results[0].0, "query_books");
    assert_eq!(results[1].0, "update_books");
    assert_eq!(results[1].1["updated"], json!(1));
    Ok(())
}
