//! The physical schema as the database sees it, plus the schema-change requests
//! that mutate it.
//!
//! Two directions:
//!
//! - [`PhysicalTable`] and friends are the *result* of
//!   [`introspect`](crate::DatabaseDriver::introspect): the live shape of a
//!   table read from `information_schema`. Per the goals there is no table
//!   discovery step — as soon as a database is connected, every table is usable,
//!   so introspection is the source of truth and stored metadata is only an
//!   optional overlay (§5, §9).
//! - [`SchemaChange`] is the *input* to
//!   [`apply_schema`](crate::DatabaseDriver::apply_schema): a single create/drop
//!   table or add/drop column. Notably, creating a table does **not** invent an
//!   `id` column — key fields are declared explicitly like any other (§5).
//!
//! Both model composite primary keys and foreign keys to non-primary-key
//! columns, which the goals require, so keys are always `Vec<String>` and never
//! "the id column".

use serde::{Deserialize, Serialize};

/// A table exactly as it exists in the database, as returned by introspection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PhysicalTable {
    /// The table name (unqualified).
    pub name: String,
    /// The containing schema namespace (e.g. `public`), when the backend has
    /// one. `None` means the driver's default schema.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// Columns in declaration order.
    pub columns: Vec<Column>,
    /// Names of the columns forming the primary key, in key order. Empty when
    /// the table has no primary key; more than one entry is a composite key.
    #[serde(default)]
    pub primary_key: Vec<String>,
    /// Foreign-key constraints declared on this table.
    #[serde(default)]
    pub foreign_keys: Vec<ForeignKey>,
}

/// One column of a [`PhysicalTable`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Column {
    /// The column name.
    pub name: String,
    /// The backend's own type name (e.g. `text`, `int8`, `timestamptz`). Mapping
    /// this to a rich/basic Saltcorn type is the type layer's job (§6), not the
    /// driver's.
    pub sql_type: String,
    /// Whether the column accepts `NULL`.
    pub nullable: bool,
    /// How the column fills itself in when a write omits it, if it does.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated: Option<ColumnGenerator>,
}

/// How a column supplies a value when a write does not give it one.
///
/// One enum rather than a `default: Option<String>` beside an `identity: bool`,
/// because a column has **one** of these and never both: Postgres refuses an
/// identity column that also carries a default. The two are the same fact —
/// "the database fills this in" — spelled differently, and the pair that can
/// express nonsense is the pair somebody eventually writes.
///
/// This is what a primary key needs to be usable. A key column nobody can supply
/// a value for is a table no form can insert into, and the goals are explicit
/// that no `id` column is invented — so the key the admin declares has to
/// generate itself, or "create the key field yourself" would mean "and now type
/// a key by hand for every row".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "generator", content = "sql")]
pub enum ColumnGenerator {
    /// The backend numbers the column itself — Postgres's `GENERATED BY DEFAULT
    /// AS IDENTITY`.
    ///
    /// *By default*, never *always*: an explicit value is still accepted, which
    /// is what restoring a backup and importing a CSV that carries its own `id`
    /// column both depend on.
    Identity,
    /// A column default, rendered as backend SQL (`gen_random_uuid()`, `now()`,
    /// `false`).
    Default(String),
}

/// One column of a prepared statement's result, as reported by
/// [`describe`](crate::DatabaseDriver::describe).
///
/// Deliberately not a [`Column`]: a result column has no nullability the backend
/// will commit to and no default — an expression is not a column of a table.
/// What it has is a name and a type, which is exactly what typing a custom
/// query's response needs. As with [`Column::sql_type`], the type is the
/// backend's own name for it; mapping it to a Saltcorn type is the type layer's
/// job (§6), not the driver's.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DescribedColumn {
    /// The column's output name (an alias, or whatever the backend derived).
    pub name: String,
    /// The backend's own type name (e.g. `text`, `int8`, `numeric`).
    pub sql_type: String,
}

/// A foreign-key constraint. Local `columns` reference `referenced_columns` of
/// `referenced_table`, positionally. The referenced columns need not be a
/// primary key (the goals require FKs to non-PK columns).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ForeignKey {
    /// Local columns constrained by this key, in order.
    pub columns: Vec<String>,
    /// The referenced table's (unqualified) name.
    pub referenced_table: String,
    /// The referenced columns, positionally matching `columns`.
    pub referenced_columns: Vec<String>,
}

/// A single schema mutation applied by
/// [`apply_schema`](crate::DatabaseDriver::apply_schema).
///
/// Kept deliberately minimal for the MVP: create/drop a table and add/drop a
/// column. Indexes, constraints, and alterations arrive as the design demands
/// them. Creating a table adds **no** implicit primary-key column.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "op")]
pub enum SchemaChange {
    /// Create a new table with the given columns and optional primary key.
    CreateTable {
        /// The new table's name.
        name: String,
        /// Column definitions, in the order they should be declared.
        columns: Vec<ColumnDef>,
        /// Names of columns forming the primary key (empty for none; more than
        /// one for a composite key). Each must appear in `columns`.
        #[serde(default)]
        primary_key: Vec<String>,
        /// Create the table **without write-ahead logging** — Postgres's
        /// `UNLOGGED` (see
        /// [`unlogged_tables`](crate::DbCapabilities::unlogged_tables)).
        ///
        /// Only ever a request: a backend that does not advertise the capability
        /// creates an ordinary table, because the flag is a performance
        /// property and never a correctness one. Ask for it only where losing
        /// every row on an unclean shutdown is acceptable — the session table
        /// (§7.2) is the case it exists for.
        #[serde(default)]
        unlogged: bool,
    },
    /// Drop an existing table.
    DropTable {
        /// The table to drop.
        name: String,
        /// Suppress an error when the table does not exist.
        #[serde(default)]
        if_exists: bool,
    },
    /// Add a column to an existing table.
    AddColumn {
        /// The table to alter.
        table: String,
        /// The column to add.
        column: ColumnDef,
    },
    /// Drop a column from an existing table.
    DropColumn {
        /// The table to alter.
        table: String,
        /// The column to drop.
        column: String,
        /// Suppress an error when the column does not exist.
        #[serde(default)]
        if_exists: bool,
    },
    /// Make these columns the table's primary key, replacing the key it has.
    ///
    /// A table is created with the key its columns declare, and a table created
    /// with none has none — the goals are explicit that no `id` column is
    /// invented (§5). So the key has to be settable **afterwards**, or a table
    /// would be stuck without one for as long as it existed: the admin adds the
    /// key field to a table that has no key, exactly as they add any other
    /// field, and this is the half of that which the columns cannot express.
    ///
    /// Replacing rather than adding, because "add a second key" is not a thing a
    /// table can have: a composite key grown one column at a time is a sequence
    /// of whole keys, each replacing the last.
    SetPrimaryKey {
        /// The table to alter.
        table: String,
        /// The columns forming the new key, in key order. Each must be a column
        /// of the table, and each must be `NOT NULL`.
        columns: Vec<String>,
    },
    /// Give an existing column a [generator](ColumnGenerator), or take away the
    /// one it has.
    ///
    /// The other half of [`SetPrimaryKey`](SchemaChange::SetPrimaryKey). A key
    /// declared when the column is created gets its generator in the
    /// [`ColumnDef`]; a key switched on afterwards — which is the ordinary way a
    /// table gets one, since none is invented — has a column that already exists,
    /// and this is what turns it into a key that fills itself in. Without it,
    /// ticking the box would produce a key every writer has to type by hand.
    SetColumnGenerator {
        /// The table to alter.
        table: String,
        /// The column to alter.
        column: String,
        /// The generator to give it; `None` removes whatever it has.
        generator: Option<ColumnGenerator>,
    },
}

/// The definition of a column to create, used inside a [`SchemaChange`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ColumnDef {
    /// The column name.
    pub name: String,
    /// The backend SQL type for the column (e.g. `text`, `uuid`, `int8`).
    pub sql_type: String,
    /// Whether the column accepts `NULL`.
    pub nullable: bool,
    /// How the column should fill itself in when a write omits it, if at all.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated: Option<ColumnGenerator>,
    /// Whether a `UNIQUE` constraint should be attached to the column.
    #[serde(default)]
    pub unique: bool,
    /// The column this one references, if it is a foreign key.
    ///
    /// Single-column only, which is what a `REFERENCES` clause on the column
    /// itself can express. A composite foreign key is a table-level constraint
    /// and will need its own [`SchemaChange`] when something needs one; nothing
    /// does yet, and inventing the general form here would mean two ways to
    /// declare the simple case.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub references: Option<ColumnRef>,
}

/// A reference to one column of one table — the target of a single-column
/// foreign key (see [`ColumnDef::references`]).
///
/// The target need not be a primary key; it must only be unique, which the
/// goals require (a `Key` field "holds the value of a referenced field, not
/// necessarily the target PK").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ColumnRef {
    /// The referenced table's (unqualified) name.
    pub table: String,
    /// The referenced column.
    pub column: String,
}

impl ColumnDef {
    /// A nullable column of the given name and SQL type, with no default and no
    /// unique constraint — the base to tweak fields on.
    pub fn new(name: impl Into<String>, sql_type: impl Into<String>) -> Self {
        ColumnDef {
            name: name.into(),
            sql_type: sql_type.into(),
            nullable: true,
            generated: None,
            unique: false,
            references: None,
        }
    }

    /// Mark this column `NOT NULL`.
    pub fn not_null(mut self) -> Self {
        self.nullable = false;
        self
    }

    /// Attach a `UNIQUE` constraint to this column.
    pub fn unique(mut self) -> Self {
        self.unique = true;
        self
    }

    /// Set the column default (backend SQL).
    pub fn default(mut self, sql: impl Into<String>) -> Self {
        self.generated = Some(ColumnGenerator::Default(sql.into()));
        self
    }

    /// Have the backend number the column — see
    /// [`ColumnGenerator::Identity`].
    pub fn identity(mut self) -> Self {
        self.generated = Some(ColumnGenerator::Identity);
        self
    }

    /// Make this column a foreign key onto `table`.`column`.
    pub fn references(mut self, table: impl Into<String>, column: impl Into<String>) -> Self {
        self.references = Some(ColumnRef {
            table: table.into(),
            column: column.into(),
        });
        self
    }
}
