//! The concrete admin-API handlers (technical design §13.1, §7).
//!
//! [`admin_handlers`] builds the [`HandlerRegistry`] that the admin
//! [`EndpointSet`](sc_api::admin_endpoints) dispatches against: one entry per
//! endpoint `name`, each closing over a shared [`Catalog`]. The handlers are the
//! server-side half of the typed API — bootstrap/auth, the table & field catalog,
//! row CRUD, and user management — and they stay free of HTTP plumbing: they read
//! a [`HandlerCtx`] and return a [`HandlerResponse`], deferring cookies/sessions
//! to the dispatcher via [`SessionAction`](crate::SessionAction).
//!
//! Data crosses the wire as plain JSON. The row endpoints are thin wrappers over
//! [`sc_api::rows`], the shared row-CRUD layer an application's REST API runs
//! too — the admin API is not a privileged special case, it is the same
//! machinery (design §13.1). A row is addressed by its single-column primary key
//! (composite keys are post-MVP), and `createTable` gives a new table a default
//! identity `id` key so the row editor has something to address.

use std::collections::BTreeMap;
use std::sync::Arc;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use bytes::Bytes;
use sc_api::auth::{credentials, user_summary_json};
use sc_api::rows::{self, require_object};
use sc_app::{
    ApiConfig, AppId, Application, CspPolicy, FrameworkRef, StaticDir, app_source_from_config,
    applications_using_file_store, delete_application, framework_config_spec,
    framework_default_csp, list_applications, load_application, registered_framework_info,
    require_scaffoldable, save_application, scaffold_app,
};
use sc_auth::{
    COL_EMAIL, COL_ID, COL_ROLE, USERS_TABLE, User, any_user_exists, authenticate_admin,
    create_first_user, create_user,
};
use sc_catalog::{
    Attrs, Catalog, DataField, FileStoreId, TableId, connect_file_store_def, delete_file_store,
    list_file_stores, load_file_store, load_file_store_by_name, resolve_options, save_file_store,
};
use sc_error::{Error, Result};
use sc_files::{
    Entry, FileMeta, FileStoreDef, FileStoreDefId, backend_config_spec, check_access,
    effective_min_role, filter_visible, registered_backends,
};
use sc_query::{Expr, Projection, Select, Source, Statement};
use sc_types::{FormField, TypeRef};
use serde_json::{Map, Value as Json, json};

use crate::apps::{AppMounts, build_and_mount};
use crate::handler::{HandlerRegistry, HandlerResponse};

/// The SQL type of the default primary key `createTable` gives a new table: a
/// database-generated identity so rows can be inserted without supplying an id,
/// while still allowing an explicit one.
const DEFAULT_PK_SQL_TYPE: &str = "bigint generated by default as identity";

/// Build the registry of admin handlers over a shared [`Catalog`] and the live
/// [`AppMounts`] registry.
///
/// The names match the [`Endpoint`](sc_api::Endpoint) `name`s in
/// [`admin_endpoints`](sc_api::admin_endpoints); the router resolves each
/// endpoint's [`HandlerRef::Named`](sc_api::HandlerRef) here at dispatch time.
///
/// `apps` is the **same** live handle the router resolves requests against, so
/// the application `build`/`delete` handlers mount and unmount apps that start
/// serving (or stop) with no restart (§13.2). For an admin-only server pass an
/// [`AppMounts`] with the catalog attached ([`AppMounts::new`]); the application
/// CRUD handlers still work, and a build simply mounts an app no subdomain routes
/// to until a `--base-domain` is configured.
pub fn admin_handlers(catalog: Arc<Catalog>, apps: Arc<AppMounts>) -> HandlerRegistry {
    let mut reg = HandlerRegistry::new();

    // --- bootstrap & auth ---------------------------------------------------

    reg.register("authStatus", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let exists = any_user_exists(&catalog).await?;
                let current = ctx.user.as_ref().map_or(Json::Null, user_summary_json);
                Ok(HandlerResponse::ok(json!({
                    "any_user_exists": exists,
                    "current_user": current,
                })))
            }
        }
    });

    reg.register("createFirstUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                let user = create_first_user(&catalog, &email, &password).await?;
                // Log the new admin straight in — they came from the bootstrap
                // screen and expect to land in the app.
                let body = user_summary_json(&user);
                Ok(HandlerResponse::start_session(user, body))
            }
        }
    });

    reg.register("login", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                match authenticate_admin(&catalog, &email, &password).await? {
                    Some(user) => {
                        let body = user_summary_json(&user);
                        Ok(HandlerResponse::start_session(user, body))
                    }
                    None => Err(Error::auth("invalid credentials")),
                }
            }
        }
    });

    reg.register("logout", |_ctx| async {
        Ok(HandlerResponse::end_session(json!({ "ok": true })))
    });

    // --- catalog: tables & fields ------------------------------------------

    reg.register("listTables", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let tables = catalog.tables()?;
                let out: Vec<Json> = tables
                    .iter()
                    .filter(|t| !t.is_system())
                    .map(|t| json!({ "name": t.name }))
                    .collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createTable", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?;
                let id = DataField::plain("id", TypeRef::from_sql_type(DEFAULT_PK_SQL_TYPE))
                    .required()
                    .primary_key();
                let table = catalog.create_table(name, &[id]).await?;
                Ok(HandlerResponse::ok(json!({ "name": table.name })).with_status(201))
            }
        }
    });

    reg.register("listFields", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let out: Vec<Json> = table.fields.iter().map(field_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createField", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = ctx.path_param("table")?.to_owned();
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?.to_owned();
                let sql_type = non_empty_str_field(obj, "sql_type")?;
                let nullable = bool_field(obj, "nullable")?;
                let mut field = DataField::plain(&name, TypeRef::from_sql_type(sql_type));
                if !nullable {
                    field = field.required();
                }
                let table = catalog.create_field(&table, &field).await?;
                let created = table
                    .field(&name)
                    .ok_or_else(|| Error::msg(format!("field `{name}` missing after create")))?;
                Ok(HandlerResponse::ok(field_json(created)).with_status(201))
            }
        }
    });

    // --- row CRUD -----------------------------------------------------------

    reg.register("listRows", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                Ok(HandlerResponse::ok(
                    rows::list_rows(&catalog, &table).await?,
                ))
            }
        }
    });

    reg.register("createRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let row = rows::create_row(&catalog, &table, &ctx.body).await?;
                Ok(HandlerResponse::ok(row).with_status(201))
            }
        }
    });

    reg.register("updateRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                let row = rows::update_row(&catalog, &table, id, &ctx.body).await?;
                Ok(HandlerResponse::ok(row))
            }
        }
    });

    reg.register("deleteRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                Ok(HandlerResponse::ok(
                    rows::delete_row(&catalog, &table, id).await?,
                ))
            }
        }
    });

    // --- files (file manager) ----------------------------------------------

    // The **union** of defined and connected stores, which neither alone gets
    // right. Listing only the connected ones (what the MVP did) hides a store
    // whose directory has been unmounted — exactly the store the admin needs to
    // find and repoint. Listing only the definitions hides a store connected by
    // `--file-store`, which has no row but is real and browsable, so a developer
    // running with the flag would see an empty list. Stored stores come first,
    // then any connected store with no definition, which reports a null id to
    // say "there is nothing here to edit".
    reg.register("listFileStores", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let defs = list_file_stores(&catalog).await?;
                let mut out: Vec<Json> = defs
                    .iter()
                    .map(|def| file_store_json(&catalog, def))
                    .collect::<Result<_>>()?;

                for name in catalog.file_store_names()? {
                    if !defs.iter().any(|def| def.name == name) {
                        out.push(ephemeral_file_store_json(&catalog, &name)?);
                    }
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createFileStore", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                // A create mints a fresh id; the body carries everything else.
                let def = file_store_from_body(FileStoreDefId::new(), &ctx.body)?;
                save_file_store(&catalog, &def).await?;
                // Connect it straight away so the admin finds out now whether the
                // directory is actually reachable, rather than on next boot. A
                // failure is deliberately *not* an error: the definition is saved
                // and valid, and the reason is reported in the response so the UI
                // can show "saved, but not connected: <why>".
                let _ = connect_file_store_def(&catalog, &def);
                Ok(HandlerResponse::ok(file_store_json(&catalog, &def)?).with_status(201))
            }
        }
    });

    reg.register("updateFileStore", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let id = parse_file_store_id(ctx.path_param("id")?)?;
                let existing = load_file_store(&catalog, id)
                    .await?
                    .ok_or_else(|| Error::not_found(format!("no file store with id {id:?}")))?;
                // The id is the path's, not the body's — the row's identity is
                // not something a payload gets to reassign.
                let def = file_store_from_body(id, &ctx.body)?;
                save_file_store(&catalog, &def).await?;

                // A rename leaves the old handle connected under the old name,
                // still serving, because saving deliberately does not touch the
                // registry (§1.1). Disconnect it here — this is the one place
                // that knows both the before and the after.
                if existing.name != def.name {
                    catalog.disconnect_file_store(&existing.name)?;
                }
                // Reconnect under the current name so an edited path takes
                // effect immediately, with no restart (§1.3).
                let _ = connect_file_store_def(&catalog, &def);
                Ok(HandlerResponse::ok(file_store_json(&catalog, &def)?))
            }
        }
    });

    reg.register("deleteFileStore", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let id = parse_file_store_id(ctx.path_param("id")?)?;
                let existing = load_file_store(&catalog, id)
                    .await?
                    .ok_or_else(|| Error::not_found(format!("no file store with id {id:?}")))?;

                // Collect the references `sc-catalog` cannot see. Applications
                // live a crate above it, so this is the one place that can put
                // both halves of the check together — without it a store still
                // serving an app's source could be deleted out from under it.
                let app_refs = applications_using_file_store(&catalog, &existing.name).await?;
                let deleted = delete_file_store(&catalog, id, &app_refs).await?;

                // Removing the row is the definition's end; disconnecting is what
                // stops it serving. Both are needed — the file manager would
                // otherwise go on browsing a store the admin had just deleted.
                if deleted {
                    catalog.disconnect_file_store(&existing.name)?;
                }
                Ok(HandlerResponse::ok(json!({ "deleted": deleted })))
            }
        }
    });

    reg.register("listFileStoreBackends", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let mut out = Vec::new();
                for name in registered_backends() {
                    let spec = resolve_options(&catalog, backend_config_spec(&name)?).await?;
                    out.push(json!({
                        "name": name,
                        "config_spec": spec.iter().map(form_field_json).collect::<Vec<_>>(),
                    }));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("browseFiles", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                // `dir` is optional-ish: an absent/empty value lists the root.
                let dir = obj.get("dir").and_then(Json::as_str).unwrap_or("");
                let role = caller_role(&ctx);
                check_access(store.as_ref(), floor, dir, role).await?;

                // The directory's own floor covers every child, so it is
                // computed once here rather than re-walking the ancestors for
                // each entry.
                let dir_floor = effective_min_role(store.as_ref(), floor, dir).await?;
                let entries = store.list(dir).await?;
                // Filtered, not refused: a readable directory may hold entries
                // the caller cannot open, and listing their names leaks exactly
                // what the rule was set to hide.
                let visible = filter_visible(store.as_ref(), dir_floor, entries, role).await?;
                let out: Vec<Json> = visible.iter().map(entry_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("readFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?;
                check_access(store.as_ref(), floor, path, caller_role(&ctx)).await?;
                let bytes = store.read(path).await?;
                // Always provide base64 (for binary download); add a decoded
                // `text` when the bytes are valid UTF-8 (for the text editor).
                let text = std::str::from_utf8(&bytes)
                    .ok()
                    .map(|s| Json::String(s.to_owned()))
                    .unwrap_or(Json::Null);
                Ok(HandlerResponse::ok(json!({
                    "path": path,
                    "size": bytes.len(),
                    "base64": BASE64.encode(&bytes),
                    "text": text,
                })))
            }
        }
    });

    reg.register("writeFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;
                let data = file_body_bytes(obj)?;
                let size = data.len();
                store.write(&path, data).await?;
                Ok(HandlerResponse::ok(file_entry_written_json(&path, size)).with_status(201))
            }
        }
    });

    reg.register("makeDirectory", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;
                store.mkdir(&path).await?;
                Ok(HandlerResponse::ok(directory_entry_json(&path)).with_status(201))
            }
        }
    });

    reg.register("deleteFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;
                let deleted = store.delete(&path).await?;
                Ok(HandlerResponse::ok(json!({ "deleted": deleted })))
            }
        }
    });

    reg.register("renameFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let from = non_empty_str_field(obj, "from")?.to_owned();
                let to = non_empty_str_field(obj, "to")?.to_owned();
                // Both ends are checked: reading from a restricted place and
                // writing into one are each things the rule governs, and a move
                // does both.
                let role = caller_role(&ctx);
                check_access(store.as_ref(), floor, &from, role).await?;
                check_access(store.as_ref(), floor, &to, role).await?;
                store.rename(&from, &to).await?;
                Ok(HandlerResponse::ok(entry_json(&renamed_entry(&to))))
            }
        }
    });

    // Served by the `/upload/{store}/{*path}` route rather than a typed endpoint
    // (the endpoint model has no bytes shape), but registered here like any
    // other handler so it reaches the same catalog and the same access rule.
    // Routing around the `EndpointSet` must not mean routing around those.
    reg.register("uploadFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let path = ctx.path_param("path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;
                let data = ctx.raw_body()?.clone();
                let size = data.len();
                store.write(&path, data).await?;
                Ok(HandlerResponse::ok(file_entry_written_json(&path, size)).with_status(201))
            }
        }
    });

    reg.register("getFileMeta", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;
                let meta = store.get_meta(&path).await?;
                let effective = effective_min_role(store.as_ref(), floor, &path).await?;
                Ok(HandlerResponse::ok(file_meta_json(&path, &meta, effective)))
            }
        }
    });

    reg.register("setFileMeta", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let name = ctx.path_param("store")?.to_owned();
                let (store, floor) = resolve_store(&catalog, &name).await?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                check_access(store.as_ref(), floor, &path, caller_role(&ctx)).await?;

                let min_role = optional_role(obj, "min_role")?;
                let attributes = match obj.get("attributes") {
                    Some(Json::Object(o)) => o
                        .iter()
                        .map(|(k, v)| {
                            let text = v.as_str().map(str::to_owned).ok_or_else(|| {
                                Error::invalid(format!("attribute `{k}` must be a string"))
                            })?;
                            Ok((k.clone(), text))
                        })
                        .collect::<Result<BTreeMap<String, String>>>()?,
                    None | Some(Json::Null) => BTreeMap::new(),
                    Some(_) => return Err(Error::invalid("field `attributes` must be an object")),
                };

                let meta = FileMeta {
                    min_role,
                    attributes,
                };
                store.set_meta(&path, &meta).await?;
                // Recomputed after the write, so the response reflects what now
                // applies rather than what was asked for — they differ whenever a
                // parent directory is more restrictive than the rule just set.
                let effective = effective_min_role(store.as_ref(), floor, &path).await?;
                Ok(HandlerResponse::ok(file_meta_json(&path, &meta, effective)))
            }
        }
    });

    // --- applications -------------------------------------------------------

    reg.register("listApplications", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let apps = list_applications(&catalog).await?;
                let out: Vec<Json> = apps.iter().map(application_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createApplication", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                // A create mints a fresh id; the body carries everything else.
                let app = application_from_body(AppId::new(), &ctx.body)?;
                save_application(&catalog, &app).await?;
                // A `react` app's project is the server's to create (§2.3): this
                // is the step that removes the SSH requirement, so it happens on
                // the first save rather than waiting for an admin to ask. It is
                // deliberately *not* fatal to the create — the row is already
                // saved and valid, and an unwritable store or an occupied
                // directory is a thing the admin fixes and re-tries, not a reason
                // to lose the application they just configured.
                let mut body = application_json(&app);
                let scaffold = scaffold_new_app(&catalog, &app).await;
                if let Some(obj) = body.as_object_mut() {
                    match &scaffold {
                        Ok(Some(report)) => {
                            obj.insert("scaffolded".to_owned(), json!(report.summary()));
                        }
                        Ok(None) => {}
                        Err(e) => {
                            obj.insert("scaffold_error".to_owned(), json!(e.causes()));
                        }
                    }
                }
                Ok(HandlerResponse::ok(body).with_status(201))
            }
        }
    });

    reg.register("updateApplication", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let id = parse_app_id(ctx.path_param("id")?)?;
                if load_application(&catalog, id).await?.is_none() {
                    return Err(Error::not_found(format!("no application with id {id}")));
                }
                // The id is the path's, not the body's — the row's identity is not
                // something a payload gets to reassign.
                let app = application_from_body(id, &ctx.body)?;
                save_application(&catalog, &app).await?;
                Ok(HandlerResponse::ok(application_json(&app)))
            }
        }
    });

    reg.register("deleteApplication", {
        let catalog = catalog.clone();
        let apps = apps.clone();
        move |ctx| {
            let catalog = catalog.clone();
            let apps = apps.clone();
            async move {
                let id = parse_app_id(ctx.path_param("id")?)?;
                // Load first so we know the subdomain to unmount — deleting the row
                // is the definition's end, unmounting is what stops it serving.
                let existing = load_application(&catalog, id).await?;
                let deleted = delete_application(&catalog, id).await?;
                if let Some(app) = &existing {
                    apps.unmount(&app.subdomain);
                }
                if !deleted {
                    return Err(Error::not_found(format!("no application with id {id}")));
                }
                Ok(HandlerResponse::ok(json!({ "deleted": true })))
            }
        }
    });

    reg.register("buildApplication", {
        let catalog = catalog.clone();
        let apps = apps.clone();
        move |ctx| {
            let catalog = catalog.clone();
            let apps = apps.clone();
            async move {
                let id = parse_app_id(ctx.path_param("id")?)?;
                let app = load_application(&catalog, id)
                    .await?
                    .ok_or_else(|| Error::not_found(format!("no application with id {id}")))?;
                // Build and mount live. A build failure propagates as an
                // Application error (§16) whose message is the bundler's own
                // diagnostics, and leaves any previously mounted version serving.
                let report = build_and_mount(&apps, app).await?;
                Ok(HandlerResponse::ok(json!({
                    "built": true,
                    "git_repo": report.git_repo,
                    "log": build_log(&report),
                })))
            }
        }
    });

    // --- frameworks ---------------------------------------------------------

    // Server-query options are resolved here, so the UI receives a concrete list
    // and needs no query evaluator of its own (§1.6). That is what let the
    // `store` setting become a pick-list without waiting for `ui/form-runtime`.
    reg.register("listFrameworks", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let mut out = Vec::new();
                // In registry order, which is itself editorial: the framework an
                // admin should take comes first (§2.2), and each carries the
                // label and sentence the picker shows — so the screen presents
                // two very different propositions while knowing neither (§2.4).
                for info in registered_framework_info() {
                    let spec =
                        resolve_options(&catalog, framework_config_spec(&info.name)?).await?;
                    out.push(json!({
                        "name": info.name,
                        "label": info.label,
                        "description": info.description,
                        "config_spec": spec.iter().map(form_field_json).collect::<Vec<_>>(),
                    }));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    // --- users --------------------------------------------------------------

    reg.register("listUsers", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let select = Select::from(Source::table(USERS_TABLE)).columns(vec![
                    Projection::expr(Expr::col(COL_ID)),
                    Projection::expr(Expr::col(COL_EMAIL)),
                    Projection::expr(Expr::col(COL_ROLE)),
                ]);
                let rows = catalog
                    .primary()
                    .query(&Statement::from(select))
                    .await?
                    .try_collect()
                    .await?;
                let mut out = Vec::with_capacity(rows.len());
                for row in &rows {
                    out.push(user_summary_json(&User::from_row(row)?));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let email = non_empty_str_field(obj, "email")?;
                let password = non_empty_str_field(obj, "password")?;
                let role = int_field(obj, "role")?;
                let role = u8::try_from(role)
                    .map_err(|_| Error::invalid(format!("role {role} is not in 1..=100")))?;
                let user = create_user(&catalog, email, password, role).await?;
                Ok(HandlerResponse::ok(user_summary_json(&user)).with_status(201))
            }
        }
    });

    reg
}

// --- request/response shaping --------------------------------------------------

/// A field (column) as `{ name, sql_type, nullable }`.
fn field_json(field: &DataField) -> Json {
    json!({
        "name": field.base.name,
        "sql_type": field.base.type_.sql_type(),
        "nullable": !field.required,
    })
}

// --- applications: wire shaping ------------------------------------------------

/// An [`Application`] as the API returns it (matching `application_schema`): the
/// id plus every field, with the nested framework/CSP/attributes as plain JSON.
fn application_json(app: &Application) -> Json {
    json!({
        "id": app.id.to_string(),
        "name": app.name,
        "description": app.description,
        "subdomain": app.subdomain,
        "framework": framework_ref_json(&app.framework),
        "extra_frameworks": app.extra_frameworks.iter().map(framework_ref_json).collect::<Vec<_>>(),
        "tables": app.tables.iter().map(|t| t.0.clone()).collect::<Vec<_>>(),
        "file_stores": app.file_stores.iter().map(|s| s.0.clone()).collect::<Vec<_>>(),
        "apis": app.apis.iter().map(|a| json!({ "provider": a.provider, "mount": a.mount })).collect::<Vec<_>>(),
        "static_dirs": app.static_dirs.iter().map(|d| json!({ "mount": d.mount, "store": d.store.0, "path": d.path })).collect::<Vec<_>>(),
        "csp": csp_json(&app.csp),
        "attributes": Json::Object(app.attributes.clone()),
        "source": app_source_json(app),
    })
}

/// Where the app's source lives, as `{ store, path }` — or `null` for a framework
/// with no source tree.
///
/// **Derived here rather than read off the config**, because how a framework
/// spells its source is the framework's business: `code` states it in `store` +
/// `source`, `react` derives it from `project`. Resolving it server-side is what
/// lets the admin UI link into the file manager at an app's source with no
/// per-framework code in the screen (§2.4). A config that does not resolve is not
/// an error here: this is a convenience field on a row that is being listed, and
/// the *reason* it does not resolve is reported where it belongs — on save, or on
/// build.
fn app_source_json(app: &Application) -> Json {
    match app_source_from_config(&app.framework) {
        Ok(source) => json!({
            "store": source.store.0,
            "path": source.build.source_dir,
        }),
        Err(_) => Json::Null,
    }
}

/// A [`FrameworkRef`] as `{ name, config }`.
fn framework_ref_json(fw: &FrameworkRef) -> Json {
    json!({ "name": fw.name, "config": Json::Object(fw.config.clone()) })
}

/// A [`CspPolicy`] as a directive→sources object.
fn csp_json(csp: &CspPolicy) -> Json {
    Json::Object(
        csp.directives
            .iter()
            .map(|(name, sources)| {
                (
                    name.clone(),
                    Json::Array(sources.iter().map(|s| Json::String(s.clone())).collect()),
                )
            })
            .collect(),
    )
}

/// Scaffold a newly created application's project, when it is one that has a
/// project to scaffold.
///
/// `Ok(None)` means "nothing to do" — the app uses a framework that brings its
/// own project (`code`), which is not a failure and should not be reported as
/// one. An `Err` is a real scaffold failure (unreachable store, occupied
/// directory) and is surfaced *alongside* the created application rather than
/// instead of it.
async fn scaffold_new_app(
    catalog: &Catalog,
    app: &Application,
) -> Result<Option<sc_app::ScaffoldReport>> {
    if require_scaffoldable(app).is_err() {
        return Ok(None);
    }
    scaffold_app(catalog, app).await.map(Some)
}

/// Parse an [`Application`] from a create/update body (matching
/// `application_input_schema`), carrying `id` — the body never sets the identity.
///
/// Missing collections default to empty and a missing `csp` to
/// [`CspPolicy::strict`], so the minimal body is `{ name, subdomain, framework }`.
/// Save-time validation (framework config against its spec) happens in
/// `save_application`, not here.
fn application_from_body(id: AppId, body: &Json) -> Result<Application> {
    let obj = require_object(body)?;
    let name = non_empty_str_field(obj, "name")?.to_owned();
    let subdomain = non_empty_str_field(obj, "subdomain")?.to_owned();
    let description = obj
        .get("description")
        .and_then(Json::as_str)
        .unwrap_or("")
        .to_owned();
    let framework = parse_framework(
        obj.get("framework")
            .ok_or_else(|| Error::invalid("missing field `framework`"))?,
    )?;
    let extra_frameworks = parse_array(obj, "extra_frameworks")?
        .iter()
        .map(parse_framework)
        .collect::<Result<_>>()?;
    let tables = parse_str_array(obj, "tables")?
        .into_iter()
        .map(TableId)
        .collect();
    let file_stores = parse_str_array(obj, "file_stores")?
        .into_iter()
        .map(FileStoreId)
        .collect();
    let apis = parse_array(obj, "apis")?
        .iter()
        .map(|v| {
            let o = require_object(v)?;
            Ok(ApiConfig::new(
                non_empty_str_field(o, "provider")?,
                str_field(o, "mount")?,
            ))
        })
        .collect::<Result<_>>()?;
    let static_dirs = parse_array(obj, "static_dirs")?
        .iter()
        .map(|v| {
            let o = require_object(v)?;
            Ok(StaticDir::new(
                str_field(o, "mount")?,
                FileStoreId(non_empty_str_field(o, "store")?.to_owned()),
                str_field(o, "path")?,
            ))
        })
        .collect::<Result<_>>()?;
    let csp = parse_csp(obj.get("csp"), &framework.name)?;
    let attributes = match obj.get("attributes") {
        None | Some(Json::Null) => Attrs::new(),
        Some(Json::Object(o)) => o.clone(),
        Some(_) => return Err(Error::invalid("`attributes` must be an object")),
    };

    Ok(Application {
        id,
        name,
        description,
        subdomain,
        framework,
        extra_frameworks,
        tables,
        file_stores,
        apis,
        static_dirs,
        csp,
        attributes,
    })
}

/// Parse a `{ name, config }` framework reference; a missing/null `config` is an
/// empty settings bag.
fn parse_framework(value: &Json) -> Result<FrameworkRef> {
    let obj = require_object(value)?;
    let name = non_empty_str_field(obj, "name")?.to_owned();
    let config = match obj.get("config") {
        None | Some(Json::Null) => Attrs::new(),
        Some(Json::Object(o)) => o.clone(),
        Some(_) => {
            return Err(Error::invalid(format!(
                "framework `{name}` config must be an object"
            )));
        }
    };
    Ok(FrameworkRef { name, config })
}

/// Parse a `csp` directive→sources object; absent means the framework's default
/// policy ([`framework_default_csp`]).
///
/// The default is the framework's rather than a fixed `strict` because a
/// framework that also chooses the build tooling knows what that tooling's output
/// needs — a scaffolded React app gets a policy fitted to a Vite bundle, and the
/// admin who is no longer picking the bundler is not asked to derive the policy
/// for it either. A stated `csp` always wins: this is a default, not a fixture.
fn parse_csp(value: Option<&Json>, framework: &str) -> Result<CspPolicy> {
    match value {
        None | Some(Json::Null) => Ok(framework_default_csp(framework)),
        Some(Json::Object(o)) => {
            let mut directives = BTreeMap::new();
            for (name, sources) in o {
                let Some(items) = sources.as_array() else {
                    return Err(Error::invalid(format!(
                        "csp directive `{name}` must be a list of sources"
                    )));
                };
                let sources = items
                    .iter()
                    .map(|s| {
                        s.as_str().map(str::to_owned).ok_or_else(|| {
                            Error::invalid(format!(
                                "csp directive `{name}` has a non-string source"
                            ))
                        })
                    })
                    .collect::<Result<_>>()?;
                directives.insert(name.clone(), sources);
            }
            Ok(CspPolicy { directives })
        }
        Some(_) => Err(Error::invalid("`csp` must be an object")),
    }
}

/// An optional JSON-array field, defaulting to empty when absent or null.
fn parse_array<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a [Json]> {
    match obj.get(key) {
        None | Some(Json::Null) => Ok(&[]),
        Some(Json::Array(items)) => Ok(items),
        Some(_) => Err(Error::invalid(format!("field `{key}` must be an array"))),
    }
}

/// An optional array-of-strings field (table / store subsets), defaulting empty.
fn parse_str_array(obj: &Map<String, Json>, key: &str) -> Result<Vec<String>> {
    parse_array(obj, key)?
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::to_owned)
                .ok_or_else(|| Error::invalid(format!("field `{key}` must be an array of strings")))
        })
        .collect()
}

/// Parse an application id from a path segment.
/// A file store as the API returns it (matching `file_store_schema`): its stored
/// definition plus the live state only the running server knows.
///
/// `connected`/`error`/`is_git_repo` are read from the catalog rather than the
/// row, because they are not properties of the definition: the same definition
/// is connected on one machine and not on another, and that difference is
/// exactly what the admin needs to see.
fn file_store_json(catalog: &Catalog, def: &FileStoreDef) -> Result<Json> {
    let connected = catalog.file_store(&def.name)?;
    Ok(json!({
        "id": Some(def.id.0),
        "name": def.name,
        "description": def.description,
        "backend": def.backend,
        "config": Json::Object(def.config.clone()),
        "min_role": def.min_role,
        "connected": connected.is_some(),
        // Only meaningful when not connected; a connected store has had any
        // recorded reason cleared, so this is null for a working store.
        "error": catalog.file_store_error(&def.name)?,
        // A property of the instance, so null when there is no instance to ask.
        "is_git_repo": connected.map(|store| store.is_git_repo()),
    }))
}

/// Resolve a store by name to its live handle **and** its store-wide `min_role`
/// floor (§1.1), which is the outermost entry on every path in it.
///
/// The floor comes from the stored definition, so a store connected by
/// `--file-store` — which has no definition — has no floor. That is correct
/// rather than a gap: an ephemeral developer store has no configured policy, and
/// inventing a restrictive default would break the workflow the flag exists for.
async fn resolve_store(
    catalog: &Catalog,
    name: &str,
) -> Result<(Arc<dyn sc_files::FileStore>, Option<u8>)> {
    let store = catalog.require_file_store(name)?;
    let floor = load_file_store_by_name(catalog, name)
        .await
        .ok()
        .flatten()
        .and_then(|def| def.min_role);
    Ok((store, floor))
}

/// The role of the caller, defaulting to public when unauthenticated.
///
/// **Currently always `1` in practice**, because every file endpoint is
/// `AuthRequirement::admin()` and an admin clears every rule. The check is wired
/// in regardless: it is correct by construction, it costs nothing, and it starts
/// doing real work the moment a non-admin role can reach a store — which is what
/// an application's file access will need. Enforcement living only in the future
/// caller would be the same mistake as the rule living only in a doc comment.
fn caller_role(ctx: &crate::handler::HandlerCtx) -> u8 {
    ctx.user
        .as_ref()
        .map_or(sc_files::ROLE_PUBLIC, |user| user.role)
}

/// A file's metadata as the API returns it (matching `file_meta_schema`).
///
/// Reports both the rule set on this entry and the `effective_min_role` that
/// actually applies — they differ whenever a parent directory or the store
/// itself is more restrictive, and showing only the former would let an admin
/// believe a file is reachable when its folder has locked it.
fn file_meta_json(path: &str, meta: &FileMeta, effective: Option<u8>) -> Json {
    json!({
        "path": path,
        "min_role": meta.min_role,
        "effective_min_role": effective,
        "attributes": meta
            .attributes
            .iter()
            .map(|(k, v)| (k.clone(), Json::String(v.clone())))
            .collect::<Map<String, Json>>(),
    })
}

/// An optional role field of a body: absent or null means unrestricted, and a
/// value outside the 1–100 scale is rejected rather than clamped.
fn optional_role(obj: &Map<String, Json>, key: &str) -> Result<Option<u8>> {
    match obj.get(key) {
        None | Some(Json::Null) => Ok(None),
        Some(value) => {
            let raw = value
                .as_i64()
                .ok_or_else(|| Error::invalid(format!("field `{key}` must be a number or null")))?;
            u8::try_from(raw)
                .ok()
                .filter(|r| (1..=100).contains(r))
                .ok_or_else(|| {
                    Error::invalid(format!(
                        "field `{key}` must be a role between 1 and 100, got {raw}"
                    ))
                })
                .map(Some)
        }
    }
}

/// The entry JSON returned after creating a directory.
fn directory_entry_json(path: &str) -> Json {
    json!({
        "name": path.trim_matches('/').rsplit('/').next().unwrap_or(path),
        "path": path.trim_matches('/'),
        "is_dir": true,
        "size": Json::Null,
    })
}

/// The [`Entry`] describing a rename's destination, so the response says where
/// the thing now is.
fn renamed_entry(to: &str) -> Entry {
    let path = to.trim_matches('/').to_owned();
    Entry {
        name: path.rsplit('/').next().unwrap_or(&path).to_owned(),
        path,
        is_dir: false,
        size: None,
    }
}

/// A connected store that has **no** stored definition — one supplied by
/// `--file-store` (§1.3), which is deliberately ephemeral and unpersisted.
///
/// Reported with a null id, which is what tells the admin UI there is nothing to
/// edit or delete: the store is real and browsable, but its existence ends with
/// the process unless the flag is passed again. It is listed rather than hidden
/// because a developer running with the flag would otherwise see an empty
/// file-stores screen and have no way to reach the store they just connected.
fn ephemeral_file_store_json(catalog: &Catalog, name: &str) -> Result<Json> {
    let store = catalog.require_file_store(name)?;
    Ok(json!({
        "id": Json::Null,
        "name": name,
        "description": "",
        // Named rather than left blank: the flag only ever makes local stores,
        // and the UI shows this next to the stored ones.
        "backend": sc_files::LOCAL_BACKEND,
        "config": json!({}),
        "min_role": Json::Null,
        // It is in the registry, so by construction it is connected.
        "connected": true,
        "error": Json::Null,
        "is_git_repo": Some(store.is_git_repo()),
    }))
}

/// Build a [`FileStoreDef`] from a create/update body, with `id` supplied by the
/// caller (minted on create, taken from the path on update).
///
/// The backend's settings are *not* validated here: `save_file_store` checks
/// them against the backend's declared spec, which is the single place that
/// knows how, and doing it twice would risk the two drifting.
fn file_store_from_body(id: FileStoreDefId, body: &Json) -> Result<FileStoreDef> {
    let obj = require_object(body)?;
    let name = non_empty_str_field(obj, "name")?.to_owned();
    let backend = non_empty_str_field(obj, "backend")?.to_owned();
    let description = obj
        .get("description")
        .and_then(Json::as_str)
        .unwrap_or("")
        .to_owned();
    let config = match obj.get("config") {
        Some(Json::Object(o)) => o.clone(),
        // A backend with no settings may be posted without a config at all.
        None | Some(Json::Null) => sc_types::Attrs::new(),
        Some(_) => return Err(Error::invalid("field `config` must be an object")),
    };
    // Absent or null means unrestricted. A value outside the role scale is
    // rejected rather than clamped — clamping would quietly change who can
    // reach the store, which is the opposite of what the admin asked for.
    let min_role = match obj.get("min_role") {
        None | Some(Json::Null) => None,
        Some(value) => {
            let raw = value
                .as_i64()
                .ok_or_else(|| Error::invalid("field `min_role` must be a number or null"))?;
            Some(
                u8::try_from(raw)
                    .ok()
                    .filter(|r| (1..=100).contains(r))
                    .ok_or_else(|| {
                        Error::invalid(format!(
                            "field `min_role` must be a role between 1 and 100, got {raw}"
                        ))
                    })?,
            )
        }
    };

    Ok(FileStoreDef {
        id,
        name,
        description,
        backend,
        config,
        min_role,
        attributes: sc_types::Attrs::new(),
    })
}

fn parse_file_store_id(raw: &str) -> Result<FileStoreDefId> {
    uuid::Uuid::parse_str(raw)
        .map(FileStoreDefId)
        .map_err(|_| Error::invalid(format!("`{raw}` is not a valid file store id")))
}

fn parse_app_id(raw: &str) -> Result<AppId> {
    uuid::Uuid::parse_str(raw)
        .map(AppId)
        .map_err(|_| Error::invalid(format!("`{raw}` is not a valid application id")))
}

/// The bundler's combined output, for the build log: stdout then stderr.
fn build_log(report: &sc_app::BuildReport) -> String {
    let mut log = String::new();
    // The first build of a scaffolded app is mostly the install, and an admin
    // watching a build that takes a minute needs to see why (§2.3).
    if let Some(install) = &report.install_log {
        log.push_str(install);
        if !log.is_empty() && !log.ends_with('\n') {
            log.push('\n');
        }
    }
    log.push_str(&report.stdout);
    if !report.stderr.is_empty() {
        if !log.is_empty() && !log.ends_with('\n') {
            log.push('\n');
        }
        log.push_str(&report.stderr);
    }
    log
}

/// A [`FormField`] as the API returns it (matching `form_field_schema`): enough
/// for the admin UI to render and label a control for it.
fn form_field_json(field: &FormField) -> Json {
    let type_name = field
        .base
        .type_
        .as_basic()
        .map(|b| b.name())
        .unwrap_or("text");
    json!({
        "name": field.base.name,
        "label": field.base.label,
        "type": type_name,
        "required": field.required,
        "default": field.default.clone().unwrap_or(Json::Null),
        "options": field.static_options(),
    })
}

/// A [`FileStore`](sc_files::FileStore) directory listing entry as JSON, matching
/// the API's `file_entry_schema` (`name`, `path`, `is_dir`, `size?`).
fn entry_json(entry: &Entry) -> Json {
    json!({
        "name": entry.name,
        "path": entry.path,
        "is_dir": entry.is_dir,
        "size": entry.size,
    })
}

/// The entry JSON returned after a successful `writeFile`: a file (never a
/// directory) at `path` with the byte count just written.
fn file_entry_written_json(path: &str, size: usize) -> Json {
    let name = path.rsplit('/').next().unwrap_or(path);
    json!({
        "name": name,
        "path": path,
        "is_dir": false,
        "size": size,
    })
}

/// Decode a `writeFile` body's contents: exactly one of `base64` (arbitrary
/// bytes) or `text` (UTF-8) must be present.
fn file_body_bytes(obj: &Map<String, Json>) -> Result<Bytes> {
    let base64 = obj.get("base64").and_then(Json::as_str);
    let text = obj.get("text").and_then(Json::as_str);
    match (base64, text) {
        (Some(_), Some(_)) => Err(Error::invalid(
            "provide either `base64` or `text`, not both",
        )),
        (Some(encoded), None) => BASE64
            .decode(encoded)
            .map(Bytes::from)
            .map_err(|e| Error::invalid(format!("invalid base64 in `base64`: {e}"))),
        (None, Some(text)) => Ok(Bytes::from(text.to_owned().into_bytes())),
        (None, None) => Err(Error::invalid(
            "missing file contents: set `base64` or `text`",
        )),
    }
}

// --- body accessors ------------------------------------------------------------

/// A required string field of an object body.
fn str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    obj.get(key)
        .and_then(Json::as_str)
        .ok_or_else(|| Error::invalid(format!("missing or non-string field `{key}`")))
}

/// A required, non-empty (after trimming) string field.
fn non_empty_str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    let value = str_field(obj, key)?;
    if value.trim().is_empty() {
        return Err(Error::invalid(format!("field `{key}` must not be empty")));
    }
    Ok(value)
}

/// A required boolean field of an object body.
fn bool_field(obj: &Map<String, Json>, key: &str) -> Result<bool> {
    obj.get(key)
        .and_then(Json::as_bool)
        .ok_or_else(|| Error::invalid(format!("missing or non-boolean field `{key}`")))
}

/// A required integer field of an object body.
fn int_field(obj: &Map<String, Json>, key: &str) -> Result<i64> {
    obj.get(key)
        .and_then(Json::as_i64)
        .ok_or_else(|| Error::invalid(format!("missing or non-integer field `{key}`")))
}
