//! The concrete admin-API handlers (technical design §13.1, §7).
//!
//! [`admin_handlers`] builds the [`HandlerRegistry`] that the admin
//! [`EndpointSet`](sc_api::admin_endpoints) dispatches against: one entry per
//! endpoint `name`, each closing over a shared [`Catalog`]. The handlers are the
//! server-side half of the typed API — bootstrap/auth, the table & field catalog,
//! row CRUD, and user management — and they stay free of HTTP plumbing: they read
//! a [`HandlerCtx`] and return a [`HandlerResponse`], deferring cookies/sessions
//! to the dispatcher via [`SessionAction`](crate::SessionAction).
//!
//! Data crosses the wire as plain JSON; [`crate::convert`] bridges it to the
//! query layer's [`Value`]. Row endpoints address a row by its single-column
//! primary key (composite keys are post-MVP), and `createTable` gives a new table
//! a default identity `id` key so the row editor has something to address.

use std::sync::Arc;

use sc_auth::{
    COL_EMAIL, COL_ID, COL_ROLE, USERS_TABLE, User, any_user_exists, authenticate_admin,
    create_first_user, create_user,
};
use sc_catalog::{Catalog, DataField, Table};
use sc_db::Row;
use sc_error::{Error, Result};
use sc_query::{
    Assignment, Delete, Expr, Insert, Projection, Select, Source, Statement, Update, Value,
};
use sc_types::TypeRef;
use serde_json::{Map, Value as Json, json};

use crate::convert::{json_to_value, value_to_json};
use crate::handler::{HandlerRegistry, HandlerResponse};

/// The SQL type of the default primary key `createTable` gives a new table: a
/// database-generated identity so rows can be inserted without supplying an id,
/// while still allowing an explicit one.
const DEFAULT_PK_SQL_TYPE: &str = "bigint generated by default as identity";

/// Build the registry of admin handlers over a shared [`Catalog`].
///
/// The names match the [`Endpoint`](sc_api::Endpoint) `name`s in
/// [`admin_endpoints`](sc_api::admin_endpoints); the router resolves each
/// endpoint's [`HandlerRef::Named`](sc_api::HandlerRef) here at dispatch time.
pub fn admin_handlers(catalog: Arc<Catalog>) -> HandlerRegistry {
    let mut reg = HandlerRegistry::new();

    // --- bootstrap & auth ---------------------------------------------------

    reg.register("authStatus", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let exists = any_user_exists(&catalog).await?;
                let current = ctx.user.as_ref().map_or(Json::Null, user_summary_json);
                Ok(HandlerResponse::ok(json!({
                    "any_user_exists": exists,
                    "current_user": current,
                })))
            }
        }
    });

    reg.register("createFirstUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                let user = create_first_user(&catalog, &email, &password).await?;
                // Log the new admin straight in — they came from the bootstrap
                // screen and expect to land in the app.
                let body = user_summary_json(&user);
                Ok(HandlerResponse::start_session(user, body))
            }
        }
    });

    reg.register("login", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                match authenticate_admin(&catalog, &email, &password).await? {
                    Some(user) => {
                        let body = user_summary_json(&user);
                        Ok(HandlerResponse::start_session(user, body))
                    }
                    None => Err(Error::auth("invalid credentials")),
                }
            }
        }
    });

    reg.register("logout", |_ctx| async {
        Ok(HandlerResponse::end_session(json!({ "ok": true })))
    });

    // --- catalog: tables & fields ------------------------------------------

    reg.register("listTables", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let tables = catalog.tables()?;
                let out: Vec<Json> = tables
                    .iter()
                    .filter(|t| !t.is_system())
                    .map(|t| json!({ "name": t.name }))
                    .collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createTable", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?;
                let id = DataField::plain("id", TypeRef::from_sql_type(DEFAULT_PK_SQL_TYPE))
                    .required()
                    .primary_key();
                let table = catalog.create_table(name, &[id]).await?;
                Ok(HandlerResponse::ok(json!({ "name": table.name })).with_status(201))
            }
        }
    });

    reg.register("listFields", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let out: Vec<Json> = table.fields.iter().map(field_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createField", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = ctx.path_param("table")?.to_owned();
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?.to_owned();
                let sql_type = non_empty_str_field(obj, "sql_type")?;
                let nullable = bool_field(obj, "nullable")?;
                let mut field = DataField::plain(&name, TypeRef::from_sql_type(sql_type));
                if !nullable {
                    field = field.required();
                }
                let table = catalog.create_field(&table, &field).await?;
                let created = table
                    .field(&name)
                    .ok_or_else(|| Error::msg(format!("field `{name}` missing after create")))?;
                Ok(HandlerResponse::ok(field_json(created)).with_status(201))
            }
        }
    });

    // --- row CRUD -----------------------------------------------------------

    reg.register("listRows", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let select = Select::from(Source::table(table.name.clone()))
                    .columns(vec![Projection::all()]);
                let rows = catalog
                    .provider(&table)
                    .query(&select)
                    .await?
                    .try_collect()
                    .await?;
                let out: Vec<Json> = rows.iter().map(row_to_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let obj = require_object(&ctx.body)?;
                let mut columns = Vec::with_capacity(obj.len());
                let mut values = Vec::with_capacity(obj.len());
                for (key, json) in obj {
                    let value = column_value(&table, key, json)?;
                    columns.push(key.clone());
                    values.push(Expr::lit(value));
                }
                if columns.is_empty() {
                    return Err(Error::invalid("no fields to insert"));
                }
                let insert = Insert::row(table.name.clone(), columns, values)
                    .returning(vec![Projection::all()]);
                let row = write_one(&catalog, &table, Statement::from(insert)).await?;
                Ok(HandlerResponse::ok(row_to_json(&row)).with_status(201))
            }
        }
    });

    reg.register("updateRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                let obj = require_object(&ctx.body)?;
                let pk = single_pk(&table)?;
                let mut assignments = Vec::with_capacity(obj.len());
                for (key, json) in obj {
                    // The primary key addresses the row; it is not reassignable
                    // through the body.
                    if key == &pk {
                        continue;
                    }
                    let value = column_value(&table, key, json)?;
                    assignments.push(Assignment::new(key.clone(), Expr::lit(value)));
                }
                if assignments.is_empty() {
                    return Err(Error::invalid("no fields to update"));
                }
                let update = Update {
                    table: table.name.clone(),
                    assignments,
                    filter: Some(pk_filter(&table, &pk, id)?),
                    returning: vec![Projection::all()],
                };
                let rows = write(&catalog, &table, Statement::from(update)).await?;
                let row = rows
                    .into_iter()
                    .next()
                    .ok_or_else(|| Error::not_found(format!("no row with {pk} = {id}")))?;
                Ok(HandlerResponse::ok(row_to_json(&row)))
            }
        }
    });

    reg.register("deleteRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                let pk = single_pk(&table)?;
                let delete = Delete {
                    table: table.name.clone(),
                    filter: Some(pk_filter(&table, &pk, id)?),
                    returning: vec![Projection::expr(Expr::col(pk.clone()))],
                };
                let rows = write(&catalog, &table, Statement::from(delete)).await?;
                if rows.is_empty() {
                    return Err(Error::not_found(format!("no row with {pk} = {id}")));
                }
                Ok(HandlerResponse::ok(json!({ "deleted": true })))
            }
        }
    });

    // --- users --------------------------------------------------------------

    reg.register("listUsers", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let select = Select::from(Source::table(USERS_TABLE)).columns(vec![
                    Projection::expr(Expr::col(COL_ID)),
                    Projection::expr(Expr::col(COL_EMAIL)),
                    Projection::expr(Expr::col(COL_ROLE)),
                ]);
                let rows = catalog
                    .primary()
                    .query(&Statement::from(select))
                    .await?
                    .try_collect()
                    .await?;
                let mut out = Vec::with_capacity(rows.len());
                for row in &rows {
                    out.push(user_summary_json(&User::from_row(row)?));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let email = non_empty_str_field(obj, "email")?;
                let password = non_empty_str_field(obj, "password")?;
                let role = int_field(obj, "role")?;
                let role = u8::try_from(role)
                    .map_err(|_| Error::invalid(format!("role {role} is not in 1..=100")))?;
                let user = create_user(&catalog, email, password, role).await?;
                Ok(HandlerResponse::ok(user_summary_json(&user)).with_status(201))
            }
        }
    });

    reg
}

// --- request/response shaping --------------------------------------------------

/// The public JSON view of a [`User`]: id, email, role (never the password hash).
fn user_summary_json(user: &User) -> Json {
    json!({
        "id": user.id.to_string(),
        "email": user.get(COL_EMAIL).and_then(Value::as_text).unwrap_or_default(),
        "role": i64::from(user.role),
    })
}

/// A field (column) as `{ name, sql_type, nullable }`.
fn field_json(field: &DataField) -> Json {
    json!({
        "name": field.base.name,
        "sql_type": field.base.type_.sql_type(),
        "nullable": !field.required,
    })
}

/// A row as a JSON object keyed by column name, values in natural JSON.
fn row_to_json(row: &Row) -> Json {
    let mut map = Map::with_capacity(row.len());
    for (name, value) in row.columns().iter().zip(row.values()) {
        map.insert(name.clone(), value_to_json(value));
    }
    Json::Object(map)
}

/// Coerce a JSON value for a named column of `table`, rejecting unknown columns.
fn column_value(table: &Table, column: &str, json: &Json) -> Result<Value> {
    let field = table
        .field(column)
        .ok_or_else(|| Error::invalid(format!("`{}` has no field `{column}`", table.name)))?;
    let basic = field
        .base
        .type_
        .as_basic()
        .ok_or_else(|| Error::invalid(format!("field `{column}` has no basic type")))?;
    json_to_value(basic, json)
}

/// The single primary-key column of `table`, or an error when the table has a
/// composite or absent key (row addressing needs exactly one — composite keys
/// are post-MVP).
fn single_pk(table: &Table) -> Result<String> {
    match table.primary_key.as_slice() {
        [pk] => Ok(pk.clone()),
        [] => Err(Error::invalid(format!(
            "table `{}` has no primary key to address rows by",
            table.name
        ))),
        _ => Err(Error::invalid(format!(
            "table `{}` has a composite primary key (unsupported for row addressing)",
            table.name
        ))),
    }
}

/// `pk = <id>`, coercing the path-parameter string to the key column's type.
fn pk_filter(table: &Table, pk: &str, id: &str) -> Result<Expr> {
    let value = column_value(table, pk, &Json::String(id.to_owned()))?;
    Ok(Expr::col(pk).eq(Expr::lit(value)))
}

/// Run a write statement against the table's provider, collecting `RETURNING` rows.
async fn write(catalog: &Catalog, table: &Table, statement: Statement) -> Result<Vec<Row>> {
    catalog
        .provider(table)
        .write(&statement)
        .await?
        .try_collect()
        .await
}

/// Run a write expected to return exactly one row (an insert with `RETURNING`).
async fn write_one(catalog: &Catalog, table: &Table, statement: Statement) -> Result<Row> {
    write(catalog, table, statement)
        .await?
        .into_iter()
        .next()
        .ok_or_else(|| Error::msg("write returned no row"))
}

// --- body accessors ------------------------------------------------------------

/// Email + password from a credentials body.
fn credentials(body: &Json) -> Result<(String, String)> {
    let obj = require_object(body)?;
    let email = non_empty_str_field(obj, "email")?.to_owned();
    let password = non_empty_str_field(obj, "password")?.to_owned();
    Ok((email, password))
}

/// The request body as a JSON object, or a `400`-mapped error.
fn require_object(body: &Json) -> Result<&Map<String, Json>> {
    body.as_object()
        .ok_or_else(|| Error::invalid("expected a JSON object body"))
}

/// A required string field of an object body.
fn str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    obj.get(key)
        .and_then(Json::as_str)
        .ok_or_else(|| Error::invalid(format!("missing or non-string field `{key}`")))
}

/// A required, non-empty (after trimming) string field.
fn non_empty_str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    let value = str_field(obj, key)?;
    if value.trim().is_empty() {
        return Err(Error::invalid(format!("field `{key}` must not be empty")));
    }
    Ok(value)
}

/// A required boolean field of an object body.
fn bool_field(obj: &Map<String, Json>, key: &str) -> Result<bool> {
    obj.get(key)
        .and_then(Json::as_bool)
        .ok_or_else(|| Error::invalid(format!("missing or non-boolean field `{key}`")))
}

/// A required integer field of an object body.
fn int_field(obj: &Map<String, Json>, key: &str) -> Result<i64> {
    obj.get(key)
        .and_then(Json::as_i64)
        .ok_or_else(|| Error::invalid(format!("missing or non-integer field `{key}`")))
}
