//! The concrete admin-API handlers (technical design §13.1, §7).
//!
//! [`admin_handlers`] builds the [`HandlerRegistry`] that the admin
//! [`EndpointSet`](sc_api::admin_endpoints) dispatches against: one entry per
//! endpoint `name`, each closing over a shared [`Catalog`]. The handlers are the
//! server-side half of the typed API — bootstrap/auth, the table & field catalog,
//! row CRUD, and user management — and they stay free of HTTP plumbing: they read
//! a [`HandlerCtx`] and return a [`HandlerResponse`], deferring cookies/sessions
//! to the dispatcher via [`SessionAction`](crate::SessionAction).
//!
//! Data crosses the wire as plain JSON. The row endpoints are thin wrappers over
//! [`sc_api::rows`], the shared row-CRUD layer an application's REST API runs
//! too — the admin API is not a privileged special case, it is the same
//! machinery (design §13.1). A row is addressed by its single-column primary key
//! (composite keys are post-MVP), and `createTable` gives a new table a default
//! identity `id` key so the row editor has something to address.

use std::sync::Arc;

use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use bytes::Bytes;
use sc_auth::{
    COL_EMAIL, COL_ID, COL_ROLE, USERS_TABLE, User, any_user_exists, authenticate_admin,
    create_first_user, create_user,
};
use sc_api::rows::{self, require_object};
use sc_catalog::{Catalog, DataField};
use sc_error::{Error, Result};
use sc_files::Entry;
use sc_query::{Expr, Projection, Select, Source, Statement, Value};
use sc_types::TypeRef;
use serde_json::{Map, Value as Json, json};

use crate::handler::{HandlerRegistry, HandlerResponse};

/// The SQL type of the default primary key `createTable` gives a new table: a
/// database-generated identity so rows can be inserted without supplying an id,
/// while still allowing an explicit one.
const DEFAULT_PK_SQL_TYPE: &str = "bigint generated by default as identity";

/// Build the registry of admin handlers over a shared [`Catalog`].
///
/// The names match the [`Endpoint`](sc_api::Endpoint) `name`s in
/// [`admin_endpoints`](sc_api::admin_endpoints); the router resolves each
/// endpoint's [`HandlerRef::Named`](sc_api::HandlerRef) here at dispatch time.
pub fn admin_handlers(catalog: Arc<Catalog>) -> HandlerRegistry {
    let mut reg = HandlerRegistry::new();

    // --- bootstrap & auth ---------------------------------------------------

    reg.register("authStatus", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let exists = any_user_exists(&catalog).await?;
                let current = ctx.user.as_ref().map_or(Json::Null, user_summary_json);
                Ok(HandlerResponse::ok(json!({
                    "any_user_exists": exists,
                    "current_user": current,
                })))
            }
        }
    });

    reg.register("createFirstUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                let user = create_first_user(&catalog, &email, &password).await?;
                // Log the new admin straight in — they came from the bootstrap
                // screen and expect to land in the app.
                let body = user_summary_json(&user);
                Ok(HandlerResponse::start_session(user, body))
            }
        }
    });

    reg.register("login", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let (email, password) = credentials(&ctx.body)?;
                match authenticate_admin(&catalog, &email, &password).await? {
                    Some(user) => {
                        let body = user_summary_json(&user);
                        Ok(HandlerResponse::start_session(user, body))
                    }
                    None => Err(Error::auth("invalid credentials")),
                }
            }
        }
    });

    reg.register("logout", |_ctx| async {
        Ok(HandlerResponse::end_session(json!({ "ok": true })))
    });

    // --- catalog: tables & fields ------------------------------------------

    reg.register("listTables", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let tables = catalog.tables()?;
                let out: Vec<Json> = tables
                    .iter()
                    .filter(|t| !t.is_system())
                    .map(|t| json!({ "name": t.name }))
                    .collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createTable", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?;
                let id = DataField::plain("id", TypeRef::from_sql_type(DEFAULT_PK_SQL_TYPE))
                    .required()
                    .primary_key();
                let table = catalog.create_table(name, &[id]).await?;
                Ok(HandlerResponse::ok(json!({ "name": table.name })).with_status(201))
            }
        }
    });

    reg.register("listFields", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let out: Vec<Json> = table.fields.iter().map(field_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createField", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = ctx.path_param("table")?.to_owned();
                let obj = require_object(&ctx.body)?;
                let name = non_empty_str_field(obj, "name")?.to_owned();
                let sql_type = non_empty_str_field(obj, "sql_type")?;
                let nullable = bool_field(obj, "nullable")?;
                let mut field = DataField::plain(&name, TypeRef::from_sql_type(sql_type));
                if !nullable {
                    field = field.required();
                }
                let table = catalog.create_field(&table, &field).await?;
                let created = table
                    .field(&name)
                    .ok_or_else(|| Error::msg(format!("field `{name}` missing after create")))?;
                Ok(HandlerResponse::ok(field_json(created)).with_status(201))
            }
        }
    });

    // --- row CRUD -----------------------------------------------------------

    reg.register("listRows", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                Ok(HandlerResponse::ok(rows::list_rows(&catalog, &table).await?))
            }
        }
    });

    reg.register("createRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let row = rows::create_row(&catalog, &table, &ctx.body).await?;
                Ok(HandlerResponse::ok(row).with_status(201))
            }
        }
    });

    reg.register("updateRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                let row = rows::update_row(&catalog, &table, id, &ctx.body).await?;
                Ok(HandlerResponse::ok(row))
            }
        }
    });

    reg.register("deleteRow", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let table = catalog.require(ctx.path_param("table")?)?;
                let id = ctx.path_param("id")?;
                Ok(HandlerResponse::ok(
                    rows::delete_row(&catalog, &table, id).await?,
                ))
            }
        }
    });

    // --- files (file manager) ----------------------------------------------

    reg.register("listFileStores", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let mut out = Vec::new();
                for name in catalog.file_store_names()? {
                    let store = catalog.require_file_store(&name)?;
                    out.push(json!({
                        "name": name,
                        "is_git_repo": store.is_git_repo(),
                    }));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("browseFiles", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let store = catalog.require_file_store(ctx.path_param("store")?)?;
                let obj = require_object(&ctx.body)?;
                // `dir` is optional-ish: an absent/empty value lists the root.
                let dir = obj.get("dir").and_then(Json::as_str).unwrap_or("");
                let entries = store.list(dir).await?;
                let out: Vec<Json> = entries.iter().map(entry_json).collect();
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("readFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let store = catalog.require_file_store(ctx.path_param("store")?)?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?;
                let bytes = store.read(path).await?;
                // Always provide base64 (for binary download); add a decoded
                // `text` when the bytes are valid UTF-8 (for the text editor).
                let text = std::str::from_utf8(&bytes)
                    .ok()
                    .map(|s| Json::String(s.to_owned()))
                    .unwrap_or(Json::Null);
                Ok(HandlerResponse::ok(json!({
                    "path": path,
                    "size": bytes.len(),
                    "base64": BASE64.encode(&bytes),
                    "text": text,
                })))
            }
        }
    });

    reg.register("writeFile", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let store = catalog.require_file_store(ctx.path_param("store")?)?;
                let obj = require_object(&ctx.body)?;
                let path = non_empty_str_field(obj, "path")?.to_owned();
                let data = file_body_bytes(obj)?;
                let size = data.len();
                store.write(&path, data).await?;
                Ok(HandlerResponse::ok(file_entry_written_json(&path, size)).with_status(201))
            }
        }
    });

    // --- users --------------------------------------------------------------

    reg.register("listUsers", {
        let catalog = catalog.clone();
        move |_ctx| {
            let catalog = catalog.clone();
            async move {
                let select = Select::from(Source::table(USERS_TABLE)).columns(vec![
                    Projection::expr(Expr::col(COL_ID)),
                    Projection::expr(Expr::col(COL_EMAIL)),
                    Projection::expr(Expr::col(COL_ROLE)),
                ]);
                let rows = catalog
                    .primary()
                    .query(&Statement::from(select))
                    .await?
                    .try_collect()
                    .await?;
                let mut out = Vec::with_capacity(rows.len());
                for row in &rows {
                    out.push(user_summary_json(&User::from_row(row)?));
                }
                Ok(HandlerResponse::ok(Json::Array(out)))
            }
        }
    });

    reg.register("createUser", {
        let catalog = catalog.clone();
        move |ctx| {
            let catalog = catalog.clone();
            async move {
                let obj = require_object(&ctx.body)?;
                let email = non_empty_str_field(obj, "email")?;
                let password = non_empty_str_field(obj, "password")?;
                let role = int_field(obj, "role")?;
                let role = u8::try_from(role)
                    .map_err(|_| Error::invalid(format!("role {role} is not in 1..=100")))?;
                let user = create_user(&catalog, email, password, role).await?;
                Ok(HandlerResponse::ok(user_summary_json(&user)).with_status(201))
            }
        }
    });

    reg
}

// --- request/response shaping --------------------------------------------------

/// The public JSON view of a [`User`]: id, email, role (never the password hash).
fn user_summary_json(user: &User) -> Json {
    json!({
        "id": user.id.to_string(),
        "email": user.get(COL_EMAIL).and_then(Value::as_text).unwrap_or_default(),
        "role": i64::from(user.role),
    })
}

/// A field (column) as `{ name, sql_type, nullable }`.
fn field_json(field: &DataField) -> Json {
    json!({
        "name": field.base.name,
        "sql_type": field.base.type_.sql_type(),
        "nullable": !field.required,
    })
}

/// A [`FileStore`](sc_files::FileStore) directory listing entry as JSON, matching
/// the API's `file_entry_schema` (`name`, `path`, `is_dir`, `size?`).
fn entry_json(entry: &Entry) -> Json {
    json!({
        "name": entry.name,
        "path": entry.path,
        "is_dir": entry.is_dir,
        "size": entry.size,
    })
}

/// The entry JSON returned after a successful `writeFile`: a file (never a
/// directory) at `path` with the byte count just written.
fn file_entry_written_json(path: &str, size: usize) -> Json {
    let name = path.rsplit('/').next().unwrap_or(path);
    json!({
        "name": name,
        "path": path,
        "is_dir": false,
        "size": size,
    })
}

/// Decode a `writeFile` body's contents: exactly one of `base64` (arbitrary
/// bytes) or `text` (UTF-8) must be present.
fn file_body_bytes(obj: &Map<String, Json>) -> Result<Bytes> {
    let base64 = obj.get("base64").and_then(Json::as_str);
    let text = obj.get("text").and_then(Json::as_str);
    match (base64, text) {
        (Some(_), Some(_)) => Err(Error::invalid(
            "provide either `base64` or `text`, not both",
        )),
        (Some(encoded), None) => BASE64
            .decode(encoded)
            .map(Bytes::from)
            .map_err(|e| Error::invalid(format!("invalid base64 in `base64`: {e}"))),
        (None, Some(text)) => Ok(Bytes::from(text.to_owned().into_bytes())),
        (None, None) => Err(Error::invalid(
            "missing file contents: set `base64` or `text`",
        )),
    }
}

// --- body accessors ------------------------------------------------------------

/// Email + password from a credentials body.
fn credentials(body: &Json) -> Result<(String, String)> {
    let obj = require_object(body)?;
    let email = non_empty_str_field(obj, "email")?.to_owned();
    let password = non_empty_str_field(obj, "password")?.to_owned();
    Ok((email, password))
}

/// A required string field of an object body.
fn str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    obj.get(key)
        .and_then(Json::as_str)
        .ok_or_else(|| Error::invalid(format!("missing or non-string field `{key}`")))
}

/// A required, non-empty (after trimming) string field.
fn non_empty_str_field<'a>(obj: &'a Map<String, Json>, key: &str) -> Result<&'a str> {
    let value = str_field(obj, key)?;
    if value.trim().is_empty() {
        return Err(Error::invalid(format!("field `{key}` must not be empty")));
    }
    Ok(value)
}

/// A required boolean field of an object body.
fn bool_field(obj: &Map<String, Json>, key: &str) -> Result<bool> {
    obj.get(key)
        .and_then(Json::as_bool)
        .ok_or_else(|| Error::invalid(format!("missing or non-boolean field `{key}`")))
}

/// A required integer field of an object body.
fn int_field(obj: &Map<String, Json>, key: &str) -> Result<i64> {
    obj.get(key)
        .and_then(Json::as_i64)
        .ok_or_else(|| Error::invalid(format!("missing or non-integer field `{key}`")))
}
